Repository rocq-prover/rocq, pull requests merged in 2018-07, with the labels that each got.

#7759 Workaround to fix #7731 (printing not splitting line at break hint).
  test-suite/output/Notations3.out
  test-suite/output/Notations3.v
  vernac/metasyntax.ml
Labels: kind: fix, part: notations

#7760 Fixes #7712 (an anomaly in reporting bad recursive notation format).
  test-suite/bugs/closed/7712.v
  vernac/metasyntax.ml
Labels: kind: anomaly, kind: fix, part: notations

#7964 Document that GITURL variables shouldn't have a trailing .git anymore.
  dev/ci/user-overlays/07863-rm-sorts-contents.sh
  dev/ci/user-overlays/07906-univs-of-constr.sh
  dev/ci/user-overlays/7080-herbelin-master+swapping-modules-constr-context.sh
  dev/ci/user-overlays/README.md
Labels: kind: documentation

#7961 [api] Fix wrong deprecation warning (#7915)
  vernac/misctypes.ml
Labels: kind: fix

#7965 doc: Fix typesetting in Gallina extensions
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation, kind: fix

#7969 doc: typesetting and hyperlinks in Syntax Extensions
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, kind: fix

#7977 allow `make check` to succeed when -prefix is given to ./configure and make install not run yet
  lib/envars.ml
Labels: kind: infrastructure

#7974 Fix default.nix following a package renaming.
  default.nix
Labels: kind: fix, kind: infrastructure

#7942 Extend readme with 'beginners guide'
  CONTRIBUTING.md
  dev/README
  dev/README.md
  dev/doc/README.md
  dev/doc/setup.txt
  dev/doc/translate.txt
Labels: kind: documentation

#7607 Simplify reification of predicate in bytecode and native compilers
  pretyping/nativenorm.ml
  pretyping/vnorm.ml
Labels: kind: cleanup, part: elaboration

#7978 [ci] [docker] Make sure we don't install optional packages with apt.
  .circleci/config.yml
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: fix, kind: infrastructure

#7992 Print something after the build completed if it wasn't a runner failure.
  .gitlab-ci.yml
Labels: kind: infrastructure

#7989 [ci] Avoid annoying detached head warning.
  dev/ci/ci-common.sh
Labels: kind: infrastructure

#7994 Make bin/ in makefile, not configure.
  Makefile
  configure.ml
Labels: kind: infrastructure, part: build

#7991 Make Travis faster by removing more builds.
  .travis.yml
Labels: kind: infrastructure

#7990 Convert timing tool to python3
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/002-single-file-sorting/time-of-build-pretty.log.expected
  tools/CoqMakefile.in
  tools/TimeFileMaker.py
  tools/make-both-single-timing-files.py
  tools/make-both-time-files.py
  tools/make-one-time-file.py
Labels: kind: enhancement, part: tools

#8008 Add test for #8004.
  test-suite/bugs/closed/8004.v
Labels: kind: infrastructure, part: test-suite, part: universes

#7821 [refine] obey the use_unification_heuristics flag
  plugins/ltac/extratactics.ml4
  proofs/pfedit.mli
Labels: kind: enhancement

#8005 Fix compilation of Coq with camlp5 master branch.
  grammar/coqpp_main.ml
  parsing/pcoq.ml
  parsing/pcoq.mli
Labels: kind: fix

#7921 Archive the `gallina` tool
  .gitignore
  CHANGES
  Makefile.build
  Makefile.common
  Makefile.install
  configure.ml
  doc/sphinx/practical-tools/utilities.rst
  man/gallina.1
  tools/CoqMakefile.in
  tools/gallina.ml
  tools/gallina_lexer.mll
Labels: kind: cleanup

#8020 Modify URLs in xml-protocol.md
  dev/doc/xml-protocol.md
Labels: kind: documentation, kind: fix

#7985 Remove letouzey from CODEOWNERS since he left the Coq organization.
  .github/CODEOWNERS
Labels: kind: infrastructure

#8015 Output UTF-8 explicitly in timing tools
  tools/CoqMakefile.in
  tools/TimeFileMaker.py
Labels: kind: fix, kind: infrastructure, part: tools

#7884 Fix #5719: Uncaught exception Invalid_argument.
  pretyping/cases.ml
  test-suite/bugs/closed/5719.v
Labels: kind: fix

#8025 Fix rst syntax for `quote ident {ident}`
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation, kind: fix

#7983 Turn a dead branch into an assertion failure in VM reification.
  pretyping/vnorm.ml
Labels: kind: cleanup

#7899 My recent improvements to the backport script.
  dev/tools/backport-pr.sh
Labels: kind: infrastructure

#8034 [travis] Try to workaround the repeated APT failures by using Jason Gross's suggestion.
  .travis.yml
Labels: kind: infrastructure

#8036 [travis] Remove even more jobs.
  .travis.yml
Labels: kind: infrastructure

#8031 Remove auto-retry in GitLab CI now that @coqbot is handling it.
  .gitlab-ci.yml
Labels: kind: infrastructure

#8002 make-both-single-timing-files: fix --sort-by=diff
  tools/TimeFileMaker.py
Labels: kind: fix, part: tools

#8021 Get rid of horrendous hack limiting the size of parsed integers
  parsing/g_prim.mlg
Labels: kind: cleanup

#8035 Fix #8033: Tactic assert-suceeds has a typo in its name in the manual
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation, kind: fix

#7998 [coqpp] Move to its own directory.
  .gitignore
  Makefile.build
  Makefile.common
  coqpp/coqpp_ast.mli
  coqpp/coqpp_lex.mll
  coqpp/coqpp_main.ml
  coqpp/coqpp_parse.mly
Labels: kind: infrastructure

#7871 [ci] Upgrade edge OCaml to 4.07.0 and Dune to 1.0.0
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  INSTALL
  dev/build/windows/makecoq_mingw.sh
  dev/ci/appveyor.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/doc/README.md
Labels: kind: infrastructure

#8051 Clean-up user-overlays folder.
  dev/ci/user-overlays/07746-cleanup-unused-various.sh
  dev/ci/user-overlays/07820-mattam82-hints-constants.sh
  dev/ci/user-overlays/07898-ppedrot-rm-campl4-remains.sh
  dev/ci/user-overlays/07902-ppedrot-camlp5-parser.sh
Labels: kind: cleanup

#7907 Tactic deprecation machinery
  CHANGES
  doc/sphinx/language/gallina-specification-language.rst
  grammar/tacextend.mlp
  plugins/ltac/g_ltac.ml4
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ltac/tacenv.ml
  plugins/ltac/tacenv.mli
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  test-suite/output/Deprecation.out
  test-suite/output/Deprecation.v
  test-suite/success/LtacDeprecation.v
Labels: kind: feature, part: tactics

#6930 Make -warn-error fail on warnings emitted by coqc on stdlib.
  Makefile.build
  configure.ml
Labels: kind: infrastructure

#8057 Fixed typos, wording and grammar errors in the Preamble of the Reference Manual (Introduction, Credits).
  doc/sphinx/credits.rst
  doc/sphinx/introduction.rst
Labels: kind: documentation, kind: fix

#8066 [ltac] Remove unused functions.
  kernel/retroknowledge.ml
  kernel/retroknowledge.mli
  plugins/ltac/extraargs.ml4
Labels: kind: cleanup

#8069 Only check overlay extensions on git-tracked files
  dev/tools/check-overlays.sh
Labels: kind: enhancement, kind: infrastructure

#8060 Remove useless libobject in proof_using
  vernac/proof_using.ml
Labels: kind: cleanup

#8068 [build] Build Coq and plugins with `-strict-sequence`
  configure.ml
  ide/gtk_parsing.ml
  interp/constrintern.ml
  plugins/funind/recdef.mli
  plugins/micromega/mutils.mli
Labels: kind: cleanup

#7897 Remove fourier plugin
  .github/CODEOWNERS
  CHANGES
  CREDITS
  META.coq
  Makefile.common
  Makefile.dev
  dev/ocamldebug-coq.run
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/proof-engine/tactics.rst
  ide/MacOS/default_accel_map
  ide/coq_commands.ml
  plugins/fourier/Fourier.v
  plugins/fourier/Fourier_util.v
  plugins/fourier/fourier.ml
  plugins/fourier/fourierR.ml
  plugins/fourier/fourier_plugin.mlpack
  plugins/fourier/g_fourier.mlg
  plugins/micromega/Fourier.v
  plugins/micromega/Fourier_util.v
  test-suite/success/LraTest.v
  theories/Reals/Machin.v
  theories/Reals/PSeries_reg.v
  theories/Reals/R_sqrt.v
  theories/Reals/Ranalysis5.v
  theories/Reals/Ratan.v
  theories/Reals/Rbasic_fun.v
  theories/Reals/Rderiv.v
  theories/Reals/Reals.v
  theories/Reals/Rlimit.v
  theories/Reals/Rpower.v
  theories/Reals/Rtrigo.v
  theories/Reals/Rtrigo1.v
  theories/Reals/Rtrigo_calc.v
  tools/coqdoc/output.ml
Labels: kind: cleanup

#8054 [dev] Autogenerate OCaml dev files.
  .github/CODEOWNERS
  .gitignore
  .merlin.in
  META.coq.in
  Makefile
  Makefile.build
  Makefile.dev
  dev/tools/coqdev.el
  ide/.merlin.in
  plugins/.merlin.in
  test-suite/unit-tests/.merlin.in
Labels: kind: infrastructure

#8089 Remove declare_object for SsrHave NoTCResolution.
  CHANGES
  plugins/ssr/ssrfwd.ml
Labels: kind: cleanup

#8037 Export a function to apply toplevel tactic values in Tacinterp.
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacinterp.mli
  plugins/setoid_ring/newring.ml
Labels: kind: enhancement

#8086 Improved chapter 'The tactic language' of the Reference Manual.
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation

#8095 Improvements for the chapter 'Detailed examples of tactics' of the Reference Manual.
  doc/sphinx/proof-engine/detailed-tactic-examples.rst
Labels: kind: documentation

#6597 Binary, Octal, and Hex conversions between [positive], [Z], [N], [nat] and [string]
  CHANGES
  doc/stdlib/index-list.html.template
  theories/Strings/BinaryString.v
  theories/Strings/HexString.v
  theories/Strings/OctalString.v
Labels: kind: enhancement, part: standard library

#8000 Fix #7854: Native compilation + flambda trigger SEGFAULT.
  kernel/nativevalues.ml
  test-suite/bugs/closed/7854.v
Labels: kind: fix

#8083 Add test for repeated section with same name
  CHANGES
  doc/sphinx/language/gallina-extensions.rst
  test-suite/bugs/closed/8081.v
Labels: kind: documentation

#8040 [ci] Enable native compiler in `egde:flambda` build.
  .gitlab-ci.yml
  .travis.yml
Labels: kind: infrastructure

#8139 Replace all the CoInductives with Variants in the SSR plugin
  plugins/ssr/ssrbool.v
  plugins/ssr/ssreflect.v
  plugins/ssr/ssrfun.v
Labels: kind: cleanup

#7889 Cleanup reduction effects: they only work on constants.
  pretyping/cbv.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/tacred.ml
Labels: kind: cleanup

#734 [travis] Also run coqchk on HoTT
  dev/ci/ci-hott.sh
Labels: kind: infrastructure

#8133 Fixes #8126: issue with notations and nested applications
  interp/constrintern.ml
  test-suite/bugs/closed/8126.v
  test-suite/output/Notations3.out
  test-suite/output/Notations3.v
Labels: kind: fix

#8150 Fix static declaration of plugins in coqpp.
  coqpp/coqpp_main.ml
Labels: kind: fix

#7274 Avoiding introducing dependency on the indices of a term which has no matching clauses.
  pretyping/cases.ml
  test-suite/bugs/closed/2733.v
Labels: kind: enhancement, kind: fix, part: elaboration

#8084 Properly disable native compilation when -native-compiler is unset.
  kernel/nativeconv.ml
  kernel/nativelib.ml
Labels: kind: fix

#7786 In "redundant clause" pattern-matching error, show also the pattern (closes #7777)
  test-suite/output/Cases.out
  test-suite/output/Cases.v
  vernac/himsg.ml
Labels: kind: enhancement, kind: user messages, part: elaboration

#8101 Remove ClosedModule and ClosedSection from libstack
  library/lib.ml
  library/lib.mli
  printing/prettyp.ml
Labels: kind: cleanup

#8166 Fix Search query in CoqIDE.
  ide/coqide.ml
Labels: kind: fix

#8164 Add information to option type errors
  library/goptions.ml
  test-suite/output/BadOptionValueType.out
  test-suite/output/BadOptionValueType.v
Labels: kind: user messages

#8173 Missing backslash in a documentation file.
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation, kind: fix

#8174 [ci] Remove CircleCI setup.
  .circleci/config.yml
  .github/CODEOWNERS
  README.md
  dev/ci/README.md
  dev/ci/ci-common.sh
  test-suite/Makefile
Labels: kind: infrastructure

#8148 Doc: preliminary work before #7291 which add an "Unable to unify" message
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#8160 Improved chapters 'Implicit Coercions' and 'Canonical Structures' of the Reference Manual.
  doc/sphinx/addendum/canonical-structures.rst
  doc/sphinx/addendum/implicit-coercions.rst
Labels: kind: documentation

#8137 Fix 8132. Print the content of body, not its type.
  CHANGES
  printing/printer.ml
  printing/proof_diffs.ml
  printing/proof_diffs.mli
Labels: kind: fix

#8113 Make universe object Dispose
  interp/declare.ml
Labels: kind: cleanup, part: universes
