Repository rocq-prover/rocq, pull requests merged in 2018-11, with the labels that each got.

#8845 Fix typos in the document about CIC
  doc/sphinx/language/cic.rst
Labels: kind: documentation, kind: fix

#8809 [dev doc] Update proof engine docs, fixes #6640
  dev/doc/proof-engine.md
Labels: kind: documentation, kind: fix

#8834 [error printing] Fix improper grounding of open terms in printing.
  engine/eConstr.ml
  engine/eConstr.mli
  vernac/himsg.ml
Labels: kind: fix

#8877 Fix #8876: expected number of arguments for cumulative constructors
  checker/reduction.ml
  test-suite/coqchk/bug_8876.v
Labels: kind: fix, part: checker, part: universes

#8836 [default.nix] Add coq-version and setupHook.
  default.nix
Labels: kind: infrastructure

#8857 [library] Better sizing for libobject hashtbl.
  library/libobject.ml
Labels: kind: cleanup

#8882 Fix #8881: validate fails to use inductive equivalence in case_info
  checker/inductive.ml
  test-suite/coqchk/bug_8881.v
Labels: kind: fix, part: checker, part: modules

#8824 Do not check convertibility of pattern types in the kernel
  clib/cArray.ml
  clib/cArray.mli
  kernel/reduction.ml
Labels: kind: performance, part: kernel

#8896 Expose Typing.judge_of_apply
  pretyping/typing.mli
Labels: kind: enhancement

#7952 Fix an algorithmic issue in the vernac guardedness checker.
  pretyping/inductiveops.ml
Labels: kind: fix, kind: performance

#8899 Remove the deprecated Token module and port the corresponding code.
  gramlib/token.ml
  gramlib/token.mli
  parsing/cLexer.ml
  toplevel/coqloop.ml
  vernac/explainErr.ml
Labels: kind: cleanup

#8884 Improve rendering of the credits.
  doc/sphinx/credits.rst
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation, kind: fix

#8903 [dune] Add to vo rules explicit location of coqlib in boot mode.
  tools/coq_dune.ml
Labels: kind: infrastructure

#8912 [dune] [coqide] Use copy action instead of (run cp ...)
  ide/dune
Labels: kind: infrastructure

#8926 Move features that were not backported to 8.9 to the 8.10 section of CHANGES.md.
  CHANGES.md
Labels: kind: documentation, kind: fix

#8868 [Docker] Update OCaml (4.07.1) and camlp5 (7.07-almost)
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/dune-workspace.all
Labels: kind: infrastructure

#8918 Fix overlays on Windows CI
  dev/build/windows/makecoq_mingw.sh
Labels: kind: fix, kind: infrastructure

#8927 Optimise git cloning
  .gitlab-ci.yml
Labels: kind: infrastructure

#8901 [dune] Add "quick" and "check" targets for fast builds.
  Makefile.dune
Labels: kind: infrastructure

#8928 Fixes #8910: typo in nameops.ml
  engine/nameops.ml
Labels: kind: documentation, kind: fix

#8098 Update/improve two aspects of the merging process.
  dev/doc/MERGING.md
Labels: kind: documentation, kind: meta

#8944 Revert PR #8923 (require camlp5 >=7.06)
  .gitlab-ci.yml
  INSTALL
  configure.ml
  coq.opam
  dev/ci/docker/bionic_coq/Dockerfile
  parsing/pcoq.ml
Labels: kind: fix

#8947 Ensure termination of `file_exists_respecting_case`
  lib/system.ml
Labels: kind: fix

#8820 Standardize handling of Automatic Introduction.
  CHANGES.md
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/bugs/closed/bug_8791.v
  vernac/classes.ml
  vernac/lemmas.ml
Labels: kind: fix

#8956 Fix dune runtest invocation
  Makefile.dune
Labels: kind: fix, kind: infrastructure

#8949 Remove checker printers
  Makefile.checker
  Makefile.dev
  Makefile.dune
  dev/checker.dbg
  dev/checker_db
  dev/checker_dune_db
  dev/checker_printers.dbg
  dev/checker_printers.ml
  dev/checker_printers.mli
  dev/doc/build-system.dune.md
  dev/dune
  dev/dune-dbg.in
Labels: kind: infrastructure

#8958 [clib] Remove unneeded `get_extension` function.
  clib/cUnix.ml
  clib/cUnix.mli
  lib/coqProject_file.ml
Labels: kind: cleanup

#8892 Fix part of #8224: grounding open term in fixpoints
  test-suite/bugs/closed/bug_8224.v
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comProgramFixpoint.ml
Labels: kind: fix

#8962 [ci] Add paramcoq to CI.
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-paramcoq.sh
Labels: kind: infrastructure

#8960 [dune] Build `cmxs` files instead of `cmxa` in "quick" target.
  Makefile.dune
Labels: kind: infrastructure

#8979 Skip submodules in HoTT CI script.
  dev/ci/ci-hott.sh
Labels: kind: infrastructure

#8936 Fix #8908: incorrect refresh of algebraic universes.
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  pretyping/evarsolve.ml
  test-suite/bugs/closed/bug_8908.v
Labels: kind: fix, part: universes

#8957 Fix -top for univbinders output test.
  test-suite/output/UnivBinders.v
Labels: kind: fix

#8976 CoqHammer CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-coqhammer.sh
Labels: kind: infrastructure

#8906 [Goptions] More detailed error messages
  library/goptions.ml
Labels: kind: enhancement

#8886 [VM] Fix compilation of int31 eliminators
  test-suite/bugs/closed/bug_8885.v
  theories/Numbers/Cyclic/Int31/Int31.v
Labels: kind: fix, priority: critical

#8966 coq_makefile: Fix ocamldep ignoring mlg files
  test-suite/coq-makefile/camldep/_CoqProject
  test-suite/coq-makefile/camldep/run.sh
  tools/CoqMakefile.in
Labels: kind: fix, part: tools

#8914 [CoqProject] Abstract warning function for CoqProject readers.
  dev/ci/user-overlays/08914-ejgallego-lib+better_boot_coqproject.sh
  ide/coqide.ml
  lib/coqProject_file.ml
  lib/coqProject_file.mli
  tools/coq_makefile.ml
  tools/coqdep.ml
Labels: kind: infrastructure

#8992 put protocol/ in ide/.merlin
  ide/.merlin.in
Labels: kind: infrastructure

#8712 [stm] avoid unshare safe env to detect correctly env changing tactics
  kernel/environ.ml
  kernel/safe_typing.ml
Labels: kind: fix

#9013 Do not Export the init modules
  CHANGES.md
  test-suite/success/Require.v
  toplevel/coqtop.ml
Labels: kind: fix, part: standard library

#9023 [gramlib] Remove unused alias.
  gramlib/grammar.ml
  gramlib/grammar.mli
  parsing/pcoq.ml
  vernac/pvernac.ml
Labels: kind: cleanup

#8999 [pfedit] Remove cook_proof stub.
  plugins/funind/functional_principles_types.ml
  plugins/funind/indfun_common.ml
  plugins/funind/indfun_common.mli
  proofs/pfedit.ml
  proofs/pfedit.mli
  vernac/lemmas.ml
  vernac/obligations.ml
Labels: kind: cleanup

#9001 [options] Remove deprecated option automatic introduction.
  CHANGES.md
  doc/sphinx/proof-engine/proof-handling.rst
  lib/flags.ml
  lib/flags.mli
  test-suite/bugs/closed/bug_2001.v
  test-suite/bugs/closed/bug_6661.v
  test-suite/success/Fixpoint.v
  test-suite/success/autointros.v
  vernac/classes.ml
  vernac/lemmas.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#8902 [ltac] Use CAst nodes in the tactic AST.
  dev/ci/user-overlays/08902-ejgallego-ltac+use_atts_in_ast.sh
  plugins/firstorder/g_ground.mlg
  plugins/ltac/coretactics.mlg
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_tactic.mlg
  plugins/ltac/pptactic.ml
  plugins/ltac/profile_ltac.ml
  plugins/ltac/rewrite.ml
  plugins/ltac/tacentries.ml
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacsubst.ml
  plugins/ltac/tactic_debug.ml
  plugins/ltac/tauto.ml
  plugins/setoid_ring/newring.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssrmatching/ssrmatching.ml
Labels: kind: cleanup, kind: feature

#9026 [Documentation/Combined Scheme] Typo
  doc/sphinx/user-extensions/proof-schemes.rst
Labels: kind: documentation, kind: fix

#9003 [vernacextend] Consolidate extension points API
  coqpp/coqpp_main.ml
  dev/ci/user-overlays/09003-ejgallego-vernac+move_extend_ast.sh
  dev/top_printers.ml
  plugins/derive/g_derive.mlg
  plugins/funind/g_indfun.mlg
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_obligations.mlg
  plugins/ltac/g_rewrite.mlg
  plugins/setoid_ring/g_newring.mlg
  stm/stm.ml
  stm/stm.mli
  stm/vernac_classifier.ml
  stm/vernac_classifier.mli
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/egramml.mli
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacexpr.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
Labels: kind: cleanup

#8987 Deprecate hint declaration/removal with no specified database
  CHANGES.md
  plugins/btauto/Algebra.v
  plugins/btauto/Reflect.v
  plugins/ssr/ssrbool.v
  plugins/ssr/ssrfun.v
  tactics/hints.ml
  theories/Bool/Bool.v
  theories/Classes/RelationPairs.v
  theories/FSets/FMapAVL.v
  theories/FSets/FMapFacts.v
  theories/FSets/FMapFullAVL.v
  theories/FSets/FMapInterface.v
  theories/FSets/FMapList.v
  theories/FSets/FMapWeakList.v
  theories/FSets/FSetBridge.v
  theories/FSets/FSetInterface.v
  theories/FSets/FSetProperties.v
  theories/Init/Datatypes.v
  theories/Lists/List.v
  theories/Lists/ListSet.v
  theories/Lists/SetoidList.v
  theories/Lists/SetoidPermutation.v
  theories/Logic/JMeq.v
  theories/MSets/MSetAVL.v
  theories/MSets/MSetGenTree.v
  theories/MSets/MSetInterface.v
  theories/MSets/MSetList.v
  theories/MSets/MSetProperties.v
  theories/MSets/MSetRBT.v
  theories/MSets/MSetWeakList.v
  theories/Numbers/Cyclic/ZModulo/ZModulo.v
  theories/Numbers/Natural/Abstract/NDefOps.v
  theories/Program/Basics.v
  theories/Program/Wf.v
  theories/QArith/Qcanon.v
  theories/QArith/Qreals.v
  theories/Reals/RIneq.v
  theories/Sets/Cpo.v
  theories/Sets/Infinite_sets.v
  theories/Sets/Powerset.v
  theories/Sets/Relations_1_facts.v
  theories/Sets/Relations_3_facts.v
  theories/Sets/Uniset.v
  theories/Sorting/Heap.v
  theories/Sorting/Permutation.v
  theories/Sorting/Sorted.v
  theories/Structures/DecidableType.v
  theories/Structures/Equalities.v
  theories/Structures/EqualitiesFacts.v
  theories/Structures/OrderedType.v
  theories/Structures/Orders.v
  theories/Structures/OrdersLists.v
  theories/Vectors/VectorDef.v
  theories/Wellfounded/Inclusion.v
  theories/Wellfounded/Transitive_Closure.v
  theories/ZArith/Zdiv.v
  theories/ZArith/Zlogarithm.v
  vernac/vernacentries.ml
Labels: kind: cleanup

#9002 [pfedit] Remove `start_proof` stub from `Pfedit`
  proofs/pfedit.ml
  proofs/pfedit.mli
  proofs/proof_global.mli
  vernac/lemmas.ml
  vernac/lemmas.mli
Labels: kind: cleanup

#8982 [proof] Provide better control of "open proofs" exceptions.
  proofs/logic.ml
  proofs/proof.ml
  proofs/proof.mli
  proofs/proof_global.ml
  proofs/proofs.mllib
  tactics/class_tactics.ml
  tactics/eauto.ml
  vernac/obligations.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#9031 Rename gh->bug_ test files
  test-suite/bugs/closed/bug_6165.v
  test-suite/bugs/closed/bug_6384.v
  test-suite/bugs/closed/bug_6385.v
Labels: kind: cleanup

#9033 gitlab: Install stdlib doc in build:base
  .gitlab-ci.yml
  dev/ci/README.md
Labels: kind: documentation, kind: fix, kind: infrastructure

#9017 Remove SSR profiling
  plugins/ssr/ssrbwd.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrequality.ml
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
Labels: kind: cleanup

#9016 PRINT_LOGS=1 in appveyor test suite run
  test-suite/Makefile
  test-suite/report.sh
Labels: kind: infrastructure, platform: Windows

#8948 [dune] Some tweaks to docs.
  dev/doc/build-system.dune.md
Labels: kind: documentation

#9035 [dune] Only build printers when the ltac plugin is available.
  dev/dune
Labels: kind: infrastructure

#8998 [legacy proof engine] Remove some cruft.
  dev/base_include
  dev/ci/user-overlays/08998-ejgallego-legacy_proof_eng_clean.sh
  dev/doc/coq-src-description.txt
  dev/top_printers.mli
  plugins/funind/functional_principles_proofs.ml
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrelim.ml
  plugins/ssrmatching/ssrmatching.mli
  printing/printer.mli
  printing/proof_diffs.mli
  proofs/clenvtac.ml
  proofs/logic.ml
  proofs/logic.mli
  proofs/proof_type.ml
  proofs/proofs.mllib
  proofs/refiner.ml
  proofs/refiner.mli
  proofs/tacmach.ml
  proofs/tacmach.mli
  tactics/eauto.ml
  tactics/eauto.mli
  tactics/equality.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#8975 Minor update to micromega.rst
  doc/sphinx/addendum/micromega.rst
Labels: kind: documentation

#8985 [gramlib] [build] Switch make-based system to packed gramlib
  .gitignore
  .merlin.in
  META.coq.in
  Makefile
  Makefile.build
  Makefile.common
  Makefile.install
  configure.ml
  dev/ci/user-overlays/08985-ejgallego-build+pack_gramlib.sh
  parsing/cLexer.ml
  parsing/cLexer.mli
  parsing/dune
  parsing/extend.ml
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/funind/plugin_base.dune
  plugins/ltac/plugin_base.dune
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  plugins/ssrmatching/plugin_base.dune
  printing/dune
  printing/proof_diffs.ml
  tools/CoqMakefile.in
  toplevel/coqloop.ml
  toplevel/dune
  vernac/dune
  vernac/explainErr.ml
Labels: kind: infrastructure

#9005 More informative error on vo validation failure
  Makefile.build
  checker/validate.ml
  checker/values.ml
  checker/values.mli
Labels: kind: enhancement, kind: user messages, part: checker

#8945 [camlp5] Remove dependency on camlp5.
  .gitlab-ci.yml
  .merlin.in
  .travis.yml
  CHANGES.md
  INSTALL
  META.coq.in
  Makefile
  Makefile.build
  Makefile.common
  Makefile.ide
  checker/include
  config/coq_config.mli
  configure.ml
  coq.opam
  default.nix
  dev/base_include
  dev/build/windows/makecoq_mingw.sh
  dev/ci/README.md
  dev/ci/appveyor.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/doc/README.md
  dev/doc/changes.md
  dev/ocamldebug-coq.run
  gramlib/gramlib.mllib
  grammar/argextend.mlp
  grammar/dune
  grammar/q_util.mli
  grammar/q_util.mlp
  grammar/tacextend.mlp
  grammar/vernacextend.mlp
  lib/envars.ml
  tools/CoqMakefile.in
Labels: kind: cleanup, kind: infrastructure, part: build

#9049 [default.nix] Add graphviz for STM DAG printer
  default.nix
Labels: kind: infrastructure

#8967 Fix #8922 (uncaught pp_diff exception)
  ide/idetop.ml
  lib/pp_diff.ml
  printing/printer.ml
  printing/proof_diffs.ml
  proofs/proof.ml
  test-suite/unit-tests/printing/proof_diffs_test.ml
Labels: kind: fix, priority: high

#8924 Misc updates to codeowners
  .github/CODEOWNERS
Labels: kind: meta

#9021 merge-pr: Improve overlay check
  dev/tools/merge-pr.sh
Labels: kind: infrastructure

#9044 Remove pidetop from CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-pidetop.sh
Labels: kind: infrastructure

#9055 [dev] fix create_overlay wrt branch names containing /
  dev/tools/create_overlays.sh
Labels: needs: rebase

#8890 Looking for notation both before or after removal of top coercion
  interp/constrextern.ml
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: kind: fix, part: notations

#9022 [ci] [doc] Split user/developer README, add info about Nix/Docker CI
  dev/ci/README-developers.md
  dev/ci/README-users.md
  dev/ci/README.md
Labels: kind: documentation, kind: infrastructure

#8950 [topfmt] Add phase attribute for toplevel printing.
  toplevel/coqargs.ml
  toplevel/coqloop.ml
  toplevel/coqloop.mli
  toplevel/coqtop.ml
  vernac/topfmt.ml
  vernac/topfmt.mli
Labels: kind: cleanup

#8996 Fix #8937: inductive conversion in coqchk subtyping
  checker/mod_checking.ml
  test-suite/coqchk/bug_8937.v
Labels: kind: fix, part: checker

#9036 Add bodies to sphinx objects.
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/miscellaneous-extensions.rst
  doc/sphinx/addendum/omega.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/proof-handling.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/proof-schemes.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, kind: fix

#9074 Fix ocamldebug-coq for packed gramlib
  dev/ocamldebug-coq.run
Labels: kind: fix, kind: infrastructure

#9063 [checker] Remove duplicated code from checker / clib
  checker/check.ml
Labels: kind: cleanup

#9075 [ci] Set windows jobs to allow_failure: true
  .gitlab-ci.yml
Labels: kind: ci-failure, kind: infrastructure

#8986 Put -indices-matter in typing_flags
  checker/checker.ml
  checker/values.ml
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/indtypes.ml
  kernel/indtypes.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  library/global.ml
  library/global.mli
  toplevel/coqargs.ml
  toplevel/coqargs.mli
  toplevel/coqtop.ml
  vernac/comInductive.ml
Labels: kind: cleanup

#7696 Remove some univ_flexible_alg from cases
  pretyping/cases.ml
Labels: kind: cleanup, part: elaboration, part: universes

#7033 Remove obsolete files from dev/doc
  dev/doc/about-hints
  dev/doc/cic.dtd
  dev/doc/minicoq.tex
  dev/doc/transition-V5.10-V6
  dev/doc/transition-V6-V7
  dev/doc/translate.txt
Labels: kind: cleanup

#8854 Fix #8364: making univ algebraic when already equal to another.
  engine/uState.ml
  kernel/uGraph.ml
  kernel/uGraph.mli
  test-suite/bugs/closed/bug_8364.v
Labels: kind: anomaly, kind: fix, part: universes

#9089 Fix #9076 (warning appears when running test suite)
  test-suite/modules/Nat.v
Labels: kind: fix, part: test-suite

#8826 [toplevel] Allow to specify default options.
  ide/idetop.ml
  toplevel/coqargs.ml
  toplevel/coqargs.mli
  toplevel/coqtop.ml
  toplevel/coqtop.mli
  toplevel/workerLoop.ml
Labels: kind: cleanup

#8727 [options] New helper for creation of boolean options plus reference.
  engine/namegen.ml
  engine/namegen.mli
  engine/univMinim.ml
  interp/constrexpr_ops.ml
  interp/constrexpr_ops.mli
  interp/constrextern.ml
  interp/constrintern.ml
  interp/constrintern.mli
  library/goptions.ml
  library/goptions.mli
  pretyping/cbv.ml
  pretyping/classops.ml
  pretyping/coercion.ml
  pretyping/pretyping.ml
  pretyping/typeclasses.ml
  stm/stm.ml
  toplevel/coqargs.ml
  vernac/obligations.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#9070 [ssreflect] Export more parsing witnesses.
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrparser.mli
Labels: kind: enhancement

#9104 coqide: Remove unused win32_kill C function
  ide/coqide_WIN32.ml.in
  ide/ide_win32_stubs.c
Labels: kind: cleanup, part: IDE

#9102 [ltac] Remove aliases already present in the lower layers.
  dev/ci/user-overlays/09102-ejgallego-ltac+remove_aliases.sh
  plugins/ltac/extraargs.mli
  plugins/ltac/extratactics.mli
  plugins/ltac/g_rewrite.mlg
  plugins/ltac/pptactic.ml
  plugins/ltac/pptactic.mli
  plugins/ltac/rewrite.mli
  plugins/ltac/tacarg.mli
  plugins/ltac/taccoerce.mli
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.mli
  plugins/ltac/tacinterp.mli
  plugins/ltac/tacsubst.mli
  plugins/ltac/tactic_debug.mli
  plugins/ltac/tactic_matching.mli
  plugins/ssr/ssrast.mli
  plugins/ssr/ssrcommon.mli
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
Labels: kind: cleanup

#8807 Added two proofs to the Lists library: Forall_inv_tail and Exists_impl
  CREDITS
  theories/Lists/List.v
Labels: kind: feature, part: standard library

#9068 [dune] Minor tweak of dependencies.
  META.coq.in
  clib/dune
  kernel/dune
  lib/dune
Labels: kind: infrastructure
