Repository rocq-prover/rocq, pull requests merged in 2018-03, with the labels that each got.

#6847 Fix make source-doc
  Makefile.doc
Labels: kind: fix, kind: infrastructure, kind: regression

#6850 Fix #6751 trust_file_cache logic was inverted
  lib/system.ml
  toplevel/coqargs.ml
Labels: kind: fix, kind: regression

#6861 Typo in the documentation of the `pattern` tactic
  doc/refman/RefMan-tac.tex
Labels: kind: documentation, kind: fix

#6864 Remove empty, wrongly located, doc file.
  parsing/doc.tex
Labels: kind: cleanup

#6856 travis: elpi needs findlib >= 1.5
  .travis.yml
Labels: kind: fix, kind: infrastructure

#915 Fix rewrite in * side conditions
  CHANGES
  doc/refman/RefMan-tac.tex
  tactics/equality.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  test-suite/success/rewrite.v
Labels: kind: fix, part: tactics

#6511 [econstr] Continue consolidation of EConstr API under `interp`.
  dev/base_include
  dev/ci/user-overlays/06511-ejgallego-econstr+more_fix.sh
  dev/top_printers.ml
  engine/termops.ml
  engine/termops.mli
  ide/ide_slave.ml
  interp/constrintern.ml
  interp/constrintern.mli
  interp/declare.ml
  interp/impargs.ml
  interp/impargs.mli
  interp/modintern.ml
  interp/notation.ml
  interp/notation.mli
  plugins/funind/glob_term_to_relation.ml
  plugins/funind/indfun.ml
  plugins/funind/recdef.ml
  plugins/ltac/extratactics.ml4
  plugins/ltac/rewrite.ml
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/setoid_ring/newring.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrvernac.ml4
  plugins/ssr/ssrview.ml
  plugins/ssrmatching/ssrmatching.ml4
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  printing/ppconstr.ml
  proofs/proof.ml
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/tactics.ml
  vernac/classes.ml
  vernac/comAssumption.ml
  vernac/comFixpoint.ml
  vernac/comInductive.ml
  vernac/comProgramFixpoint.ml
  vernac/obligations.ml
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: redesign

#6846 Moving code for "simple induction"/"simple destruct" to coretactics.ml4.
  plugins/ltac/coretactics.ml4
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup, part: tactics

#6873 [toplevel] Update state when `Drop` exception is thrown [#6872]
  dev/base_include
  toplevel/coqloop.ml
  toplevel/coqloop.mli
  toplevel/coqtop.ml
  toplevel/coqtop.mli
Labels: kind: fix

#6876 Unify Const_sorts and Const_type, and remove Vsort
  dev/vm_printers.ml
  kernel/cbytecodes.ml
  kernel/cbytecodes.mli
  kernel/cbytegen.ml
  kernel/cemitcodes.ml
  kernel/vconv.ml
  kernel/vm.ml
  kernel/vmvalues.ml
  kernel/vmvalues.mli
  pretyping/vnorm.ml
Labels: part: VM

#6879 Fix #6878: univ undefined for [with Definition] bad instance size.
  kernel/uGraph.ml
  test-suite/bugs/closed/6878.v
Labels: kind: anomaly, kind: fix, part: universes

#6885 [stm] Partial fix for bug #6884 [location missing from replay nodes]
  stm/stm.ml
Labels: kind: fix, part: STM

#6886 [v8.7] [stm] Partial fix for bug #6884 [location missing from replay nodes]
  stm/stm.ml
Labels: kind: fix, part: STM

#6749 Fixing an anomaly in the presence of "let-in" in the type of a record.
  test-suite/success/Inductive.v
  vernac/record.ml
Labels: kind: anomaly, kind: fix

#6824 Remove deprecated options related to typeclasses.
  doc/refman/Classes.tex
  tactics/class_tactics.ml
  tactics/tactics.ml
  test-suite/bugs/closed/3513.v
  test-suite/bugs/opened/3926.v
  test-suite/success/old_typeclass.v
Labels: kind: cleanup

#6896 [compat] Remove NOOP deprecated options.
  doc/refman/RefMan-sch.tex
  plugins/ssr/ssrequality.ml
  test-suite/bugs/closed/3481.v
  test-suite/bugs/closed/3520.v
  test-suite/bugs/closed/3662.v
  test-suite/bugs/closed/HoTT_coq_077.v
  test-suite/bugs/closed/HoTT_coq_104.v
  test-suite/success/letproj.v
  test-suite/success/primitiveproj.v
  vernac/indschemes.ml
Labels: kind: cleanup

#6898 [compat] Remove "Intuition Iff Unfolding"
  doc/refman/RefMan-tac.tex
  plugins/ltac/tauto.ml
Labels: kind: cleanup

#6900 [compat] Remove "Tactic Pattern Unification"
  pretyping/unification.ml
Labels: kind: cleanup

#6901 [compat] Remove "Injection L2R Pattern Order"
  tactics/equality.ml
Labels: kind: cleanup

#6917 Fix failing packaging job.
  .travis.yml
Labels: kind: fix, kind: infrastructure

#6374 [toplevel] Modify printing goal strategy.
  toplevel/coqloop.ml
  toplevel/vernac.ml
Labels: kind: cleanup, kind: enhancement, kind: redesign

#6462 Sanitize universe declaration in Context (stop using a ref...)
  test-suite/bugs/closed/2245.v
  vernac/classes.ml
Labels: kind: cleanup, part: universes

#6911 [ssr] Declare prenex implicits for `Some_inj`
  plugins/ssr/ssrfun.v
  test-suite/bugs/closed/6910.v
Labels: kind: fix, part: ssreflect

#6922 Remove outdated information regarding the FAQ.
  doc/LICENSE
Labels: kind: cleanup, kind: documentation, kind: fix

#6932 [stdlib] Do not use deprecated notations
  plugins/extraction/ExtrOcamlNatBigInt.v
  plugins/extraction/ExtrOcamlNatInt.v
Labels: kind: cleanup, part: standard library

#6744 Add String.concat
  CHANGES
  theories/Strings/String.v
Labels: kind: enhancement, part: standard library

#6783 ssr: use `apply_type ~typecheck:true` everywhere (fix #6634)
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrtacticals.ml
  test-suite/bugs/closed/6634.v
Labels: kind: fix, kind: regression

#6903 [compat] Remove "Shrink Abstract"
  doc/refman/RefMan-ltac.tex
  tactics/tactics.ml
  test-suite/success/shrink_abstract.v
Labels: kind: cleanup

#6924 Clean-up remove always false useeager argument.
  tactics/auto.ml
Labels: kind: cleanup

#6933 Standard headers for C and Python.
  dev/header.c
  dev/header.ml
  dev/header.py
Labels: kind: infrastructure

#6582 Mangle auto-generated names
  CHANGES
  doc/refman/RefMan-com.tex
  engine/namegen.ml
  engine/namegen.mli
  tactics/tactics.ml
  test-suite/success/name_mangling.v
  tools/coqc.ml
  toplevel/coqargs.ml
  toplevel/usage.ml
Labels: kind: feature

#6743 Add notation {x & P} for sigT
  CHANGES
  theories/Init/Notations.v
  theories/Init/Specif.v
Labels: kind: feature, part: standard library

#6899 [compat] Remove "Standard Proposition Elimination"
  engine/namegen.ml
  engine/namegen.mli
  tactics/tactics.ml
  test-suite/bugs/closed/2378.v
  test-suite/bugs/opened/1596.v
Labels: kind: cleanup

#6927 Add some missing flushes in configure.
  configure.ml
Labels: kind: fix

#6918 romega: get rid of EConstr.Unsafe
  plugins/romega/const_omega.ml
  plugins/romega/const_omega.mli
  plugins/romega/refl_omega.ml
Labels: kind: cleanup

#6522 Fix core hint database issue #6521
  test-suite/success/Hints.v
  theories/Init/Peano.v
Labels: kind: enhancement, kind: fix, part: standard library

#6816 Adding mention of shelved/given-up status in Show Existentials
  printing/printer.ml
  printing/printer.mli
  test-suite/output/Arguments_renaming.out
  test-suite/output/Existentials.out
  test-suite/output/Notations3.out
  test-suite/output/inference.out
  vernac/vernacentries.ml
Labels: kind: enhancement, kind: user messages, part: tactics

#6925 Extraction: switch to EConstr.t as the central type to extract from.
  plugins/extraction/extract_env.ml
  plugins/extraction/extract_env.mli
  plugins/extraction/extraction.ml
  plugins/extraction/extraction.mli
Labels: kind: cleanup

#6926 An experimental 'Show Extraction' command (grant feature wish #4129)
  CHANGES
  plugins/extraction/extract_env.ml
  plugins/extraction/extract_env.mli
  plugins/extraction/extraction.ml
  plugins/extraction/extraction.mli
  plugins/extraction/g_extraction.ml4
  plugins/extraction/table.ml
  test-suite/success/ShowExtraction.v
Labels: kind: feature, part: extraction

#6928 gitlab: install num for all 4.06 jobs
  .gitlab-ci.yml
Labels: kind: fix, kind: infrastructure

#407 Fix SR breakage due to allowing fixpoints on non-rec values
  kernel/inductive.ml
  test-suite/failure/fixpointeta.v
  vernac/himsg.ml
Labels: kind: fix

#6496 Generate typed generic code from ltac macros
  grammar/tacextend.mlp
  grammar/vernacextend.mlp
  intf/extend.ml
  lib/genarg.ml
  lib/genarg.mli
  plugins/ltac/g_eqdecide.ml4
  plugins/ltac/taccoerce.ml
  plugins/ltac/taccoerce.mli
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacinterp.mli
  plugins/nsatz/g_nsatz.ml4
Labels: kind: redesign

#6800 [checker] Printer cleanup.
  checker/checker.ml
  checker/print.ml
  checker/print.mli
Labels: kind: cleanup, kind: fix

#6871 [build] Simpler byte/opt toplevel build.
  Makefile.build
  toplevel/coqtop_bin.ml
  toplevel/coqtop_byte_bin.ml
  toplevel/coqtop_opt_bin.ml
Labels: kind: infrastructure, needs: review

#6941 [toplevel] Respect COQ_COLORS environment variable
  toplevel/coqtop.ml
  vernac/topfmt.ml
  vernac/topfmt.mli
Labels: kind: fix, kind: regression

#6945 Fix error with univ binders on monomorphic records.
  test-suite/output/UnivBinders.out
  test-suite/output/UnivBinders.v
  vernac/record.ml
Labels: kind: fix, kind: regression, part: universes

#6895 [compat] Remove "Refolding Reduction" option.
  doc/refman/RefMan-tac.tex
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  test-suite/bugs/opened/3424.v
  test-suite/output/inference.out
  test-suite/output/inference.v
Labels: kind: cleanup

#6806 Adding missing unification constraint noticed by @skyskimmer
  pretyping/typing.ml
Labels: kind: fix, part: elaboration

#6953 [default.nix] Pin nixpkgs version to include Sphinx dependencies
  default.nix
Labels: kind: infrastructure

#6946 Fix expected number of arguments for cumulative constructors.
  kernel/reduction.ml
  test-suite/success/cumulativity.v
Labels: kind: fix, part: universes

#6949 Revert PR #873: New strategy based on open scopes for deciding…
  CHANGES
  interp/constrextern.ml
  interp/notation.ml
  interp/notation.mli
  test-suite/output/Notations.out
  test-suite/output/Notations.v
  test-suite/output/Notations2.out
  test-suite/output/Notations2.v
  test-suite/output/Notations3.out
  test-suite/output/Notations3.v
Labels: kind: fix, kind: regression

#6912 [doc] Document removal of deprecated options.
  CHANGES
Labels: kind: documentation

#6967 [META] Update Coq version number.
  META.coq
Labels: kind: infrastructure

#7036 Sphinx doc chapter 17
  Makefile.doc
  doc/refman/Cases.tex
  doc/refman/Reference-Manual.tex
  doc/sphinx/addendum/extended-pattern-matching.rst
  doc/sphinx/index.rst
Labels: kind: documentation

#7038 Sphinx doc chapter 19
  Makefile.doc
  doc/refman/CanonicalStructures.tex
  doc/refman/Reference-Manual.tex
  doc/sphinx/addendum/canonical-structures.rst
  doc/sphinx/index.rst
Labels: kind: documentation

#7039 Sphinx doc chapter 21
  Makefile.doc
  doc/refman/Omega.tex
  doc/refman/Reference-Manual.tex
  doc/sphinx/addendum/omega.rst
  doc/sphinx/biblio.bib
  doc/sphinx/index.rst
Labels: kind: documentation

#7031 Owners for developer tools
  .github/CODEOWNERS
Labels: kind: infrastructure

#7030 [default.nix] Add dependencies of the merging script.
  default.nix
Labels: kind: infrastructure

#6968 [stm] Never consider `Backtrack` as part of the script.
  stm/stm.ml
Labels: kind: fix

#7028 Fix #7026: ssr: applying an overloaded lemma as a view takes too long.
  plugins/ssr/ssrcommon.ml
Labels: kind: fix, kind: performance

#7052 More precise wording about the merge process.
  dev/doc/MERGING.md
Labels: kind: infrastructure

#7029 improve merge-pr script
  dev/tools/merge-pr.sh
Labels: kind: infrastructure

#7018 Fix typo in CHANGES.
  CHANGES
Labels: kind: documentation, kind: fix

#7046 Switch maintainers for documentation
  .github/CODEOWNERS
Labels: kind: infrastructure

#6970 [vernac] Move `Quit` and `Drop` to the toplevel layer.
  dev/base_include
  ide/ide_slave.ml
  intf/vernacexpr.ml
  lib/cErrors.ml
  lib/cErrors.mli
  parsing/g_vernac.ml4
  printing/ppvernac.ml
  stm/stm.ml
  stm/vernac_classifier.ml
  toplevel/coqinit.ml
  toplevel/coqinit.mli
  toplevel/coqloop.ml
  toplevel/coqloop.mli
  toplevel/coqtop.ml
  toplevel/g_toplevel.ml4
  toplevel/toplevel.mllib
  toplevel/vernac.ml
  toplevel/vernac.mli
  vernac/vernacentries.ml
  vernac/vernacinterp.ml
Labels: kind: cleanup

#6739 Tentative fix for #6520: camlcity.org unresponsive makes AppVeyor fail.
  dev/build/windows/makecoq_mingw.sh
Labels: kind: fix, kind: infrastructure

#7062 Slightly refining some error messages about unresolvable evars.
  engine/evarutil.ml
  engine/evarutil.mli
  engine/termops.ml
  intf/evar_kinds.ml
  pretyping/cases.ml
  pretyping/evardefine.ml
  test-suite/output/Errors.out
  test-suite/output/Errors.v
  vernac/himsg.ml
Labels: kind: enhancement, kind: user messages, part: elaboration

#6835 Deprecate undocumented "intros until 0" in favor of "intros *"
  plugins/micromega/Tauto.v
  tactics/tactics.ml
Labels: kind: cleanup, kind: user messages, part: tactics

#6961 [test-suite] Add backtracking test for `Load`.
  test-suite/ide/load.fake
Labels: kind: infrastructure

#7090 stm: don't propagate side effects when editing a proof
  stm/stm.ml
  test-suite/ide/bug7088.fake
Labels: kind: fix

#7072 Update codeowners
  .github/CODEOWNERS
Labels: kind: infrastructure

#7130 gitlab: fix environment for build template
  .gitlab-ci.yml
Labels: kind: fix, kind: infrastructure

#7111 Fix #6631: Derive Plugin gives "Anomaly: more than one statement".
  tactics/tactics.ml
  test-suite/bugs/closed/6631.v
Labels: kind: fix

#6989 Enable whitespace checking for new Sphinx file extensions.
  .gitattributes
Labels: kind: fix, kind: infrastructure

#7121 Remove outdated patch from ci-sf
  dev/ci/ci-sf.sh
Labels: kind: fix, kind: infrastructure
