Repository rocq-prover/rocq, pull requests merged in 2018-04, with the labels that each got.

#7132 [doc] Add some more documentation to STM API.
  stm/stm.mli
Labels: kind: documentation

#7154 Update coq_makefile timing test
  test-suite/coq-makefile/timing/run.sh
Labels: kind: fix, kind: infrastructure

#7138 [stm] Move VernacBacktrack to the toplevel.
  intf/vernacexpr.ml
  parsing/g_vernac.ml4
  printing/ppvernac.ml
  stm/stm.ml
  stm/vernac_classifier.ml
  toplevel/coqloop.ml
  toplevel/g_toplevel.ml4
  vernac/vernacentries.ml
  vernac/vernacprop.ml
Labels: kind: cleanup, part: STM

#7144 [toplevel] Protect goal printing better wrt Break [helps with #7142]
  toplevel/coqloop.ml
Labels: kind: fix

#7147 [doc] Document better ocamlfind and flambda requirements.
  INSTALL
Labels: kind: documentation

#7158 [meta] Add `num` to the set of base libraries.
  META.coq
Labels: kind: fix, kind: infrastructure

#7163 merge-pr.sh: cache github API calls
  dev/tools/merge-pr.sh
Labels: kind: fix, kind: infrastructure, kind: performance, part: tools

#7127 Fix #6257: anomaly with Printing Projections and Context.
  interp/constrextern.ml
  test-suite/output/Projections.out
  test-suite/output/Projections.v
Labels: kind: anomaly, kind: user messages, part: notations

#7169 Sphinx docs: fix typo in Chrząszcz (non-ASCII character lost in sphinx migration)
  doc/sphinx/credits.rst
Labels: kind: documentation, kind: fix

#6838 Light refactoring of implicit arguments
  interp/impargs.ml
Labels: kind: cleanup

#7180 Remove unused script.
  ide/MacOS/relatify_with-respect-to_.sh
Labels: kind: cleanup

#6960 [api] Move some types to their proper module.
  dev/ci/user-overlays/06960-ejgallego-ltac+tacdepr.sh
  intf/misctypes.ml
  plugins/funind/invfun.ml
  plugins/ltac/pltac.mli
  plugins/ltac/pptactic.mli
  plugins/ltac/tacarg.mli
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  tactics/equality.mli
  tactics/inv.ml
  tactics/inv.mli
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#7129 Fix #7124: Warning "Ignoring implicit status" does not provide line number
  interp/implicit_quantifiers.ml
Labels: kind: fix, kind: user messages

#7070 Clarify wording in tactics documentation.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#7082 Expliciting and taking advantage of a representation invariant in Esubst
  kernel/esubst.ml
  kernel/esubst.mli
Labels: kind: cleanup

#7165 [ssr] check cleared hyps do exist (fix #7050)
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrparser.ml4
  test-suite/output/ssr_clear.out
  test-suite/output/ssr_clear.v
Labels: kind: fix, kind: regression

#7184 [toplevel] Fix path initialization before vio processing (closes #7044)
  toplevel/coqtop.ml
Labels: kind: fix

#7176 Fix #6956: Uncaught exception in bytecode compilation
  kernel/cbytegen.ml
  kernel/univ.ml
  kernel/univ.mli
  test-suite/bugs/closed/6956.v
Labels: kind: fix

#7207 [ci] Tentative fix for #7206: MacOS test-suite job failing.
  .travis.yml
Labels: kind: fix, kind: infrastructure

#7103 Fix #7101: STM delegation policy broken
  CHANGES
  lib/aux_file.ml
Labels: kind: regression

#7116 Fixes #7110: missing test on the absence of a "as" while looking for a notation for a nested pattern
  interp/constrextern.ml
  interp/notation_ops.ml
  test-suite/output/Notations3.out
  test-suite/output/Notations3.v
Labels: kind: fix, part: notations

#7205 [ci] Test branches for v8.8.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#6955 Fixed many typos and grammar errors in chapter 11 of the manual.
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, kind: fix

#7143 [toplevel] Catch exceptions when printing goals [fixes: #7140]
  toplevel/coqloop.ml
Labels: kind: fix

#7218 Add myself as the primary maintainer of the warnings system
  .github/CODEOWNERS
Labels: kind: infrastructure

#7203 removing ugly error message of #5147
  plugins/funind/functional_principles_types.ml
Labels: kind: anomaly, kind: fix

#7102 Improvements to the merge script.
  dev/tools/merge-pr.sh
Labels: kind: infrastructure

#7107 Fixes #7100: lost of main file location in case of Ltac failure in other file
  lib/loc.ml
  lib/loc.mli
  plugins/ltac/tactic_debug.ml
Labels: kind: fix, kind: regression, kind: user messages, part: ltac

#7096 coqide: avoid marking sentences that are not in the document anymore
  ide/coqOps.ml
Labels: kind: fix

#500 Move bugs that have been closed on Bugzilla
  test-suite/bugs/closed/1501.v
  test-suite/bugs/closed/2456.v
  test-suite/bugs/closed/2814.v
  test-suite/bugs/closed/3100.v
  test-suite/bugs/closed/3230.v
  test-suite/bugs/closed/3320.v
  test-suite/bugs/opened/3209.v
  test-suite/bugs/opened/3916.v
  test-suite/bugs/opened/3948.v
  test-suite/bugs/opened/4813.v
Labels: kind: cleanup

#6972 [api] Deprecate a couple of aliases that we missed.
  checker/cic.mli
  checker/closure.ml
  checker/closure.mli
  checker/environ.mli
  checker/reduction.ml
  checker/subtyping.ml
  checker/term.ml
  checker/values.ml
  clib/cArray.ml
  clib/cArray.mli
  clib/cList.ml
  clib/cList.mli
  clib/option.mli
  engine/eConstr.mli
  interp/impargs.mli
  interp/notation_ops.ml
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/constr.ml
  kernel/constr.mli
  kernel/environ.mli
  kernel/names.mli
  kernel/term.ml
  kernel/term.mli
  kernel/typeops.mli
  pretyping/cbv.ml
  pretyping/cbv.mli
  pretyping/evarconv.mli
  pretyping/evarsolve.mli
  pretyping/inductiveops.mli
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/retyping.mli
  pretyping/typing.mli
  pretyping/unification.ml
Labels: kind: cleanup

#7201 Translation fixes in chapter syntax extensions.
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, kind: fix

#7202 Correction of ugly message described in #4667
  plugins/funind/indfun.ml
Labels: kind: anomaly, kind: fix

#7179 Fix #5981, bugs/opened/3263.v is non-deterministic by removing the test.
  test-suite/bugs/opened/3263.v
Labels: kind: fix, needs: owner

#7222 [sphinx] Remove migration artefacts.
  doc/sphinx/addendum/miscellaneous-extensions.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, kind: fix

#7231 Fixing the 3 cases of a "Stream.Error" ended with two periods.
  interp/constrintern.ml
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: fix, kind: user messages, part: elaboration

#6454 [econstr] Flag to make `to_constr` fail if its output contains evars
  dev/ci/user-overlays/06454-ejgallego-evar+strict_to_constr.sh
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evarutil.ml
  plugins/cc/cctac.ml
  plugins/firstorder/sequent.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrview.ml
  pretyping/cases.ml
  pretyping/evarsolve.ml
  pretyping/pretyping.ml
  pretyping/retyping.ml
  pretyping/tacred.ml
  pretyping/typing.ml
  pretyping/vnorm.ml
  tactics/hints.ml
  vernac/classes.ml
  vernac/comDefinition.ml
  vernac/comFixpoint.ml
  vernac/comProgramFixpoint.ml
  vernac/himsg.ml
Labels: kind: cleanup

#7247 Simplify CircleCI script
  .circleci/config.yml
  CREDITS
Labels: kind: cleanup, kind: infrastructure

#7246 Add missing CHANGES entry for #6169.
  CHANGES
Labels: kind: documentation

#7251 doc: Rename UbuntuMono-Square to CoqNotations and tweak spacing
  doc/LICENSE
  doc/sphinx/_static/CoqNotations.ttf
  doc/sphinx/_static/UbuntuMono-Square.ttf
  doc/sphinx/_static/notations.css
  doc/tools/coqrst/notations/CoqNotations.ttf
  doc/tools/coqrst/notations/UbuntuMono-Square.ttf
  doc/tools/coqrst/notations/fontsupport.py
Labels: kind: documentation, kind: fix

#7200 [ltac] Deprecate nameless fix/cofix.
  CHANGES
  doc/RecTutorial/RecTutorial.tex
  doc/RecTutorial/RecTutorial.v
  tactics/tactics.ml
  test-suite/bugs/closed/2001.v
  test-suite/bugs/closed/3320.v
  test-suite/bugs/closed/3350.v
  test-suite/success/ShowExtraction.v
  test-suite/success/name_mangling.v
  theories/Arith/Div2.v
  theories/Arith/Even.v
  theories/Arith/PeanoNat.v
  theories/PArith/BinPos.v
  theories/Sorting/Heap.v
Labels: kind: cleanup

#7263 CHANGES: document COQFLAGS change
  CHANGES
Labels: kind: documentation

#7237 [ssr] fix delayed clears (fix #7045)
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssripats.ml
  test-suite/success/ssr_delayed_clear_rename.v
Labels: kind: fix, kind: regression, part: ssreflect

#7125 Adding ML headers in setoid_ring
  plugins/setoid_ring/Algebra_syntax.v
  plugins/setoid_ring/Integral_domain.v
  plugins/setoid_ring/RealField.v
  plugins/setoid_ring/Ring_tac.v
  plugins/setoid_ring/Rings_Q.v
  plugins/setoid_ring/Rings_R.v
  plugins/setoid_ring/Rings_Z.v
Labels: kind: infrastructure

#7225 Document the Export Set/Unset commands.
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: fix

#7264 [Sphinx] Fix a lot of references and description of options
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#7266 Remove LaTeX refman, now that migration to Sphinx is complete
  .gitignore
  INSTALL.doc
  Makefile
  Makefile.doc
  doc/refman/AddRefMan-pre.tex
  doc/refman/Reference-Manual.tex
  doc/refman/biblio.bib
  doc/refman/coq-listing.tex
  doc/refman/coqide-queries.png
  doc/refman/coqide.png
  doc/refman/headers.hva
  doc/refman/headers.sty
  doc/refman/index.html
  doc/refman/menu.html
Labels: kind: cleanup

#7269 Protecting against a "deprecated cofix" warning.
  theories/Lists/Streams.v
Labels: kind: fix

#7270 Sphinx doc fix indices
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/biblio.bib
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/proof-handling.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/proof-schemes.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: cleanup, needs: merge of dependency

#7272 Mention other deprecations and fixes in CHANGES
  CHANGES
Labels: kind: infrastructure

#7276 Add some 8.8.0 contributors in credits
  doc/sphinx/credits.rst
Labels: kind: documentation

#7271 Change version number to 8.8.0.
  .bintray.json
  configure.ml
  dev/build/windows/makecoq_mingw.sh
Labels: kind: infrastructure

#7277 Mention sphinxcontrib-bibtex in INSTALL.doc
  INSTALL.doc
Labels: kind: documentation

#7242 Update the CI branch for Equations.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure, priority: high

#7268 Travis: cleanup environment variables a bit.
  .travis.yml
Labels: kind: cleanup, kind: infrastructure

#7275 gitlab: separate opam-boot jobs, use opam init and OPAMROOT
  .gitlab-ci.yml
Labels: kind: infrastructure

#7280 [stm] expose restore/backup since ~doc is (still) dummy
  stm/stm.ml
  stm/stm.mli
Labels: kind: fix, part: STM

#7281 [stm] push functional API further
  stm/stm.ml
  stm/stm.mli
Labels: kind: enhancement, part: STM

#7287 [default.nix] Build doc with nix-build.
  default.nix
Labels: kind: infrastructure

#7294 fix Iris ci
  dev/ci/ci-iris-lambda-rust.sh
Labels: kind: cleanup, kind: fix, kind: infrastructure

#7248 Assign circleci files to @SkySkimmer
  .github/CODEOWNERS
Labels: kind: infrastructure

#7219 merge script support https + typos in doc
  dev/doc/MERGING.md
  dev/tools/merge-pr.sh
Labels: kind: documentation, kind: fix

#7282 [toplevel] allow toploop_init change Coq options
  ide/ide_slave.ml
  stm/workerLoop.ml
  stm/workerLoop.mli
  toplevel/coqtop.ml
  toplevel/coqtop.mli
Labels: kind: redesign

#7306 [ci] Update tracked branches for v8.8.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#7319 CI: add fcsl-pcm
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-fcsl-pcm.sh
Labels: kind: infrastructure

#7240 [doc] [engine] Document `abort_on_undefined_evars`.
  dev/doc/changes.md
Labels: kind: documentation

#7244 Making tactic-in-term aware of "Set Ltac Debug"
  CHANGES
  plugins/ltac/tacinterp.ml
Labels: kind: enhancement, kind: feature, kind: user messages, part: elaboration, part: ltac

#7108 Legacy refiner handle eta-expanded case analysis
  proofs/logic.ml
Labels: kind: cleanup

#6512 [api] Relocate `intf` modules according to dependency-order.
  .github/CODEOWNERS
  .merlin
  META.coq
  Makefile.common
  configure.ml
  dev/base_include
  dev/core.dbg
  dev/doc/coq-src-description.txt
  dev/ocamldebug-coq.run
  engine/engine.mllib
  engine/evar_kinds.ml
  interp/interp.mllib
  interp/notation_term.ml
  intf/intf.mllib
  library/decl_kinds.ml
  library/library.mllib
  library/misctypes.ml
  pretyping/constrexpr.ml
  pretyping/extend.ml
  pretyping/genredexpr.ml
  pretyping/glob_term.ml
  pretyping/locus.ml
  pretyping/pattern.ml
  pretyping/pretyping.mllib
  pretyping/vernacexpr.ml
Labels: kind: infrastructure

#307 Adding a flag to support different naming modes for evar hypotheses.
  engine/evarutil.ml
  engine/evarutil.mli
Labels: kind: feature

#7322 Test suite Makefile: print message for failing tests as they come, misc improvements
  test-suite/Makefile
Labels: kind: infrastructure

#6866 Slight improvement of messages related to direct and indirect uses of tactic `clear`.
  engine/evarutil.ml
  engine/evarutil.mli
  tactics/tactics.ml
Labels: kind: user messages, part: tactics

#7290 Update debugging.md
  dev/doc/debugging.md
Labels: kind: documentation

#7181 Sphinx docs: clarify strict implicit arguments a bit
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation

#7331 Fix a typo in the reference manual: <; -> <:
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation, kind: fix

#7350 Updating CI to recent changes in Mtac2 (former MetaCoq)
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-mtac2.sh
Labels: kind: enhancement, kind: infrastructure

#7321 configure: make -annotate fatal, and color error and warnings
  configure.ml
Labels: kind: infrastructure

#7351 Always print explanation for univ inconsistency, rm Flags.univ_print
  dev/top_printers.ml
  kernel/uGraph.ml
  kernel/univ.ml
  kernel/univ.mli
  lib/flags.ml
  lib/flags.mli
  pretyping/detyping.ml
Labels: kind: cleanup, part: kernel, part: universes

#7358 Fix #7356: missing lift when interpreting default instances of evars
  pretyping/pretyping.ml
  test-suite/success/evars.v
Labels: kind: fix, part: elaboration

#7367 circle CI: do not use cache from old config.yml versions
  .circleci/config.yml
Labels: kind: fix, kind: infrastructure

#7357 [CI] elpi 1.0 has an official opam package
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
Labels: kind: fix, kind: infrastructure

#7376 Fix gitlab ubuntu version
  .gitlab-ci.yml
Labels: kind: fix

#7386 [doc] Remove unused dependencies.
  .gitlab-ci.yml
  .travis.yml
  INSTALL.doc
  Makefile.doc
Labels: kind: documentation, kind: infrastructure

#7381 [gitlab] Update base image to Ubuntu bionic + some improvements.
  .gitlab-ci.yml
Labels: kind: infrastructure

#6958 [lib] Move global options to their proper place.
  kernel/cbytegen.ml
  kernel/cbytegen.mli
  kernel/clambda.ml
  kernel/clambda.mli
  lib/flags.ml
  lib/flags.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#7355 [owners] Makefile.ci belongs to the CI category.
  .github/CODEOWNERS
Labels: kind: infrastructure

#6944 Strict focusing using Default Goal Selector.
  CHANGES
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/tactics.rst
  plugins/ltac/g_ltac.ml4
  plugins/ltac/pptactic.ml
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  pretyping/vernacexpr.ml
  proofs/pfedit.ml
  proofs/proof_bullet.ml
  tactics/tacticals.ml
  test-suite/success/goal_selector.v
Labels: kind: feature, part: tactics

#6935 Separate universe minimization and evar normalization functions
  engine/evarutil.mli
  plugins/funind/glob_termops.ml
  plugins/funind/recdef.ml
  plugins/setoid_ring/newring.ml
  tactics/elimschemes.ml
  tactics/tactics.ml
  vernac/classes.ml
  vernac/comFixpoint.ml
  vernac/comInductive.ml
  vernac/lemmas.ml
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, part: universes

#7379 [doc] Update Sphinx build instructions for Debian derivatives.
  .gitignore
  INSTALL.doc
Labels: kind: documentation
