Repository rocq-prover/rocq, pull requests merged in 2018-09, with the labels that each got.

#8107 Fixes #8106: anomaly if declaring levels for only printing then only parsing
  parsing/notgram_ops.ml
  test-suite/bugs/closed/8106.v
Labels: kind: fix, part: notations

#8286 Fixing #7867: class error message tried to print a "fun" with no binders
  parsing/g_constr.mlg
  test-suite/bugs/closed/7867.v
Labels: kind: fix, part: typeclasses

#8363 Fix #8361: dependency states: camldevfiles
  Makefile.dev
Labels: kind: fix, kind: infrastructure

#8147 [ssr] assertion -> error message (Fix #8134)
  plugins/ssr/ssripats.ml
Labels: kind: fix

#7953 More efficient abstraction over variables in Cooking.
  kernel/cooking.ml
Labels: kind: performance

#8124 Fix #8121: anomalies in native_compute with let and evars.
  kernel/nativecode.ml
  kernel/nativeconv.ml
  kernel/nativeinstr.mli
  kernel/nativelambda.ml
  kernel/nativelambda.mli
  kernel/nativevalues.ml
  kernel/nativevalues.mli
  pretyping/nativenorm.ml
  test-suite/bugs/closed/8121.v
Labels: kind: anomaly, kind: fix, part: native compiler

#8387 Make -compat 8.8 import Coq.Compat.Coq88
  test-suite/success/CompatCurrentFlag.v
  test-suite/success/CompatOldFlag.v
  test-suite/success/CompatPreviousFlag.v
  toplevel/coqargs.ml
Labels: kind: fix

#8264 More efficient computation of avoided variables during pretyping.
  pretyping/pretyping.ml
Labels: kind: performance

#8263 Do not abstract over the named variable in unsafe introduction tactic.
  tactics/tactics.ml
Labels: kind: cleanup

#7968 Restrict universes in comInductive
  test-suite/bugs/closed/7967.v
  vernac/comInductive.ml
Labels: kind: fix, part: universes

#8295 Fix #8291: print universe names in universe context for Check.
  test-suite/output/UnivBinders.out
  test-suite/output/UnivBinders.v
  vernac/vernacentries.ml
Labels: kind: user messages, part: universes

#8420 [pfedit] Fix master build due to merge conflict
  proofs/pfedit.ml
Labels: kind: fix, priority: high

#8415 [bin] Fix binary location procedure to work with symlinks.
  ide/ideutils.ml
  lib/system.ml
Labels: kind: fix, kind: infrastructure

#8394 Print the entire string to the CoqIDE screen, e.g. for "Print Options"
  ide/ideutils.ml
Labels: kind: fix, kind: regression

#8110 Fixing capital letters in the "in" syntax of instantiate.
  doc/sphinx/proof-engine/tactics.rst
  plugins/ltac/extraargs.ml4
Labels: kind: fix

#8412 [dune] [ci] Fix and test release profile + use 1.1 dune-workspace
  .gitlab-ci.yml
  Makefile.dune
  dune
  dune-project
  dune-workspace
Labels: kind: infrastructure

#8411 Changes to default.nix to be able to use Dune.
  default.nix
Labels: kind: infrastructure

#8426 [dune] [doc] Document `dune utop $lib`
  .github/CODEOWNERS
  .ocamlinit
  dev/doc/build-system.dune.md
Labels: kind: documentation, kind: infrastructure

#8435 [dune] Fix build of coq_dune in 4.02.3
  tools/coq_dune.ml
Labels: kind: fix

#8437 Recover lost snippet
  doc/sphinx/addendum/extended-pattern-matching.rst
Labels: kind: documentation, kind: fix

#8430 Move to a team of code owners for the Nix files.
  .github/CODEOWNERS
Labels: kind: meta

#8323 Owners of Makefile.{ci,doc} are teams {ci,doc}-maintainers.
  .github/CODEOWNERS
Labels: kind: infrastructure, kind: meta

#7743 Bound proof-search in default program obligation tactic.
  CHANGES
  theories/Program/Tactics.v
Labels: kind: fix, part: program

#8290 Fix #8288: cumulativity inferance ignores args to bound variables
  pretyping/inferCumulativity.ml
  test-suite/bugs/closed/8288.v
Labels: kind: anomaly, part: universes

#8417 Fixing #8416: Print Assumptions missing module information from compiles files
  test-suite/Makefile
  test-suite/output/PrintAssumptions.out
  test-suite/output/PrintAssumptions.v
  test-suite/prerequisite/module_bug7192.v
  test-suite/prerequisite/module_bug8416.v
  vernac/assumptions.ml
Labels: kind: fix, priority: high

#8230 fix formulation of the Euclid Theorem in comment
  theories/Numbers/Integer/Abstract/ZDivEucl.v
Labels: part: standard library

#8105 Remove environment passing to cache_coercion function
  pretyping/classops.ml
  pretyping/classops.mli
  printing/prettyp.ml
  printing/prettyp.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, part: coercions

#8448 Have `gitFull` in the nix-shell
  default.nix
Labels: kind: infrastructure

#8393 Backport fix #8121: anomalies in native_compute with let and evars.
  kernel/nativecode.ml
  kernel/nativelambda.ml
  pretyping/nativenorm.ml
  test-suite/bugs/closed/8121.v
Labels: kind: fix

#8425 Deprecate romega in favor of lia
  CHANGES
  doc/sphinx/addendum/omega.rst
  plugins/btauto/Algebra.v
  plugins/romega/g_romega.mlg
  theories/FSets/FMapFullAVL.v
  theories/Numbers/Cyclic/Int31/Cyclic31.v
  theories/ZArith/Zquot.v
Labels: kind: cleanup, part: tactics

#8278 Do not inline let-bound functions in clambda optimization.
  kernel/clambda.ml
Labels: kind: fix, kind: performance

#8285 Fixing #8270: cbn was applying zeta even when not asked for.
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  proofs/redexpr.ml
  test-suite/bugs/closed/8270.v
Labels: kind: fix, part: tactics

#8444 Bump version number to 8.10+alpha.
  .bintray.json
  META.coq.in
  configure.ml
Labels: kind: infrastructure

#8372 Grammar rule in the documentation of ssreflect's anonymous arguments
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: hijacked, kind: documentation, part: ssreflect

#8406 building-a-coq-project-with-coq-makefile:fix typos
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation, kind: fix

#8433 Fix bug #8432 : program fixpoint and universes
  test-suite/bugs/closed/8432.v
  vernac/obligations.ml
Labels: kind: fix, part: program, priority: high

#8243 Remove xargs from "make clean" so it won't fail on Cygwin
  Makefile
  test-suite/Makefile
Labels: kind: infrastructure, platform: Windows

#8097 Use more efficient accu check for cofix unfolding in native compilation.
  kernel/nativecode.ml
  kernel/nativevalues.ml
Labels: kind: performance

#8467 Manual: fix documentation of the “fresh” tactic
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation, part: ltac

#8436 Move maps & sets indexed by GlobRef.t into the kernel
  engine/namegen.ml
  engine/univNames.ml
  interp/impargs.ml
  interp/notation.ml
  interp/reserve.ml
  kernel/names.ml
  kernel/names.mli
  library/coqlib.ml
  library/globnames.ml
  library/globnames.mli
  library/keys.ml
  plugins/extraction/extract_env.ml
  plugins/extraction/table.ml
  plugins/firstorder/instances.ml
  plugins/firstorder/sequent.ml
  plugins/setoid_ring/newring.ml
  pretyping/arguments_renaming.ml
  pretyping/classops.ml
  pretyping/recordops.ml
  pretyping/reductionops.ml
  pretyping/typeclasses.ml
  tactics/btermdn.ml
  tactics/hints.ml
  tactics/term_dnet.ml
  vernac/assumptions.ml
  vernac/assumptions.mli
Labels: kind: cleanup

#8485 Missing space in cic.rst
  doc/sphinx/language/cic.rst
Labels: kind: documentation, kind: fix

#8486 Mising prime in the subtyping rules
  doc/sphinx/language/cic.rst
Labels: kind: documentation, kind: fix

#8463 Remove Dischargedhypsmaps
  interp/declare.ml
  library/dischargedhypsmap.ml
  library/dischargedhypsmap.mli
  library/library.mllib
Labels: kind: cleanup

#7343 Add missing index entries.
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation, kind: fix

#8505 Fix Windows builds: OPAM has changed its URL schema.
  dev/build/windows/makecoq_mingw.sh
Labels: kind: fix, kind: infrastructure, platform: Windows

#8297 Fix #7754: universe declarations on mutual inductives
  plugins/funind/glob_term_to_relation.ml
  test-suite/bugs/closed/7754.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: user messages, part: universes

#8518 [dune] Add "watch" target for continuous build mode.
  Makefile.dune
Labels: kind: infrastructure

#8455 Move tests in bugs/ to bugs/closed/.
  test-suite/bugs/closed/2428.v
  test-suite/bugs/closed/4623.v
  test-suite/bugs/closed/4624.v
  test-suite/bugs/closed/7333.v
Labels: kind: cleanup, part: test-suite

#8521 Create a team of micromega maintainers
  .github/CODEOWNERS
Labels: kind: infrastructure

#8462 Zify: replace local definitions by equations
  plugins/omega/PreOmega.v
  test-suite/success/ROmega4.v
Labels: kind: enhancement, part: micromega

#8516 CHANGES for 8.8.2.
  CHANGES
Labels: kind: documentation

#8522 [dune] Improve support for Coq tools.
  tools/coqdoc/dune
  tools/dune
Labels: kind: infrastructure

#8526 Fix Travis CI by pinning brew OPAM package to version 1.2.2.
  .travis.yml
Labels: kind: fix, kind: infrastructure

#8523 Backport of PR #8519, issue #8514 (windows CI failures) to v8.8
  .gitlab-ci.yml
  dev/ci/gitlab.bat
Labels: kind: infrastructure

#8537 [default.nix] Bump nixpkgs to use Dune 1.2.1.
  default.nix
Labels: kind: infrastructure

#8536 Fix #8513: EConstr.eq_constr doesn't properly take into account universe variables
  engine/eConstr.ml
Labels: kind: fix

#8530 Fix typo in comment.
  theories/Numbers/Cyclic/Int31/Int31.v
Labels: kind: fix, kind: internal

#8527 dev/doc/profiling.txt: per-component flame graphs
  dev/doc/profiling.txt
Labels: kind: documentation

#8499 [api] Deprecate constructors of deprecated datatypes.
  plugins/funind/indfun.ml
  plugins/ltac/extratactics.ml4
  plugins/ltac/g_ltac.ml4
  plugins/ltac/g_tactic.mlg
  plugins/ltac/pptactic.ml
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacsubst.ml
  vernac/g_proofs.mlg
  vernac/ppvernac.ml
  vernac/vernacexpr.ml
Labels: kind: compatibility

#8520 [ci] [docker] Move to OPAM 2.0
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#8541 Update flag, option and table descriptions in coqdomain.py, update README.rst to match.
  doc/sphinx/README.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation

#8550 Don't use dune-template for apidoc
  .gitlab-ci.yml
Labels: kind: cleanup, kind: infrastructure

#8542 Add addon dependency management to windows installer
  dev/build/windows/makecoq_mingw.sh
  dev/build/windows/patches_coq/coq_new.nsi
Labels: kind: fix, kind: infrastructure, part: installation, platform: Windows

#6343 [engine] Remove and deprecate `nf_enter` et al.
  dev/doc/changes.md
  engine/ftactic.ml
  engine/ftactic.mli
  engine/proofview.mli
  plugins/btauto/refl_btauto.ml
  plugins/firstorder/rules.ml
  plugins/ltac/evar_tactics.ml
  plugins/ltac/extratactics.ml4
  plugins/ltac/tacinterp.ml
  plugins/ltac/tactic_debug.ml
  plugins/micromega/coq_micromega.ml
  plugins/omega/coq_omega.ml
  plugins/romega/refl_omega.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrparser.ml4
  stm/stm.ml
  tactics/autorewrite.ml
  tactics/class_tactics.ml
  tactics/equality.ml
  tactics/tactics.ml
Labels: kind: cleanup

#8235 NArith: deprecate N2Bv_gen
  CHANGES
  theories/NArith/Ndigits.v
Labels: part: standard library

#8535 Fixing #8532: regression in Print Assumptions within a functor.
  test-suite/bugs/closed/8532.v
  vernac/assumptions.ml
Labels: kind: fix

#8217 Fixes #8215: "critical" type inference bug in interpreting evars by name
  CHANGES
  pretyping/pretyping.ml
  test-suite/bugs/closed/8215.v
Labels: kind: fix, part: elaboration

#8419 Remove romega in favor of lia
  CHANGES
  META.coq.in
  Makefile.common
  Makefile.dev
  dev/ocamldebug-coq.run
  dev/v8-syntax/syntax-v8.tex
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/omega.rst
  plugins/btauto/Reflect.v
  plugins/romega/README
  plugins/romega/ROmega.v
  plugins/romega/ReflOmegaCore.v
  plugins/romega/const_omega.ml
  plugins/romega/const_omega.mli
  plugins/romega/g_romega.mlg
  plugins/romega/plugin_base.dune
  plugins/romega/refl_omega.ml
  plugins/romega/romega_plugin.mlpack
  test-suite/bugs/closed/4717.v
  test-suite/success/ROmega.v
  test-suite/success/ROmega0.v
  test-suite/success/ROmega2.v
  test-suite/success/ROmega3.v
  test-suite/success/ROmegaPre.v
Labels: kind: cleanup, part: tactics

#7309 Made names of existential variables interpretable as Ltac variables.
  CHANGES
  pretyping/globEnv.ml
  pretyping/globEnv.mli
  pretyping/pretyping.ml
  test-suite/success/ltac.v
Labels: kind: enhancement, kind: feature, kind: fix, part: ltac

#7571 [kernel] Compile with almost all warnings enabled.
  kernel/cClosure.ml
  kernel/cbytecodes.ml
  kernel/cbytegen.ml
  kernel/clambda.ml
  kernel/constr.ml
  kernel/context.ml
  kernel/conv_oracle.ml
  kernel/cooking.ml
  kernel/csymtable.ml
  kernel/declareops.ml
  kernel/dune
  kernel/environ.ml
  kernel/indtypes.ml
  kernel/inductive.ml
  kernel/mod_subst.ml
  kernel/modops.ml
  kernel/names.ml
  kernel/nativecode.ml
  kernel/nativeconv.ml
  kernel/nativelambda.ml
  kernel/nativelib.ml
  kernel/opaqueproof.ml
  kernel/reduction.ml
  kernel/subtyping.ml
  kernel/term.ml
  kernel/term_typing.ml
  kernel/typeops.ml
  kernel/uGraph.ml
  kernel/univ.ml
  kernel/vars.ml
  kernel/vconv.ml
  kernel/vm.ml
  kernel/vmvalues.ml
Labels: kind: cleanup

#8534 Checking if low-level name printers are used on purpose or not
  checker/environ.ml
  checker/indtypes.ml
  checker/typeops.ml
  dev/vm_printers.ml
  engine/termops.ml
  engine/termops.mli
  interp/constrextern.ml
  kernel/nativelibrary.ml
  kernel/term_typing.ml
  plugins/ltac/pptactic.ml
  plugins/ltac/tacinterp.ml
  pretyping/cbv.ml
  pretyping/inductiveops.ml
  pretyping/recordops.ml
  pretyping/reductionops.ml
  printing/printer.ml
  tactics/tacticals.ml
  test-suite/output/ltac_missing_args.out
  vernac/auto_ind_decl.ml
Labels: kind: fix

#8506 [ssr] use the right environment in ssrpattern (fix #8454)
  plugins/ssrmatching/ssrmatching.ml
  test-suite/ssr/ssrpattern.v
Labels: kind: fix

#8504 Allow successive attributes #[foo] #[bar]
  doc/sphinx/language/gallina-specification-language.rst
  test-suite/success/attribute-syntax.v
  vernac/g_vernac.mlg
Labels: kind: compatibility

#8497 Use "rm -rf" in "make clean" so .coq-native directories are removed
  Makefile
Labels: kind: fix, kind: infrastructure

#8102 Fix #8043: Unsafe assignment in checker.
  checker/validate.ml
  checker/values.ml
  checker/values.mli
Labels: kind: fix

#8561 Fix votour compilation after #8102.
  checker/votour.ml
Labels: kind: fix

#8571 [stdlib] Fix warning due to missing Declare Scope in Bvector
  theories/Bool/Bvector.v
Labels: kind: fix, part: standard library

#8562 [build] Re-enable warning 59.
  configure.ml
Labels: kind: infrastructure

#8559 [api] Two more missing deprecations.
  vernac/vernacexpr.ml
Labels: kind: cleanup, kind: compatibility

#6524 [print] Restrict use of "debug" Termops printer.
  dev/doc/changes.md
  dev/top_printers.ml
  engine/termops.ml
  engine/termops.mli
  plugins/cc/ccalgo.ml
  plugins/ltac/tactic_debug.ml
  pretyping/evarconv.ml
  pretyping/evardefine.ml
  pretyping/globEnv.ml
  pretyping/inductiveops.ml
  pretyping/pretyping.ml
  pretyping/recordops.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/unification.ml
  printing/printer.ml
  proofs/clenv.ml
  proofs/tacmach.ml
  tactics/class_tactics.ml
  tactics/tacticals.ml
Labels: kind: cleanup

#8570 [ssr] [camlp5] Remove warning from camlp5
  plugins/ssr/ssrparser.ml4
Labels: kind: cleanup

#8545 Functionalize evarmap passing in Cases.ml
  pretyping/cases.ml
  pretyping/cases.mli
  pretyping/pretyping.ml
Labels: kind: cleanup

#8568 [dune] [coqide] Turn CoqIDE into a library.
  ide/dune
Labels: kind: infrastructure

#8569 [dune] [configure] Further tweaks for interactive use.
  Makefile.dune
  config/dune
  configure.ml
Labels: kind: infrastructure

#8576 [api] Remove unnecessary type alias introduced in 8.9
  vernac/classes.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup

#8479 Fix #8478: Undeclared universe anomaly with sections
  engine/univNames.ml
  engine/univNames.mli
  engine/universes.ml
  engine/universes.mli
  interp/declare.ml
  library/lib.ml
  library/lib.mli
  test-suite/bugs/closed/8478.v
Labels: kind: anomaly, kind: fix, part: sections, part: universes

#8597 [dune] Enable warning 60 [unused local module]
  dune-workspace
Labels: kind: infrastructure

#8590 Functionalizing calls to the environment in Himsg
  pretyping/indrec.ml
  pretyping/indrec.mli
  tactics/inv.ml
  vernac/explainErr.ml
  vernac/himsg.ml
  vernac/himsg.mli
  vernac/indschemes.ml
Labels: hijacked, kind: cleanup

#8599 Typo in top_printers.ml
  dev/top_printers.ml
Labels: kind: fix
