Repository rocq-prover/rocq, pull requests merged in 2018-10, with the labels that each got.

#8604 Fix issue 8603 Move Windows CI runs to folder C:/ci
  dev/ci/gitlab.bat
Labels: kind: ci-failure, kind: infrastructure, platform: Windows

#8301 Documentation for proof diffs
  doc/sphinx/README.rst
  doc/sphinx/_static/diffs-coqide-compacted.png
  doc/sphinx/_static/diffs-coqide-multigoal.png
  doc/sphinx/_static/diffs-coqide-on.png
  doc/sphinx/_static/diffs-coqide-removed.png
  doc/sphinx/_static/diffs-coqtop-compacted.png
  doc/sphinx/_static/diffs-coqtop-multigoal.png
  doc/sphinx/_static/diffs-coqtop-on.png
  doc/sphinx/_static/diffs-coqtop-on3.png
  doc/sphinx/biblio.bib
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proof-engine/proof-handling.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation

#517 Some lemmas about dependent equality
  theories/Init/Datatypes.v
  theories/Init/Logic.v
  theories/Init/Specif.v
Labels: kind: feature, part: standard library

#8606 [dune] [configure] Fix typo in default prefix setting.
  configure.ml
Labels: kind: fix, kind: infrastructure

#8501 [classes] Split large `new_instance` function up.
  vernac/classes.ml
  vernac/classes.mli
Labels: kind: cleanup

#8177 Make the warning for non-imported hints compatible with internal backtracking
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: user messages

#7634 Extend combined scheme to Schemes in Type
  CHANGES
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/user-extensions/proof-schemes.rst
  library/coqlib.ml
  library/coqlib.mli
  test-suite/success/CombinedScheme.v
  vernac/indschemes.ml
Labels: kind: fix

#8579 [dune] [merlin] Fix some usability issues.
  dev/doc/build-system.dune.md
  dune-project
  dune-workspace
  kernel/.merlin.in
Labels: kind: infrastructure

#8575 Remove {Safe_typing,Global}.push_context
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  library/global.ml
  library/global.mli
Labels: kind: cleanup, part: universes

#8254 Inline the definition of CClosure.mk_clos_deep.
  kernel/cClosure.ml
Labels: kind: cleanup

#7372 Four new lemmas for lists
  theories/Lists/List.v
Labels: kind: feature, part: standard library

#8531 [ci] Add plugin-tutorial to CI.
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-plugin-tutorial.sh
Labels: kind: infrastructure

#7522 [ocaml] Update required OCaml version to 4.05.0
  .gitlab-ci.yml
  .travis.yml
  CHANGES
  INSTALL
  configure.ml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/doc/profiling.txt
  kernel/nativelib.ml
  test-suite/coqchk/cumulativity.v
  tools/coq_dune.ml
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: infrastructure

#8612 Fix issue 8610 - Change important CI DOS batch files to CRLF
  dev/build/windows/MakeCoq_MinGW.bat
  dev/ci/gitlab.bat
Labels: kind: infrastructure, platform: Windows

#8614 [dune] [doc] Some tweaks to doc + per user flags.
  dev/doc/build-system.dune.md
Labels: kind: documentation, kind: infrastructure

#8623 [dune] Fix PHONY target in Dune's helper makefile.
  Makefile.dune
Labels: kind: infrastructure

#8625 Fix issue #8611 - Change extensions of log files in WIndows build to …
  dev/build/windows/makecoq_mingw.sh
Labels: kind: infrastructure, platform: Windows

#8613 [ci] [travis] Remove CI contrib testing from Travis.
  .github/CODEOWNERS
  .travis.yml
  Makefile.ci
  dev/ci/ci-common.sh
  dev/tools/sudo-apt-get-update.sh
Labels: kind: infrastructure

#8629 [doc] Nits on utilities / toplevel building.
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation, kind: infrastructure

#8596 [api] Cleanup `Decls`: remove unused function, move vernac helper.
  library/decls.ml
  library/decls.mli
  pretyping/typeclasses.ml
  pretyping/typeclasses.mli
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/obligations.ml
Labels: kind: cleanup

#8563 Fix checker soundness bug with polymorphism capturing global univs
  checker/checker.ml
  checker/univ.ml
Labels: kind: fix, part: checker, priority: critical

#8631 [dune] Fix couple of minor bugs in #8617
  Makefile.dune
  dev/dune-workspace.all
Labels: kind: infrastructure

#8639 [api] Be more explicit about deprecation of debug printers.
  engine/termops.mli
Labels: kind: cleanup, kind: compatibility

#7361 Towards selecting "best" unification failure among several
  pretyping/evarconv.ml
  test-suite/output/unifconstraints.out
  test-suite/output/unifconstraints.v
Labels: kind: enhancement, kind: user messages, part: elaboration, part: unification

#8626 [ocaml] [lib] Remove some compatibility layers for OCaml < 4.03.0
  clib/cString.ml
  clib/cString.mli
  clib/hashcons.ml
  ide/preferences.ml
  ide/protocol/xml_lexer.mll
  parsing/pcoq.mli
  plugins/extraction/common.ml
  plugins/extraction/haskell.ml
  plugins/extraction/table.ml
  tools/coqdep_common.ml
  tools/coqdep_lexer.mll
  tools/coqdoc/alpha.ml
  tools/coqdoc/index.ml
  tools/coqdoc/output.ml
  tools/ocamllibdep.mll
Labels: kind: cleanup, kind: compatibility

#8636 [doc] [api] Remove `ocamldoc` support in favor of `odoc`
  .gitignore
  .gitlab-ci.yml
  Makefile
  Makefile.doc
  dev/README.md
  dev/ci/README.md
  dev/ocamldoc/docintro
  dev/ocamldoc/fix-ocamldoc-utf8
  dev/ocamldoc/header.tex
  dev/ocamldoc/html/style.css
Labels: kind: documentation, kind: infrastructure

#8650 [ci] [dune] [opam] Fixes to OPAM and CI target.
  .gitlab-ci.yml
  INSTALL
  coq.opam
  dev/ci/docker/bionic_coq/Dockerfile
  ide/coqide.opam
  ide/dune-workspace
Labels: kind: infrastructure

#8661 CI: fix Iris and stdpp ref selection
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-iris-lambda-rust.sh
Labels: kind: fix, kind: infrastructure

#8658 Remove duplicate committers.
  .mailmap
Labels: kind: infrastructure

#8582 [api] Deprecate `evar_map` ref combinators.
  engine/evarutil.mli
  plugins/funind/functional_principles_types.ml
  pretyping/cases.ml
  pretyping/evarsolve.ml
  pretyping/indrec.ml
  tactics/inv.ml
Labels: kind: cleanup

#8627 [dune] [opam] Install `revision` file when building with Dune.
  .github/CODEOWNERS
  Makefile.dev
  configure.ml
  dev/tools/make_git_revision.sh
  dune
Labels: kind: cleanup, kind: fix, part: build

#8660 Issue 8659 not always build all addons
  .gitlab-ci.yml
  dev/ci/README.md
  dev/ci/gitlab.bat
Labels: kind: infrastructure, platform: Windows

#8654 Remove FCast from CClosure.fterm.
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/reduction.ml
  pretyping/inferCumulativity.ml
Labels: kind: cleanup

#8657 [dune] Refactor files following advice from upstream.
  .gitlab-ci.yml
  coqide.opam
  dune
  dune-workspace
  ide/dune-project
  ide/dune-workspace
Labels: kind: infrastructure

#8677 [dune] Fix bad interaction among PR #8627 and #8657
  dune
Labels: kind: fix, kind: infrastructure

#8674 [ci] Add aac-tactics.
  .gitlab-ci.yml
  Makefile.ci
  dev/build/windows/makecoq_mingw.sh
  dev/ci/ci-aac-tactics.sh
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#8676 Fixes #8672: ill-formed pattern substitution in notation with "let"
  interp/notation_ops.ml
  test-suite/bugs/closed/8672.v
Labels: kind: fix, part: notations

#8673 Remove dead code in universe handling in the abstract tactical.
  tactics/tactics.ml
Labels: kind: cleanup

#8651 [dune] Provide an optimized build profile with inlining reports.
  Makefile.dune
  dev/doc/build-system.dune.md
  dev/dune-workspace.all
  dune
Labels: kind: infrastructure

#8692 [test-suite] Don't reset `OCAMLPATH`, but append to it.
  test-suite/Makefile
Labels: kind: fix

#8384 Small fixes in attribute documentation.
  doc/sphinx/language/gallina-specification-language.rst
Labels: kind: documentation, kind: fix

#8701 Fix build of Nix package with sandbox.
  default.nix
Labels: kind: fix, kind: infrastructure

#8644 [build] enable warnings on kernel/% in make based builds
  Makefile.build
Labels: kind: infrastructure, part: build

#8648 Add minimal CHANGES entry about deprecated compat notations
  CHANGES.md
Labels: kind: documentation, priority: blocker

#8697 [dune] Fix public name of tool: coq_tex -> coq-tex
  tools/dune
Labels: kind: infrastructure

#8699 [quote] Remove spurious file after deletion of quote plugin.
  plugins/quote/plugin_base.dune
  plugins/setoid_ring/plugin_base.dune
Labels: kind: cleanup

#8681 [dune] Fix and improve flags:
  dune
Labels: kind: infrastructure

#8702 [coq_dune] Abstract path operations wrt directory separator.
  tools/coq_dune.ml
Labels: kind: infrastructure

#8594 Miscellaneous refinements and cleaning of module printing
  printing/printmod.ml
  test-suite/output/PrintModule.out
  test-suite/output/PrintModule.v
Labels: kind: cleanup, kind: fix

#8680 Check that lambda/prod ast's have proper binders during interning/printing
  interp/constrintern.ml
  printing/ppconstr.ml
Labels: kind: cleanup

#8703 [vernac] Remove unused `start_hook` `save_hook` from Lemmas.
  vernac/lemmas.ml
  vernac/lemmas.mli
Labels: kind: cleanup

#8714 Documenting -arg in _CoqProject.
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#8652 Add missing indexes for Hint Cut and Hint Mode.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#8546 [ci] Allow bedrock to fail.
  .gitlab-ci.yml
Labels: kind: infrastructure

#8732 [ci] [sf] Remove sed hacks from the SF build.
  dev/ci/ci-sf.sh
Labels: kind: infrastructure

#8716 Lemmas: Little simplification of artificially convoluted code
  vernac/lemmas.ml
Labels: kind: cleanup

#8589 Correct some spelling errors (continued)
  doc/sphinx/proof-engine/tactics.rst
  doc/tools/Translator.tex
  ide/nanoPG.ml
  kernel/clambda.ml
  lib/future.ml
  lib/future.mli
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/recdef.ml
  plugins/omega/PreOmega.v
  plugins/omega/omega.ml
  plugins/ssrmatching/ssrmatching.ml
  stm/stm.ml
  test-suite/bugs/closed/bug_4132.v
  test-suite/success/univers.v
  tools/coq_makefile.ml
  tools/coqdoc/output.ml
  tools/coqworkmgr.ml
  vernac/comProgramFixpoint.ml
  vernac/obligations.ml
Labels: kind: fix

#8742 [clib] Remove Array functions available in OCaml 4.05.0
  clib/cArray.ml
  clib/cArray.mli
Labels: kind: cleanup

#8738 [clib] Deprecate string functions available in OCaml 4.05
  clib/cString.ml
  clib/cString.mli
  ide/coqide.ml
  ide/preferences.ml
  lib/envars.ml
  plugins/ltac/profile_ltac.ml
  tools/coq_makefile.ml
  toplevel/coqargs.ml
Labels: kind: cleanup

#8754 [doc] [build] Remove ocamlbuild leftovers.
  .gitignore
  Makefile
  dev/doc/build-system.txt
  dev/doc/ocamlbuild.txt
  tools/coq_makefile.ml
Labels: kind: cleanup

#8756 [micromega] Build csdpcert
  plugins/micromega/plugin_base.dune
Labels: kind: infrastructure

#8724 [universes] deprecate constr_of_global
  engine/univGen.ml
  engine/univGen.mli
  plugins/btauto/refl_btauto.ml
  plugins/firstorder/rules.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/indfun_common.ml
  plugins/funind/invfun.ml
  plugins/funind/recdef.ml
  plugins/nsatz/nsatz.ml
  plugins/omega/coq_omega.ml
  plugins/rtauto/refl_tauto.ml
  plugins/setoid_ring/newring.ml
  plugins/ssr/ssrcommon.ml
  proofs/tacmach.ml
  proofs/tacmach.mli
  vernac/auto_ind_decl.ml
  vernac/obligations.ml
Labels: kind: cleanup

#8758 [api] Qualify access to `Nametab`
  engine/namegen.ml
  interp/constrextern.ml
  interp/constrintern.ml
  interp/syntax_def.ml
  library/coqlib.ml
  plugins/ltac/tacenv.ml
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  pretyping/classops.ml
  pretyping/detyping.ml
  pretyping/indrec.ml
  pretyping/recordops.ml
  printing/printer.ml
  vernac/class.ml
  vernac/classes.ml
  vernac/comInductive.ml
  vernac/indschemes.ml
  vernac/search.ml
Labels: kind: cleanup

#8782 gitignore test-suite/.nia.cache
  .gitignore
Labels: kind: infrastructure

#8769 [library] Remove redundant re-addition of universe constraints.
  interp/declare.ml
Labels: kind: cleanup

#8708 Stupid but critical unfolding heuristic.
  checker/reduction.ml
  kernel/conv_oracle.ml
Labels: kind: performance

#8797 [doc] [api] Update `odoc` to new release 1.3.0
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#8786 Adding a regression test for bug #8785: universe constraints missing
  test-suite/bugs/closed/bug_8785.v
Labels: kind: fix

#8802 [dune] Install man pages + remove two obsolete ones.
  man/coq-interface.1
  man/coq-parser.1
  man/dune
Labels: kind: documentation, kind: infrastructure

#8799 Fix formatting. Use standard if..then grammar.
  doc/sphinx/proof-engine/proof-handling.rst
Labels: kind: documentation, kind: fix

#8798 Order Greek letters consistently w/rest of document
  doc/sphinx/language/cic.rst
Labels: kind: documentation

#8806 Fixing #8794: anomaly with abbreviation binding both a term and a binder
  interp/notation_ops.ml
  test-suite/bugs/closed/bug_8794.v
Labels: kind: fix

#8776 Replace non-idiomatic "dead-alleys" with idiomatic "dead-ends"
  doc/sphinx/credits.rst
Labels: kind: documentation

#8813 Fix a few rendering issues in the manual
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation

#8762 [dune] [opam] Move to OPAM 2.0
  .gitlab-ci.yml
  coq.opam
  coqide-server.opam
  coqide.opam
  dev/ci/docker/bionic_coq/Dockerfile
  dev/dune-workspace.all
  dune
  dune-project
Labels: kind: infrastructure

#7186 Moving `fold_constr_with_full_binders` to a place
  engine/termops.ml
  kernel/constr.ml
  kernel/constr.mli
  vernac/assumptions.ml
Labels: kind: cleanup

#8777 Move side-effects into Safe_typing
  kernel/safe_typing.ml
  kernel/term_typing.ml
  kernel/term_typing.mli
Labels: kind: cleanup

#8821 [default.nix] Update to dune 1.4.
  default.nix
Labels: kind: infrastructure

#8753 [build] Refactoring of config lib and ocamldebug tweaks.
  .gitignore
  META.coq.in
  Makefile
  Makefile.build
  Makefile.checker
  Makefile.common
  Makefile.dev
  Makefile.ide
  checker/check.mllib
  config/config.mllib
  dev/base_db
  dev/checker.dbg
  dev/checker_db
  dev/checker_printers.dbg
  dev/core.dbg
  dev/db
  dev/top_printers.dbg
  lib/lib.mllib
Labels: kind: cleanup, kind: infrastructure

#8804 Fix issue #8801 (uncaught Not_found after F1 sequence in coqide)
  ide/wg_Command.ml
Labels: kind: fix, part: IDE

#8803 Fix issue #8800 (gtk warning about gtk_scrolled_window_add_with_viewport)
  ide/wg_Command.ml
Labels: kind: fix, part: IDE

#8814 Comment Environ.set_universes
  kernel/environ.mli
Labels: kind: internal

#8827 Revert "[ci] Pin CI_REF to plugin_tutorial to use not yet merged commit."
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#8780 Cleanup comparing projections through their constants.
  kernel/names.ml
  kernel/names.mli
  pretyping/evarconv.ml
  pretyping/reductionops.ml
Labels: kind: cleanup

#8737 Correctly report non-projection fields in records
  interp/constrintern.ml
  test-suite/output/RecordFieldErrors.out
  test-suite/output/RecordFieldErrors.v
Labels: kind: fix, kind: user messages

#8765 Give code ownership of merging doc to pushers team to notify members when it changes.
  .github/CODEOWNERS
Labels: kind: infrastructure, kind: meta

#8830 Fix #8410: Welcome flood from Coqide.
  toplevel/coqtop.ml
Labels: kind: fix, kind: regression, part: IDE

#8751 Rename checker/{main->coqchk}
  Makefile.checker
  checker/coqchk.ml
  checker/coqchk.mli
  checker/dune
Labels: kind: cleanup, part: checker

#8750 [ci] [doc] Notes about branch names.
  dev/ci/README.md
  dev/ci/user-overlays/README.md
Labels: kind: documentation, kind: infrastructure

#8849 Fix for bug #8848.
  pretyping/evarsolve.ml
  test-suite/bugs/closed/bug_8848.v
Labels: kind: fix

#8851 Credits for 8.9
  doc/sphinx/credits.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#8825 [libobject] Move object_name next to object definition.
  interp/declare.mli
  library/declaremods.mli
  library/lib.ml
  library/lib.mli
  library/libnames.ml
  library/libnames.mli
  library/libobject.ml
  library/libobject.mli
  printing/prettyp.mli
Labels: kind: cleanup

#8869 Bump version number to 8.9+beta1.
  .bintray.json
  configure.ml
Labels: kind: infrastructure

#8867 Notations: fixing a bug when printing abbreviations in custom entries.
  interp/constrextern.ml
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: kind: fix

#8841 Share the construction of the evar instance in Clenv.make_evar_clause.
  proofs/clenv.ml
Labels: kind: fix, kind: performance

#8759 Fix #8755: Uncaught exception Ltac_plugin.Taccoerce.CannotCoerceTo.
  plugins/ltac/tacinterp.ml
  test-suite/bugs/closed/bug_8755.v
Labels: kind: fix

#8752 Enable fragile pattern warning in cclosure
  kernel/cClosure.ml
Labels: kind: cleanup, part: kernel
