Repository rocq-prover/rocq, pull requests merged in 2018-06, with the labels that each got.

#7660 Add codeowner for timing python scripts
  .github/CODEOWNERS
Labels: kind: infrastructure

#7606 Allow more than one signature and name per Sphinx object
  doc/sphinx/README.rst
  doc/sphinx/README.template.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: infrastructure

#7234 Reduce circular dependency constants <-> projections
  checker/cic.mli
  checker/environ.ml
  checker/environ.mli
  checker/mod_checking.ml
  checker/values.ml
  kernel/clambda.ml
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/inductive.ml
  kernel/nativecode.ml
  kernel/term_typing.ml
  kernel/typeops.ml
  kernel/typeops.mli
  library/heads.ml
  plugins/extraction/extraction.ml
  pretyping/inductiveops.ml
  tactics/hints.ml
Labels: kind: cleanup, part: kernel

#7680 [ci] Expose updated `OCAMLPATH` for CI users.
  dev/ci/ci-common.sh
  dev/ci/ci-pidetop.sh
Labels: kind: infrastructure

#7681 Fixes #7636: location missing on deprecated compatibility notations.
  interp/constrintern.ml
  interp/syntax_def.ml
  interp/syntax_def.mli
Labels: kind: fix

#7683 [lib] Fix wrong deprecation annotations.
  clib/cMap.ml
  clib/cMap.mli
Labels: kind: fix

#7689 configure: fix warning printing
  configure.ml
Labels: kind: user messages

#7682 Fixes #7641: more detailed message about disjunctive patterns with different variables
  interp/constrintern.ml
Labels: kind: fix

#7649 Remove some dead code in class_tactics.ml
  tactics/class_tactics.ml
Labels: kind: cleanup, part: typeclasses

#7640 Small refactoring to clarify make_local_hint_db.
  tactics/hints.ml
Labels: kind: cleanup

#7657 Fix a couple typos in deprecation messages
  vernac/vernacexpr.ml
Labels: kind: documentation, kind: fix

#7496 Fix #4403: insufficient handling of type-in-type in kernel.
  kernel/reduction.ml
  test-suite/bugs/closed/4403.v
Labels: kind: fix, part: universes

#7619 Mention test-suite in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind: infrastructure

#7648 Indicate in the doc that clearbody can take several idents
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#7590 Fix #7586: Anomaly "Uncaught exception Not_found".
  pretyping/unification.ml
  test-suite/bugs/closed/7392.v
Labels: kind: fix

#7552 Fix #7539: Checker does not properly handle negative coinductive types.
  checker/closure.ml
  test-suite/coqchk/bug_7539.v
Labels: kind: fix

#7216 Replace uses of Termops.dependent by more specific functions.
  engine/termops.ml
  engine/termops.mli
  plugins/firstorder/unify.ml
  pretyping/cases.ml
  pretyping/evarsolve.ml
  pretyping/unification.ml
  tactics/equality.ml
  tactics/inv.ml
Labels: kind: cleanup

#7013 Fixes #7011: Fix/CoFix were not considered in main loop of tactic unification.
  pretyping/unification.ml
  test-suite/bugs/closed/7011.v
Labels: kind: fix, part: unification

#7349 Fix an anomaly when calling Obligation 0 or Obligation -1.
  vernac/obligations.ml
Labels: kind: anomaly, kind: fix, part: program

#7189 Fix #5539: algebraic universe produced by cases.
  pretyping/cases.ml
  test-suite/bugs/closed/5539.v
Labels: kind: fix, part: universes

#7114 Fix #7113: Program Let Fixpoint in section causes anomaly
  test-suite/bugs/closed/7113.v
  vernac/obligations.ml
Labels: kind: anomaly, kind: fix, part: program

#7199 Fixes #7195: missing freshness condition in Ltac pattern-matching names
  pretyping/constr_matching.ml
  test-suite/bugs/closed/7195.v
Labels: kind: fix, part: ltac

#7418 Actually take advantage of the normalization status of kernel closures.
  kernel/cClosure.ml
Labels: kind: performance

#7601 Fix notation for code snippet in documentation
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation, kind: fix

#7655 Refactor parsing rules for Hint Resolve -> and Hint Resolve <-
  plugins/ltac/extratactics.ml4
  tactics/hints.ml
  tactics/hints.mli
  vernac/g_proofs.ml4
  vernac/ppvernac.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup

#7596 [ci] [windows] Use newer OCaml version.
  dev/build/windows/makecoq_mingw.sh
  dev/build/windows/patches_coq/lablgtk-2.18.6.patch
  dev/ci/appveyor.sh
Labels: kind: infrastructure, platform: Windows

#7481 document 7025 (coq_makefile flag variables)
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#7486 Update old parts of CHANGES to use current bug numbers.
  CHANGES
Labels: kind: cleanup, kind: documentation

#7315 An attempt to clarify error message for Arguments needing "rename" flag
  test-suite/output/Arguments_renaming.out
  vernac/vernacentries.ml
Labels: kind: enhancement, kind: user messages

#7453 Refuse to parse empty [Context] command.
  vernac/g_vernac.ml4
Labels: kind: fix

#7646 Fix #4714: Stack overflow with native compute
  kernel/nativelambda.ml
Labels: kind: fix, part: native compiler

#7690 Fixing typos in file Berardi.v
  theories/Logic/Berardi.v
Labels: kind: fix, part: standard library

#7643 Fix #7631: native_compute fails to compile an example in Coq 8.8
  kernel/constr.ml
  kernel/constr.mli
  kernel/nativecode.ml
  test-suite/bugs/closed/7631.v
Labels: kind: fix, part: native compiler

#7464 Make whitespace linter not check for trailing space.
  .gitattributes
Labels: kind: infrastructure

#7663 test suite: make target to regenerate failing output tests
  test-suite/Makefile
  test-suite/README.md
Labels: kind: infrastructure, part: test-suite

#7004 Make `simple apply` obey `Opaque` directive.
  CHANGES
  plugins/ssrmatching/ssrmatching.ml4
  pretyping/unification.ml
  pretyping/unification.mli
  tactics/tactics.ml
Labels: kind: fix, part: tactics, part: unification

#7717 [ci] Temporal fix for CompCert
  dev/ci/ci-compcert.sh
Labels: kind: infrastructure

#7706 Fix wrong deprecation msg
  engine/evarutil.mli
Labels: kind: fix

#7629 Fix anomaly in autoapply when an unbound hint name is provided
  tactics/class_tactics.ml
Labels: kind: anomaly, kind: fix, part: tactics

#7735 Remove cross-crypto from Travis. It is still tested in GitLab CI.
  .travis.yml
Labels: kind: infrastructure

#7687 [ci] [docker] Pin specific versions of OPAM CI dependencies.
  .circleci/config.yml
  .gitlab-ci.yml
  dev/ci/ci-compcert.sh
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#7417 Micromega clean-up
  plugins/micromega/certificate.ml
  plugins/micromega/certificate.mli
  plugins/micromega/coq_micromega.ml
  plugins/micromega/coq_micromega.mli
  plugins/micromega/csdpcert.ml
  plugins/micromega/csdpcert.mli
  plugins/micromega/g_micromega.mli
  plugins/micromega/mfourier.ml
  plugins/micromega/mfourier.mli
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/persistent_cache.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  plugins/micromega/sos.ml
  plugins/micromega/sos_lib.ml
  plugins/micromega/sos_lib.mli
Labels: kind: cleanup, part: micromega

#7747 dev/doc/univpoly.{txt => md}, split off primitive projection info
  dev/doc/primproj.md
  dev/doc/universes.md
  dev/doc/universes.txt
Labels: kind: cleanup, kind: documentation

#7739 add test for #7595
  test-suite/misc/7595.sh
  test-suite/misc/7595/FOO.v
  test-suite/misc/7595/base.v
Labels: kind: infrastructure, part: test-suite

#7642 Gitlab: retry failed jobs once
  .gitlab-ci.yml
Labels: kind: infrastructure

#7515 gitlab: build sphinx doc in separate job
  .gitlab-ci.yml
  Makefile.doc
  doc/tools/coqrst/repl/coqtop.py
Labels: kind: cleanup, kind: enhancement, kind: infrastructure

#7691 Fixing spelling of statment/statement in two API types
  parsing/extend.ml
  parsing/pcoq.ml
  parsing/pcoq.mli
Labels: kind: fix

#7736 [ci] Fix GeoCoq after https://github.com/GeoCoq/GeoCoq/issues/12
  dev/ci/ci-common.sh
  dev/ci/ci-geocoq.sh
Labels: kind: infrastructure

#7757 [lib] Fix wrong deprecation comment.
  clib/cList.ml
  clib/cList.mli
Labels: kind: fix

#7748 Add a bit of doc to EConstr.decompose_lam*
  engine/eConstr.mli
Labels: kind: documentation

#7761 Fixing #7700: section variables bound to abbreviations were not found
  interp/constrintern.ml
  test-suite/bugs/closed/7700.v
Labels: kind: fix

#6827 [VM] Remove projection names from structured constants.
  dev/vm_printers.ml
  kernel/cbytecodes.ml
  kernel/cbytecodes.mli
  kernel/cemitcodes.ml
  kernel/cemitcodes.mli
  kernel/csymtable.ml
  kernel/vmvalues.ml
  kernel/vmvalues.mli
Labels: kind: cleanup, part: VM

#7008 Bump version number to 8.9+alpha1
  .bintray.json
  META.coq
  configure.ml
Labels: kind: infrastructure

#7782 [VM] Rename reloc -> cenv
  kernel/cbytegen.ml
Labels: kind: cleanup, part: VM

#7789 Fixes #7779: destruct's "in" clause was forgetting the possibility of an "eqn" clause
  tactics/tactics.ml
  test-suite/bugs/closed/7779.v
Labels: kind: fix

#7241 [coq_makefile] COQMF_WINDRIVE is empty on linux (fix #7233)
  tools/CoqMakefile.in
  tools/coq_makefile.ml
Labels: kind: fix, kind: regression

#7800 Markdown docs: switch from absolute to relative links.
  CONTRIBUTING.md
  README.md
  dev/ci/README.md
  dev/ci/user-overlays/README.md
  dev/doc/MERGING.md
  test-suite/README.md
Labels: kind: documentation

#7790 [ci] Require runner `docker` tag on `docker-boot` job.
  .gitlab-ci.yml
Labels: kind: infrastructure

#7771 Tweak printing boxes for unicode binders
  test-suite/output/Unicode.out
  test-suite/output/Unicode.v
  theories/Unicode/Utf8_core.v
Labels: kind: enhancement, part: notations, part: standard library

#7105 Getting rid of some false "collision between bound variable names" warnings
  pretyping/glob_ops.ml
Labels: kind: enhancement, kind: user messages

#7193 Fixes #7192: Print Assumptions does not enter implementation of submodules.
  library/global.ml
  library/global.mli
  test-suite/output/PrintAssumptions.out
  test-suite/output/PrintAssumptions.v
  vernac/assumptions.ml
Labels: kind: fix, priority: high

#7809 Fix deprecation warning introduced by PR 664 merge
  pretyping/cases.ml
Labels: kind: fix

#7813 Workaround for #2800: handling non-value arguments in tactics.
  plugins/ltac/tacinterp.ml
  test-suite/bugs/closed/2800.v
Labels: kind: anomaly, kind: fix

#7814 doc: Add "Print Canonical Projections" command to Command index
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation

#7635 Define rec_declaration in terms of prec_declaration.
  kernel/constr.ml
  kernel/constr.mli
Labels: kind: cleanup

#7752 [merge script] Check if the CI that was run is outdated.
  dev/tools/merge-pr.sh
Labels: kind: infrastructure

#7818 Do not allow spliting in res_pf, this is reserved for pretyping
  proofs/clenvtac.ml
  test-suite/success/Hints.v
Labels: kind: fix

#7828 [Spawn] no control sock on unix
  lib/spawn.ml
  lib/spawn.mli
  stm/spawned.ml
Labels: kind: fix

#7844 Remove Elpi from Travis.
  .travis.yml
Labels: kind: infrastructure

#7822 cArray: proper invalid_arg exceptions
  clib/cArray.ml
Labels: kind: fix

#7848 Fix a typo in documentation
  doc/sphinx/addendum/generalized-rewriting.rst
Labels: kind: documentation, kind: fix

#7824 Fixes #7811 (uncaught Not_found in notation printer related to "match").
  pretyping/glob_ops.ml
  test-suite/bugs/closed/7811.v
Labels: kind: fix, part: notations

#7849 Fix #7615: Functor inlining drops universe substitution.
  CHANGES
  checker/declarations.ml
  kernel/mod_subst.ml
  kernel/modops.ml
  test-suite/bugs/closed/7615.v
Labels: kind: fix, priority: critical

#7840 Remove Hashcons.Hobj
  clib/hashcons.ml
  clib/hashcons.mli
Labels: kind: cleanup

#7855 Update section on adding your project to CI and link to example PR.
  dev/ci/README.md
Labels: kind: documentation, kind: infrastructure

#7856 Fix #7829: Spurious documentation failures.
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: infrastructure

#7841 Remove Canary
  checker/check.mllib
  checker/values.ml
  clib/canary.ml
  clib/canary.mli
  clib/clib.mllib
  kernel/names.ml
Labels: kind: cleanup

#7801 [vernac] Add option to force building really mutual induction schemes
  pretyping/indrec.ml
  pretyping/indrec.mli
  vernac/indschemes.ml
  vernac/indschemes.mli
Labels: kind: enhancement, kind: fix

#7491 Fix #7421: constr_eq ignores universe constraints.
  CHANGES
  doc/sphinx/proof-engine/tactics.rst
  engine/evd.ml
  engine/evd.mli
  plugins/ltac/extratactics.ml4
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/bugs/closed/7421.v
Labels: kind: fix, part: tactics, part: universes

#7842 Fix #7836: tools/inferior-coq.el uses next-line instead of forward-line.
  tools/inferior-coq.el
Labels: kind: fix, part: tools

#7815 On cygwin, pass the filename in a format that coqdoc understands.
  doc/tools/coqrst/coqdoc/main.py
Labels: kind: fix, platform: Windows

#7770 Move indices on top on the TOC. Closes #7764.
  doc/sphinx/conf.py
  doc/sphinx/credits.rst
  doc/sphinx/index.rst
  doc/sphinx/introduction.rst
Labels: kind: documentation

#7873 Make Clément the secondary codeowner of doc/tools/coqrst.
  .github/CODEOWNERS
Labels: kind: infrastructure, kind: meta

#7774 [build] Fix checks and notes noting 4.02.1 instead of 4.02.3
  INSTALL.ide
  configure.ml
  dev/doc/profiling.txt
Labels: kind: fix

#7893 Update dpdgraph branch name
  dev/ci/ci-basic-overlay.sh
Labels: kind: fix, kind: infrastructure

#7715 Simplify the cooking of primitive projections.
  kernel/cooking.ml
Labels: kind: cleanup

#7827 [engine] safe [add_unification_pb] interface
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  pretyping/evarconv.ml
Labels: kind: fix, part: unification

#7772 [native_compute] Delay computations with toplevel match
  kernel/nativelambda.ml
Labels: kind: performance

#7805 Towards listing the critical bugs of the history of Coq.
  dev/doc/critical-bugs
Labels: help wanted, kind: documentation

#7895 Revert "Add a note about [ci skip] in CI README."
  dev/ci/README.md
Labels: kind: documentation

#7559 Existing Class noop when already a class + warning.
  doc/sphinx/addendum/type-classes.rst
  test-suite/bugs/closed/5012.v
  vernac/record.ml
Labels: kind: fix, part: typeclasses

#7851 Modernize the introduction of the reference manual.
  doc/sphinx/biblio.bib
  doc/sphinx/index.rst
  doc/sphinx/introduction.rst
Labels: kind: documentation

#7919 Fix equality check on global names from native compute.
  kernel/nativecode.ml
Labels: kind: fix, part: native compiler

#7775 Fix handling of universe context for expanded program obligations.
  vernac/obligations.ml
Labels: kind: anomaly, kind: fix

#7826 evd: restrict_evar with candidates, can raise NoCandidatesLeft
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  tactics/tactics.ml
Labels: kind: enhancement

#7924 Ad hoc fix for #5696, #7903 (ltac subterms and open subterms in notations).
  interp/constrintern.ml
  test-suite/bugs/closed/5696.v
  test-suite/bugs/closed/7903.v
Labels: kind: fix

#7939 Turn the CoqProject_file module into a pure ML file
  lib/coqProject_file.ml
Labels: kind: cleanup

#7934 Add mit-plv/bedrock2-ci to CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-bedrock2.sh
Labels: kind: infrastructure

#7932 CoqIDE scrolls the proof buffer down to the first goal.
  ide/wg_ProofView.ml
Labels: kind: enhancement, kind: regression, part: IDE

#7917 Critical bugs: added #3243 and Gonthier's bug in lazy machine.
  dev/doc/critical-bugs
Labels: kind: documentation

#7937 Mention Consortium in README
  README.md
Labels: kind: documentation

#7946 Update maintainers for native/VM files in pretyping
  .github/CODEOWNERS
Labels: kind: infrastructure, kind: meta

#7928 Fix 'unbound variable' issue on Windows packaging jobs.
  dev/build/windows/makecoq_mingw.sh
Labels: kind: fix, kind: infrastructure, platform: Windows

#7948 Syntax for naming an existential variable
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation, kind: fix, kind: regression

#7860 Fix #7704: Launching coqide through PATH fails.
  lib/system.ml
  test-suite/Makefile
  test-suite/misc/7704.sh
  test-suite/misc/aux7704.v
Labels: kind: fix

#7955 Set Coq version to 8.8.1.
  .bintray.json
  configure.ml
Labels: kind: infrastructure

#7890 Inline a function from Quote used in setoid_ring.
  plugins/setoid_ring/g_newring.ml4
  plugins/setoid_ring/newring.ml
  plugins/setoid_ring/newring.mli
Labels: kind: cleanup

#7918 Mini-update of version history with recent changes.
  dev/doc/versions-history.tex
Labels: kind: documentation

#7949 Split the Ssrmatching module between code and grammar rules.
  plugins/ssr/ssrparser.ml4
  plugins/ssrmatching/g_ssrmatching.ml4
  plugins/ssrmatching/g_ssrmatching.mli
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
  plugins/ssrmatching/ssrmatching_plugin.mlpack
Labels: kind: cleanup, kind: fix

#7960 [build] Remove target binary before copy.
  Makefile.build
Labels: kind: fix
