Repository rocq-prover/rocq, pull requests merged in 2019-11, with the labels that each got.

#11021 Fix build in master
  plugins/micromega/RMicromega.v
Labels: kind: fix

#11015 [Nix] Update reference to nixpkgs
  dev/nixpkgs.nix
Labels: kind: infrastructure

#11028 Update the deprecation doc of `Shrink Obligations`
  doc/sphinx/addendum/program.rst
Labels: kind: documentation, kind: fix

#11007 [classes] Some refactoring on proof save preparation.
  vernac/classes.ml
Labels: kind: cleanup

#10958 Elan → Stratego in documentation of `rewrite_strat`.
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/biblio.bib
Labels: kind: documentation, kind: fix

#11041 Cite POPL19 SProp paper
  doc/sphinx/addendum/sprop.rst
  doc/sphinx/biblio.bib
  doc/sphinx/language/cic.rst
Labels: kind: documentation

#11038 fix(*.opam): Add missing version "dev"
  coq-refman.opam
  coq.opam
  coqide-server.opam
  coqide.opam
Labels: kind: fix, kind: infrastructure

#11059 Swap parsing precedence of `::` and `,` ; Fix #10116
  test-suite/bugs/closed/bug_10116.v
  user-contrib/Ltac2/g_ltac2.mlg
Labels: kind: fix

#11050 Replace "option" in doc when it refers to a flag
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/omega.rst
  doc/sphinx/addendum/parallel-proof-processing.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/language/cic.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/proof-handling.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/proof-schemes.rst
  stm/stm.ml
Labels: kind: documentation, kind: user messages

#11042 The "univ poly can capture global univs" checker side bug is fixed
  dev/doc/critical-bugs
Labels: kind: documentation

#11069 Do not include final stops in queries. (Fixes #11058)
  ide/gtk_parsing.ml
  ide/wg_Completion.ml
Labels: kind: fix, part: IDE

#11040 [CI] Update Mtac2 to master-8.11 branch.
  dev/ci/ci-basic-overlay.sh
Labels: kind: internal

#11014 Fix #8459: anomaly not enough abstractions in fix body
  kernel/inductive.ml
  test-suite/bugs/closed/bug_8459.v
Labels: kind: fix

#11065 [Docker] Dedicate a docker image to the v8.11 branch
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#11017 Make [Proof_global.closed_proof_output] opaque
  stm/stm.ml
  tactics/proof_global.mli
  vernac/lemmas.ml
Labels: kind: cleanup

#10980 Fix #10903: type-in-type allows fixpoints on sprop inductives
  kernel/inductive.ml
  test-suite/bugs/closed/bug_10903.v
Labels: kind: fix, part: SProp

#11052 Fix #11048: uncaught destKO in inductive type
  test-suite/bugs/closed/bug_11048.v
  vernac/comInductive.ml
Labels: kind: fix

#11032 Run update-compat script with --release option.
  doc/stdlib/index-list.html.template
  lib/flags.ml
  lib/flags.mli
  test-suite/success/Compat88.v
  test-suite/success/CompatOldOldFlag.v
  test-suite/success/NotationDeprecation.v
  test-suite/tools/update-compat/run.sh
  theories/Compat/Coq88.v
  toplevel/coqargs.ml
  vernac/g_vernac.mlg
Labels: kind: cleanup, kind: infrastructure

#11045 Forbid Include inside sections
  test-suite/bugs/closed/bug_10060.v
  vernac/declaremods.ml
Labels: kind: anomaly, kind: fix, part: modules, part: sections

#11092 [dune] Have only one rule calling configure
  config/dune
  configure.ml
  kernel/byterun/dune
Labels: kind: fix, kind: infrastructure, part: build

#11067 Expand documentation about generating a Docker image.
  dev/ci/docker/README.md
Labels: kind: documentation

#11070 Do not rely on the user settings but on the actual window size. (Fixes #10956)
  ide/coqide.ml
  ide/session.ml
  ide/session.mli
Labels: kind: fix, part: IDE

#11094 Miscellaneous micro-improvements of the syntax of records
  parsing/g_constr.mlg
  printing/ppconstr.ml
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: kind: cleanup, kind: enhancement

#11116 Create branch for Paramcoq CI
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#11100 small documentation fixes
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/biblio.bib
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, kind: fix

#10979 Fix doc for universes(foo) attributes
  doc/sphinx/language/cic.rst
  doc/sphinx/language/gallina-specification-language.rst
Labels: kind: documentation, kind: fix

#11079 Rename non-unique local nonterminals
  parsing/g_constr.mlg
  plugins/ltac/g_tactic.mlg
  user-contrib/Ltac2/g_ltac2.mlg
  vernac/g_vernac.mlg
Labels: kind: cleanup

#11095 Do not export the internals of the prepare_hint function.
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#11115 [dune] Update .gitignore after #11092
  .gitignore
Labels: kind: fix, kind: infrastructure

#11106 Printing name of change log file in changelog script
  dev/tools/make-changelog.sh
Labels: kind: enhancement, kind: infrastructure

#11074 coqdep: only output vos when passed -vos
  Makefile.build
  tools/CoqMakefile.in
  tools/coqdep.ml
  tools/coqdep_common.ml
  tools/coqdep_common.mli
Labels: kind: infrastructure, part: build

#11068 coq_makefile: support COQBIN with no ending /
  doc/changelog/08-tools/11068-coqbin-noslash.rst
  tools/CoqMakefile.in
Labels: kind: enhancement, part: tools

#11144 Fix broken links
  CONTRIBUTING.md
Labels: kind: documentation, kind: fix

#11075 load .vo when .vos is missing + misc vos changes
  doc/sphinx/practical-tools/coq-commands.rst
  test-suite/coq-makefile/coqdoc1/run.sh
  test-suite/coq-makefile/coqdoc2/run.sh
  test-suite/coq-makefile/mlpack1/run.sh
  test-suite/coq-makefile/mlpack2/run.sh
  test-suite/coq-makefile/multiroot/run.sh
  test-suite/coq-makefile/native1/run.sh
  test-suite/coq-makefile/plugin1/run.sh
  test-suite/coq-makefile/plugin2/run.sh
  test-suite/coq-makefile/plugin3/run.sh
  tools/CoqMakefile.in
  toplevel/ccompile.ml
  toplevel/coqcargs.mli
  vernac/loadpath.ml
Labels: kind: fix, kind: infrastructure

#11139 [ci] Use coq/bignums v8.11 branch
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#10614 Update the Gallina grammar in doc, "Terms" section
  Makefile.build
  Makefile.doc
  doc/sphinx/addendum/extended-pattern-matching.rst
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/conf.py
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/README.md
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  doc/tools/docgram/prodn.edit_mlg
  doc/tools/docgram/productionlist.edit_mlg
Labels: kind: documentation

#11154 add tlc to ci; please proof read very carefully and test. thanks
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-tlc.sh
Labels: kind: infrastructure

#11145 Document -vos flag for coqdep
  doc/sphinx/practical-tools/coq-commands.rst
  man/coqdep.1
  tools/coqdep.ml
Labels: kind: documentation

#11109 Register proof_irrelevance
  theories/Logic/ProofIrrelevance.v
Labels: kind: fix, part: standard library

#10587 [coqdoc] Nest <a> into <h2> instead of the other way around
  tools/coqdoc/output.ml
Labels: kind: documentation, kind: infrastructure, part: tools

#11152 Cache the relevance flag in rel contexts in an efficient way.
  kernel/reduction.ml
  kernel/retypeops.ml
  kernel/retypeops.mli
  pretyping/retyping.ml
Labels: kind: fix, kind: performance

#11159 Minor fix in doc for [unfold]
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation, kind: fix

#11034 Update update-compat.py
  dev/tools/update-compat.py
Labels: kind: enhancement, kind: infrastructure

#11173 [ssr] fix «W -- weakening» doc
  plugins/ssr/ssrbool.v
Labels: kind: documentation

#11180 Add more development setup instructions for tutorials
  doc/plugin_tutorial/README.md
Labels: kind: documentation

#11166 Add test for #11161
  test-suite/bugs/closed/bug_11161.v
Labels: kind: infrastructure, part: test-suite

#11090 Printing of coercions to which a notation is associated: a refined version of #8890 which prevents #11033.
  doc/changelog/03-notations/11090-master+refactoring-application-printing.rst
  interp/constrextern.ml
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: kind: enhancement, kind: fix, part: coercions, part: notations

#11179 Fix Windows 32 bit build
  configure.ml
Labels: kind: compatibility, kind: fix, platform: Windows

#11177 Add a complexity test for `pattern`
  test-suite/complexity/pattern.v
Labels: kind: performance, part: test-suite

#11193 weaker then -> weaker than
  doc/sphinx/addendum/generalized-rewriting.rst
Labels: kind: documentation, kind: fix

#11196 missing " in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind: documentation, kind: fix

#11199 Correcting unintended changelog message for #11090 (coercion+notation regression)
  doc/changelog/03-notations/11090-master+refactoring-application-printing.rst
Labels: kind: fix

#11197 Release notes for Coq 8.10.2
  doc/changelog/03-notations/11090-master+refactoring-application-printing.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#11205 Revert: Backport PR #11177: Add a complexity test for `pattern`
  test-suite/complexity/pattern.v
Labels: kind: fix, kind: infrastructure

#11206 Coq version 8.10.2
  configure.ml
Labels: kind: meta

#11186 Remove undocumented and deprecated `Congruence Depth` option
  plugins/firstorder/g_ground.mlg
Labels: kind: cleanup

#11215 Revert #10394 on v8.11
  META.coq.in
  ide/coq_lex.mll
  test-suite/Makefile
  test-suite/unit-tests/ide/lex_tests.ml
Labels: kind: fix

#11204 Relax the pattern complexity test
  test-suite/complexity/pattern.v
Labels: kind: infrastructure

#11213 Pin CI developments for the 8.11+beta1 release.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#11184 Undeprecate Add Setoid / Add Morphism.
  plugins/ltac/rewrite.ml
Labels: kind: user messages
