Repository rocq-prover/rocq, pull requests merged in 2019-07, with the labels that each got.

#10340 [vernac] Remove special status of Load, turn it into VtNoProof
  vernac/vernacentries.ml
Labels: kind: cleanup

#10336 Improve the ambiguous paths warning to indicate which path is ambiguous with new one
  doc/changelog/07-commands-and-options/10336-ambiguous-paths.rst
  doc/sphinx/addendum/implicit-coercions.rst
  pretyping/classops.ml
  test-suite/output/relaxed_ambiguous_paths.out
Labels: kind: user messages, part: coercions

#10467 [nix] python2 -> python3
  default.nix
Labels: kind: infrastructure

#10338 Fix #9455: avoid update_global_env when unchanged Global.universes()
  stm/stm.ml
  vernac/vernacentries.ml
Labels: kind: fix, kind: performance, part: STM, part: universes

#10472 [vernac] Fix bad merge which resulted in code using wrong module name.
  vernac/vernacentries.ml
Labels: kind: fix, priority: high

#10442 Reify libobject containers
  checker/values.ml
  library/declaremods.ml
  library/declaremods.mli
  library/lib.ml
  library/lib.mli
  library/libobject.ml
  library/libobject.mli
  library/library.ml
  plugins/extraction/extract_env.ml
  printing/prettyp.ml
  vernac/search.ml
Labels: kind: cleanup, kind: redesign

#10479 Fix miscellaneous mistakes in unreleased changelog entries.
  doc/changelog/02-specification-language/10049-bidi-app.rst
  doc/changelog/02-specification-language/10167-orpat-mixfix.rst
  doc/changelog/02-specification-language/10215-rm-maybe-open-proof.rst
  doc/changelog/03-notations/10180-deprecate-notations.rst
  doc/changelog/04-tactics/09288-injection-as.rst
  doc/changelog/04-tactics/10318-select-only-error.rst
  doc/changelog/07-commands-and-options/09530-rm-unknown.rst
Labels: kind: documentation, kind: fix

#10484 Correct doc about default value for Typeclasses Dependency Order
  doc/sphinx/addendum/type-classes.rst
Labels: kind: documentation, kind: fix

#10482 Use Format.pp_print_list with conditional instead of fold for list prints in gramlib
  gramlib/grammar.ml
Labels: kind: cleanup

#10490 Dockerfile: update menhir version
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#10466 [python] Remove use of generic python shebang, update CI
  azure-pipelines.yml
  default.nix
  dev/tools/update-compat.py
  tools/make-both-single-timing-files.py
  tools/make-both-time-files.py
  tools/make-one-time-file.py
Labels: kind: ci-failure, kind: fix, kind: infrastructure

#9686 [error] Remove special error printing pre-processing
  dev/base_include
  lib/cErrors.ml
  lib/cErrors.mli
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/g_indfun.mlg
  plugins/funind/indfun.ml
  plugins/funind/invfun.ml
  plugins/funind/recdef.ml
  plugins/ltac/tactic_debug.ml
  plugins/ssr/ssrvernac.mlg
  stm/stm.ml
  user-contrib/Ltac2/tac2entries.ml
  user-contrib/Ltac2/tac2print.ml
  vernac/declareObl.ml
  vernac/explainErr.ml
  vernac/explainErr.mli
  vernac/himsg.ml
  vernac/himsg.mli
  vernac/obligations.ml
  vernac/vernac.mllib
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: fix

#10497 [lemmas] Move mutually recursive lemma analysis to its own module.
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/recLemmas.ml
  vernac/recLemmas.mli
  vernac/vernac.mllib
Labels: kind: cleanup

#10067 Faster renaming of shadowed variables in evar instance creation.
  engine/evarutil.ml
Labels: kind: fix, kind: performance

#10453 [errors] Small cleanups and removal of dead code.
  ide/idetop.ml
  lib/cErrors.ml
  lib/cErrors.mli
Labels: kind: cleanup

#10471 [core] [api] Support OCaml 4.08
  .gitlab-ci.yml
  INSTALL
  azure-pipelines.yml
  checker/analyze.ml
  checker/check.ml
  dev/ci/azure-opam.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/dune-workspace.all
  doc/changelog/11-infrastructure-and-dependencies/10471-ocaml-408.rst
  engine/logic_monad.ml
  engine/proofview.ml
  ide/protocol/richpp.ml
  ide/session.ml
  ide/wg_Completion.ml
  interp/constrextern.ml
  interp/dumpglob.ml
  interp/notation.ml
  kernel/nativecode.ml
  lib/future.ml
  lib/pp.ml
  lib/util.ml
  lib/util.mli
  library/summary.ml
  plugins/extraction/common.ml
  plugins/ltac/profile_ltac.ml
  plugins/ltac/tactic_debug.ml
  plugins/micromega/certificate.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/csdpcert.ml
  plugins/micromega/mfourier.ml
  plugins/micromega/mutils.ml
  plugins/micromega/polynomial.ml
  plugins/micromega/simplex.ml
  plugins/micromega/sos_lib.ml
  plugins/micromega/vect.ml
  plugins/omega/coq_omega.ml
  plugins/omega/omega.ml
  plugins/ssr/ssrview.ml
  pretyping/classops.ml
  printing/prettyp.ml
  tactics/btermdn.ml
  tactics/class_tactics.ml
  tactics/redops.ml
  tools/coqdep.ml
  tools/coqdep_common.ml
  tools/coqdoc/main.ml
  tools/coqdoc/output.ml
  tools/ocamllibdep.mll
  toplevel/coqloop.ml
  vernac/metasyntax.ml
  vernac/ppvernac.ml
  vernac/search.ml
  vernac/topfmt.ml
Labels: kind: compatibility, kind: infrastructure

#10446 [proof] Remove sign parameter to open_lemma.
  plugins/funind/recdef.ml
  vernac/declareObl.ml
  vernac/declareObl.mli
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/obligations.ml
Labels: kind: cleanup

#10509 [CI/Azure/macOS] Attempt at pinning the homebrew-core repository
  azure-pipelines.yml
Labels: kind: infrastructure

#10506 merge-pr.sh: filter reviews to remove the PR author
  dev/tools/merge-pr.sh
Labels: kind: infrastructure

#10510 Fixed a few wrong reference and typos
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, kind: fix, part: ssreflect

#10424 Update doc for % escapes in Sphinx, improve error messages
  doc/sphinx/README.rst
  doc/sphinx/README.template.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: infrastructure

#10496 [proof] Minor cleanup in proof.ml
  printing/printer.ml
  proofs/pfedit.ml
  proofs/proof.ml
  proofs/proof.mli
  proofs/proof_global.ml
  user-contrib/Ltac2/tac2entries.ml
Labels: kind: cleanup

#10512 Remove Stm.call_process_error_once
  stm/stm.ml
Labels: kind: cleanup

#10517 Azure CI MacOS: build byte target first
  azure-pipelines.yml
Labels: kind: fix, kind: infrastructure

#10520 Fix typos
  dev/doc/xml-protocol.md
Labels: kind: documentation

#10518 [funind] Remove unneeded callback.
  plugins/funind/functional_principles_types.mli
  plugins/funind/indfun.ml
  plugins/funind/invfun.ml
  plugins/funind/invfun.mli
Labels: kind: cleanup, part: funind

#10532 [doc] Fix typo in doc/sphinx/addendum/ring.rst
  doc/sphinx/addendum/ring.rst
Labels: kind: documentation

#10521 Move unfold_side_flags CClosure -> Tacred internals
  kernel/cClosure.ml
  kernel/cClosure.mli
  pretyping/tacred.ml
Labels: kind: cleanup

#9884 doc_grammar, a utility to extract Coq's grammar from .mlg files and insert it into .rst files
  .gitattributes
  .gitignore
  Makefile.build
  Makefile.common
  coqpp/coqpp_lex.mll
  coqpp/coqpp_main.ml
  coqpp/coqpp_parse.mly
  coqpp/coqpp_parser.ml
  coqpp/coqpp_parser.mli
  coqpp/dune
  doc/tools/docgram/README.md
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  doc/tools/docgram/prodn.edit_mlg
  doc/tools/docgram/productionlist.edit_mlg
Labels: kind: documentation, kind: infrastructure

#10462 [Pretyping] Do not restrict a solved evar
  pretyping/evarconv.ml
  test-suite/bugs/closed/bug_10300.v
Labels: kind: fix, part: elaboration

#10554 Do not rely on dummy TACTIC EXTEND for ssreflect tactics.
  plugins/ssr/ssrparser.mlg
Labels: kind: cleanup

#10552 Fix a detail in 2 doc files for the under tactic
  doc/sphinx/changes.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, kind: fix

#10536 Fix #10533: uncaught Invalid_argument Array.fold_left2 in rewrite
  pretyping/unification.ml
  test-suite/bugs/closed/bug_10533.v
Labels: kind: fix, part: unification

#10568 Mark primitive integers as able to participate in reductions (fixes #10560).
  kernel/cClosure.ml
  test-suite/bugs/closed/bug_10560.v
Labels: kind: fix, part: kernel

#10563 changed name of cos3PI4 to cos_3PI4 for consistency
  theories/Reals/Rtrigo_calc.v
Labels: kind: cleanup, part: standard library, priority: nice to have

#10569 [Int63] Remove redundant misnamed lemma lsr_add_distr
  theories/Numbers/Cyclic/Int63/Int63.v
Labels: kind: fix, part: standard library

#10538 [vernac] [inductive] Remove unused functions/exports.
  vernac/comInductive.ml
  vernac/comInductive.mli
Labels: kind: cleanup

#10581 Remove the tactic wizard, as it has not worked for several years and no one complained (fixes #10580).
  doc/sphinx/practical-tools/coqide.rst
  ide/MacOS/default_accel_map
  ide/coqOps.ml
  ide/coqOps.mli
  ide/coqide.ml
  ide/coqide_ui.ml
  ide/preferences.ml
Labels: kind: fix, part: IDE

#10574 Remove deprecated `Backtrack` command
  doc/sphinx/proof-engine/vernacular-commands.rst
  stm/stm.ml
  stm/vernac_classifier.ml
  toplevel/coqloop.ml
  toplevel/g_toplevel.mlg
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
  vernac/vernacprop.ml
Labels: kind: cleanup

#10548 Refine documentation of tokens
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/doc_grammar.ml
Labels: kind: documentation

#10595 [CI/Azure/macOS] Unshallow the homebrew-core repository
  azure-pipelines.yml
Labels: kind: infrastructure

#10594 Fix issue #10593 : Software foundations URL changed
  dev/ci/ci-basic-overlay.sh
Labels: kind: ci-failure, kind: infrastructure
