Repository rocq-prover/rocq, pull requests merged in 2019-05, with the labels that each got.

#10048 [CI/Azure/macOS] Fix install of OCaml through OPAM
  azure-pipelines.yml
Labels: kind: fix, kind: infrastructure, platform: macOS

#10047 [opam] [dune] Fix opam build by correctly setting prefix.
  coq.opam
Labels: kind: fix, kind: infrastructure

#10038 [comDefinition] Use prepare function from DeclareDef.
  doc/plugin_tutorial/tuto1/src/simple_declare.ml
  vernac/comDefinition.ml
Labels: kind: cleanup

#10025 Fix #9994: `revert dependent` is extremely slow.
  tactics/tactics.ml
  test-suite/bugs/closed/bug_10025.v
Labels: kind: fix, kind: performance

#9984 Add PairUsualDecidableTypeFull
  CHANGES.md
  theories/Structures/EqualitiesFacts.v
Labels: kind: feature, part: standard library

#10057 Fix #10054: Numeral Notations without the ltac plugin.
  plugins/syntax/g_numeral.mlg
  plugins/syntax/plugin_base.dune
Labels: kind: enhancement, kind: fix

#10012 Document convert_concl_no_check (#3225)
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#9926 [vernac] [ast] Make location info an attribute of vernaculars.
  ide/idetop.ml
  plugins/funind/g_indfun.mlg
  plugins/funind/glob_term_to_relation.ml
  stm/proofBlockDelimiter.ml
  stm/stm.ml
  stm/stm.mli
  stm/vernac_classifier.ml
  toplevel/coqloop.ml
  toplevel/g_toplevel.mlg
  toplevel/vernac.ml
  toplevel/vernac.mli
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/pvernac.ml
  vernac/pvernac.mli
  vernac/topfmt.ml
  vernac/topfmt.mli
  vernac/vernacentries.ml
  vernac/vernacentries.mli
  vernac/vernacexpr.ml
  vernac/vernacprop.ml
Labels: kind: cleanup

#10068 Coqchk: encapsulating an anomaly NotConvertible into a proper user-level typing error
  checker/mod_checking.ml
Labels: kind: fix, part: checker

#10063 CoqIDE: recognize qualified identifiers as words.
  ide/gtk_parsing.ml
Labels: kind: fix, part: IDE

#10053 Document change_no_check variants
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#10016 [test-suite] Remove a test with a Timeout that fails frequently on CI.
  test-suite/success/ROmega3.v
Labels: kind: ci-failure, kind: infrastructure, part: test-suite

#10077 [refman] Add a note reminding about the typeclass_instances database.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#10119 Show diffs in error messages only if Diffs is enabled
  test-suite/output/Error_msg_diffs.v
  vernac/himsg.ml
Labels: kind: fix

#10086 Fix gitignore for ltac2
  .gitignore
Labels: kind: infrastructure

#10087 Added description of Q
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#10082 Fix PLUGINSVO computation after ltac2 integration
  Makefile.vofiles
Labels: kind: cleanup, part: build

#10126 Ignore generated dune file for Ltac2
  .gitignore
Labels: kind: fix, kind: infrastructure

#10120 Clean-up: remove dead appveyor.sh file.
  dev/ci/appveyor.sh
Labels: kind: cleanup, kind: infrastructure

#10065 CI: run coqchk without -silent
  .gitlab-ci.yml
Labels: kind: infrastructure

#10080 Define minimum Sphinx version in conf.py.
  doc/sphinx/conf.py
Labels: kind: documentation, kind: infrastructure, part: build

#10058 Remove various circumvolutions from reduction behaviors
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/tacred.ml
  test-suite/output/Arguments.out
  test-suite/output/Arguments.v
  test-suite/output/Arguments_renaming.out
  vernac/vernacentries.ml
Labels: kind: cleanup, part: tactics

#10083 Avoid trivial (u=u) constraints in AcyclicGraph.constraints_for
  lib/acyclicGraph.ml
Labels: kind: cleanup

#10061 Print custom grammar entries
  doc/changelog/03-notations/10061-print-custom-grammar.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  test-suite/success/Notations2.v
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: fix, kind: user messages, part: notations

#9887 [api] Remove 8.10 deprecations.
  clib/cString.ml
  clib/cString.mli
  dev/doc/changes.md
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/ftactic.ml
  engine/ftactic.mli
  engine/proofview.ml
  engine/proofview.mli
  engine/termops.ml
  engine/termops.mli
  engine/uState.ml
  engine/uState.mli
  engine/univGen.ml
  engine/univGen.mli
  interp/impargs.ml
  interp/impargs.mli
  kernel/indtypes.ml
  kernel/indtypes.mli
  kernel/names.ml
  kernel/names.mli
  lib/rtree.ml
  lib/rtree.mli
  library/global.ml
  library/global.mli
  library/globnames.ml
  library/globnames.mli
  library/lib.ml
  library/nametab.ml
  library/nametab.mli
  plugins/funind/recdef.ml
  plugins/micromega/coq_micromega.ml
  plugins/ssr/ssrequality.ml
  pretyping/evarconv.ml
  pretyping/evarconv.mli
  printing/printmod.ml
  proofs/proof.ml
  proofs/proof.mli
  proofs/tacmach.ml
  proofs/tacmach.mli
  tactics/ppred.mli
  toplevel/coqargs.ml
  toplevel/coqtop.ml
  toplevel/usage.ml
  vernac/himsg.ml
  vernac/himsg.mli
Labels: kind: cleanup, kind: internal

#10137 [Gitlab-CI/macos] Allow gtksourceview to find libffi
  dev/build/osx/make-macos-dmg.sh
Labels: kind: fix, kind: infrastructure

#10164 Add aucontext debug printer
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
Labels: kind: infrastructure

#10136 [ltac2] Add primitive integers
  user-contrib/Ltac2/Constr.v
  user-contrib/Ltac2/Init.v
  user-contrib/Ltac2/tac2core.ml
  user-contrib/Ltac2/tac2ffi.ml
  user-contrib/Ltac2/tac2ffi.mli
Labels: kind: enhancement, part: ltac2

#9905 [vm] x86_64 registers
  kernel/byterun/coq_interp.c
Labels: kind: performance, part: VM

#10150 Handle tags shorter than "diff." without an exception
  vernac/topfmt.ml
Labels: kind: fix

#10171 Bump version number to 8.9.1.
  CHANGES.md
  configure.ml
Labels: kind: infrastructure

#10183 [Gitlab-CI] Target macOS version 10.11
  .gitlab-ci.yml
Labels: kind: infrastructure

#10134 Simplify impargs
  interp/impargs.ml
Labels: kind: cleanup, part: elaboration

#10190 Implicit Quantifiers recurse in continuation of let-in
  interp/implicit_quantifiers.ml
  test-suite/bugs/closed/bug_10189.v
Labels: kind: fix, part: elaboration

#9873 Remove test file with Timeout that failed spuriously.
  test-suite/bugs/closed/bug_4429.v
Labels: kind: ci-failure, kind: infrastructure, part: test-suite

#10186 [CI/Azure/macOS] Target macOS version 10.11
  azure-pipelines.yml
Labels: kind: infrastructure, platform: macOS

#10042 [Classes] Use prepare_parameter from DeclareDef.
  vernac/classes.ml
  vernac/comAssumption.ml
Labels: kind: cleanup

#9980 [ci] Set artifact expire date for all jobs.
  .gitlab-ci.yml
Labels: kind: infrastructure

#10207 Partly revert micromega parsing using typeclasses.
  plugins/micromega/DeclConstant.v
  plugins/micromega/MExtraction.v
  plugins/micromega/ZMicromega.v
  plugins/micromega/coq_micromega.ml
  plugins/micromega/micromega.ml
  plugins/micromega/micromega.mli
  plugins/omega/PreOmega.v
  test-suite/micromega/bug_10158.v
  test-suite/micromega/rsyntax.v
  test-suite/output/MExtraction.v
Labels: kind: fix, part: micromega

#10178 Improve doc for generalizing binders
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation

#10211 Use grep in changelog test instead of adhoc reads
  test-suite/misc/changelog.sh
Labels: kind: infrastructure, part: test-suite

#10173 Fail: don't catch critical errors
  vernac/vernacentries.ml
Labels: kind: fix

#10214 Better dune ocamldebug integration
  dev/doc/build-system.dune.md
  dev/dune
  dev/dune-dbg.in
  dev/tools/coqdev.el
Labels: kind: enhancement, kind: infrastructure

#10227 Update `Bind Scope` documentation to reflect dynamic binding semantics.
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, kind: fix, part: notations

#10195 Minor Ltac2 documentation fix: type parameters are optional.
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation, kind: fix

#10167 do not parse `|` as infix in patterns; parse `|}` as `|` `}`
  doc/changelog/02-specification-language/10167-orpat-mixfix.rst
  doc/sphinx/addendum/extended-pattern-matching.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  interp/constrintern.ml
  parsing/g_constr.mlg
  parsing/g_prim.mlg
  parsing/pcoq.ml
  parsing/pcoq.mli
  printing/ppconstr.ml
  test-suite/success/Case18.v
  vernac/egramcoq.ml
  vernac/g_vernac.mlg
Labels: kind: cleanup, part: notations

#10118 Make progress toward #9411: reject new undefined references.
  doc/sphinx/conf.py
Labels: kind: documentation, kind: infrastructure

#10209 Fix #10208 don't fail when passed extensionless -topfile
  stm/stm.ml
Labels: kind: fix

#10244 Coqc: Treat unknown arguments starting with dash as unknown options rather than files
  toplevel/coqcargs.ml
Labels: kind: enhancement, kind: fix

#10220 Use new coqrst syntax for alternatives in SSReflect chapter.
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, part: ssreflect

#10235 [debug] Print restriction metadata in evar map debug printer
  engine/termops.ml
Labels: kind: internal

#10198 Centralize the hashconsing of constant declarations.
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/opaqueproof.ml
  kernel/safe_typing.ml
  kernel/term_typing.ml
  kernel/term_typing.mli
Labels: kind: cleanup, kind: performance

#10249 More precise type for export and inlining of private constants
  interp/declare.ml
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  library/global.mli
  proofs/pfedit.ml
  vernac/obligations.ml
Labels: kind: cleanup, part: kernel

#10258 Remove the delayed universe table from object files.
  checker/check.ml
  checker/mod_checking.ml
  checker/values.ml
  kernel/opaqueproof.ml
  kernel/opaqueproof.mli
  library/library.ml
  library/library.mli
  stm/stm.ml
Labels: kind: cleanup

#10228 gitlab: run less jobs unless FULL_CI=true
  .gitlab-ci.yml
Labels: kind: infrastructure

#10049 [elaboration] Bidirectionality hints
  doc/changelog/02-specification-language/10049-bidi-app.rst
  doc/sphinx/language/gallina-extensions.rst
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  printing/prettyp.ml
  test-suite/success/BidirectionalityHints.v
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: feature, part: elaboration

#10269 Checker: don't use monomorphic universes attached to a constant
  checker/mod_checking.ml
Labels: kind: fix, part: checker, priority: critical
