Repository rocq-prover/rocq, pull requests merged in 2019-09, with the labels that each got.

#10716 [funind] Don't export duplicate save function.
  plugins/funind/gen_principle.ml
  plugins/funind/indfun_common.ml
  plugins/funind/indfun_common.mli
Labels: kind: cleanup, part: funind

#10562 [library] Move library to vernac
  library/coqlib.ml
  library/library.mllib
  library/states.ml
  library/states.mli
  printing/prettyp.ml
  printing/prettyp.mli
  toplevel/coqc.ml
  toplevel/coqtop.ml
  vernac/library.ml
  vernac/library.mli
  vernac/vernac.mllib
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: redesign

#10648 [extraction] Fix #7191: Avoid unsound eta-reduction
  plugins/extraction/mlutil.ml
  test-suite/output/bug7191.out
  test-suite/output/bug7191.v
Labels: kind: fix, part: extraction

#10719 Make SSR congr tactic work on arrows in Type.
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrequality.ml
  test-suite/ssr/congr.v
Labels: kind: fix

#10645 [ci] Update to OCaml 4.08.1
  .gitlab-ci.yml
  INSTALL
  azure-pipelines.yml
  dev/ci/azure-opam.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/dune-workspace.all
Labels: kind: infrastructure

#10729 Locations for notation deprecation warnings
  interp/notation.ml
  interp/syntax_def.ml
Labels: kind: enhancement, kind: user messages

#10730 Add missing index for From ... Require ...
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#10605 [toplevel] Make all argument lists to be in user-declared order.
  stm/stm.ml
  toplevel/ccompile.ml
  toplevel/coqargs.ml
  toplevel/coqcargs.ml
  toplevel/vernac.ml
Labels: kind: cleanup

#9406 [stdlib] Do not put INR_eq in the “real” hint database
  test-suite/output/NoAxiomFromR.out
  test-suite/output/NoAxiomFromR.v
  theories/Reals/RIneq.v
Labels: kind: fix, part: standard library

#10742 Switch maintenance of `ring` to a team
  .github/CODEOWNERS
Labels: kind: meta

#10748 Hack for fixing #10578: handle between the three main CoqIDE windows not always set at the expected position
  ide/session.ml
Labels: kind: fix, part: IDE

#10752 Coq version 8.10+β3
  configure.ml
Labels: kind: meta

#9856 A 'zify' tactic as a ML plugin
  Makefile.common
  doc/changelog/04-tactics/09856-zify.rst
  doc/sphinx/addendum/micromega.rst
  doc/stdlib/hidden-files
  plugins/micromega/Lia.v
  plugins/micromega/MExtraction.v
  plugins/micromega/QMicromega.v
  plugins/micromega/RMicromega.v
  plugins/micromega/Refl.v
  plugins/micromega/RingMicromega.v
  plugins/micromega/Tauto.v
  plugins/micromega/ZMicromega.v
  plugins/micromega/Zify.v
  plugins/micromega/ZifyBool.v
  plugins/micromega/ZifyClasses.v
  plugins/micromega/ZifyInst.v
  plugins/micromega/coq_micromega.ml
  plugins/micromega/coq_micromega.mli
  plugins/micromega/g_micromega.mlg
  plugins/micromega/g_zify.mlg
  plugins/micromega/micromega.ml
  plugins/micromega/micromega.mli
  plugins/micromega/persistent_cache.ml
  plugins/micromega/persistent_cache.mli
  plugins/micromega/plugin_base.dune
  plugins/micromega/zify.ml
  plugins/micromega/zify.mli
  plugins/micromega/zify_plugin.mlpack
  plugins/omega/PreOmega.v
  plugins/omega/g_omega.mlg
  test-suite/.csdp.cache
  test-suite/micromega/non_lin_ci.v
  test-suite/micromega/rexample.v
  test-suite/micromega/rsyntax.v
  test-suite/micromega/zomicron.v
  test-suite/output/MExtraction.v
  test-suite/success/Nia.v
Labels: kind: feature, kind: performance

#10777 Mark SF as allow failure until it gets fixed.
  .gitlab-ci.yml
Labels: kind: infrastructure

#10776 Fix #10413 (CI failure on tags).
  .gitlab-ci.yml
Labels: kind: fix, kind: infrastructure

#10758 Fix #10757: Program Fixpoint uses "exists" for telescopes
  doc/changelog/02-specification-language/10758-fix-10757.rst
  test-suite/bugs/closed/bug_10757.v
  theories/Init/Logic.v
  vernac/comProgramFixpoint.ml
Labels: kind: fix

#10699 [gitlab/ci] Prevent Corn from running if Bignums has failed.
  .gitlab-ci.yml
Labels: kind: infrastructure

#10774 Make `zify` does work for `Z.to_N`
  doc/changelog/04-tactics/10774-zify-Z_to_N.rst
  plugins/micromega/ZifyInst.v
  test-suite/micromega/bug_9162.v
Labels: kind: enhancement, part: micromega

#10781 Fixes #10778 (fresh was not updated after renaming of intropattern entry in #10239)
  plugins/ltac/tacarg.ml
  plugins/ltac/taccoerce.ml
  test-suite/bugs/closed/bug_10778.v
Labels: kind: fix, part: notations, part: tactics

#10784 Fix #10783: use binder_annot in Ltac2.Constr.Unsafe.kind
  test-suite/ltac2/constr.v
  user-contrib/Ltac2/Constr.v
Labels: kind: fix

#10713 Define morphisms of real numbers and accelerate Cauchy reals
  doc/stdlib/index-list.html.template
  theories/Reals/ConstructiveCauchyReals.v
  theories/Reals/ConstructiveCauchyRealsMult.v
  theories/Reals/ConstructiveRIneq.v
  theories/Reals/ConstructiveRcomplete.v
  theories/Reals/ConstructiveReals.v
  theories/Reals/ConstructiveRealsLUB.v
  theories/Reals/ConstructiveRealsMorphisms.v
  theories/Reals/Raxioms.v
Labels: kind: feature, part: standard library

#10673 [lemmas] Cleanup users of default proof information.
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/recdef.ml
  vernac/classes.ml
  vernac/obligations.ml
Labels: kind: cleanup
