Repository rocq-prover/rocq, pull requests merged in 2019-04, with the labels that each got.

#9725 Lia: various impovements (support for #8764, fix #9268 and #9615)
  CHANGES.md
  doc/sphinx/proof-engine/tactics.rst
  doc/stdlib/hidden-files
  plugins/micromega/DeclConstant.v
  plugins/micromega/Lia.v
  plugins/micromega/Lqa.v
  plugins/micromega/Lra.v
  plugins/micromega/MExtraction.v
  plugins/micromega/QMicromega.v
  plugins/micromega/RMicromega.v
  plugins/micromega/Refl.v
  plugins/micromega/RingMicromega.v
  plugins/micromega/Tauto.v
  plugins/micromega/VarMap.v
  plugins/micromega/ZMicromega.v
  plugins/micromega/certificate.ml
  plugins/micromega/certificate.mli
  plugins/micromega/coq_micromega.ml
  plugins/micromega/coq_micromega.mli
  plugins/micromega/g_micromega.mlg
  plugins/micromega/micromega.ml
  plugins/micromega/micromega.mli
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  plugins/micromega/simplex.ml
  plugins/micromega/vect.ml
  plugins/micromega/vect.mli
  test-suite/.csdp.cache
  test-suite/micromega/example_nia.v
  test-suite/micromega/rsyntax.v
  test-suite/micromega/zomicron.v
  test-suite/output/MExtraction.v
  theories/FSets/FSetEqProperties.v
  theories/FSets/FSetProperties.v
  theories/Reals/Rbasic_fun.v
Labels: kind: enhancement, kind: fix, part: tactics

#9659 Fix #9652: rewrite fails to detect lack of progress
  engine/proofview.ml
  engine/proofview.mli
  proofs/goal.ml
  proofs/goal.mli
  tactics/equality.ml
  test-suite/bugs/closed/bug_9652.v
Labels: kind: fix, kind: regression

#9875 [doc] Add a note about Dune support to the manual.
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation, kind: infrastructure

#9628 Backport #9475 and #9515: automatic deployment of documentation to GitHub Pages
  .gitlab-ci.yml
Labels: kind: infrastructure

#9731 Fix issue #9722 pkg-config not found
  dev/build/windows/MakeCoq_MinGW.bat
  dev/build/windows/makecoq_mingw.sh
Labels: kind: fix, kind: infrastructure, platform: Windows

#8638 Remove -compat 8.7
  CHANGES.md
  doc/stdlib/index-list.html.template
  lib/flags.ml
  lib/flags.mli
  test-suite/bugs/closed/bug_4798.v
  test-suite/bugs/closed/bug_9166.v
  test-suite/success/CompatOldOldFlag.v
  test-suite/tools/update-compat/run.sh
  theories/Arith/Compare_dec.v
  theories/Compat/Coq87.v
  theories/FSets/FMapFacts.v
  theories/Init/Specif.v
  theories/Logic/EqdepFacts.v
  theories/NArith/BinNat.v
  theories/NArith/Ndec.v
  theories/NArith/Ndiv_def.v
  theories/NArith/Nsqrt_def.v
  theories/PArith/BinPos.v
  theories/ZArith/BinInt.v
  theories/ZArith/ZArith_dec.v
  theories/ZArith/Zabs.v
  theories/ZArith/Zcompare.v
  theories/ZArith/Zdiv.v
  theories/ZArith/Zeven.v
  theories/ZArith/Zmax.v
  theories/ZArith/Zmin.v
  theories/ZArith/Znumtheory.v
  theories/ZArith/Zorder.v
  theories/ZArith/Zpow_facts.v
  theories/ZArith/Zquot.v
  toplevel/coqargs.ml
  vernac/g_vernac.mlg
Labels: kind: compatibility

#9896 Minor correction to numeral notations doc
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, kind: fix

#9861 [program] Allow evars in type of fixpoints.
  vernac/comProgramFixpoint.ml
Labels: kind: fix

#9804 CI: Use job-local timeout for build-template and test-suite-template
  .gitlab-ci.yml
Labels: kind: ci-failure, kind: infrastructure

#9890 Improve coqchk -norec perf by not checking for ill-formed data in dependencies
  checker/check.ml
Labels: kind: performance, part: checker

#9881 Protect some I/O routines from SIGALRM
  clib/cThread.ml
  ide/idetop.ml
  lib/control.ml
  lib/control.mli
  stm/asyncTaskQueue.ml
Labels: kind: fix

#9901 [dune] Fix include object dirs.
  dev/incdir_dune
Labels: kind: infrastructure

#9904 [CI] Fix build of math-comp dependencies
  dev/ci/ci-common.sh
Labels: kind: fix, kind: infrastructure

#9685 [vernac] Small cleanup to remove assert false.
  stm/stm.ml
  stm/vernac_classifier.ml
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
  vernac/vernacprop.ml
Labels: kind: cleanup

#9923 [ci/deploy] Fix branch creation when pushing to coq/coq-on-cachix.
  .gitlab-ci.yml
Labels: kind: fix, kind: infrastructure

#9924 Fix numeral notations test in async mode.
  test-suite/output/NumeralNotations.out
  test-suite/output/NumeralNotations.v
  test-suite/success/NumeralNotationsNoLocal.v
Labels: kind: fix, part: test-suite

#9915 Remove cache in Heads
  interp/declare.ml
  pretyping/heads.ml
  pretyping/heads.mli
Labels: kind: cleanup

#9931 Fix spelling in comment.
  theories/Arith/PeanoNat.v
Labels: kind: documentation, kind: fix

#9928 Fix #9812: CoqIDE on gtk3 has wrong defaults for selection BG.
  ide/preferences.ml
  ide/preferences.mli
  ide/session.ml
  ide/wg_Command.ml
  ide/wg_MessageView.ml
  ide/wg_ProofView.ml
  ide/wg_ScriptView.ml
Labels: kind: fix, part: IDE, priority: blocker

#9941 Improve SProp error message to mention the Allow StrictProp flag.
  doc/sphinx/addendum/sprop.rst
  vernac/himsg.ml
Labels: kind: documentation, kind: user messages

#9910 [api] [proofs] Remove dependency of proofs on interp.
  interp/constrintern.ml
  interp/constrintern.mli
  parsing/dune
  proofs/dune
  proofs/logic.ml
  proofs/pfedit.ml
  proofs/pfedit.mli
  proofs/proof.ml
  proofs/proof.mli
  proofs/tacmach.ml
  proofs/tacmach.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: internal

#9943 [mailmap] Tweak Emilio's entries.
  .mailmap
Labels: kind: meta

#9938 [coqdep] Exit with error code on exception.
  tools/coqdep.ml
Labels: kind: fix, kind: infrastructure, part: build, part: tools

#9949 [stm] Report correct ids on some errors where it was dummy.
  stm/stm.ml
Labels: kind: user messages

#9957 Add missing build dependency in `coq.opam`
  coq.opam
Labels: kind: fix, kind: infrastructure

#9927 Don't store closures in summary (reduction effects)
  pretyping/reductionops.ml
Labels: kind: cleanup

#9906 coq_makefile install target: error if any file is missing
  CHANGES.md
  test-suite/coq-makefile/missing-install/run.sh
  tools/CoqMakefile.in
Labels: kind: infrastructure

#9836 [schemes] Don't re-declare scheme side-effects that are already there.
  tactics/ind_tables.ml
Labels: kind: cleanup, part: kernel

#9978 Remove duplicate copy of _warn_if_duplicate_name.
  doc/tools/coqrst/coqdomain.py
Labels: kind: cleanup, kind: documentation, kind: infrastructure

#9889 Fix pretty-printing of primitive integers
  interp/constrextern.ml
  test-suite/output/Int63Syntax.out
  test-suite/output/Int63Syntax.v
Labels: kind: fix

#9962 [native compiler] Encoding of constructors based on tags
  kernel/nativecode.ml
  kernel/nativelambda.ml
  kernel/nativelambda.mli
Labels: kind: cleanup, part: native compiler

#9989 [refman] Fix a quoting problem.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation, kind: fix

#9988 [refman] Properly define token regexp.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation, kind: fix

#9999 Fix PKG in ide/.merlin.in for gtk3
  ide/.merlin.in
Labels: kind: infrastructure

#10001 Add a typing colon in the output of the Search ssreflect vernacular
  plugins/ssr/ssrvernac.mlg
Labels: kind: fix, part: ssreflect

#9981 [dune] Build coqc.byte executable.
  topbin/dune
Labels: kind: infrastructure

#9990 [opam] Use version to provide better package bounds.
  coq-refman.opam
  coq.opam
  coqide-server.opam
  coqide.opam
Labels: kind: infrastructure

#9998 coq_makefile: do not pass -opt/-byte to coqc (fix #9974)
  tools/CoqMakefile.in
Labels: kind: infrastructure, part: build

#9605 [coq_makefile] Enforce warn_error for plugins.
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/README-users.md
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-relation_algebra.sh
  dev/doc/changes.md
  doc/sphinx/practical-tools/utilities.rst
  lib/envars.ml
  tools/CoqMakefile.in
Labels: kind: infrastructure

#10010 [ci/gitlab] Remove after_switch message (not useful anymore).
  .gitlab-ci.yml
Labels: kind: cleanup, kind: infrastructure

#9997 CoqIDE: fix open-file dialog and icons on macOS
  Makefile.ide
  azure-pipelines.yml
Labels: kind: fix, platform: macOS

#9985 [engine] Fix #9259
  engine/evd.ml
Labels: kind: fix

#10021 More robust timing test.
  test-suite/coq-makefile/timing/run.sh
Labels: kind: ci-failure, kind: infrastructure, part: test-suite

#10018 Document unshelve (#3225)
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#10011 [refman] Fix typo.
  doc/sphinx/addendum/type-classes.rst
Labels: kind: documentation, kind: fix

#10007 Amending sphinx-on-windows fix in #9819 so that it does not trigger a warning on MacOS X (and other BSD systems).
  Makefile.doc
Labels: kind: fix, kind: infrastructure

#9775 inferCumulativity: shortcut for all-Invariant inductives
  pretyping/inferCumulativity.ml
Labels: kind: performance, part: universes

#9935 [api] [proof] Alert users that `Vernacstate.Proof_global` is not to be used.
  dev/top_printers.ml
  ide/idetop.ml
  stm/stm.ml
  toplevel/ccompile.ml
  toplevel/coqloop.ml
  toplevel/vernac.ml
  vernac/vernacentries.ml
  vernac/vernacstate.mli
Labels: kind: fix, kind: internal

#9946 Add some entries to .mailmap
  .mailmap
Labels: kind: infrastructure

#10024 [toplevel] Only print welcome header in standard coqtop.
  toplevel/coqtop.ml
Labels: kind: fix

#9952 Remove `constr_of_global_in_context`
  kernel/typeops.ml
  kernel/typeops.mli
  library/global.ml
  library/global.mli
Labels: kind: cleanup

#9995 fix `simpl_rel` and notations, `{pred T}` alias, `nonPropType` interface
  CHANGES.md
  CREDITS
  plugins/ssr/ssrbool.v
  plugins/ssr/ssreflect.v
  plugins/ssr/ssrfun.v
  test-suite/prerequisite/ssr_mini_mathcomp.v
  test-suite/ssr/nonPropType.v
  test-suite/ssr/predRewrite.v
Labels: kind: cleanup, kind: enhancement, kind: fix, part: ssreflect

#10019 Update behavior of -emacs to support showing diffs in ProofGeneral (master branch)
  toplevel/coqargs.ml
  toplevel/coqargs.mli
  toplevel/coqtop.ml
  vernac/topfmt.ml
  vernac/topfmt.mli
Labels: kind: enhancement, kind: user messages

#9947 Remove Global.env from goptions by passing from vernacentries
  library/goptions.ml
  library/goptions.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#10032 Remove leftover test suite file Quote.out
  test-suite/output/Quote.out
Labels: kind: cleanup, part: test-suite

#10033 Remove the k0 argument from pretype functions.
  pretyping/pretyping.ml
Labels: kind: cleanup
