Repository rocq-prover/rocq, pull requests merged in 2019-10, with the labels that each got.

#10805 Remove spurious uses of CoInductive in SSR prerequisite.
  test-suite/prerequisite/ssr_mini_mathcomp.v
Labels: kind: cleanup

#10809 Postpone the computation of relative constraints in universe unification
  engine/uState.ml
Labels: kind: performance, part: universes

#10806 Micromega tactics are no longer confused by primitive projections
  doc/changelog/04-tactics/10806-fix-micromega-wrt-projections.rst
  plugins/micromega/coq_micromega.ml
  test-suite/bugs/closed/bug_9512.v
Labels: kind: fix, part: micromega, part: primitive records

#10798 Loosen restrictions on mixing universe mono/polymorphism in sections
  doc/sphinx/addendum/universe-polymorphism.rst
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  kernel/section.ml
  kernel/section.mli
  library/global.ml
  library/global.mli
  library/lib.ml
  library/lib.mli
  test-suite/success/section_poly.v
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: enhancement, part: kernel, part: sections

#9772 [Stdlib] OrderedType: do not pollute the “core” hint database
  doc/changelog/10-standard-library/09772-ordered_type-hint-db.rst
  doc/sphinx/proof-engine/tactics.rst
  test-suite/bugs/opened/bug_1596.v
  theories/FSets/FMapAVL.v
  theories/FSets/FMapFacts.v
  theories/FSets/FMapFullAVL.v
  theories/FSets/FMapList.v
  theories/FSets/FSetBridge.v
  theories/FSets/FSetProperties.v
  theories/Structures/OrderedType.v
  theories/Structures/OrderedTypeEx.v
Labels: kind: enhancement, part: standard library

#10763 Fix syntax of reduction tactics when listing qualid to reduce or not.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation, kind: fix

#10833 8.10.0 release notes.
  doc/changelog/04-tactics/10806-fix-micromega-wrt-projections.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#10834 Fix #10831: minor issues in documentation of Function.
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation, kind: fix

#9933 Add a few missing notes to the release doc.
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#10791 Replace custom timeout logic with new GitLab's per-job timeout keyword.
  .gitlab-ci.yml
Labels: kind: infrastructure

#10840 Release process: release notes
  dev/doc/release-process.md
Labels: kind: documentation, kind: infrastructure

#10817 Remove redundancy in section hypotheses of kernel entries.
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/entries.ml
  kernel/safe_typing.ml
  kernel/section.ml
  kernel/term_typing.ml
  tactics/declare.ml
  tactics/declare.mli
  tactics/proof_global.ml
  tactics/proof_global.mli
  vernac/lemmas.ml
Labels: kind: cleanup, part: sections

#10697 [vernac] Split vernacular translation and interpretation.
  stm/stm.ml
  stm/vernac_classifier.ml
  toplevel/coqargs.ml
  vernac/vernac.mllib
  vernac/vernacentries.ml
  vernac/vernacentries.mli
  vernac/vernacextend.ml
  vernac/vernacinterp.ml
  vernac/vernacinterp.mli
Labels: kind: redesign

#10850 chmod -x some files
  dev/build/windows/patches_coq/ocaml-4.07.1.patch
  dev/build/windows/patches_coq/pkg-config.c
  ide/coq2.ico
  user-contrib/Ltac2/Bool.v
  user-contrib/Ltac2/Init.v
Labels: kind: cleanup

#10804 Fix Print All of section variables
  tactics/declare.ml
Labels: kind: fix

#10828 Simple script to prefill a changelog entry
  .github/CODEOWNERS
  dev/tools/make-changelog.sh
Labels: kind: infrastructure

#10740 More precise error messages for `Add Ring`
  plugins/setoid_ring/InitialRing.v
Labels: kind: user messages

#10818 Merge Direct and Indirect nodes in Opaqueproof.
  checker/check.ml
  checker/values.ml
  checker/values.mli
  checker/votour.ml
  kernel/cooking.ml
  kernel/opaqueproof.ml
  kernel/opaqueproof.mli
  kernel/safe_typing.ml
  stm/stm.ml
Labels: kind: performance

#10862 Simplify universe handling wrt side effects: rm demote_seff_univs
  engine/evd.ml
  engine/uState.ml
  engine/uState.mli
  tactics/pfedit.ml
Labels: kind: cleanup, part: tactics, part: universes

#10881 [make] separate generated gramlib ml files from mli files (fix #10864)
  Makefile
  Makefile.build
  Makefile.install
Labels: kind: fix, kind: infrastructure

#10889 Fix #10888: Context import behaviour in modtype
  test-suite/bugs/closed/bug_10888.v
  vernac/comAssumption.ml
Labels: kind: fix

#10887 fix rev_right_loop doc
  plugins/ssr/ssrfun.v
Labels: kind: documentation

#10852 Fix #10842: incorrect handling of unicode input before space
  ide/wg_ScriptView.ml
Labels: kind: fix, part: IDE

#10883 Doc update with mlg extension - fix #10855
  .gitignore
  dev/doc/build-system.txt
  dev/doc/coq-src-description.txt
  dev/v8-syntax/syntax-v8.tex
  doc/sphinx/practical-tools/utilities.rst
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/cc/README
  plugins/cc/ccproof.ml
  tools/CoqMakefile.in
Labels: kind: documentation, kind: fix

#10882 Document Gaëtan's new script to prefill a changelog entry.
  doc/changelog/README.md
Labels: kind: documentation, kind: meta

#10896 Assign ownership of the test-suite compat files
  .github/CODEOWNERS
Labels: kind: infrastructure

#10915 Fix link to `xml-protocol.md` in `dev/README.md`
  dev/README.md
Labels: kind: documentation, kind: fix

#8228 (Partially) Revert "Make Environ.globals abstract."
  kernel/environ.ml
  kernel/environ.mli
Labels: kind: internal, kind: regression

#10913 re-expose UState.demote_seff_univs
  engine/uState.ml
  engine/uState.mli
Labels: kind: fix

#10919 factorize or_var_map
  plugins/ltac/g_tactic.mlg
  plugins/ltac/tacsubst.ml
  pretyping/locusops.ml
  pretyping/locusops.mli
Labels: kind: cleanup

#10914 Fix Locate printing regression
  interp/notation.ml
  test-suite/output/locate.out
  test-suite/output/locate.v
Labels: kind: fix, part: notations

#10891 Fix #9851: anomaly when unsolved evar in Add Ring
  plugins/setoid_ring/newring.ml
  test-suite/bugs/closed/bug_9851.v
Labels: kind: fix

#10787 Fix #10779 (hnf normalisation of instance + reification of overloaded operators)
  doc/stdlib/hidden-files
  plugins/micromega/Fourier_util.v
  plugins/micromega/RMicromega.v
  plugins/micromega/ZMicromega.v
  plugins/micromega/Zify.v
  plugins/micromega/ZifyBool.v
  plugins/micromega/ZifyComparison.v
  plugins/micromega/ZifyInst.v
  plugins/micromega/g_zify.mlg
  plugins/micromega/mutils.ml
  plugins/micromega/zify.ml
  plugins/micromega/zify.mli
Labels: kind: fix, part: micromega

#10886 test-suite/Makefile: work when manually involved for dune-compiled Coq
  test-suite/Makefile
Labels: kind: infrastructure

#10880 Allow to pass Ltac1 values to Ltac2 quotations.
  doc/sphinx/proof-engine/ltac2.rst
  test-suite/ltac2/ltac2env.v
  user-contrib/Ltac2/g_ltac2.mlg
  user-contrib/Ltac2/tac2core.ml
  user-contrib/Ltac2/tac2entries.ml
  user-contrib/Ltac2/tac2entries.mli
  user-contrib/Ltac2/tac2env.mli
  user-contrib/Ltac2/tac2intern.ml
Labels: kind: feature, part: ltac2

#10897 Fix coq#4741: Extract Constant/Inductive with JSON
  plugins/extraction/json.ml
Labels: kind: fix, part: extraction

#10929 documentation fixes
  doc/sphinx/language/cic.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, kind: fix

#10938 Better wording for "Show Proof" and fix typos
  doc/sphinx/proof-engine/proof-handling.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#10945 Release notes for Coq 8.10.1
  doc/changelog/01-kernel/10904-fix-debruijn-sprop-rel.rst
  doc/changelog/05-tactic-language/10899-master+fix10894-regression-ltac-uconstr-typing.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#10943 [meta] Add plugin stanza to META so Fl_dynload works for Coq plugins
  META.coq.in
Labels: kind: infrastructure

#10962 Add missing instances for `implb` and `xorb` in ZifyBool.v
  plugins/micromega/ZifyBool.v
Labels: kind: enhancement, part: micromega

#10827 Replace classical reals quotient axioms by functional extensionality
  doc/changelog/10-standard-library/10827-dedekind-reals.rst
  doc/stdlib/index-list.html.template
  plugins/syntax/r_syntax.ml
  test-suite/success/Nsatz.v
  theories/Logic/HLevels.v
  theories/Reals/ClassicalDedekindReals.v
  theories/Reals/ConstructiveCauchyReals.v
  theories/Reals/ConstructiveRIneq.v
  theories/Reals/ConstructiveRcomplete.v
  theories/Reals/ConstructiveRealsMorphisms.v
  theories/Reals/RIneq.v
  theories/Reals/Raxioms.v
  theories/Reals/Rdefinitions.v
Labels: kind: enhancement, part: standard library

#10976 Fix link to `coq-notes.md`
  dev/doc/xml-protocol.md
Labels: kind: documentation, kind: fix

#10952 [library] [nit] Remove unnecessary type alias.
  library/lib.ml
  library/lib.mli
  vernac/classes.ml
Labels: kind: cleanup

#10944 [meta] Add zify plugin to META file.
  META.coq.in
Labels: kind: infrastructure

#10947 Rename `VDFILE` from `.coqdeps.d` to `.<CoqMakefile>.d` in `coq_makefile`
  doc/changelog/08-tools/10947-coq-makefile-dep.rst
  tools/CoqMakefile.in
  tools/coq_makefile.ml
Labels: kind: infrastructure

#10942 Describe XML tags used for highlighting diff text
  dev/doc/xml-protocol.md
Labels: kind: documentation

#10892 [engine] Remove UnivGen.global_of_constr
  dev/doc/changes.md
  engine/univGen.ml
  engine/univGen.mli
Labels: kind: cleanup, kind: question

#10494 Show diffs in "Show Proof."
  doc/changelog/07-commands-and-options/10494-diffs-in-show-proof.rst
  doc/sphinx/proof-engine/proof-handling.rst
  printing/proof_diffs.mli
  tactics/pfedit.ml
  tactics/pfedit.mli
  test-suite/output-coqtop/ShowProofDiffs.out
  test-suite/output-coqtop/ShowProofDiffs.v
  toplevel/coqloop.ml
  toplevel/g_toplevel.mlg
Labels: kind: enhancement

#10949 [declare] Provide helper for private constant inlining.
  tactics/declare.ml
  tactics/declare.mli
  tactics/pfedit.ml
  vernac/declareObl.ml
  vernac/obligations.ml
Labels: kind: cleanup

#10303 Raise an anomaly when looking up unknown constant/inductive
  clib/cMap.ml
  clib/hMap.ml
  clib/int.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/names.ml
  kernel/names.mli
  kernel/safe_typing.ml
  pretyping/indrec.ml
  pretyping/tacred.ml
  vernac/assumptions.ml
Labels: kind: cleanup, part: kernel

#10981 [abstract] Remove un-unused reference to `evar_map`
  tactics/abstract.ml
Labels: kind: cleanup

#10960 Move inference_hook from vernacentries to lemmas
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#10999 [refman] Give an example of contradiction when positivity checking is disabled.
  doc/sphinx/language/cic.rst
Labels: kind: documentation

#11004 [test-suite] Test section-local mutual Fixpoint.
  test-suite/success/Fixpoint.v
Labels: kind: infrastructure, part: test-suite

#10953 [declare] Remove declare_scheme hook in Declare
  tactics/declare.ml
  tactics/declare.mli
  tactics/declareScheme.ml
  tactics/declareScheme.mli
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  tactics/tactics.mllib
Labels: kind: cleanup

#10933 Add clarification in make-changelog.
  dev/tools/make-changelog.sh
Labels: kind: enhancement

#10995 add test for #4502 (fixed by unknown commit)
  test-suite/bugs/closed/bug_4502.v
Labels: kind: internal

#11009 Rename the 2 local type_cstr nonterminals to give them unique names
  parsing/g_constr.mlg
  vernac/g_vernac.mlg
Labels: kind: cleanup

#10997 Implement the unsupported attribute error using the warning system
  doc/changelog/02-specification-language/10997-unsupport-atts-warn.rst
  doc/sphinx/language/gallina-specification-language.rst
  vernac/attributes.ml
Labels: kind: enhancement

#9883 Add support for Sorts in numeral notations
  doc/changelog/03-notations/09883-numeral-notations-sorts.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  interp/notation.ml
  test-suite/output/NumeralNotations.out
  test-suite/output/NumeralNotations.v
Labels: kind: enhancement, part: notations

#11000 make: guard cp calls with rm -f on executables
  Makefile.checker
  Makefile.ide
Labels: kind: fix

#10994 Numbers.Cyclic: use “lia” rather than “omega”
  theories/Numbers/Cyclic/Abstract/CyclicAxioms.v
  theories/Numbers/Cyclic/Abstract/NZCyclic.v
  theories/Numbers/Cyclic/Int31/Cyclic31.v
  theories/Numbers/Cyclic/Int31/Ring31.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/Numbers/Cyclic/ZModulo/ZModulo.v
Labels: kind: cleanup, part: standard library
