Repository rocq-prover/rocq, pull requests merged in 2019-01, with the labels that each got.

#9276 Remove dead code from CClosure.
  kernel/cClosure.ml
  kernel/cClosure.mli
Labels: kind: cleanup

#9264 Fix shallow flag in vernac state
  vernac/vernacstate.ml
Labels: kind: cleanup, part: STM

#8977 Update .mailmap.
  .mailmap
Labels: kind: infrastructure

#9305 Remove formal-topology from CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-formal-topology.sh
Labels: kind: infrastructure

#8373 Fixes #8369: Not_found in printing message about an unresolved subevar.
  test-suite/bugs/closed/bug_8369.v
  test-suite/output/Errors.out
  vernac/himsg.ml
Labels: kind: fix, part: elaboration

#9241 Fix #9240: Register for IDProp causes anomaly when non constant
  pretyping/evarconv.ml
  test-suite/bugs/closed/bug_9240.v
Labels: kind: anomaly, kind: fix

#9292 Fixing some wrong scopes of variables in the interpretation of the "in" clause of a "match"
  interp/constrexpr_ops.ml
  interp/constrexpr_ops.mli
  interp/constrintern.ml
  test-suite/success/Cases.v
Labels: kind: fix, part: notations

#9282 [ssrmatching] update license banner (fix #9281)
  plugins/ssrmatching/ssrmatching.mli
  plugins/ssrmatching/ssrmatching.v
Labels: kind: fix

#9273 Fix #9272: `Unset Nested Proofs Allowed` does not capture nested `Ins…
  stm/stm.ml
  test-suite/bugs/opened/bug_3890.v
Labels: kind: user messages

#9316 Fix #3934: coqc -time -quick gives unreadable output
  lib/system.ml
  lib/system.mli
  stm/stm.ml
  toplevel/vernac.ml
  vernac/topfmt.ml
  vernac/topfmt.mli
  vernac/vernacentries.ml
Labels: kind: fix

#9322 [ci] Update fiat-crypto legacy
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-fiat-crypto-legacy.sh
Labels: kind: infrastructure

#9327 [Manual] Remove link to non-existing CSS file
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation

#9318 Add Azure Pipelines build badge
  README.md
Labels: kind: documentation, kind: infrastructure

#9331 [STM] Fix semantics of `cur_id` w.r.t. error states
  stm/stm.ml
Labels: kind: fix

#9143 Documenting the internal role of to_string and print in Names
  kernel/names.ml
  kernel/names.mli
Labels: kind: internal

#9335 [STM] kill no_safe_id anomaly
  stm/stm.ml
Labels: kind: fix

#8778 Move plugin tutorial to Coq repo
  .github/CODEOWNERS
  .gitlab-ci.yml
  Makefile
  Makefile.ci
  Makefile.common
  Makefile.doc
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-plugin_tutorial.sh
  doc/plugin_tutorial/.gitignore
  doc/plugin_tutorial/.travis.yml
  doc/plugin_tutorial/LICENSE
  doc/plugin_tutorial/Makefile
  doc/plugin_tutorial/README.md
  doc/plugin_tutorial/tuto0/Makefile
  doc/plugin_tutorial/tuto0/_CoqProject
  doc/plugin_tutorial/tuto0/src/dune
  doc/plugin_tutorial/tuto0/src/g_tuto0.mlg
  doc/plugin_tutorial/tuto0/src/tuto0_main.ml
  doc/plugin_tutorial/tuto0/src/tuto0_main.mli
  doc/plugin_tutorial/tuto0/src/tuto0_plugin.mlpack
  doc/plugin_tutorial/tuto0/theories/Demo.v
  doc/plugin_tutorial/tuto0/theories/Loader.v
  doc/plugin_tutorial/tuto1/Makefile
  doc/plugin_tutorial/tuto1/_CoqProject
  doc/plugin_tutorial/tuto1/src/dune
  doc/plugin_tutorial/tuto1/src/g_tuto1.mlg
  doc/plugin_tutorial/tuto1/src/simple_check.ml
  doc/plugin_tutorial/tuto1/src/simple_check.mli
  doc/plugin_tutorial/tuto1/src/simple_declare.ml
  doc/plugin_tutorial/tuto1/src/simple_declare.mli
  doc/plugin_tutorial/tuto1/src/simple_print.ml
  doc/plugin_tutorial/tuto1/src/simple_print.mli
  doc/plugin_tutorial/tuto1/src/tuto1_plugin.mlpack
  doc/plugin_tutorial/tuto1/theories/Loader.v
  doc/plugin_tutorial/tuto2/Makefile
  doc/plugin_tutorial/tuto2/_CoqProject
  doc/plugin_tutorial/tuto2/src/.gitignore
  doc/plugin_tutorial/tuto2/src/demo.mlg
  doc/plugin_tutorial/tuto2/src/demo_plugin.mlpack
  doc/plugin_tutorial/tuto2/src/dune
  doc/plugin_tutorial/tuto2/theories/Test.v
  doc/plugin_tutorial/tuto3/Makefile
  doc/plugin_tutorial/tuto3/_CoqProject
  doc/plugin_tutorial/tuto3/src/construction_game.ml
  doc/plugin_tutorial/tuto3/src/construction_game.mli
  doc/plugin_tutorial/tuto3/src/dune
  doc/plugin_tutorial/tuto3/src/g_tuto3.mlg
  doc/plugin_tutorial/tuto3/src/tuto3_plugin.mlpack
  doc/plugin_tutorial/tuto3/src/tuto_tactic.ml
  doc/plugin_tutorial/tuto3/src/tuto_tactic.mli
  doc/plugin_tutorial/tuto3/theories/Data.v
  doc/plugin_tutorial/tuto3/theories/Loader.v
  doc/plugin_tutorial/tuto3/theories/test.v
  tools/CoqMakefile.in
Labels: kind: documentation

#9307 Handle local definitions in implicit arguments of Instance
  CHANGES.md
  test-suite/bugs/closed/bug_9300.v
  vernac/classes.ml
Labels: kind: fix

#9346 Add .nia.cache to .gitignore
  .gitignore
Labels: kind: cleanup

#9242 merge-pr: add reviewer info to commit message
  dev/tools/merge-pr.sh
Labels: kind: enhancement, kind: infrastructure

#9345 [ci] Update fiat-crypto to the new pipeline
  dev/ci/ci-fiat-crypto.sh
Labels: kind: ci-failure, kind: fix, kind: infrastructure

#9353 Fix merge-pr.sh when multiple review comments
  dev/tools/merge-pr.sh
Labels: kind: fix

#9340 Add badges linking to a selection of up-to-date Coq packages.
  README.md
Labels: kind: documentation

#9332 Add OSX job to azure
  azure-pipelines.yml
Labels: kind: enhancement, kind: infrastructure

#9225 Fix issue: Windows CI: cygwin install cache is not reused #9212
  dev/ci/gitlab.bat
Labels: kind: infrastructure, platform: Windows

#9239 [ci] [appveyor] Pass -j2 to Appveyor's build and build test suite again
  dev/ci/appveyor.sh
Labels: kind: infrastructure, platform: Windows

#9361 Make prvect tail recursive (fix #9355)
  lib/pp.ml
  test-suite/unit-tests/lib/pp_big_vect.ml
Labels: kind: anomaly, kind: fix, kind: user messages

#9339 Move plugin tutorial to team ownership
  .github/CODEOWNERS
Labels: kind: meta

#9337 Fixing #9329: registering empty levels in the order they are computed
  test-suite/bugs/closed/bug_9329.v
  vernac/egramcoq.ml
Labels: kind: fix, part: notations

#9374 Documentation: ring and field simplify can take no arguments
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#9357 Fix recursive loadpath of ML files
  vernac/mltop.ml
Labels: kind: fix

#9377 [CS] recognize applied primitive projections as keys (fix #9375)
  pretyping/recordops.ml
  test-suite/bugs/closed/bug_9375.v
Labels: kind: fix

#9392 Fix small errors in cic.rst.
  doc/sphinx/language/cic.rst
Labels: kind: documentation

#9384 Improve the note in the beginning of the Ltac chapter.
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation

#9325 Stop [Print] from saying [is (not) universe polymorphic].
  printing/prettyp.ml
  test-suite/output/Arguments_renaming.out
  test-suite/output/Binder.out
  test-suite/output/Cases.out
  test-suite/output/Implicit.out
  test-suite/output/Load.out
  test-suite/output/Notations3.out
  test-suite/output/PatternsInBinders.out
  test-suite/output/PrintInfos.out
  test-suite/output/StringSyntax.out
  test-suite/output/TranspModtype.out
  test-suite/output/UnivBinders.out
  test-suite/output/goal_output.out
  test-suite/output/inference.out
Labels: kind: user messages

#9391 Clarify meaning of Primitive Projections
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation

#9362 Fix makefile .merlin for unit tests
  Makefile
Labels: kind: infrastructure

#9402 Move \def\plus and \def\tri to refman-preamble.sty.
  doc/sphinx/language/cic.rst
  doc/sphinx/refman-preamble.sty
Labels: kind: documentation, kind: fix

#9420 [doc] Remove emacs mentions from INSTALL
  INSTALL
Labels: kind: documentation

#9424 Surround "assumption" with :tacn:`` in tactics.rst
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#9383 Remove travis
  .travis.yml
  CONTRIBUTING.md
  README.md
  dev/build/windows/makecoq_mingw.sh
  dev/ci/README-developers.md
  dev/ci/ci-wrapper.sh
  dev/doc/MERGING.md
  dev/tools/merge-pr.sh
  test-suite/report.sh
Labels: kind: cleanup, kind: infrastructure

#9421 [vernac] Fix classification of `Declare Custom Entry`
  stm/vernac_classifier.ml
Labels: kind: fix

#9417 Update update-compat.py script
  dev/tools/update-compat.py
  test-suite/bugs/closed/bug_4798.v
  test-suite/bugs/closed/bug_9166.v
Labels: kind: fix, kind: infrastructure

#9435 Use \mathcal instead of \cal
  dev/doc/versions-history.tex
  doc/common/macros.tex
  doc/sphinx/refman-preamble.sty
Labels: kind: documentation, kind: fix

#9440 Create deployment environment for Cachix.
  .gitlab-ci.yml
Labels: kind: infrastructure

#9448 [ci] [ocaml] Fix OCaml trunk builds.
  .gitlab-ci.yml
  dune
Labels: kind: infrastructure
