Repository rocq-prover/rocq, pull requests merged in 2020-01, with the labels that each got.

#11335 Stdlib : Arith/Wf_nat : Add statements with output in Type
  theories/Arith/Wf_nat.v
Labels: kind: enhancement, part: standard library

#11295 Use code owner teams for every component.
  .github/CODEOWNERS
  CONTRIBUTING.md
  dev/doc/MERGING.md
  dev/doc/shield-icon.png
Labels: kind: meta

#11211 Fixing status reporting for complexity tests
  test-suite/Makefile
Labels: kind: fix, kind: infrastructure

#11340 [refman] Fix bad quoting practice leftover from Sphinx migration.
  doc/sphinx/language/gallina-specification-language.rst
Labels: kind: documentation, kind: fix

#11361 Fix #11360: discharge of template inductive with param only use of var
  doc/changelog/01-kernel/11361-fix-11360-discharge-template-param-var.rst
  kernel/indtypes.ml
  test-suite/bugs/closed/bug_11360.v
Labels: kind: fix, part: kernel, part: sections

#11369 [refman] Correct manual about implicit parameters in inductives
  doc/sphinx/language/gallina-extensions.rst
Labels: kind: documentation, kind: fix

#11245 [tools] Remove support for python2
  azure-pipelines.yml
  default.nix
  doc/changelog/11-infrastructure-and-dependencies/11245-bye+py2.rst
  doc/tools/coqrst/notations/fontsupport.py
  test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh
Labels: kind: infrastructure

#11341 Add non-utf8 timing test
  test-suite/coq-makefile/timing/precomputed-time-tests/run.sh
Labels: kind: fix, kind: infrastructure, part: test-suite

#11378 let CI test bedrock2's 'tested' branch instead of 'master'
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#11375 Add note about default goal selector next to bullet docs
  doc/sphinx/proof-engine/proof-handling.rst
Labels: kind: documentation

#11371 [merge script] Never bypass outdated branch sanity check.
  dev/tools/merge-pr.sh
Labels: kind: infrastructure, kind: meta

#11384 Fix build after merge of #11164
  pretyping/recordops.ml
  pretyping/recordops.mli
  vernac/prettyp.ml
Labels: kind: fix, priority: high

#11387 [refman] missing space in "Controlling the locality of commands"
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation, kind: fix

#11385 Add badges for Docker Hub and coqorg/coq:latest version
  README.md
Labels: kind: documentation, kind: infrastructure

#11349 [refman] [changelog] Announce omega replacement.
  doc/sphinx/addendum/omega.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#11285 fix #11279. Specialize h no longer expands letins in the type of h.
  tactics/tactics.ml
  test-suite/success/specialize.v
Labels: kind: fix

#11081 Native compute: cleanup temporary files on program exit
  clib/cUnix.ml
  clib/cUnix.mli
  doc/changelog/01-kernel/11081-native-cleanup.rst
  kernel/nativelib.ml
Labels: kind: fix

#11392 Document the Set Default Proof Mode command.
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proof-engine/proof-handling.rst
Labels: kind: documentation, kind: fix, priority: blocker

#11394 [coqdoc] Fix #11353: coqdoc -g omits all sentences with decorations
  doc/changelog/08-tools/11394-fix-coqdoc-annotations.rst
  test-suite/coqdoc/bug11353.html.out
  test-suite/coqdoc/bug11353.tex.out
  test-suite/coqdoc/bug11353.v
  tools/coqdoc/cpretty.mll
Labels: kind: fix, priority: blocker

#11249 [stdlib] Additional statements in List.v
  theories/Lists/List.v
Labels: kind: enhancement, part: standard library

#11370 [zify] elim let in ML
  doc/changelog/04-tactics/11370-zify-elim-let.rst
  plugins/micromega/Zify.v
  plugins/micromega/g_zify.mlg
  plugins/micromega/zify.ml
  plugins/micromega/zify.mli
  plugins/omega/PreOmega.v
Labels: kind: performance

#11374 Close #11133
  test-suite/bugs/closed/bug_11133.v
Labels: kind: internal

#11373 Close #11168
  test-suite/bugs/closed/bug_11168.v
Labels: kind: internal

#11362 Lia bugfix 11191
  doc/changelog/04-tactics/11362-micromega-fix-11191.rst
  plugins/micromega/ZifyInst.v
  plugins/micromega/certificate.ml
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  test-suite/micromega/bug_11191a.v
  test-suite/micromega/bug_11191b.v
Labels: kind: fix, kind: regression

#11410 [ci] [gitlab] Add `interruptible: true` to jobs.
  .gitlab-ci.yml
Labels: kind: infrastructure

#11398 Fix issue #11396 : Rlist hides standard list constructors cons and nil
  dev/ci/ci-basic-overlay.sh
  doc/changelog/10-standard-library/11396-issue_11396_Rlist.rst
  theories/Reals/Ranalysis.v
  theories/Reals/Ranalysis_reg.v
  theories/Reals/RiemannInt.v
  theories/Reals/RiemannInt_SF.v
Labels: kind: compatibility, part: standard library

#11214 Add a script to pin CI developments.
  dev/doc/release-process.md
  dev/tools/pin-ci.sh
Labels: kind: infrastructure

#11406 [dune] [dbg] Add support for coqtop in dune-dbg
  coq.opam
  dev/doc/build-system.dune.md
  dev/dune
  dev/dune-dbg.in
  dev/dune_db_408
  dev/dune_db_409
Labels: kind: infrastructure

#11428 [mltop] Deprecate -load-ml options in anticipation of #11409
  doc/changelog/07-commands-and-options/11428-mltop+depr_lowlevel_dynloads.rst
  toplevel/coqargs.ml
Labels: kind: cleanup

#11431 [ci] Pin SF until they solve their CI issues.
  dev/ci/ci-sf.sh
Labels: kind: ci-failure, kind: infrastructure

#11430 [zify] quick fix of #11191
  doc/changelog/04-tactics/11430-fix-lia-regression.rst
  doc/stdlib/hidden-files
  plugins/micromega/ZifyInst.v
  test-suite/micromega/bug_11191.v
Labels: kind: fix, kind: regression

#11433 [xml-protocol doc] Fix link to vscoq
  dev/doc/xml-protocol.md
Labels: kind: documentation

#11422 Fix #11421 computation of Set+2
  dev/doc/critical-bugs
  doc/changelog/01-kernel/11422-Setplus2.rst
  kernel/univ.ml
  test-suite/bugs/closed/bug_11421.v
Labels: kind: inconsistency, part: universes, priority: blocker

#11438 [lint] Use makefile wrapper instead of calling dune command directly.
  Makefile.dune
  dev/lint-repository.sh
Labels: kind: ci-failure, kind: fix, kind: infrastructure, priority: high

#11445 Clear patches folder before each windows build run
  dev/build/windows/MakeCoq_MinGW.bat
Labels: kind: infrastructure, platform: Windows

#11440 Add ZifyPow module, forgotten in #11430.
  plugins/micromega/ZifyPow.v
Labels: kind: fix, part: micromega

#11444 Minor tweaks to the 8.11 changelog.
  doc/sphinx/changes.rst
Labels: kind: documentation

#11446 Changed Gitlab CI runner tag for Windows to windows-inria
  .gitlab-ci.yml
Labels: kind: infrastructure, platform: Windows

#11448 Temporarily remove Menhirlib from built addons
  dev/build/windows/makecoq_mingw.sh
  dev/ci/gitlab.bat
Labels: kind: fix, kind: infrastructure

#11439 Release 8.11.0
  configure.ml
Labels: kind: internal

#11025 Add Set NativeCompute Timing
  doc/changelog/04-tactics/11023-nativecompute-timing.rst
  doc/sphinx/proof-engine/tactics.rst
  pretyping/nativenorm.ml
  pretyping/nativenorm.mli
  vernac/vernacentries.ml
Labels: kind: enhancement, kind: performance, kind: user messages, part: native compiler

#11415 Remove the CoqIDE "Revert all Buffers" command.
  doc/changelog/09-coqide/11415-remove-ide-revert-all-buffers.rst
  ide/coqide.ml
  ide/coqide_ui.ml
Labels: kind: cleanup, kind: fix, part: IDE

#11459 cleanup: Lib.freeze doesn't use its [~marshallable] argument
  library/lib.ml
  library/lib.mli
  library/states.ml
  stm/stm.ml
  vernac/metasyntax.ml
Labels: kind: cleanup

#11419 schemes: use rigid universes
  engine/evd.ml
  engine/evd.mli
  tactics/elimschemes.ml
  test-suite/success/Scheme.v
Labels: kind: enhancement, part: universes

#11379 [ocaml] Remove Custom Backtrace module in favor of OCaml's
  clib/backtrace.ml
  clib/backtrace.mli
  clib/exninfo.ml
  clib/exninfo.mli
  dev/doc/changes.md
  ide/coqide.ml
  lib/cErrors.ml
  lib/control.ml
  lib/flags.ml
  lib/pp.ml
  toplevel/coqargs.ml
  toplevel/coqinit.ml
  toplevel/vernac.ml
  vernac/topfmt.ml
Labels: kind: cleanup, kind: redesign, kind: user messages

#11376 Fix fold order in CArray.fold_right(2)_map
  clib/cArray.ml
  clib/cArray.mli
Labels: kind: internal

#11469 Add reduction-effects to the CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-reduction_effects.sh
Labels: kind: infrastructure

#11473 Remove dead code in Globnames.
  engine/univGen.ml
  engine/univGen.mli
  library/globnames.ml
  library/globnames.mli
  vernac/classes.ml
Labels: kind: cleanup

#11455 Small API additions to kernel/univ
  kernel/uGraph.ml
  kernel/univ.ml
  kernel/univ.mli
  pretyping/detyping.ml
Labels: kind: cleanup

#11408 [mltop] Remove error handling hacks in favor of default methods.
  topbin/coqtop_byte_bin.ml
  vernac/himsg.ml
  vernac/mltop.ml
Labels: kind: cleanup, kind: user messages

#11399 Checker: use inductive's check_template flag
  checker/checkInductive.ml
  checker/check_stat.ml
  test-suite/failure/Template.v
Labels: kind: fix, part: checker

#11409 [rfc] [mltop] Removal of dynamic loading of object and `.ml` files
  doc/changelog/07-commands-and-options/11409-mltop+deprecate_use.rst
  doc/sphinx/practical-tools/coq-commands.rst
  stm/asyncTaskQueue.ml
  topbin/coqtop_byte_bin.ml
  toplevel/coqargs.ml
  toplevel/usage.ml
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: cleanup

#11480 Remove unused CEphemeron.iter_opt, cleanup comments
  clib/cEphemeron.ml
  clib/cEphemeron.mli
Labels: kind: cleanup

#11307 Remove the hacks relying on hardwired libobject tags.
  dev/top_printers.ml
  library/libobject.ml
  library/libobject.mli
  plugins/extraction/extract_env.ml
  tactics/declare.ml
  tactics/declare.mli
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/prettyp.ml
  vernac/search.ml
  vernac/vernac.mllib
Labels: kind: cleanup, part: vernac

#11418 Add some more info to the maintainer doc.
  CONTRIBUTING.md
Labels: kind: documentation, kind: meta

#11464 Fix off-by-one in docs of `first num last` (fix #11463)
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, kind: fix, part: ssreflect

#11377 coqtop: stop on Sys_blocked_io
  toplevel/coqloop.ml
Labels: kind: fix
