Repository rocq-prover/rocq, pull requests merged in 2020-09, with the labels that each got.

#12962 Add zarith to the include path for ocamldebug-coq
  dev/ocamldebug-coq.run
Labels: kind: fix, kind: infrastructure

#12961 [declare] Return both declared constants in Derive path.
  vernac/declare.ml
Labels: kind: fix

#12892 Update update_global_env usage
  dev/ci/user-overlays/12892-SkySkimmer-update-s-univs.sh
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  engine/uState.ml
  engine/uState.mli
  proofs/proof.ml
  proofs/proof.mli
  stm/stm.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/vernacinterp.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: cleanup

#12872 Unify the shelves
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  engine/proofview_monad.ml
  engine/proofview_monad.mli
  engine/termops.ml
  ide/coqide/idetop.ml
  printing/printer.ml
  proofs/proof.ml
  proofs/proof.mli
  proofs/refine.ml
  stm/proofBlockDelimiter.ml
  tactics/class_tactics.ml
  toplevel/coqloop.ml
  vernac/classes.ml
  vernac/declare.ml
  vernac/vernacentries.ml
Labels: kind: fix, kind: redesign

#12883 Use a faster algorithm to check for class existence.
  pretyping/typeclasses.ml
Labels: kind: performance

#12943 Move Elim-specific code
  tactics/elim.ml
  tactics/elim.mli
  tactics/inv.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
Labels: kind: cleanup

#12899 [bench] Update bench script with better urls and more info
  dev/bench/gitlab.sh
Labels: kind: enhancement, kind: fix, kind: infrastructure

#12973 Random cleanup around the data structures used in Equality
  tactics/equality.ml
  tactics/tactics.ml
Labels: kind: cleanup, part: tactics

#12876 Namegen.visible_ids: fixing what seems to be typos
  engine/namegen.ml
Labels: kind: fix

#12956 Perform an inversion of control in hint validation for eapply.
  tactics/hints.ml
Labels: kind: cleanup

#12968 Replace `frozen` by `allowed` evars in evarconv, and delay them
  dev/ci/user-overlays/12968-maximedenes-delay-frozen-evarconv.sh
  plugins/ltac/rewrite.ml
  pretyping/evarconv.ml
  pretyping/evarconv.mli
  pretyping/evarsolve.ml
  pretyping/evarsolve.mli
  pretyping/unification.ml
  pretyping/unification.mli
  proofs/clenv.ml
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/equality.ml
Labels: kind: cleanup, part: unification

#12953 Add :math: around math
  doc/sphinx/addendum/micromega.rst
Labels: kind: documentation, kind: enhancement

#12912 Fix algebraic comparison with sprop on one side
  kernel/uGraph.ml
  test-suite/bugs/closed/bug_12909.v
Labels: kind: fix

#12900 [bench] Also upload the raw timing files, etc
  dev/bench/gitlab-bench.yml
  dev/bench/gitlab.sh
Labels: kind: enhancement, kind: infrastructure

#12893 Fix incorrect debruijn handling when Record calls maybe_unify_params_in
  test-suite/output/bug_12887.out
  test-suite/output/bug_12887.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
Labels: kind: fix, part: primitive records

#12969 CI: build Iris examples instead of lambda-Rust
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-iris.sh
  dev/ci/ci-lambda_rust.sh
Labels: kind: infrastructure

#12980 Simplify the implementation of Elim
  tactics/elim.ml
  tactics/elim.mli
  tactics/inv.ml
Labels: kind: cleanup, part: tactics

#12976 Remove clenv chaining in Equality
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/equality.ml
Labels: kind: cleanup, part: proof engine, part: tactics

#12988 Remove dead code in clenv-generating functions.
  proofs/clenv.ml
  proofs/clenv.mli
Labels: kind: cleanup

#12987 Fix printing of `change` tactic
  plugins/ltac/pptactic.ml
Labels: kind: fix

#12954 Fixes a freshness issue with destruct/induction (see comment in #12944).
  tactics/tactics.ml
  test-suite/bugs/closed/bug_12944.v
  test-suite/success/induct.v
Labels: kind: fix, part: rewriting tactics

#12927 Explain that tactics applied to multiple goals don't preserve the order
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#12991 [Small typo] Update match.rst
  doc/sphinx/language/extensions/match.rst
Labels: kind: documentation, kind: fix

#12931 Proof using cleanup, small doc addition and fix using Type in collections
  doc/sphinx/proof-engine/proof-handling.rst
  test-suite/bugs/closed/bug_12930.v
  vernac/proof_using.ml
Labels: kind: fix

#12993 Remove deprecated tactic cutrewrite.
  doc/changelog/04-tactics/12993-remove-cutrewrite.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/extratactics.mlg
  tactics/equality.ml
  tactics/equality.mli
Labels: kind: cleanup

#12905 Lint stdlib with -mangle-names #2
  theories/Bool/Bool.v
  theories/Classes/CMorphisms.v
  theories/Classes/CRelationClasses.v
  theories/Classes/Morphisms.v
  theories/Classes/RelationClasses.v
  theories/Init/Peano.v
  theories/Init/Tactics.v
  theories/Init/Wf.v
  theories/Numbers/NatInt/NZAdd.v
  theories/Numbers/NatInt/NZBase.v
  theories/Numbers/NatInt/NZDiv.v
  theories/Numbers/NatInt/NZGcd.v
  theories/Numbers/NatInt/NZLog.v
  theories/Numbers/NatInt/NZMul.v
  theories/Numbers/NatInt/NZMulOrder.v
  theories/Numbers/NatInt/NZOrder.v
  theories/Numbers/NatInt/NZParity.v
  theories/Numbers/NatInt/NZPow.v
  theories/Numbers/NatInt/NZSqrt.v
  theories/Relations/Operators_Properties.v
  theories/Relations/Relations.v
  theories/Setoids/Setoid.v
  theories/Structures/GenericMinMax.v
  theories/Structures/Orders.v
  theories/Structures/OrdersFacts.v
  theories/Structures/OrdersTac.v
Labels: kind: cleanup, part: standard library

#7825 [tactics] Refine test for unresolved evars: not reachable from initial evars
  doc/changelog/02-specification-language/07825-rechable-from-evars.rst
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/proofview_monad.ml
  engine/proofview_monad.mli
  engine/termops.ml
  proofs/refine.ml
  tactics/tacticals.ml
  tactics/tactics.ml
  test-suite/bugs/closed/bug_4413.v
  test-suite/bugs/closed/bug_7825.v
  vernac/comFixpoint.ml
Labels: kind: fix, part: tactics, part: unification

#12094 Extend app_inj_tail and other list lemmas
  doc/changelog/10-standard-library/12094-app_inj_tail.rst
  theories/Lists/List.v
Labels: kind: feature, part: standard library

#12994 Fix docgram's dune file following #12085.
  doc/tools/docgram/dune
Labels: kind: fix, kind: infrastructure

#12998 changelog entry for 12857
  doc/changelog/06-ssreflect/12857-changelog-for-12857.rst
Labels: kind: fix

#12997 Add a fast-path to Tactics.e_change_in_hyps.
  tactics/tactics.ml
Labels: kind: performance

#13001 Update INSTALL.md
  INSTALL.md
Labels: kind: documentation

#13005 Add simple-io to dev/ci/nix.
  dev/ci/nix/default.nix
  dev/ci/nix/simple-io.nix
Labels: kind: infrastructure

#13011 Minimal changes to make the refman compatible with Sphinx 3.
  .gitignore
  doc/README.md
  doc/changelog/11-infrastructure-and-dependencies/13011-sphinx-3.rst
  doc/sphinx/README.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/tools/coqrst/coqdomain.py
  doc/tools/docgram/README.md
Labels: kind: compatibility, kind: documentation

#13022 Fixing documentation relatively to example of use of extra spaces in notations
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, part: notations

#13014 [ci] [mathcomp] run the test suite
  dev/ci/ci-mathcomp.sh
Labels: kind: infrastructure

#12972 [ci] [docker] Up testing to OCaml 4.11.1
  .gitlab-ci.yml
  .ocamlformat
  INSTALL.md
  azure-pipelines.yml
  dev/ci/azure-opam.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/dune-workspace.all
  dev/nixpkgs.nix
  doc/changelog/11-infrastructure-and-dependencies/12972-ocaml+4_11.rst
  plugins/micromega/sos.ml
Labels: kind: compatibility, kind: infrastructure, part: ocaml

#13016 Remove deprecated Extraction Language command value "Ocaml"
  doc/changelog/07-commands-and-options/13016-remove-Ocaml-value.rst
  plugins/extraction/g_extraction.mlg
Labels: kind: cleanup

#8743 [micromega] Switch from `Big_int` to ZArith.
  .gitlab-ci.yml
  .merlin.in
  INSTALL.md
  azure-pipelines.yml
  coq.opam
  coq.opam.docker
  dev/build/windows/makecoq_mingw.sh
  dev/ci/docker/bionic_coq/Dockerfile
  plugins/micromega/certificate.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/mfourier.ml
  plugins/micromega/numCompat.ml
  plugins/micromega/numCompat.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/simplex.ml
  plugins/micromega/sos.ml
  plugins/micromega/vect.ml
  test-suite/.csdp.cache.test-suite
  test-suite/Makefile
Labels: kind: cleanup

#13015 Propagate zarith dependency.
  default.nix
Labels: kind: fix, kind: infrastructure

#13008 Use fresher names in eqschemes
  tactics/eqschemes.ml
  test-suite/bugs/closed/bug_13003.v
Labels: kind: fix

#13024 [CI] Always upload artifacts
  .gitlab-ci.yml
Labels: kind: infrastructure

#13007 [build] Don't link `num` anymore in Coq
  .gitlab-ci.yml
  INSTALL.md
  META.coq.in
  Makefile.build
  azure-pipelines.yml
  configure.ml
  coq.opam
  coq.opam.docker
  default.nix
  dev/ci/docker/bionic_coq/Dockerfile
  doc/changelog/11-infrastructure-and-dependencies/13007-zarith+goodbye_num.rst
  plugins/micromega/dune
  tools/CoqMakefile.in
  toplevel/dune
Labels: kind: compatibility, kind: infrastructure

#13027 [vernac] Don't allow attributes on print / check
  vernac/vernacentries.ml
Labels: kind: fix, kind: user messages

#12610 [leminv] [declare] Use higher-level Declare API.
  plugins/ltac/leminv.ml
Labels: kind: internal

#13043 [ci] call dmesg after quick/async jobs to detect OOM
  .gitlab-ci.yml
Labels: kind: infrastructure

#13051 Improve `simple apply` example
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#12963 Formally deprecate the double induction tactic.
  plugins/ltac/coretactics.mlg
  test-suite/success/induct.v
  theories/Reals/Rseries.v
Labels: hijacked, kind: cleanup

#13055 Fix Removed in Sphinx 4 deprecations.
  doc/tools/coqrst/coqdomain.py
Labels: kind: compatibility

#13052 Clean up Dnet implementation
  tactics/btermdn.ml
  tactics/btermdn.mli
  tactics/dn.ml
  tactics/dn.mli
Labels: kind: cleanup, part: tactics

#12723 dune: pass -bin-annot to configure
  config/dune
Labels: kind: infrastructure, part: build

#13057 Adding debugging printers for Intmap
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
Labels: kind: infrastructure

#13063 Make print-pretty-timed robust against non-output-sync logs
  dev/ci/ci-common.sh
  doc/changelog/08-tools/13063-fix-no-output-sync-make-file.rst
  test-suite/coq-makefile/timing/precomputed-time-tests/007-no-output-sync/run.sh
  test-suite/coq-makefile/timing/precomputed-time-tests/007-no-output-sync/time-of-build.err.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/007-no-output-sync/time-of-build.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/007-no-output-sync/time-of-build.log.in
  test-suite/coq-makefile/timing/precomputed-time-tests/run.sh
  tools/TimeFileMaker.py
Labels: kind: fix, kind: infrastructure, part: tools

#13049 [configure] Fix version checks for lablgtk and zarith
  INSTALL.md
  configure.ml
  dev/nixpkgs.nix
Labels: kind: fix, kind: infrastructure

#13050 [ci/gitlab/cachix] Avoid running in trouble when calling git fetch --unshallow
  .gitlab-ci.yml
Labels: kind: infrastructure

#13046 Small optimization of acyclic graph merge operation
  lib/acyclicGraph.ml
Labels: kind: performance

#13056 [v8.12] Use tag v2.6 for VST, like in the platform.
  dev/build/windows/makecoq_mingw.sh
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-vst.sh
Labels: kind: infrastructure

#12960 Fixes #9403 and #10803: missing flattening of nested applications in notations
  doc/changelog/03-notations/12960-master+fix9403-missing-flattening-app-notations.rst
  interp/notation_ops.ml
  test-suite/output/bug_10803.out
  test-suite/output/bug_10803.v
  test-suite/output/bug_9403.out
  test-suite/output/bug_9403.v
Labels: kind: fix, part: notations

#13067 Setting default value for Display Parentheses off in CoqIDE
  doc/changelog/03-notations/13067-master+fix-display-parentheses-default-coqide.rst
  ide/coqide/coq.ml
Labels: kind: user messages, part: IDE, part: notations, part: printer

#13026 A temporary fix of #13018 and #12775 for branch 8.12
  doc/changelog/03-notations/13026-master+fix-printing-custom-no-level-8.2.rst
  test-suite/output/bug_13018.out
  test-suite/output/bug_13018.v
  vernac/metasyntax.ml
Labels: kind: fix, part: notations, part: printer

#13061 fix build:quick and build:base+async artifacts
  .gitlab-ci.yml
Labels: kind: fix, kind: infrastructure

#12847 Tactics inversion and replace work with eq in type
  doc/changelog/04-tactics/12847-master+inversion-works-with-eq-in-type.rst
  tactics/equality.ml
  tactics/inv.ml
  test-suite/success/eqtacticsnois.v
Labels: kind: enhancement, kind: fix

#13028 Fixes #9716 and #13004: don't drop the qualifier of quotations at printing time
  dev/ci/user-overlays/13028-herbelin-master+fix-quotations-printing.sh
  dev/doc/changes.md
  doc/changelog/05-tactic-language/13028-master+fix-quotations-printing.rst
  plugins/ltac/extraargs.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/pptactic.ml
  plugins/ltac/tacentries.ml
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacsubst.ml
  plugins/setoid_ring/newring.ml
  plugins/ssr/ssrparser.mlg
  test-suite/output/bug_13004.out
  test-suite/output/bug_13004.v
  test-suite/output/print_ltac.out
  user-contrib/Ltac2/tac2core.ml
Labels: kind: fix, part: printer, part: tactics

#13073 A temporary fix of #13018 and #12775 for branch 8.12 (bis)
  doc/changelog/03-notations/13026-master+fix-printing-custom-no-level-8.2.rst
  test-suite/output/bug_13018.out
  test-suite/output/bug_13018.v
  vernac/metasyntax.ml
Labels: kind: fix, part: notations, part: printer

#12977 Statically ensure that only polymophic hint terms come with a context.
  dev/ci/user-overlays/12977-ppedrot-static-hint-poly.sh
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/hints.mli
  vernac/classes.ml
  vernac/comHints.ml
Labels: kind: cleanup

#13077 Fix issue #13065 - Windows CI broken
  dev/build/windows/patches_coq/ocaml-4.08.1.patch
Labels: kind: fix, platform: Windows

#12894 Modify bytecode representation of closures to please OCamls GC (fix #12636).
  kernel/byterun/coq_fix_code.c
  kernel/byterun/coq_interp.c
  kernel/byterun/coq_memory.c
  kernel/byterun/coq_values.c
  kernel/byterun/coq_values.h
  kernel/genOpcodeFiles.ml
  kernel/vm.ml
  kernel/vmbytegen.ml
  kernel/vmemitcodes.ml
  kernel/vmsymtable.ml
  kernel/vmvalues.ml
  kernel/vmvalues.mli
Labels: kind: fix, part: VM

#12919 [v8.12] Document incompatibility with OCaml 4.12.
  INSTALL.md
  configure.ml
Labels: kind: documentation

#12999 More improvements in locating tactic errors
  plugins/ltac/taccoerce.ml
  plugins/ltac/taccoerce.mli
  plugins/ltac/tacinterp.ml
  test-suite/output/ErrorLocation_ltac_1.out
  test-suite/output/ErrorLocation_ltac_1.v
  test-suite/output/ErrorLocation_ltac_2.out
  test-suite/output/ErrorLocation_ltac_2.v
  test-suite/output/ErrorLocation_ltac_3.out
  test-suite/output/ErrorLocation_ltac_3.v
  test-suite/output/ErrorLocation_ltac_4.out
  test-suite/output/ErrorLocation_ltac_4.v
Labels: kind: fix, part: tactics, priority: high

#13053 [lib] make canonical_path_name always absolute (fix #13031)
  clib/cUnix.ml
  test-suite/misc/coq_makefile_destination_of.sh
Labels: kind: fix

#13105 [nix] CI script wrapper now requires Python
  dev/ci/nix/default.nix
Labels: kind: infrastructure

#12946 Fixes part 1 of #12908: undetected collision involving a lonely notation at printing time.
  doc/changelog/03-notations/12946-master+fix12908-part1-collision-lonely-notation-printing.rst
  interp/notation.ml
  test-suite/output/bug_12908.out
  test-suite/output/bug_12908.v
Labels: kind: fix, part: notations

#13039 Lint stdlib with -mangle-names #3
  theories/Arith/Between.v
  theories/Arith/Compare_dec.v
  theories/Arith/EqNat.v
  theories/Arith/Factorial.v
  theories/Arith/Le.v
  theories/Arith/Mult.v
  theories/Arith/PeanoNat.v
  theories/Arith/Peano_dec.v
  theories/Arith/Plus.v
  theories/Arith/Wf_nat.v
  theories/Lists/List.v
  theories/Logic/EqdepFacts.v
  theories/Logic/Eqdep_dec.v
  theories/NArith/BinNat.v
  theories/NArith/Nnat.v
  theories/Numbers/Natural/Abstract/NAdd.v
  theories/Numbers/Natural/Abstract/NAddOrder.v
  theories/Numbers/Natural/Abstract/NBase.v
  theories/Numbers/Natural/Abstract/NBits.v
  theories/Numbers/Natural/Abstract/NDiv.v
  theories/Numbers/Natural/Abstract/NGcd.v
  theories/Numbers/Natural/Abstract/NLcm.v
  theories/Numbers/Natural/Abstract/NMaxMin.v
  theories/Numbers/Natural/Abstract/NOrder.v
  theories/Numbers/Natural/Abstract/NParity.v
  theories/Numbers/Natural/Abstract/NPow.v
  theories/Numbers/Natural/Abstract/NSub.v
  theories/PArith/BinPos.v
  theories/PArith/Pnat.v
  theories/setoid_ring/BinList.v
  theories/setoid_ring/Ring_theory.v
Labels: kind: cleanup, part: standard library

#13097 Modify how quotations handle whole sentences.
  ide/coqide/coq_lex.mll
  parsing/cLexer.ml
Labels: kind: fix, part: IDE

#13101 Reduce nitpick_ignore list a little.
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/conf.py
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/user-extensions/proof-schemes.rst
Labels: kind: cleanup, kind: documentation, kind: fix

#13111 Small document fixes.
  doc/sphinx/language/cic.rst
  doc/sphinx/language/coq-library.rst
Labels: kind: documentation

#13032 More precise information when unification fails because of incompatible candidates
  pretyping/evarsolve.ml
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  vernac/himsg.ml
Labels: kind: user messages

#13021 Almost fully moving funind to new proof engine
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/functional_principles_proofs.mli
  plugins/funind/gen_principle.ml
  plugins/funind/indfun_common.ml
  plugins/funind/indfun_common.mli
  plugins/funind/recdef.ml
  proofs/tacmach.ml
  proofs/tacmach.mli
  tactics/tacticals.ml
  tactics/tacticals.mli
Labels: kind: cleanup, part: tactics
