Repository rocq-prover/rocq, pull requests merged in 2020-08, with the labels that each got.

#12772 coqdoc: Fix the “details” environment
  doc/changelog/08-tools/12772-fix-details.rst
  test-suite/coqdoc/details.html.out
  test-suite/coqdoc/details.tex.out
  test-suite/coqdoc/details.v
  tools/coqdoc/cpretty.mll
Labels: kind: fix, part: coqdoc

#12706 Mention coqbot minimize feature in issue template.
  .github/ISSUE_TEMPLATE.md
Labels: kind: meta

#12724 CI metacoq: make .merlin
  dev/ci/ci-metacoq.sh
Labels: kind: infrastructure

#12782 Trying to rephrase complex sentences to make them easier to read.
  doc/sphinx/language/extensions/evars.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/language/extensions/match.rst
Labels: kind: documentation, kind: fix

#12643 Document "Print Debug GC" command and OCAMLRUNPARAM environment variable
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proof-engine/proof-handling.rst
Labels: kind: documentation

#12796 [default.nix] Propagate dependency on num following #12604.
  default.nix
Labels: kind: fix, kind: infrastructure

#12749 [ssr] turn "nothing to inject" into a real warning (fix #12746)
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  plugins/ssr/ssrelim.ml
  tactics/equality.ml
  tactics/equality.mli
  test-suite/ssr/noting_to_inject.v
Labels: kind: user messages

#12814 [zify] fix for bug#12791
  plugins/micromega/zify.ml
  test-suite/micromega/bug_12791.v
Labels: kind: fix, part: micromega

#12815 [micromega] Fix bug#12790
  plugins/micromega/certificate.ml
  test-suite/micromega/bug_12790.v
Labels: kind: fix, part: micromega

#12794 Repair coqide option "Display parentheses"
  ide/coqide/coq.ml
Labels: kind: fix, part: IDE

#12717 More documentation on grammars and parsing
  dev/README.md
  dev/doc/parsing.md
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#12748 Windows CI: changed cygwin repo server
  dev/build/windows/MakeCoq_MinGW.bat
Labels: kind: ci-failure, platform: Windows

#12479 Bring Int63 notations into line with stdlib
  doc/changelog/10-standard-library/12479-fix-int-ltb-notations.rst
  test-suite/primitive/uint63/eqb.v
  test-suite/primitive/uint63/leb.v
  test-suite/primitive/uint63/ltb.v
  test-suite/primitive/uint63/mod.v
  test-suite/primitive/uint63/unsigned.v
  theories/Array/PArray.v
  theories/Numbers/Cyclic/Int63/Cyclic63.v
  theories/Numbers/Cyclic/Int63/Int63.v
Labels: kind: fix, part: notations, part: standard library

#12556 Bring Float notations in line with stdlib
  doc/changelog/10-standard-library/12556-fix-float-ltb-notations.rst
  doc/sphinx/language/coq-library.rst
  test-suite/bugs/closed/bug_12483.v
  test-suite/primitive/float/compare.v
  test-suite/primitive/float/gen_compare.sh
  theories/Floats/FloatAxioms.v
  theories/Floats/PrimFloat.v
Labels: kind: fix, part: notations, part: standard library

#12718 Do not rely on higher-order interfaces for patterns in dnets.
  tactics/btermdn.ml
  tactics/btermdn.mli
  tactics/dn.ml
  tactics/dn.mli
  tactics/hints.ml
Labels: kind: cleanup

#12720 Factor code related to class hint clenv
  dev/ci/user-overlays/12720-ppedrot-factor-class-hint-clenv.sh
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/auto.ml
  tactics/auto.mli
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#12716 deprecate prod_curry and prod_uncurry
  doc/changelog/10-standard-library/12716-curry.rst
  theories/Init/Datatypes.v
Labels: kind: cleanup, part: standard library

#12799 [stdlib] [List] Additional statements about List.repeat
  doc/changelog/10-standard-library/12799-list-repeat.rst
  theories/Lists/List.v
  theories/Sorting/Permutation.v
Labels: kind: feature, part: standard library

#12823 Move reduce_mind_case from Reductionops to Tacred.
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/tacred.ml
Labels: kind: cleanup

#12751 Fixes reduction effect printing in the presence of non purely applicative stacks
  pretyping/cbv.ml
  pretyping/reductionops.ml
  tactics/cbn.ml
Labels: kind: fix

#12802 Document semantic restriction on patterns in Gallina match construct
  doc/sphinx/language/core/variants.rst
  interp/constrintern.ml
Labels: kind: documentation, kind: fix, kind: user messages

#12841 Recommend replace as a replacement to cutrewrite.
  doc/sphinx/proof-engine/tactics.rst
  tactics/equality.ml
Labels: kind: documentation, kind: user messages

#12774 Fixing tactic loc updating in #12223
  plugins/ltac/tacinterp.ml
  test-suite/output/ErrorLocation_12774_1.out
  test-suite/output/ErrorLocation_12774_1.v
  test-suite/output/ErrorLocation_12774_2.out
  test-suite/output/ErrorLocation_12774_2.v
  test-suite/output/ErrorLocation_tac_in_term_1.out
  test-suite/output/ErrorLocation_tac_in_term_1.v
  test-suite/output/ErrorLocation_tac_in_term_2.out
  test-suite/output/ErrorLocation_tac_in_term_2.v
Labels: kind: fix

#12725 Store evar identity instances in evarinfo / named_context_val
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  kernel/environ.ml
  kernel/environ.mli
  plugins/ssr/ssrcommon.ml
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/globEnv.ml
  proofs/goal.ml
  tactics/tactics.ml
Labels: kind: performance

#12822 Do not precompute hint dnets eagerly
  tactics/hints.ml
Labels: kind: performance

#12709 Simplify hint pattern handling
  dev/ci/user-overlays/12709-ppedrot-hint-pattern-out.sh
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#12856 Adding a mention of the JSON extraction in the documentation.
  doc/sphinx/addendum/extraction.rst
Labels: kind: documentation

#12756 Do not refresh the names of implicit arguments.
  dev/ci/user-overlays/12756-jashug-dont-refresh-argument-names.sh
  doc/changelog/02-specification-language/12756-dont-refresh-argument-names.rst
  interp/impargs.ml
  test-suite/bugs/closed/bug_12001.v
  test-suite/output/Arguments_renaming.out
  test-suite/output/Arguments_renaming.v
  test-suite/output/Implicit.out
  test-suite/success/Typeclasses.v
  vernac/comArguments.ml
Labels: kind: cleanup, kind: fix, part: implicit arguments

#12851 Extraction: At declaration point of a global, use its declaring name
  plugins/extraction/common.ml
  plugins/extraction/common.mli
  plugins/extraction/ocaml.ml
Labels: kind: fix

#12816 Fixes #12787: anomaly of tactic injection in the presence of artificial dependencies disappearing by reduction
  .gitlab-ci.yml
  dev/bench/gitlab.sh
  dev/bench/render_results
  dev/bench/sort-by-deps
  dev/bench/sort-by-deps.sh
  dev/bench/timelog2html
  doc/changelog/04-tactics/12816-master+fix12787-K-redex-injection-anomaly.rst
  tactics/equality.ml
  test-suite/bugs/closed/bug_12787.v
Labels: kind: fix, part: tactics

#12832 Introduce GitHub Action to check for conflicts in PRs.
  .github/CODEOWNERS
  .github/workflows/check-conflicts.yml
Labels: kind: infrastructure

#12854 Mini-fix in test suite: arithmetic directory does no longer exist
  test-suite/Makefile
Labels: kind: fix, part: test-suite

#12864 Improve `make approve-output`
  doc/changelog/11-infrastructure-and-dependencies/12864-fix-approve-output.rst
  test-suite/Makefile
Labels: kind: fix, kind: infrastructure, part: test-suite

#12738 Fix subject reduction VS cumulative inductives and function eta
  doc/changelog/01-kernel/12738-fix-sr-cumul-inds.rst
  kernel/reduction.ml
  test-suite/bugs/closed/bug_7015.v
Labels: kind: fix, part: kernel

#12565 Dnets now consider axioms as being opaque for pattern recognition.
  dev/ci/user-overlays/12565-ppedrot-fix-tc-search-opacity.sh
  tactics/auto.ml
  tactics/btermdn.ml
  tactics/btermdn.mli
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: performance

#12835 Slightly reorganising the test suite to follow its documentation
  test-suite/Makefile
  test-suite/bugs/bug_5996.v
  test-suite/bugs/closed/bug_11140.v
  test-suite/bugs/closed/bug_4690.v
  test-suite/bugs/closed/bug_9490.v
  test-suite/bugs/closed/bug_9532.v
  test-suite/bugs/opened/bug_2904.v
  test-suite/bugs/opened/bug_5996.v
Labels: needs: test-suite update

#12868 Lint stdlib with -mangle-names #1
  theories/Init/Datatypes.v
  theories/Init/Logic.v
  theories/Init/Specif.v
Labels: kind: cleanup, part: standard library

#12886 Fix Coqtail test directory.
  dev/ci/ci-coqtail.sh
Labels: kind: infrastructure

#12878 Update sigma instead of erasing it in `update_global_env`
  engine/proofview.ml
  engine/proofview.mli
  proofs/proof.ml
  proofs/proof.mli
  vernac/declare.ml
Labels: kind: cleanup, part: proof engine

#12778 Merging is now possible with coqbot.
  CONTRIBUTING.md
Labels: kind: documentation, kind: meta

#12870 CI: stop testing 4.11+trunk
  .gitlab-ci.yml
Labels: kind: infrastructure

#12798 Change OUnit package name to ounit2.
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  test-suite/Makefile
  test-suite/unit-tests/.merlin.in
Labels: kind: compatibility, kind: infrastructure, part: test-suite

#12882 Perform a few tweaks to make the bench script work properly.
  .gitlab-ci.yml
  dev/bench/gitlab.sh
Labels: kind: infrastructure, part: bench

#12728 Fix slow Print Universes Subgraph when many ambient universes.
  vernac/vernacentries.ml
Labels: kind: fix, kind: performance, part: universes

#12888 Add /dev/bench to CODEOWNERS
  .github/CODEOWNERS
Labels: kind: infrastructure

#12801 Put cyclic numbers in sort Set instead of Type
  dev/ci/user-overlays/12801-VincentSe-CyclicSet.sh
  doc/changelog/10-standard-library/12801-cyclic-set.rst
  theories/Numbers/Cyclic/Abstract/CyclicAxioms.v
  theories/Numbers/Cyclic/Abstract/DoubleType.v
Labels: kind: performance, part: standard library

#12758 Fixing a coercion entry transitivity bug.
  interp/notation.ml
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: kind: fix, part: notations

#12897 [test-suite] close the proof added in #12857
  test-suite/output/ssr_error_multiple_intro_after_case.v
Labels: kind: fix, part: test-suite

#12879 added numeral_notation to META.coq.in
  META.coq.in
Labels: kind: fix, kind: infrastructure

#12861 Require NsatzTactic: nsatz support for Z and Q
  doc/changelog/10-standard-library/12861-nsatz-tactic-instances.rst
  doc/sphinx/addendum/nsatz.rst
  test-suite/bugs/closed/bug_12860.v
  theories/nsatz/Nsatz.v
  theories/nsatz/NsatzTactic.v
Labels: kind: fix, part: standard library

#12884 Documentation of coq_makefile: fix name of installation dir + help on using option -f
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: enhancement, part: tools

#12901 [bench] Remove useless commit guessing logic
  dev/bench/gitlab.sh
Labels: kind: infrastructure

#12881 Deprecate intro_using
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/recdef.ml
  plugins/omega/coq_omega.ml
  tactics/elim.ml
  tactics/eqdecide.ml
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/bugs/closed/bug_12676.v
Labels: kind: fix, part: tactics

#12904 Move bench job definition to its own file
  .gitlab-ci.yml
  dev/bench/gitlab-bench.yml
Labels: kind: infrastructure

#12085 Convert ltac2 chapter to use prodn, update syntax
  Makefile.doc
  doc/sphinx/_static/coqnotations.sty
  doc/sphinx/_static/notations.css
  doc/sphinx/changes.rst
  doc/sphinx/conf.py
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/conversion.rst
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/coqrst/coqdomain.py
  doc/tools/docgram/README.md
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#12898 [ssr] backport ssrbool from Math Comp 1.11
  theories/ssr/ssrbool.v
Labels: kind: feature, part: ssreflect

#12911 Use the lite variants of performance tests in the bench default packages
  dev/bench/gitlab-bench.yml
Labels: kind: infrastructure

#12867 Fast freeze summary
  clib/dyn.ml
  clib/dyn.mli
  library/summary.ml
Labels: kind: performance

#12877 Propagate in-context information for explicitation of extra arguments of notations
  interp/constrextern.ml
  test-suite/output/Implicit.out
  test-suite/output/Implicit.v
  test-suite/output/Notations5.out
  test-suite/output/Notations5.v
Labels: kind: enhancement, part: notations, part: printer

#12850 Avoid running configure when plugins/ modified
  config/dune
  config/list_plugins.ml
  configure.ml
Labels: kind: infrastructure

#12913 Modify lia to work with -mangle-names
  test-suite/bugs/closed/bug_12907.v
  theories/micromega/Lia.v
Labels: kind: fix, part: micromega

#12499 Clean future goals
  clib/option.ml
  clib/option.mli
  engine/evarutil.ml
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  engine/proofview_monad.ml
  engine/proofview_monad.mli
  ide/coqide/idetop.ml
  printing/printer.ml
  proofs/goal.ml
  proofs/goal.mli
  proofs/proof.ml
  proofs/proof.mli
  proofs/refine.ml
  stm/proofBlockDelimiter.ml
  tactics/class_tactics.ml
  test-suite/bugs/closed/bug_10939.v
  test-suite/bugs/closed/bug_4095.v
  toplevel/coqloop.ml
  vernac/classes.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, part: proof engine

#12918 tacinterp mini cleanup useless letin
  plugins/ltac/tacinterp.ml
Labels: kind: cleanup

#12862 [coqchk] Look inside inner modules as well
  checker/mod_checking.ml
  doc/changelog/08-tools/12862-more-mod-checking.rst
  test-suite/output-coqchk/bug_12845.out
  test-suite/output-coqchk/bug_12845.v
Labels: kind: fix, part: checker

#12849 Rename VM-related kernel/cfoo files to kernel/vmfoo
  .github/CODEOWNERS
  Makefile.build
  Makefile.make
  dev/vm_printers.ml
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/dune
  kernel/genOpcodeFiles.ml
  kernel/kernel.mllib
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/nativelambda.ml
  kernel/term_typing.ml
  kernel/vconv.ml
  kernel/vm.ml
  kernel/vmbytecodes.ml
  kernel/vmbytecodes.mli
  kernel/vmbytegen.ml
  kernel/vmbytegen.mli
  kernel/vmemitcodes.ml
  kernel/vmemitcodes.mli
  kernel/vmlambda.ml
  kernel/vmlambda.mli
  kernel/vmsymtable.ml
  kernel/vmsymtable.mli
  pretyping/vnorm.ml
  tactics/redexpr.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: internal

#12922 Fix .gitignore after the merge of #12849.
  .gitignore
Labels: kind: internal

#12632 [state] A few nits after consolidation of state.
  stm/stm.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: internal

#12924 Remove meta-based refiner code in ssr
  engine/evarutil.ml
  engine/evarutil.mli
  plugins/ssr/ssrelim.ml
Labels: kind: cleanup

#12932 par: print relevant subgoal when failing
  stm/stm.ml
  test-suite/output/Partac.out
  test-suite/output/Partac.v
Labels: kind: user messages

#12933 Add test for past anomaly
  test-suite/bugs/closed/bug_5703.v
Labels: kind: internal

#11742 [numeral] [plugins] Remove Coq's `Bigint` module in favor of ZArith.
  .gitlab-ci.yml
  INSTALL.md
  META.coq.in
  Makefile.build
  azure-pipelines.yml
  clib/bigint.ml
  clib/bigint.mli
  configure.ml
  coq.opam
  coq.opam.docker
  default.nix
  dev/base_include
  dev/build/windows/MakeCoq_MinGW.bat
  dev/build/windows/makecoq_mingw.sh
  dev/ci/azure-opam.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/08743-ejgallego-zarith.sh
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  doc/changelog/11-infrastructure-and-dependencies/11742-zarith+core.rst
  interp/dune
  interp/notation.ml
  interp/notation.mli
  interp/numTok.ml
  interp/numTok.mli
  plugins/extraction/big.ml
  plugins/extraction/dune
  plugins/nsatz/dune
  plugins/nsatz/ideal.ml
  plugins/nsatz/nsatz.ml
  plugins/nsatz/polynom.ml
  plugins/nsatz/polynom.mli
  plugins/omega/coq_omega.ml
  plugins/syntax/float_syntax.ml
  plugins/syntax/r_syntax.ml
  tools/CoqMakefile.in
  toplevel/dune
Labels: kind: cleanup, kind: infrastructure, kind: internal

#12890 ring: generate fresh names for lemmas
  plugins/setoid_ring/newring.ml
  test-suite/bugs/closed/bug_12889.v
Labels: kind: fix, part: tactics

#12939 Fix configure check for zarith
  configure.ml
Labels: kind: infrastructure

#12929 Make abstract compatible with mangle names
  tactics/abstract.ml
  test-suite/bugs/closed/bug_12928.v
  test-suite/bugs/closed/bug_3146.v
  test-suite/success/name_mangling.v
Labels: kind: fix

#12934 Enrich `evar_map` printer with future goals stack
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
Labels: kind: internal, part: proof engine

#12952 Fix rendering of -> in micromega
  doc/sphinx/addendum/micromega.rst
Labels: kind: documentation, kind: fix

#12935 Drop opaque bodies of abstracted definitions.
  kernel/safe_typing.ml
Labels: kind: performance

#12875 Further extensions of About wrt Arguments and renaming
  dev/ci/user-overlays/12875-herbelin-master+about-print-all-arguments-names.sh
  interp/impargs.ml
  interp/impargs.mli
  plugins/ssr/ssrvernac.mlg
  test-suite/output/Arguments.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/Arguments_renaming.v
  test-suite/output/Cases.out
  test-suite/output/Implicit.out
  test-suite/output/Inductive.out
  test-suite/output/InitSyntax.out
  test-suite/output/PatternsInBinders.out
  test-suite/output/PrintInfos.out
  test-suite/output/Projections.out
  test-suite/output/UnivBinders.out
  vernac/comArguments.ml
  vernac/prettyp.ml
Labels: kind: enhancement, kind: user messages, part: implicit arguments

#12958 Fix load_printers after zarith
  dev/core.dbg
  dev/core_dune.dbg
  dev/dune_db_408
  dev/dune_db_409
Labels: kind: fix, kind: infrastructure, part: build
