Repository rocq-prover/rocq, pull requests merged in 2020-12, with the labels that each got.

#13531 [kernel]Use ~l2r:true to restore previous order of unfolding
  kernel/inductive.ml
Labels: kind: fix, kind: performance, part: kernel

#13526 dune: Don't echo "$(pwd)" when creating the shims
  dev/shim/dune
Labels: kind: infrastructure, part: build

#13490 [ssr] Backport ssrbool from MathComp 1.12.0
  doc/changelog/06-ssreflect/13490-backport-ssrbool.rst
  theories/ssr/ssrbool.v
Labels: kind: enhancement, part: ssreflect

#13472 [ci] Add job for gappa
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-gappa.sh
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#13543 Fix a bug in funind.
  plugins/funind/recdef.ml
Labels: kind: fix

#13471 gitlab CI: remove redundant "dependencies" info
  .gitlab-ci.yml
Labels: kind: infrastructure

#13275 Put all Int63 primitives in a separate file
  doc/stdlib/index-list.html.template
  plugins/syntax/int63_syntax.ml
  test-suite/output/Int63Syntax.out
  test-suite/output/Int63Syntax.v
  test-suite/primitive/uint63/addcarryc.v
  test-suite/primitive/uint63/addmuldiv.v
  test-suite/primitive/uint63/diveucl.v
  test-suite/primitive/uint63/head0.v
  test-suite/primitive/uint63/subcarryc.v
  test-suite/primitive/uint63/tail0.v
  theories/Floats/PrimFloat.v
  theories/Numbers/Cyclic/Abstract/CarryType.v
  theories/Numbers/Cyclic/Abstract/DoubleType.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/Numbers/Cyclic/Int63/PrimInt63.v
Labels: kind: enhancement, part: standard library

#13554 Split long lines in errors and warning index
  doc/sphinx/_static/notations.css
Labels: kind: documentation, kind: infrastructure

#13548 Move *_with_full_binders variants out of the kernel.
  engine/termops.ml
  kernel/constr.ml
  kernel/constr.mli
  vernac/assumptions.ml
Labels: kind: cleanup

#13558 [refman] Fix error names.
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/definitions.rst
Labels: kind: documentation

#13497 [rm] update release notes
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#13551 Stop calling Id.Map.domain on univ binders every individual universe
  engine/univNames.ml
  library/nametab.ml
  library/nametab.mli
  tactics/declareUctx.ml
Labels: kind: performance, kind: regression, part: universes

#13442 Add an abstraction function in the LtacX FFI.
  doc/changelog/05-tactic-language/13442-ltac2-abstract-ffi.rst
  test-suite/ltac2/compat.v
  user-contrib/Ltac2/Ltac1.v
  user-contrib/Ltac2/tac2core.ml
  user-contrib/Ltac2/tac2env.ml
  user-contrib/Ltac2/tac2env.mli
  user-contrib/Ltac2/tac2interp.ml
  user-contrib/Ltac2/tac2interp.mli
Labels: kind: feature, part: ltac2

#13569 typo
  doc/sphinx/language/extensions/arguments-command.rst
Labels: kind: documentation

#13552 Delay inventing names for monomorphic universes
  engine/uState.ml
  engine/uState.mli
  test-suite/output/UnivBinders.out
  test-suite/output/UnivBinders.v
  vernac/declareUniv.ml
  vernac/declareUniv.mli
Labels: kind: performance, kind: regression, kind: user messages, part: universes

#13553 Document Number Notation for primitive integers
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, part: notations

#13585 [RM] Update changes 13501
  doc/changelog/01-kernel/13501-fix-13495.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#13556 Fix spelling in warning entry
  doc/changelog/07-commands-and-options/13556-master.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/output/bug_12908.v
  vernac/metasyntax.ml
Labels: kind: fix

#13587 Tag 8.13 beta1
  azure-pipelines.yml
  configure.ml
Labels: kind: infrastructure

#13588 Add `depopts: coq-native` in coq.opam.docker
  coq.opam.docker
Labels: kind: infrastructure

#13596 Add a test for cbv over inductive types which feature let-bindings.
  test-suite/success/cbv_let.v
Labels: kind: internal

#13572 [dune] [opam] Disable dune subst in opam files until the upstream fix is propagated
  coq-doc.opam
  coq.opam
  coqide-server.opam
  coqide.opam
  dune-project
Labels: kind: fix, kind: infrastructure

#13597 Congruence: don't replace error messages by "congruence failed"
  plugins/cc/cctac.ml
  plugins/cc/cctac.mli
  test-suite/output/bug_13595.out
  test-suite/output/bug_13595.v
Labels: kind: fix, kind: user messages

#13591 [rm] update instructions for windows signing
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#13537 More efficient implementation for substitutions.
  dev/ci/user-overlays/13537-ppedrot-lazy-subst-kernel.sh
  kernel/cClosure.ml
  kernel/esubst.ml
  kernel/esubst.mli
  kernel/nativelambda.ml
  kernel/typeops.ml
  kernel/vmlambda.ml
  pretyping/cbv.ml
Labels: kind: performance, part: kernel

#13564 Allow all characters in tacn, cmd, ... names. Report duplicate names.
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: infrastructure

#13605 [osx] disable brew cleanup
  azure-pipelines.yml
Labels: kind: fix, kind: infrastructure

#13590 Move Azure jobs to GitHub Actions.
  .github/workflows/ci.yml
  README.md
  azure-pipelines.yml
  dev/ci/azure-build.sh
Labels: kind: infrastructure

#12100 Fixing use of argument scopes in patterns + a further cleanup of constrintern.ml
  interp/constrintern.ml
  pretyping/cases.ml
  pretyping/cases.mli
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  test-suite/output/Cases.out
  test-suite/output/Cases.v
  test-suite/output/RecordFieldErrors.out
  test-suite/output/RecordFieldErrors.v
  test-suite/success/Case22.v
  test-suite/success/Cases.v
  vernac/himsg.ml
Labels: kind: cleanup, kind: fix, part: notations

#13608 Changelog for 8.12.2.
  doc/sphinx/changes.rst
Labels: kind: documentation

#13607 [v8.12] 8.12.2 release
  configure.ml
  doc/sphinx/changes.rst
Labels: kind: documentation, kind: infrastructure

#13582 Generalize exp_ineq1 and add exp_ineq1_le, which holds forall Reals.
  doc/changelog/10-standard-library/13582-exp_ineq.rst
  theories/Reals/Rpower.v
Labels: kind: feature, part: standard library

#13540 Clean support of primitive integers
  interp/notation.ml
  kernel/byterun/coq_uint63_emul.h
  kernel/uint63.mli
  kernel/uint63_31.ml
  kernel/uint63_63.ml
Labels: kind: cleanup, kind: inconsistency, part: parser, part: printer, part: reduction strategies

#13612 Bump reference to 8.12 refman following unexpected 8.12.2 release.
  doc/sphinx/conf.py
Labels: kind: documentation, kind: infrastructure

#13611 Clarify changelog categories.
  doc/changelog/07-vernac-commands-and-options/00000-title.rst
  doc/changelog/07-vernac-commands-and-options/13556-master.rst
  doc/changelog/08-cli-tools/00000-title.rst
  doc/changelog/08-tools/00000-title.rst
Labels: kind: documentation, kind: meta

#13519 Better primitive type support in custom string and numeral notations.
  doc/changelog/03-notations/13519-primitiveArrayNotations.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  engine/evd.ml
  engine/evd.mli
  engine/univGen.ml
  engine/univGen.mli
  interp/notation.ml
  kernel/environ.ml
  kernel/environ.mli
  test-suite/output/StringSyntaxPrimitive.out
  test-suite/output/StringSyntaxPrimitive.v
Labels: kind: enhancement, part: notations

#13492 Removing non relevant argument binding_kind of GLocalDef.
  dev/doc/changes.md
  interp/constrextern.ml
  interp/constrintern.ml
  interp/notation_ops.ml
  pretyping/glob_term.ml
Labels: kind: cleanup

#13603 [ci] function to declare projects
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-common.sh
  dev/ci/user-overlays/12218-proux01-numeral-notations-non-inductive.sh
  dev/ci/user-overlays/12449-SkySkimmer-minim-prop-toset.sh
  dev/ci/user-overlays/12611-ejgallego-record+refactor.sh
  dev/ci/user-overlays/12653-SkySkimmer-cumul-syntax.sh
  dev/ci/user-overlays/12873-master+minifix-unification-error-reporting-recheck-applications.sh
  dev/ci/user-overlays/13075-ppedrot-explicit-names-quotient.sh
  dev/ci/user-overlays/13128-SkySkimmer-noinstance.sh
  dev/ci/user-overlays/13139-ppedrot-clean-hint-constr.sh
  dev/ci/user-overlays/13166-herbelin-master+fixes13165-missing-impargs-defined-fields.sh
  dev/ci/user-overlays/13312-ejgallego-attributes+bool_single.sh
  dev/ci/user-overlays/13386-master+fix9971-primproj-canonical-structure-on-evar-type.sh
  dev/ci/user-overlays/13415-SkySkimmer-intern-univs.sh
  dev/ci/user-overlays/13481-elpi-1.12.sh
  dev/ci/user-overlays/README.md
  dev/tools/create_overlays.sh
  dev/tools/notify-upstream-pins.sh
Labels: kind: infrastructure

#13620 Use a registered printer for tactic coercion failure.
  plugins/ltac/taccoerce.ml
Labels: kind: performance

#13619 doc: Clarify the status of simpl vs cbn
  doc/sphinx/proofs/writing-proofs/rewriting.rst
Labels: kind: documentation

#13509 Remove compatibility flag Set Bracketing Last Introduction Pattern
  doc/changelog/04-tactics/13509-master+remove-bracketing-last-introduction-pattern-flag.rst
  doc/sphinx/proof-engine/tactics.rst
  tactics/tactics.ml
  test-suite/bugs/closed/bug_4787.v
Labels: kind: compatibility

#13613 [changes] mark #12765 as experimental
  doc/sphinx/changes.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#13626 [ci] update doc for overlays
  dev/ci/user-overlays/README.md
Labels: kind: documentation, kind: internal, kind: meta

#13523 [envars] honor file "coq_environment.txt"
  INSTALL.md
  lib/envars.ml
  test-suite/dune
  test-suite/misc/coq_environment.sh
  test-suite/ocaml_pwd.ml
  tools/coq_makefile.ml
Labels: kind: cleanup

#13630 Cleanup reductionops
  pretyping/recordops.ml
  pretyping/recordops.mli
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/unification.ml
Labels: kind: cleanup

#13632 [ci] Update pin ci script
  dev/ci/ci-basic-overlay.sh
  dev/tools/pin-ci.sh
Labels: kind: fix, kind: infrastructure

#13621 Fast path in tclPROGRESS.
  clib/cList.ml
  clib/cList.mli
  engine/proofview.ml
Labels: kind: performance

#13609 Extrude the computation of redexp flags in reduce.
  tactics/genredexpr.ml
  tactics/redexpr.ml
  tactics/redexpr.mli
  tactics/tactics.ml
Labels: kind: cleanup, kind: performance, part: tactics

#13633 [ci] uniform name of projects w.r.t. opam packages
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-elpi.sh
  dev/ci/ci-gappa.sh
Labels: kind: cleanup, kind: infrastructure

#13625 Tweak constr_matching so as to make it tail-rec on projection expansion.
  pretyping/constr_matching.ml
Labels: kind: performance

#13615 Document the manual tasks that I need to do at each release.
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#13616 Bench: add .log extension to .stdout/stderr files
  dev/bench/gitlab.sh
Labels: kind: infrastructure

#13568 Fix #13566: Add checks for invalid occurrences in several tactics.
  doc/changelog/04-tactics/13568-master+fix13566-check-invalid-occurrences-especially-rewrite.rst
  plugins/ltac/extratactics.mlg
  plugins/ltac/rewrite.ml
  pretyping/find_subterm.ml
  pretyping/find_subterm.mli
  pretyping/locusops.ml
  pretyping/locusops.mli
  pretyping/tacred.ml
  test-suite/success/rewrite_in.v
Labels: kind: fix, part: tactics

#13644 Fix overlay system: projects need to be loaded before overlays.
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-common.sh
Labels: kind: infrastructure

#13643 Add -q flag to coqrst python invocation of coqtop
  doc/tools/coqrst/repl/coqtop.py
Labels: kind: documentation, kind: fix, kind: infrastructure

#13652 Add a test for change over case nodes.
  test-suite/success/change_case.v
Labels: kind: infrastructure

#13628 Cache meta instances in Clenv
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/typing.ml
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/equality.ml
  tactics/hints.ml
  tactics/tactics.ml
Labels: kind: performance

#13530 Revert removal of eoi_entry in #13447
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/ltac/pltac.ml
  plugins/ltac/pltac.mli
Labels: kind: cleanup, kind: fix

#13138 Towards a documentation / cleanup of evarconv
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/evarsolve.mli
  pretyping/reductionops.ml
  pretyping/reductionops.mli
Labels: kind: cleanup, part: unification

#13651 Shorten/improve intro of "Basic proof writing" chapter.
  doc/sphinx/proofs/writing-proofs/index.rst
Labels: kind: documentation

#13649 Lint stdlib with -mangle-names #5
  theories/Bool/BoolEq.v
  theories/Bool/DecBool.v
  theories/Bool/IfProp.v
  theories/Bool/Zerob.v
  theories/Classes/CEquivalence.v
  theories/Classes/CMorphisms.v
  theories/Classes/CRelationClasses.v
  theories/Classes/DecidableClass.v
  theories/Classes/Equivalence.v
  theories/Logic/FunctionalExtensionality.v
  theories/Logic/JMeq.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/Program/Wf.v
  theories/QArith/QArith_base.v
  theories/QArith/Qreduction.v
  theories/ZArith/Zgcd_alt.v
  theories/ZArith/Zpow_facts.v
  theories/ZArith/Zpower.v
  theories/micromega/Tauto.v
  theories/micromega/ZMicromega.v
  theories/setoid_ring/Field_theory.v
Labels: kind: cleanup, part: standard library

#13673 Clean ALL sphinx output files
  Makefile.doc
Labels: kind: documentation, kind: infrastructure

#13650 [ci/gitlab/windows] Bump OCaml to 4.10.2 to fix Windows CI.
  dev/build/windows/makecoq_mingw.sh
Labels: kind: fix, kind: infrastructure

#13677 CoqIDE: Fix CC reference in makefile
  Makefile.ide
Labels: kind: infrastructure

#13659 Make ssr datastructures cpattern and rpattern public
  plugins/ssr/ssrast.mli
  plugins/ssr/ssrbwd.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrprinters.ml
  plugins/ssr/ssrprinters.mli
  plugins/ssrmatching/g_ssrmatching.mlg
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
Labels: kind: cleanup

#13679 [v8.13] [CI] Update paramcoq branch to v8.13
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#13662 Fixes #13657: vscoq needs goal uid.
  ide/coqide/idetop.ml
  ide/coqide/wg_ProofView.ml
Labels: kind: fix

#13665 Set Python's default output encoding to utf-8
  .gitlab-ci.yml
  dev/ci/docker/README.md
  dev/ci/docker/bionic_coq/Dockerfile
  doc/README.md
  doc/tools/coqrst/coqdomain.py
Labels: kind: infrastructure

#13686 [refman] Clarify meaning of goal in documentation of instantiate.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#13684 Document the -native-compiler option
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proofs/writing-proofs/rewriting.rst
Labels: kind: documentation, part: native compiler

#13682 Fix broken HTML rendering of inference rules (fix #12783).
  test-suite/coqdoc/verbatim.html.out
  tools/coqdoc/output.ml
Labels: kind: fix, part: coqdoc

#13321 Move evaluable_global_reference from Names to Tacred.
  dev/ci/user-overlays/13321-ppedrot-mv-evaluable-global-ref-out-of-kernel.sh
  kernel/mod_subst.ml
  kernel/mod_subst.mli
  kernel/names.ml
  kernel/names.mli
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/indfun_common.ml
  plugins/funind/indfun_common.mli
  plugins/ltac/pptactic.ml
  plugins/ltac/pptactic.mli
  plugins/ltac/taccoerce.ml
  plugins/ltac/taccoerce.mli
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacsubst.ml
  plugins/ltac/tauto.ml
  plugins/omega/coq_omega.ml
  plugins/ssr/ssrequality.ml
  pretyping/heads.ml
  pretyping/tacred.ml
  pretyping/tacred.mli
  printing/printer.mli
  proofs/tacmach.mli
  tactics/auto.ml
  tactics/eauto.ml
  tactics/genredexpr.ml
  tactics/hints.mli
  tactics/redexpr.ml
  tactics/redexpr.mli
  tactics/tactics.mli
  user-contrib/Ltac2/tac2tactics.ml
  vernac/classes.mli
  vernac/comHints.ml
  vernac/declare.ml
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#13692 Fix failing Windows CI builds.
  dev/build/windows/makecoq_mingw.sh
Labels: kind: infrastructure
