Repository rocq-prover/rocq, pull requests merged in 2020-03, with the labels that each got.

#11708 [ci] elpi 1.10.2
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/11051-gares-elpi-1.8.sh
  dev/ci/user-overlays/11708-gares-elpi-1.10.sh
Labels: kind: infrastructure

#11728 [dune] [doc] Be more explicit about coqtop dependencies
  dev/doc/build-system.dune.md
Labels: kind: documentation, part: build

#11681 Fix backtraces in conversion anomalies caught by Reductionops.
  pretyping/reductionops.ml
Labels: kind: internal

#11634 Remove the dependency in float.cmo and uint63.cmo for building votour
  Makefile.build
Labels: kind: fix, part: build

#11695 Refactor lookaheads
  parsing/g_constr.mlg
  parsing/g_prim.mlg
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/ltac/extraargs.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_tactic.mlg
  plugins/ssr/ssrparser.mlg
  toplevel/g_toplevel.mlg
  user-contrib/Ltac2/g_ltac2.mlg
  vernac/g_vernac.mlg
Labels: kind: cleanup, part: parser

#11709 Deprecate the "prolog" tactic.
  plugins/ltac/g_auto.mlg
Labels: kind: cleanup

#11618 [loadpath] Rework and simplify ML loadpath handling
  doc/changelog/11-infrastructure-and-dependencies/11618-loadpath+split_ml_handling.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  ide/coq_commands.ml
  ide/fake_ide.ml
  stm/stm.ml
  stm/stm.mli
  test-suite/ide/debug_ltac.fake
  test-suite/ide/undo002.fake
  toplevel/ccompile.ml
  toplevel/coqargs.ml
  toplevel/coqargs.mli
  toplevel/coqinit.ml
  toplevel/coqinit.mli
  toplevel/coqtop.ml
  vernac/g_vernac.mlg
  vernac/loadpath.ml
  vernac/loadpath.mli
  vernac/mltop.ml
  vernac/mltop.mli
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: infrastructure, part: build

#11380 [exninfo] Deprecate aliases for exception re-raising.
  engine/logic_monad.ml
  engine/proofview.ml
  engine/proofview.mli
  ide/idetop.ml
  ide/protocol/xmlprotocol.ml
  interp/impargs.ml
  interp/notation.ml
  kernel/inductive.ml
  kernel/nativelib.ml
  kernel/safe_typing.ml
  lib/cErrors.mli
  lib/future.ml
  lib/system.ml
  lib/util.mli
  library/states.ml
  parsing/pcoq.ml
  plugins/funind/indfun_common.ml
  plugins/ltac/extratactics.mlg
  plugins/ltac/tacinterp.ml
  plugins/ssr/ssrcommon.ml
  pretyping/cases.ml
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/unification.ml
  proofs/refiner.ml
  stm/asyncTaskQueue.ml
  stm/stm.ml
  tactics/abstract.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/pfedit.ml
  tactics/tacticals.mli
  tactics/tactics.ml
  toplevel/coqinit.ml
  toplevel/coqloop.ml
  toplevel/vernac.ml
  user-contrib/Ltac2/tac2core.ml
  vernac/declareDef.ml
  vernac/declaremods.ml
  vernac/indschemes.ml
  vernac/lemmas.ml
  vernac/library.ml
  vernac/metasyntax.ml
  vernac/obligations.ml
  vernac/topfmt.ml
  vernac/vernacentries.ml
  vernac/vernacextend.ml
  vernac/vernacinterp.ml
  vernac/vernacstate.ml
Labels: kind: cleanup

#11429 [zify] several efficiency enhancements
  doc/changelog/04-tactics/11429-zify-optimisation.rst
  plugins/micromega/certificate.ml
  plugins/micromega/g_zify.mlg
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  plugins/micromega/zify.ml
  plugins/micromega/zify.mli
  test-suite/.csdp.cache
  theories/micromega/Lia.v
  theories/micromega/ZMicromega.v
  theories/micromega/Zify.v
  theories/micromega/ZifyClasses.v
  theories/micromega/ZifyInst.v
  theories/omega/PreOmega.v
Labels: kind: performance, part: micromega

#11715 Be robust in calculating visible ids for non-registered constants.
  engine/namegen.ml
  test-suite/output/bug_8206.out
  test-suite/output/bug_8206.v
Labels: kind: fix

#11602 Adding support for an "only parsing" modifier in "where"-based notation
  dev/ci/user-overlays/11602-herbelin-master+support-only-parsing-where-clause.sh
  doc/changelog/03-notations/11602-master+support-only-parsing-where-clause.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/output/Inductive.out
  test-suite/output/Inductive.v
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/vernacexpr.ml
Labels: kind: enhancement, part: notations

#11522 Adding an alias `pose proof (x:=t)` for `pose proof t as x` following the model of `pose (x:=t)`.
  doc/changelog/04-tactics/11522-master+pose-proof-wo-as-syntax.rst
  doc/sphinx/proof-engine/tactics.rst
  plugins/ltac/g_tactic.mlg
  test-suite/success/pose.v
Labels: kind: enhancement

#7791 Deprecating the declaration of arbitrary terms as hints.
  doc/changelog/07-commands-and-options/7791-deprecate-hint-constr.rst
  doc/sphinx/proof-engine/tactics.rst
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/hints.mli
  vernac/classes.ml
Labels: kind: cleanup

#11693 [boot] Don't initialize coqlib when `-boot` is passed.
  toplevel/coqargs.ml
  toplevel/coqinit.ml
  toplevel/coqinit.mli
  toplevel/coqloop.ml
  toplevel/coqtop.ml
Labels: kind: infrastructure, part: build

#11744 [dune] Fix bug in auto-configure deps.
  config/dune
Labels: kind: infrastructure, part: build

#11717 [dune] [ocamldebug] Improve ocamldebug rules
  dev/doc/build-system.dune.md
  dev/dune
Labels: kind: infrastructure, part: build

#11723 Fix mishandling of sigma in guess_elim (regression from 8.11)
  tactics/tactics.ml
  test-suite/bugs/closed/bug_11722.v
Labels: kind: fix

#11698 Fix #11592: Side effect safety may be broken by universe effects
  kernel/safe_typing.ml
  test-suite/misc/side-eff-leak-univs.sh
  test-suite/misc/side-eff-leak-univs/.gitignore
  test-suite/misc/side-eff-leak-univs/_CoqProject
  test-suite/misc/side-eff-leak-univs/src/evil.mlg
  test-suite/misc/side-eff-leak-univs/src/evil_plugin.mlpack
  test-suite/misc/side-eff-leak-univs/theories/evil.v
Labels: kind: fix, kind: inconsistency

#11740 Ltac2: Add notation for enough and eenough
  doc/changelog/05-tactic-language/11740-ltac2-enough.rst
  test-suite/ltac2/example2.v
  user-contrib/Ltac2/Notations.v
Labels: kind: feature, part: ltac2

#11714 [gramlib] Refactor gramlib interface.
  gramlib/grammar.ml
  gramlib/grammar.mli
  parsing/extend.ml
  parsing/pcoq.ml
Labels: kind: cleanup

#11578 [exn] Keep information from multiple extra exn handlers
  lib/cErrors.ml
  lib/cErrors.mli
  plugins/ltac/tactic_debug.ml
  plugins/ltac/tactic_debug.mli
  user-contrib/Ltac2/tac2entries.ml
Labels: kind: fix, kind: internal

#11773 [doc] [dune] Update Dune build instructions
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#11720 Remove some productionlists
  doc/sphinx/README.rst
  doc/sphinx/README.template.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/conf.py
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/coqrst/coqdomain.py
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#11787 Do not erase OCAMLPATH in CI targets with Dune-built Coq
  dev/ci/ci-common.sh
Labels: kind: fix, part: build, part: test-suite

#11774 [exn] [nit] Remove not very useful re-raises.
  kernel/safe_typing.ml
  lib/control.ml
  lib/pp.ml
  tactics/pfedit.ml
  vernac/vernacextend.ml
  vernac/vernacstate.ml
Labels: kind: cleanup

#11763 Fixing an amusing small bug in parsing decimal numbers in R
  plugins/syntax/r_syntax.ml
  test-suite/output/RealSyntax.out
  test-suite/output/RealSyntax.v
Labels: kind: fix, part: parser

#11764 Simplify mutual template polymorphism
  checker/checkInductive.ml
  checker/checkTypes.mli
  checker/values.ml
  dev/ci/user-overlays/11764-ppedrot-simplify-template.sh
  kernel/cooking.ml
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/entries.ml
  kernel/environ.ml
  kernel/indTyping.ml
  kernel/indTyping.mli
  kernel/indtypes.ml
  kernel/inductive.ml
  kernel/inductive.mli
  pretyping/evarsolve.ml
  pretyping/inductiveops.ml
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: cleanup

#11732 Update the OCaml version in `default.nix` to 4.09.0
  Makefile.doc
  default.nix
  dev/nixpkgs.nix
Labels: kind: infrastructure

#11788 Prevent CoqIDE from hanging when invalid channels are still open.
  ide/coqide.ml
Labels: kind: fix, part: IDE

#11767 Fix #11738 : Funind using deprecated Coqlib API.
  plugins/funind/indfun_common.ml
  plugins/funind/recdef.ml
  theories/Arith/Lt.v
  theories/Arith/PeanoNat.v
  theories/Arith/Wf_nat.v
  theories/Init/Peano.v
  theories/Init/Wf.v
Labels: kind: cleanup

#11790 [lib] [ccalgo] Remove unused code / cleanup
  clib/cStack.ml
  clib/cStack.mli
  clib/clib.mllib
  lib/util.ml
  lib/util.mli
  plugins/cc/ccalgo.mli
Labels: kind: cleanup

#11786 Fix #11730: Mangle Names vs Infix
  test-suite/bugs/closed/bug_11730.v
  vernac/metasyntax.ml
Labels: kind: fix

#11769 Fix #9930: "change" replaces 0-param projections by constants
  pretyping/tacred.ml
  test-suite/bugs/closed/bug_9512.v
  test-suite/bugs/closed/bug_9930.v
Labels: kind: fix

#11800 [ci] [gitlab] Move VST to `allow_failure`
  .gitlab-ci.yml
Labels: kind: ci-failure

#11754 [micromega] Add numerical compatibility layer.
  Makefile.build
  plugins/micromega/certificate.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/csdpcert.ml
  plugins/micromega/itv.ml
  plugins/micromega/itv.mli
  plugins/micromega/mfourier.ml
  plugins/micromega/micromega_plugin.mlpack
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/numCompat.ml
  plugins/micromega/numCompat.mli
  plugins/micromega/persistent_cache.ml
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  plugins/micromega/simplex.ml
  plugins/micromega/simplex.mli
  plugins/micromega/sos.ml
  plugins/micromega/sos.mli
  plugins/micromega/sos_lib.ml
  plugins/micromega/sos_lib.mli
  plugins/micromega/sos_types.ml
  plugins/micromega/sos_types.mli
  plugins/micromega/vect.ml
  plugins/micromega/vect.mli
  plugins/micromega/zify.ml
Labels: kind: cleanup, kind: compatibility

#11810 [dune] Fix ocamlopt_flags for release profile
  dune
Labels: kind: fix, part: build

#11780 Minor improvements to the unreleased changelog.
  doc/changelog/02-specification-language/11098-master+arguments-supports-anonymous-implicit.rst
  doc/changelog/02-specification-language/11368-trailing_implicit_error.rst
  doc/changelog/02-specification-language/11600-uniform-syntax.rst
  doc/changelog/03-notations/10832-master+fix6082-7766-overriding-notation-format.rst
  doc/changelog/03-notations/11650-parensNew.rst
  doc/changelog/04-tactics/10760-more-rapply.rst
  doc/changelog/04-tactics/10998-zify-complements.rst
  doc/changelog/04-tactics/11023-nativecompute-timing.rst
  doc/changelog/04-tactics/11288-omega+depr.rst
  doc/changelog/04-tactics/11362-micromega-fix-11191.rst
  doc/changelog/04-tactics/11370-zify-elim-let.rst
  doc/changelog/04-tactics/11429-zify-optimisation.rst
  doc/changelog/04-tactics/11474-lia-bug-fix-11436.rst
  doc/changelog/05-tactic-language/10343-issue-10342-ltac2-standard-library.rst
  doc/changelog/05-tactic-language/11740-ltac2-enough.rst
  doc/changelog/07-commands-and-options/07791-deprecate-hint-constr.rst
  doc/changelog/07-commands-and-options/10747-canonical-better-message.rst
  doc/changelog/07-commands-and-options/11164-let-cs.rst
  doc/changelog/07-commands-and-options/11618-loadpath+split_ml_handling.rst
  doc/changelog/08-tools/11409-mltop+deprecate_use.rst
  doc/changelog/08-tools/11523-coqdep+refactor2.rst
  doc/changelog/08-tools/11617-toplevel+boot.rst
  doc/changelog/09-coqide/11414-remove-ide-tactic-menu.rst
  doc/changelog/09-coqide/11415-remove-ide-revert-all-buffers.rst
  doc/changelog/10-standard-library/11127-trunk.rst
  doc/changelog/10-standard-library/11240-rew-dependent.rst
  doc/changelog/10-standard-library/11686-fix-int-notations.rst
  doc/changelog/11-infrastructure-and-dependencies/11245-bye+py2.rst
  doc/changelog/12-misc/10486-native-string-extraction.rst
Labels: kind: documentation, kind: fix

#11781 Minor improvements to the unreleased changelog.
  doc/changelog/09-coqide/10008-snyke7+escape_spaces.rst
Labels: kind: documentation, kind: fix

#11798 Tests make bytecode
  test-suite/coq-makefile/camldep/run.sh
  test-suite/coq-makefile/findlib-package-unpacked/run.sh
Labels: kind: infrastructure

#11796 Remove parallel building of Sphinx documentation.
  doc/dune
Labels: kind: fix, kind: infrastructure, part: build

#11003 [vernac] Remove deprecated function.
  vernac/comAssumption.ml
  vernac/comAssumption.mli
Labels: kind: cleanup

#11815 [ci] [doc] Point to actual docker instructions.
  dev/ci/README-users.md
Labels: kind: documentation, kind: infrastructure

#11804 [CI] test hierarchy builder as part of elpi
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-elpi.sh
Labels: kind: infrastructure

#11016 [proof] Remove duplication in the proof save path.
  vernac/comFixpoint.ml
  vernac/declareDef.ml
  vernac/declareDef.mli
  vernac/declareObl.ml
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#11805 Fix coqchk for primitive integers on 32bit arch with OCaml >= 4.08 (#11624)
  checker/analyze.ml
Labels: kind: fix, part: checker

#11803 Update Azure MacOS version 10.13 -> 10.14
  azure-pipelines.yml
  dev/build/osx/make-macos-dmg.sh
Labels: kind: infrastructure, priority: high

#11688 When parsing a negative integer, ensure that the minus sign is contiguous to the number.
  parsing/g_prim.mlg
Labels: kind: enhancement, part: parser

#11797 Dune build rules for doc_grammar and fullGrammar.
  coqpp/dune
  doc/tools/docgram/README.md
  doc/tools/docgram/dune
Labels: kind: documentation, part: build, part: parser

#10858 Implementing postponed constraints in TC resolution
  doc/changelog/02-specification-language/10858-stuck-classed.md
  doc/sphinx/addendum/type-classes.rst
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/class_tactics.mli
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
  test-suite/bugs/closed/bug_9058.v
  test-suite/success/HintMode.v
  test-suite/success/Typeclasses.v
Labels: kind: enhancement, part: typeclasses

#11831 [ci] Re-enable VST testing
  .gitlab-ci.yml
Labels: kind: infrastructure

#11813 Fixed link to "match" syntax figures.
  doc/sphinx/addendum/extended-pattern-matching.rst
Labels: kind: documentation, kind: fix

#11811 Remove a positivity check when Positivity Checking is off
  doc/changelog/01-kernel/11811-uncheck_positivity_bug.rst
  kernel/indtypes.ml
  test-suite/bugs/closed/bug_11811.v
Labels: kind: fix, part: kernel

#11825 [ci] [docker] Update components in Docker image
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/08726-herbelin-master+more-stable-meaning-to-Discharge-flag.sh
  dev/ci/user-overlays/09566-ejgallego-proof_global+move_termination_routine_out.sh
  dev/ci/user-overlays/09645-ejgallego-proof+sayonara_baby.sh
  dev/ci/user-overlays/09867-primitive-floats.sh
  dev/ci/user-overlays/10204-rm-unsafe-type-of-coercion.sh
  dev/ci/user-overlays/10231-herbelin-master+locating-warning-different-implicit-term-type.sh
  dev/ci/user-overlays/10316-ejgallego-proof+recthms.sh
  dev/ci/user-overlays/10319-SkySkimmer-vernac-when-sideff.sh
  dev/ci/user-overlays/10334-ppedrot-rm-kernel-sideeff-role.sh
  dev/ci/user-overlays/10337-ejgallego-vernac+qed_special_case_inject_proof.sh
  dev/ci/user-overlays/10362-ppedrot-delay-poly-opaque.sh
  dev/ci/user-overlays/10406-ppedrot-desync-entry-proof.sh
  dev/ci/user-overlays/10419-ejgallego-heads+test.sh
  dev/ci/user-overlays/10434-ejgallego-proof+hook_record.sh
  dev/ci/user-overlays/10441-ppedrot-static-poly-section.sh
  dev/ci/user-overlays/10476-maximedenes-rm-library-optim.sh
  dev/ci/user-overlays/10516-ejgallego-proof+dup_save.sh
  dev/ci/user-overlays/10642-SkySkimmer-feedback-added-axiom.sh
  dev/ci/user-overlays/10660-ejgallego-errors+private.sh
  dev/ci/user-overlays/10665-ejgallego-api+varkind.sh
  dev/ci/user-overlays/10674-ejgallego-proofs+declare_unif.sh
  dev/ci/user-overlays/10681-ejgallego-proof+private_entry.sh
  dev/ci/user-overlays/10727-ejgallego-library+to_vernac_step2.sh
  dev/ci/user-overlays/10811-SkySkimmer-sprop-default-on.sh
  dev/ci/user-overlays/10832-herbelin-master+fix6082-7766-overriding-notation-format.sh
  dev/ci/user-overlays/11027-SkySkimmer-expose-comind-univ.sh
  dev/ci/user-overlays/11141-herbelin-master+labelled-pr_lconstr-and-co.sh
  dev/ci/user-overlays/11172-herbelin-master+coercion-notation-interleaved-printing.sh
  dev/ci/user-overlays/11235-non-maximal-implicit.sh
  dev/ci/user-overlays/11293-ppedrot-rename-class-files.sh
  dev/ci/user-overlays/11338-ppedrot-rm-global-uses-evd.sh
  dev/ci/user-overlays/11368-trailing-implicit-error.sh
  dev/ci/user-overlays/11417-ppedrot-rm-kind-of-type.sh
  dev/ci/user-overlays/11521-SkySkimmer-no-optname.sh
  dev/ci/user-overlays/11557-SkySkimmer-template-directify.sh
  dev/ci/user-overlays/11602-herbelin-master+support-only-parsing-where-clause.sh
  dev/ci/user-overlays/11708-gares-elpi-1.10.sh
  dev/ci/user-overlays/11764-ppedrot-simplify-template.sh
Labels: kind: infrastructure

#11699 Comment difference between the 2 hashes on constr
  kernel/constr.ml
Labels: kind: internal

#11746 Register commonly used names from the Reals library for plugins (e.g. gappa)
  doc/stdlib/index-list.html.template
  theories/Reals/Rregisternames.v
Labels: kind: feature, part: standard library

#11839 Dead code in g_prim.mlg
  parsing/g_prim.mlg
Labels: kind: cleanup, part: parser

#11812 Add an Export locality to hints
  dev/ci/user-overlays/11812-ppedrot-export-hint-globality.sh
  doc/changelog/07-commands-and-options/11812-export-hint-globality.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  plugins/ltac/g_auto.mlg
  pretyping/typeclasses.ml
  pretyping/typeclasses.mli
  tactics/hints.ml
  tactics/hints.mli
  test-suite/success/export_hint.v
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/classes.ml
  vernac/declareObl.ml
  vernac/obligations.ml
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: enhancement

#11607 Hide binder type in Ltac2
  test-suite/ltac2/binder.v
  test-suite/ltac2/constr.v
  user-contrib/Ltac2/Constr.v
  user-contrib/Ltac2/Init.v
  user-contrib/Ltac2/tac2core.ml
  user-contrib/Ltac2/tac2ffi.ml
  user-contrib/Ltac2/tac2ffi.mli
Labels: kind: cleanup, part: ltac2

#11735 Deprecating catchable_exception
  dev/doc/changes.md
  engine/proofview.ml
  engine/proofview.mli
  plugins/ltac/rewrite.ml
  plugins/ltac/tacintern.ml
  plugins/ltac/tactic_debug.ml
  plugins/omega/coq_omega.ml
  proofs/logic.mli
  proofs/refiner.ml
  tactics/class_tactics.ml
  tactics/class_tactics.mli
  tactics/equality.ml
  tactics/hints.ml
  tactics/tactics.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#11822 Grants #11692: clear dependent knows about let-in
  test-suite/output/clear.out
  test-suite/output/clear.v
  theories/Init/Tactics.v
Labels: kind: enhancement, part: tactics

#11795 Print implicit arguments in types of references
  dev/top_printers.ml
  doc/changelog/07-commands-and-options/11795-print_implicit_args.rst
  interp/constrextern.ml
  interp/constrextern.mli
  printing/printer.ml
  printing/printer.mli
  printing/proof_diffs.ml
  printing/proof_diffs.mli
  test-suite/output/Arguments.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/PrintInfos.out
  test-suite/output/Search.out
  test-suite/output/SearchHead.out
  test-suite/output/SearchPattern.out
  test-suite/output/SearchRewrite.out
  vernac/prettyp.ml
  vernac/vernacentries.ml
Labels: kind: enhancement, part: implicit arguments, part: vernac

#11860 [ci] [docker] Update to 4.09.1
  .gitlab-ci.yml
  INSTALL.md
  azure-pipelines.yml
  dev/ci/azure-opam.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/dune-workspace.all
  doc/changelog/11-infrastructure-and-dependencies/11860-ci+ocaml_to_4091.rst
Labels: kind: infrastructure

#11760 firstorder: default tactic is “auto with core”
  doc/changelog/04-tactics/11760-firstorder-leaf.rst
  doc/sphinx/proof-engine/tactics.rst
  plugins/firstorder/g_ground.mlg
  test-suite/output/NoAxiomFromR.v
  theories/Classes/CMorphisms.v
  theories/Classes/Morphisms.v
  theories/Classes/Morphisms_Prop.v
  theories/Compat/Coq812.v
  theories/FSets/FMapAVL.v
  theories/FSets/FMapFacts.v
  theories/FSets/FMapPositive.v
  theories/FSets/FSetBridge.v
  theories/FSets/FSetCompat.v
  theories/FSets/FSetEqProperties.v
  theories/FSets/FSetProperties.v
  theories/Lists/List.v
  theories/MSets/MSetPositive.v
  theories/Numbers/Cyclic/Abstract/NZCyclic.v
  theories/Structures/EqualitiesFacts.v
Labels: kind: enhancement, part: standard library, part: tactics

#11745 Remove invisible U+FE00 variation selector from CoqIDE bindings
  ide/default_bindings_src.ml
Labels: kind: fix, part: IDE

#11862 Fix deprecation warning in sphinx and remove workaround for fixed bug
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  doc/README.md
  doc/sphinx/conf.py
  doc/tools/coqrst/coqdomain.py
Labels: kind: fix

#11601 [refman] Move chapters into new structure.
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/miscellaneous-extensions.rst
  doc/sphinx/appendix/history-and-changes/index.rst
  doc/sphinx/appendix/indexes/index.rst
  doc/sphinx/changes.rst
  doc/sphinx/genindex.rst
  doc/sphinx/history.rst
  doc/sphinx/index.html.rst
  doc/sphinx/index.latex.rst
  doc/sphinx/introduction.rst
  doc/sphinx/language/core/index.rst
  doc/sphinx/language/extensions/index.rst
  doc/sphinx/license.rst
  doc/sphinx/proofs/automatic-tactics/index.rst
  doc/sphinx/proofs/creating-tactics/index.rst
  doc/sphinx/proofs/writing-proofs/index.rst
  doc/sphinx/using/libraries/index.rst
  doc/sphinx/using/tools/index.rst
Labels: kind: documentation, kind: redesign

#11857 Remove calls to structural equality in Micromega
  plugins/micromega/coq_micromega.ml
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/vect.ml
Labels: kind: performance, part: micromega

#11778 [ocamformat] Update to 0.13.0
  .gitlab-ci.yml
  .ocamlformat
  Makefile.dune
  dev/ci/docker/bionic_coq/Dockerfile
  dev/doc/changes.md
Labels: kind: infrastructure

#11847 Properly thread let-bindings in Funind principle construction.
  plugins/funind/functional_principles_types.ml
  test-suite/bugs/closed/bug_11846.v
Labels: kind: fix

#11665 Make Cumulative, NonCumulative and Private attributes.
  doc/changelog/07-commands-and-options/11162-local-cs.rst
  doc/changelog/07-commands-and-options/11546-rm-uncheck-template.rst
  doc/changelog/07-commands-and-options/11663-remove-polymorphic-unqualified.rst
  doc/changelog/07-commands-and-options/11665-cumulative-attr.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/changes.rst
  doc/sphinx/conf.py
  doc/sphinx/language/cic.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/funind/glob_term_to_relation.ml
  stm/vernac_classifier.ml
  test-suite/success/attribute_syntax.v
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: documentation, kind: enhancement, part: attributes, part: vernac

#11855 Build and install refman with Dune.
  .gitlab-ci.yml
  Makefile.dune
  coq-doc.opam
  doc/dune
  doc/stdlib/dune
Labels: kind: infrastructure, part: build

#11851 Process command line load vernaculars before command line Goptions
  doc/changelog/08-tools/11851-coqc-flags-fix.rst
  doc/sphinx/practical-tools/coq-commands.rst
  toplevel/ccompile.ml
  toplevel/ccompile.mli
  toplevel/coqtop.ml
  toplevel/usage.ml
Labels: kind: enhancement, part: toplevel

#11731 [proof] Miscellaneous refactorings
  dev/ci/user-overlays/11731-ejgallego-proof+more_naming_unif.sh
  doc/plugin_tutorial/tuto1/src/simple_declare.ml
  plugins/funind/gen_principle.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  stm/stm.ml
  tactics/abstract.ml
  tactics/declare.ml
  tactics/declare.mli
  tactics/pfedit.ml
  tactics/pfedit.mli
  tactics/proof_global.ml
  tactics/proof_global.mli
  vernac/auto_ind_decl.ml
  vernac/classes.ml
  vernac/comAssumption.ml
  vernac/comDefinition.ml
  vernac/comFixpoint.ml
  vernac/comProgramFixpoint.ml
  vernac/declareDef.ml
  vernac/declareDef.mli
  vernac/declareObl.ml
  vernac/declareObl.mli
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/obligations.ml
  vernac/obligations.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#11872 [v8.11] Split documentation of coqdoc in a separate file.
  Makefile.doc
  doc/dune
  doc/sphinx/conf.py
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/using/tools/coqdoc.rst
Labels: kind: internal

#11442 Add module ZifyPow to avoid compatibility issue with 8.11.
  doc/changelog/04-tactics/11362-micromega-fix-11191.rst
  doc/stdlib/hidden-files
  theories/micromega/ZifyPow.v
Labels: kind: compatibility

#11867 Fix the computation of recursive principles with let-bindings.
  pretyping/indrec.ml
Labels: kind: fix

#11888 Fix broken links in prodn:: in doc
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: fix, kind: infrastructure

#9607 [ci] add metacoq
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-equations.sh
  dev/ci/ci-metacoq.sh
Labels: kind: infrastructure

#11892 [refman] Fix caching, which was broken by the addition of coq_config
  doc/sphinx/changes.rst
  doc/sphinx/conf.py
Labels: kind: documentation, kind: fix, kind: infrastructure

#11858 Rename Retypeops -> Relevanceops
  kernel/kernel.mllib
  kernel/reduction.ml
  kernel/relevanceops.ml
  kernel/relevanceops.mli
  kernel/term_typing.ml
  pretyping/retyping.ml
Labels: kind: cleanup

#11826 [proof] Deprecate unused tacmach functions.
  proofs/tacmach.mli
Labels: kind: cleanup

#11772 [obligations] Don't allocate libobjects for obligation info.
  vernac/declareObl.ml
  vernac/declareObl.mli
  vernac/obligations.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#11703 Making of NumTok an API for numeral
  dev/ci/user-overlays/11703-herbelin-master+turning-numTok-into-a-numeral-API.sh
  dev/doc/changes.md
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  interp/constrexpr.ml
  interp/constrexpr_ops.ml
  interp/constrextern.ml
  interp/constrintern.ml
  interp/notation.ml
  interp/notation.mli
  interp/numTok.ml
  interp/numTok.mli
  parsing/cLexer.ml
  parsing/cLexer.mli
  parsing/g_constr.mlg
  parsing/g_prim.mlg
  parsing/pcoq.ml
  parsing/pcoq.mli
  parsing/tok.ml
  parsing/tok.mli
  plugins/ltac/g_tactic.mlg
  plugins/ssr/ssrparser.mlg
  plugins/syntax/float_syntax.ml
  plugins/syntax/g_numeral.mlg
  plugins/syntax/r_syntax.ml
  printing/ppconstr.ml
  test-suite/Makefile
  test-suite/output/NumeralNotations.out
  test-suite/output/NumeralNotations.v
  test-suite/output/RealSyntax.out
  test-suite/output/RealSyntax.v
  test-suite/output/allBytes.out
  test-suite/output/allBytes.v
  vernac/egramcoq.ml
  vernac/metasyntax.ml
Labels: kind: internal

#11875 Fix deploy of refman following #11855.
  .gitlab-ci.yml
  Makefile.dune
Labels: kind: fix, kind: infrastructure

#11785 [proof] consolidation of mutual definition declaration path
  tactics/proof_global.ml
  tactics/proof_global.mli
  vernac/comFixpoint.ml
  vernac/declareDef.ml
  vernac/declareDef.mli
  vernac/declareObl.ml
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#11705 Convert Gallina Extensions chapter to use prodns
  doc/changelog/02-specification-language/11098-master+arguments-supports-anonymous-implicit.rst
  doc/changelog/02-specification-language/11235-non_maximal_implicit.rst
  doc/changelog/02-specification-language/11368-trailing_implicit_error.rst
  doc/sphinx/changes.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/coqrst/coqdomain.py
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#11898 Switch opam file to make
  coq.opam.docker
Labels: kind: infrastructure

#11891 Fix levels of `<=?` and `<?` in the stdlib
  doc/changelog/10-standard-library/11891-fix-order-notations.rst
  test-suite/bugs/closed/bug_11890.v
  theories/Sorting/Mergesort.v
  theories/Structures/Orders.v
Labels: kind: fix, part: notations, part: standard library

#11885 Sorting: Swap the names of Sorted_sort and LocallySorted_sort
  doc/changelog/10-standard-library/1185-sort.rst
  theories/Sorting/Mergesort.v
Labels: kind: fix, part: standard library

#11832 [ocamlformat] Use doc-comments=before style.
  .ocamlformat
  plugins/micromega/certificate.ml
  plugins/micromega/certificate.mli
  plugins/micromega/coq_micromega.ml
  plugins/micromega/coq_micromega.mli
  plugins/micromega/mfourier.ml
  plugins/micromega/mutils.mli
  plugins/micromega/persistent_cache.mli
  plugins/micromega/polynomial.mli
  plugins/micromega/simplex.ml
  plugins/micromega/vect.ml
  plugins/micromega/vect.mli
  plugins/micromega/zify.ml
Labels: kind: internal

#11913 Doc_grammar: Update cmd:: and tacn:: constructs in .rsts
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/tools/docgram/README.md
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/orderedGrammar
  doc/tools/docgram/prodn.edit_mlg
  doc/tools/docgram/productionlist.edit_mlg
Labels: kind: documentation, kind: infrastructure

#11919 Remove outdated mention of -allow-sprop.
  doc/sphinx/language/cic.rst
Labels: kind: documentation, part: SProp

#11918 Fix #11845: anomaly when including partially applied functor
  kernel/modops.ml
  test-suite/bugs/closed/bug_11845.v
Labels: kind: fix

#11920 Shrink refman-prelude files.
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/refman-preamble.rst
  doc/sphinx/refman-preamble.sty
Labels: kind: cleanup, kind: documentation

#11877 Removing deprecated destruct/remember syntax _eqn.
  doc/changelog/04-tactics/11877-master+deprecated-_eqn.rst
  doc/sphinx/language/gallina-specification-language.rst
  plugins/ltac/g_tactic.mlg
Labels: kind: cleanup, part: tactics

#11929 Reintroduce a command that was actually used in another one. Fix build of PDF manual.
  doc/sphinx/refman-preamble.sty
Labels: kind: fix

#11925 [ci] Add bbv
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-bbv.sh
Labels: kind: infrastructure

#11102 Use the Alloc_small macro from the OCaml runtime rather than our own.
  kernel/byterun/coq_gc.h
  kernel/byterun/coq_interp.c
  kernel/byterun/coq_memory.c
Labels: kind: cleanup, part: VM

#11751 Fix #11749: don't warn for hidden files.
  doc/stdlib/make-library-index
Labels: kind: infrastructure, part: build

#11848 Nicer printing for decimal constants
  doc/changelog/03-notations/11848-nicer-decimal-printing.rst
  plugins/syntax/r_syntax.ml
  test-suite/output/QArithSyntax.out
  test-suite/output/RealSyntax.out
  theories/Init/Decimal.v
  theories/QArith/QArith_base.v
Labels: kind: enhancement, part: notations

#11871 Split documentation of coqdoc on separate page.
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/using/tools/coqdoc.rst
  doc/sphinx/using/tools/index.rst
Labels: kind: documentation

#11809 [configure] Remove `-std=c99` from default C flags
  configure.ml
Labels: kind: infrastructure, part: VM

#11950 Document change of behavior of Fail in 8.11.
  doc/sphinx/changes.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#11944 Remove SearchAbout command, deprecated in 8.5
  doc/changelog/07-commands-and-options/11944-rm-searchabout-cmd.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  ide/coq_commands.ml
  ide/microPG.ml
  plugins/ssr/ssrvernac.mlg
  test-suite/bugs/closed/HoTT_coq_010.v
  test-suite/bugs/closed/bug_3900.v
  test-suite/success/search.v
  test-suite/success/searchabout.v
  theories/Init/Prelude.v
  tools/coqdoc/output.ml
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/search.ml
  vernac/search.mli
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup

#11859 Warn when non exactly parsing non floating-point
  doc/changelog/03-notations/11859-warn-inexact-float.rst
  doc/sphinx/language/coq-library.rst
  kernel/float64.ml
  plugins/syntax/float_syntax.ml
  test-suite/output/FloatExtraction.out
  test-suite/output/FloatSyntax.out
  test-suite/output/FloatSyntax.v
Labels: kind: enhancement, part: parser

#11874 Auto-format micromega files in pre-commit hook.
  dev/tools/pre-commit
Labels: kind: infrastructure

#11018 “auto with zarith”: use “lia” rather than “omega”
  doc/changelog/04-tactics/11018-lia-in-auto-with-zarith.rst
  theories/Numbers/Cyclic/Int31/Cyclic31.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/omega/Omega.v
Labels: kind: cleanup, kind: enhancement, part: standard library, part: tactics

#11958 Add -no-update command line option to doc_grammar for Dune
  Makefile.doc
  doc/tools/docgram/README.md
  doc/tools/docgram/doc_grammar.ml
Labels: kind: documentation, kind: infrastructure

#11951 Remove a useless reversed variant in Vars.
  kernel/vars.ml
  kernel/vars.mli
  pretyping/vnorm.ml
Labels: kind: cleanup

#11817 [cleanup] Remove unnecessary Map/Set module creation
  ide/wg_Completion.ml
  lib/system.ml
  library/libnames.ml
  library/libnames.mli
  pretyping/coercionops.ml
  printing/proof_diffs.ml
  printing/proof_diffs.mli
  proofs/goal.ml
  vernac/library.ml
Labels: kind: cleanup

#11921 Remove some cruft from Reductionops API.
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/retyping.ml
  pretyping/unification.ml
  proofs/clenv.ml
Labels: kind: cleanup

#11968 Fix commit hook when there are no changes (eg amend message)
  dev/tools/pre-commit
Labels: kind: fix, kind: infrastructure

#11965 Partial revert of #11817.
  ide/wg_Completion.ml
Labels: kind: fix

#11969 ocamlformat: use whitelist instead of blacklist
  .ocamlformat
  .ocamlformat-ignore
  plugins/micromega/.ocamlformat
  plugins/micromega/.ocamlformat-ignore
Labels: kind: cleanup, kind: infrastructure

#11725 Cleanup stdlib reals.
  doc/changelog/10-standard-library/11725-cleanup-reals.rst
  doc/stdlib/index-list.html.template
  theories/Reals/Abstract/ConstructiveAbs.v
  theories/Reals/Abstract/ConstructiveLUB.v
  theories/Reals/Abstract/ConstructiveLimits.v
  theories/Reals/Abstract/ConstructiveReals.v
  theories/Reals/Abstract/ConstructiveRealsMorphisms.v
  theories/Reals/Abstract/ConstructiveSum.v
  theories/Reals/Cauchy/ConstructiveCauchyAbs.v
  theories/Reals/Cauchy/ConstructiveCauchyReals.v
  theories/Reals/Cauchy/ConstructiveCauchyRealsMult.v
  theories/Reals/Cauchy/ConstructiveRcomplete.v
  theories/Reals/ConstructiveReals.v
  theories/Reals/ConstructiveRealsLUB.v
  theories/Reals/ConstructiveRealsMorphisms.v
  theories/Reals/Raxioms.v
Labels: kind: enhancement, part: standard library

#11647 [rfc] Consolidation of parsing interfaces
  .gitlab-ci.yml
  coqpp/coqpp_main.ml
  gramlib/grammar.ml
  gramlib/grammar.mli
  gramlib/plexing.ml
  gramlib/plexing.mli
  parsing/cLexer.ml
  parsing/cLexer.mli
  parsing/extend.ml
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/ltac/tacentries.ml
  printing/proof_diffs.ml
  toplevel/vernac.ml
  user-contrib/Ltac2/g_ltac2.mlg
  user-contrib/Ltac2/tac2core.ml
  user-contrib/Ltac2/tac2entries.ml
  user-contrib/Ltac2/tac2entries.mli
  vernac/egramcoq.ml
  vernac/egramml.ml
  vernac/egramml.mli
  vernac/pvernac.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
Labels: kind: cleanup, kind: redesign, part: notations, part: parser

#11668 Helping issue #11659 by leaving only the Cast hack in the grammar.
  test-suite/output/PatternsInBinders.out
  vernac/comDefinition.ml
  vernac/g_vernac.mlg
Labels: kind: cleanup

#11131 [ci] [gitlab] Add test-suite test for OCaml 4.10 and 4.11
  .gitlab-ci.yml
  INSTALL.md
  azure-pipelines.yml
  configure.ml
  dev/ci/azure-opam.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/dune-workspace.all
  doc/changelog/11-infrastructure-and-dependencies/11131-ci+back_to_ocaml_410.rst
Labels: kind: infrastructure

#11818 [proof] Further consolidation of the regular declaration path
  dev/ci/user-overlays/11818-ejgallego-proof+remove_special_case_first_declaration_in_mutual.sh
  doc/plugin_tutorial/tuto1/src/simple_declare.ml
  plugins/funind/gen_principle.ml
  pretyping/pretyping.ml
  tactics/proof_global.ml
  tactics/proof_global.mli
  vernac/classes.ml
  vernac/comAssumption.ml
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comProgramFixpoint.ml
  vernac/declareDef.ml
  vernac/declareDef.mli
  vernac/declareObl.ml
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/obligations.ml
  vernac/obligations.mli
  vernac/retrieveObl.ml
  vernac/retrieveObl.mli
  vernac/vernac.mllib
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: internal

#11931 Fix typo in new doc on `Program Mode`
  doc/sphinx/addendum/program.rst
Labels: kind: documentation, kind: fix

#11823 [funind] [cleanup] Remove unused function parameters
  plugins/funind/gen_principle.ml
Labels: kind: cleanup

#11684 Remove spurious anomalies in kernel reduction
  kernel/reduction.ml
  test-suite/success/ConversionOrder.v
Labels: kind: anomaly, kind: fix, part: kernel

#11889 Fix a spelling mistake in the code: s/magicaly/magically/
  pretyping/reductionops.ml
Labels: kind: cleanup, kind: internal

#11915 [proof] Split delayed and regular proof closing functions
  plugins/funind/gen_principle.ml
  stm/stm.ml
  tactics/declare.ml
  tactics/declare.mli
  tactics/pfedit.ml
  tactics/proof_global.ml
  tactics/proof_global.mli
  vernac/lemmas.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: cleanup

#11579 Remove ad-hoc treatment of inductive parameters in implicit arguments
  doc/changelog/02-specification-language/11579-inductive-params.rst
  interp/constrintern.ml
  interp/constrintern.mli
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_auto.mlg
  plugins/ltac/tacinterp.ml
  plugins/ssr/ssrcommon.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  proofs/evar_refiner.ml
  tactics/tactics.ml
  test-suite/bugs/closed/bug_11585.v
  test-suite/bugs/closed/bug_5233.v
  test-suite/output/Inductive.out
  test-suite/success/InductiveVsImplicitsVsTC.v
  user-contrib/Ltac2/tac2core.ml
  user-contrib/Ltac2/tac2tactics.ml
  vernac/classes.ml
  vernac/comAssumption.ml
  vernac/comDefinition.ml
  vernac/comFixpoint.ml
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/comProgramFixpoint.ml
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: fix, part: implicit arguments
