Repository rocq-prover/rocq, pull requests merged in 2020-05, with the labels that each got.

#12222 Less confusing configure message when lablgtk exists but not lablgtksourceview
  configure.ml
Labels: kind: user messages, part: build

#12221 Replace QSeqEquiv by QCauchySeq, simplify proofs.
  test-suite/complexity/ConstructiveCauchyRealsPerformance.v
  theories/Reals/Cauchy/ConstructiveCauchyAbs.v
  theories/Reals/Cauchy/ConstructiveCauchyReals.v
  theories/Reals/Cauchy/ConstructiveCauchyRealsMult.v
  theories/Reals/Cauchy/ConstructiveRcomplete.v
Labels: kind: cleanup, part: standard library

#12172 Refactor first chapter: first step, the section on basics.
  doc/changelog/07-commands-and-options/11665-cumulative-attr.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/appendix/indexes/index.rst
  doc/sphinx/changes.rst
  doc/sphinx/conf.py
  doc/sphinx/coq-attrindex.rst
  doc/sphinx/coq-optindex.rst
  doc/sphinx/language/cic.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/index.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/practical-tools/coqide.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/std-glossindex.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/sphinx/using/libraries/index.rst
  doc/sphinx/using/libraries/writing.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#12197 LtacProf now handles multi-success backtracking
  doc/changelog/05-tactic-language/12197-ltacprof-multi-success.rst
  doc/sphinx/proof-engine/ltac.rst
  plugins/ltac/profile_ltac.ml
  test-suite/bugs/closed/bug_12196.v
  test-suite/bugs/closed/bug_6378.v
  test-suite/success/ltacprof.v
Labels: kind: fix, part: ltac

#12238 [stdlib] [CPermutation] patch for #12031
  theories/Sorting/CPermutation.v
Labels: kind: enhancement, part: standard library

#12231 Simplify division of Cauchy reals
  theories/Reals/Cauchy/ConstructiveCauchyRealsMult.v
Labels: kind: enhancement, part: standard library

#12220 [dune] [doc] Tweaks
  Makefile.dune
Labels: kind: documentation, kind: infrastructure

#12211 When TIMED=1, emit timing info for OCaml files
  Makefile.build
  doc/changelog/08-tools/12211-time-ocaml.rst
  tools/CoqMakefile.in
Labels: kind: enhancement, kind: infrastructure, part: build

#12225 [ci] [doc] More detailed documentation for overlay building
  dev/ci/README-developers.md
Labels: kind: documentation, kind: infrastructure

#12252 [refman] Add missing (only parsing) to example of compat notations.
  doc/sphinx/using/libraries/writing.rst
Labels: kind: documentation

#12227 Spring cleaning of the tactic compatibility layer
  dev/ci/user-overlays/12227-ppedrot-refiner-rm-v82.sh
  plugins/btauto/refl_btauto.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/ssr/ssrbwd.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrelim.mli
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrequality.mli
  plugins/ssr/ssrfwd.ml
  plugins/ssr/ssrfwd.mli
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrtacticals.ml
  plugins/ssr/ssrtacticals.mli
  plugins/ssrmatching/g_ssrmatching.mlg
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
  proofs/clenvtac.ml
  proofs/refiner.ml
  proofs/refiner.mli
  stm/stm.ml
  tactics/equality.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
  test-suite/ssr/simpl_done.v
  test-suite/ssr/try_case.v
Labels: kind: cleanup

#12018 Adding properties about implb in Bool.v
  doc/changelog/10-standard-library/12018-master+implb-characterization.rst
  theories/Bool/Bool.v
Labels: kind: feature, part: standard library

#12008 [stdlib] Add order properties about bool
  doc/changelog/10-standard-library/12008-ollibs-bool.rst
  doc/stdlib/index-list.html.template
  theories/Bool/Bool.v
  theories/Bool/BoolOrder.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/Structures/OrdersEx.v
Labels: kind: feature, part: standard library

#12171 [stdlib] [list] Symmetry in conclusions of map_eq_cons and map_eq_app
  theories/Lists/List.v
  theories/Sorting/CPermutation.v
  theories/Sorting/Permutation.v
Labels: kind: enhancement, part: standard library

#12267 [ci] bump elpi to 1.11
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/12267-gares-elpi-1.11.sh
Labels: kind: infrastructure

#12024 Fixes for LaTeX/html export of standard library in coqdoc
  doc/stdlib/Library.tex
  theories/extraction/ExtrOCamlFloats.v
  tools/coqdoc/cpretty.mll
Labels: kind: fix, part: coqdoc, part: standard library, part: tools

#12262 Fix #12211 (TIMED for ocaml files doesn't print file name)
  Makefile.build
Labels: kind: fix, kind: infrastructure, part: build

#12236 [funind] Remove use of low-level entries in scheme generation.
  plugins/funind/gen_principle.ml
  vernac/auto_ind_decl.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/obligations.ml
  vernac/pfedit.ml
  vernac/proof_global.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, part: funind

#12121 Fixes #11903 and warns about non truly-recursive (co)fixpoints
  doc/changelog/02-specification-language/12121-master+fix11903-warn-non-truly-fixpoint.rst
  doc/changelog/10-standard-library/12121-master+fix11903-warn-non-truly-fixpoint.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  plugins/funind/gen_principle.ml
  test-suite/output/Fixpoint.out
  test-suite/output/Fixpoint.v
  theories/FSets/FMapAVL.v
  theories/Init/Decimal.v
  theories/NArith/BinNatDef.v
  theories/ZArith/BinIntDef.v
  theories/extraction/ExtrOcamlBigIntConv.v
  theories/extraction/ExtrOcamlIntConv.v
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/declare.ml
Labels: kind: fix, kind: user messages

#12068 Coqide completion: tentative fix for #11943
  doc/changelog/09-coqide/12068-master+coqide-completion-no-matched.rst
  ide/wg_Completion.ml
  ide/wg_Completion.mli
  ide/wg_ScriptView.ml
Labels: kind: fix

#12268 Add an example to motivate strictly positive occurrences check
  doc/sphinx/language/cic.rst
Labels: kind: documentation

#12281 [doc] named lemmas can be Saved too
  doc/sphinx/proof-engine/proof-handling.rst
Labels: kind: documentation, kind: fix

#12263 HaskellExtr: Add type annotations to Prelude.==
  doc/changelog/10-standard-library/12263-fix-haskell-extraction.rst
  test-suite/bugs/closed/bug_12257.v
  test-suite/output/Extraction_Haskell_String_12258.out
  test-suite/output/Extraction_Haskell_String_12258.v
  theories/extraction/ExtrHaskellString.v
Labels: kind: fix, part: extraction

#12272 Cleanup formatting in .. coqtop:: directives
  doc/tools/coqrst/coqdoc/main.py
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: infrastructure

#11990 [micromega] use Coqlib.lib_ref to get Coq constants.
  plugins/micromega/coq_micromega.ml
  theories/Init/Datatypes.v
  theories/QArith/QArith_base.v
  theories/Reals/Rregisternames.v
  theories/ZArith/BinInt.v
  theories/micromega/DeclConstant.v
  theories/micromega/EnvRing.v
  theories/micromega/Lra.v
  theories/micromega/QMicromega.v
  theories/micromega/RMicromega.v
  theories/micromega/RingMicromega.v
  theories/micromega/Tauto.v
  theories/micromega/VarMap.v
  theories/micromega/ZMicromega.v
Labels: kind: compatibility, part: micromega

#12122 Avoid registering as keywords the #... in Primitive
  kernel/cPrimitives.ml
  kernel/cPrimitives.mli
  theories/Numbers/Cyclic/Int63/Int63.v
  vernac/g_vernac.mlg
Labels: kind: cleanup

#12040 Document the signing procedure of released binary packages.
  dev/doc/release-process.md
Labels: kind: internal, kind: meta

#12163 Fix #12159 (Numeral Notations do not play well with multiple scopes for the same inductive)
  doc/changelog/03-notations/12163-fix-12159.rst
  interp/constrextern.ml
  interp/notation.ml
  interp/notation.mli
  plugins/ssr/ssrparser.mlg
  test-suite/output/bug_12159.out
  test-suite/output/bug_12159.v
Labels: kind: fix, part: notations

#12237 [stdlib] [List] add results around incl, filter and nth
  doc/changelog/10-standard-library/12237-list-more-filter-incl.rst
  theories/Lists/List.v
Labels: kind: feature, part: standard library

#12204 Ltac helper functions API
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacinterp.mli
Labels: kind: internal

#12241 [declare] Merge DeclareDef into Declare
  doc/plugin_tutorial/tuto1/src/simple_declare.ml
  plugins/funind/gen_principle.ml
  plugins/funind/recdef.ml
  plugins/ltac/g_ltac.mlg
  plugins/ltac/rewrite.ml
  vernac/classes.ml
  vernac/classes.mli
  vernac/comAssumption.ml
  vernac/comAssumption.mli
  vernac/comCoercion.ml
  vernac/comCoercion.mli
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comHints.ml
  vernac/comHints.mli
  vernac/comProgramFixpoint.ml
  vernac/comProgramFixpoint.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/declareDef.ml
  vernac/declareDef.mli
  vernac/declareObl.ml
  vernac/declareObl.mli
  vernac/declareUniv.ml
  vernac/declareUniv.mli
  vernac/g_proofs.mlg
  vernac/indschemes.ml
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/locality.ml
  vernac/locality.mli
  vernac/obligations.ml
  vernac/obligations.mli
  vernac/ppvernac.ml
  vernac/pvernac.mli
  vernac/vernac.mllib
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup, kind: redesign

#12286 [sphinx] Add links to other versions of the refman
  dev/doc/release-process.md
  doc/LICENSE
  doc/sphinx/_templates/versions.html
  doc/sphinx/conf.py
Labels: kind: documentation, kind: infrastructure

#12287 Define CRzero and CRone via CR_of_Q
  theories/Reals/Abstract/ConstructiveAbs.v
  theories/Reals/Abstract/ConstructiveLUB.v
  theories/Reals/Abstract/ConstructiveLimits.v
  theories/Reals/Abstract/ConstructiveReals.v
  theories/Reals/Abstract/ConstructiveRealsMorphisms.v
  theories/Reals/Abstract/ConstructiveSum.v
  theories/Reals/Cauchy/ConstructiveRcomplete.v
Labels: kind: enhancement, part: standard library

#12235 Ensure eintros allows creating evars
  user-contrib/Ltac2/Notations.v
Labels: kind: bug, part: ltac2

#12129 Add a `with_strategy` tactic
  doc/changelog/04-tactics/12129-add-with-strategy.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  interp/stdarg.ml
  interp/stdarg.mli
  kernel/conv_oracle.ml
  kernel/conv_oracle.mli
  parsing/g_prim.mlg
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/ltac/extraargs.mlg
  plugins/ltac/extraargs.mli
  plugins/ltac/extratactics.mlg
  plugins/ltac/pptactic.ml
  plugins/ltac/taccoerce.ml
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacsubst.ml
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/output/print_ltac.out
  test-suite/output/print_ltac.v
  test-suite/success/strategy.v
  test-suite/success/with_strategy.v
  vernac/g_vernac.mlg
Labels: kind: feature, part: tactics

#12294 [errors] Don't raise inside exception printers
  engine/proofview.ml
  proofs/proof.ml
  proofs/proof_bullet.ml
  tactics/pfedit.ml
  vernac/vernacstate.ml
Labels: kind: fix

#12273 Deprecate Refiner API
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/indfun_common.ml
  plugins/funind/recdef.ml
  plugins/ltac/evar_tactics.ml
  plugins/ltac/tacinterp.ml
  plugins/ssr/ssrcommon.ml
  proofs/refiner.mli
  tactics/tacticals.ml
Labels: kind: cleanup, kind: internal

#10609 Register (for Coqlib.ref_lib) several base datatypes of stdlib
  theories/Init/Datatypes.v
Labels: kind: internal, part: standard library

#12254 In non-strict mode, accept any variable as a tactic reference.
  doc/changelog/05-tactic-language/12254-wit-ref-dyn.rst
  plugins/ltac/tacintern.ml
  test-suite/success/tac_wit_ref.v
Labels: kind: fix

#12303 [changelog] Fuse changelogs for #11249 and #12237
  doc/changelog/10-standard-library/11249-ollibs-list-changelog.rst
  doc/changelog/10-standard-library/12237-list-more-filter-incl.rst
Labels: kind: documentation, part: standard library

#12190 [stdlib] [Permutation] Declare more instances as Global
  theories/Sorting/Permutation.v
Labels: kind: enhancement, part: standard library

#12146 Fixes #10812: tactic subst failure with section variables indirectly dependent in goal
  doc/changelog/04-tactics/12146-master+fix10812-subst-failure-section-variables.rst
  doc/sphinx/proof-engine/tactics.rst
  engine/termops.ml
  engine/termops.mli
  tactics/equality.ml
  test-suite/bugs/closed/bug_10812.v
Labels: kind: fix

#12162 Fixing #12161: rename Bool.leb into Bool.le
  doc/changelog/10-standard-library/12008-ollibs-bool.rst
  doc/changelog/10-standard-library/12162-bool-leb.rst
  theories/Bool/Bool.v
  theories/Bool/BoolOrder.v
  theories/Sets/Uniset.v
Labels: kind: enhancement, part: standard library

#12223 Locating error again in atomic tactics (fixes #12152)
  doc/changelog/04-tactics/12223-master+fix12152-locating-error-atomic-level.rst
  plugins/ltac/tacinterp.ml
  test-suite/output/ErrorLocation_12152_1.out
  test-suite/output/ErrorLocation_12152_1.v
  test-suite/output/ErrorLocation_12152_2.out
  test-suite/output/ErrorLocation_12152_2.v
  test-suite/output/ErrorLocation_12255.out
  test-suite/output/ErrorLocation_12255.v
Labels: kind: fix, part: tactics

#11503 Allow to rebind the old value of a mutable Ltac2 entry.
  doc/changelog/05-tactic-language/11503-ltac2-rebind-with-value.rst
  doc/sphinx/proof-engine/ltac2.rst
  test-suite/ltac2/rebind.v
  user-contrib/Ltac2/g_ltac2.mlg
  user-contrib/Ltac2/tac2entries.ml
  user-contrib/Ltac2/tac2expr.mli
  user-contrib/Ltac2/tac2intern.ml
  user-contrib/Ltac2/tac2intern.mli
  user-contrib/Ltac2/tac2interp.ml
Labels: kind: feature, part: ltac2

#12307 Cleaning up the legacy proof engine
  plugins/cc/cctac.ml
  plugins/setoid_ring/newring.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  proofs/clenv.ml
  proofs/clenv.mli
  proofs/clenvtac.ml
  proofs/logic.ml
  proofs/logic.mli
  proofs/refiner.ml
  vernac/himsg.ml
Labels: kind: cleanup

#12309 Remove documentation of -compile, which was removed in #8690.
  doc/sphinx/practical-tools/coq-commands.rst
Labels: kind: documentation, kind: fix

#12310 Tweak the OCaml version used to generate the MacOS package.
  azure-pipelines.yml
Labels: kind: infrastructure

#11828 [obligations] Deprecated flag cleanup
  doc/changelog/07-commands-and-options/11828-obligations+depr_hide_obligation.rst
  doc/sphinx/addendum/program.rst
  test-suite/success/shrink_obligations.v
  vernac/declareObl.ml
Labels: kind: cleanup, needs: rebase, part: program

#12229 Hopefully consensual cleaning of keywords
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/tactics.rst
  parsing/g_constr.mlg
  parsing/g_prim.mlg
  plugins/ltac/g_class.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_tactic.mlg
  vernac/g_proofs.mlg
  vernac/g_vernac.mlg
Labels: kind: cleanup, kind: documentation, kind: enhancement

#12293 Fix timestamp of coqchk manpage
  man/coq-tex.1
  man/coq_makefile.1
  man/coqc.1
  man/coqchk.1
  man/coqdep.1
  man/coqdoc.1
  man/coqide.1
  man/coqtop.1
  man/coqtop.byte.1
  man/coqtop.opt.1
  man/coqwc.1
Labels: kind: cleanup, kind: documentation

#12244 Store the OCaml version used for Coq in vo files.
  checker/check.ml
  checker/values.ml
  lib/system.ml
  lib/system.mli
  vernac/library.ml
Labels: kind: user messages

#12315 Tests for bugs #9583 (fixed by #11613) and #9679.
  test-suite/bugs/closed/bug_9583.v
  test-suite/bugs/closed/bug_9679.v
Labels: kind: fix, part: test-suite

#8808 Extending support for mixing binders and terms in abbreviations
  dev/ci/user-overlays/8808-herbelin-master+support-binder+term-in-abbrev.sh
  doc/changelog/03-notations/8808-master+support-binder+term-in-abbrev.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  interp/constrintern.ml
  interp/syntax_def.ml
  interp/syntax_def.mli
  test-suite/bugs/closed/bug_7903.v
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  vernac/metasyntax.ml
Labels: kind: enhancement, part: notations

#12097 Interleave commandline require/set/unset commands
  doc/changelog/08-tools/11851-coqc-flags-fix.rst
  doc/sphinx/practical-tools/coq-commands.rst
  stm/stm.ml
  stm/stm.mli
  test-suite/output/interleave_options_bad_order.out
  test-suite/output/interleave_options_bad_order.v
  test-suite/output/interleave_options_correct_order.out
  test-suite/output/interleave_options_correct_order.v
  toplevel/ccompile.ml
  toplevel/ccompile.mli
  toplevel/coqargs.ml
  toplevel/coqargs.mli
  toplevel/coqtop.ml
Labels: kind: enhancement

#12214 nit: don't open Persistent_cache in micromega
  plugins/micromega/coq_micromega.ml
Labels: kind: cleanup, part: micromega

#12320 [ci] [sf] Fix SF build.
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-sf.sh
Labels: kind: ci-failure, kind: fix, kind: infrastructure

#12313 Make explicit that UGraph lower bounds are only of two kinds.
  engine/uState.ml
  engine/uState.mli
  engine/univMinim.ml
  engine/univMinim.mli
  engine/univops.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/indTyping.ml
  kernel/uGraph.ml
  kernel/uGraph.mli
  library/global.mli
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: cleanup

#12312 Clarify the documentation for merging PRs with overlays
  CONTRIBUTING.md
Labels: kind: documentation, kind: meta

#11922 No more local reduction functions in Reductionops.
  dev/ci/user-overlays/11922-ppedrot-rm-local-reductionops.sh
  interp/constrintern.ml
  interp/notation.ml
  interp/notation.mli
  plugins/extraction/extraction.ml
  plugins/firstorder/instances.ml
  plugins/firstorder/instances.mli
  plugins/firstorder/sequent.ml
  plugins/firstorder/sequent.mli
  plugins/firstorder/unify.ml
  plugins/firstorder/unify.mli
  plugins/funind/functional_principles_proofs.ml
  plugins/ltac/rewrite.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrequality.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/cases.ml
  pretyping/coercion.ml
  pretyping/coercionops.ml
  pretyping/coercionops.mli
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/indrec.ml
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/retyping.ml
  pretyping/tacred.ml
  pretyping/typeclasses.ml
  pretyping/typing.ml
  pretyping/typing.mli
  pretyping/unification.ml
  proofs/clenv.ml
  proofs/clenvtac.ml
  tactics/eauto.ml
  tactics/eqschemes.ml
  tactics/equality.ml
  tactics/hipattern.ml
  tactics/tactics.ml
  vernac/auto_ind_decl.ml
  vernac/comCoercion.ml
  vernac/comHints.ml
  vernac/metasyntax.ml
Labels: kind: cleanup

#12327 Add a changelog for 8.11.2.
  doc/changelog/01-kernel/11972-fix-require-in-section.rst
  doc/changelog/04-tactics/12116-master+fix12045-missing-reduction-in-using-ind-scheme.rst
  doc/changelog/04-tactics/12223-master+fix12152-locating-error-atomic-level.rst
  doc/changelog/07-commands-and-options/12070-native-compiler-disabled.rst
  doc/changelog/09-coqide/12060-ide-disable-csd.rst
  doc/changelog/09-coqide/12068-master+coqide-completion-no-matched.rst
  doc/changelog/09-coqide/12106-master+coqide-style-apply-all-windows.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#12296 Fixes #12234: wrong environment for Show Proof
  doc/changelog/07-commands-and-options/12296-master+fix12234-show-proof-proper.rst
  test-suite/bugs/closed/bug_12234.v
  vernac/vernacentries.ml
Labels: kind: fix, part: proof engine

#12256 Move the static check of evaluability in unfold tactic to runtime.
  doc/changelog/04-tactics/12256-unfold-dyn-check.rst
  doc/sphinx/proof-engine/tactics.rst
  interp/notation.ml
  interp/notation.mli
  interp/smartlocate.ml
  plugins/ltac/tacintern.ml
  test-suite/bugs/closed/bug_11727.v
  test-suite/bugs/closed/bug_4925.v
  test-suite/bugs/closed/bug_5159.v
  test-suite/bugs/closed/bug_5764.v
  test-suite/success/with_strategy.v
  vernac/prettyp.ml
  vernac/vernacentries.ml
Labels: kind: fix

#12032 [win] Elpi, Coq-Elpi and HB
  dev/build/windows/MakeCoq_master_installer.bat
  dev/build/windows/makecoq_mingw.sh
  dev/ci/gitlab.bat
Labels: kind: feature, kind: infrastructure

#11992 do not re-export ListNotations from Program
  doc/changelog/10-standard-library/11992-no-reexports.rst
  test-suite/bugs/closed/bug_2830.v
  test-suite/bugs/closed/bug_4151.v
  test-suite/success/Record.v
  theories/Program/Syntax.v
Labels: kind: cleanup, part: notations, part: standard library

#12243 Add a note on build-time dependencies to INSTALL.md.
  INSTALL.md
Labels: kind: documentation

#11755 [exn] [tactics] improve backtraces on monadic errors
  clib/exninfo.ml
  clib/exninfo.mli
  doc/changelog/12-misc/11755-exn+tclfail.rst
  engine/proofview.ml
  plugins/ltac/g_class.mlg
  plugins/ltac/rewrite.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tactic_matching.ml
  plugins/omega/coq_omega.ml
  plugins/ssr/ssrview.ml
  proofs/clenvtac.ml
  proofs/proof.ml
  proofs/refine.ml
  tactics/auto.ml
  tactics/autorewrite.ml
  tactics/class_tactics.ml
  tactics/contradiction.ml
  tactics/eauto.ml
  tactics/elim.ml
  tactics/eqdecide.ml
  tactics/equality.ml
  tactics/hints.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
  user-contrib/Ltac2/tac2match.ml
Labels: kind: enhancement, kind: internal

#11979 Add a rudimentary script to generate release changelog.
  dev/tools/generate-release-changelog.sh
Labels: kind: infrastructure

#12323 Fixes #12322: anomaly when printing "fun" binders with implicit types
  doc/changelog/02-specification-language/12323-master+fix12322-anomaly-implicit-binder-factorization.rst
  interp/constrextern.ml
  test-suite/output/ImplicitTypes.out
  test-suite/output/ImplicitTypes.v
Labels: kind: fix, part: printer

#12239 Split Gallina, Gallina ext and most of CIC chapters into multiple pages.
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/language/cic.rst
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/coinductive.rst
  doc/sphinx/language/core/conversion.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/language/core/index.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/language/core/primitive.rst
  doc/sphinx/language/core/sorts.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/language/extensions/arguments-command.rst
  doc/sphinx/language/extensions/canonical.rst
  doc/sphinx/language/extensions/evars.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/language/extensions/index.rst
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/language/module-system.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#11566 [misc] Better preserve backtraces in several modules
  dev/ci/user-overlays/11566-ejgallego-exninfo+coercion.sh
  interp/constrexpr_ops.ml
  interp/constrintern.ml
  interp/modintern.ml
  interp/notation.ml
  interp/smartlocate.ml
  kernel/cbytegen.ml
  lib/cErrors.ml
  lib/cErrors.mli
  library/nametab.ml
  library/nametab.mli
  plugins/extraction/extract_env.ml
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  pretyping/coercion.ml
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  user-contrib/Ltac2/tac2core.ml
  vernac/obligations.ml
  vernac/record.ml
Labels: kind: cleanup, kind: fix, kind: internal

#12335 Clarify release-process.md
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#12277 Checking validity of coqdoc file name (fixes #12265)
  doc/tools/coqrst/coqdoc/main.py
  tools/coqdoc/dune
  tools/coqdoc/main.ml
Labels: kind: fix, part: coqdoc

#12330 Add redirects for HTML pages that were moved.
  doc/sphinx/addendum/canonical-structures.rst
  doc/sphinx/addendum/extended-pattern-matching.rst
  doc/sphinx/language/gallina-extensions.rst
  doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/language/module-system.rst
Labels: kind: documentation, kind: infrastructure

#12071 [ci] [micromega] Fix windows build and Micromega bug introduced in #11756
  azure-pipelines.yml
  dev/ci/azure-build.sh
  plugins/micromega/persistent_cache.ml
Labels: kind: ci-failure, kind: fix, kind: infrastructure, part: micromega, platform: Windows

#12326 Fix #11761: Functional Induction throws unrecoverable error.
  doc/changelog/04-tactics/12326-fix11761-functional-induction-throws-unrecoverable-error.rst
  doc/sphinx/using/libraries/funind.rst
  plugins/funind/g_indfun.mlg
  test-suite/success/Funind.v
Labels: kind: fix, part: funind

#12288 Prove that classical reals implement constructive reals.
  doc/changelog/10-standard-library/12287-zero-of-Q.rst
  doc/changelog/10-standard-library/12288-constructive-experimental.rst
  doc/stdlib/index-list.html.template
  theories/Reals/Abstract/ConstructiveAbs.v
  theories/Reals/Abstract/ConstructiveLUB.v
  theories/Reals/Abstract/ConstructiveLimits.v
  theories/Reals/Abstract/ConstructiveMinMax.v
  theories/Reals/Abstract/ConstructivePower.v
  theories/Reals/Abstract/ConstructiveReals.v
  theories/Reals/Abstract/ConstructiveRealsMorphisms.v
  theories/Reals/Abstract/ConstructiveSum.v
  theories/Reals/Cauchy/ConstructiveCauchyAbs.v
  theories/Reals/Cauchy/ConstructiveCauchyReals.v
  theories/Reals/Cauchy/ConstructiveCauchyRealsMult.v
  theories/Reals/Cauchy/ConstructiveRcomplete.v
  theories/Reals/ClassicalConstructiveReals.v
Labels: kind: cleanup, kind: documentation, kind: feature

#11981 Ltac2: add notations for eval cbv in ... and other in place reductions
  doc/changelog/05-tactic-language/11981-ltac2-eval-notations.rst
  test-suite/ltac2/notations.v
  test-suite/output/ltac2_notations_eval_in.out
  test-suite/output/ltac2_notations_eval_in.v
  user-contrib/Ltac2/Notations.v
Labels: kind: feature, part: ltac2

#12345 test-suite/Makefile: fix incomplete prerequisite list
  test-suite/Makefile
Labels: kind: fix, part: test-suite

#12341 [search] [ssr] Emit deprecated message when calling search from ssreflect
  plugins/ssr/ssrvernac.mlg
  plugins/ssr/ssrvernac.mli
  plugins/ssrsearch/g_search.mlg
  vernac/g_vernac.mlg
Labels: kind: user messages, part: ssreflect

#11980 Improve spacing in Print Assumptions
  printing/printer.ml
  test-suite/output/PrintAssumptions.out
Labels: kind: fix, kind: user messages

#12289 test-suite: fix bug causing unit tests to be skipped
  azure-pipelines.yml
  test-suite/Makefile
  test-suite/unit-tests/ide/lex_tests.ml
  test-suite/unit-tests/printing/proof_diffs_test.ml
Labels: kind: fix, kind: infrastructure

#12301 [declare] Grand unification of the proof save path.
  clib/cSig.mli
  clib/hMap.ml
  dev/ci/user-overlays/10185-SkySkimmer-instance-no-bang.sh
  dev/ci/user-overlays/11703-herbelin-master+turning-numTok-into-a-numeral-API.sh
  dev/ci/user-overlays/11731-ejgallego-proof+more_naming_unif.sh
  dev/ci/user-overlays/11812-ppedrot-export-hint-globality.sh
  dev/ci/user-overlays/11818-ejgallego-proof+remove_special_case_first_declaration_in_mutual.sh
  dev/ci/user-overlays/11820-SkySkimmer-partial-import.sh
  dev/ci/user-overlays/11896-ppedrot-evar-inst-list.sh
  dev/ci/user-overlays/12023-herbelin-master+fixing-empty-Ltac-v-file.sh
  dev/ci/user-overlays/12107-SkySkimmer-no-mod-univs.sh
  dev/ci/user-overlays/12227-ppedrot-refiner-rm-v82.sh
  plugins/derive/derive.ml
  stm/stm.ml
  vernac/classes.ml
  vernac/comDefinition.ml
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/declareObl.ml
  vernac/declareObl.mli
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/locality.ml
  vernac/locality.mli
  vernac/obligations.ml
  vernac/obligations.mli
  vernac/pfedit.ml
  vernac/proof_global.ml
  vernac/vernac.mllib
  vernac/vernacentries.ml
  vernac/vernacinterp.ml
Labels: kind: cleanup, kind: redesign

#12353 Update release-process.md
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#12224 Support :gdef:`text<term>` syntax (adding "<term>")
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  doc/README.md
  doc/changelog/11-infrastructure-and-dependencies/12224-gdef_alias.rst
  doc/sphinx/README.rst
  doc/sphinx/conf.py
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/sorts.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: infrastructure

#12362 Use dev version for opam git pinning in .gitlab-ci.yml.
  .gitlab-ci.yml
Labels: kind: infrastructure

#12342 Direct URL for triggering a pipeline with SKIP_DOCKER=false.
  dev/ci/README-developers.md
Labels: kind: documentation

#12354 [universes] [api] Provide UState.from_env
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  vernac/auto_ind_decl.ml
  vernac/declare.ml
  vernac/obligations.ml
Labels: kind: cleanup, kind: internal

#12356 [declare] Remove unused parameters in prepare_obligation
  vernac/comDefinition.ml
  vernac/declare.ml
  vernac/declare.mli
Labels: kind: cleanup, kind: internal

#12350 [test-suite] Ensure copies of files are writable
  test-suite/.csdp.cache.test-suite
  test-suite/Makefile
  test-suite/coq-makefile/template/init.sh
Labels: kind: fix, part: test-suite

#12359 [ci] Add mit-plv/engine-bench
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-engine_bench.sh
Labels: kind: infrastructure

#12377 Adapt the documentation to the move from Gitter to Zulip.
  .github/SUPPORT.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: kind: documentation

#12316 Use pagination in fetching the number of reviews
  dev/tools/merge-pr.sh
Labels: kind: infrastructure

#12358 [topfmt] Set formatter + flush fix
  doc/changelog/07-commands-and-options/12358-redirect_printing_params.rst
  test-suite/misc/redirect_printing.out
  test-suite/misc/redirect_printing.sh
  test-suite/misc/redirect_printing.v
  vernac/topfmt.ml
Labels: kind: fix, kind: user messages

#12364 [ci] [docker] Bump ocamlformat and dune
  .gitlab-ci.yml
  .ocamlformat
  dev/ci/docker/bionic_coq/Dockerfile
  dev/nixpkgs.nix
Labels: kind: infrastructure, part: build

#12368 Print a newline at the end of timing tables
  doc/changelog/08-tools/12368-fix-missing-newline-time-file-maker.rst
  test-suite/coq-makefile/timing/after/time-of-build-both.log.desired
  test-suite/coq-makefile/timing/per-file-after/A.v.timing.diff.desired
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/002-single-file-sorting/time-of-build-pretty-real.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/002-single-file-sorting/time-of-build-pretty-user.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/time-of-build-pretty.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/004-per-file-fuzz/foo-real.v.timing.diff.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/004-per-file-fuzz/foo-user.v.timing.diff.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user.log.expected
  tools/TimeFileMaker.py
Labels: kind: fix, kind: infrastructure, part: tools

#12371 [obligations] Minor refactoring
  vernac/declare.ml
  vernac/declare.mli
  vernac/obligations.ml
Labels: kind: cleanup, part: program

#12355 [8.12] Use pinned commits in dev/ci/ci-user-overlays.sh.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#12295 Fixes #12233: printing environment corrupted with eta-expansion of "match" branches
  doc/changelog/07-commands-and-options/12295-master+fix12234-show-proof.rst
  plugins/ssrmatching/ssrmatching.ml
  pretyping/detyping.ml
  test-suite/bugs/closed/bug_12233.v
Labels: kind: fix, part: printer

#12076 [coqchk] Fix #5030 (coqchk reports names from opaque modules as axioms)
  checker/check.ml
  checker/check.mli
  checker/check_stat.ml
  checker/check_stat.mli
  checker/checker.ml
  checker/mod_checking.ml
  checker/mod_checking.mli
  checker/safe_checking.ml
  checker/safe_checking.mli
  doc/changelog/08-tools/12076-fix-5030.rst
  test-suite/Makefile
  test-suite/output-coqchk/bug_5030.out
  test-suite/output-coqchk/bug_5030.v
Labels: kind: fix, part: checker

#12363 [8.12] Tweak the OCaml version used to generate the MacOS package.
  azure-pipelines.yml
Labels: kind: infrastructure

#12379 Omit voluminous Latex warnings
  Makefile.doc
Labels: kind: documentation, kind: infrastructure

#12392 [backport-pr] Select correct remote of the master branch.
  dev/tools/backport-pr.sh
  dev/tools/generate-release-changelog.sh
  dev/tools/merge-pr.sh
Labels: kind: infrastructure, kind: meta

#12403 Fix hyperlinks in changes.rst
  doc/sphinx/changes.rst
Labels: kind: documentation, kind: fix

#12344 Cleanup noisy prefixes
  engine/uState.ml
  kernel/section.ml
Labels: kind: cleanup, kind: internal

#12366 Delay evaluating arguments of the "exists" tactic
  doc/changelog/04-tactics/12366-fix-exists.rst
  plugins/ltac/coretactics.mlg
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/bugs/closed/bug_12365.v
Labels: kind: fix

#12388 Fix an uncaught python exception in timing
  doc/changelog/11-infrastructure-and-dependencies/12388-fix-timing-diff-0s.rst
  test-suite/coq-makefile/timing/precomputed-time-tests/006-zero-before/run.sh
  test-suite/coq-makefile/timing/precomputed-time-tests/006-zero-before/time-of-build-after.log.in
  test-suite/coq-makefile/timing/precomputed-time-tests/006-zero-before/time-of-build-before.log.in
  test-suite/coq-makefile/timing/precomputed-time-tests/006-zero-before/time-of-build-both.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/run.sh
  tools/TimeFileMaker.py
Labels: kind: fix, kind: infrastructure

#12410 dev/tools/make-changelog.sh now asks about fixed bugs
  dev/tools/make-changelog.sh
  doc/changelog/08-tools/12410-add-fixes.rst
Labels: kind: enhancement, kind: infrastructure

#12408 Fix output tests for location errors when running in async mode.
  test-suite/output/ErrorLocation_12152_1.v
  test-suite/output/ErrorLocation_12152_2.v
  test-suite/output/ErrorLocation_12255.v
Labels: kind: fix, part: test-suite

#12389 Small coq_makefile improvement.
  doc/changelog/08-tools/12389-coq_makefile.rst
  doc/sphinx/practical-tools/utilities.rst
  tools/CoqMakefile.in
Labels: kind: enhancement

#12399 Remove the prolog tactic.
  doc/changelog/04-tactics/12399-rm-prolog.rst
  plugins/ltac/g_auto.mlg
  tactics/eauto.ml
  tactics/eauto.mli
Labels: kind: cleanup

#12421 Fixes for compilation without native dynlink
  plugins/ssrsearch/g_search.mlg
  user-contrib/Ltac2/g_ltac2.mlg
  vernac/mltop.ml
Labels: kind: fix, part: toplevel
