Repository rocq-prover/rocq, pull requests merged in 2020-06, with the labels that each got.

#12431 [ci] Split fiat-crypto into non-OCaml and OCaml
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-fiat_crypto.sh
  dev/ci/ci-fiat_crypto_ocaml.sh
Labels: kind: fix, kind: infrastructure

#12422 Fixes #12418: an assert false in inference of return clause
  doc/changelog/02-specification-language/12422-master+fix-12418-cases-anomaly.rst
  pretyping/cases.ml
  test-suite/bugs/closed/bug_12418.v
Labels: kind: fix, part: elaboration

#11974 Require in Section: warning is now about fragility not deprecation.
  doc/changelog/07-commands-and-options/11972-fix-require-in-section.rst
  vernac/vernacentries.ml
Labels: kind: user messages

#12412 Reduce options passed to workers
  stm/asyncTaskQueue.ml
  toplevel/usage.ml
Labels: kind: fix, part: STM

#12427 Add a dependency of coq_makefile's coqdep target into _CoqProject
  tools/CoqMakefile.in
Labels: kind: enhancement, part: tools

#12419 Various cleanups in eauto
  tactics/eauto.ml
Labels: kind: cleanup

#12440 [declare] Hide internals of variable declaration entries.
  vernac/comAssumption.ml
  vernac/declare.ml
  vernac/declare.mli
Labels: kind: cleanup, kind: internal

#11707 Split the Reductionops machine from the cbn one
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  pretyping/evarconv.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/unification.ml
  tactics/cbn.ml
  tactics/cbn.mli
  tactics/redexpr.ml
  tactics/tactics.mllib
Labels: kind: cleanup

#12456 Fix version switcher when building with Dune.
  doc/sphinx/conf.py
  doc/sphinx/dune
Labels: kind: fix, part: build

#12397 Fix #12280: do not use xindy to avoid build failures on some machines.
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  doc/README.md
  doc/sphinx/conf.py
Labels: kind: documentation, kind: infrastructure

#12437 Fix ONLY_WINDOWS in .gitlab-ci.yml.
  .gitlab-ci.yml
Labels: kind: infrastructure

#12459 Document incompatibility with Sphinx 3.
  doc/README.md
  doc/sphinx/changes.rst
Labels: kind: documentation

#12460 Add remaining 8.12+beta1 changelog entries.
  doc/changelog/02-specification-language/12422-master+fix-12418-cases-anomaly.rst
  doc/changelog/07-commands-and-options/11972-fix-require-in-section.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#12450 Document known issue of Proof <term> with PG.
  doc/sphinx/proof-engine/proof-handling.rst
Labels: kind: documentation

#12336 Factorize code in hint declaration.
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#12380 Fix #12361 (indexing issues in the PDF)
  doc/sphinx/changes.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation

#12473 Match only a single line as the coqtop prompt in coqtop:: directive
  doc/tools/coqrst/repl/coqtop.py
Labels: kind: documentation, kind: fix, kind: infrastructure

#12451 Fix Flocq build on Windows.
  dev/build/windows/makecoq_mingw.sh
Labels: kind: fix, kind: infrastructure

#12471 Fix uncaught NotArity in inductive type
  test-suite/bugs/closed/bug_12390.v
  vernac/comInductive.ml
Labels: kind: fix

#12480 Don't suggest Proof using when no section variables
  test-suite/output/SuggestProofUsing.out
  test-suite/output/SuggestProofUsing.v
  vernac/declare.ml
Labels: kind: fix, kind: user messages

#12482 [ci] [overlays] Pin unicoq to a stable version.
  dev/ci/ci-basic-overlay.sh
Labels: kind: ci-failure, kind: infrastructure

#12462 Summary of changes for 8.12
  doc/sphinx/changes.rst
Labels: kind: documentation

#12103 Convert Ltac chapter to prodn
  Makefile.doc
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/language/extensions/arguments-command.rst
  doc/sphinx/language/extensions/canonical.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/proof-handling.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/coqrst/coqdomain.py
  doc/tools/docgram/README.md
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#12186 CReal: changed epsilon for modulus of convergence from 1/n to 1/2^n
  doc/changelog/10-standard-library/12186-creal-new-modulus.rst
  doc/stdlib/hidden-files
  test-suite/complexity/ConstructiveCauchyRealsPerformance.v
  test-suite/output/MExtraction.v
  theories/Reals/Cauchy/ConstructiveCauchyAbs.v
  theories/Reals/Cauchy/ConstructiveCauchyReals.v
  theories/Reals/Cauchy/ConstructiveCauchyRealsMult.v
  theories/Reals/Cauchy/ConstructiveExtra.v
  theories/Reals/Cauchy/ConstructiveRcomplete.v
  theories/Reals/Cauchy/PosExtra.v
  theories/Reals/Cauchy/QExtra.v
  theories/Reals/ClassicalConstructiveReals.v
  theories/Reals/ClassicalDedekindReals.v
  theories/Reals/Raxioms.v
  theories/Reals/Rdefinitions.v
Labels: kind: enhancement, part: standard library

#12484 Fix #12483 Incorrect specification of PrimFloat.leb
  dev/doc/critical-bugs
  doc/changelog/10-standard-library/12484-fix12483.rst
  test-suite/bugs/closed/bug_12483.v
  theories/Floats/SpecFloat.v
Labels: kind: fix, kind: inconsistency

#12423 Remove info tactic, deprecated in 8.5
  doc/changelog/04-tactics/12423-rm-info.rst
  plugins/ltac/g_ltac.mlg
  plugins/ltac/pptactic.ml
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacsubst.ml
  test-suite/modules/PO.v
  test-suite/output/auto.v
Labels: kind: cleanup

#12443 Fix #12442: Confusing error message when the intro pattern of "apply in" fails
  tactics/tactics.ml
  test-suite/output/bug12442.out
  test-suite/output/bug12442.v
Labels: kind: fix

#12492 Fix Windows addons.
  dev/build/windows/makecoq_mingw.sh
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#12481 Minor improvements to the sections on basics and sorts.
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/sorts.rst
Labels: kind: documentation

#12498 [dune] [dbg] Fix coqide target after CoqIDE move.
  dev/dune
  dev/dune-dbg.in
Labels: kind: fix, part: build

#12415 [v8.12] Carefully select which versions of add-ons are included in the Windows installer.
  dev/build/windows/makecoq_mingw.sh
  dev/build/windows/patches_coq/VST.patch
  dev/build/windows/patches_coq/gappa_plugin-gappalib-coq-1.4.3.patch
  dev/ci/ci-basic-overlay.sh
  dev/ci/gitlab.bat
Labels: kind: infrastructure

#12500 Bump version number to 8.12+beta1.
  configure.ml
Labels: kind: infrastructure

#12357 [declare] Remove some unused `fix_exn`
  lib/future.ml
  lib/future.mli
  stm/stm.ml
  test-suite/interactive/ParalITP_fail_on_qed.v
  vernac/declare.ml
  vernac/declare.mli
Labels: kind: cleanup, kind: internal, part: STM

#12501 Coq-Elpi patch to remove memory-intensive test.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#12494 [dev/ci/nix] Support for building the Gappa plugin.
  dev/ci/nix/default.nix
  dev/ci/nix/gappa.nix
Labels: kind: infrastructure

#11906 [micromega] native support for boolean operators
  doc/changelog/04-tactics/11906-micromega-booleans.rst
  doc/sphinx/addendum/micromega.rst
  plugins/micromega/coq_micromega.ml
  plugins/micromega/g_zify.mlg
  plugins/micromega/micromega.ml
  plugins/micromega/micromega.mli
  plugins/micromega/zify.ml
  plugins/micromega/zify.mli
  test-suite/micromega/zify.v
  theories/Bool/Bool.v
  theories/Init/Datatypes.v
  theories/ZArith/BinInt.v
  theories/micromega/Lia.v
  theories/micromega/QMicromega.v
  theories/micromega/RMicromega.v
  theories/micromega/Tauto.v
  theories/micromega/ZMicromega.v
  theories/micromega/ZifyBool.v
  theories/micromega/ZifyClasses.v
  theories/micromega/ZifyComparison.v
  theories/micromega/ZifyInst.v
Labels: kind: enhancement, part: micromega

#12509 updated ci for unicoq
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-unicoq.sh
Labels: kind: infrastructure

#12506 [toplevel] Annotate tailcall functions
  toplevel/coqloop.ml
  toplevel/vernac.ml
  vernac/vernacinterp.ml
Labels: kind: internal

#12508 Fix #12507 Anomaly when using a ssreflect `reflect` view
  plugins/ssr/ssrequality.ml
  test-suite/ssr/rewrtite_err_msg.v
Labels: kind: user messages

#12511 [v8.12] Bump Gappa plugin to use latest release and remove the compatibility patch
  dev/build/windows/patches_coq/gappa_plugin-gappalib-coq-1.4.3.patch
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#12536 tactics.rst: fix typo — readd `cbv` to title of its section
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#12535 [v8.12] Bump interval
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#12533 [CI] Update paramcoq branch to v8.12
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#12502 Preserve sharing in evar instances
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evarutil.ml
  engine/evarutil.mli
  engine/univSubst.ml
  kernel/environ.mli
  pretyping/globEnv.ml
Labels: kind: performance

#12531 Fast inductive compilation
  kernel/cbytegen.ml
  vernac/comInductive.ml
Labels: kind: fix, kind: performance

#12407 Fix #12406: fix Coq type error in dependent induction's Ltac
  theories/Program/Equality.v
Labels: kind: fix, part: standard library

#12559 Add index for coqdoc.
  doc/sphinx/using/tools/coqdoc.rst
Labels: kind: documentation

#12505 Cleanup the Hints API
  dev/ci/user-overlays/12505-ppedrot-factor-hint-flags.sh
  plugins/firstorder/sequent.ml
  tactics/auto.ml
  tactics/auto.mli
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#12546 [ci] Use a tested branch of Perennial
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#12555 Add test-suite/redirect_test.out file to .gitignore
  .gitignore
Labels: kind: internal

#12434 Slight improvement in naming dependent existential variables in goals
  engine/evd.ml
  test-suite/output-coqtop/DependentEvars.out
  test-suite/output-coqtop/DependentEvars2.out
  test-suite/output/unification.out
  test-suite/output/unification.v
Labels: kind: enhancement, kind: user messages, part: tactics

#12520 Cleanup the autorewrite implementation
  tactics/autorewrite.ml
  tactics/autorewrite.mli
Labels: kind: cleanup

#8796 Elementary properties about IZR for generic use
  theories/Reals/RIneq.v
Labels: kind: feature, part: standard library

#12552 Add a pre-hook mechanism for the `zify` tactic
  doc/changelog/04-tactics/12552-zify-pre-hook.rst
  doc/sphinx/addendum/micromega.rst
  test-suite/micromega/zify.v
  theories/micromega/Zify.v
Labels: kind: enhancement, part: micromega

#12530 Fix glob_sort_family for SProp
  pretyping/glob_ops.ml
  test-suite/bugs/closed/bug_12529.v
Labels: kind: fix, part: SProp, part: elaboration

#12562 CoqIDE: accept to open files with invalid names
  doc/changelog/09-coqide/12562-coqide-lax-filename.rst
  ide/coqide/coqide.ml
Labels: kind: fix, part: IDE

#12577 [ci] Add coq-community/coq-performance-tests
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-coq_performance_tests.sh
Labels: kind: infrastructure

#12550 Fix configure usage in .opam
  coq.opam
Labels: kind: fix

#12517 Fix #4459 by improving `par:` error message
  stm/stm.ml
Labels: kind: user messages

#12580 Remove the catchable-exception related functions.
  proofs/logic.ml
  proofs/logic.mli
  tactics/class_tactics.ml
  tactics/class_tactics.mli
Labels: kind: cleanup

#12579 Simplify Clenv API
  dev/base_include
  plugins/ltac/leminv.ml
  proofs/clenv.ml
  proofs/clenv.mli
  proofs/clenvtac.ml
  proofs/clenvtac.mli
  proofs/proofs.mllib
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/equality.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
Labels: kind: cleanup, kind: internal

#12554 Add back fiat-crypto-legacy to the CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-fiat_crypto_legacy.sh
Labels: kind: infrastructure

#12544 [v8.12] Bump Equation to 1.2.2 and UniCoq to 1.4.
  dev/build/windows/makecoq_mingw.sh
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-unicoq.sh
Labels: kind: infrastructure

#12598 Mention VSCoq with respect to _CoqProject
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#12583 [test-suite] Fix dependencies of modules/ files
  doc/changelog/11-infrastructure-and-dependencies/12583-fix-remake.rst
  test-suite/Makefile
Labels: kind: fix, part: test-suite

#12518 [ci] [ocaml] Track OCaml 4.12
  .gitlab-ci.yml
Labels: kind: infrastructure

#12372 [declare] Refactor constant information into a record.
  dev/base_include
  dev/ci/user-overlays/12372-ejgallego-proof+info.sh
  doc/plugin_tutorial/tuto1/src/g_tuto1.mlg
  doc/plugin_tutorial/tuto1/src/simple_declare.ml
  ide/coqide/idetop.ml
  plugins/derive/derive.ml
  plugins/derive/derive.mli
  plugins/extraction/extract_env.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/gen_principle.mli
  plugins/funind/recdef.ml
  plugins/funind/recdef.mli
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_obligations.mlg
  plugins/ltac/rewrite.ml
  plugins/ltac/rewrite.mli
  proofs/proof.ml
  stm/proofBlockDelimiter.ml
  stm/stm.ml
  stm/vernac_classifier.ml
  user-contrib/Ltac2/tac2entries.ml
  vernac/classes.ml
  vernac/classes.mli
  vernac/comAssumption.ml
  vernac/comAssumption.mli
  vernac/comCoercion.ml
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comHints.ml
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/comProgramFixpoint.ml
  vernac/comProgramFixpoint.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/declareDef.ml
  vernac/g_proofs.mlg
  vernac/lemmas.ml
  vernac/lemmas.mli
  vernac/obligations.ml
  vernac/obligations.mli
  vernac/pfedit.ml
  vernac/proof_global.ml
  vernac/recLemmas.ml
  vernac/recLemmas.mli
  vernac/vernac.mllib
  vernac/vernacentries.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
  vernac/vernacinterp.ml
  vernac/vernacinterp.mli
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: cleanup, kind: internal

#12604 Update CAMLDONTLINK in CoqMakefile.in
  tools/CoqMakefile.in
Labels: kind: fix, kind: infrastructure

#12541 Fix #12228 negative integers not accepted in ltac integer_list
  doc/changelog/05-tactic-language/12541-fix12228.rst
  tactics/redexpr.ml
  test-suite/bugs/closed/bug_12228.v
Labels: kind: fix, part: ltac

#12570 CoqIDE: fix lexing of UTF-8 in quotations like constr:()
  ide/coqide/coq_lex.mll
Labels: kind: fix

#11977 Generate default names for bound universes of polymorphic definitions
  engine/uState.ml
  engine/univNames.ml
  engine/univNames.mli
  printing/printer.ml
  printing/printer.mli
  printing/printmod.ml
  test-suite/output/UnivBinders.out
  vernac/himsg.ml
  vernac/prettyp.ml
Labels: kind: user messages, part: universes

#12599 Remove the Refiner module
  dev/base_include
  dev/ci/user-overlays/12599-ppedrot-rm-deprecated-refiner.sh
  dev/top_printers.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/ltac/rewrite.ml
  plugins/ltac/tacinterp.ml
  plugins/setoid_ring/newring.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  printing/printer.ml
  printing/proof_diffs.ml
  proofs/proofs.mllib
  proofs/refiner.ml
  proofs/refiner.mli
  proofs/tacmach.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/equality.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
  vernac/declare.ml
  vernac/himsg.ml
Labels: kind: cleanup, kind: internal

#12596 Credit Erik Martin-Dorel for work on Docker.
  doc/sphinx/changes.rst
Labels: kind: documentation
