Repository rocq-prover/rocq, pull requests merged in 2021-12, with the labels that each got.

#15273 Replace "Reset Initial" with "coqtop:: reset" in doc
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: fix, kind: documentation

#13460 Extraction: preventing possible conflicts with OCaml's primitive type names
  doc/changelog/08-tools/13460-master+fix-ocaml-int-extraction-clash.rst
  test-suite/bugs/closed/bug_7017.v
  test-suite/output/Search.out
  test-suite/output/SearchPattern.out
  test-suite/output/Search_headconcl.out
  theories/Init/Decimal.v
  theories/Init/Hexadecimal.v
  theories/Init/Number.v
Labels: kind: fix, part: extraction

#15276 Small clean up of the Proofview.V82 module
  engine/proofview.ml
  engine/proofview.mli
  proofs/proof.ml
Labels: kind: cleanup

#15272 Deprecate Universal Lemma Under Conjunction flag.
  doc/changelog/07-vernac-commands-and-options/15272-deprecate-universal-lemma-under-conj.rst
  doc/sphinx/proof-engine/tactics.rst
  tactics/tactics.ml
Labels: kind: cleanup

#15261 Remove most of the Goal module.
  dev/top_printers.ml
  ide/coqide/idetop.ml
  printing/printer.ml
  printing/proof_diffs.ml
  proofs/goal.ml
  proofs/goal.mli
  proofs/logic.ml
  proofs/proof.ml
  proofs/proof.mli
  stm/partac.ml
  stm/stm.ml
Labels: kind: cleanup

#15277 Deprecate the argument-free instantiate tactic
  doc/changelog/04-tactics/15277-deprecate-instantiate-tactic.rst
  doc/sphinx/proof-engine/tactics.rst
  engine/proofview.ml
  engine/proofview.mli
  plugins/ltac/extratactics.mlg
Labels: kind: cleanup

#15284 Clean up the ssr implementation
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrview.ml
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
Labels: kind: cleanup

#15285 generate-release-changelog.sh: order entries automatically
  dev/doc/release-process.md
  dev/tools/generate-release-changelog.sh
Labels: kind: infrastructure

#15250 Set the level of the Ltac2 "now" notation to 6.
  doc/changelog/05-tactic-language/15250-ltac2-fix-now-precedence.rst
  test-suite/bugs/closed/bug_15122.v
  user-contrib/Ltac2/Notations.v
Labels: kind: fix, part: ltac2

#15269 Move text from tactics.rst to proof-mode.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
Labels: kind: documentation

#15275 More correct "unsupported attributes" for ltac2 commands
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  vernac/attributes.ml
  vernac/attributes.mli
Labels: kind: fix

#15267 Move text from tactics.rst to ltac.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
Labels: kind: documentation

#15245 Fixes #15244: wrong choice of final name for specialize with an introduction pattern
  doc/changelog/04-tactics/15245-master+fix15244-specialize-wrong-final-name-ipat.rst
  tactics/tactics.ml
  test-suite/bugs/closed/bug_15244.v
Labels: kind: fix, part: tactics

#15268 Remove `Universal Lemma Under Conjunction` flag (deprecated in 8.15).
  doc/changelog/07-vernac-commands-and-options/15268-test-remove-univ-lemma-under-conj.rst
  doc/sphinx/proof-engine/tactics.rst
  tactics/tactics.ml
  test-suite/success/apply.v
Labels: kind: cleanup

#15098 [extraction] extend bigint extraction with division and more comparisons
  doc/changelog/10-standard-library/15098-extract-bigint.rst
  test-suite/success/extraction_bigint.v
  theories/extraction/ExtrOcamlZBigInt.v
Labels: part: extraction, kind: enhancement

#15278 Use evar map when calling vm_conv from outside the kernel.
  kernel/nativeconv.ml
  kernel/vconv.ml
  kernel/vconv.mli
  pretyping/pretyping.ml
  pretyping/vnorm.ml
Labels: kind: fix

#15288 Clean up some Proofview / Proof V82 API.
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  printing/printer.ml
  printing/printer.mli
  proofs/proof.ml
  proofs/proof.mli
  test-suite/bugs/closed/bug_15288.v
  vernac/declare.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, part: proof engine

#15271 Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix

#15289 Respect hint priority in typeclasses eauto with multiple dbs
  doc/changelog/04-tactics/15289-hnt-pri.rst
  tactics/class_tactics.ml
  test-suite/bugs/closed/bug_5304.v
Labels: kind: fix

#15306 Remove doubled periods in changes
  doc/sphinx/changes.rst
Labels: kind: documentation

#15307 When "change" is applied to terms of incompatible types, tell which they are
  tactics/tactics.ml
  test-suite/output/Errors.out
  test-suite/output/Errors.v
Labels: kind: user messages, part: tactics, kind: enhancement

#15302 Small pretyping/ cleanups
  plugins/ltac2/tac2tactics.ml
  pretyping/cases.ml
  pretyping/nativenorm.ml
  pretyping/nativenorm.mli
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/tacred.ml
  pretyping/tacred.mli
  pretyping/unification.ml
  pretyping/unification.mli
  pretyping/vnorm.ml
  tactics/equality.ml
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#15312 Remove unused Map.Unsafe.map API
  clib/cMap.ml
  clib/cMap.mli
  clib/hMap.ml
Labels: kind: cleanup

#15319 Fix CODEOWNERS after move of Ltac2 OCaml code.
  .github/CODEOWNERS
Labels: kind: fix, kind: meta

#15314 Deprecate the bfs eauto tactic.
  doc/sphinx/changes.rst
  plugins/ltac/g_auto.mlg
  plugins/ltac2/tac2tactics.ml
Labels: kind: fix

#15321 docs: Add new shields.io badge for `coqorg/coq:latest`
  README.md
Labels: kind: documentation

#15293 Drop backtrace when raising Exit
  checker/check.ml
  checker/checker.ml
  checker/votour.ml
  clib/cArray.ml
  clib/option.ml
  engine/termops.ml
  ide/coqide/ideutils.ml
  interp/constrextern.ml
  interp/notation_ops.ml
  plugins/micromega/polynomial.ml
  pretyping/detyping.ml
  pretyping/evarsolve.ml
  tactics/equality.ml
  tactics/tactics.ml
  topbin/coqnative_bin.ml
  vernac/egramcoq.ml
  vernac/loadpath.ml
  vernac/metasyntax.ml
Labels: kind: performance

#15301 Ensure that errors are located in the current command.
  test-suite/output/Arguments.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/BadOptionValueType.out
  test-suite/output/Cases.out
  test-suite/output/ErrorInCanonicalStructures.out
  test-suite/output/ErrorLocation_tac_in_term.out
  test-suite/output/ErrorLocation_tac_in_term.v
  test-suite/output/Errors.out
  test-suite/output/HintLocality.out
  test-suite/output/Inductive.out
  test-suite/output/InvalidDisjunctiveIntro.out
  test-suite/output/Load.out
  test-suite/output/Notations.out
  test-suite/output/NumberNotations.out
  test-suite/output/Partac.out
  test-suite/output/ProofUsingClashWarning.out
  test-suite/output/RecordMissingField.out
  test-suite/output/SchemeNames.out
  test-suite/output/Search.out
  test-suite/output/UnivBinders.out
  test-suite/output/bug5778.out
  test-suite/output/bug6404.out
  test-suite/output/bug_12887.out
  test-suite/output/bug_13320.out
  test-suite/output/bug_13942.out
  test-suite/output/bug_15097.out
  test-suite/output/bug_15106.out
  test-suite/output/bug_8206.out
  test-suite/output/ltac.out
  test-suite/output/ltac_extra_args.out
  test-suite/output/ltac_missing_args.out
  test-suite/output/undeclared_key.out
  vernac/vernacinterp.ml
  vernac/vernacinterp.mli
Labels: kind: fix

#15323 Also mention the deprecation of bfs eauto in the doc.
  doc/sphinx/proofs/automatic-tactics/auto.rst
Labels: kind: documentation

#15329 Fix test suite after parallel merge of #15301 and #15307
  test-suite/output/Errors.out
Labels: kind: fix, part: test-suite

#15308 Remove the legacy qualifier for ARGUMENT EXTEND
  coqpp/coqpp_main.ml
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  proofs/tacmach.mli
Labels: kind: cleanup

#15304 Merge gather_dependent_evars with gather_dependent_evars_terms in Evarutil
  engine/evarutil.ml
  engine/evarutil.mli
  printing/printer.ml
Labels: kind: cleanup

#15311 Correctly remove defined evars from the future goal state.
  engine/evd.ml
Labels: kind: fix, kind: performance

#15327 Provide an explicit primitive to raise non-zero Ltac failures.
  dev/ci/user-overlays/15327-ppedrot-split-tclfail-level.sh
  plugins/btauto/refl_btauto.ml
  plugins/cc/cctac.ml
  plugins/firstorder/ground.ml
  plugins/firstorder/instances.ml
  plugins/firstorder/rules.ml
  plugins/funind/indfun_common.ml
  plugins/funind/invfun.ml
  plugins/funind/recdef.ml
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_class.mlg
  plugins/ltac/internals.ml
  plugins/ltac/rewrite.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tauto.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/zify.ml
  plugins/ring/ring.ml
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/equality.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
Labels: kind: cleanup

#15305 Deprecate the Proofview.V82 module
  engine/ftactic.ml
  engine/proofview.ml
  engine/proofview.mli
  plugins/ltac2/tac2core.ml
  proofs/refine.ml
  proofs/tacmach.ml
  proofs/tacmach.mli
  tactics/autorewrite.ml
  tactics/eauto.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
Labels: kind: cleanup

#15328 refactor: micro optimize Hashset.repr
  clib/hashset.ml
Labels: kind: performance

#15351 Clean up the Proof_diffs API
  ide/coqide/idetop.ml
  printing/printer.ml
  printing/printer.mli
  printing/proof_diffs.ml
  printing/proof_diffs.mli
Labels: kind: cleanup

#15353 refactor: remove mysterious identity map
  plugins/ltac/rewrite.ml
Labels: kind: cleanup

#15324 Remove the bfs implementation from eauto
  dev/ci/user-overlays/15324-ppedrot-rm-eauto-bfs-implem.sh
  doc/sphinx/changes.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  lib/explore.ml
  lib/explore.mli
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/recdef.ml
  plugins/ltac/g_auto.mlg
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ltac2/tac2tactics.mli
  plugins/rtauto/refl_tauto.ml
  tactics/eauto.ml
  tactics/eauto.mli
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
Labels: kind: cleanup

#15294 Remove custom extraction of comparison to int in ExtrOCamlInt63
  dev/ci/user-overlays/15294-Lysxia-extract-comparison.sh
  doc/changelog/10-standard-library/15294-extract-comparison.rst
  theories/extraction/ExtrOCamlInt63.v
Labels: kind: fix, part: extraction

#15317 Libobject/Lib name handling refactor
  checker/values.ml
  dev/ci/ci-quickchick.sh
  dev/ci/user-overlays/15317-SkySkimmer-libobject-names.sh
  dev/top_printers.ml
  doc/plugin_tutorial/tuto2/src/persistent_counter.ml
  doc/sphinx/proof-engine/vernacular-commands.rst
  interp/impargs.ml
  interp/implicit_quantifiers.ml
  interp/notation.ml
  interp/syntax_def.ml
  library/coqlib.ml
  library/goptions.ml
  library/lib.ml
  library/lib.mli
  library/libobject.ml
  library/libobject.mli
  library/nametab.mli
  plugins/extraction/table.ml
  plugins/funind/indfun_common.ml
  plugins/ltac/extratactics.mlg
  plugins/ltac/tacentries.ml
  plugins/ltac/tacenv.ml
  plugins/ltac/tactic_option.ml
  plugins/ltac2/tac2entries.ml
  plugins/micromega/zify.ml
  plugins/ring/ring.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrview.ml
  pretyping/arguments_renaming.ml
  pretyping/keys.ml
  pretyping/reductionops.ml
  tactics/autorewrite.ml
  tactics/declareScheme.ml
  tactics/hints.ml
  tactics/redexpr.ml
  test-suite/unit-tests/printing/proof_diffs_test.ml
  vernac/canonical.ml
  vernac/classes.ml
  vernac/comArguments.ml
  vernac/comCoercion.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/declareUniv.ml
  vernac/declaremods.ml
  vernac/declaremods.mli
  vernac/library.ml
  vernac/metasyntax.ml
  vernac/mltop.ml
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/record.ml
  vernac/search.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#15343 Fixing regression in reporting incompatible notations
  parsing/extend.ml
  parsing/extend.mli
  test-suite/bugs/closed/bug_13966.v
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  vernac/metasyntax.ml
Labels: part: notations, kind: regression

#15346 Updating the list of keywords to avoid in extraction to Haskell and OCaml
  plugins/extraction/haskell.ml
  plugins/extraction/ocaml.ml
Labels: part: extraction, kind: enhancement

#15350 Do not unconditionally record backtraces in CoqIDE.
  ide/coqide/coqOps.ml
  ide/coqide/coqide.ml
Labels: kind: fix, part: IDE

#15354 Fuse sort and unique
  interp/impargs.ml
Labels: kind: cleanup

#15342 Renaming ETProdReference/TTReference -> ETProdGlobal/TTGlobal for uniformity
  parsing/extend.ml
  parsing/extend.mli
  vernac/egramcoq.ml
  vernac/metasyntax.ml
Labels: kind: cleanup

#15361 add a test for #9633 after fixed by #14562
  test-suite/bugs/closed/bug_9633.v
Labels: kind: infrastructure

#15340 Fixes #15335: let entry coercions in notations and custom ident/global notations respect "only parsing"
  doc/changelog/03-notations/15340-master+fix15335-entry-coercions-respect-only-parsing.rst
  interp/notation.ml
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  vernac/metasyntax.ml
Labels: kind: fix, part: notations, kind: enhancement, part: custom

#15369 Fix test suite after parallel merge of #15340 and #15343
  test-suite/output/Notations4.out
Labels: kind: fix

#15363 refactor: remove pointless array allocation
  plugins/ltac/rewrite.ml
Labels: kind: cleanup

#15332 refactor: use raise_notrace in AcyclicGraph
  lib/acyclicGraph.ml
Labels: kind: performance

#15357 Deprecate Goal.goal alias of Evar.t
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  plugins/ssr/ssrast.mli
  printing/printer.mli
  printing/proof_diffs.ml
  proofs/proof.mli
  proofs/tacmach.mli
  stm/partac.ml
  stm/proofBlockDelimiter.ml
  stm/proofBlockDelimiter.mli
  stm/stm.ml
  stm/stm.mli
  tactics/tacticals.mli
Labels: kind: cleanup

#15371 Move bug_9633 to correct directory
  test-suite/bugs/bug_9633.v
Labels: kind: infrastructure

#15338 Fixes #15334: anomaly on parsing error due to empty entry (8.14 regression)
  doc/changelog/03-notations/15338-master+fix15334-parsing-failure-on-empty-grammar.rst
  gramlib/grammar.ml
  test-suite/output/bug_15334.out
  test-suite/output/bug_15334.v
Labels: kind: fix, part: parser

#15365 Fixes evar normalization bug in unification observed in test file for #3209
  pretyping/evarsolve.ml
Labels: kind: fix, part: unification

#15374 Print all goals in debugger (quick fix)
  ide/coqide/idetop.ml
  plugins/ltac/tactic_debug.ml
  toplevel/coqtop.ml
Labels: kind: fix, part: debugger

#15243 8.14: warn deprecated locality on Instance even when interactive
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/changes.rst
  test-suite/bugs/closed/bug_14704.v
  vernac/classes.ml
Labels: kind: fix, kind: user messages, Coq Consortium support services

#15379 Deprecate "dfs eauto" tactic
  doc/sphinx/proofs/automatic-tactics/auto.rst
  plugins/ltac/g_auto.mlg
Labels: kind: cleanup

#15387 Contributing guide: fix grammar mistake (less -> fewer).
  CONTRIBUTING.md
Labels: kind: fix, kind: documentation

#15355 Ensure at grammar level that module application is always to a qualid.
  doc/changelog/07-vernac-commands-and-options/15355-mod-apply-ident.rst
  doc/sphinx/language/core/modules.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  interp/constrexpr.ml
  interp/modintern.ml
  kernel/modops.ml
  kernel/modops.mli
  test-suite/bugs/bug_11133.v
  vernac/g_vernac.mlg
  vernac/himsg.ml
  vernac/ppvernac.ml
Labels: kind: cleanup, part: modules

#15372 Clean the Printer API
  ide/coqide/idetop.ml
  printing/printer.ml
  printing/printer.mli
  printing/proof_diffs.ml
  printing/proof_diffs.mli
  toplevel/coqloop.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, part: printer, part: diffs

#15265 Mention existence of various undocumented tactics
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/nsatz.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/automatic-tactics/logic.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/sphinx/using/libraries/funind.rst
Labels: kind: documentation

#15291 Wish #7911: support for recursively using "x .. y" in recursive notations
  doc/changelog/03-notations/15291-master+wish-recursive-patterns-in-argument-of-recursive-notations.rst
  interp/constrintern.ml
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: part: notations, kind: enhancement

#15388 Replace P_Rmin with Rmin_case (fixes #15382)
  doc/changelog/10-standard-library/15388-rmincase.rst
  theories/Reals/Rpower.v
Labels: kind: cleanup, part: standard library

#15377 rewrite.ml: pass full "cstr" to transitivity
  plugins/ltac/rewrite.ml
  test-suite/bugs/bug_10923.v
Labels: kind: fix

#15380 contrintern binder_block_names: don't store unused id set
  interp/constrintern.ml
Labels: kind: cleanup

#15389 Adding a "smart" version of List.fold_left_map and List.fold_right_map
  clib/cList.ml
  clib/cList.mli
  kernel/constr.ml
  kernel/environ.ml
Labels: kind: cleanup

#13861 [cmdline] use / in -print-mod-uid as dir separator on windows
  toplevel/coqtop.ml
Labels: kind: fix

#15136 Fix "make test-suite" with legacy build
  Makefile.common
  test-suite/Makefile
Labels: kind: fix, part: test-suite

#15385 Fixes #9555: expansion of self in functorial module types wrongly extend over the type of parameters, impacting the correctness of the algebraic form of the type of parameters
  doc/changelog/01-kernel/15385-master+fix-bug9555-subst-module-type-wrongly-over-functor.rst
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/modops.mli
  test-suite/output/bug_9555.out
  test-suite/output/bug_9555.v
Labels: kind: fix, part: modules, part: kernel, part: printer

#15393 Deprecate the Evd.sigma wrapper
  dev/ci/user-overlays/15393-ppedrot-deprecate-sigma-wrapper.sh
  dev/top_printers.ml
  dev/top_printers.mli
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  plugins/firstorder/ground.ml
  plugins/funind/indfun_common.ml
  plugins/funind/recdef.ml
  plugins/ssr/ssrast.mli
  plugins/ssr/ssripats.ml
  printing/printer.ml
  printing/printer.mli
  proofs/proof.ml
  proofs/proof.mli
  proofs/tacmach.ml
  proofs/tacmach.mli
  tactics/tacticals.mli
Labels: kind: cleanup

#15396 Remove Termops.global_vars API
  engine/termops.ml
  engine/termops.mli
  plugins/ltac/leminv.ml
Labels: kind: cleanup

#15401 Use anonymous primitive projections in the VM.
  dev/vm_printers.ml
  kernel/byterun/coq_interp.c
  kernel/genOpcodeFiles.ml
  kernel/vconv.ml
  kernel/vmemitcodes.ml
  kernel/vmemitcodes.mli
  kernel/vmsymtable.ml
  kernel/vmvalues.ml
  kernel/vmvalues.mli
  pretyping/vnorm.ml
  test-suite/vm_norm_records.v
Labels: kind: cleanup, kind: performance, part: VM

#15383 A pass on error messages related to the "with" clause of module types
  doc/sphinx/language/core/modules.rst
  interp/modintern.ml
  interp/modintern.mli
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/modops.mli
  plugins/extraction/extract_env.ml
  test-suite/output/ErrorModuleWith.out
  test-suite/output/ErrorModuleWith.v
  test-suite/output/bug_8206.out
  test-suite/output/qualification.out
  vernac/himsg.ml
Labels: kind: cleanup, kind: user messages, part: modules
