Repository rocq-prover/rocq, pull requests merged in 2021-06, with the labels that each got.

#14408 Zify for Sint63
  doc/changelog/04-tactics/14408-ZifySint63.rst
  doc/sphinx/addendum/micromega.rst
  doc/stdlib/hidden-files
  test-suite/micromega/int63.v
  test-suite/micromega/sint63.v
  theories/micromega/ZifySint63.v
Labels: kind: feature, part: micromega, part: primitive types

#14377 Fixes #13966: broken invariant when overriding notation with different applicability to "match" patterns
  doc/changelog/03-notations/14377-master+fix13966-broken-invariant-notation-overriden-different-pattern-applicability.rst
  interp/notation.ml
  test-suite/bugs/closed/bug_13966.v
Labels: kind: fix, part: notations

#14376 Print ANTLR version warning only once.
  doc/tools/coqrst/notations/parsing.py
Labels: kind: documentation, kind: infrastructure

#14415 Rename inductive.rst
  doc/sphinx/proofs/writing-proofs/index.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/sphinx/user-extensions/proof-schemes.rst
  doc/tools/docgram/doc_grammar.ml
Labels: kind: documentation

#14421 Kernel sort comparison: fully delegate to ugraph
  kernel/reduction.ml
  test-suite/bugs/closed/bug_14420.v
Labels: kind: fix

#14418 Cleanup old overlay files
  dev/ci/user-overlays/09710-ppedrot-compact-case-repr.sh
  dev/ci/user-overlays/13202-SkySkimmer-debug-infra.sh
  dev/ci/user-overlays/13299-jashug-preserve-universes-notation.sh
  dev/ci/user-overlays/13321-ppedrot-mv-evaluable-global-ref-out-of-kernel.sh
  dev/ci/user-overlays/13512-herbelin-master+fix13413-apply-on-intro-pattern-fresh-names.sh
  dev/ci/user-overlays/13537-ppedrot-lazy-subst-kernel.sh
  dev/ci/user-overlays/13617-ejgallego-make+use_dune_for_ocaml.sh
  dev/ci/user-overlays/13725-SkySkimmer-hint-rw-local.sh
  dev/ci/user-overlays/13842-proux01-remove-decimal.sh
  dev/ci/user-overlays/13844-gares-command-loc.sh
  dev/ci/user-overlays/13847-gares-elpi-1.13-coq-elpi-1.9.0.sh
  dev/ci/user-overlays/13852-Lysxia-no-collision-projection.sh
  dev/ci/user-overlays/13885-ejgallego-ocaml+4.12.sh
  dev/ci/user-overlays/13911-Zimmi48-remove_type_cast.sh
  dev/ci/user-overlays/13912-pi8027-remove-bijint.sh
  dev/ci/user-overlays/13958-gares-recordops-api.sh
  dev/ci/user-overlays/14050-SkySkimmer-no-remote-counter-alt.sh
  dev/ci/user-overlays/14075-herbelin-master+new-level-abstraction-streams-with-location.sh
  dev/ci/user-overlays/14099-LasseBlaauwbroek-fix-destruct-type.sh
  dev/ci/user-overlays/14111-gares-update-elpi.sh
  dev/ci/user-overlays/14148-ppedrot-export-instance-take-two.sh
  dev/ci/user-overlays/14224-jfehrle-ltac_loc_info.sh
  dev/ci/user-overlays/14247-SkySkimmer-usubst-clean.sh
  dev/ci/user-overlays/14295-gares-export-ind-parsing-rules.sh
  dev/ci/user-overlays/14337-ppedrot-eager-constr-mod-subst.sh
  dev/ci/user-overlays/14357-gares-update-elpi-1.10.sh
Labels: kind: cleanup, kind: infrastructure

#14430 Stop replacing file names by "stdin" in output tests
  test-suite/Makefile
  test-suite/output/Arguments_renaming.out
  test-suite/output/Cases.out
  test-suite/output/DebugFlags.out
  test-suite/output/Deprecation.out
  test-suite/output/ErrorInCanonicalStructures.out
  test-suite/output/ErrorInCanonicalStructures2.out
  test-suite/output/ErrorInModule.out
  test-suite/output/ErrorInSection.out
  test-suite/output/ErrorLocation_12152_1.out
  test-suite/output/ErrorLocation_12152_2.out
  test-suite/output/ErrorLocation_12255.out
  test-suite/output/ErrorLocation_12774_1.out
  test-suite/output/ErrorLocation_12774_2.out
  test-suite/output/ErrorLocation_12774_3.out
  test-suite/output/ErrorLocation_13241_1.out
  test-suite/output/ErrorLocation_13241_2.out
  test-suite/output/ErrorLocation_ltac_1.out
  test-suite/output/ErrorLocation_ltac_2.out
  test-suite/output/ErrorLocation_ltac_3.out
  test-suite/output/ErrorLocation_ltac_4.out
  test-suite/output/ErrorLocation_tac_in_term_1.out
  test-suite/output/ErrorLocation_tac_in_term_2.out
  test-suite/output/Error_msg_diffs.out
  test-suite/output/Fixpoint.out
  test-suite/output/FloatExtraction.out
  test-suite/output/FloatSyntax.out
  test-suite/output/Naming.out
  test-suite/output/Notations4.out
  test-suite/output/NumberNotations.out
  test-suite/output/UnboundRef.out
  test-suite/output/Warnings.out
  test-suite/output/bug_12908.out
  test-suite/output/bug_8206.out
  test-suite/output/ltac2_deprecated.out
  test-suite/output/notation_principal_scope.out
  test-suite/output/qualification.out
  test-suite/output/relaxed_ambiguous_paths.out
  test-suite/output/ssr_error_multiple_intro_after_case.out
  test-suite/output/ssr_explain_match.out
  test-suite/output/undeclared_key.out
Labels: kind: cleanup, part: test-suite

#14431 test-suite: don't use $(wildcard) in approve-output
  test-suite/Makefile
Labels: kind: fix, part: test-suite

#14414 make: orderedGrammar is .PRECIOUS
  Makefile.doc
Labels: kind: fix, kind: infrastructure, part: build

#14433 [build] Install coqdoc.sty in global share prefix.
  tools/coqdoc/dune
Labels: kind: fix, kind: infrastructure, part: installation

#14293 Moved lemmas from Reals/Cauchy/QExtra.v to a proper place in QArith
  doc/changelog/10-standard-library/14293-qarith_cleanup.rst
  test-suite/complexity/ConstructiveCauchyRealsPerformance.v
  theories/QArith/QArith_base.v
  theories/QArith/Qabs.v
  theories/QArith/Qpower.v
  theories/QArith/Qround.v
  theories/Reals/Cauchy/ConstructiveCauchyAbs.v
  theories/Reals/Cauchy/ConstructiveCauchyReals.v
  theories/Reals/Cauchy/ConstructiveCauchyRealsMult.v
  theories/Reals/Cauchy/ConstructiveRcomplete.v
  theories/Reals/Cauchy/QExtra.v
  theories/Reals/ClassicalDedekindReals.v
Labels: kind: cleanup, kind: feature, part: standard library

#14416 Fast bound saturation in Micromega
  plugins/micromega/certificate.ml
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  plugins/micromega/vect.ml
  plugins/micromega/vect.mli
Labels: kind: performance

#14437 Remove Interval from the continuous integration.
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-interval.sh
Labels: kind: ci-failure

#14432 Make a lookup of the canonical structure table faster
  pretyping/structures.ml
  pretyping/structures.mli
Labels: kind: performance, part: elaboration

#14403 Fix make-changelog when the branch names contains a /
  dev/tools/make-changelog.sh
Labels: kind: fix, kind: infrastructure

#14343 Do not close Z_scope in ZArith
  dev/ci/user-overlays/14343-RalfJung-Z_scope.sh
  doc/changelog/10-standard-library/14343-Z_scope.rst
  test-suite/bugs/closed/bug_13307.v
  theories/ZArith/Zeven.v
Labels: kind: fix, part: standard library

#14442 Extraction: Support for locating errors mentioning a reference, and locating them
  plugins/extraction/table.ml
  plugins/extraction/table.mli
Labels: kind: enhancement, part: extraction

#14345 [Extraction] [Haskell] Add support for GHC >= 9
  doc/changelog/10-standard-library/14345-new-haskell.rst
  plugins/extraction/haskell.ml
  test-suite/output/Extraction_Haskell_String_12258.out
Labels: kind: fix, part: extraction

#14451 Bench: don't render results for package "coq"
  dev/bench/bench.sh
Labels: kind: infrastructure

#14384 [primitive ints] Add Sint63.abs
  doc/changelog/10-standard-library/14384-Sint63_additions.rst
  doc/sphinx/language/core/primitive.rst
  test-suite/micromega/sint63.v
  theories/Numbers/Cyclic/Int63/Sint63.v
  theories/micromega/ZifySint63.v
Labels: kind: enhancement, part: primitive types, priority: nice to have

#14398 Update doc after changes to PrimInt63 and Sint63
  checker/values.ml
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  interp/notation.ml
Labels: kind: cleanup, kind: documentation

#14457 Show a warning instead of an anomaly for Diff_Failure exception
  doc/changelog/04-tactics/14457-proof_diffs_anomaly.rst
  ide/coqide/idetop.ml
  lib/pp_diff.ml
  printing/printer.ml
  printing/proof_diffs.ml
  printing/proof_diffs.mli
  vernac/himsg.ml
Labels: kind: anomaly, kind: fix

#14434 [build] Install Coqide FAQ
  Makefile.ide
  ide/coqide/dune
Labels: kind: infrastructure

#13663 More robust display of goal names in graphical user interfaces.
  ide/coqide/idetop.ml
  ide/coqide/protocol/interface.ml
  ide/coqide/protocol/xmlprotocol.ml
  ide/coqide/wg_ProofView.ml
Labels: kind: fix

#14406 Lemmas about list cutting & map
  doc/changelog/10-standard-library/14406-master.rst
  theories/Lists/List.v
Labels: kind: feature, part: standard library

#13398 Adding an "elaboration"/interpretation function for named_context
  interp/constrintern.ml
  interp/constrintern.mli
Labels: kind: cleanup, part: elaboration

#14459 Do not retype the argument of Equality.instantiate_lemma.
  tactics/equality.ml
Labels: kind: cleanup, kind: performance

#14428 Clean up scheme computation in the induction tactic
  tactics/equality.ml
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#14449 Remove and clean up redundant rewriting API in Equality.
  dev/ci/user-overlays/14449-ppedrot-clean-equality-generic-rewrite-api.sh
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/recdef.ml
  plugins/ltac/extratactics.mlg
  plugins/ssr/ssrcommon.ml
  tactics/autorewrite.ml
  tactics/equality.ml
  tactics/equality.mli
  vernac/auto_ind_decl.ml
Labels: kind: cleanup

#14450 Use the new refiner for Tactics.descend_in_conjunctions.
  tactics/tactics.ml
Labels: kind: cleanup

#14461 Move require-in-module warning from deprecated to fragile
  vernac/library.ml
Labels: kind: user messages

#14464 Improved coqbot documentation in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind: documentation

#14466 Makefile.dune install target does not succeed
  Makefile.dune
Labels: kind: fix, part: build

#14460 Prepare for 8.15.
  doc/stdlib/index-list.html.template
  sysinit/coqargs.ml
  test-suite/success/CompatCurrentFlag.v
  test-suite/success/CompatOldFlag.v
  test-suite/success/CompatOldOldFlag.v
  test-suite/success/CompatPreviousFlag.v
  theories/Compat/Coq814.v
  theories/Compat/Coq815.v
  tools/configure/configure.ml
Labels: kind: cleanup, kind: compatibility, kind: infrastructure

#14439 Do not rely on the template status to decide keeping proof equalities.
  doc/changelog/05-tactic-language/14439-keep-proof-equality-table.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  library/goptions.ml
  library/goptions.mli
  pretyping/retyping.ml
  pretyping/retyping.mli
  tactics/equality.ml
  tactics/equality.mli
  vernac/declareInd.ml
Labels: kind: cleanup, kind: redesign

#14474 [native] Improve error message for ocaml compiler stack overflow
  kernel/nativelib.ml
Labels: kind: user messages, part: native compiler

#14473 [coqnative] Exit with non zero code on error
  topbin/coqnative_bin.ml
Labels: kind: fix, part: native compiler

#14463 [parser] Remove deprecated gram_universe API
  parsing/pcoq.ml
  parsing/pcoq.mli
  vernac/pvernac.ml
  vernac/pvernac.mli
Labels: kind: cleanup

#14429 Minor parsing/lexing refactorings
  gramlib/grammar.ml
  gramlib/grammar.mli
  parsing/cLexer.ml
  parsing/tok.ml
  parsing/tok.mli
Labels: kind: cleanup, part: parser

#14417 Move cooking types to Declarations from Opaqueproof
  checker/mod_checking.mli
  dev/ci/user-overlays/14417-SkySkimmer-cooking-info-decls.sh
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/declarations.ml
  kernel/declareops.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/nativecode.mli
  kernel/opaqueproof.ml
  kernel/opaqueproof.mli
  kernel/safe_typing.ml
  kernel/section.ml
  kernel/section.mli
  kernel/subtyping.ml
  kernel/term_typing.mli
  library/global.mli
  library/lib.ml
  library/lib.mli
  plugins/extraction/extraction.mli
  plugins/extraction/table.ml
  plugins/extraction/table.mli
  vernac/classes.ml
  vernac/library.mli
Labels: kind: cleanup

#14444 Fixing #14443: shift by 1 in locating start of parsing error messages
  gramlib/grammar.ml
Labels: kind: fix, part: parser

#14470 Ignore COQ_USE_DUNE when installing through opam
  Makefile
Labels: kind: fix, part: build

#14484 Small reorder in zulip bench bot message
  dev/bench/bench.sh
Labels: kind: infrastructure

#14458 List: make split_combine usable
  doc/changelog/10-standard-library/14458-split_combine.rst
  theories/Lists/List.v
Labels: kind: enhancement, part: standard library

#14452 CoqIDE Unicode: parentheses: use math, not CJK
  doc/changelog/09-coqide/14452-btj+patch-1.rst
  ide/coqide/default_bindings_src.ml
Labels: kind: enhancement, part: IDE

#14071 Gramlib: improved support for multi-token LIST0/LIST1 separators and related minor changes
  coqpp/coqpp_main.ml
  gramlib/grammar.ml
  gramlib/grammar.mli
  parsing/extend.ml
  parsing/extend.mli
  parsing/notation_gram.ml
  plugins/ltac/tacentries.ml
  test-suite/success/Notations2.v
  user-contrib/Ltac2/tac2core.ml
  vernac/egramcoq.ml
  vernac/metasyntax.ml
  vernac/vernacextend.ml
Labels: kind: cleanup, kind: enhancement, part: parser

#13037 [impargs] use clos_whd_all (by need, rather than by name)
  interp/impargs.ml
  test-suite/complexity/impargs.v
Labels: kind: performance

#14489 [ci] Improve ci-metacoq script
  dev/ci/ci-metacoq.sh
Labels: kind: fix, kind: infrastructure

#14436 [build] Fix docgram deps in dune-make bridge
  Makefile.common
Labels: kind: fix, kind: infrastructure

#14483 Algorithmically more efficient substitution in application retyping.
  pretyping/retyping.ml
Labels: kind: performance

#14479 Envars.print_config always uses Coq_config.all_src_dirs
  lib/envars.ml
  lib/envars.mli
  sysinit/coqinit.ml
  tools/coq_makefile.ml
Labels: kind: cleanup

#14493 Fixes the kernel name comparison used when deactivating notations
  doc/changelog/03-notations/14493-master+fix14486-part-wrong-eq-kn-notation.rst
  interp/constrextern.ml
  test-suite/output/bug_12777.out
  test-suite/output/bug_12777.v
Labels: kind: fix, part: notations

#13102 Locating identifiers in a few plugin commands
  interp/stdarg.ml
  interp/stdarg.mli
  parsing/pcoq.ml
  plugins/derive/g_derive.mlg
  plugins/extraction/extract_env.ml
  plugins/extraction/extract_env.mli
  plugins/extraction/g_extraction.mlg
  plugins/extraction/table.ml
  plugins/extraction/table.mli
  plugins/funind/g_indfun.mlg
  plugins/ltac/g_obligations.mlg
  plugins/ltac/g_rewrite.mlg
  plugins/ring/g_ring.mlg
  plugins/syntax/g_number_string.mlg
Labels: kind: cleanup, part: parser

#14487 Add test for possible bug encountered in #14480
  test-suite/success/StuckHintMode.v
Labels: kind: internal, part: test-suite

#14504 Fix fullGrammar and common.edit_mlg following #13102.
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
Labels: kind: fix, kind: internal

#14508 Use the official version of Gappa for continuous integration.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#14478 Substitute universes in types of proof-mode mutual fixpoints.
  test-suite/bugs/closed/bug_14057.v
  vernac/declare.ml
Labels: kind: fix

#14491 Refresh type in Tacred.abstract_scheme
  pretyping/tacred.ml
  test-suite/bugs/closed/bug_14300.v
Labels: kind: fix

#14517 [coqnative] Accept -native-output-dir
  topbin/coqnative_bin.ml
Labels: kind: infrastructure, part: native compiler, priority: blocker

#14495 Fast Typing for application rule
  engine/eConstr.ml
  engine/eConstr.mli
  kernel/vars.ml
  kernel/vars.mli
  pretyping/typing.ml
Labels: kind: performance

#14518 [build] [compat] Declare coq.kernel as a compat library for 8.14
  kernel/dune
Labels: kind: compatibility, kind: infrastructure

#14079 Treat set predicativity and sprop-allowed more like normal typing flags
  checker/check_stat.ml
  checker/checker.ml
  checker/include
  checker/values.ml
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  library/global.ml
  library/global.mli
  printing/printer.ml
  sysinit/coqargs.ml
  sysinit/coqargs.mli
  sysinit/coqinit.ml
  topbin/coqnative_bin.ml
Labels: kind: cleanup

#14390 Cleanup evar map handling around coq_unit_judge
  pretyping/cases.ml
  pretyping/evarconv.ml
  pretyping/evarconv.mli
  test-suite/bugs/closed/bug_9240.v
  theories/Init/Datatypes.v
Labels: kind: cleanup

#14523 Amending #13663 for backwards compatibility with vscoq (goal name in XML protocol)
  ide/coqide/protocol/interface.ml
  ide/coqide/protocol/xmlprotocol.ml
Labels: kind: fix

#14526 Explain how to fix locality warnings
  tactics/autorewrite.ml
  tactics/hints.ml
  vernac/classes.ml
Labels: kind: fix, kind: user messages

#14533 Legacy build: use $(HIDE) for large coqdoc invocation
  Makefile.doc
Labels: kind: fix, kind: infrastructure, part: build

#14499 Test suite fixes when run with autoconfigured Coq
  test-suite/coq-makefile/native1/run.sh
  test-suite/coq-makefile/native2/run.sh
  test-suite/coq-makefile/native3/run.sh
  test-suite/coq-makefile/native4/run.sh
  test-suite/coq-makefile/template/theories/test.v
  test-suite/misc/changelog.sh
  test-suite/misc/non-marshalable-state/.gitignore
  tools/coq_makefile.ml
Labels: kind: cleanup, kind: fix, part: test-suite

#14509 Fail if program mode candargs cannot be unified
  pretyping/pretyping.ml
Labels: kind: cleanup

#14534 Tweak the DebugFlag test.
  test-suite/output/DebugFlags.out
  test-suite/output/DebugFlags.v
Labels: kind: internal

#14538 [coqnative] Support -boot option
  topbin/coqnative_bin.ml
Labels: kind: fix, kind: infrastructure, part: build, part: native compiler, part: tools, priority: blocker

#14511 ci: fix pinning script
  dev/tools/pin-ci.sh
Labels: kind: fix

#14253 Store the closedness of a term on its leave in unification matchrec.
  pretyping/unification.ml
  test-suite/success/rewrite_closed.v
Labels: kind: performance

#14528 Deprecate the new auto tactic.
  doc/sphinx/changes.rst
  plugins/ltac/g_auto.mlg
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
Labels: kind: cleanup

#14179 Convert "Reasoning with inductive types" chapter to prodn.
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/parallel-proof-processing.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/changes.rst
  doc/sphinx/history.rst
  doc/sphinx/language/cic.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/coinductive.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/language/extensions/evars.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/practical-tools/coqide.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/sphinx/using/libraries/funind.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#14532 Grammar engine does not locate itself the errors produced by right-hand side of grammar rules
  gramlib/grammar.ml
  plugins/ltac/g_tactic.mlg
  vernac/g_vernac.mlg
Labels: kind: fix, part: parser

#14549 Slightly saner definition of Unification.subst_defined_metas_evars.
  pretyping/unification.ml
Labels: kind: cleanup

#14527 Remove the new auto tactic.
  doc/changelog/04-tactics/14527-rm-new-auto.rst
  plugins/ltac/g_auto.mlg
  tactics/auto.ml
  tactics/auto.mli
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
  user-contrib/Ltac2/tac2stdlib.ml
  user-contrib/Ltac2/tac2tactics.ml
  user-contrib/Ltac2/tac2tactics.mli
Labels: kind: cleanup, part: tactics

#14545 [build] Fix coqtop shim in byte mode.
  dev/shim/dune
Labels: kind: fix, kind: infrastructure

#14544 [build] Fix typo in Makefile following the renaming of stub lib
  Makefile.build
Labels: kind: fix, kind: infrastructure

#14566 Minor phrasing fixes
  doc/sphinx/changes.rst
Labels: kind: documentation, kind: fix

#14559 dune: Add default alias = install alias
  dune
Labels: kind: cleanup, part: build

#14565 ci-unimath: stop running DisplayedInserter.v
  dev/ci/ci-unimath.sh
Labels: kind: ci-failure, kind: infrastructure, part: CI

#14561 Windows action: run make -f Makefile.dune world
  dev/ci/azure-build.sh
Labels: kind: fix, part: CI

#14540 Do not link libraries in coqnative.
  topbin/coqnative_bin.ml
Labels: kind: performance, part: native compiler

#13353 Cleanup of metasyntax.ml
  dev/ci/user-overlays/13353-herbelin-master+metasyntax-cleaning.sh
  interp/dumpglob.ml
  interp/dumpglob.mli
  interp/notation.ml
  interp/notation.mli
  parsing/ppextend.ml
  parsing/ppextend.mli
  printing/ppconstr.ml
  test-suite/output/NotationSyntax.out
  test-suite/output/NotationSyntax.v
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  test-suite/output/allBytes.out
  test-suite/output/notation_principal_scope.out
  vernac/comFixpoint.ml
  vernac/comInductive.ml
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/ppvernac.mli
  vernac/record.ml
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup, part: notations
