Repository rocq-prover/rocq, pull requests merged in 2021-05, with the labels that each got.

#14017 [coqdep] Make some options and API internal
  tools/coqdep.ml
  tools/coqdep.mli
  tools/coqdep_common.ml
  tools/coqdep_common.mli
Labels: kind: cleanup

#13885 [ocaml] Bump Ocaml edge to 4.12.0
  .github/workflows/ci.yml
  .gitlab-ci.yml
  INSTALL.md
  coqpp/coqpp_main.ml
  dev/ci/azure-opam.sh
  dev/ci/ci-basic-overlay.sh
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/13885-ejgallego-ocaml+4.12.sh
  dev/dune-workspace.all
  dev/top_printers.ml
  doc/changelog/11-infrastructure-and-dependencies/13885-ocaml+4.12.rst
  interp/constrextern.ml
  interp/constrextern.mli
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrview.ml
  plugins/ssr/ssrview.mli
  stm/stm.ml
  tools/configure/configure.ml
  vernac/comCoercion.ml
  vernac/vernacentries.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
Labels: kind: infrastructure, part: ocaml

#14142 No evar map surgery (Evd.remove) in rewrite
  plugins/ltac/rewrite.ml
  test-suite/bugs/closed/bug_14239.v
Labels: kind: cleanup

#14212 [build] [doc] Build a few more targets hygienically
  .gitlab-ci.yml
  Makefile.doc
  doc/dune
  doc/stdlib/Library.tex
  doc/tools/show_latex_messages
Labels: kind: infrastructure, part: build

#14223 [build] Fix missing deps to trigger coqide rebuild in bridge mode
  Makefile.ide
Labels: kind: fix, kind: infrastructure, part: build

#14225 [build] Some more fixes to Dune-Make bridge + ci-* targets
  Makefile.build
  Makefile.common
  dev/ci/ci-common.sh
  dune
  kernel/nativelib.ml
  test-suite/misc/coq_environment.sh
  tools/coq_makefile.ml
Labels: kind: fix, kind: infrastructure, part: build

#14235 Specialize the warning for "Hint Rewrite" without an explicit locality.
  tactics/autorewrite.ml
Labels: kind: fix, kind: user messages

#14240 Legacy build: split coqdep invocation if command line too long
  Makefile.build
Labels: kind: fix, kind: infrastructure, platform: macOS

#14233 [build] Ensure `make world` builds all targets present in `make install`
  Makefile.build
  Makefile.ide
  Makefile.install
Labels: kind: fix, kind: infrastructure, part: build

#14205 [build] [dune] Add world-prelude target to produce a subset of world
  Makefile.dune
Labels: kind: infrastructure, part: build

#14229 Normalize universes before comparing in progress
  engine/evarutil.ml
  engine/univProblem.ml
  engine/univProblem.mli
  lib/acyclicGraph.ml
  test-suite/bugs/closed/bug_14221.v
Labels: kind: fix, part: universes

#13440 Micro uniformization evarconv in passing
  pretyping/evarsolve.ml
Labels: kind: cleanup, part: unification

#14217 ci: override coq url in platform script
  dev/ci/platform-windows.bat
Labels: kind: fix, kind: infrastructure

#14067 [doc] Note that `coq_makefile --help` will display help.
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#14167 Improve description of "coqc -Q"
  doc/sphinx/addendum/ring.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#13287 Allow split compilation for native compute files
  Makefile.build
  Makefile.common
  doc/changelog/08-cli-tools/13287-native-vo-to-cmxs-compiler.rst
  doc/sphinx/practical-tools/utilities.rst
  topbin/coqnative_bin.ml
  topbin/dune
Labels: kind: internal, part: build, part: native compiler

#14257 Fixes #14211: ident notation modifier wrongly classified for printing
  doc/changelog/03-notations/14257-master+fix14211-buggy-ident-notation-modifier-for-printing-custom-entry.rst
  test-suite/bugs/closed/bug_14211.v
  vernac/metasyntax.ml
Labels: kind: fix, part: notations

#14154 [coqdoc] Some refactoring / cleanup in preparation for component consolidation
  tools/coqdoc/cdglobals.ml
  tools/coqdoc/cdglobals.mli
  tools/coqdoc/fileUtil.ml
  tools/coqdoc/fileUtil.mli
  tools/coqdoc/glob_file.ml
  tools/coqdoc/glob_file.mli
  tools/coqdoc/index.ml
  tools/coqdoc/index.mli
  tools/coqdoc/latexCompiler.ml
  tools/coqdoc/latexCompiler.mli
  tools/coqdoc/main.ml
  tools/coqdoc/main.mli
Labels: kind: cleanup, part: coqdoc

#14270 Fix the native compilation of Ltac2 in hybrid mode.
  Makefile.build
  topbin/coqnative_bin.ml
Labels: kind: fix, part: build, part: native compiler

#14273 [coqnative] Adjust library dependency
  topbin/dune
Labels: kind: cleanup, part: build

#14274 Update inductive.rst
  doc/sphinx/language/core/inductive.rst
Labels: kind: documentation, kind: fix

#14262 Tweaks for running doc_gram_verify in CI
  Makefile.doc
  doc/tools/docgram/README.md
  doc/tools/docgram/doc_grammar.ml
Labels: kind: documentation, kind: infrastructure

#14275 Add codeowners (CI maintainers) for the linter scripts.
  .github/CODEOWNERS
Labels: kind: meta

#14219 Have "make clean" remove files that Dune regards as unhygenic
  Makefile.make
Labels: kind: fix, kind: infrastructure, part: build

#14183 Custom entries are superglobal
  doc/changelog/03-notations/14183-custom-load.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/bugs/closed/bug_13654.v
  test-suite/bugs/closed/bug_9521.v
  test-suite/bugs/closed/bug_9640.v
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  test-suite/success/Notations2.v
  vernac/metasyntax.ml
Labels: kind: fix

#14146 Update release doc: we don't publish news on the website anymore.
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#14096 The usual order of strings, take 2
  doc/changelog/10-standard-library/14096-string-ot.rst
  theories/Structures/OrdersEx.v
Labels: kind: enhancement, part: standard library

#14280 Fix the compilation of the stdlib after #14096.
  theories/Structures/OrdersEx.v
Labels: kind: fix, priority: high

#14264 Allow undefined evars during firstorder
  plugins/firstorder/instances.ml
  test-suite/bugs/closed/bug_14264.v
Labels: kind: fix

#13539 Small improvement in naming dependent goals
  pretyping/unification.ml
  test-suite/output/unification.out
  test-suite/output/unification.v
Labels: kind: enhancement, part: proof engine

#14261 Fixing #14207: multiple warning about unused variable catching several cases
  clib/cArray.ml
  clib/cArray.mli
  doc/changelog/02-specification-language/14261-master+fix14207-warning-unused-variable-in-match-return.rst
  pretyping/cases.ml
  pretyping/cases.mli
  test-suite/output/Cases.out
  test-suite/output/Cases.v
Labels: kind: fix

#14087 Q lemmas: reduction, EQ from parts, num/denum cancellation
  doc/changelog/10-standard-library/14087-q-lemmas/qlemmas.rst
  theories/QArith/QArith_base.v
Labels: kind: enhancement, part: standard library

#14247 Cleanup some universe substitution functions
  dev/ci/user-overlays/14247-SkySkimmer-usubst-clean.sh
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  engine/univSubst.ml
  engine/univSubst.mli
  kernel/univ.ml
  kernel/univ.mli
  tactics/hints.ml
  vernac/comHints.ml
Labels: kind: cleanup

#14220 [debugger] Restore ~loc parm in "Parsable.make", allow setting loc.bp
  gramlib/grammar.ml
  gramlib/grammar.mli
  gramlib/plexing.ml
  gramlib/plexing.mli
  lib/lStream.ml
  lib/lStream.mli
  parsing/cLexer.ml
  parsing/pcoq.ml
  parsing/pcoq.mli
  toplevel/vernac.ml
  vernac/vernacinterp.ml
Labels: kind: enhancement, kind: fix

#14242 Clean the Reductionops.Stack API
  dev/base_include
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  pretyping/evarconv.ml
  pretyping/evarconv.mli
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/unification.ml
Labels: kind: cleanup

#14290 make sure Ltac2 module Option is available when requiring Ltac2.Ltac2
  user-contrib/Ltac2/Ltac2.v
Labels: kind: fix

#14288 respect debug flag in Ltac2.Std.eauto
  user-contrib/Ltac2/tac2tactics.ml
Labels: kind: fix

#14295 [parsing] expose parsing rules for inductive declarations
  dev/ci/user-overlays/14295-gares-export-ind-parsing-rules.sh
  vernac/g_vernac.mlg
  vernac/pvernac.ml
  vernac/pvernac.mli
Labels: kind: internal

#14294 [build] Don't buffer output of sphinx calls
  Makefile.dune
Labels: kind: infrastructure

#14285 Fixing #14283: coqdoc does not report the name of file where an error occurs
  doc/changelog/08-cli-tools/14285-master+coqdoc-error-reports-line.rst
  tools/coqdoc/cpretty.mll
Labels: kind: fix, part: coqdoc

#14258 [build] Remove undocumented prefix install vars, use DESTDIR
  Makefile.doc
  Makefile.ide
  Makefile.install
  dev/doc/INSTALL.make.md
  doc/changelog/11-infrastructure-and-dependencies/14258-build+destdir.rst
Labels: kind: documentation, kind: fix, part: build

#14316 Fix pre-commit hook on binary files
  dev/tools/pre-commit
Labels: kind: fix, kind: infrastructure

#14315 Update the icon file to have multiple sizes
  ide/coqide/coq.ico
Labels: kind: enhancement, kind: fix, part: IDE

#14263 Add `hex_{Z,N,positive}_scope`
  doc/changelog/10-standard-library/14263-hex-z.rst
  test-suite/output/NSyntax.out
  test-suite/output/NSyntax.v
  test-suite/output/PosSyntax.out
  test-suite/output/PosSyntax.v
  test-suite/output/ZSyntax.out
  test-suite/output/ZSyntax.v
  theories/NArith/BinNat.v
  theories/NArith/BinNatDef.v
  theories/Numbers/BinNums.v
  theories/PArith/BinPos.v
  theories/PArith/BinPosDef.v
  theories/ZArith/BinInt.v
  theories/ZArith/BinIntDef.v
Labels: kind: enhancement, part: notations, part: standard library

#14267 Show the non-build specific name of the Coq file target in hybrid mode.
  Makefile.build
Labels: kind: infrastructure

#14224 [debugger] Preserve Loc.t info for Ltac constructs
  dev/ci/user-overlays/14224-jfehrle-ltac_loc_info.sh
  plugins/firstorder/g_ground.mlg
  plugins/ltac/coretactics.mlg
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_tactic.mlg
  plugins/ltac/pptactic.ml
  plugins/ltac/profile_ltac.ml
  plugins/ltac/rewrite.ml
  plugins/ltac/tacentries.ml
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacsubst.ml
  plugins/ltac/tactic_debug.ml
  plugins/ltac/tactic_option.ml
  plugins/ltac/tauto.ml
  plugins/ring/ring.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssrmatching/ssrmatching.ml
  user-contrib/Ltac2/tac2core.ml
Labels: kind: enhancement, part: ltac

#14318 Hide useless missing .aux file message in CoqIDE
  lib/aux_file.ml
Labels: kind: cleanup, kind: fix

#14277 [ltac] expose APIs to project Tacentries.ty_ml GADT
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
Labels: kind: internal

#14308 Prevent back and forth change of representation in kernel strong reduction
  kernel/cClosure.ml
Labels: kind: fix

#14250 Split level creation from level population in Grammar
  coqpp/coqpp_ast.mli
  coqpp/coqpp_lex.mll
  coqpp/coqpp_main.ml
  coqpp/coqpp_parse.mly
  dev/doc/changes.md
  doc/tools/docgram/doc_grammar.ml
  gramlib/gramext.ml
  gramlib/gramext.mli
  gramlib/grammar.ml
  gramlib/grammar.mli
  parsing/g_constr.mlg
  parsing/pcoq.ml
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_obligations.mlg
  plugins/ltac/tacentries.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrvernac.mlg
  plugins/ssrmatching/g_ssrmatching.mlg
  plugins/ssrsearch/g_search.mlg
  user-contrib/Ltac2/g_ltac2.mlg
  user-contrib/Ltac2/tac2entries.ml
  vernac/egramcoq.ml
  vernac/egramml.ml
  vernac/g_proofs.mlg
  vernac/g_vernac.mlg
  vernac/pvernac.ml
  vernac/vernacextend.ml
Labels: kind: redesign

#14086 [stdlib] [Arith] uniform modulo
  doc/changelog/10-standard-library/14086-mod-uniform.rst
  kernel/byterun/coq_interp.c
  kernel/uint63_31.ml
  kernel/uint63_63.ml
  plugins/micromega/micromega.ml
  test-suite/success/Nia.v
  theories/Init/Nat.v
  theories/ZArith/BinIntDef.v
  theories/ZArith/Zdiv.v
  theories/ZArith/Znat.v
  theories/extraction/ExtrHaskellNatNum.v
  theories/extraction/ExtrHaskellZNum.v
  theories/extraction/ExtrOcamlZBigInt.v
  theories/omega/PreOmega.v
Labels: kind: enhancement, part: standard library

#14336 Formally deprecate the Regular Subst Tactic option.
  doc/changelog/07-vernac-commands-and-options/14336-deprecate-regular-subst-option.rst
  tactics/equality.ml
  test-suite/output/subst.out
  test-suite/output/subst.v
Labels: kind: cleanup, part: tactics

#14309 Deprecate -native-compiler option for coqc.
  Makefile.build
  doc/changelog/08-cli-tools/14309-native-deprecate-coqc-native-compiler-flag.rst
  doc/sphinx/practical-tools/coq-commands.rst
  sysinit/coqargs.ml
  sysinit/coqargs.mli
  sysinit/coqinit.ml
  test-suite/output/bug_13821_native_command_line_warn.v
  theories/dune
  tools/CoqMakefile.in
  user-contrib/Ltac2/dune
Labels: kind: cleanup, part: native compiler

#14299 Native profiler compat with OCaml 4.12.0
  pretyping/nativenorm.ml
Labels: kind: fix

#14070 Gramlib: new tree-based look-ahead of tokens
  doc/changelog/03-notations/14070-master+gramlib-tree-based-token-look-ahead.rst
  gramlib/grammar.ml
  test-suite/success/Notations2.v
Labels: kind: feature, part: parser

#14347 Clean the logic of general_elim_clause.
  tactics/equality.ml
Labels: kind: cleanup

#14307 Force dune to use locally built coqide for the shim
  dev/shim/dune
Labels: kind: fix, part: build

#14334 Add vscoq language server to CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-vscoq.sh
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#14357 [ci] coq-elpi 1.10.0
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/14357-gares-update-elpi-1.10.sh
Labels: kind: infrastructure

#14358 Extract and consolidate new refman page on reasoning with inductive types.
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proofs/writing-proofs/index.rst
  doc/sphinx/proofs/writing-proofs/inductive.rst
  doc/sphinx/user-extensions/proof-schemes.rst
Labels: kind: documentation

#14323 Post bench updates to zulip
  dev/bench/bench.sh
  dev/bench/gitlab-bench.yml
  dev/bench/render_results
Labels: kind: infrastructure

#14372 More links to attribute, flag and option documentation.
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/sprop.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/language/extensions/canonical.rst
  doc/sphinx/language/extensions/evars.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/automatic-tactics/logic.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/sphinx/proofs/writing-proofs/inductive.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#14351 Clean the internal flag in scheme declaration
  tactics/elimschemes.ml
  tactics/eqschemes.ml
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  vernac/auto_ind_decl.ml
  vernac/indschemes.ml
Labels: kind: cleanup

#14238 coq_makefile: use DELETE_ON_ERROR
  doc/changelog/08-cli-tools/14238-delete-error.rst
  tools/CoqMakefile.in
Labels: kind: enhancement, kind: fix, kind: infrastructure, part: build

#14364 include Makefile.ci in Makefile.dune
  Makefile.ci
  Makefile.dune
  dev/ci/ci-common.sh
Labels: kind: infrastructure, part: build

#14380 Bench zulip bot: post link to PR being benched.
  dev/bench/bench.sh
Labels: kind: infrastructure

#14259 Fixes #14199 and other Ctrl-C issues in coqtop
  gramlib/grammar.ml
  toplevel/coqloop.ml
  vernac/himsg.ml
Labels: kind: fix, part: toplevel

#14365 Update description of overlays
  dev/ci/user-overlays/README.md
Labels: kind: documentation, part: build

#14368 Protecting the transparent_state printer from failing in debugger
  printing/printer.ml
Labels: kind: fix, kind: internal

#14170 Adding a couple of missing keywords in coqdoc
  tools/coqdoc/cpretty.mll
Labels: kind: fix, part: coqdoc

#14150 Make `pose_all_metas_as_evars` also pose free metas inside defined metas
  pretyping/unification.ml
  test-suite/bugs/closed/bug_14150.v
Labels: kind: fix

#14362 Cleanup CI scripts "&&" usage and minor other style changes
  dev/ci/ci-aac_tactics.sh
  dev/ci/ci-argosy.sh
  dev/ci/ci-bbv.sh
  dev/ci/ci-bedrock2.sh
  dev/ci/ci-bignums.sh
  dev/ci/ci-color.sh
  dev/ci/ci-common.sh
  dev/ci/ci-compcert.sh
  dev/ci/ci-coq_dpdgraph.sh
  dev/ci/ci-coq_performance_tests.sh
  dev/ci/ci-coq_tools.sh
  dev/ci/ci-coqhammer.sh
  dev/ci/ci-coqprime.sh
  dev/ci/ci-coqtail.sh
  dev/ci/ci-coquelicot.sh
  dev/ci/ci-corn.sh
  dev/ci/ci-cross_crypto.sh
  dev/ci/ci-deriving.sh
  dev/ci/ci-elpi.sh
  dev/ci/ci-engine_bench.sh
  dev/ci/ci-equations.sh
  dev/ci/ci-ext_lib.sh
  dev/ci/ci-fcsl_pcm.sh
  dev/ci/ci-fiat_crypto.sh
  dev/ci/ci-fiat_crypto_legacy.sh
  dev/ci/ci-fiat_crypto_ocaml.sh
  dev/ci/ci-fiat_parsers.sh
  dev/ci/ci-flocq.sh
  dev/ci/ci-fourcolor.sh
  dev/ci/ci-gappa.sh
  dev/ci/ci-geocoq.sh
  dev/ci/ci-hott.sh
  dev/ci/ci-interval.sh
  dev/ci/ci-iris.sh
  dev/ci/ci-math_classes.sh
  dev/ci/ci-mathcomp.sh
  dev/ci/ci-mczify.sh
  dev/ci/ci-menhir.sh
  dev/ci/ci-metacoq.sh
  dev/ci/ci-mtac2.sh
  dev/ci/ci-oddorder.sh
  dev/ci/ci-paramcoq.sh
  dev/ci/ci-perennial.sh
  dev/ci/ci-quickchick.sh
  dev/ci/ci-reduction_effects.sh
  dev/ci/ci-relation_algebra.sh
  dev/ci/ci-rewriter.sh
  dev/ci/ci-sf.sh
  dev/ci/ci-simple_io.sh
  dev/ci/ci-stdlib2.sh
  dev/ci/ci-tlc.sh
  dev/ci/ci-unicoq.sh
  dev/ci/ci-unimath.sh
  dev/ci/ci-verdi_raft.sh
  dev/ci/ci-vscoq.sh
  dev/ci/ci-vst.sh
Labels: kind: cleanup

#14381 Fix overlay system when used locally (out of CI)
  dev/ci/ci-common.sh
  dev/ci/user-overlays/README.md
Labels: kind: fix, kind: infrastructure

#14382 Handle delayed opaque proofs in Print Assumptions
  doc/changelog/07-vernac-commands-and-options/14382-assumptions-delayed-opaque.rst
  test-suite/misc/print-assumptions-vok.sh
  test-suite/misc/print-assumptions-vok/file1.v
  test-suite/misc/print-assumptions-vok/file2.v
  vernac/assumptions.ml
Labels: kind: fix

#13871 Remove IF_then_else
  doc/changelog/10-standard-library/13871-IF.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  theories/Init/Logic.v
Labels: kind: cleanup, part: standard library

#14378 Fixes #14124: forbid empty strings in Ltac notations
  doc/changelog/04-tactics/14378-master+fix14124-check-empty-string-ltac-notation.rst
  plugins/ltac/g_ltac.mlg
Labels: kind: fix, part: ltac, part: notations

#14385 Fixing spacing in the extraction inside module warning
  plugins/extraction/table.ml
Labels: kind: fix, part: extraction

#14102 Fixes #14100: extraction failure of a logical type with parameters sealed behind a non-logical type assumption
  doc/changelog/07-vernac-commands-and-options/14102-master+fix14100-extraction-aliased-logical-type-with-params.rst
  plugins/extraction/extraction.ml
  test-suite/bugs/closed/bug_14100.v
Labels: kind: fix, part: extraction

#14174 Add `inversion_sigma H`
  doc/changelog/04-tactics/14174-inversion-sigma-on.rst
  doc/changelog/10-standard-library/14174-inversion-sigma-on.rst
  doc/sphinx/proofs/writing-proofs/inductive.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
  test-suite/success/InversionSigma.v
  test-suite/success/bug_14174.v
  theories/Init/Logic.v
  theories/Init/Specif.v
  theories/Init/Tactics.v
Labels: kind: enhancement, part: standard library, part: tactics

#14355 Further clean up of the hint API
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#14356 Opaque API for serialized opaque tables
  checker/check.ml
  kernel/opaqueproof.ml
  kernel/opaqueproof.mli
  stm/stm.ml
  vernac/library.ml
  vernac/library.mli
Labels: kind: cleanup

#14371 No reason to set transparency to typeclasses transparency when trying unification heuristics
  doc/changelog/02-specification-language/14371-master+default-transparent-for-unification-heuristics.rst
  pretyping/pretyping.ml
  test-suite/bugs/closed/bug_14374.v
Labels: kind: fix, part: unification

#14037 [zify] add support for Nat.div, Nat.mod, Nat.pow
  doc/changelog/04-tactics/14037-N-Z-div-mod.rst
  doc/sphinx/addendum/micromega.rst
  doc/stdlib/hidden-files
  test-suite/micromega/div_mod.v
  test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v
  theories/Arith/PeanoNat.v
  theories/NArith/Nnat.v
  theories/Numbers/Cyclic/Int31/Cyclic31.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/Numbers/Cyclic/ZModulo/ZModulo.v
  theories/Numbers/Integer/Abstract/ZDivFloor.v
  theories/Numbers/NatInt/NZDiv.v
  theories/PArith/Pnat.v
  theories/QArith/Qround.v
  theories/ZArith/Zdiv.v
  theories/ZArith/Znat.v
  theories/ZArith/Znumtheory.v
  theories/ZArith/Zquot.v
  theories/micromega/ZifyInst.v
  theories/micromega/ZifyN.v
  theories/micromega/ZifyNat.v
Labels: kind: enhancement, part: micromega, part: standard library

#12411 Add support for CoqMakefile.local-late
  doc/changelog/08-tools/12411-makefile-local-late.rst
  doc/sphinx/practical-tools/utilities.rst
  test-suite/coq-makefile/local-late-extension/Makefile.local-late
  test-suite/coq-makefile/local-late-extension/make-printvo.log.expected
  test-suite/coq-makefile/local-late-extension/run.sh
  tools/CoqMakefile.in
  tools/coq_makefile.ml
Labels: kind: enhancement, kind: infrastructure, part: tools

#14399 Fix bench bot PR title
  dev/bench/bench.sh
Labels: kind: infrastructure

#14389 Remove deprecated Univops module
  engine/univops.ml
  engine/univops.mli
Labels: kind: cleanup

#14363 Printing of projections was missing a box opening
  printing/ppconstr.ml
  test-suite/output/Record.out
  test-suite/output/Record.v
Labels: kind: fix

#14401 Fix changelog entry for PR 14087
  doc/changelog/10-standard-library/14087-q-lemmas.rst
Labels: kind: cleanup

#14296 Nicer anomaly in lookup_constant/inductive
  kernel/environ.ml
Labels: kind: internal

#14369 When terms in SProp do not unify, rely on proof irrelevance
  pretyping/evarconv.ml
  test-suite/success/unification.v
Labels: kind: enhancement, part: unification

#14391 Correctly declare scheme dependencies
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  vernac/auto_ind_decl.ml
  vernac/auto_ind_decl.mli
  vernac/indschemes.ml
Labels: kind: cleanup

#14383 Fast monomial implementation in Micromega
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
Labels: kind: performance

#14272 Fix a discrepancy between the doc and reality of `coqworkmgr`
  doc/sphinx/addendum/parallel-proof-processing.rst
Labels: kind: documentation, kind: fix

#14386 Allow dependent products as keys of canonical instances
  doc/changelog/02-specification-language/14041-cs_lambda.rst
  doc/changelog/02-specification-language/14386-cs_dep_prod.rst
  doc/sphinx/language/extensions/canonical.rst
  pretyping/evarconv.ml
  pretyping/structures.ml
  test-suite/output/Warnings.out
  test-suite/output/Warnings.v
  test-suite/success/CanonicalStructure.v
Labels: kind: enhancement

#14081 Ltac2: add lazy boolean operators
  doc/changelog/05-tactic-language/14081-ltac2_lazy_bool.rst
  test-suite/ltac2/bool_lib.v
  user-contrib/Ltac2/Bool.v
Labels: kind: feature, part: ltac2

#14392 Do not consider scrutinees of projections and cases as heads for hint mode "!"
  doc/changelog/02-specification-language/14392-nohead-evar-application-hea.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  tactics/hints.ml
  test-suite/success/HintMode.v
Labels: kind: enhancement

#14395 Forbid changing typing flags inside sections
  dev/doc/critical-bugs
  doc/changelog/01-kernel/14395-print-assum-section-flags.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/environ.mli
  kernel/safe_typing.ml
  kernel/term_typing.ml
  test-suite/bugs/closed/bug_14317.v
Labels: kind: fix, kind: inconsistency

#14407 guard against timelog2html failure
  dev/bench/bench.sh
Labels: kind: infrastructure

#9711 Allow projections to be declared as classes.
  doc/changelog/02-specification-language/9711-primitive-projection-classes.rst
  pretyping/typeclasses.ml
  test-suite/bugs/closed/bug_12975.v
Labels: kind: feature

#14404 Fix Makefile.local-late test
  test-suite/coq-makefile/local-late-extension/Makefile.local-late
  test-suite/coq-makefile/local-late-extension/printvo.expected
  test-suite/coq-makefile/local-late-extension/run.sh
Labels: kind: fix, part: test-suite

#14410 Explode detailed tactic examples
  doc/sphinx/proof-engine/detailed-tactic-examples.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/writing-proofs/index.rst
  doc/sphinx/proofs/writing-proofs/inductive.rst
  test-suite/bugs/closed/bug_13363.v
  test-suite/output/bug_13266.v
Labels: kind: cleanup, kind: documentation

#14153 [stdlib] [List] cleaner List.v
  doc/changelog/10-standard-library/14153-cleaner-list.rst
  theories/Lists/List.v
Labels: kind: enhancement, part: standard library

#14402 Localize the scheme creation functions
  tactics/elimschemes.ml
  tactics/eqschemes.ml
  tactics/eqschemes.mli
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  vernac/auto_ind_decl.ml
Labels: kind: cleanup

#14337 Remove the delayed name substitution mechanism from the kernel
  checker/mod_checking.ml
  checker/values.ml
  dev/ci/user-overlays/14337-ppedrot-eager-constr-mod-subst.sh
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/environ.ml
  kernel/mod_subst.ml
  kernel/mod_subst.mli
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/nativecode.ml
  kernel/nativelambda.ml
  kernel/opaqueproof.ml
  kernel/safe_typing.ml
  kernel/subtyping.ml
  kernel/term_typing.ml
  kernel/vmbytegen.ml
  kernel/vmbytegen.mli
  kernel/vmemitcodes.ml
  kernel/vmemitcodes.mli
  kernel/vmlambda.ml
  kernel/vmsymtable.ml
  library/global.ml
  plugins/extraction/extract_env.ml
  plugins/extraction/extraction.ml
  pretyping/tacred.ml
  vernac/assumptions.ml
  vernac/prettyp.ml
  vernac/printmod.ml
Labels: kind: cleanup

#14413 Prevent a quadratic blowup in Micromega annotations.
  plugins/micromega/coq_micromega.ml
  plugins/micromega/micromega.ml
  plugins/micromega/micromega.mli
  theories/micromega/Tauto.v
Labels: kind: performance
