Repository rocq-prover/rocq, pull requests merged in 2021-09, with the labels that each got.

#13972 [ide] Extend the API so we can specify max both depth
  ide/coqide/idetop.ml
  ide/coqide/protocol/richpp.ml
  ide/coqide/protocol/richpp.mli
  ide/coqide/protocol/xmlprotocol.ml
  ide/coqide/protocol/xmlprotocol.mli
  ide/coqide/wg_MessageView.ml
  ide/coqide/wg_ProofView.ml
Labels: part: IDE, kind: internal

#14820 Partially revert f4fd9fd0 (in #11711): it introduced an inefficiency in tactic apply
  tactics/tactics.ml
Labels: kind: fix, part: tactics, kind: efficiency

#14825 Minifix in a nonsensical coqdep error message: don't add dirname on unknown option name in a Coq project.
  lib/coqProject_file.ml
Labels: kind: fix, kind: user messages, part: tools

#13664 Notations for numerals are treated natively and do not modify the constr parser
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  parsing/cLexer.ml
  parsing/g_constr.mlg
  parsing/tok.ml
  test-suite/output/NotationSyntax.out
  test-suite/output/NotationSyntax.v
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  test-suite/output/PrintGrammarConstr.out
  test-suite/output/PrintGrammarConstr.v
  vernac/egramcoq.ml
  vernac/metasyntax.ml
Labels: part: notations, kind: enhancement

#14828 Handle coq project parsing errors in coqdep
  lib/coqProject_file.ml
  lib/coqProject_file.mli
  tools/coqdep_common.ml
Labels: part: tools, kind: anomaly

#14826 coqdep: Replacing anomaly with a warning on non-existing directory
  tools/coqdep_common.ml
Labels: kind: user messages, part: tools, kind: anomaly

#14829 Coqdep: indicate the root when reporting about missing files that are non-existent only wrt this root
  tools/coqdep_common.ml
Labels: kind: user messages, part: tools, kind: enhancement

#14794 Adding a few functions about rel context in constr and econstr together with a reorganization
  dev/ci/user-overlays/14794-herbelin-master+rel-context-constr-econstr-api-reorganization.sh
  dev/doc/changes.md
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/termops.mli
  kernel/context.ml
  kernel/context.mli
  kernel/esubst.ml
  kernel/indtypes.ml
  kernel/inductive.ml
  kernel/reduction.ml
  kernel/vars.ml
  kernel/vars.mli
  plugins/firstorder/instances.ml
  pretyping/cases.ml
  pretyping/cbv.ml
  pretyping/detyping.ml
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/vnorm.ml
  tactics/cbn.ml
  tactics/eqschemes.ml
  vernac/comProgramFixpoint.ml
  vernac/record.ml
Labels: kind: cleanup

#14831 Fix #14814 (Anomaly when registering a float primitive without prior registration of the float type)
  kernel/typeops.ml
Labels: kind: fix, part: primitive types

#14515 [install] [configure] Remove unused variables, notes about install location
  Makefile.install
  dev/doc/INSTALL.make.md
  test-suite/Makefile
  tools/configure/configure.ml
Labels: kind: fix, kind: infrastructure, part: build

#14608 Adding a scheduled workflow for stale PRs.
  .github/workflows/stale.yml
Labels: kind: infrastructure

#14839 CI category_theory: use build:base to match equations
  .gitlab-ci.yml
Labels: kind: fix, kind: infrastructure

#14845 Only run stale scheduled workflow on main Coq repo.
  .github/workflows/stale.yml
Labels: kind: infrastructure

#14847 Fix workflow syntax in stale schedule workflow.
  .github/workflows/stale.yml
Labels: kind: infrastructure

#14788 More principled implementation of Btermdnet matching
  tactics/btermdn.ml
  test-suite/bugs/closed/bug_13209.v
  test-suite/bugs/closed/bug_14788.v
Labels: kind: fix, kind: cleanup

#14810 Changing the δ flag semantics in CClosure
  dev/ci/user-overlays/14810-ppedrot-cclosure-cleanup-fdelta.sh
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/reduction.ml
  plugins/firstorder/ground.ml
  plugins/ssr/ssrcommon.ml
  pretyping/tacred.ml
  tactics/eauto.ml
  tactics/redexpr.ml
Labels: kind: cleanup

#14842 aux: don't panic if the .aux file is not writable
  lib/aux_file.ml
Labels: kind: fix, kind: compatibility, part: toplevel

#14279 [CI] Reactivate native-compile for some jobs
  dev/ci/ci-color.sh
  dev/ci/ci-coqprime.sh
  dev/ci/ci-fiat_crypto.sh
  dev/ci/ci-fiat_crypto_ocaml.sh
  dev/ci/ci-fiat_parsers.sh
  dev/ci/ci-perennial.sh
  dev/ci/ci-rewriter.sh
  dev/ci/ci-vst.sh
Labels: kind: infrastructure, part: native compiler, part: CI

#14763 Redesign import filter system for acceptable performance.
  doc/sphinx/language/core/modules.rst
  interp/syntax_def.ml
  interp/syntax_def.mli
  library/libobject.ml
  library/libobject.mli
  test-suite/success/PartialImport.v
  vernac/declare.ml
  vernac/declare.mli
  vernac/declaremods.ml
  vernac/vernacentries.ml
Labels: kind: redesign, kind: performance

#14818 Parameters of inductives in Number Notations can be arbitrary terms
  interp/notation.ml
  interp/notation.mli
  plugins/syntax/number.ml
  plugins/syntax/number.mli
  test-suite/output/NumberNotations.out
  test-suite/output/NumberNotations.v
Labels: kind: fix, part: notations

#14803 [sysinit] fix oversight
  test-suite/output/bug_13821_native_command_line_warn.v
  toplevel/workerLoop.ml
Labels: kind: fix, kind: internal

#14780 Obligation state is a stack with push/pop on module and section start/end
  clib/neList.ml
  clib/neList.mli
  doc/changelog/07-vernac-commands-and-options/14780-obl-stack.rst
  test-suite/bugs/closed/bug_14446.v
  toplevel/ccompile.ml
  vernac/vernacentries.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
  vernac/vernacinterp.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: fix, kind: cleanup, part: program, part: sections, kind: internal, part: vernac

#14808 Correctly share opaque references in CClosure reftab.
  kernel/cClosure.ml
Labels: kind: performance

#14853 Stale workflow: fix syntax for using secret.
  .github/workflows/stale.yml
Labels: kind: infrastructure

#14858 Update mailmap.
  .mailmap
Labels: kind: meta

#14851 CI: stop using a bunch of stages
  .gitlab-ci.yml
  dev/bench/gitlab-bench.yml
Labels: kind: cleanup, kind: infrastructure

#14854 Use "next()" more in coqargs
  sysinit/coqargs.ml
Labels: kind: cleanup

#14844 [configure] Detect Dune 2.9, use right install options in this case.
  Makefile.doc
  Makefile.install
  dev/doc/INSTALL.make.md
  doc/README.md
  doc/sphinx/changes.rst
  tools/CoqMakefile.in
  tools/configure/configure.ml
Labels: kind: infrastructure

#14855 Mark #14610 and #14664 as present in 8.14.
  doc/changelog/04-tactics/14610-master+fix-14609-set-tactic-not-typing.rst
  doc/changelog/07-vernac-commands-and-options/14664-alizter+fix-14652.rst
  doc/sphinx/changes.rst
Labels: kind: documentation, priority: blocker

#14793 Share evar identities between clenv evars.
  engine/evarutil.ml
  engine/evarutil.mli
  proofs/clenv.ml
  proofs/goal.ml
Labels: kind: performance

#14813 Exporting sigT Notations, plus some theorems between (A * B) and {_ : A & B}
  doc/changelog/10-standard-library/14813-sigT.rst
  theories/Init/Specif.v
  theories/Relations/Relation_Operators.v
  theories/Wellfounded/Lexicographic_Product.v
Labels: part: standard library, kind: enhancement

#14860 Less verbose bench logs
  dev/bench/bench.sh
Labels: kind: cleanup, part: bench

#14819 Remove 8.13 deprecations
  dev/ci/user-overlays/14819-proux01-rm_deprecated_813.sh
  doc/changelog/03-notations/14819-rm_deprecated_813.rst
  doc/changelog/07-vernac-commands-and-options/14819-rm_deprecated_813.rst
  doc/changelog/10-standard-library/14819-rm_deprecated_813.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/changes.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/stdlib/hidden-files
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  engine/proofview.ml
  engine/proofview.mli
  ide/coqide/wg_ProofView.ml
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/ltac/extratactics.mlg
  plugins/ltac/pltac.ml
  plugins/ltac/pltac.mli
  plugins/syntax/g_number_string.mlg
  printing/printer.ml
  proofs/proof.ml
  proofs/proof.mli
  test-suite/bugs/closed/bug_2969.v
  test-suite/bugs/closed/bug_3531.v
  test-suite/bugs/closed/bug_3647.v
  test-suite/bugs/closed/bug_6202.v
  test-suite/success/apply.v
  test-suite/success/attribute_syntax.v
  theories/Floats/PrimFloat.v
  theories/Init/Datatypes.v
  theories/Init/Number.v
  theories/Init/Numeral.v
  theories/Init/Prelude.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/Numbers/Cyclic/Int63/Uint63.v
  theories/Numbers/DecimalFacts.v
  theories/Numbers/HexadecimalFacts.v
  theories/Program/Basics.v
  theories/Program/Combinators.v
  user-contrib/Ltac2/tac2entries.ml
  user-contrib/Ltac2/tac2entries.mli
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/g_proofs.mlg
  vernac/ppvernac.ml
  vernac/pvernac.ml
  vernac/pvernac.mli
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup

#14630 Add a paragraph on reviewing PRs from newcomers.
  CONTRIBUTING.md
Labels: kind: documentation, kind: meta

#14659 Update debugging docs a bit
  Makefile.build
  Makefile.dev
  Makefile.make
  dev/doc/build-system.dune.md
  dev/doc/debugging.md
Labels: kind: cleanup, kind: documentation, kind: infrastructure

#14809 Adding a simple lexicographic product
  doc/changelog/10-standard-library/14809-lexipair.rst
  theories/Relations/Relation_Operators.v
  theories/Wellfounded/Lexicographic_Product.v
Labels: part: standard library, kind: enhancement

#14861 Don't bench opam's overhead.
  dev/bench/bench.sh
  dev/bench/render_results
  dev/bench/wrapper.sh
Labels: kind: fix, kind: infrastructure, kind: enhancement, part: bench

#14871 Improve boxing in univ printing
  engine/termops.ml
  kernel/univ.ml
  test-suite/output/ShowUnivs.out
  test-suite/output/ShowUnivs.v
  vernac/vernacentries.ml
Labels: kind: user messages

#14870 CI: build autosubst outside of ci-iris
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-autosubst.sh
  dev/ci/ci-iris.sh
Labels: kind: infrastructure

#14832 Create number-maintainers team
  .github/CODEOWNERS
  test-suite/output/FloatNumberSyntax.out
  test-suite/output/FloatNumberSyntax.v
  test-suite/output/Int31NumberSyntax.out
  test-suite/output/Int31NumberSyntax.v
  test-suite/output/Int63NumberSyntax.out
  test-suite/output/Int63NumberSyntax.v
  test-suite/output/NNumberSyntax.out
  test-suite/output/NNumberSyntax.v
  test-suite/output/RealNumberSyntax.out
  test-suite/output/RealNumberSyntax.v
  test-suite/output/Sint63NumberSyntax.out
  test-suite/output/Sint63NumberSyntax.v
  test-suite/output/ZNumberSyntax.out
  test-suite/output/ZNumberSyntax.v
  test-suite/output/sint63NumberNotation.out
  test-suite/output/sint63NumberNotation.v
Labels: kind: meta

#14698 Recommend `make -C test-suite` over other methods.
  dev/doc/build-system.dune.md
  test-suite/README.md
Labels: kind: documentation, kind: internal

#12425 [ci] [gh-actions] Run the platform job using Github Actions
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .gitlab-ci.yml
  dev/ci/README-developers.md
  dev/ci/azure-build.sh
  dev/ci/azure-opam.sh
  dev/ci/azure-test.sh
  dev/ci/platform-windows.bat
  dev/ci/platform/coq-pf-01-sysinfo.bat
  dev/ci/platform/coq-pf-02-download.bat
  dev/ci/platform/coq-pf-03-build.bat
  dev/ci/platform/coq-pf-04-installer.bat
  dev/doc/changes.md
  dev/tools/merge-pr.sh
  doc/changelog/11-infrastructure-and-dependencies/12425-ci+gh_actions_win.rst
Labels: kind: infrastructure, platform: Windows

#14059 [build] [tools] Consolidation of directory handling code
  boot/dune
  boot/env.ml
  boot/env.mli
  boot/path.ml
  boot/util.ml
  checker/checker.ml
  checker/dune
  clib/cPath.mli
  dev/ci/user-overlays/14059-ejgallego-coq+path_boot.sh
  dev/doc/changes.md
  doc/changelog/08-cli-tools/14059-coq+path_boot.rst
  doc/dune
  doc/sphinx/using/tools/coqdoc.rst
  ide/coqide/unicode_bindings.ml
  kernel/dune
  kernel/nativelib.ml
  lib/dune
  lib/envars.ml
  lib/envars.mli
  man/coqdoc.1
  plugins/micromega/coq_micromega.ml
  sysinit/coqargs.ml
  sysinit/coqinit.ml
  sysinit/coqloadpath.ml
  sysinit/coqloadpath.mli
  sysinit/dune
  test-suite/Makefile
  tools/configure/configure.ml
  tools/coq_makefile.ml
  tools/coqdep.ml
  tools/coqdep_common.ml
  tools/coqdoc/cdglobals.ml
  tools/coqdoc/cdglobals.mli
  tools/coqdoc/dune
  tools/coqdoc/index.ml
  tools/coqdoc/main.ml
  tools/dune
  topbin/coqnative_bin.ml
  toplevel/coqloop.ml
  toplevel/coqtop.ml
Labels: kind: redesign, part: build

#14863 Introduce a CoqIDE option to deactivate unicode binding completetion.
  doc/changelog/09-coqide/14863-coqide-opt-unicode-binding.rst
  doc/sphinx/practical-tools/coqide.rst
  ide/coqide/coqide.ml
  ide/coqide/preferences.ml
  ide/coqide/preferences.mli
Labels: kind: feature, part: IDE

#14812 Clarify installation instructions for Coq Plugin Tutorial
  doc/plugin_tutorial/README.md
Labels: kind: documentation

#14827 Remove mention of confusing dummy line number on non-existing file for coqdep
  tools/coqdep_common.ml
Labels: kind: user messages, part: tools

#14877 Update load_printers after coq-core.boot was added.
  dev/core.dbg
  dev/core_dune.dbg
  dev/dune_db_408
  dev/dune_db_409
Labels: kind: fix, kind: infrastructure, part: build

#14824 ocamllibdep: raise a proper error for directory not found rather than an uncaught exception
  tools/ocamllibdep.mll
Labels: kind: fix, part: tools

#14881 [coqtop] [byte] [ocaml] Address OCaml 4.13 deprecations
  topbin/coqtop_byte_bin.ml
Labels: kind: compatibility, part: ocaml

#14873 [build] [coqide] Provide correct platform-specific hooks.
  ide/coqide/coqide_QUARTZ.c.in
  ide/coqide/coqide_WIN32.c.in
  ide/coqide/coqide_WIN32.ml.in
  ide/coqide/coqide_X11.c.in
  ide/coqide/dune
  ide/coqide/gen_gtk_platform.ml
Labels: kind: fix, kind: infrastructure, part: build

#14878 [boot] [meta] Add codeowners for `boot`
  .github/CODEOWNERS
Labels: kind: meta

#14714 Added reminder to not end with period in make-changelog.
  dev/tools/make-changelog.sh
Labels: kind: infrastructure

#14189 [configure] Rewrite and modularization of configure [1/n]
  .github/CODEOWNERS
  .gitlab-ci.yml
  INSTALL.md
  dev/doc/INSTALL.make.md
  dev/doc/profiling.txt
  doc/changelog/11-infrastructure-and-dependencies/14189-configure+rewrite_mod.rst
  tools/configure/cmdArgs.ml
  tools/configure/cmdArgs.mli
  tools/configure/configure.ml
  tools/configure/configure.mli
  tools/configure/coqide.ml
  tools/configure/coqide.mli
  tools/configure/dune
  tools/configure/util.ml
  tools/configure/util.mli
Labels: kind: cleanup, kind: infrastructure, part: build

#14894 Track v8.14's documentation instead of v8.13's.
  doc/sphinx/conf.py
Labels: kind: documentation, kind: infrastructure

#14850 Fix scoping of the do_subrelation local definition in setoid rewrite.
  plugins/ltac/rewrite.ml
  test-suite/bugs/closed/bug_14725.v
Labels: kind: fix

#14897 [changes] Rectify changelog w.r.t. configure fixes.
  dev/doc/changes.md
  doc/changelog/11-infrastructure-and-dependencies/14844-configure_dune_detect.rst
  doc/sphinx/changes.rst
Labels: kind: fix, kind: documentation

#14711 Handling universe context and names together and centrally treating in declare.ml
  dev/ci/user-overlays/14711-herbelin-master+univs-ctx-and-binders-centralized.sh
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  interp/modintern.ml
  plugins/ring/ring.ml
  tactics/ind_tables.mli
  test-suite/misc/poly-capture-global-univs/src/evilImpl.ml
  vernac/classes.ml
  vernac/comAssumption.ml
  vernac/comAssumption.mli
  vernac/comInductive.ml
  vernac/comPrimitive.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/declareInd.ml
  vernac/record.ml
  vernac/record.mli
Labels: kind: cleanup, part: universes

#14902 fix make-changelog.sh
  dev/tools/make-changelog.sh
Labels: kind: fix, kind: infrastructure

#14846 Using the name of inductive types in inductive blocks rather than indices
  checker/checkInductive.ml
  dev/ci/user-overlays/14846-herbelin-master+inlining-inductive-names-in-inductive-blocks.sh
  dev/doc/changes.md
  engine/eConstr.ml
  engine/eConstr.mli
  kernel/cClosure.ml
  kernel/declarations.ml
  kernel/indtypes.ml
  kernel/inductive.ml
  kernel/inductive.mli
  kernel/reduction.ml
  kernel/safe_typing.ml
  kernel/subtyping.ml
  pretyping/cbv.ml
  pretyping/detyping.ml
  pretyping/inductiveops.ml
  pretyping/nativenorm.ml
  pretyping/vnorm.ml
  vernac/assumptions.ml
  vernac/assumptions.mli
Labels: kind: cleanup, part: kernel, part: inductives

#14903 Remove the duplicate universe state from kernel declarations
  checker/checkInductive.ml
  checker/mod_checking.ml
  checker/values.ml
  dev/ci/user-overlays/14903-ppedrot-split-mono-univ-entry.sh
  engine/uState.ml
  engine/uState.mli
  interp/modintern.ml
  kernel/cooking.ml
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/entries.ml
  kernel/indTyping.ml
  kernel/inductive.ml
  kernel/mod_typing.ml
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  kernel/subtyping.ml
  kernel/term_typing.ml
  library/global.ml
  library/global.mli
  plugins/ring/ring.ml
  printing/printer.ml
  test-suite/misc/poly-capture-global-univs/src/evilImpl.ml
  test-suite/output/UnivBinders.out
  test-suite/output/bug_11934.out
  vernac/comAssumption.ml
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/comPrimitive.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/declareUniv.ml
  vernac/declareUniv.mli
  vernac/prettyp.ml
  vernac/record.ml
  vernac/record.mli
Labels: kind: cleanup

#14900 The "class" typeclass object has no import time effect
  vernac/classes.ml
Labels: kind: cleanup

#14904 Add test for printing of template polymorphism info
  test-suite/output/Inductive.out
  test-suite/output/Inductive.v
  test-suite/output/PrimitiveProjectionsAttribute_Records.out
  test-suite/output/PrintInfos.out
  vernac/prettyp.ml
Labels: kind: user messages

#14905 Remove ancient "Print Modules" syntax
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  ide/coqide/coq_commands.ml
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup

#14916 Slight simplification of Indtyping.get_template logic
  kernel/indTyping.ml
Labels: kind: cleanup

#14918 Small trivial cleanups in side-effect handling in Safe_typing.
  kernel/safe_typing.ml
  kernel/safe_typing.mli
Labels: kind: cleanup

#14917 Merge CClosure.inductive_subst and Reduction.inductive_subst
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/reduction.ml
Labels: kind: cleanup

#14758 Understand some inductive cumulativity in old unification
  doc/changelog/04-tactics/14758-unif-cumul.rst
  engine/eConstr.ml
  engine/eConstr.mli
  pretyping/unification.ml
  test-suite/bugs/closed/bug_14734.v
  test-suite/bugs/closed/bug_6976.v
Labels: kind: enhancement, part: universes

#14931 Correctly cache opaque body access in Print Assumptions.
  vernac/assumptions.ml
Labels: kind: performance

#14901 Fixes #14899: improved output of "Eval red in term" by betaiota-normalizing the type, like Check does
  doc/changelog/07-vernac-commands-and-options/14901-master+wish14899-nf-betaiota-on-result-evai-in.rst
  test-suite/output/bug_14899.out
  test-suite/output/bug_14899.v
  vernac/vernacentries.ml
Labels: kind: fix, part: vernac

#14919 [build] Set dune root explicitly / use --release
  Makefile.common
  configure
  tools/configure/cmdArgs.ml
Labels: kind: fix, kind: infrastructure, part: build

#14940 Remove state explicit management for good
  config/coq_config.mli
  doc/changelog/07-vernac-commands-and-options/14940-rm-output-state-for-good.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  ide/coqide/coq_commands.ml
  lib/system.ml
  lib/system.mli
  tools/configure/configure.ml
  toplevel/coqc.ml
  toplevel/coqcargs.ml
  toplevel/coqcargs.mli
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: cleanup

#14922 document more Hint Cut quirks
  doc/sphinx/proofs/automatic-tactics/auto.rst
Labels: kind: documentation

#14945 Correctly handle a test introduced in #14758 in async mode.
  test-suite/bugs/closed/bug_14734.v
Labels: kind: fix

#14946 More explicit error message for missing constraints in @{...|...}
  engine/uState.ml
Labels: kind: user messages

#14939 [printing] Move notation printing format to printing
  printing/ppextend.ml
  printing/ppextend.mli
Labels: kind: internal

#14932 Do not lift subterms in the cut tactic.
  tactics/tactics.ml
Labels: kind: performance

#14848 Uniformly use dnets for goals with evars in all auto tactics
  dev/ci/user-overlays/14848-ppedrot-btermdn-discriminate-evar.sh
  doc/changelog/04-tactics/14848-btermdn-discriminate-evar.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  tactics/auto.ml
  tactics/btermdn.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: performance

#14949 Add some doc for [Constr.Case]
  kernel/constr.mli
Labels: kind: internal
