Repository rocq-prover/rocq, pull requests merged in 2021-08, with the labels that each got.

#14690 Use cdebug for vernacinterp debug print
  vernac/vernacinterp.ml
Labels: kind: cleanup

#14699 Added #[projections(primitive)] attribute for structures.
  doc/changelog/07-vernac-commands-and-options/14699-alizter+primitive-attribute.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/language/core/coinductive.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/records.rst
  test-suite/failure/PrimitiveProjectionsAttribute_Inductives.v
  test-suite/output/PrimitiveProjectionsAttribute.out
  test-suite/output/PrimitiveProjectionsAttribute.v
  test-suite/output/PrimitiveProjectionsAttribute_Records.out
  test-suite/output/PrimitiveProjectionsAttribute_Records.v
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
Labels: kind: feature, part: attributes, part: primitive records

#14697 Allowing certain non-local hint commands inside sections
  doc/changelog/07-vernac-commands-and-options/14697-hint-section-locality.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  plugins/ltac/g_auto.mlg
  tactics/hints.ml
  tactics/hints.mli
  test-suite/output/HintLocality.out
  test-suite/output/HintLocality.v
  vernac/classes.ml
  vernac/declare.ml
  vernac/vernacentries.ml
Labels: kind: enhancement, part: tactics, part: typeclasses

#14730 Remove the eta flag from CClosure redflags.
  kernel/cClosure.ml
  kernel/cClosure.mli
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/structures.ml
  tactics/cbn.ml
Labels: kind: cleanup

#14742 Output test for `Scheme` command(s).
  test-suite/output/SchemeNames.out
  test-suite/output/SchemeNames.v
Labels: kind: infrastructure, part: test-suite

#14713 Fixes #14708: anomalies in applied notation variable in match patterns
  doc/changelog/03-notations/14713-master+fix-14708-anomaly-applied-notation-var-in-pattern.rst
  interp/constrexpr_ops.ml
  interp/constrintern.ml
  test-suite/bugs/closed/bug_14708.v
Labels: kind: fix, part: notations

#14598 Explicit Projection nodes in concrete syntax
  dev/ci/user-overlays/14598-herbelin-master+proj-nodes-in-concrete-syntax.sh
  dev/doc/changes.md
  doc/sphinx/language/core/records.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  interp/constrexpr.ml
  interp/constrexpr_ops.ml
  interp/constrextern.ml
  interp/constrintern.ml
  interp/implicit_quantifiers.ml
  interp/notation.ml
  interp/notation_ops.ml
  interp/notation_term.ml
  parsing/g_constr.mlg
  plugins/funind/gen_principle.ml
  plugins/funind/glob_term_to_relation.ml
  plugins/funind/glob_termops.ml
  plugins/ltac/rewrite.ml
  plugins/ltac/tacintern.ml
  plugins/ssr/ssrvernac.mlg
  plugins/ssrmatching/ssrmatching.ml
  pretyping/detyping.ml
  pretyping/glob_ops.ml
  pretyping/glob_term.ml
  pretyping/patternops.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  printing/ppconstr.ml
  printing/proof_diffs.ml
  test-suite/output/bug_6764.out
  test-suite/output/bug_6764.v
  test-suite/success/Funind.v
Labels: kind: cleanup, part: parser

#14715 More comprehensive use of unification when pretyping lambdas and applications
  pretyping/coercion.ml
  pretyping/coercion.mli
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  test-suite/success/CanonicalStructure.v
Labels: kind: fix

#14744 Add category-theory to ci.
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-category_theory.sh
Labels: kind: infrastructure, part: CI

#14757 Install expat and libxml2 in macOS deps
  .github/workflows/ci.yml
Labels: kind: fix, kind: infrastructure, part: CI

#14754 Faster algorithm for addition of coercions.
  pretyping/coercionops.ml
Labels: kind: performance

#14672 In error messages, consider evars equal to all for deciding verbosity
  doc/changelog/03-notations/14672-coerce-print-hole.rst
  interp/constrexpr_ops.ml
  interp/constrexpr_ops.mli
  test-suite/output/CoercionOnHole.out
  test-suite/output/CoercionOnHole.v
  vernac/himsg.ml
Labels: kind: enhancement

#14705 Handle default locality at attribute time
  dev/ci/user-overlays/14705-SkySkimmer-inst-local-warn.sh
  doc/changelog/02-specification-language/14705-inst-local-warn.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_auto.mlg
  plugins/ltac/rewrite.ml
  tactics/autorewrite.ml
  tactics/autorewrite.mli
  tactics/hints.ml
  tactics/hints.mli
  test-suite/bugs/closed/bug_14704.v
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/classes.ml
  vernac/classes.mli
  vernac/comAssumption.ml
  vernac/declare.ml
  vernac/vernacentries.ml
Labels: kind: user messages, kind: enhancement

#14750 Add "Succeed" command modifier, like "Fail Fail" but keeps error messages
  doc/changelog/02-specification-language/14750-succeed.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  stm/proofBlockDelimiter.ml
  stm/stm.ml
  test-suite/output/Succeed.out
  test-suite/output/Succeed.v
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernac_classifier.ml
  vernac/vernacexpr.ml
  vernac/vernacinterp.ml
  vernac/vernacprop.ml
  vernac/vernacprop.mli
Labels: kind: feature, part: vernac

#14756 Don't require execute permission on ci-* scripts
  dev/ci/ci-aac_tactics.sh
  dev/ci/ci-argosy.sh
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-bbv.sh
  dev/ci/ci-bedrock2.sh
  dev/ci/ci-bignums.sh
  dev/ci/ci-category_theory.sh
  dev/ci/ci-color.sh
  dev/ci/ci-compcert.sh
  dev/ci/ci-coq_dpdgraph.sh
  dev/ci/ci-coq_performance_tests.sh
  dev/ci/ci-coq_tools.sh
  dev/ci/ci-coqhammer.sh
  dev/ci/ci-coqprime.sh
  dev/ci/ci-coqtail.sh
  dev/ci/ci-coquelicot.sh
  dev/ci/ci-corn.sh
  dev/ci/ci-cross_crypto.sh
  dev/ci/ci-deriving.sh
  dev/ci/ci-elpi.sh
  dev/ci/ci-engine_bench.sh
  dev/ci/ci-equations.sh
  dev/ci/ci-ext_lib.sh
  dev/ci/ci-fcsl_pcm.sh
  dev/ci/ci-fiat_crypto.sh
  dev/ci/ci-fiat_crypto_legacy.sh
  dev/ci/ci-fiat_crypto_ocaml.sh
  dev/ci/ci-fiat_parsers.sh
  dev/ci/ci-flocq.sh
  dev/ci/ci-fourcolor.sh
  dev/ci/ci-gappa.sh
  dev/ci/ci-geocoq.sh
  dev/ci/ci-hott.sh
  dev/ci/ci-iris.sh
  dev/ci/ci-math_classes.sh
  dev/ci/ci-mathcomp.sh
  dev/ci/ci-mczify.sh
  dev/ci/ci-menhir.sh
  dev/ci/ci-metacoq.sh
  dev/ci/ci-mtac2.sh
  dev/ci/ci-oddorder.sh
  dev/ci/ci-paramcoq.sh
  dev/ci/ci-perennial.sh
  dev/ci/ci-quickchick.sh
  dev/ci/ci-reduction_effects.sh
  dev/ci/ci-relation_algebra.sh
  dev/ci/ci-rewriter.sh
  dev/ci/ci-sf.sh
  dev/ci/ci-simple_io.sh
  dev/ci/ci-stdlib2.sh
  dev/ci/ci-tlc.sh
  dev/ci/ci-unicoq.sh
  dev/ci/ci-unimath.sh
  dev/ci/ci-verdi_raft.sh
  dev/ci/ci-vscoq.sh
  dev/ci/ci-vst.sh
  dev/ci/ci-wrapper.sh
Labels: kind: cleanup, kind: infrastructure

#14732 On-the-fly η-reduction of dnet patterns and terms.
  doc/changelog/04-tactics/14732-btermdn-up-to-eta-match.rst
  tactics/btermdn.ml
  test-suite/bugs/closed/bug_14731.v
Labels: kind: fix

#14625 Fix running test suite (unit tests) outside dune with pure dune build
  test-suite/Makefile
Labels: kind: fix, kind: infrastructure

#14234 String: add leb
  doc/changelog/10-standard-library/14234-string_leb.rst
  theories/Strings/Ascii.v
  theories/Strings/String.v
  theories/Structures/OrderedTypeEx.v
Labels: kind: feature, part: standard library

#14751 Remove test-suite/bugs/opened/bug_3345.v
  test-suite/bugs/opened/bug_3345.v
Labels: kind: fix

#14669 Fixes #7228: anomaly with Set Extraction Conservative Types on singletons
  doc/changelog/07-vernac-commands-and-options/14669-master+fix7228-anomaly-extraction-singleton-conservative.rst
  plugins/extraction/extraction.ml
  test-suite/bugs/closed/bug_7228.v
Labels: kind: fix, part: extraction

#14764 Fix missing evar normalization when reifying match in vm/native norm
  pretyping/nativenorm.ml
  pretyping/vnorm.ml
  test-suite/bugs/closed/bug_13950.v
Labels: kind: fix

#14766 Fix cofix vs fix in warnings about cofixpoints
  test-suite/output/Fixpoint.out
  vernac/comFixpoint.ml
Labels: kind: user messages

#14770 Add #5744 to test-suite
  test-suite/bugs/closed/bug_5744.v
Labels: kind: infrastructure, part: test-suite

#14772 Error on attributes on Qed/Defined
  test-suite/bugs/closed/bug_14360.v
  vernac/vernacentries.ml
Labels: kind: fix

#14755 Faster reduction for canonical structure registering.
  pretyping/structures.ml
Labels: kind: performance

#14786 Switch artifact expiration date to 1 month
  .gitlab-ci.yml
Labels: kind: infrastructure

#14574 Put Permutation-related Proper instances at default priority.
  doc/changelog/10-standard-library/14574-permutation-prio.rst
  theories/Sorting/Permutation.v
Labels: kind: fix, part: standard library

#14771 Refactoring / hardening related to the `Structural Injection` flag.
  plugins/funind/gen_principle.ml
  plugins/ssr/ssrelim.ml
  tactics/eqdecide.ml
  tactics/equality.ml
  tactics/equality.mli
  theories/Numbers/DecimalQ.v
  theories/Numbers/DecimalR.v
  theories/Numbers/HexadecimalQ.v
  theories/Numbers/HexadecimalR.v
  vernac/auto_ind_decl.ml
Labels: kind: cleanup

#14765 Fix simpl with pattern an ltac variable bound to a term with evars.
  plugins/ltac/tacinterp.ml
  test-suite/bugs/closed/bug_13933.v
Labels: kind: fix

#14753 Treat variable patterns uniformly in Btermdn.
  tactics/btermdn.ml
Labels: kind: cleanup

#14787 Define COQBIN in CoqMakefile.in to avoid "undefined variable" warnings
  doc/changelog/08-cli-tools/14787-coqbin-declaration.rst
  tools/CoqMakefile.in
Labels: part: tools, kind: enhancement

#14726 Let Context.Named.to_instance conform to its specification + mini-simplifications about named_context
  kernel/context.ml
  kernel/context.mli
  kernel/inductive.ml
  kernel/reduction.ml
  plugins/extraction/extraction.ml
  pretyping/cases.ml
  pretyping/detyping.ml
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  proofs/logic.ml
  tactics/eqschemes.ml
  tactics/tactics.ml
  vernac/auto_ind_decl.ml
  vernac/comCoercion.ml
  vernac/comHints.ml
  vernac/comInductive.ml
  vernac/printmod.ml
  vernac/record.ml
Labels: kind: cleanup

#14783 CI: VST uses master branch
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure, part: CI

#14792 Small configure cleanup: prefs not mutable after args parsing
  tools/configure/configure.ml
Labels: kind: cleanup

#14716 Fix unexpected vertical formatting of goal conclusion
  printing/printer.ml
  test-suite/output/Notations3.out
  test-suite/output/Notations3.v
Labels: kind: fix, part: notations, part: printer

#14779 More modular typed_vernac implementation
  coqpp/coqpp_main.ml
  dev/ci/user-overlays/14779-SkySkimmer-typed-vernac-modular.sh
  dev/top_printers.ml
  plugins/funind/g_indfun.mlg
  plugins/ltac/g_obligations.mlg
  test-suite/bugs/closed/bug_12138.v
  test-suite/bugs/closed/bug_14781.v
  vernac/vernacentries.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
  vernac/vernacinterp.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: cleanup, kind: user messages, kind: internal

#14767 Preserve \r in XML and don't bump the line count for it
  ide/coqide/coq.ml
  ide/coqide/protocol/xml_lexer.mll
  ide/coqide/protocol/xml_parser.ml
  ide/coqide/protocol/xml_parser.mli
Labels: kind: fix, part: debugger

#14354 Debugger: mapping between absolute filenames and dirpaths
  dev/ci/user-overlays/14354-jfehrle-modpath_in_loct.sh
  lib/feedback.ml
  lib/loc.ml
  lib/loc.mli
  library/libnames.ml
  toplevel/ccompile.ml
  toplevel/vernac.ml
  toplevel/vernac.mli
  vernac/loadpath.ml
  vernac/loadpath.mli
  vernac/topfmt.ml
  vernac/vernacinterp.ml
Labels: kind: enhancement, part: debugger

#14525 Include floats in the number notation mechanism
  doc/changelog/03-notations/14525-rm-float-plugin.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  interp/constrextern.ml
  interp/notation.ml
  interp/notation.mli
  plugins/syntax/dune
  plugins/syntax/float_syntax.ml
  plugins/syntax/float_syntax_plugin.mllib
  plugins/syntax/number.ml
  test-suite/output/NumberNotations.out
  test-suite/output/NumberNotations.v
  theories/Floats/PrimFloat.v
  theories/dune
Labels: part: notations, kind: enhancement, part: primitive types

#14797 More accurate IllTypedInstance error messages
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/evarsolve.mli
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  vernac/himsg.ml
Labels: kind: fix, kind: user messages, part: unification

#14816 Fix printing mutual fixpoints
  printing/ppconstr.ml
  test-suite/output/bug_14815.out
  test-suite/output/bug_14815.v
Labels: kind: fix, part: notations

#14817 A few miscellaneous typos
  doc/sphinx/language/core/modules.rst
  interp/constrintern.ml
  interp/impargs.ml
  interp/impargs.mli
  interp/implicit_quantifiers.ml
  kernel/constr.ml
  parsing/g_constr.mlg
  pretyping/detyping.ml
Labels: kind: cleanup, kind: internal

#14776 Fix #13857: Nonsensical error messages of apply
  tactics/tactics.ml
  test-suite/output/bug_13857.out
  test-suite/output/bug_13857.v
Labels: kind: fix
