Repository rocq-prover/rocq, pull requests merged in 2021-10, with the labels that each got.

#14961 [ci] [docker] Bump cppo version.
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: fix, part: CI

#14960 Add a newline at the end of generated changelog files.
  dev/tools/make-changelog.sh
Labels: kind: fix, part: tools

#14889 [configure] Guard debug code under `-debug` flag
  tools/configure/cmdArgs.ml
  tools/configure/cmdArgs.mli
  tools/configure/configure.ml
  tools/configure/util.ml
  tools/configure/util.mli
Labels: kind: fix, part: build

#14955 [test-suite] Add test for #10193
  test-suite/bugs/closed/bug_10193.v
Labels: kind: infrastructure

#14956 [test-suite] Add test for #10182
  test-suite/bugs/closed/bug_10182.v
Labels: kind: infrastructure

#14958 added #13385 to test-suite
  test-suite/bugs/closed/bug_13385.v
Labels: kind: fix, kind: infrastructure, part: test-suite

#14890 [test-suite] Error when calling test-suite without a full build.
  test-suite/Makefile
Labels: kind: user messages, part: test-suite

#14964 Document new coqbot `SKIP_DOCKER=false` feature.
  dev/ci/README-developers.md
  dev/ci/docker/README.md
Labels: kind: documentation, kind: meta

#14963 Bump Sphinx to 3.0.2.
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  doc/README.md
  doc/changelog/11-infrastructure-and-dependencies/14963-master.rst
  doc/sphinx/conf.py
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation, kind: infrastructure

#14965 CI: check CACHEKEY in docker-boot
  .gitlab-ci.yml
  dev/tools/check-cachekey.sh
Labels: kind: infrastructure

#14968 add period to changelog
  dev/tools/make-changelog.sh
Labels: kind: infrastructure

#14969 CI: continue to work when an overlay was merged upstream
  dev/ci/ci-common.sh
Labels: kind: fix, kind: infrastructure, part: CI

#14957 coqchk respects sharing flag per-definition
  checker/checkFlags.ml
  doc/changelog/08-cli-tools/14957-coqchk-share-red.rst
Labels: kind: fix, kind: performance

#14879 [ci] [ocaml] Bump edge compiler to Ocaml 4.13.0
  .gitlab-ci.yml
  INSTALL.md
  dev/ci/docker/bionic_coq/Dockerfile
  doc/changelog/11-infrastructure-and-dependencies/14879-ci+ocaml_4_13.rst
  dune
  kernel/dune
  tools/configure/configure.ml
Labels: kind: compatibility, part: ocaml

#14924 Move futures out of kernel
  checker/check.ml
  checker/mod_checking.ml
  checker/mod_checking.mli
  dev/ci/user-overlays/14924-ppedrot-move-opaque-out-of-kernel.sh
  kernel/entries.ml
  kernel/modops.ml
  kernel/modops.mli
  kernel/opaqueproof.ml
  kernel/opaqueproof.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  kernel/term_typing.mli
  library/global.ml
  library/global.mli
  plugins/extraction/extraction.ml
  stm/stm.ml
  test-suite/ide/join-idem.fake
  test-suite/ide/join-module1.fake
  test-suite/ide/join-module2.fake
  toplevel/ccompile.ml
  vernac/assumptions.ml
  vernac/declare.ml
  vernac/declaremods.ml
  vernac/declaremods.mli
  vernac/future.ml
  vernac/future.mli
  vernac/library.ml
  vernac/library.mli
  vernac/opaques.ml
  vernac/opaques.mli
  vernac/prettyp.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: redesign

#14977 Print library name in "Cannot load a library with the same name as the current one." error
  kernel/safe_typing.ml
Labels: kind: user messages

#14954 Simpler universe propagation in safe_typing module start/end
  kernel/safe_typing.ml
Labels: kind: cleanup

#14979 Add theories/_CoqProject (makes -topfile work when editing the stdlib)
  theories/Classes/CMorphisms.v
  theories/Classes/Morphisms.v
  theories/_CoqProject
Labels: kind: fix

#14978 Refresh universes in apply tactic
  tactics/tactics.ml
  test-suite/bugs/closed/bug_8310.v
Labels: kind: fix

#14971 Clarify behavior of Locate command
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#14974 Add timeout to the bench
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench
