Repository rocq-prover/rocq, pull requests merged in 2022-05, with the labels that each got.

#15960 Port deprecated Format code in recent versions of OCaml.
  ide/coqide/protocol/richpp.ml
  lib/pp.ml
  vernac/topfmt.ml
Labels: kind: cleanup

#15967 Various code cleanups now that we require OCaml >= 4.09
  .github/workflows/ci-windows.yml
  .gitlab-ci.yml
  INSTALL.md
  clib/cMap.ml
  clib/cMap.mli
  clib/cSig.mli
  clib/cThread.ml
  clib/hMap.ml
  default.nix
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/platform/coq-pf-03-build.bat
  dev/core.dbg
  dev/core_dune.dbg
  dev/db
  dev/doc/INSTALL.make.md
  dev/doc/build-system.dune.md
  dev/dune_db
  dev/dune_db_408
  dev/dune_db_409
  dev/tools/coqdev.el
  doc/changelog/09-coqide/15947-cleanup_ocaml409.rst
  doc/changelog/12-misc/15967-cleanup_ocaml409.rst
  doc/sphinx/practical-tools/utilities.rst
  kernel/uint63_31.ml
  kernel/uint63_63.ml
  plugins/extraction/ocaml.ml
  plugins/micromega/persistent_cache.ml
  pretyping/nativenorm.ml
  test-suite/output/EmptyExtraction.out
  tools/configure/coqide.ml
Labels: kind: cleanup

#15965 Forbid template univ poly for mutual inductives
  doc/changelog/01-kernel/15965-no-mutual-template.rst
  doc/sphinx/language/core/inductive.rst
  kernel/indTyping.ml
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: cleanup

#15693 Reversible coercions
  dev/ci/user-overlays/15693-gares-reverse-coercions.sh
  doc/changelog/02-specification-language/15693-reverse-coercions.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  pretyping/coercion.ml
  pretyping/coercionops.ml
  pretyping/coercionops.mli
  test-suite/output/relaxed_ambiguous_paths.out
  test-suite/success/reverse_coercions.v
  test-suite/success/reverse_coercions_ac.v
  test-suite/success/reverse_coercions_typeclasses_and_canonical.v
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/comAssumption.ml
  vernac/comCoercion.ml
  vernac/comCoercion.mli
  vernac/comInductive.ml
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/prettyp.ml
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: feature, part: coercions

#15908 Compute template universes using the cumulativity inference algorithm.
  kernel/indTyping.ml
  kernel/indTyping.mli
  vernac/comInductive.ml
Labels: kind: redesign

#15988 Try to preserve physical equality in Constr.exliftn.
  kernel/constr.ml
Labels: kind: performance

#15953 [coqdep] clean up error handling for coqdep
  tools/coqdep/common.ml
Labels: kind: cleanup, part: coqdep

#15984 Avoid CoqIDE crash for #15873 (but not a full fix)
  ide/coqide/coqOps.ml
Labels: kind: fix, part: IDE

#15979 Delay computation of abstracted context in Cooking.
  kernel/cooking.ml
Labels: kind: performance

#15995 Remove coq-prog-args comments from test for #7916
  test-suite/bugs/bug_7916.v
Labels: kind: cleanup, part: test-suite

#15994 Run fiat-crypto-ocaml with -j 1
  dev/ci/ci-fiat_crypto_ocaml.sh
Labels: kind: infrastructure

#15990 [CI] Test coq-native separately from split packages
  .gitlab-ci.yml
Labels: kind: infrastructure

#13395 More examples of the usage of variance of inductives
  doc/sphinx/addendum/universe-polymorphism.rst
Labels: kind: documentation, part: universes

#15997 CI unimath: skip BiadjunctionPreserveInserters
  dev/ci/ci-unimath.sh
Labels: kind: infrastructure

#15976 Fix Search failing in proof with no focused goal.
  test-suite/bugs/bug_15972.v
  vernac/vernacentries.ml
Labels: kind: fix

#15981 Update univ poly doc after automatic naming of universes.
  doc/sphinx/addendum/universe-polymorphism.rst
Labels: kind: documentation

#15945 Import categories for all importing commands and import filters for Require
  dev/ci/user-overlays/15945-SkySkimmer-require-filters.sh
  doc/changelog/07-vernac-commands-and-options/15945-require-filters.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  library/lib.ml
  library/lib.mli
  sysinit/coqargs.ml
  sysinit/coqargs.mli
  sysinit/coqinit.ml
  test-suite/success/ImportCat.v
  test-suite/success/PartialImport.v
  vernac/declaremods.ml
  vernac/declaremods.mli
  vernac/g_vernac.mlg
  vernac/library.ml
  vernac/library.mli
  vernac/ppvernac.ml
  vernac/printmod.ml
  vernac/vernacentries.ml
  vernac/vernacentries.mli
  vernac/vernacexpr.ml
Labels: kind: enhancement

#16008 [native compiler] Don't search for coqlib too eagerly.
  kernel/nativelib.ml
Labels: kind: usability

#15333 Replace Pervasives with Stdlib in nat extraction
  doc/changelog/10-standard-library/15333-extract-nat-int.rst
  theories/extraction/ExtrOcamlNatInt.v
Labels: kind: cleanup, part: extraction

#15982 Small cleanups
  kernel/constr.ml
  kernel/nativecode.ml
  plugins/funind/indfun_common.ml
  tools/coqwc.mll
Labels: kind: cleanup

#15971 [build] Don't use .exe for binaries in Cygwin
  tools/configure/configure.ml
Labels: kind: fix, part: build

#16003 [coqdep] Fix Unix stat errors and some cleanup
  tools/coqdep/common.ml
Labels: kind: fix, part: coqdep

#15970 Abstract away the type of matching contexts.
  plugins/ltac/taccoerce.ml
  plugins/ltac/taccoerce.mli
  plugins/ltac/tacinterp.ml
  plugins/ltac/tactic_matching.ml
  plugins/ltac/tactic_matching.mli
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2match.ml
  plugins/ltac2/tac2match.mli
  pretyping/constr_matching.ml
  pretyping/constr_matching.mli
Labels: kind: cleanup

#15896 Reduce the amount of useless typing in Equality.
  tactics/equality.ml
Labels: kind: performance

#16005 Document zarith 1.12 version bump.
  .github/workflows/ci-macos.yml
  INSTALL.md
  coq-core.opam
  coq.opam.docker
  doc/changelog/11-infrastructure-and-dependencies/15483-bump-zarith-doc.rst
  dune-project
  tools/configure/configure.ml
Labels: kind: documentation

#16011 Bump the menhir tag in CI.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#16018 Fix typo in reverse coercions changelog
  doc/changelog/02-specification-language/15693-reverse-coercions.rst
Labels: kind: fix

#15996 Convert byte offset to char offset efficiently
  ide/coqide/coqOps.ml
Labels: kind: fix, kind: performance, part: IDE

#15912 [coqide] Fix code to display goal in both top script and current script buffers
  ide/coqide/coqide.ml
Labels: kind: fix, part: ltac debugger

#16014 Fix coqdep on import categories and filters in Require
  test-suite/misc/coqdep-require-filter-categories.sh
  test-suite/misc/coqdep-require-filter-categories/.gitignore
  test-suite/misc/coqdep-require-filter-categories/fA.v
  test-suite/misc/coqdep-require-filter-categories/fB.v
  test-suite/misc/coqdep-require-filter-categories/fC.v
  test-suite/misc/coqdep-require-filter-categories/stderr.ref
  test-suite/misc/coqdep-require-filter-categories/stdout.ref
  tools/coqdep/lexer.mll
Labels: kind: fix

#16021 Unification.make_pattern_test: use newer evar map instead of older
  pretyping/unification.ml
  test-suite/bugs/bug_15978.v
Labels: kind: fix

#16013 dune-dbg: understand coqdep
  dev/dune
  dev/dune-dbg.in
  tools/coqdep/dune
Labels: kind: infrastructure

#16012 tactic unification debug: print terms when entering unification
  pretyping/unification.ml
Labels: kind: internal

#16027 Add test for #11677
  test-suite/bugs/bug_11677.v
Labels: kind: infrastructure, part: test-suite

#16028 Add test for #5328
  test-suite/bugs/bug_5328.v
Labels: kind: infrastructure, part: test-suite

#16030 Drop minimum zarith version to 1.11
  .github/workflows/ci-macos.yml
  .gitlab-ci.yml
  INSTALL.md
  coq-core.opam
  coq.opam.docker
  dev/ci/docker/bionic_coq/Dockerfile
  doc/changelog/11-infrastructure-and-dependencies/15483-bump-zarith-doc.rst
  dune-project
  tools/configure/configure.ml
Labels: kind: infrastructure, part: build

#15274 Tactic_option supports export
  dev/ci/user-overlays/15274-SkySkimmer-tacopt.sh
  doc/changelog/07-vernac-commands-and-options/15274-tacopt.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/proofs/automatic-tactics/logic.rst
  plugins/firstorder/g_ground.mlg
  plugins/ltac/g_obligations.mlg
  plugins/ltac/tactic_option.ml
  plugins/ltac/tactic_option.mli
  test-suite/output/bug_15106.v
  theories/Classes/EquivDec.v
  theories/Classes/SetoidClass.v
  theories/Classes/SetoidTactics.v
  theories/Program/Tactics.v
Labels: kind: fix, kind: enhancement

#16017 Cleanup of native compilation
  kernel/nativecode.ml
  kernel/nativelambda.ml
  kernel/nativelambda.mli
Labels: kind: cleanup

#16032 Stop using module type CList.ExtS + Remove CList.except (alias of remove)
  clib/cList.ml
  clib/cList.mli
  interp/notation.ml
  lib/util.ml
  lib/util.mli
Labels: kind: cleanup

#16049 [coqdep] moved coqdeplib into own directory
  tools/coqdep/coqdep.ml
  tools/coqdep/dune
  tools/coqdep/lib/args.ml
  tools/coqdep/lib/args.mli
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/common.mli
  tools/coqdep/lib/dune
  tools/coqdep/lib/error.ml
  tools/coqdep/lib/lexer.mli
  tools/coqdep/lib/lexer.mll
  tools/coqdep/lib/loadpath.ml
  tools/coqdep/lib/loadpath.mli
  tools/coqdep/lib/options.ml
  tools/coqdep/lib/options.mli
  tools/coqdep/lib/warning.ml
Labels: kind: infrastructure, part: coqdep

#16059 Pin CI branches for the 8.16 release.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#16058 Do not rely on the Stream API to parse Coq project files.
  lib/coqProject_file.ml
Labels: kind: cleanup

#16009 More direct implementation of hashconsing terms
  kernel/constr.ml
Labels: kind: cleanup

#16029 Fix progress incorrectly failing when evar instantiated in hyps
  engine/proofview.ml
  test-suite/bugs/bug_7957.v
Labels: kind: fix

#16061 Avoid endless loop in Replace All when search text is empty
  ide/coqide/wg_Find.ml
Labels: kind: fix, part: IDE

#16057 Do not compute the return sort of template inductive types in the kernel.
  kernel/indTyping.ml
  test-suite/bugs/bug_16057.v
  test-suite/success/Template.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
Labels: kind: cleanup

#16066 Fix uncaught UnableTounify with bidi hints
  pretyping/pretyping.ml
  test-suite/bugs/bug_16063.v
Labels: kind: fix

#15867 CI: use ocaml 4.14.0 for edge switch
  .gitlab-ci.yml
  INSTALL.md
  checker/checker.ml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/15867-SkySkimmer-edge-4.14.sh
  doc/changelog/11-infrastructure-and-dependencies/15867-edge-4.14.rst
  gramlib/lStream.ml
  gramlib/lStream.mli
  gramlib/stream.ml
  gramlib/stream.mli
  ide/coqide/idetop.ml
  interp/constrexpr_ops.ml
  interp/constrintern.ml
  interp/dune
  interp/numTok.ml
  interp/numTok.mli
  lib/util.ml
  lib/util.mli
  parsing/cLexer.ml
  parsing/g_constr.mlg
  parsing/tok.ml
  plugins/ltac/g_tactic.mlg
  plugins/ssrmatching/g_ssrmatching.mlg
  printing/proof_diffs.ml
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/error.ml
  toplevel/coqloop.ml
  toplevel/g_toplevel.mlg
  toplevel/vernac.ml
  vernac/comInductive.ml
  vernac/himsg.ml
  vernac/proof_using.ml
  vernac/record.ml
  vernac/vernacinterp.ml
Labels: kind: infrastructure, part: ocaml

#16067 doc: Update with renaming of int_scope to dec_int_scope
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#16041 Document `cannot recognize a statement based on @reference` error
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
Labels: kind: documentation

#16065 Display non-visible characters in escaped form (e.g. "\x00")
  ide/coqide/ideutils.ml
Labels: kind: fix, part: IDE

#15986 [stdlib] [Permutation] constructive pigeonhole principle for lists
  doc/changelog/10-standard-library/15986-pigeonhole.rst
  theories/Lists/List.v
  theories/Sorting/Permutation.v
Labels: kind: feature, part: standard library

#16086 Bump the compatibility layer for 8.16.
  dev/ci/ci-flocq.sh
  dev/ci/ci-flocq3.sh
  doc/stdlib/index-list.html.template
  sysinit/coqargs.ml
  test-suite/success/CompatOldOldFlag.v
  test-suite/tools/update-compat/run.sh
  theories/Compat/Coq813.v
Labels: kind: infrastructure

#16075 [coqdep] Cleanup findlib-specific functions.
  clib/cList.ml
  clib/cList.mli
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/error.ml
  tools/coqdep/lib/fl.ml
  tools/coqdep/lib/fl.mli
Labels: kind: cleanup, part: build, part: coqdep

#16092 Fix extraction of max/min to Stdlib.max/min
  theories/extraction/ExtrOcamlNatInt.v
Labels: kind: fix, part: extraction

#16098 Add changes for 8.15.2.
  doc/changelog/04-tactics/15866-inuit-solver.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#16108 Vernacstate.Declare: remove unused APIs
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: cleanup, kind: internal, part: vernac

#16102 Remove Gappa from continuous integration.
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-gappa.sh
  dev/ci/nix/default.nix
  dev/ci/nix/gappa.nix
  dev/ci/user-overlays/15220-gares-dynlink-w-findlib.sh
  dev/ci/user-overlays/15867-SkySkimmer-edge-4.14.sh
Labels: kind: infrastructure, part: CI

#16101 Fix buggy implementation of SFclassify
  dev/doc/critical-bugs
  doc/sphinx/changes.rst
  test-suite/bugs/bug_16096.v
  theories/Floats/SpecFloat.v
Labels: kind: fix, part: standard library

#16111 Add the 8.16 release to sphinx/conf.py.
  doc/sphinx/conf.py
Labels: kind: documentation

#15991 [mltop] Fix bug storing legacy module info in Summary
  dev/doc/changes.md
  library/summary.ml
  library/summary.mli
  sysinit/coqloadpath.ml
  test-suite/coq-makefile/coqdoc1/run.sh
  test-suite/coq-makefile/coqdoc2/run.sh
  test-suite/coq-makefile/mlpack1/run.sh
  test-suite/coq-makefile/mlpack2/run.sh
  test-suite/coq-makefile/multiroot/run.sh
  test-suite/coq-makefile/native1/run.sh
  test-suite/coq-makefile/native2/run.sh
  test-suite/coq-makefile/native3/run.sh
  test-suite/coq-makefile/native4/run.sh
  test-suite/coq-makefile/plugin1/run.sh
  test-suite/coq-makefile/plugin2/run.sh
  test-suite/coq-makefile/plugin3/run.sh
  tools/CoqMakefile.in
  topbin/coqtop_byte_bin.ml
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: fix, kind: documentation, part: build
