Repository rocq-prover/rocq, pull requests merged in 2022-10, with the labels that each got.

#16587 Fix undefined evars in `case q: T`
  plugins/ssr/ssrelim.ml
  test-suite/bugs/bug_16587.v
Labels: kind: fix

#16582 Cleanups around the use of Evd.expand_existential.
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/termops.mli
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
Labels: kind: cleanup

#16585 Add flag to skip computing diffs for hypotheses
  ide/coqide/idetop.ml
  printing/proof_diffs.ml
  printing/proof_diffs.mli
Labels: kind: performance

#16575 Remove unused Nativevalues.arrayinit and arraymap
  kernel/nativevalues.ml
  kernel/nativevalues.mli
Labels: kind: cleanup

#16558 Fix printing of ssreflect `abstract` tactic.
  doc/tools/docgram/fullGrammar
  plugins/ssr/ssrparser.mlg
  test-suite/output/bug_16558.out
  test-suite/output/bug_16558.v
Labels: kind: fix

#16542 CClosure: don't partially apply evar_repack
  kernel/cClosure.ml
Labels: kind: cleanup

#16600 Disable most CI jobs by default.
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#16608 CI: timeout 60min for test suite jobs
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#16601 Disable even more jobs when FULL_CI is not set to true.
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#16581 Workaround for CoqIDE preferences crashing on MacOS (#16136).
  ide/coqide/preferences.ml
Labels: kind: fix, part: IDE

#16597 Allow undefined evars when converting to `Constr.t` in `congruence`
  plugins/cc/cctac.ml
  test-suite/bugs/bug_16597.v
Labels: kind: fix

#16611 Test suite: disable native compile for SchemeEquality
  test-suite/success/SchemeEquality.v
Labels: kind: infrastructure

#16612 soft set ulimit in gitlab-ci.yml
  .gitlab-ci.yml
Labels: kind: infrastructure

#16614 Add a separator to unsupported-attributes message
  test-suite/output/bug_16613.out
  test-suite/output/bug_16613.v
  vernac/attributes.ml
Labels: kind: fix, kind: user messages

#16604 Fix capitalization for macos in GitHub action
  .github/workflows/ci-macos.yml
Labels: kind: infrastructure

#16574 Non rectypes Nativevalues.t using GADT
  kernel/nativecode.ml
  kernel/nativeconv.ml
  kernel/nativevalues.ml
  kernel/nativevalues.mli
  pretyping/nativenorm.ml
Labels: kind: cleanup

#16486 [ci] Add SerAPI to CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-serapi.sh
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure, part: CI

#16619 Ltac2 constr_kind correctly cast evars
  plugins/ltac2/tac2core.ml
  test-suite/bugs/bug_16617.v
Labels: kind: fix, kind: anomaly, part: ltac2

#16588 [stdlib] some facts for NoDup
  doc/changelog/11-standard-library/16588-NoDup_app_comm.rst
  theories/Lists/List.v
  theories/Lists/ListDec.v
Labels: part: standard library, kind: enhancement

#16623 CI: set interruptible: true (except for bench)
  .gitlab-ci.yml
  dev/bench/gitlab-bench.yml
Labels: kind: infrastructure, part: CI

#16595 [bench] set OPAMCLI to 2.0 to silence warnings
  dev/bench/bench.sh
Labels: kind: infrastructure

#16605 Fix problems with `destruct using`
  doc/changelog/05-Ltac-language/16605-fix-destruct-using.rst
  pretyping/tacred.ml
  pretyping/tacred.mli
  tactics/tactics.ml
  test-suite/bugs/bug_16605.v
Labels: kind: fix

#16596 Tactical `only` is at level 3, print it as such
  plugins/ltac/pptactic.ml
  test-suite/output/bug_16596.out
  test-suite/output/bug_16596.v
Labels: kind: fix

#16628 Bench: stop printing "mem faults" column
  dev/bench/render_results.ml
Labels: kind: infrastructure

#16624 use List.In_dec for ListSet.set_In_dec
  theories/Lists/ListSet.v
Labels: kind: cleanup, part: standard library

#16621 Remove mathcomp_base job
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-mathcomp.sh
  dev/ci/ci-mathcomp_test.sh
Labels: kind: infrastructure

#16007 Stop using rectypes in coq-core
  .ocamlinit
  dev/doc/build-system.dune.md
  doc/changelog/12-infrastructure-and-dependencies/16007-norectypes-constr.rst
  doc/sphinx/practical-tools/utilities.rst
  dune
  engine/logic_monad.ml
  engine/logic_monad.mli
  kernel/constr.ml
  stm/stm.ml
  topbin/coqtop_byte_bin.ml
  vernac/declare.ml
Labels: kind: cleanup

#16631 Faster implementation of Proofview.undefined_evars and Proofview.undefined
  engine/proofview.ml
Labels: kind: performance

#16639 Add missing link to token definition in refman.
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation

#16638 Remove useless "New" wrapper modules
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/indfun_common.ml
  plugins/funind/indfun_common.mli
  plugins/funind/recdef.ml
  plugins/ltac/internals.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrview.ml
  tactics/tacticals.mli
  tactics/tactics.ml
  tactics/tactics.mli
  vernac/classes.ml
Labels: kind: cleanup

#16650 [CI] [makefile] remove duplicate ci-mathcomp entry
  Makefile.ci
Labels: kind: infrastructure, part: CI

#16632 Add `skipn_skipn`
  doc/changelog/11-standard-library/16632-patch-1.rst
  theories/Lists/List.v
Labels: part: standard library, kind: enhancement

#16556 Ltac2 record punning
  doc/changelog/06-Ltac2-language/16556-tac2-puns.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2print.ml
  test-suite/ltac2/record_punning.v
Labels: kind: enhancement, part: ltac2

#16142 Fix "Interrupt computations" on Windows
  doc/changelog/10-coqide/16142-fix_win_interrupt2.rst
  ide/coqide/coq.ml
  ide/coqide/coqide.ml
  ide/coqide/coqide_WIN32.c.in
  ide/coqide/coqide_WIN32.ml.in
  ide/coqide/coqide_main.ml
  ide/coqide/dune
  ide/coqide/idetop.ml
  ide/coqide/shared.ml
  ide/coqide/shared.mli
  ide/coqide/shared_QUARTZ.c.in
  ide/coqide/shared_QUARTZ.ml.in
  ide/coqide/shared_WIN32.c.in
  ide/coqide/shared_WIN32.ml.in
  ide/coqide/shared_X11.c.in
  ide/coqide/shared_X11.ml.in
  ide/coqide/shared_os_specific.mli
  lib/spawn.ml
Labels: kind: fix, part: IDE

#16625 [vernac] duplicate extra dep is a warning
  doc/sphinx/proof-engine/vernacular-commands.rst
  test-suite/success/extra_dep.v
  vernac/comExtraDeps.ml
  vernac/loadpath.ml
  vernac/loadpath.mli
Labels: kind: fix

#16547 Ltac2 Constr.in_context: check that the type is actually a type
  doc/changelog/06-Ltac2-language/16547-in_context-check-ty.rst
  plugins/ltac2/tac2core.ml
  pretyping/typing.mli
  test-suite/bugs/bug_16540.v
Labels: kind: fix, part: ltac2

#16649 Add SMTCoq to CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-smtcoq.sh
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure, part: CI

#16644 More details in the documentation of Declare ML Module (+ typo)
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  tools/coqdep/lib/error.ml
Labels: kind: documentation, part: build

#16642 Use natural instead of integer in instantiate tactic syntax
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/extratactics.mlg
Labels: kind: cleanup

#16498 Convert tactics chapter to prodn, part 2
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/language/cic.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/language/extensions/evars.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/sphinx/using/libraries/funind.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#16651 Fix the conversion of Prod values in the native compiler.
  dev/doc/critical-bugs
  doc/changelog/01-kernel/16651-fix-native-vprod-unsoundness.rst
  kernel/nativeconv.ml
  test-suite/bugs/bug_16645.v
Labels: kind: fix, kind: inconsistency

#16674 Fix failure introduced by a semantic merge conflict.
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: fix

#16670 Remove absurd_hyp.
  doc/changelog/04-tactics/16670-remove-absurd_hyp.rst
  theories/Init/Tactics.v
Labels: kind: cleanup

#16679 [bench] Add tweakable native
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#15565 Dispatch consistently it_mkLambda and cie between econstr.ml and termops.ml
  dev/ci/user-overlays/15565-herbelin-master+it_mkLambda-and-cie-econstr-termops-dispatch.sh
  engine/eConstr.ml
  engine/eConstr.mli
  engine/termops.ml
  engine/termops.mli
  plugins/extraction/extraction.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/ssr/ssrelim.ml
  proofs/clenv.ml
  tactics/autorewrite.ml
  tactics/eqschemes.ml
  vernac/auto_ind_decl.ml
  vernac/comCoercion.ml
  vernac/comProgramFixpoint.ml
Labels: kind: cleanup

#16647 Ltac2: don't anomaly when applying ()
  plugins/ltac2/tac2intern.ml
  test-suite/bugs/bug_12820.v
Labels: kind: fix, part: ltac2

#16520 Ltac2: binder_make produces a "not a type" message instead of raw retypeerror, provide unsafe_make
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2print.ml
  user-contrib/Ltac2/Constr.v
Labels: kind: feature, part: ltac2

#16544 Use a user-provided equality in Pcoq rule factorizing instead of (==).
  clib/cList.ml
  clib/cList.mli
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/ltac/tacentries.ml
  plugins/ltac2/tac2entries.ml
  vernac/egramcoq.ml
Labels: kind: cleanup

#16561 [cleanup] Remove `Format Notation` command
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  printing/ppextend.ml
  printing/ppextend.mli
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup

#16687 Remove Format Notation from refman.
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: fix

#16660 Remove pkg:opam job (redundant with pkg:opam:native)
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#16630 [dev] factor shim deps through alias
  dev/shim/dune
Labels: kind: infrastructure

#16626 Do not rely on case expansion in VM and Native reification
  pretyping/nativenorm.ml
  pretyping/vnorm.ml
Labels: kind: cleanup

#16658 [coqdep] Be more deterministic w.r.t. the plugin loading mode
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/fl.ml
  tools/coqdep/lib/fl.mli
Labels: kind: infrastructure, part: coqdep

#16676 fix coqdep not recognizing ignore import_categories syntax
  test-suite/misc/coqdep-require-filter-categories/fD.v
  test-suite/misc/coqdep-require-filter-categories/fE.v
  test-suite/misc/coqdep-require-filter-categories/fF.v
  test-suite/misc/coqdep-require-filter-categories/fG.v
  test-suite/misc/coqdep-require-filter-categories/stdout.ref
  tools/coqdep/lib/lexer.mll
Labels: kind: fix

#16570 [dev] shorten names of shims
  Makefile
  dev/doc/build-system.dune.md
  dev/include
  dev/shim/dune
  dev/tools/coqdev.el
Labels: kind: infrastructure

#16536 Put Ltac2.Bool notations in a separate module
  doc/changelog/06-Ltac2-language/16536-bool-notations-submodule.rst
  user-contrib/Ltac2/Bool.v
Labels: kind: enhancement, part: ltac2

#16694 Remove an outdated comment from `kernel/constr.ml`
  kernel/constr.ml
Labels: kind: documentation, part: kernel

#16594 [build] Unify worker binaries.
  dev/shim/dune
  lib/spawn.ml
  stm/asyncTaskQueue.ml
  stm/partac.ml
  stm/stm.ml
  topbin/coqqueryworker_bin.ml
  topbin/coqtacticworker_bin.ml
  topbin/coqworker_bin.ml
  topbin/dune
  toplevel/workerLoop.ml
  toplevel/workerLoop.mli
Labels: kind: cleanup, kind: performance, part: build

#16669 CI: set default timeout
  .gitlab-ci.yml
  dev/bench/gitlab-bench.yml
Labels: kind: infrastructure

#16407 Deprecated undocumented and unused `>` clear modifier.
  doc/changelog/04-tactics/16407-deprecate-keep-clear.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_tactic.mlg
Labels: kind: cleanup

#16552 Ltac2 record update syntax
  doc/changelog/06-Ltac2-language/16552-tac2-default-record.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2quote.ml
  test-suite/ltac2/default_record.v
Labels: kind: enhancement, part: ltac2

#16656 Remove the Vuniv_level constructor of VM value kinds.
  dev/vm_printers.ml
  kernel/vconv.ml
  kernel/vm.ml
  kernel/vmvalues.ml
  kernel/vmvalues.mli
  pretyping/vnorm.ml
Labels: kind: cleanup

#16688 Windows CI: use coq-ci branch from Platform.
  .github/workflows/ci-windows.yml
Labels: kind: infrastructure, platform: Windows, part: CI

#16695 Set soft ulimit in bench
  dev/bench/bench.sh
Labels: kind: infrastructure

#16691 Remove unused arguments to record.ml internal functions
  vernac/record.ml
Labels: kind: cleanup

#16699 coqworker: worker names are not mutable
  stm/asyncTaskQueue.ml
  stm/asyncTaskQueue.mli
  stm/partac.ml
  stm/stm.ml
Labels: kind: cleanup

#16696 Uniform naming scheme for VM kind views
  dev/vm_printers.ml
  kernel/vconv.ml
  kernel/vm.ml
  kernel/vmvalues.ml
  kernel/vmvalues.mli
  pretyping/vnorm.ml
Labels: kind: cleanup

#16665 [coqchk] support for -boot flag
  checker/checker.ml
Labels: part: checker, kind: enhancement

#15780 [rewrite] Revert commenting of `Params` instance in Morphisms from #13969
  test-suite/misc/universes.sh
  theories/Classes/Morphisms.v
Labels: kind: fix, kind: performance

#16678 Move CoqworkmgrApi out of stm to it own library
  stm/dune
  tools/coqworkmgr/coqworkmgr.ml
  tools/coqworkmgr/coqworkmgrApi.ml
  tools/coqworkmgr/coqworkmgrApi.mli
  tools/coqworkmgr/dune
  tools/dune
Labels: kind: cleanup, part: build

#14966 [dumpglob] Document the [.glob] file format.
  interp/dumpglob.mli
Labels: kind: documentation

#16697 Move the Prod case from native atoms to values.
  kernel/nativecode.ml
  kernel/nativeconv.ml
  kernel/nativevalues.ml
  kernel/nativevalues.mli
  pretyping/nativenorm.ml
Labels: kind: cleanup, part: native compiler

#16704 Partac: don't drop critical exceptions
  stm/partac.ml
Labels: kind: fix

#16711 Fix coqworker spawning on windows
  lib/spawn.ml
Labels: kind: fix

#16705 Small simplification of Evd.evar_filtered_env
  engine/evd.ml
Labels: kind: cleanup

#16703 Correctly perform the fast-path in Evarsolve.invert_definition.
  pretyping/evarsolve.ml
Labels: kind: performance

#16712 dune_rule_gen: stop considering .aux as targets
  tools/dune_rule_gen/coq_module.ml
Labels: kind: cleanup

#16717 Fix coqworker spawning on windows part 2
  lib/spawn.ml
Labels: kind: fix

#16719 Try to be resistant to zulip failures
  dev/bench/bench.sh
Labels: kind: infrastructure

#16714 Delete md5sum.ml
  tools/md5sum.ml
Labels: kind: cleanup

#16493 Ltac2: redundant pattern warning for general patterns
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2interp.ml
  plugins/ltac2/tac2print.ml
  test-suite/bugs/bug_14135.v
  test-suite/output/ltac2_match.out
  test-suite/output/ltac2_match.v
Labels: kind: user messages, part: ltac2

#16667 Hooks have no default value
  engine/evd.ml
  lib/hook.ml
  lib/hook.mli
  pretyping/evarconv.ml
  stm/stm.ml
  stm/stm.mli
Labels: kind: cleanup

#16710 Make the evar_info type private.
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  plugins/ssrmatching/ssrmatching.ml
  pretyping/evarsolve.ml
  pretyping/globEnv.ml
Labels: kind: cleanup

#16713 Fast path in evar-evar unification.
  clib/sList.ml
  clib/sList.mli
  engine/evd.ml
  pretyping/evarsolve.ml
Labels: kind: internal

#16724 Stop printing findlib paths on Dynlink errors
  vernac/mltop.ml
Labels: kind: user messages

#16690 Replace undocumented `Print TypeClasses` with `Print Typeclasses`
  doc/changelog/08-vernac-commands-and-options/16690-master.rst
  doc/sphinx/addendum/type-classes.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup

#16722 Refine the evar-evar fast path criterion in Evarsolve.
  clib/sList.ml
  clib/sList.mli
  pretyping/evarsolve.ml
Labels: kind: performance

#16736 Clarify that for now, only classic projects are supported for backporting.
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#16721 Remove a dubious use of Evd.add in ComProgramFixpoint.
  vernac/comProgramFixpoint.ml
  vernac/retrieveObl.ml
  vernac/retrieveObl.mli
Labels: kind: cleanup

#16737 Remove Evarutil.non_instantiated
  engine/evarutil.ml
  engine/evarutil.mli
  vernac/retrieveObl.ml
Labels: kind: cleanup

#16741 Fix typos
  doc/sphinx/addendum/micromega.rst
Labels: kind: documentation

#16750 Fix outdated reference to coq-bench repo
  dev/ci/README-users.md
Labels: kind: documentation

#16730 Remove the simplistic Evd.make_evar function.
  engine/evd.ml
  engine/evd.mli
  vernac/declare.ml
Labels: kind: cleanup

#16723 [ssr] do not solve TC when generating have proof term (fix #16720)
  plugins/ssr/ssrfwd.ml
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/ssr/bug_16720.v
Labels: kind: fix

#16753 Remove nonsense sentence in doc for refine
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#16747 Fix definitional classes with letin parameter
  test-suite/bugs/bug_16744.v
  vernac/record.ml
Labels: kind: fix

#16727 setoid-rewrite: Supply correct env in `mk_relty`
  tactics/rewrite.ml
  test-suite/bugs/bug_16727.v
Labels: kind: fix
