Repository rocq-prover/rocq, pull requests merged in 2022-01, with the labels that each got.

#15344 Renaming syntax_def.ml into abbreviation.ml
  dev/base_include
  dev/ci/user-overlays/15344-herbelin-master+renaming-syntax_def.ml-abbreviation.ml.sh
  dev/ci/user-overlays/15344-herbelin-renaming-syntax_def.ml-abbreviation.ml.sh
  interp/abbreviation.ml
  interp/abbreviation.mli
  interp/constrextern.ml
  interp/constrextern.mli
  interp/constrintern.ml
  interp/constrintern.mli
  interp/dumpglob.ml
  interp/notation.ml
  interp/notation.mli
  interp/notation_term.ml
  interp/smartlocate.ml
  interp/syntax_def.ml
  library/globnames.ml
  library/globnames.mli
  library/nametab.ml
  library/nametab.mli
  plugins/syntax/number.ml
  tools/coqdoc/glob_file.ml
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#15421 doc: IF is not a keyword
  doc/sphinx/language/core/basic.rst
Labels: kind: fix, kind: documentation

#15368 [ssr] ignore shelving of unresolved TC in views
  plugins/ssr/ssrview.ml
  test-suite/ssr/tcfwd.v
Labels: kind: fix

#15406 Share the hashconsing table between Constant and Inductive.
  kernel/names.ml
Labels: kind: cleanup, kind: performance

#14880 Share hashing and hashconsing in lists.
  clib/hashcons.ml
  clib/hashcons.mli
  kernel/names.ml
  kernel/univ.ml
Labels: kind: cleanup

#15414 Reduce the use of `Global` functions
  dev/ci/user-overlays/15414-ppedrot-reduce-global-use.sh
  doc/plugin_tutorial/tuto3/src/construction_game.ml
  doc/plugin_tutorial/tuto3/src/g_tuto3.mlg
  engine/evarutil.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/functional_principles_types.ml
  plugins/funind/functional_principles_types.mli
  plugins/funind/gen_principle.ml
  plugins/funind/recdef.ml
  plugins/ltac/rewrite.ml
  pretyping/cases.ml
  pretyping/coercion.ml
  pretyping/detyping.ml
  pretyping/program.ml
  pretyping/program.mli
Labels: kind: cleanup

#15411 [stdlib] [Arith] Integrate deprecated results from Arith.Even and Arith.Div2
  doc/changelog/10-standard-library/14736-Arith2.rst
  theories/Arith/Arith_prebase.v
  theories/Arith/Div2.v
  theories/Arith/Even.v
  theories/Arith/Gt.v
  theories/Arith/Le.v
  theories/Arith/Mult.v
  theories/Arith/PeanoNat.v
  theories/Arith/Plus.v
Labels: kind: cleanup, part: standard library

#15416 Simplify the ssr code
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssr/ssripats.ml
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
Labels: kind: cleanup

#15405 Remove the flashbar display for found strings in CoqIDE.
  ide/coqide/wg_Find.ml
Labels: kind: fix, part: IDE

#15397 [List] Add count_occ_rev
  doc/changelog/10-standard-library/15397-count_occ_rev.rst
  theories/Lists/List.v
Labels: part: standard library, kind: enhancement

#15427 [stdlib] [PeanoNat] Add EvenT and OddT (Even and Odd in Type)
  doc/changelog/10-standard-library/15427-Arith3.rst
  theories/Arith/PeanoNat.v
Labels: kind: feature, part: standard library

#15433 Fast path in the Evarsolve computation of distinct aliasing check.
  pretyping/evarsolve.ml
Labels: kind: performance

#15429 Set -coqlib in dune coqdoc invocation
  doc/stdlib/dune
Labels: kind: infrastructure, part: build

#15415 Clean Printer internals
  printing/printer.ml
Labels: kind: cleanup, part: printer

#15407 Parameterize the Evarutil naming flag with the rigid set of identifiers.
  dev/ci/user-overlays/15407-ppedrot-evarutil-precise-naming-mode.sh
  engine/evarutil.ml
  engine/evarutil.mli
  pretyping/cases.ml
  pretyping/pretyping.ml
  proofs/clenv.ml
Labels: kind: cleanup

#15412 Fixes #15403: inlining not propagated along aliases of module paths in delta-resolver
  doc/changelog/01-kernel/15412-master+fix15403-missing-inlining-resolver-composition.rst
  kernel/mod_subst.ml
  test-suite/bugs/bug_15403.v
Labels: kind: fix, part: modules

#15419 Simplify the internal state of eauto
  tactics/eauto.ml
Labels: kind: cleanup

#15437 added #3810 to test-suite
  test-suite/output/bug_3810.out
  test-suite/output/bug_3810.v
Labels: kind: infrastructure, part: test-suite

#15430 Cleanup unknown argument handling in coqdoc
  Makefile.doc
  tools/coqdoc/main.ml
Labels: kind: cleanup, part: coqdoc

#15456 Fixes #15455: regression due to #14606 in computing best implicit arguments signature for projections
  interp/impargs.ml
  test-suite/bugs/bug_15455.v
Labels: kind: fix, part: implicit arguments

#15446 [stdlib] [CMorphisms] rename scope signature into signatureT
  dev/ci/user-overlays/15446-olaure01-signatureT.sh
  doc/changelog/10-standard-library/15446-signatureT.rst
  test-suite/output/signatureT.out
  test-suite/output/signatureT.v
  theories/Classes/CEquivalence.v
  theories/Classes/CMorphisms.v
Labels: part: standard library, part: notations, kind: enhancement

#15449 Better implementation for micromega proof compaction
  plugins/micromega/coq_micromega.ml
Labels: kind: cleanup, kind: performance

#15450 [ssr] intern/interp all ipats (including equation name)
  plugins/ssr/ssrparser.mlg
  test-suite/ssr/caseeqltac.v
Labels: kind: fix

#15462 Add metacoq to bench packages
  dev/bench/bench.sh
Labels: kind: infrastructure

#15296 Bench plotter script
  dev/bench/plotter
Labels: kind: internal

#15460 A note in reference manual on the implicit status of main argument of t.(f) notation
  doc/sphinx/language/core/records.rst
Labels: kind: documentation, part: implicit arguments

#15439 Release summary for Coq 8.15
  .mailmap
  doc/sphinx/changes.rst
Labels: kind: documentation

#12640 Use local persistent data structures for VM global tables
  dev/vm_printers.ml
  kernel/byterun/coq_interp.c
  kernel/byterun/coq_interp.h
  kernel/vm.ml
  kernel/vmbytecodes.ml
  kernel/vmbytecodes.mli
  kernel/vmbytegen.ml
  kernel/vmbytegen.mli
  kernel/vmemitcodes.ml
  kernel/vmemitcodes.mli
  kernel/vmsymtable.ml
  kernel/vmsymtable.mli
  kernel/vmvalues.ml
  kernel/vmvalues.mli
  tactics/redexpr.ml
Labels: kind: cleanup, part: VM

#15366 Command Fail not catching anomalies
  doc/changelog/07-vernac-commands-and-options/15366-master+Fail-not-catching-anomaly.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  vernac/vernacinterp.ml
Labels: kind: redesign, kind: feature

#14138 Fix bug #13618: too restrictive recognition of homogeneous relations
  doc/changelog/04-tactics/14138-fix-recognition-of-homogeneous-relations.rst
  plugins/ltac/rewrite.ml
  test-suite/bugs/bug_13618.v
Labels: kind: fix, part: rewriting tactics

#15454 Use the new representation in old unification on Case / Case problems.
  pretyping/unification.ml
Labels: kind: cleanup

#15465 Add a box and align items of the ( x , y , .. , z ) and [ x ; y ; .. ; z ] notations
  test-suite/output/StringSyntax.out
  theories/Init/Notations.v
  theories/Lists/List.v
Labels: part: standard library, kind: enhancement

#15472 Integrate new 8.15 changes to changes.rst
  doc/changelog/01-kernel/15385-master+fix-bug9555-subst-module-type-wrongly-over-functor.rst
  doc/changelog/03-notations/15338-master+fix15334-parsing-failure-on-empty-grammar.rst
  doc/changelog/03-notations/15340-master+fix15335-entry-coercions-respect-only-parsing.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#15473 Fix generate-release-changelog deleting title files
  dev/tools/generate-release-changelog.sh
Labels: kind: fix, kind: infrastructure

#15477 Fix test suite
  test-suite/bugs/bug_6278.v
  test-suite/success/setoid_test.v
Labels: kind: fix

#15458 uin `ssrbool.v`, renamed `mono2W_in` to `mono1W_in` (was misnamed).
  theories/ssr/ssrbool.v
Labels: kind: fix

#15468 `add_notation_interpretation` should not add syntax rules
  vernac/metasyntax.ml
Labels: kind: cleanup

#15386 Fixes #9579 about locally corrupted functorial algebraic form of module type + inconsistencies in taking inline levels into account
  kernel/entries.ml
  kernel/mod_typing.ml
  test-suite/modules/inlining.v
  vernac/declaremods.ml
Labels: kind: fix, part: modules

#15483 Update zarith 1.10 -> 1.12
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#15478 Simplify the ssrmatching implementation
  plugins/ssr/ssrequality.ml
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
  test-suite/bugs/bug_15469.v
Labels: kind: cleanup

#15480 Set the universe context in Ssrequality.rwargtac instead of merging.
  plugins/ssr/ssrequality.ml
Labels: kind: cleanup, part: ssreflect, part: universes

#14563 Adding user support for naming a variable inhabiting a record type
  dev/ci/user-overlays/14563-herbelin-master+record-with-default-variable-name.sh
  doc/changelog/02-specification-language/14563-master+record-with-default-variable-name.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/records.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  test-suite/output/InductiveMainName.out
  test-suite/output/InductiveMainName.v
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/record.ml
  vernac/record.mli
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: enhancement, part: primitive records

#15442 Make the program naming scheme uniform w.r.t. the standard one.
  doc/changelog/07-vernac-commands-and-options/15442-deprecate-program-naming-mode.rst
  doc/sphinx/addendum/program.rst
  engine/evarutil.ml
  test-suite/bugs/bug_1784.v
  test-suite/bugs/bug_2083.v
  test-suite/bugs/bug_4280.v
  test-suite/success/ProgramWf.v
  theories/Compat/Coq815.v
Labels: kind: cleanup

#15488 Remove Eauto.registered_e_assumption.
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/eauto.mli
Labels: kind: cleanup

#15485 Consistently adding periods in error messages raised in vernac
  vernac/record.ml
  vernac/vernacentries.ml
  vernac/vernacextend.ml
Labels: kind: user messages

#15438 Rely on the new case representation in Evarsolve.
  pretyping/evarconv.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
Labels: kind: cleanup

#15459 [opam] honor coq-native
  coq-core.opam
  coq-core.opam.template
Labels: kind: infrastructure

#15390 Port `eauto` to the new engine
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup, part: auto

#14759 Improve function napply_except_last, fix its description comment
  theories/Numbers/NaryFunctions.v
Labels: kind: redesign, part: standard library

#15358 Avoid bound names in instantiate_notation_constr
  interp/constrintern.ml
  test-suite/bugs/bug_15356.v
Labels: kind: cleanup

#15461 Explain details of "only" selector
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation

#15484 Stronger invariants on the syntax of records and variants
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/core/variants.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  kernel/indtypes.ml
  test-suite/success/Record.v
  vernac/declareInd.ml
  vernac/g_vernac.mlg
  vernac/printmod.ml
Labels: kind: cleanup, kind: enhancement, part: records, part: inductives

#15466 Delay the merging of universes for type compatibility in old unification.
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/unification.ml
Labels: kind: enhancement, part: universes

#15464 Restore compilation of the bytecode interpreter with OCaml 5.00.
  kernel/byterun/coq_fix_code.c
  kernel/byterun/coq_interp.c
  kernel/byterun/coq_memory.c
Labels: part: VM, kind: compatibility

#13969 Fix bug #7916, allowing `Reflexive` to have mode `! !`
  dev/ci/user-overlays/13969-mattam82-rewrite-reflexive-mode.sh
  doc/changelog/04-tactics/13969-allow-reflexive-mode.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  plugins/ltac/rewrite.ml
  tactics/class_tactics.ml
  test-suite/bugs/bug_7916.v
  test-suite/success/Typeclasses.v
  theories/Classes/Morphisms.v
  theories/Classes/RelationClasses.v
  theories/Classes/SetoidTactics.v
Labels: kind: fix, part: typeclasses

#15502 Fix setoid_rewrite on Equiv : Type -> Type -> Type
  .ocp-indent
  plugins/ltac/rewrite.ml
  test-suite/bugs/bug_6278.v
Labels: kind: fix

#15378 Understand goal selectors in ltac2
  doc/changelog/05-tactic-language/15378-tac2select.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  test-suite/ltac2/goal_select.v
Labels: kind: feature

#15515 Moving file in obsolete doc/changelog/08-tools change log directory to a more appropriate change log directory
  doc/changelog/12-misc/13460-master+fix-ocaml-int-extraction-clash.rst
Labels: kind: infrastructure

#15507 Check existence of the name in Declare.CInfo.start_core
  test-suite/bugs/bug_15031.v
  vernac/declare.ml
Labels: kind: fix, part: vernac

#15470 Slightly clean the Printing Existential Instances code
  dev/top_printers.ml
  interp/constrextern.ml
  interp/constrextern.mli
  pretyping/detyping.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, part: printer

#15509 [CI] [flocq] Also install glob files
  dev/ci/ci-flocq.sh
Labels: kind: fix, kind: infrastructure, part: CI

#15505 Avoid using is_ground_env in evarconv
  pretyping/evarconv.ml
Labels: kind: cleanup

#15535 Split github CI actions into 2 workflows + disable windows while it's broken
  .github/workflows/ci-macos.yml
  .github/workflows/ci-windows.yml.disabled
Labels: kind: infrastructure, part: CI

#15479 Remove "open Coercion" in unification.ml (used for 1 line)
  pretyping/unification.ml
Labels: kind: internal

#15532 Fix incorrect line numbers in Errors panel
  doc/changelog/09-coqide/15532-error_line_nos.rst
  ide/coqide/coqOps.ml
Labels: kind: fix, part: IDE

#15511 Fixes #15497: deactivate glob dumping while executing Load
  doc/changelog/08-cli-tools/15511-master+fix15497-no-dumpglob-while-loading.rst
  interp/dumpglob.ml
  interp/dumpglob.mli
  vernac/vernacinterp.ml
Labels: kind: fix, part: coqdoc

#15533 Remove the only call to the OCaml Ephemeron API.
  engine/evarutil.ml
Labels: kind: cleanup

#15514 Use folding sections in gitlab CI + remove useless set -e
  .gitlab-ci.yml
  dev/ci/gitlab-section.sh
Labels: kind: infrastructure

#15546 Document rewrite_db
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation

#15501 Concentrate the Clenv code in Equality.
  engine/evd.ml
  engine/evd.mli
  pretyping/unification.ml
  pretyping/unification.mli
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/equality.ml
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/bugs/bug_15501.v
Labels: kind: cleanup

#15543 Add coq-category-theory to bench
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#15542 Make the bytecode interpreter more resilient to exceptions.
  kernel/byterun/coq_interp.c
Labels: kind: fix, part: VM

#14740 Split Scheme Equality into own vernac + misc cleanup
  dev/ci/user-overlays/14740-alizter-alizter+split-scheme-vernac.sh
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  vernac/g_vernac.mlg
  vernac/indschemes.ml
  vernac/indschemes.mli
  vernac/ppvernac.ml
  vernac/ppvernac.mli
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: fix, kind: cleanup, part: scheme

#15550 Mention Coqtail in refman
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
Labels: kind: documentation

#15556 minor fixes after merge of #14740
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
Labels: kind: documentation, part: scheme

#15551 [CI] CI for paco
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-paco.sh
Labels: kind: infrastructure, part: CI

#15404 Mostly cosmetic changes to hopefully make kernel code on modules easier to read
  checker/mod_checking.ml
  dev/top_printers.ml
  kernel/declareops.ml
  kernel/inductive.ml
  kernel/mod_subst.ml
  kernel/mod_typing.ml
  kernel/mod_typing.mli
  kernel/modops.ml
  kernel/modops.mli
  kernel/names.ml
  kernel/names.mli
  kernel/safe_typing.ml
  kernel/subtyping.ml
  plugins/extraction/table.ml
  plugins/ssr/ssrequality.ml
  tactics/cbn.ml
  tactics/equality.ml
  vernac/assumptions.ml
  vernac/declaremods.ml
Labels: kind: cleanup, part: modules

#15498 Fixes #15451: incompletenesses in guard condition regarding cofix and primitive projections
  doc/changelog/01-kernel/15498-master+fix15451-incompleteness-guard-condition.rst
  kernel/inductive.ml
  test-suite/bugs/bug_15451.v
Labels: kind: fix, part: kernel, part: inductives

#15530 Workaround for stale data appearing in variables panel when there are 0 items
  ide/coqide/wg_Debugger.ml
Labels: kind: fix, part: ltac debugger

#15570 Fix STM classification of Ltac2 Eval: should be query
  plugins/ltac2/g_ltac2.mlg
  test-suite/bugs/bug_15569.v
Labels: kind: fix

#15506 Legacy build: remove nonsense `byte` target and noop `install-byte`
  .github/workflows/ci-macos.yml
  Makefile.build
  Makefile.install
  Makefile.make
  coq.opam.docker
  default.nix
Labels: kind: infrastructure, kind: internal

#15566 Errors from decompose_lam_n_assum & cie should be anomalies
  engine/eConstr.ml
  kernel/term.ml
Labels: kind: cleanup

#15526 Adding Scheme Boolean Equality to produce Boolean equality w/o full decidability
  doc/changelog/07-vernac-commands-and-options/15526-master+adding-specific-scheme-boolean-equality.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  vernac/g_vernac.mlg
  vernac/indschemes.ml
  vernac/indschemes.mli
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: enhancement, part: scheme

#15576 Inform dune that autoconfigure depends on PWD
  config/dune
Labels: kind: fix, kind: infrastructure
