Repository rocq-prover/rocq, pull requests merged in 2022-06, with the labels that each got.

#16113 Remove CClosure stats infrastructure
  kernel/cClosure.ml
  kernel/cClosure.mli
  pretyping/cbv.ml
Labels: kind: cleanup

#16114 [8.16] [mltop] Improve and fix the legacy plugin loading method.
  dev/ci/ci-basic-overlay.sh
  dev/doc/changes.md
  lib/cErrors.ml
  library/summary.ml
  library/summary.mli
  sysinit/coqloadpath.ml
  test-suite/coq-makefile/coqdoc1/run.sh
  test-suite/coq-makefile/coqdoc2/run.sh
  test-suite/coq-makefile/mlpack1/run.sh
  test-suite/coq-makefile/mlpack2/run.sh
  test-suite/coq-makefile/multiroot/run.sh
  test-suite/coq-makefile/native1/run.sh
  test-suite/coq-makefile/native2/run.sh
  test-suite/coq-makefile/native3/run.sh
  test-suite/coq-makefile/native4/run.sh
  test-suite/coq-makefile/plugin1/run.sh
  test-suite/coq-makefile/plugin2/run.sh
  test-suite/coq-makefile/plugin3/run.sh
  test-suite/micromega/witness_tactics.v
  theories/Init/Byte.v
  theories/Init/Ltac.v
  theories/Init/Prelude.v
  theories/Init/Tauto.v
  theories/btauto/Btauto.v
  theories/derive/Derive.v
  theories/extraction/Extraction.v
  theories/funind/FunInd.v
  theories/micromega/Lia.v
  theories/micromega/Lqa.v
  theories/micromega/Lra.v
  theories/micromega/Psatz.v
  theories/micromega/QMicromega.v
  theories/micromega/RMicromega.v
  theories/micromega/ZMicromega.v
  theories/micromega/Zify.v
  theories/micromega/ZifyInst.v
  theories/nsatz/NsatzTactic.v
  theories/rtauto/Rtauto.v
  theories/setoid_ring/Ring_base.v
  theories/setoid_ring/Ring_tac.v
  theories/ssr/ssreflect.v
  theories/ssrmatching/ssrmatching.v
  tools/CoqMakefile.in
  tools/coqdep/common.ml
  topbin/coqtop_byte_bin.ml
  user-contrib/Ltac2/Init.v
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: fix

#16123 Commit for 8.16+rc1.
  tools/configure/configure.ml
Labels: kind: infrastructure

#16107 Stop inferring template universes in the kernel
  kernel/indTyping.ml
  test-suite/bugs/bug_11039.v
  test-suite/output/Inductive.v
  test-suite/output/PrimitiveProjectionsAttribute_Records.out
  test-suite/success/Template.v
  theories/ssr/ssrbool.v
  theories/ssr/ssreflect.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
Labels: kind: cleanup

#16124 Locate UniverseLengthMismatch errors
  engine/univGen.ml
  pretyping/pretyping.ml
Labels: kind: user messages

#16078 [coqdep] Remove unhandled Add LoadPath Code
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/lexer.mli
  tools/coqdep/lib/lexer.mll
Labels: kind: cleanup, part: build, part: coqdep

#16109 Use a proper printing handler for a setoid rewrite error.
  tactics/rewrite.ml
Labels: kind: cleanup

#16106 `Ltac ::=`: respect `Local`
  doc/changelog/05-tactic-language/16106-local-ltac-redef.rst
  doc/sphinx/proof-engine/ltac.rst
  plugins/ltac/tacenv.ml
  test-suite/success/ltac.v
Labels: kind: fix

#16070 Improve CoqIDE documentation
  doc/changelog/09-coqide/16070-coqide_async_doc.rst
  doc/sphinx/_static/async-mode.png
  doc/sphinx/addendum/parallel-proof-processing.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/practical-tools/coqide.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
Labels: kind: documentation, part: IDE

#16023 Ltac2 deep matches (unoptimized interpretation)
  doc/changelog/05-tactic-language/16023-tac2match.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  lib/cAst.ml
  lib/cAst.mli
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2interp.ml
  plugins/ltac2/tac2print.ml
  plugins/ltac2/tac2print.mli
  test-suite/ltac2/matching.v
Labels: kind: feature, part: ltac2

#16073 [build] [mltop] Distinguish plugin loading API from module loading API
  lib/cErrors.ml
  test-suite/micromega/witness_tactics.v
  theories/Init/Byte.v
  theories/Init/Ltac.v
  theories/Init/Prelude.v
  theories/Init/Tauto.v
  theories/btauto/Btauto.v
  theories/derive/Derive.v
  theories/extraction/Extraction.v
  theories/funind/FunInd.v
  theories/micromega/Lia.v
  theories/micromega/Lqa.v
  theories/micromega/Lra.v
  theories/micromega/Psatz.v
  theories/micromega/QMicromega.v
  theories/micromega/RMicromega.v
  theories/micromega/ZMicromega.v
  theories/micromega/Zify.v
  theories/micromega/ZifyInst.v
  theories/nsatz/NsatzTactic.v
  theories/rtauto/Rtauto.v
  theories/setoid_ring/Ring_base.v
  theories/setoid_ring/Ring_tac.v
  theories/ssr/ssreflect.v
  theories/ssrmatching/ssrmatching.v
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/error.ml
  topbin/coqtop_byte_bin.ml
  user-contrib/Ltac2/Init.v
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: user messages, part: build, kind: internal, part: coqdep

#16154 CI: allow_failure for fiat_crypto_ocaml
  .gitlab-ci.yml
Labels: kind: infrastructure

#16122 Disable warning 40 (Constructor or label name used out of scope)
  dev/doc/style.txt
  dune
  kernel/dune
  vernac/vernacentries.ml
  vernac/vernacextend.ml
Labels: kind: infrastructure, kind: internal

#16137 Improve dev changelog
  dev/doc/changes.md
Labels: kind: documentation, part: build

#16135 Warn for unused var in pattern even when catching a single case
  doc/changelog/02-specification-language/16135-warn_unused_pattern.rst
  doc/sphinx/language/extensions/match.rst
  pretyping/cases.ml
  test-suite/output/Cases.out
  test-suite/output/Notations.v
  theories/Floats/SpecFloat.v
  theories/Lists/List.v
Labels: kind: user messages

#16088 Fast path in hnf_constr
  pretyping/tacred.ml
  pretyping/tacred.mli
  tactics/equality.ml
  tactics/hints.ml
Labels: kind: performance

#16159 Disable warning 40 in configure
  tools/configure/configure.ml
Labels: kind: infrastructure

#16143 Tweaks on key bindings doc
  doc/sphinx/practical-tools/coqide.rst
Labels: kind: documentation, part: IDE

#16166 fixed congruence regression #16140 in 8.16
  plugins/cc/cctac.ml
  test-suite/bugs/bug_16140.v
Labels: kind: fix

#16128 Statically enforce internal invariants on rewrite functions.
  tactics/equality.ml
Labels: kind: cleanup

#16131 Add linebreaking to long error message (ComAssumption.maybe_error_many_udecls)
  test-suite/output/UnivBinders.out
  vernac/comAssumption.ml
Labels: kind: user messages

#16155 CI: remove allow_failure from fiat_crypto_ocaml
  .gitlab-ci.yml
Labels: kind: infrastructure

#16145 Fix occurence state passing in find_subterm
  pretyping/find_subterm.ml
  test-suite/bugs/bug_16144.v
Labels: kind: fix

#16129 Tolerate repeated univ names in Print/About
  engine/uState.ml
  engine/uState.mli
  printing/printer.ml
  printing/printer.mli
  test-suite/output/UnivBinders.out
  test-suite/output/UnivBinders.v
  vernac/himsg.ml
  vernac/prettyp.ml
  vernac/printmod.ml
Labels: kind: fix

#16158 Backport MathComp PRs #872 #874
  doc/changelog/06-ssreflect/16158-backport_mc_872_874.rst
  theories/ssr/ssrbool.v
  theories/ssr/ssrfun.v
Labels: part: ssreflect, kind: enhancement

#16160 Remove the last remnants of the V82 module and their mentions.
  dev/doc/coq-src-description.txt
  engine/proofview.ml
  engine/proofview.mli
  test-suite/bugs/bug_2969.v
Labels: kind: cleanup

#16156 Document intuition_solver for 8.15
  doc/sphinx/proofs/automatic-tactics/logic.rst
Labels: kind: documentation

#16162 [bench] Replace Stdlib.List with Clib.CList to use tail-recursion
  dev/bench/dune
  dev/bench/render_line_results.ml
  dev/bench/render_results.ml
  dev/bench/table.ml
Labels: kind: infrastructure, part: bench

#16147 [coqdev.el] Don't error if `ocamldebug` is not present.
  dev/tools/coqdev.el
Labels: kind: infrastructure

#16178 Document intuition_solver for 8.16
  doc/sphinx/proofs/automatic-tactics/logic.rst
Labels: kind: documentation

#16187 [build] Use public names in `(libraries` for stdlib
  theories/dune
Labels: kind: infrastructure

#16184 added Nat.le_add_l
  doc/changelog/10-standard-library/16184-dropin_nat.rst
  theories/Arith/Arith_prebase.v
  theories/Arith/Plus.v
  theories/FSets/FSetProperties.v
  theories/MSets/MSetProperties.v
  theories/Numbers/DecimalFacts.v
  theories/Numbers/HexadecimalFacts.v
  theories/Numbers/Natural/Abstract/NAddOrder.v
  theories/Reals/SeqSeries.v
  theories/funind/Recdef.v
Labels: kind: feature, part: standard library

#16118 [build] Bump minimal Dune required version to 2.9
  .github/workflows/ci-macos.yml
  .gitlab-ci.yml
  INSTALL.md
  Makefile.install
  coq-core.opam
  coq-doc.opam
  coq-stdlib.opam
  coq.opam
  coq.opam.docker
  coqide-server.opam
  coqide.opam
  dev/ci/docker/bionic_coq/Dockerfile
  doc/changelog/11-infrastructure-and-dependencies/16118-build+bump_dune.rst
  dune-project
  kernel/byterun/dune
  theories/dune
  tools/configure/configure.ml
Labels: kind: infrastructure, part: build

#15807 Delay Universe Substitution in CClosure
  dev/bench/bench.sh
  dev/ci/user-overlays/15807-SkySkimmer-delayed_univs.sh
  interp/impargs.ml
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/inferCumulativity.ml
  kernel/reduction.ml
  kernel/typeops.ml
  kernel/vars.ml
  plugins/ring/ring.ml
Labels: kind: performance, part: universes

#16090 Sort entries when writing coqide.keys file
  ide/coqide/preferences.ml
Labels: part: IDE, kind: enhancement, kind: usability

#16188 Use Typing.type_of less in tactics.ml
  pretyping/typing.ml
  pretyping/typing.mli
  tactics/tactics.ml
Labels: kind: cleanup, kind: performance

#16205 Add test for #16204
  test-suite/bugs/bug_16204.v
Labels: kind: infrastructure, part: universes

#16195 CI: Add lean importer
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-lean_importer.sh
Labels: kind: infrastructure

#16115 [doc] [mltop] Improve documentation of Declare ML Module for 8.16
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#16130 Print less trailing spaces in `Print`
  proofs/miscprint.ml
  test-suite/output/Arguments.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/Cases.out
  test-suite/output/Notations3.out
  test-suite/output/PatternsInBinders.out
  test-suite/output/PrintInfos.out
  test-suite/output/PrintingParentheses.out
  test-suite/output/Projections.out
  test-suite/output/StringSyntax.out
  test-suite/output/UnivBinders.out
  test-suite/output/bug_11934.out
  test-suite/output/bug_14815.out
  test-suite/output/inference.out
  vernac/prettyp.ml
Labels: kind: user messages

#16196 Remove internal CClosure.Mark indirection
  kernel/cClosure.ml
Labels: kind: cleanup

#16192 Add release step to produce alpha Docker images.
  dev/doc/release-process.md
Labels: kind: meta

#16084 Proof engine doc
  dev/doc/proof-engine.md
Labels: kind: internal

#16026 `Ltac intuition_solver`: warn if `auto with *` was needed
  doc/changelog/04-tactics/16026-intuition-with-core.rst
  doc/sphinx/proofs/automatic-tactics/logic.rst
  plugins/ltac/tauto.ml
  theories/Arith/Le.v
  theories/Bool/Bool.v
  theories/Bool/BoolOrder.v
  theories/Classes/CMorphisms.v
  theories/Classes/CRelationClasses.v
  theories/Classes/Equivalence.v
  theories/Classes/Morphisms.v
  theories/Classes/RelationClasses.v
  theories/FSets/FMapAVL.v
  theories/FSets/FMapFacts.v
  theories/FSets/FMapList.v
  theories/FSets/FSetBridge.v
  theories/FSets/FSetCompat.v
  theories/FSets/FSetDecide.v
  theories/FSets/FSetEqProperties.v
  theories/FSets/FSetFacts.v
  theories/FSets/FSetProperties.v
  theories/Init/Tauto.v
  theories/Lists/List.v
  theories/Lists/SetoidList.v
  theories/Lists/SetoidPermutation.v
  theories/MSets/MSetAVL.v
  theories/MSets/MSetDecide.v
  theories/MSets/MSetEqProperties.v
  theories/MSets/MSetFacts.v
  theories/MSets/MSetGenTree.v
  theories/MSets/MSetList.v
  theories/MSets/MSetProperties.v
  theories/MSets/MSetWeakList.v
  theories/Numbers/Integer/Abstract/ZDivEucl.v
  theories/Numbers/Integer/Abstract/ZDivFloor.v
  theories/Numbers/NatInt/NZDiv.v
  theories/Numbers/NatInt/NZOrder.v
  theories/Numbers/Natural/Abstract/NAdd.v
  theories/Reals/RIneq.v
  theories/Reals/Ranalysis5.v
  theories/Reals/Ratan.v
  theories/Reals/Rminmax.v
  theories/Sets/Powerset_facts.v
  theories/Sets/Relations_1_facts.v
  theories/Sorting/CPermutation.v
  theories/Sorting/PermutEq.v
  theories/Sorting/Permutation.v
  theories/Structures/GenericMinMax.v
  theories/Structures/OrderedType.v
  theories/Structures/OrderedTypeEx.v
  theories/Structures/Orders.v
  theories/Structures/OrdersFacts.v
  theories/Structures/OrdersTac.v
  theories/ZArith/Int.v
  theories/ZArith/Zeven.v
  theories/ZArith/Znumtheory.v
  theories/ZArith/Zquot.v
Labels: kind: user messages

#16212 Fix test suite after parallel merge #16130 and #16129
  test-suite/output/UnivBinders.out
Labels: kind: infrastructure

#16127 [acyclicGraph] is pure
  lib/acyclicGraph.ml
Labels: kind: fix, kind: cleanup

#16179 Additional patterns for ltac2: "as", records, ints, strings
  doc/changelog/05-tactic-language/16179-tac2pat.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2interp.ml
  plugins/ltac2/tac2print.ml
  test-suite/ltac2/fragile_matching.v
  test-suite/ltac2/matching.v
  test-suite/ltac2/stringmatch.v
Labels: kind: enhancement

#16209 Remove UnknownIfTermOrType constructor from Pretyping.typing_constraint
  interp/constrintern.ml
  interp/constrintern.mli
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#16197 Fix Set Default Proof Using input handling
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  test-suite/bugs/bug_16173.v
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/proof_using.ml
Labels: kind: fix, part: STM

#16185 Clarify doc for -Q/-R
  doc/sphinx/practical-tools/coq-commands.rst
Labels: kind: documentation

#16220 Fix Print Assumptions reporting about dependence on UIP
  test-suite/output/bug_16219.out
  test-suite/output/bug_16219.v
  vernac/assumptions.ml
Labels: kind: fix

#16194 Remove the last uses of the legacy refiner from Equality.
  plugins/funind/gen_principle.ml
  tactics/equality.ml
  tactics/equality.mli
  tactics/inv.ml
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#14241 [build] Build stdlib with -warn-error in dev profile.
  dune
Labels: kind: fix, part: build

#16213 Cleanup open modules in `library/`
  library/coqlib.ml
  library/global.ml
  library/globnames.ml
  library/goptions.ml
  library/goptions.mli
  library/lib.ml
  library/libnames.ml
  library/libobject.ml
  library/nametab.ml
  library/nametab.mli
  library/summary.ml
Labels: kind: cleanup

#16238 [v8.8] Backport #15271: Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16236 [v8.9] Backport #15271: Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16235 [v8.10] Backport #15271: Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16234 [v8.11] Backport #15271: Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16233 [v8.12] Backport #15271: Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16229 Fix incorrect generated letin handling in Program Cases
  pretyping/cases.ml
  test-suite/bugs/bug_16043.v
Labels: kind: fix, part: program

#16240 CI: Put "v8.16" in CACHEKEY
  .gitlab-ci.yml
Labels: kind: infrastructure

#16207 Remove deprecated Globnames APIs
  dev/ci/user-overlays/16207-SkySkimmer-rm-depr-globref.sh
  library/globnames.ml
  library/globnames.mli
Labels: kind: cleanup

#16180 UState.universe_decl contains levels not ids
  engine/uState.ml
  engine/uState.mli
  interp/constrintern.ml
Labels: kind: internal

#16202 coq_makefile: run TIMER for coqnative
  tools/CoqMakefile.in
Labels: kind: infrastructure

#15877 Factor code between records and typeclasses
  dev/ci/user-overlays/15877-proux01-cleanup_class_record.sh
  vernac/record.ml
  vernac/record.mli
Labels: kind: cleanup, part: typeclasses, kind: internal, part: records

#16242 chore: Set permissions for GitHub actions
  .github/workflows/ci-macos.yml
  .github/workflows/ci-windows.yml
  .github/workflows/stale.yml
Labels: kind: infrastructure, part: CI

#16245 [v8.15] Put "v8.15" in CACHEKEY
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#16247 Remove `overwrite_library_filenames` function in library.ml
  vernac/library.ml
  vernac/library.mli
Labels: kind: cleanup

#16250 Remove some old scripts
  dev/README.md
  dev/doc/changes.md
  dev/tools/github-check-prs.py
  dev/tools/objects.el
Labels: kind: cleanup, kind: infrastructure

#16227 Fix calling conversion with wrong mode in case inversion
  kernel/cClosure.ml
  test-suite/bugs/bug_16226.v
Labels: kind: fix

#16256 [8.16] Backport #16237
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/changes.rst
  doc/sphinx/language/core/records.rst
  theories/Classes/CRelationClasses.v
  theories/Classes/RelationClasses.v
  theories/Classes/SetoidClass.v
  vernac/record.ml
Labels: kind: fix

#16243 Ltac2 interp: simplify usage of of_closure
  plugins/ltac2/tac2interp.ml
Labels: kind: cleanup

#16252 note since when the things recommended in a deprecation note are supported
  tactics/autorewrite.ml
  vernac/classes.ml
Labels: kind: user messages
