Repository rocq-prover/rocq, pull requests merged in 2022-07, with the labels that each got.

#16231 [v8.14] Backport #15271: Delay removing native_compute .ml files until exit
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16232 [v8.13] Backport #15271: Delay removing native_compute .ml files until exit
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16264 [v8.6] Backport #15271: Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16265 [v8.5] Backport #15271: Delay removing native_compute .ml files until exit
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16254 [doc] Correctly attribute Dune port to Coq
  doc/changelog/11-infrastructure-and-dependencies/15560-build+coq_dune.rst
Labels: kind: fix, kind: documentation

#16263 [v8.7] Backport #15271: Delay removing native_compute .ml files until exit
  .gitlab-ci.yml
  kernel/nativelib.ml
Labels: kind: fix, part: native compiler

#16272 [plugin_tutorial] Remove stale .travis file.
  doc/plugin_tutorial/.travis.yml
Labels: kind: cleanup

#16268 Remove leading pwd from pretty timing logs
  doc/changelog/11-infrastructure-and-dependencies/16268-time-file-maker-remove-pwd.rst
  test-suite/coq-makefile/timing/precomputed-time-tests/008-strip-leading-pwd/run.sh
  test-suite/coq-makefile/timing/precomputed-time-tests/008-strip-leading-pwd/time-of-build-pretty-real.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/008-strip-leading-pwd/time-of-build-pretty-user.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/008-strip-leading-pwd/time-of-build.log.in
  test-suite/coq-makefile/timing/precomputed-time-tests/run.sh
  tools/TimeFileMaker.py
Labels: kind: infrastructure, kind: enhancement, part: build

#16271 Replace remaining uses of `/bin/bash` with more portable `/usr/bin/env bash`
  dev/doc/profiling.txt
  test-suite/primitive/float/gen_compare.sh
Labels: kind: fix

#16274 [configure] Remove duplicate word in output.
  tools/configure/configure.ml
Labels: kind: user messages

#16279 [coqtop] Don't initialize the boot environment on -boot
  toplevel/coqtop.ml
Labels: kind: fix

#16275 Clean `CODEOWNERS` file after #15560.
  .github/CODEOWNERS
Labels: kind: cleanup, kind: meta

#16193 Fix error when building with Sphinx 4.5
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: compatibility

#16278 [vernac] Fix nested proof handling in interpretation.
  test-suite/bugs/bug_16278.v
  test-suite/bugs/bug_16278_load.v
  vernac/vernacextend.ml
  vernac/vernacextend.mli
  vernac/vernacinterp.ml
Labels: kind: fix, part: vernac

#16259 [build] Add -q to stdlib compilation rules
  tools/dune_rule_gen/coq_rules.ml
Labels: kind: fix, part: build

#16285 Syntactically delimit match construct (fix #16284).
  pretyping/cbv.ml
Labels: kind: fix, part: kernel, priority: blocker

#16292 Add test for #16284
  test-suite/bugs/bug_16284.v
Labels: kind: infrastructure

#16283 [default.nix] Put `buildDoc` back to true and update nixpkgs to get Sphinx 4.5.
  default.nix
  dev/nixpkgs.nix
Labels: kind: infrastructure

#16206 Recurse less in extraction
  dev/ci/user-overlays/16206-extraction-less-recurse.sh
  plugins/extraction/extraction.ml
Labels: kind: fix, part: extraction

#16301 SF CI: add SLF volume
  dev/ci/ci-sf.sh
Labels: kind: infrastructure

#16291 Tweak wording for -vos
  doc/sphinx/practical-tools/coq-commands.rst
Labels: kind: documentation

#15495 Inline variant definition in the documentation after #15484.
  doc/sphinx/language/core/variants.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#16246 Add "Ltac2 language" changelog category
  doc/changelog/05-Ltac-language/00000-title.rst
  doc/changelog/05-Ltac-language/16106-local-ltac-redef.rst
  doc/changelog/05-tactic-language/00000-title.rst
  doc/changelog/06-Ltac2-language/00000-title.rst
  doc/changelog/06-Ltac2-language/16023-tac2match.rst
  doc/changelog/06-Ltac2-language/16179-tac2pat.rst
  doc/changelog/07-ssreflect/00000-title.rst
  doc/changelog/07-ssreflect/16158-backport_mc_872_874.rst
  doc/changelog/08-vernac-commands-and-options/00000-title.rst
  doc/changelog/08-vernac-commands-and-options/15274-tacopt.rst
  doc/changelog/09-cli-tools/00000-title.rst
  doc/changelog/10-coqide/00000-title.rst
  doc/changelog/10-coqide/16070-coqide_async_doc.rst
  doc/changelog/11-standard-library/00000-title.rst
  doc/changelog/11-standard-library/15986-pigeonhole.rst
  doc/changelog/11-standard-library/16184-dropin_nat.rst
  doc/changelog/12-infrastructure-and-dependencies/00000-title.rst
  doc/changelog/12-infrastructure-and-dependencies/15560-build+coq_dune.rst
  doc/changelog/12-infrastructure-and-dependencies/15867-edge-4.14.rst
  doc/changelog/12-infrastructure-and-dependencies/16118-build+bump_dune.rst
  doc/changelog/12-infrastructure-and-dependencies/16268-time-file-maker-remove-pwd.rst
  doc/changelog/13-misc/00000-title.rst
Labels: kind: infrastructure

#16182 abstract_list_all: try to do less work
  pretyping/typing.ml
  pretyping/typing.mli
  pretyping/unification.ml
  tactics/tactics.ml
  test-suite/bugs/bug_16181.v
  test-suite/bugs/bug_16182.v
Labels: kind: performance

#16168 Give a better description of Print using and section variables
  doc/changelog/08-vernac-commands-and-options/16168-print_using_doc.rst
  doc/sphinx/addendum/parallel-proof-processing.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
Labels: kind: documentation, part: sections

#16306 Remove reference to non-existent warning
  doc/sphinx/practical-tools/coq-commands.rst
Labels: kind: documentation

#16230 Add a :: notation to make field typeclass instances
  dev/ci/user-overlays/16230-proux01-field_instance.sh
  doc/changelog/08-vernac-commands-and-options/16230-field_instance.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/records.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/funind/glob_term_to_relation.ml
  test-suite/output/bug_16224.out
  test-suite/output/bug_16224.v
  theories/Classes/CRelationClasses.v
  theories/Classes/RelationClasses.v
  theories/Classes/SetoidClass.v
  vernac/classes.ml
  vernac/classes.mli
  vernac/comAssumption.ml
  vernac/comInductive.ml
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: cleanup, kind: feature, part: typeclasses, part: vernac, part: records, kind: usability

#16309 auto regression tests
  test-suite/bugs/bug_4064.v
  test-suite/bugs/bug_6195.v
Labels: kind: internal

#15888 Add a "Coq Configuration Basics" section
  doc/changelog/09-cli-tools/15888-config_doc.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/practical-tools/coqide.rst
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/using/tools/index.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
  vernac/loadpath.ml
  vernac/loadpath.mli
Labels: kind: documentation, part: config

#16302 hygienic local_db in auto
  doc/changelog/04-tactics/16302-auto-hygienic.rst
  tactics/auto.ml
  test-suite/bugs/bug_15814.v
  test-suite/bugs/bug_6332.v
Labels: kind: fix, part: auto

#16280 [ustate] api to declare binders and purge them
  engine/uState.ml
  engine/uState.mli
Labels: kind: internal

#16331 Remove redundant field instance locality warning
  test-suite/output/bug_16224.out
  vernac/record.ml
Labels: kind: user messages

#16289 [eauto] do not eagerly evaluate extern hints
  doc/changelog/04-tactics/16289-eauto-cost.rst
  tactics/eauto.ml
  test-suite/bugs/bug_16282.v
  test-suite/bugs/bug_5163.v
Labels: kind: fix

#16344 [ci] bump elpi to 1.16.5
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/16344-gares-update-elpi.sh
Labels: kind: infrastructure

#16328 [declare] expose API to export side effects
  dev/ci/user-overlays/16328-gares-declare-export-seff.sh
  vernac/declare.ml
  vernac/declare.mli
Labels: kind: internal

#16342 Remove instance-declaring code from ComAssumption.declare_axiom.
  vernac/comAssumption.ml
Labels: kind: cleanup

#16241 Add CACHEKEY editing step to release process.
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#16338 CI: use macos 11 instead of 10.15
  .github/workflows/ci-macos.yml
Labels: kind: infrastructure, part: CI

#16319 [coqdep] improve error message for plugin name
  tools/coqdep/lib/error.ml
Labels: kind: fix, kind: user messages, part: coqdep

#16337 Clean the implementation and API of autorewrite databases
  dev/ci/user-overlays/16337-ppedrot-clean-autorewrite-db.sh
  engine/termops.ml
  engine/termops.mli
  tactics/autorewrite.ml
  tactics/autorewrite.mli
  tactics/dnet.ml
  tactics/dnet.mli
  tactics/dune
  tactics/rewrite.ml
  tactics/term_dnet.ml
  tactics/term_dnet.mli
Labels: kind: cleanup

#16354 fix Frenchism in documentation
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#16299 [Install] Document problem with Opam and Dune 2.x caching in OSX
  INSTALL.md
Labels: kind: documentation
