Repository rocq-prover/rocq, pull requests merged in 2022-09, with the labels that each got.

#16443 Minor declaremods cleanups
  vernac/declaremods.ml
Labels: kind: cleanup

#16430 Simplify error message for "cannot move _ it occurs in the type of _"
  proofs/logic.ml
Labels: kind: fix

#16446 Refactor module declaration
  vernac/declaremods.ml
Labels: kind: cleanup

#16435 Reverse printing order of Ltac2 backtraces
  plugins/ltac2/tac2entries.ml
Labels: kind: fix

#16300 Stop using iter_all_segments in Search, remove iter_all_segments API
  dev/ci/user-overlays/16300-SkySkimmer-noiter.sh
  test-suite/output/Search.out
  test-suite/output/SearchPattern.out
  test-suite/output/Search_headconcl.out
  test-suite/output/bug_13244.out
  vernac/declaremods.ml
  vernac/declaremods.mli
  vernac/search.ml
Labels: kind: cleanup

#16448 Do not reason up to aliasing in Evarsolve.assoc_up_to_alias.
  pretyping/evarsolve.ml
Labels: kind: cleanup

#16208 Print info about dependant section variables in Print/About
  test-suite/output/Arguments.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/PrintSecDeps.out
  test-suite/output/PrintSecDeps.v
  vernac/prettyp.ml
Labels: kind: user messages

#16391 Faster heuristic for elimination principle computation.
  tactics/tactics.ml
Labels: kind: performance, part: tactics

#16452 Small cleanups around the elim tactics
  tactics/equality.ml
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#16429 Add `Ltac2.List.equal`
  doc/changelog/06-Ltac2-language/16429-ltac2-list-equal.rst
  user-contrib/Ltac2/List.v
Labels: kind: feature, kind: enhancement, part: ltac2

#16459 Correctly implement dest_arity for EConstr.
  pretyping/evarsolve.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  test-suite/bugs/bug_5512.v
Labels: kind: fix, kind: cleanup

#16460 Port Heads to EConstr.
  pretyping/coercion.ml
  pretyping/heads.ml
  pretyping/heads.mli
Labels: kind: cleanup

#16434 Fix Print Assumptions ignoring missing proofs with -vok
  dev/ci/user-overlays/16434-SkySkimmer-assumptions-vos.sh
  doc/changelog/08-vernac-commands-and-options/16434-assumptions-vos.rst
  test-suite/output/bug_16411.out
  test-suite/output/bug_16411.v
  test-suite/prerequisite/for_vos.v
  vernac/assumptions.ml
  vernac/assumptions.mli
Labels: kind: fix

#16004 make warn_deprecated_hint_without_locality AsError
  doc/changelog/08-vernac-commands-and-options/16004-pr-Alizter-16004.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  tactics/autorewrite.ml
  tactics/hints.ml
  vernac/classes.ml
Labels: kind: cleanup

#16456 Remove type-unsafe primitives in Proof.focus_kind.
  proofs/proof.ml
  proofs/proof.mli
Labels: kind: cleanup

#16465 [stdlib] [Arith] Typo in user message: Nat.add_com should be Nat.add_comm
  theories/Arith/Minus.v
Labels: kind: user messages, part: standard library

#16457 Ltac2: Reuse result of general pattern interning for simple cases
  plugins/ltac2/tac2intern.ml
Labels: kind: cleanup, part: ltac2

#16450 Fast Evarsolve aliasing algorithm
  pretyping/evarsolve.ml
Labels: kind: cleanup, kind: performance

#16436 Deprecate "~=" notation for JMeq in Program.Equality
  doc/changelog/11-standard-library/16436-depr-jmed-notation.rst
  theories/Program/Equality.v
Labels: kind: cleanup

#16438 Add Print Keywords command
  doc/changelog/08-vernac-commands-and-options/16438-ppkw.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  test-suite/output/PrintKeywords.out
  test-suite/output/PrintKeywords.v
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: kind: feature, part: parser

#16444 Make names of opened containers more precisely typed
  library/lib.ml
  library/nametab.ml
  library/nametab.mli
  vernac/declaremods.ml
  vernac/prettyp.ml
Labels: kind: cleanup

#16474 [CI] Fix the compilation of relation_algebra.
  .gitlab-ci.yml
  Makefile.ci
Labels: kind: infrastructure

#16467 Fast path in Environ.remove_hyps.
  kernel/environ.ml
Labels: kind: performance

#16473 Fast path in Tactics.cook_hyps.
  tactics/tactics.ml
Labels: kind: performance

#16468 Faster algorithm to recognize inductive pattern of destruct.
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  pretyping/tacred.ml
  pretyping/tacred.mli
  proofs/tacmach.ml
  proofs/tacmach.mli
  tactics/tactics.ml
Labels: kind: performance

#16483 push_relevance in InferCumulativity
  kernel/inferCumulativity.ml
  test-suite/bugs/bug_16482.v
Labels: kind: fix

#16466 Add Locate Ltac2 and Print Ltac2 Signatures
  doc/changelog/06-Ltac2-language/16466-locate-ltac2.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  test-suite/output/ltac2_printabout.out
  test-suite/output/ltac2_printabout.v
Labels: kind: feature, part: ltac2

#16461 doc: improve the description of the `decide equality' tactic
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
Labels: kind: documentation

#16481 Do not use unsafe casts for hypothesis computation in Declare.
  vernac/declare.ml
Labels: kind: cleanup

#16487 Partially revert #9139.
  engine/proofview.ml
  engine/proofview_monad.ml
  engine/proofview_monad.mli
  plugins/ltac/tacinterp.ml
  proofs/refine.ml
  tactics/tactics.ml
Labels: kind: cleanup

#16440 Enhance Print Grammar to print whole grammar or subsets of it.
  doc/changelog/08-vernac-commands-and-options/16440-print-grammar-in.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  gramlib/grammar.ml
  gramlib/grammar.mli
  lib/util.ml
  lib/util.mli
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/ltac/tacentries.ml
  plugins/ltac2/tac2entries.ml
  test-suite/output/PrintGrammar.out
  test-suite/output/PrintGrammar.v
  test-suite/output/PrintGrammarConstr.out
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/pvernac.ml
  vernac/vernacexpr.ml
Labels: kind: enhancement

#16492 Clean-up unused ONLY_WINDOWS logic.
  .gitlab-ci.yml
Labels: kind: cleanup

#16496 Stop using @ghost in CODEOWNERS
  .github/CODEOWNERS
Labels: kind: cleanup

#16499 Fix some ssreflect tactic printing code
  plugins/ssr/ssrparser.mlg
Labels: kind: fix

#16488 Be stricter about substitution of evar instances.
  dev/ci/user-overlays/16488-ppedrot-stricter-evar-access.sh
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evarutil.ml
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/termops.mli
  kernel/vars.ml
  plugins/funind/recdef.ml
  plugins/ltac/leminv.ml
  plugins/ltac2/tac2core.ml
  plugins/micromega/coq_micromega.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/evarconv.ml
  pretyping/evardefine.ml
  pretyping/evarsolve.ml
  pretyping/nativenorm.ml
  pretyping/pretyping.ml
  pretyping/vnorm.ml
  tactics/abstract.ml
  tactics/eqdecide.ml
  tactics/equality.ml
  tactics/hints.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  vernac/comProgramFixpoint.ml
Labels: kind: internal

#16490 Do not evar-normalize to-be-reified hypotheses in the Ring tactic.
  plugins/ring/ring.ml
Labels: kind: cleanup

#16502 Expose some ssr witnesses in ssrparser.mli for plugin usage
  plugins/ssr/ssrparser.mli
Labels: kind: internal

#16506 Clarify documentation of `contradiction` tactic
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#16509 Drop bicats subpackage of UniMath
  dev/ci/ci-unimath.sh
Labels: kind: cleanup, part: CI

#16505 Ensure `coqide.opam` actually installs `coqide`
  .gitlab-ci.yml
  coqide.opam
  dune-project
  ide/coqide/dune
Labels: kind: fix, part: CI

#16511 Asymptotically more efficient implementation of FutureGoals.t.
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  proofs/proof.ml
  proofs/refine.ml
  vernac/classes.ml
Labels: kind: performance

#16494 rename Makefile.dune to Makefile
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .gitlab-ci.yml
  Makefile
  Makefile.dune
  dev/doc/README.md
  dev/doc/build-system.dune.md
  dev/doc/profiling.txt
  dev/lint-commits.sh
  dev/lint-repository.sh
  test-suite/coq-makefile/timing/precomputed-time-tests/007-no-output-sync/time-of-build.log.in
Labels: kind: cleanup

#16442 Introduce a dedicated type for evar instances.
  clib/sList.ml
  clib/sList.mli
  dev/ci/user-overlays/16442-ppedrot-evar-compact-instance.sh
  dev/top_printers.ml
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/univSubst.ml
  interp/constrextern.ml
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/constr.ml
  kernel/constr.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/inferCumulativity.ml
  kernel/mod_subst.ml
  kernel/nativelambda.ml
  kernel/reduction.ml
  kernel/vmbytegen.ml
  kernel/vmlambda.ml
  plugins/ltac2/tac2core.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/cbv.ml
  pretyping/constr_matching.ml
  pretyping/detyping.ml
  pretyping/evarconv.ml
  pretyping/evardefine.ml
  pretyping/evarsolve.ml
  pretyping/evarsolve.mli
  pretyping/globEnv.ml
  pretyping/nativenorm.ml
  pretyping/pattern.ml
  pretyping/patternops.ml
  pretyping/pretyping.ml
  pretyping/tacred.ml
  pretyping/unification.ml
  pretyping/vnorm.ml
  printing/printer.ml
  proofs/clenv.ml
  tactics/btermdn.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  vernac/assumptions.ml
  vernac/himsg.ml
  vernac/retrieveObl.ml
Labels: kind: performance

#16519 Remove the Program Naming flag.
  doc/changelog/08-vernac-commands-and-options/16519-rm-program-naming.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/changes.rst
  engine/evarutil.ml
  theories/Compat/Coq815.v
Labels: kind: cleanup

#16526 Add generated dune files to artifact paths
  .gitlab-ci.yml
Labels: kind: fix, part: CI

#16518 [refman] scope_delimiter can be either scope_key or scope_name in Arguments
  doc/sphinx/language/extensions/arguments-command.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#16517 Use `Proofview.wrap_exceptions` in `eauto`
  tactics/eauto.ml
  test-suite/bugs/bug_16527.v
Labels: kind: fix

#16293 [auto] set use_metas_eagerly_in_conv_on_closed_terms = true
  doc/changelog/04-tactics/16293-auto-metas.rst
  tactics/auto.ml
  test-suite/bugs/bug_16062.v
  test-suite/bugs/bug_16323.v
  theories/Lists/List.v
  theories/Numbers/Cyclic/Int63/Uint63.v
  theories/Strings/String.v
  theories/ZArith/Zcomplements.v
  theories/ZArith/Zdiv.v
  theories/ZArith/Znat.v
Labels: kind: enhancement, part: auto

#16355 extending zify saturate class with arguments
  doc/changelog/11-standard-library/16355-zify_saturate_args.rst
  theories/micromega/ZifyClasses.v
  theories/micromega/ZifyInst.v
  theories/micromega/ZifyN.v
  theories/micromega/ZifyNat.v
Labels: kind: enhancement

#16541 Tiny typo
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#16527 Clean the API of the congruence plugin
  plugins/cc/ccalgo.ml
  plugins/cc/ccalgo.mli
  plugins/cc/ccproof.ml
  plugins/cc/ccproof.mli
  plugins/cc/cctac.ml
  plugins/cc/cctac.mli
Labels: kind: cleanup

#16535 Add Ltac2.Array.{for_all2,equal}
  doc/changelog/06-Ltac2-language/16535-array-equal.rst
  user-contrib/Ltac2/Array.v
Labels: kind: enhancement, part: ltac2

#16528 Fix some odoc warnings
  clib/exninfo.mli
  engine/eConstr.mli
  engine/evd.mli
  engine/nameops.mli
  ide/coqide/document.mli
  ide/coqide/protocol/xml_parser.mli
  kernel/cClosure.mli
  kernel/float64.mli
  kernel/float64_common.mli
  kernel/term.mli
  kernel/vars.mli
  parsing/tok.mli
  plugins/ltac/tactic_matching.mli
  plugins/micromega/vect.mli
  plugins/ssrmatching/ssrmatching.mli
  pretyping/evardefine.mli
  vernac/declare.mli
  vernac/retrieveObl.mli
Labels: kind: fix

#16530 [loadpath] Small API cleanup
  vernac/library.mli
  vernac/loadpath.ml
  vernac/loadpath.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#16524 Use Ustate.union less
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  plugins/ltac/internals.ml
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  test-suite/bugs/bug_6323.v
Labels: kind: cleanup

#16476 [gramlib] Extend API to allow finer stream control.
  gramlib/grammar.ml
  gramlib/grammar.mli
  gramlib/lStream.ml
  gramlib/lStream.mli
Labels: kind: internal, part: parser

#16472 Multiple scopes in Arguments and Bind Scope
  dev/ci/user-overlays/16472-proux01-argument_multiple_scopes.sh
  doc/changelog/03-notations/16472-argument_multiple_scopes.rst
  doc/sphinx/language/extensions/arguments-command.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  interp/constrextern.ml
  interp/constrintern.ml
  interp/constrintern.mli
  interp/notation.ml
  interp/notation.mli
  interp/notation_ops.ml
  interp/notation_term.ml
  plugins/ssr/ssrparser.mlg
  test-suite/output/ArgumentsScope.out
  test-suite/output/ArgumentsScope.v
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/comArguments.ml
  vernac/comProgramFixpoint.ml
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/prettyp.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
Labels: part: notations, kind: enhancement

#16523 Better printing when exception in exception printer
  lib/cErrors.ml
Labels: kind: user messages

#16414 Ltac2 closedn,is_closed,occur_between,occurn
  doc/changelog/06-Ltac2-language/16414-ltac-occur.rst
  plugins/ltac2/tac2core.ml
  user-contrib/Ltac2/Constr.v
Labels: kind: enhancement, part: ltac2

#16508 Ltac2: put backtraces on more exceptions
  lib/cErrors.ml
  lib/cErrors.mli
  plugins/ltac/tactic_debug.ml
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2core.mli
  plugins/ltac2/tac2entries.ml
  test-suite/output/ltac2_anomaly_backtrace.out
  test-suite/output/ltac2_anomaly_backtrace.v
Labels: kind: user messages

#16551 Ltac2 patterns allow incomplete record field list
  plugins/ltac2/tac2intern.ml
  test-suite/ltac2/matching.v
Labels: kind: enhancement

#16223 [bench] control opam binary, update to 2.1.3
  dev/bench/README.md
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#16559 Fix anomaly in ssr `abstract`
  plugins/ssr/ssripats.ml
  test-suite/bugs/bug_16559.v
Labels: kind: fix

#16562 Fix printing of ssr `unlock` tactic
  plugins/ssr/ssrparser.mlg
  test-suite/output/bug_16562.out
  test-suite/output/bug_16562.v
Labels: kind: fix

#16557 Expose more ssr witnesses in ssrparser.mli for plugin usage
  plugins/ssr/ssrparser.mli
Labels: kind: internal

#16567 Document the Subgoals XML command
  dev/doc/changes.md
  dev/doc/xml-protocol.md
Labels: kind: documentation

#16489 [stdlib] Adding three lemmata related with finiteness and decidability of equality
  doc/changelog/11-standard-library/16489-listing_decidable_eq.rst
  theories/Lists/ListDec.v
  theories/Logic/FinFun.v
Labels: part: standard library, kind: enhancement

#16549 add coqide-server as a dependency of the coq opam package
  coq.opam
  dune-project
Labels: kind: infrastructure, kind: compatibility, part: build

#16569 add binary output notation test
  test-suite/output/BinaryPrintingNotations.out
  test-suite/output/BinaryPrintingNotations.v
Labels: kind: infrastructure, part: test-suite

#15561 [build] More tweaks after the removal of Makefile build infrastructure
  config/coq_config.mli
  config/dune
  default.nix
  dev/ci/ci-common.sh
  doc/README.md
  tools/configure/cmdArgs.ml
  tools/configure/cmdArgs.mli
  tools/configure/configure.ml
Labels: kind: cleanup, kind: infrastructure, part: build

#16568 [nix] bump to OCaml 4.14 and update some packages
  default.nix
  dev/nixpkgs.nix
Labels: kind: infrastructure, platform: Nix

#16584 Update bench script after coqide-server is dep of coq
  dev/bench/bench.sh
Labels: kind: infrastructure
