Repository rocq-prover/rocq, pull requests merged in 2022-03, with the labels that each got.

#15756 Separate the part of the nametab state related to module names
  library/nametab.ml
  library/nametab.mli
Labels: kind: cleanup

#15710 Three fixes in printing Record/Inductive (universe instances and mutual types)
  engine/eConstr.ml
  engine/eConstr.mli
  engine/namegen.ml
  engine/namegen.mli
  kernel/context.ml
  kernel/context.mli
  test-suite/output/UnivBinders.out
  test-suite/output/UnivBinders.v
  vernac/printmod.ml
Labels: kind: fix, kind: user messages

#15714 Make processed part of script read only when Coq is busy
  doc/changelog/09-coqide/15714-lost_keystrokes.rst
  ide/coqide/session.ml
  ide/coqide/wg_ScriptView.ml
Labels: kind: fix, part: IDE

#15764 Move coqdep into its own folder
  tools/coqdep/common.ml
  tools/coqdep/common.mli
  tools/coqdep/coqdep.ml
  tools/coqdep/coqdep.mli
  tools/coqdep/dune
  tools/coqdep/lexer.mli
  tools/coqdep/lexer.mll
  tools/dune
Labels: kind: cleanup, kind: infrastructure, part: build, kind: internal, part: coqdep

#15769 Fixing small typo in error message
  kernel/nativelib.ml
Labels: kind: user messages

#15183 update module documentation
  doc/sphinx/language/core/modules.rst
  doc/sphinx/refman-preamble.sty
Labels: kind: documentation

#15753 Simpler typing check in Ssrequality.pirrel_rewrite.
  plugins/ssr/ssrequality.ml
  test-suite/ssr/bug_15753_1.v
  test-suite/ssr/bug_15753_2.v
Labels: kind: performance

#15751 test-suite: move vm_norm_records.v into success/
  test-suite/success/vm_norm_records.v
Labels: kind: cleanup

#15752 Deprecate the Typeclasses Filtered Unification flag.
  doc/changelog/07-vernac-commands-and-options/15752-deprecate-filtered-tc.rst
  doc/sphinx/addendum/type-classes.rst
  tactics/class_tactics.ml
Labels: kind: cleanup

#15707 Quote more findlib paths
  tools/CoqMakefile.in
Labels: kind: fix, part: tools, kind: regression, priority: blocker, part: coq_makefile

#15770 Remove a redundant typing check in Ssrelim.
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  test-suite/ssr/bug_15770.v
Labels: kind: performance

#15760 Warn when trying to deprecate a definition
  doc/changelog/07-vernac-commands-and-options/15760-deprecation_lemmas.rst
  test-suite/output/deprecation_definition.out
  test-suite/output/deprecation_definition.v
  theories/Init/Datatypes.v
  theories/NArith/Ndigits.v
  theories/Numbers/Cyclic/Int63/Cyclic63.v
  theories/ZArith/Zdiv.v
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: user messages, part: vernac

#15775 Accept \ in Windows pathnames in coq_project args
  ide/coqide/ideutils.ml
  lib/coqProject_file.ml
Labels: kind: fix

#15782 Faster computation of head equality in Ssrequality.rwprocess_rule.
  plugins/ssr/ssrequality.ml
Labels: kind: performance

#15765 merge minisys back into system
  clib/minisys.ml
  lib/system.ml
  tools/coqdep/common.ml
  topbin/coqnative_bin.ml
Labels: kind: cleanup, kind: internal

#15729 [vernac] Fix cache invalidation as not to mess with non-imperative state
  test-suite/ide/bug14981.fake
  vernac/vernacstate.ml
Labels: kind: fix, part: vernac

#15745 toplevel: fix a bug in `coqc -vok` invocation
  doc/changelog/08-cli-tools/15745-coqc-vok.rst
  stm/asyncTaskQueue.ml
  test-suite/misc/coqc_cmdline.v
  test-suite/misc/coqc_dash_o.sh
  test-suite/misc/coqc_dash_vok.sh
  toplevel/ccompile.ml
Labels: kind: fix

#15689 Update coqdev.el: minor fixes + better ocamldebug breakpoints in plugins/
  dev/tools/coqdev.el
Labels: kind: infrastructure, kind: internal

#15767 Move the rewrite implementation out of Ltac.
  plugins/ltac/comRewrite.ml
  plugins/ltac/comRewrite.mli
  plugins/ltac/g_rewrite.mlg
  plugins/ring/ring.ml
  tactics/rewrite.ml
  tactics/rewrite.mli
Labels: kind: cleanup, kind: internal

#15772 Correctly prevent editable status of text when CoqIDE is busy.
  ide/coqide/coqide.ml
  ide/coqide/session.ml
  ide/coqide/tags.ml
  ide/coqide/wg_Find.ml
  ide/coqide/wg_Find.mli
  ide/coqide/wg_ScriptView.ml
  ide/coqide/wg_ScriptView.mli
Labels: kind: fix, part: IDE

#15549 improve deprecation message for 8.16 deprecated Arith lemmas
  theories/Arith/Div2.v
  theories/Arith/EqNat.v
  theories/Arith/Even.v
  theories/Arith/Gt.v
  theories/Arith/Le.v
  theories/Arith/Lt.v
  theories/Arith/Minus.v
  theories/Arith/Mult.v
  theories/Arith/Plus.v
Labels: kind: user messages, part: standard library

#15819 Remove dead code around intern_ind_pattern
  interp/constrintern.ml
Labels: kind: cleanup, part: elaboration

#15796 Reduce the amount of typing in congruence.
  plugins/cc/cctac.ml
  pretyping/typing.mli
Labels: kind: performance

#15821 [coqdep] Refactor initialization API
  tools/coqdep/common.ml
  tools/coqdep/common.mli
  tools/coqdep/coqdep.ml
Labels: kind: internal, part: coqdep

#15794 Reduce the amount of useless typing performed by subst.
  tactics/equality.ml
Labels: kind: performance, part: tactics

#15826 Bump default OCaml version to 4.12 in Nix setup
  default.nix
  dev/nixpkgs.nix
Labels: kind: infrastructure

#15834 Fix link to standard library.
  doc/sphinx/language/coq-library.rst
Labels: kind: fix, kind: documentation, part: website

#15835 Add changelog for #15633
  doc/changelog/09-coqide/15633-change-15633.rst
Labels: kind: fix, part: diffs

#15830 Avoid diff anomaly if the new proof has no foreground goal
  printing/proof_diffs.ml
Labels: kind: fix, part: diffs

#15788 Cleaner handling of destdir for ocaml plugins
  doc/changelog/08-cli-tools/15788-nix_coqmakefile.rst
  doc/sphinx/practical-tools/utilities.rst
  tools/CoqMakefile.in
Labels: kind: infrastructure, part: coq_makefile

#15839 Check that inductives have same squashing in subtyping
  dev/doc/critical-bugs
  doc/changelog/01-kernel/15839-subtyp-check-kelim.rst
  kernel/subtyping.ml
  test-suite/bugs/bug_15838.v
Labels: kind: fix

#15837 Reduce Universe.t footprint
  checker/checkInductive.ml
  checker/values.ml
  dev/ci/user-overlays/15837-ppedrot-reduce-universe-footprint.sh
  engine/eConstr.ml
  engine/evarutil.ml
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/univProblem.ml
  engine/univProblem.mli
  kernel/constr.ml
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/indTyping.ml
  kernel/indTyping.mli
  kernel/inductive.ml
  kernel/inductive.mli
  kernel/inferCumulativity.ml
  kernel/mod_typing.ml
  kernel/reduction.ml
  kernel/sorts.ml
  kernel/sorts.mli
  kernel/subtyping.ml
  kernel/type_errors.ml
  kernel/type_errors.mli
  kernel/uGraph.ml
  kernel/uGraph.mli
  kernel/vars.ml
  plugins/funind/gen_principle.ml
  pretyping/evarsolve.ml
  pretyping/inductiveops.ml
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/retyping.ml
  pretyping/typing.ml
  pretyping/unification.ml
  tactics/cbn.ml
  vernac/comInductive.ml
  vernac/himsg.ml
Labels: kind: cleanup

#15844 Changelog for 8.15.1
  doc/changelog/01-kernel/15498-master+fix15451-incompleteness-guard-condition.rst
  doc/changelog/01-kernel/15839-subtyp-check-kelim.rst
  doc/changelog/03-notations/15628-master+check-custom-exist-only-printing.rst
  doc/changelog/04-tactics/15577-transitivity-opt-rew-rel.rst
  doc/changelog/04-tactics/15612-rewrite-with-progress.rst
  doc/changelog/04-tactics/15634-master+fix-15606-clearbody-transitive-check.rst
  doc/changelog/04-tactics/15653-cbn-refold.rst
  doc/changelog/08-cli-tools/15745-coqc-vok.rst
  doc/changelog/09-coqide/15532-error_line_nos.rst
  doc/changelog/09-coqide/15633-change-15633.rst
  doc/changelog/09-coqide/15714-lost_keystrokes.rst
  doc/changelog/12-misc/15537-master+fix15420-hardwire-names-pred-mutual-induction-schemes.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#15851 CI: use fixed platform version instead of dev branch
  .github/workflows/ci-windows.yml
Labels: kind: infrastructure

#15847 Remove the Prop < Set hack for template from the universe graph
  engine/uState.ml
  engine/univMinim.ml
  engine/univMinim.mli
  engine/univProblem.ml
  engine/univProblem.mli
  kernel/sorts.ml
  kernel/uGraph.ml
  kernel/uGraph.mli
  test-suite/output/PrintUnivsSubgraph.out
  vernac/comInductive.ml
Labels: kind: cleanup

#15845 [cleanup] pretype arguments
  pretyping/cases.ml
  pretyping/coercion.ml
  pretyping/coercion.mli
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  pretyping/unification.ml
  proofs/clenv.ml
Labels: kind: cleanup

#15657 cbn: handle combination of / and simpl nomatch
  doc/changelog/04-tactics/15657-cbn-volatile-nomatch.rst
  tactics/cbn.ml
  test-suite/bugs/bug_3989.v
  test-suite/success/cbn.v
Labels: kind: fix

#15802 Add a deprecation warning to > in Class
  doc/changelog/07-vernac-commands-and-options/15802-deprecate_backinstance.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/language/core/records.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
  theories/Classes/CRelationClasses.v
  theories/Classes/RelationClasses.v
  theories/Classes/SetoidClass.v
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: fix, kind: cleanup, part: typeclasses, part: coercions, part: records, kind: usability

#15868 Typo in Hint Extern doc
  doc/sphinx/proofs/automatic-tactics/auto.rst
Labels: kind: documentation

#15863 Restrict the universe level algebra to a single small level.
  engine/uState.ml
  engine/univMinim.ml
  engine/univProblem.ml
  interp/constrintern.ml
  interp/constrintern.mli
  kernel/inductive.ml
  kernel/sorts.ml
  kernel/uGraph.ml
  kernel/univ.ml
  kernel/univ.mli
  pretyping/detyping.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  test-suite/misc/universes.sh
  vernac/declareUniv.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#15846 Add contents::local to unreleased changes section
  doc/changelog/00-title.rst
Labels: kind: documentation

#15827 Use warn-error for dune dev mode warnings
  dune
  kernel/dune
Labels: kind: fix, part: build

#15865 bench script: handle lack of html/ directory gracefully
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#15855 Add Jasmin and mathcomp-word to CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-jasmin.sh
  dev/ci/ci-mathcomp_word.sh
Labels: kind: infrastructure, part: CI

#15860 Speed up computing proof using for Admitted when trivial
  vernac/declare.ml
Labels: kind: fix, kind: cleanup, kind: performance, part: vernac

#15677 Added fiat-crypto-with-bedrock
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#15876 Fix docgram
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: fix, kind: documentation

#15728 assert_succeeds preserves the underlying error
  doc/changelog/04-tactics/15728-assert-succeeds-message.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/tools/docgram/fullGrammar
  plugins/ltac/extratactics.mlg
  plugins/ltac/internals.ml
  plugins/ltac/internals.mli
  test-suite/output/Tactics.out
  test-suite/output/Tactics.v
  theories/Init/Tactics.v
Labels: kind: fix

#15871 First pass of cleanup of the Univ API
  dev/ci/user-overlays/15871-ppedrot-univ-cleanup-api.sh
  dev/top_printers.ml
  dev/top_printers.mli
  engine/evd.ml
  engine/uState.ml
  engine/univGen.ml
  engine/univGen.mli
  engine/univMinim.ml
  engine/univSubst.ml
  engine/univSubst.mli
  kernel/indTyping.ml
  kernel/sorts.ml
  kernel/univ.ml
  kernel/univ.mli
  kernel/vars.ml
  kernel/vmvalues.ml
  library/nametab.ml
  library/nametab.mli
  pretyping/evarsolve.ml
  pretyping/retyping.ml
  pretyping/structures.ml
  tactics/cbn.ml
  test-suite/misc/poly-capture-global-univs/src/evilImpl.ml
  vernac/comInductive.ml
  vernac/declareUniv.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#15823 [coqdep] Start to modularize loadpath handling.
  tools/coqdep/common.ml
  tools/coqdep/common.mli
  tools/coqdep/coqdep.ml
  tools/coqdep/loadpath.ml
  tools/coqdep/loadpath.mli
  tools/coqdep/options.ml
  tools/coqdep/options.mli
Labels: kind: cleanup, part: coqdep

#15866 Add "intuition_solver" indirection in intuition to allow for redefinion
  doc/changelog/04-tactics/15866-inuit-solver.rst
  test-suite/bugs/bug_7725.v
  theories/Init/Tauto.v
Labels: part: standard library, part: tactics, kind: enhancement
