Repository rocq-prover/rocq, pull requests merged in 2022-12, with the labels that each got.

#16932 Warn about the hazards of Notepad and File Manager on Windows
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#16925 Adapt the bytecode interpreter to the latest changes from OCaml 5.
  kernel/byterun/coq_interp.c
  kernel/byterun/coq_memory.c
Labels: kind: fix, part: VM

#16939 Update nixpkgs to get ocaml-lsp 4.12
  dev/nixpkgs.nix
Labels: kind: infrastructure

#16875 Understand covariant inductive cumulativity in evarconv
  pretyping/evarconv.ml
  test-suite/bugs/bug_16872.v
Labels: kind: fix

#16927 Fix #16922: bug in Nametab.remove which #12324 introduced (deactivation of notations)
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  interp/constrextern.ml
  interp/constrextern.mli
  library/nametab.ml
  test-suite/bugs/bug_16922.v
Labels: kind: fix, part: notations

#16911 Remove the Typeclasses Filtered Unification flag.
  doc/changelog/08-vernac-commands-and-options/16911-rm-tc-filtered-unification.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/changes.rst
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/hints.mli
  test-suite/success/Hints.v
Labels: kind: cleanup

#16810 Zify: use Typing to check universe sensitive applications
  plugins/micromega/zify.ml
  test-suite/bugs/bug_16803.v
Labels: part: micromega, kind: bug

#16933 Preserve the ESorts abstraction in the upper layers.
  dev/ci/user-overlays/16933-ppedrot-esorts-respect-api.sh
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  interp/notation.ml
  kernel/environ.ml
  kernel/environ.mli
  plugins/cc/cctac.ml
  plugins/funind/gen_principle.ml
  plugins/ltac2/tac2core.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/zify.ml
  plugins/ssr/ssrfwd.ml
  plugins/syntax/number.ml
  pretyping/cases.ml
  pretyping/coercion.ml
  pretyping/evarconv.ml
  pretyping/evardefine.ml
  pretyping/evardefine.mli
  pretyping/evarsolve.ml
  pretyping/indrec.ml
  pretyping/indrec.mli
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/retyping.ml
  pretyping/retyping.mli
  pretyping/typing.ml
  pretyping/typing.mli
  pretyping/unification.ml
  tactics/contradiction.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: cleanup

#16915 Add extgcd
  doc/changelog/11-standard-library/16915-add-extgcd.rst
  test-suite/complexity/vm_extgcd.v
  theories/ZArith/Znumtheory.v
Labels: kind: cleanup, kind: feature, part: standard library

#16931 Check VM is enabled in vm_compute
  doc/changelog/08-vernac-commands-and-options/16931-vm-norm-check.rst
  pretyping/vnorm.ml
  tactics/redexpr.ml
  test-suite/success/DisableVM.v
Labels: kind: fix

#16938 Add a staging notion to option declarations
  dev/ci/user-overlays/16938-SkySkimmer-staged-options.sh
  engine/namegen.ml
  engine/uState.ml
  engine/univMinim.ml
  interp/constrextern.ml
  interp/constrintern.ml
  interp/notation.ml
  library/goptions.ml
  library/goptions.mli
  plugins/extraction/table.ml
  plugins/firstorder/g_ground.mlg
  plugins/funind/indfun_common.ml
  plugins/ltac/profile_ltac.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tactic_debug.ml
  plugins/ltac/tauto.ml
  plugins/ltac2/tac2entries.ml
  plugins/micromega/certificate.ml
  plugins/micromega/coq_micromega.ml
  plugins/rtauto/proof_search.ml
  plugins/rtauto/refl_tauto.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssrmatching/ssrmatching.ml
  pretyping/coercion.ml
  pretyping/detyping.ml
  pretyping/nativenorm.ml
  pretyping/pretyping.ml
  pretyping/program.ml
  pretyping/typeclasses.ml
  pretyping/unification.ml
  printing/printer.ml
  printing/proof_diffs.ml
  proofs/goal_select.ml
  proofs/proof.ml
  proofs/proof_bullet.ml
  stm/stm.ml
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/equality.ml
  tactics/hints.ml
  tactics/redexpr.ml
  tactics/tactics.ml
  toplevel/coqloop.ml
  vernac/attributes.ml
  vernac/comInductive.ml
  vernac/comSearch.ml
  vernac/comTactic.ml
  vernac/declare.ml
  vernac/indschemes.ml
  vernac/printmod.ml
  vernac/proof_using.ml
  vernac/record.ml
  vernac/vernacentries.ml
  vernac/vernacinterp.ml
Labels: kind: redesign

#16947 Define a dummy replacement for Obj.set_tag for OCaml 5.
  kernel/byterun/coq_values.c
  kernel/nativevalues.ml
Labels: kind: internal

#16930 Remove Flags.native_compiler
  dev/ci/user-overlays/16930-SkySkimmer-flag-native.sh
  lib/flags.ml
  lib/flags.mli
  pretyping/nativenorm.ml
  sysinit/coqinit.ml
  tactics/redexpr.ml
  topbin/coqnative_bin.ml
  vernac/library.ml
Labels: kind: cleanup

#16870 Turn some calls to `Evd.find` into `Evd.find_undefined`.
  engine/eConstr.ml
  engine/evarutil.ml
  engine/evarutil.mli
  engine/proofview.ml
  ide/coqide/idetop.ml
  plugins/funind/recdef.ml
  plugins/ltac/internals.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/detyping.ml
  pretyping/evardefine.ml
  pretyping/evarsolve.ml
  pretyping/pretype_errors.ml
  pretyping/pretyping.ml
  pretyping/typeclasses.ml
  printing/proof_diffs.ml
  proofs/proof.ml
  proofs/refine.ml
  stm/proofBlockDelimiter.ml
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/rewrite.ml
  vernac/comTactic.ml
  vernac/retrieveObl.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#16955 Use relevance_of_sort in Typeops.infer_assumption (minicleanup)
  kernel/typeops.ml
Labels: kind: cleanup

#16965 Fix a typo
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation

#16959 Remove legacy exception aliases in Gramlib.Stream.
  gramlib/stream.ml
Labels: kind: cleanup, part: parser, part: ocaml

#16914 deprecate Cyclic.ZModulo.ZModulo
  doc/changelog/11-standard-library/16914-deprecate-ZModulo.rst
  theories/Numbers/Cyclic/ZModulo/ZModulo.v
Labels: kind: cleanup, part: standard library

#16952 Test for #16803: use Defined to work with async proofs
  test-suite/bugs/bug_16803.v
Labels: kind: infrastructure

#16725 Process LoadPath directories in sorted order
  doc/changelog/13-misc/16725-sort_dir.rst
  vernac/loadpath.ml
Labels: kind: enhancement, kind: usability

#16941 Serious clean up of Firstorder plugin
  plugins/firstorder/formula.ml
  plugins/firstorder/formula.mli
  plugins/firstorder/ground.ml
  plugins/firstorder/instances.ml
  plugins/firstorder/instances.mli
  plugins/firstorder/rules.ml
  plugins/firstorder/rules.mli
  plugins/firstorder/sequent.ml
  plugins/firstorder/sequent.mli
  plugins/firstorder/unify.ml
  plugins/firstorder/unify.mli
Labels: kind: cleanup

#16946 Separate interpretation and syntax declaration in tactic notations
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_ltac.mlg
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2intern.ml
Labels: kind: internal, part: ltac2

#16976 Use fresh directory for coq-makefile/expand-directories test
  test-suite/coq-makefile/expand-directories/run.sh
Labels: kind: cleanup

#16974 dune-dbg support for native, added debug printers
  dev/dune
  dev/dune-dbg.in
  dev/shim/dune
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  topbin/dune
Labels: kind: infrastructure, kind: internal

#16958 Make lazy_val use local to vmsymtable
  dev/ci/user-overlays/16958-SkySkimmer-no-lazy-val.sh
  dev/doc/critical-bugs
  doc/changelog/01-kernel/16958-no-lazy-val.rst
  engine/eConstr.ml
  engine/eConstr.mli
  engine/evarutil.ml
  kernel/cClosure.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/vmsymtable.ml
  plugins/ltac2/tac2core.ml
  proofs/logic.ml
  test-suite/bugs/bug_16957.v
Labels: kind: fix

#16936 Lessen use of `DirPath.initial`, and rename it to `dummy`
  kernel/environ.ml
  kernel/environ.mli
  kernel/names.ml
  kernel/names.mli
  kernel/opaqueproof.ml
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  library/global.ml
  library/global.mli
  library/lib.ml
  library/libnames.ml
  library/libnames.mli
  plugins/extraction/table.ml
  test-suite/unit-tests/printing/proof_diffs_test.ml
  vernac/declaremods.ml
Labels: kind: cleanup

#16969 speedup HexadecimalPos.v
  theories/Numbers/HexadecimalPos.v
Labels: kind: performance, part: standard library

#16948 Call `dune printenv` on CI
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#16756 [stdlib] add nth_error_ext, map_repeat, to_list_nil_iff, to_list_inj
  doc/changelog/11-standard-library/16756-vector_list_lemmas.rst
  theories/Lists/List.v
  theories/Vectors/VectorSpec.v
Labels: kind: feature

#16944 Refactor Metasyntax API to better separate syntax and interpretation
  dev/ci/user-overlays/16944-maximedenes-separate-notation-syntax.sh
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/ppvernac.ml
  vernac/pvernac.mli
  vernac/record.ml
  vernac/vernacentries.ml
  vernac/vernacentries.mli
  vernac/vernacexpr.ml
Labels: kind: cleanup

#16972 Extend contributors list
  .mailmap
  dev/tools/list-contributors.sh
Labels: kind: infrastructure, kind: meta

#16902 Attribute #[warnings="warning-list"] to locally control warnings
  doc/changelog/08-vernac-commands-and-options/16902-warning-att.rst
  doc/sphinx/language/core/basic.rst
  test-suite/success/warnings_attribute.v
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/vernacinterp.ml
Labels: kind: feature, part: vernac

#16991 Use Alloc_small_enter_GC with OCaml 5.
  kernel/byterun/coq_interp.c
Labels: kind: fix, part: VM

#16971 Separate parsing effects in VERNAC EXTEND macro
  coqpp/coqpp_ast.mli
  coqpp/coqpp_lex.mll
  coqpp/coqpp_main.ml
  coqpp/coqpp_parse.mly
  plugins/ltac/g_ltac.mlg
  plugins/ltac2/g_ltac2.mlg
Labels: kind: internal, part: vernac

#16975 Stop catching anomalies from conversion
  pretyping/pretype_errors.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/unification.ml
  test-suite/bugs/bug_16975.v
Labels: kind: cleanup

#16988 [cleanup] Don't use long-deprecated `Printexc.catch`
  tools/ocamllibdep.mll
  vernac/mltop.ml
Labels: kind: cleanup

#16984 ci-color: disable native
  dev/ci/ci-color.sh
Labels: kind: infrastructure

#16961 Clean the bytecode interpreter
  kernel/byterun/coq_fix_code.c
  kernel/byterun/coq_fix_code.h
  kernel/byterun/coq_interp.c
  kernel/byterun/coq_memory.c
  kernel/byterun/coq_memory.h
  kernel/byterun/coq_values.c
  kernel/vm.ml
  kernel/vm.mli
  kernel/vmvalues.ml
Labels: kind: cleanup, part: VM

#16968 Increase timeout for fiat-crypto.
  .gitlab-ci.yml
Labels: kind: infrastructure, kind: ci-failure

#16859 Support parsing Ltac2 array literals
  doc/changelog/06-Ltac2-language/16859-ltac2_parse_arrays.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2quote.ml
  plugins/ltac2/tac2quote.mli
  test-suite/ltac2/array_notation.v
Labels: kind: enhancement

#16731 made Vector.nth substructural
  doc/changelog/11-standard-library/16731-stdlib-vector.rst
  test-suite/bugs/bug_16738.v
  theories/Vectors/VectorDef.v
Labels: kind: fix, part: standard library

#16874 Reals: Renaming R_dist into Rdist for better naming uniformity
  doc/changelog/11-standard-library/16874-master+renaming-R_dist-Rdist-for-uniformity.rst
  theories/Reals/Alembert.v
  theories/Reals/AltSeries.v
  theories/Reals/Cos_plus.v
  theories/Reals/Cos_rel.v
  theories/Reals/Exp_prop.v
  theories/Reals/Machin.v
  theories/Reals/PSeries_reg.v
  theories/Reals/PartSum.v
  theories/Reals/Ranalysis1.v
  theories/Reals/Ranalysis2.v
  theories/Reals/Ranalysis3.v
  theories/Reals/Ranalysis4.v
  theories/Reals/Ranalysis5.v
  theories/Reals/Ratan.v
  theories/Reals/Rcomplete.v
  theories/Reals/Rderiv.v
  theories/Reals/Rfunctions.v
  theories/Reals/RiemannInt.v
  theories/Reals/Rlimit.v
  theories/Reals/Rpower.v
  theories/Reals/Rseries.v
  theories/Reals/Rsqrt_def.v
  theories/Reals/Rtopology.v
  theories/Reals/Rtrigo1.v
  theories/Reals/Rtrigo_alt.v
  theories/Reals/Rtrigo_def.v
  theories/Reals/Rtrigo_fun.v
  theories/Reals/Rtrigo_reg.v
  theories/Reals/SeqProp.v
  theories/Reals/SeqSeries.v
  theories/Reals/Sqrt_reg.v
Labels: part: standard library, kind: enhancement

#16999 [clib] [cThread] Don't inline `Mutex.unlock` manually.
  clib/cThread.ml
Labels: kind: compatibility, kind: internal, part: ocaml

#16765 [stdlib] add Fin and Vector lemmas
  doc/changelog/11-standard-library/16765-stdlib-more-vector.rst
  theories/Vectors/Fin.v
  theories/Vectors/VectorDef.v
  theories/Vectors/VectorSpec.v
Labels: part: standard library, kind: enhancement

#17010 [build] [bootstrap] Ignore a warning for better compat with OCaml 5.0
  lib/control.ml
Labels: kind: compatibility, part: ocaml

#17009 Correct comment in structures.mli
  pretyping/structures.mli
Labels: kind: internal

#16981 Give an error for a non-existent proof mode in the Proof Mode command
  dev/ci/user-overlays/16981-jfehrle-fix_proof_mode.sh
  doc/changelog/08-vernac-commands-and-options/16981-fix_proof_mode.rst
  doc/sphinx/proof-engine/ltac2.rst
  stm/stm.ml
  vernac/vernac_classifier.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
Labels: kind: fix

#16985 More compact representation of VM patch positions.
  kernel/vmemitcodes.ml
Labels: kind: performance, part: VM

#17005 Ensure that the acyclic graph explanation contains both end points
  kernel/uGraph.ml
  kernel/uGraph.mli
  kernel/univ.ml
  kernel/univ.mli
  lib/acyclicGraph.ml
  lib/acyclicGraph.mli
  test-suite/output/bug_17002.out
  test-suite/output/bug_17002.v
Labels: kind: fix, kind: cleanup, part: universes

#16978 [parsing] Remove hack which hampered correct parsing resumption, fix CoqIDE tooltip display.
  gramlib/stream.ml
  gramlib/stream.mli
  ide/coqide/coqOps.ml
  ide/coqide/idetop.ml
  ide/coqide/ideutils.mli
  parsing/cLexer.ml
  parsing/cLexer.mli
  test-suite/Makefile
  test-suite/interactive/ltac_debugger.v
  test-suite/unit-tests/parsing/dune
  test-suite/unit-tests/parsing/resumption.ml
Labels: kind: fix, part: IDE, kind: enhancement, kind: internal, part: parser

#17013 `Nat.iter` properties
  doc/changelog/11-standard-library/17013-natiter.rst
  theories/Arith/PeanoNat.v
Labels: part: standard library, kind: enhancement

#17015 [internal] Avoid deprecation warnings in OCaml 5.0
  stm/asyncTaskQueue.ml
  stm/workerPool.ml
Labels: kind: internal

#17019 Verdi Raft and related projects no longer use configure script
  dev/ci/ci-verdi_raft.sh
  dev/ci/nix/verdi-raft.nix
Labels: kind: infrastructure, part: CI

#17016 Revert "Compat for serapi"
  dev/ci/user-overlays/17016-SkySkimmer-explain-serapi.sh
  kernel/uGraph.ml
  kernel/uGraph.mli
  kernel/univ.ml
  kernel/univ.mli
Labels: kind: cleanup

#16997 [configure] Check for OCaml 5.0 in configure.
  config/dune
  doc/changelog/12-infrastructure-and-dependencies/16997-ci+ocaml5.rst
  tools/configure/cmdArgs.ml
  tools/configure/configure.ml
Labels: kind: compatibility, part: ocaml

#17004 Mark some debugging FunInd commands as internal and add a note on Equations.
  doc/sphinx/using/libraries/funind.rst
Labels: kind: documentation, part: funind

#17026 [coqide] Invalidate offset cache on retract
  ide/coqide/coqOps.ml
Labels: kind: fix, part: IDE

#17027 [stdlib] filter_length
  doc/changelog/11-standard-library/17027-filter_length.rst
  theories/Lists/List.v
Labels: part: standard library, kind: enhancement

#16970 CI: do not set interruptible:true on protected branches
  .gitlab-ci.yml
  dev/ci/gitlab-modes/normal-mode.yml
  dev/ci/gitlab-modes/protected-mode.yml
Labels: kind: infrastructure
