Repository rocq-prover/rocq, pull requests merged in 2022-02, with the labels that each got.

#15537 Fix #15420: statically hardwiring the names of arguments in induction schemes
  dev/ci/user-overlays/15420-herbelin-master+fix15420-hardwire-names-pred-mutual-induction-schemes.sh
  doc/changelog/12-misc/15537-master+fix15420-hardwire-names-pred-mutual-induction-schemes.rst
  pretyping/indrec.ml
  test-suite/bugs/HoTT_coq_088.v
  test-suite/bugs/HoTT_coq_090.v
  test-suite/bugs/HoTT_coq_091.v
  test-suite/bugs/bug_15420.v
  test-suite/bugs/bug_4780.v
  test-suite/output/PrintingParentheses.out
  test-suite/output/SchemeNames.out
  test-suite/output/SchemeNames.v
  test-suite/output/StringSyntax.out
  test-suite/success/Discriminate_HoTT.v
  theories/Init/Logic.v
Labels: kind: fix

#15585 fix(coq.opam.docker): Remove leftover `make byte`
  coq.opam.docker
Labels: kind: fix, priority: blocker

#15559 Stop caring about unfolding state of primproj in constr_matching
  doc/changelog/05-tactic-language/15559-constr-match-unfold-proj.rst
  pretyping/constr_matching.ml
  test-suite/bugs/bug_15554.v
  test-suite/bugs/bug_3656.v
  test-suite/bugs/bug_3662.v
Labels: kind: fix

#15563 Move rewrite_db tactic under "Usage"
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation

#15426 rewrite in *: don't skip variables appearing only through evar instances
  doc/changelog/04-tactics/15426-rew-in-all-nonevars.rst
  doc/sphinx/proof-engine/tactics.rst
  engine/evarutil.ml
  engine/evarutil.mli
  tactics/equality.ml
  test-suite/bugs/bug_15448.v
  test-suite/bugs/bug_3051.v
Labels: kind: fix

#15524 Support for inductive with defined parameters in native_compute
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/nativenorm.ml
  test-suite/success/nativecompute.v
Labels: kind: fix, part: native compiler, part: inductives

#15493 Share the check for evar groundedness in eassumption.
  tactics/eauto.ml
Labels: kind: efficiency

#15605 Fix #15603: ocamldebug fails with Reference to undefined global Dynlink.
  dev/core_dune.dbg
Labels: kind: infrastructure, kind: internal

#15601 Fix shim scripts after findlib
  dev/shim/dune
Labels: kind: fix, part: build

#15589 Print sub-error in ReplacementIllTyped
  tactics/tactics.ml
  test-suite/output/Errors.out
  test-suite/output/Errors.v
Labels: kind: user messages, part: tactics, kind: enhancement

#15599 Add some trigonometry lemmas
  doc/changelog/10-standard-library/15599-x-sinx-x.rst
  theories/Reals/Ratan.v
Labels: kind: enhancement

#15609 Add -I $COQCORELIB/.. to default loadpath
  sysinit/coqloadpath.ml
Labels: kind: fix

#15611 Evaluating possibly costly illegal fix recursive call error only at printing time
  kernel/inductive.ml
  kernel/type_errors.ml
  kernel/type_errors.mli
  test-suite/complexity/guard_illegal_call.v
  vernac/himsg.ml
Labels: kind: performance, part: inductives

#15615 Ltac2: don't use mltop magic to set the default proof mode
  plugins/ltac2/tac2entries.ml
  user-contrib/Ltac2/Init.v
Labels: kind: cleanup

#15602 Slightly better fatal dialog in CoqIDE.
  ide/coqide/coq.ml
Labels: part: IDE, kind: enhancement

#15620 DecidableClasses: added decidability instances for Z.le Z.lt Z.ge Z.gt
  doc/changelog/10-standard-library/15620-z-arith-decidable.rst
  theories/Classes/DecidableClass.v
  theories/ZArith/BinInt.v
Labels: part: standard library, kind: enhancement

#15584 micromega: addition of a Let binding in the proof format
  plugins/micromega/certificate.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/micromega.ml
  plugins/micromega/micromega.mli
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  test-suite/micromega/bug_15481.v
  theories/micromega/RingMicromega.v
Labels: kind: performance

#15577 Pass more complete cstr in Rewrite.transitivity strategy
  doc/changelog/04-tactics/15577-transitivity-opt-rew-rel.rst
  plugins/ltac/rewrite.ml
  test-suite/bugs/bug_15568.v
Labels: kind: fix

#15626 Add a test for #7068.
  test-suite/bugs/bug_7068.v
Labels: kind: fix

#15627 An optimization in the guard checker
  kernel/inductive.ml
  test-suite/complexity/guard_return_predicate.v
Labels: kind: performance, part: inductives

#15624 Share the pivot computation in micromega.
  plugins/micromega/certificate.ml
Labels: kind: performance, part: micromega

#15642 Don't drop unification error in UnexpectedType error
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  pretyping/pretyping.ml
  test-suite/output/UnexpectedType.out
  test-suite/output/UnexpectedType.v
  vernac/himsg.ml
Labels: kind: user messages

#15628 Fix #15619: Check existence of a custom entry also in only printing mode
  doc/changelog/03-notations/15628-master+check-custom-exist-only-printing.rst
  test-suite/success/Notations2.v
  vernac/metasyntax.ml
Labels: kind: fix, part: notations, part: custom

#15623 Selectively print the contents of goals in CoqIDE.
  ide/coqide/coq.ml
  ide/coqide/coq.mli
  ide/coqide/coqOps.ml
  ide/coqide/idetop.ml
  ide/coqide/protocol/interface.ml
  ide/coqide/protocol/xmlprotocol.ml
  ide/coqide/protocol/xmlprotocol.mli
  ide/coqide/wg_ProofView.ml
  ide/coqide/wg_ProofView.mli
Labels: kind: fix, kind: performance, part: IDE

#15633 Avoid diff anomaly if the new proof has no foreground goal
  printing/proof_diffs.ml
Labels: kind: fix, part: diffs

#15612 setoid_rewrite: try subterms when rewriting produces identity
  doc/changelog/04-tactics/15612-rewrite-with-progress.rst
  plugins/ltac/rewrite.ml
Labels: kind: fix

#15536 Hide the instantiation of patterns with constr variables under an API.
  plugins/ltac/tacinterp.ml
  plugins/ltac/tactic_matching.mli
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2match.ml
  pretyping/constr_matching.ml
  pretyping/constr_matching.mli
  pretyping/patternops.ml
  pretyping/patternops.mli
Labels: kind: cleanup

#15656 [ci] bump elpi to 1.14.1
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/15656-gares-bump-elpi.sh
Labels: kind: infrastructure

#15641 [micromega] add magic number and pcache_version in persistent caches
  lib/objFile.ml
  lib/system.ml
  lib/system.mli
  plugins/micromega/persistent_cache.ml
  test-suite/.csdp.cache.test-suite
Labels: kind: fix, part: micromega

#15658 Fixes "simpl proj" when the projection to reduce has extra arguments
  pretyping/tacred.ml
  test-suite/success/simpl.v
Labels: kind: fix, part: tactics, part: reduction strategies

#15672 Cleanup remnants of ltacprof_cutout test
  test-suite/output-modulo-time/ltacprof_cutoff.out
Labels: kind: cleanup

#15575 Use a dummy term for SProp conversion
  doc/changelog/01-kernel/15575-sprop-dummy-cclosure-red.rst
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/inferCumulativity.ml
  kernel/reduction.ml
  kernel/relevanceops.ml
  kernel/relevanceops.mli
  test-suite/bugs/bug_14014.v
  test-suite/success/sprop_fast.v
Labels: kind: fix, kind: performance

#15671 Make usages of masculine pronouns gender-neutral
  dev/doc/archive/Translator.tex
  dev/doc/universes.md
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/using/tools/coqdoc.rst
  tactics/tactics.ml
Labels: kind: fix, kind: documentation

#15665 [coq_makefile] Quote `OCAMLFIND` everywhere
  tools/CoqMakefile.in
Labels: kind: fix, part: tools, platform: Windows, priority: blocker, part: coq_makefile

#15453 Computation of the guardedness of a subterm assumes too strong invariants on the internal form of fixpoints
  kernel/inductive.ml
  kernel/reduction.ml
  kernel/reduction.mli
Labels: kind: fix, part: kernel

#15674 Don't invoke debug code from async worker processes
  plugins/ltac/tacinterp.ml
  plugins/ltac/tactic_debug.ml
  plugins/ltac/tactic_debug.mli
Labels: kind: fix, part: ltac debugger

#15668 Fixes #15621 by expecting an unchecked fix to however be on an inductive type
  doc/changelog/01-kernel/15668-master+fix15621-unguarded-fix-on-inductive.rst
  kernel/inductive.ml
  test-suite/bugs/bug_15621.v
Labels: kind: fix, part: kernel, part: inductives

#15644 Add variants of lemmas that do not care about the inverse of zero
  doc/changelog/10-standard-library/15644-Rinv0.rst
  theories/Reals/Alembert.v
  theories/Reals/ArithProp.v
  theories/Reals/Binomial.v
  theories/Reals/Cos_plus.v
  theories/Reals/Cos_rel.v
  theories/Reals/Exp_prop.v
  theories/Reals/RIneq.v
  theories/Reals/R_sqr.v
  theories/Reals/R_sqrt.v
  theories/Reals/Ranalysis1.v
  theories/Reals/Ranalysis2.v
  theories/Reals/Ranalysis3.v
  theories/Reals/Ranalysis5.v
  theories/Reals/Ratan.v
  theories/Reals/Rbasic_fun.v
  theories/Reals/Rderiv.v
  theories/Reals/Rfunctions.v
  theories/Reals/RiemannInt.v
  theories/Reals/Rlimit.v
  theories/Reals/Rlogic.v
  theories/Reals/Rpower.v
  theories/Reals/Rsqrt_def.v
  theories/Reals/Rtrigo1.v
  theories/Reals/Rtrigo_alt.v
  theories/Reals/Rtrigo_calc.v
  theories/Reals/Rtrigo_def.v
  theories/Reals/Rtrigo_facts.v
  theories/Reals/Rtrigo_reg.v
  theories/Reals/SeqProp.v
  theories/Reals/SeqSeries.v
  theories/Reals/Sqrt_reg.v
Labels: part: standard library, kind: enhancement

#15424 Forbid non extensible univ decls for Program Definition
  doc/changelog/07-vernac-commands-and-options/15424-progdef-no-udecl.rst
  doc/sphinx/addendum/program.rst
  test-suite/bugs/bug_15410.v
  vernac/comDefinition.ml
Labels: kind: fix

#15678 Small follow-up of the cooking cleanup
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/discharge.ml
Labels: kind: cleanup

#15347 Move `Export` support outside of `Require` libobject
  doc/changelog/07-vernac-commands-and-options/15347-require-no-export.rst
  test-suite/bugs/bug_3556.v
  vernac/library.ml
Labels: kind: fix

#15694 allow failure on metacoq
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#15667 Fixing reference manual wrt the no-impact of the "simpl never" modifier on hnf
  doc/sphinx/language/extensions/arguments-command.rst
Labels: kind: fix, kind: documentation

#15669 Abort is a regular command
  doc/changelog/07-vernac-commands-and-options/15669-abort-time.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  stm/stm.ml
  test-suite/output-modulo-time/abort.out
  test-suite/output-modulo-time/abort.v
  vernac/g_proofs.mlg
  vernac/ppvernac.ml
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.ml
  vernac/vernacinterp.ml
Labels: kind: cleanup, part: vernac

#15698 Remove the allow_failure flag from metacoq CI.
  .gitlab-ci.yml
Labels: kind: infrastructure

#15699 Fix #14021: List.lastn in Ltac2 is wrong.
  user-contrib/Ltac2/List.v
Labels: kind: bug, part: ltac2

#15703 coqdev.el: add missing require to work with Spacemacs lazy loading
  dev/tools/coqdev.el
Labels: kind: infrastructure

#15692 Formally deprecate the only remaining definition the Goal module.
  proofs/goal.mli
Labels: kind: cleanup

#15299 Reorganize the order of subsections under "Semantics" in Ltac chapter
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#15696 Simplify the Cooking API
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/discharge.ml
  kernel/section.ml
Labels: kind: cleanup

#15706 dune-dbg: understand coqchk instead of checker
  dev/dune-dbg.in
Labels: kind: infrastructure

#15527 A parametricity-style algorithm for automatic generation of Boolean equality associated to an inductive type
  dev/ci/ci-fiat_crypto.sh
  doc/changelog/07-vernac-commands-and-options/15527-master+more-principle-scheme-boolean-equality.rst
  kernel/esubst.ml
  kernel/esubst.mli
  test-suite/output/SchemeNames.out
  test-suite/success/SchemeEquality.v
  theories/Floats/PrimFloat.v
  theories/Numbers/Cyclic/Int63/PrimInt63.v
  vernac/auto_ind_decl.ml
  vernac/auto_ind_decl.mli
  vernac/indschemes.ml
Labels: kind: fix, kind: enhancement, part: scheme

#15645 Improve `--help` output for CoqIDE
  boot/usage.ml
  boot/usage.mli
  dev/ci/user-overlays/15645-alizter-alizter+improve-coqide-help.sh
  ide/coqide/coqide.ml
  ide/coqide/coqide_main.ml
  ide/coqide/dune
  ide/coqide/idetop.ml
  sysinit/coqargs.ml
  sysinit/coqargs.mli
  sysinit/coqinit.ml
  sysinit/coqinit.mli
  toplevel/coqc.ml
  toplevel/coqtop.ml
  toplevel/coqtop.mli
  toplevel/workerLoop.ml
Labels: kind: cleanup, kind: documentation, part: IDE

#15489 A pass on the documentation of records
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: cleanup, kind: documentation

#15685 Insert implicit arguments in glob_constr at beginning of extern
  interp/constrextern.ml
  test-suite/output/Utf8Impargs.out
  test-suite/output/Utf8Impargs.v
Labels: kind: fix

#15721 [micromega] Fix pre-processing
  dev/ci/user-overlays/15721-fajb-micromega-interval-analysis.sh
  plugins/micromega/certificate.ml
  test-suite/micromega/bug_15583.v
Labels: kind: fix

#15581 Fix computation of {struct} with implicit generalization
  doc/changelog/02-specification-language/15581-fix-recarg-comput.rst
  interp/constrintern.ml
  test-suite/bugs/bug_13157.v
Labels: kind: fix, part: elaboration

#15727 Remove useless vernac/vernac.mllib
  vernac/vernac.mllib
Labels: kind: cleanup, part: build, kind: internal

#15500 Refine phase separation in module internalization
  interp/modintern.ml
  interp/modintern.mli
  kernel/declarations.ml
  kernel/entries.ml
  kernel/mod_typing.mli
  vernac/declaremods.ml
  vernac/declaremods.mli
Labels: kind: internal

#15688 add example for invariant/covariant/irrelevant universes
  doc/sphinx/addendum/universe-polymorphism.rst
Labels: kind: documentation

#15732 .ocamlformat: remove unused detritus
  .ocamlformat
  plugins/funind/.ocamlformat
  plugins/micromega/.ocamlformat
Labels: kind: cleanup

#15734 More efficient hypothesis selection in tactic matching.
  plugins/ltac/tactic_matching.ml
Labels: kind: performance

#15711 [micromega] Optimise the algorithm to perform interval analysis
  plugins/micromega/certificate.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/linsolve.ml
  plugins/micromega/linsolve.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  test-suite/micromega/bound.v
Labels: kind: performance, part: micromega

#15682 Don't use raw evarconv in ltac2 quotation
  plugins/ltac2/tac2core.ml
  test-suite/bugs/bug_15681.v
Labels: kind: fix

#15652 Deprecate Add LoadPath
  doc/changelog/07-vernac-commands-and-options/15652-depr-add-loadpath.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  vernac/vernacentries.ml
Labels: kind: cleanup

#15630 Term_typing: centralizing the processing of universes
  kernel/term_typing.ml
  kernel/term_typing.mli
Labels: kind: cleanup, part: kernel

#15726 Avoid considering x as a bound variable in glob_ops on `if x then .. else ..`
  pretyping/glob_ops.ml
Labels: kind: fix

#15738 Add a test for #13834.
  test-suite/bugs/bug_13834.v
Labels: kind: fix

#15741 ltac2 apply/eapply: use open_constr in place of constr (fixes #15691)
  doc/changelog/05-tactic-language/15741-ltac2-apply.rst
  test-suite/ltac2/notations.v
  user-contrib/Ltac2/Notations.v
Labels: kind: fix

#15719 Add primitive floating-point Leibniz equality test
  checker/values.ml
  doc/changelog/10-standard-library/15719-float_equal.rst
  kernel/byterun/coq_interp.c
  kernel/cPrimitives.ml
  kernel/cPrimitives.mli
  kernel/float64_common.ml
  kernel/genOpcodeFiles.ml
  kernel/nativevalues.ml
  kernel/nativevalues.mli
  kernel/primred.ml
  kernel/vmemitcodes.ml
  test-suite/success/SchemeEquality.v
  theories/Floats/FloatAxioms.v
  theories/Floats/PrimFloat.v
  theories/extraction/ExtrOCamlFloats.v
  vernac/auto_ind_decl.ml
Labels: kind: enhancement, part: primitive types, part: scheme

#15744 Add a test for #9369.
  test-suite/bugs/bug_9369.v
Labels: kind: fix
