Repository rocq-prover/rocq, pull requests merged in 2022-04, with the labels that each got.

#15712 Restore typing check in notation.eval_constr
  interp/notation.ml
  test-suite/output/NumberNotations.out
  test-suite/output/NumberNotations.v
  test-suite/output/bug_15709.out
  test-suite/output/bug_15709.v
Labels: kind: fix, part: notations

#15887 Always process cmds and tacns (e.g. for doc_gram_verify)
  doc/tools/docgram/doc_grammar.ml
Labels: kind: fix, kind: documentation, kind: infrastructure, kind: internal

#15829 [coqdep] Allow re-entrant calls to Coqdeplib
  tools/coqdep/common.ml
  tools/coqdep/common.mli
  tools/coqdep/coqdep.ml
  tools/coqdep/loadpath.ml
  tools/coqdep/loadpath.mli
Labels: kind: cleanup, kind: internal, part: coqdep

#15754 Remove 8.14 deprecation
  doc/stdlib/index-list.html.template
  parsing/extend.ml
  parsing/extend.mli
  test-suite/bugs/bug_15070.v
  test-suite/ltac2/array_lib.v
  test-suite/primitive/float/add.v
  test-suite/primitive/float/div.v
  test-suite/primitive/float/mul.v
  test-suite/primitive/float/next_up_down.v
  test-suite/primitive/float/sqrt.v
  test-suite/primitive/float/sub.v
  test-suite/success/SchemeEquality.v
  theories/Floats/FloatAxioms.v
  theories/Floats/PrimFloat.v
  theories/Numbers/Cyclic/Int63/Cyclic63.v
  theories/Numbers/Cyclic/Int63/Int63.v
  theories/Numbers/Cyclic/Int63/Ring63.v
  theories/Numbers/Cyclic/Int63/Sint63.v
  theories/Numbers/Cyclic/Int63/Uint63.v
  theories/micromega/ZifyInt63.v
  user-contrib/Ltac2/Bool.v
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/ppvernac.ml
Labels: kind: cleanup

#15852 ExtrOcamlChar: efficient extraction for Ascii.compare
  theories/extraction/ExtrOcamlChar.v
Labels: kind: performance, part: extraction

#15853 Add a nonuniform attribute silencing warning on coercions
  dev/ci/user-overlays/15853-proux01-nonuniform_attr.sh
  doc/changelog/07-vernac-commands-and-options/15853-nonuniform_attr.rst
  doc/sphinx/addendum/implicit-coercions.rst
  test-suite/output/coercions_nonuniform.out
  test-suite/output/coercions_nonuniform.v
  vernac/comAssumption.ml
  vernac/comCoercion.ml
  vernac/comCoercion.mli
  vernac/comInductive.ml
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: enhancement, part: coercions

#15894 Update description of -check-tacs and -check-cmds for doc_grammar
  doc/tools/docgram/README.md
Labels: kind: documentation

#15836 Improve the documentation of inductive command
  dev/ci/user-overlays/15836-proux01-doc_inductive.sh
  doc/sphinx/language/core/coinductive.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/variants.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  vernac/g_vernac.mlg
  vernac/pvernac.ml
  vernac/pvernac.mli
Labels: kind: documentation

#15886 Add -bytecode-compiler flag for enabling vm_compute in coqchk
  checker/checkFlags.ml
  checker/checkFlags.mli
  checker/checker.ml
  doc/changelog/08-cli-tools/15886-enable-vm-coqchk.rst
Labels: kind: feature, part: checker

#15907 Remove leftover printf-style debugging in CoqIDE.
  ide/coqide/coqide.ml
Labels: kind: fix, kind: cleanup, part: IDE

#15890 Remove universe inference from the kernel.
  checker/mod_checking.ml
  engine/uState.ml
  engine/univSubst.ml
  engine/univSubst.mli
  kernel/constr.ml
  kernel/constr.mli
  kernel/mod_typing.ml
  kernel/mod_typing.mli
  kernel/reduction.ml
  kernel/reduction.mli
  kernel/safe_typing.ml
  kernel/subtyping.ml
  kernel/subtyping.mli
  kernel/uGraph.ml
  kernel/uGraph.mli
  kernel/univ.ml
  kernel/univ.mli
  plugins/extraction/extract_env.ml
  plugins/funind/gen_principle.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  tactics/eqschemes.ml
  vernac/declaremods.ml
Labels: kind: cleanup

#15914 Cleanup some module code
  kernel/mod_typing.ml
  vernac/declaremods.ml
Labels: kind: cleanup

#15917 user-overlays/README.md: Fix 404 error
  dev/ci/user-overlays/README.md
Labels: kind: documentation, part: CI

#15880 coq_makefile: flip logic for KEEP_ERROR, avoid double negations in comment
  dev/ci/user-overlays/15880-blaisorblade-coq_mk-delete-on-err.sh
  tools/CoqMakefile.in
Labels: kind: fix, part: coq_makefile

#15904 Changelog for #15754
  doc/changelog/03-notations/15754-changelog_15754.rst
  doc/changelog/10-standard-library/15754-changelog_15754.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: kind: documentation

#15926 Fix a typo in syntax-extensions.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: fix, kind: documentation

#15884 Disable coercions in Number Notation typechecking
  dev/ci/user-overlays/15884-proux01-num_not_no_elab.sh
  doc/changelog/03-notations/15884-num_not_no_elab.rst
  interp/constrintern.ml
  interp/constrintern.mli
  plugins/ltac/g_auto.mlg
  plugins/ltac/internals.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ssr/ssrcommon.ml
  plugins/syntax/number.ml
  pretyping/coercion.ml
  pretyping/coercion.mli
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  proofs/evar_refiner.ml
  tactics/tactics.ml
  test-suite/bugs/bug_15843.v
Labels: kind: fix, part: notations

#15921 Export micromega
  doc/changelog/04-tactics/15921-export_micromega.rst
  doc/sphinx/addendum/micromega.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/micromega/coq_micromega.ml
  plugins/micromega/coq_micromega.mli
  plugins/micromega/g_micromega.mlg
  test-suite/micromega/witness_tactics.v
  theories/micromega/Lia.v
  theories/micromega/Lqa.v
  theories/micromega/Lra.v
  theories/micromega/Psatz.v
Labels: kind: enhancement, part: micromega

#15911 Unconditionally load opaque proofs in coqchk even in norec mode.
  checker/check.ml
Labels: kind: fix, part: checker

#15931 Remove a warning due to leftover code from #15907.
  ide/coqide/coqide_ui.ml
Labels: kind: fix

#15938 Handle deletion of end of sentence char correctly
  ide/coqide/session.ml
Labels: kind: fix, part: IDE

#15940 [ci] Fix fiat-crypto-ocaml build
  dev/ci/ci-fiat_crypto_ocaml.sh
Labels: kind: fix, kind: infrastructure, part: CI

#15939 Handle paste to beginning of buffer correctly.
  ide/coqide/coqOps.ml
  ide/coqide/coqOps.mli
  ide/coqide/session.ml
Labels: kind: fix, part: IDE

#15947 Bump the minimal OCaml version to 4.09.0.
  .gitlab-ci.yml
  INSTALL.md
  coq-core.opam
  coq.opam.docker
  dev/ci/docker/bionic_coq/Dockerfile
  dev/doc/profiling.txt
  dev/dune-workspace.all
  doc/changelog/11-infrastructure-and-dependencies/15947-bump-ocaml-4.09.rst
  dune-project
  tools/configure/configure.ml
Labels: kind: infrastructure

#15935 More compact representation for cooking_info
  checker/values.ml
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/discharge.ml
  kernel/section.ml
  kernel/univ.ml
  kernel/univ.mli
Labels: kind: cleanup

#15923 Use lists instead of arrays for cbv application nodes.
  pretyping/cbv.ml
  pretyping/cbv.mli
Labels: kind: performance

#15872 [vernac] expose API to elaborate declarations
  dev/ci/user-overlays/15872-gares-interp-inductive.sh
  vernac/comAssumption.ml
  vernac/comAssumption.mli
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
  vernac/vernacentries.mli
Labels: kind: internal, part: vernac

#15955 Update bench default ocaml version
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#15950 Fix variance inference for section universes
  checker/checkInductive.ml
  checker/values.ml
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/declarations.ml
  kernel/declareops.ml
  kernel/discharge.ml
  kernel/discharge.mli
  kernel/indTyping.ml
  kernel/indtypes.ml
  kernel/inferCumulativity.ml
  kernel/inferCumulativity.mli
  kernel/safe_typing.ml
  kernel/term_typing.ml
  kernel/term_typing.mli
  test-suite/bugs/bug_15916.v
  vernac/classes.ml
Labels: kind: fix

#15959 critical-bugs entry for #15916
  dev/doc/critical-bugs
Labels: kind: documentation

#15954 Declareops.inductive_make_projection doesn't return option
  kernel/declareops.ml
  kernel/declareops.mli
  kernel/environ.mli
  pretyping/nativenorm.ml
  pretyping/vnorm.ml
Labels: kind: cleanup

#15963 Prevent stack overflow with `do` tactic
  tactics/tacticals.ml
Labels: kind: fix

#15948 [ci] bump elpi (goodbye camlp5, hello menhir)
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  dev/ci/user-overlays/15948-gares-bump-elpi.sh
Labels: kind: infrastructure

#15949 Fix some legacy OCaml behaviours
  ide/coqide/wg_Detachable.ml
  kernel/environ.ml
  topbin/coqtop_byte_bin.ml
  vernac/search.ml
Labels: kind: cleanup

#15915 Stop eagerly normalizing patterns and provide a broken flag instead.
  dev/ci/user-overlays/15915-ppedrot-pattern-of-constr-nf-flag.sh
  interp/constrintern.ml
  plugins/ltac/tacinterp.ml
  pretyping/constr_matching.ml
  pretyping/patternops.ml
  pretyping/patternops.mli
  tactics/hints.ml
Labels: kind: cleanup

#15943 Cache relevance inside projections.
  checker/values.ml
  dev/ci/user-overlays/15943-ppedrot-cache-projection-relevance.sh
  kernel/cClosure.ml
  kernel/declareops.ml
  kernel/indtypes.ml
  kernel/names.ml
  kernel/names.mli
  plugins/extraction/extraction.ml
  pretyping/inductiveops.ml
  vernac/record.ml
Labels: kind: performance

#15966 Fix printing of irrelevant and locked fterms in debugger
  kernel/cClosure.ml
Labels: kind: internal

#15399 CoqIDE: no button shadow (is too slow) #12779
  ide/coqide/coqide.ml
Labels: kind: performance, part: IDE

#15969 [CI] Test Flocq master
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-flocq3.sh
Labels: kind: infrastructure

#15662 inferCumulativity: do not unfold constants unless necessary
  doc/changelog/01-kernel/15662-speed-infer-cumul.rst
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/inferCumulativity.ml
  kernel/reduction.ml
  test-suite/bugs/bug_15916.v
  test-suite/success/CumulInd.v
  test-suite/success/cumulativity.v
Labels: kind: performance

#15964 Fix display of tooltips in script for warnings and errors
  ide/coqide/coqOps.ml
Labels: kind: fix, part: IDE
