Repository rocq-prover/rocq, pull requests merged in 2023-12, with the labels that each got.

#18357 Remove use of Obj.magic in grammar.ml
  gramlib/grammar.ml
Labels: kind: cleanup

#18362 Disable allow failure for fiat/cross-crypto
  .gitlab-ci.yml
Labels: kind: infrastructure

#17340 Inline identity projections in extraction
  plugins/extraction/extraction.ml
  test-suite/output/extraction_projection.out
Labels: part: extraction, kind: enhancement

#17687 eqschemes: Catch errors from `lib_ref` in the logic monad
  tactics/eqschemes.ml
  tactics/ind_tables.ml
  test-suite/bugs/bug_17687.v
Labels: kind: fix

#18293 Guard profiling with a flag in Ltac2.
  doc/changelog/06-Ltac2-language/18293-br-ltac2-profiling.rst
  doc/sphinx/proof-engine/ltac2.rst
  plugins/ltac2/tac2bt.ml
  plugins/ltac2/tac2entries.ml
Labels: kind: performance

#18354 [plugins] (re)-export AST witnesses.
  plugins/extraction/g_extraction.mli
  plugins/ltac/extratactics.mli
  plugins/ssr/ssrparser.mli
  plugins/ssr/ssrtacs.mli
  plugins/ssr/ssrvernac.mli
  plugins/ssrmatching/g_ssrmatching.mli
Labels: priority: blocker, kind: internal

#18330 explain the process of updating std++ and Iris
  dev/ci/ci-basic-overlay.sh
Labels: kind: documentation, kind: internal

#18366 Add refman version link for 8.19
  doc/sphinx/conf.py
Labels: kind: documentation

#18371 Fix typos in universe polymorphism documentation
  doc/sphinx/addendum/universe-polymorphism.rst
  test-suite/success/coercions.v
Labels: kind: documentation

#18367 Fix JSON string escape for profiling data output
  lib/newProfile.ml
Labels: kind: fix, kind: infrastructure, part: bench

#18389 Fix: ounit dependency is for coq.opam not coq-core.opam
  coq-core.opam
  coq.opam
  dune-project
Labels: kind: fix, kind: infrastructure, part: test-suite, part: build

#18379 Make light CI lighter
  .gitlab-ci.yml
Labels: kind: infrastructure

#18386 Fix binder_tactic after #18220 (see #18368)
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/README.md
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_ltac.mlg
  plugins/ltac/pltac.ml
  plugins/ltac/pltac.mli
  plugins/ltac/tacentries.ml
  test-suite/output/bug_18368.out
  test-suite/output/bug_18368.v
Labels: kind: fix, part: ltac, part: parser

#18388 [CI] Temporarily turn jasmin allow_failure
  .gitlab-ci.yml
Labels: kind: infrastructure

#18325 Reimplement Ncring_tac reification in ltac instead of typeclasses
  doc/changelog/11-standard-library/18325-reify-ring-ltac.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_auto.mlg
  test-suite/success/Nsatz.v
  theories/nsatz/Nsatz.v
  theories/nsatz/NsatzTactic.v
  theories/setoid_ring/Cring.v
  theories/setoid_ring/Ncring_tac.v
Labels: kind: cleanup, kind: performance

#18350 Program: don't error when Program.Tactics / Program.Wf are not required unless necessary
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
Labels: kind: user messages

#18376 Consistent permissions in the stdlib
  theories/Logic/Adjointification.v
  theories/Reals/Rtrigo_facts.v
Labels: kind: internal

#16126 Add support for output directory in extraction
  doc/changelog/08-vernac-commands-and-options/16126-extraction-output.rst
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/practical-tools/coq-commands.rst
  dune-project
  lib/system.ml
  lib/system.mli
  plugins/extraction/extract_env.ml
  plugins/extraction/table.ml
  plugins/extraction/table.mli
  test-suite/cram/dune
  test-suite/cram/extraction-output1.t/a.v
  test-suite/cram/extraction-output1.t/run.t
  test-suite/cram/extraction-output2.t/a.v
  test-suite/cram/extraction-output2.t/run.t
Labels: part: extraction, kind: enhancement

#18393 Fixes #12755 and #18392: argument names wrongly shifted in nested sections
  doc/changelog/02-specification-language/18393-master+fixes18392-12755-arguments-nested-section.rst
  pretyping/arguments_renaming.ml
  test-suite/bugs/bug_12755.v
Labels: kind: fix, part: implicit arguments

#18349 Fix #18193 don't trigger file deprecation transitively
  checker/values.ml
  doc/sphinx/using/libraries/writing.rst
  lib/deprecation.ml
  lib/deprecation.mli
  library/library_info.ml
  library/library_info.mli
  test-suite/Makefile
  test-suite/output/library_attributes_require_transitive.out
  test-suite/output/library_attributes_require_transitive.v
  test-suite/prerequisite/library_attributes_require.v
  vernac/library.ml
Labels: kind: fix, kind: user messages

#18369 Ltac2.Char.of_int: use `throw` instead of raw exception for invalid argument
  plugins/ltac2/tac2core.ml
  user-contrib/Ltac2/Char.v
Labels: kind: fix, part: ltac2

#18402 Pin jasmin
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure, part: CI

#18382 [compat] Split ltac2 compat to its own file.
  doc/stdlib/index-list.html.template
  sysinit/coqargs.ml
  theories/Compat/Coq818.v
  user-contrib/Ltac2/Compat/Coq818.v
Labels: kind: fix, part: build

#18359 [build] Bump minimal dune version to 3.6.1
  .github/workflows/ci-macos.yml
  .gitlab-ci.yml
  INSTALL.md
  clib/cSet.mli
  clib/unionfind.mli
  coq-core.opam
  coq-doc.opam
  coq-stdlib.opam
  coq.opam
  coqide-server.opam
  coqide.opam
  dev/ci/docker/old_ubuntu_lts/Dockerfile
  doc/changelog/11-standard-library/18359-dune_35.rst
  dune
  dune-project
  library/goptions.mli
  pretyping/detyping.mli
  stm/asyncTaskQueue.mli
  theories/dune.disabled
  user-contrib/Ltac2/dune.disabled
Labels: kind: infrastructure, kind: compatibility, part: build

#18403 [checker] Fix discrepancy in raw_level definition.
  checker/values.ml
Labels: kind: fix, part: checker, kind: kernel segfault/exploit

#18398 8.19: put version number in CI image names
  .gitlab-ci.yml
Labels: kind: infrastructure

#18221 Fix various issues around recarg computation
  interp/constrexpr_ops.ml
  interp/constrexpr_ops.mli
  interp/constrintern.ml
  pretyping/pretyping.ml
  test-suite/bugs/bug_18215.v
  vernac/comFixpoint.ml
Labels: kind: fix, part: inductives

#18405 Remove allow_failure on Jasmin
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#18410 Ltac2: desugar `[| |]` to `Array.empty` instead of `Array.of_list []`
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2quote.ml
  plugins/ltac2/tac2quote.mli
Labels: kind: enhancement

#18406 coqchk: fix mismatches between values.ml and actual types
  checker/check.ml
  checker/values.ml
  dev/doc/critical-bugs
  topbin/coqnative_bin.ml
Labels: kind: fix, part: checker, kind: kernel segfault/exploit

#18391 Some improvements with the "with" syntax of some tactics
  proofs/clenv.ml
  tactics/eClause.ml
  tactics/eClause.mli
  tactics/equality.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  test-suite/output/apply_with.out
  test-suite/output/apply_with.v
Labels: kind: fix, part: tactics

#18413 Fix overlay pull in CI
  dev/ci/ci-common.sh
Labels: kind: fix, kind: infrastructure

#17934 Give `Z.to_euclidean_division_equations` more power
  doc/changelog/04-tactics/17934-more-nia.rst
  doc/sphinx/addendum/micromega.rst
  test-suite/micromega/div_mod.v
  test-suite/success/Nia.v
  theories/omega/PreOmega.v
Labels: kind: enhancement, part: micromega

#18419 [build] [gen_rules] Refactor and remove useless case
  tools/dune_rule_gen/coq_rules.ml
  tools/dune_rule_gen/coq_rules.mli
  tools/dune_rule_gen/gen_rules.ml
Labels: kind: cleanup, part: build, kind: internal

#18384 [build] [gen_rules] Don't allow cyclic deps between stdlib and ltac2
  tools/dune_rule_gen/coq_rules.ml
Labels: kind: infrastructure, part: build

#18408 ci-menhir: don't set version to $(date) if already done
  dev/ci/ci-menhir.sh
Labels: kind: infrastructure

#18427 There is no IF_then_else in the stdlib
  doc/sphinx/language/coq-library.rst
Labels: kind: documentation, part: standard library

#18426 Fix printing of Remove Hints
  vernac/ppvernac.ml
Labels: kind: user messages

#18430 [cosmetic] coqdoc: fix typo in help message
  tools/coqdoc/cmdArgs.ml
Labels: kind: fix, part: coqdoc

#18213 Support TIMED=1 in test suite + some preliminary cleanups
  .github/workflows/ci-macos.yml
  .gitignore
  .gitlab-ci.yml
  dev/bench/bench.sh
  test-suite/Makefile
  test-suite/bugs/bug_181.v
  test-suite/bugs/bug_266.v
  test-suite/dune
  test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v
  test-suite/stm/arg_filter_1.v
Labels: kind: infrastructure, kind: performance, kind: enhancement

#18143 Debug printing for relevance marks
  dev/ci/user-overlays/18143-SkySkimmer-print-relevance.sh
  doc/sphinx/addendum/sprop.rst
  interp/constrexpr.mli
  interp/constrexpr_ops.ml
  interp/constrexpr_ops.mli
  interp/constrextern.ml
  interp/constrintern.ml
  interp/implicit_quantifiers.ml
  interp/notation_ops.ml
  parsing/g_constr.mlg
  plugins/funind/gen_principle.ml
  plugins/funind/glob_term_to_relation.ml
  plugins/funind/glob_termops.ml
  plugins/funind/indfun_common.ml
  plugins/ltac/g_obligations.mlg
  plugins/ltac/g_tactic.mlg
  plugins/ltac/pptactic.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrvernac.mlg
  plugins/ssrmatching/ssrmatching.ml
  pretyping/detyping.ml
  pretyping/detyping.mli
  pretyping/glob_ops.ml
  pretyping/glob_ops.mli
  pretyping/glob_term.mli
  pretyping/patternops.ml
  pretyping/pretyping.ml
  printing/ppconstr.ml
  printing/proof_diffs.ml
  tactics/hipattern.ml
  test-suite/output/DebugRelevances.out
  test-suite/output/DebugRelevances.v
  vernac/comDefinition.ml
  vernac/comFixpoint.ml
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: user messages

#17927 add Z.divide support for Z.to_euclidean_division_equations
  doc/changelog/04-tactics/17927-divide_to_euclidean_division_equations.rst
  doc/sphinx/addendum/micromega.rst
  test-suite/success/Nia.v
  theories/omega/PreOmega.v
Labels: part: standard library, kind: enhancement, part: micromega
