Repository rocq-prover/rocq, pull requests merged in 2023-08, with the labels that each got.

#17906 Ensure that About on a section name do not fail with an anomaly
  kernel/names.ml
  kernel/names.mli
  test-suite/output/Nametab.out
  test-suite/output/Nametab.v
  vernac/prettyp.ml
Labels: kind: fix, part: sections

#17894 Add `Ltac2.Constr.{is_float,is_uint63,is_array}`
  doc/changelog/06-Ltac2-language/17894-is_float.rst
  user-contrib/Ltac2/Constr.v
Labels: kind: enhancement, part: ltac2

#17848 Add waterproof to ci
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-waterproof.sh
Labels: kind: infrastructure

#17889 Fixes #17817: refer to actual chosen extraction language in extraction error messages
  doc/changelog/13-misc/17889-master+fix17817-extraction-prop-elim-error-not-ocaml-specific.rst
  plugins/extraction/table.ml
Labels: kind: fix, kind: user messages, part: extraction

#17835 coq_makefile: make .filestoinstall during the rule needing it
  tools/CoqMakefile.in
Labels: kind: infrastructure

#17912 Update CACHEKEY in preparation for release
  .gitlab-ci.yml
Labels: kind: infrastructure

#17917 [release] update changelog w.r.t. the latest backports on v8.18
  doc/changelog/01-kernel/17872-fix_17871.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#17892 Fixes #17071: appropriate error instead of anomaly in the presence of notations with constructors applied to too many arguments in pattern-matching
  doc/changelog/03-notations/17892-master+fix17071-anomaly-notation-wrong-number-constructor-arguments.rst
  interp/constrintern.ml
  test-suite/output/Cases.out
  test-suite/output/Cases.v
Labels: kind: fix, part: notations

#17914 faster setoid_ring/Ncring_polynom.v
  theories/setoid_ring/Ncring_polynom.v
Labels: kind: performance

#17787 [stdlib] Some injectivity lemmas for lists
  doc/changelog/11-standard-library/17787-app_inj_pivot.rst
  theories/Lists/List.v
Labels: part: standard library, kind: enhancement

#17902 Fixes #11237: support constructor with parameters in primitive notations for patterns
  doc/changelog/03-notations/17902-master+fix11237-constructor-parameters-in-prim-notation-for-pattern.rst
  interp/constrintern.ml
  interp/notation.ml
  interp/notation.mli
  test-suite/output/StringSyntaxPrimitive.v
  test-suite/success/Notations2.v
Labels: kind: fix, part: notations

#17919 [release] bump version to 8.18+rc1
  tools/configure/configure.ml
Labels: kind: infrastructure

#17913 Advertise Ltac2 in Ltac chapter.
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation

#17785 Split Docker images in two: one for base and one for edge.
  .gitlab-ci.yml
  dev/ci/README-users.md
  dev/ci/ci-fiat_crypto_ocaml.sh
  dev/ci/docker/edge_ubuntu/Dockerfile
  dev/ci/docker/old_ubuntu_lts/Dockerfile
  dev/doc/release-process.md
  dev/tools/check-cachekey.sh
  doc/README.md
Labels: kind: infrastructure

#17840 [coqidetop] Fix print depth setting for Richpp clients
  ide/coqide/idetop.ml
Labels: kind: fix, part: CoqIDE

#17915 Remove geocoq from CI
  .gitlab-ci.yml
  Makefile.ci
  dev/bench/bench.sh
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-geocoq.sh
  dev/ci/nix/GeoCoq.nix
  dev/ci/nix/default.nix
Labels: kind: infrastructure, kind: ci-failure

#17909 Produce warning+dynamic error on missing notation variable in Ltac2
  plugins/ltac2/tac2core.ml
  test-suite/bugs/bug_17833.v
Labels: kind: fix

#17907 For arguments scopes, statically know the list of available scopes (technical PR)
  clib/cMap.ml
  clib/cMap.mli
  clib/hMap.ml
  interp/notation.ml
  interp/notation.mli
  test-suite/output/ArgumentsScope.out
  test-suite/output/ArgumentsScope.v
  vernac/metasyntax.ml
Labels: kind: cleanup, part: sections

#17875 Add printer support for grammar entries with non-necessary-lower level on their right-hand side
  dev/ci/user-overlays/17875-herbelin-printer-support-for-entries-arbitrary-level-on-right.sh
  interp/constrextern.ml
  interp/notation.ml
  interp/notation.mli
  interp/notationextern.mli
  plugins/ltac/pptactic.ml
  printing/ppconstr.ml
  printing/ppconstr.mli
  printing/ppextend.ml
  printing/ppextend.mli
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  vernac/metasyntax.ml
Labels: kind: fix, part: notations, part: printer

#17827 Notations: collecting the notation variables binding in a given notation variable
  dev/ci/user-overlays/17827-herbelin-master+collecting-ntn-vars-binding-in-ntn-var.sh
  interp/constrintern.ml
  interp/constrintern.mli
  interp/genintern.ml
  interp/genintern.mli
  interp/notation_ops.ml
  interp/notation_term.mli
  interp/notationextern.ml
  vernac/metasyntax.ml
Labels: part: notations, kind: internal

#17930 Fix build after concurrent merge of #17875 and #17827
  interp/constrextern.ml
Labels: kind: fix

#17800 Add introduction to the section on variants and inductive types in the reference manual
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/sorts.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/language/extensions/evars.rst
Labels: kind: documentation, part: inductives

#17942 Exporting a version of pr_constr_expr/pr_lconstr_expr ensured not to be overriden
  printing/ppconstr.ml
  printing/ppconstr.mli
Labels: kind: cleanup

#17873 Remove dead code in induction internals.
  tactics/induction.ml
Labels: kind: cleanup

#17949 [CI] Add new dependency for VsCoq
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
Labels: kind: infrastructure, part: CI

#17944 test-suite: Add support for customizing coqchk args
  test-suite/Makefile
Labels: kind: infrastructure, part: test-suite

#17929 Constant_typing: eliminating the detour via type "result"
  kernel/constant_typing.ml
  kernel/constant_typing.mli
  kernel/safe_typing.ml
Labels: kind: cleanup

#17928 Don't use boolean in interp_search_restriction, and expose it
  dev/ci/user-overlays/17928-SkySkimmer-search-restr.sh
  vernac/comSearch.ml
  vernac/comSearch.mli
  vernac/g_vernac.mli
  vernac/search.ml
  vernac/search.mli
  vernac/vernacexpr.mli
Labels: kind: internal

#17924 Bidirectionality in Ltac2 typechecking + type annotations for goal/constr_matching scopes
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2quote.ml
  plugins/ltac2/tac2typing_env.ml
  user-contrib/Ltac2/Pattern.v
Labels: kind: redesign, kind: user messages

#17679 Helper module to define comparison functions, and use it in Constr.compare
  kernel/constr.ml
  lib/util.ml
  lib/util.mli
Labels: kind: cleanup

#17972 Track coq-master branch of VsCoq
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#17938 Improve the infrastructure of `nia` tests a bit
  test-suite/success/Nia.v
Labels: kind: infrastructure, part: micromega, part: test-suite

#17974 Fix "inconsistent assumptions" error message
  vernac/library.ml
Labels: kind: fix, kind: user messages

#17887 Fixes #17417: normalize hint modes and hint disjunctive paths
  doc/changelog/04-tactics/17887-master+fixes17417-hint-paths-modes-redundancies.rst
  tactics/hints.ml
  test-suite/output/HintLocality.out
Labels: kind: fix, part: hints

#17789 Fix `Typeclasses Unique Instances` option.
  tactics/class_tactics.ml
Labels: kind: fix

#17978 Statically eta-expand VERNAC actions in coqpp.
  coqpp/coqpp_main.ml
  vernac/vernacextend.mli
Labels: kind: fix

#17954 coqdep: Windows: fix normalisation of paths containing \
  tools/coqdep/lib/fl.ml
Labels: kind: infrastructure

#17989 Update ssrbool.v
  theories/ssr/ssrbool.v
Labels: kind: documentation, part: ssreflect

#17988 Addresses #17985: error on duplicate notation variable levels
  doc/changelog/03-notations/17988-master+fix17963-search-anomaly-with-evars.rst
  test-suite/output/wish_17985.out
  test-suite/output/wish_17985.v
  vernac/metasyntax.ml
Labels: part: notations, kind: enhancement
