Repository rocq-prover/rocq, pull requests merged in 2023-11, with the labels that each got.

#18068 Fix "r <num>" and "r <string>" commands in coqtop Ltac debugger
  doc/changelog/05-Ltac-language/18068-typed_debug_cmds.rst
  ide/coqide/wg_MessageView.ml
  plugins/ltac/tactic_debug.ml
Labels: kind: fix, part: ltac, part: ltac debugger

#18232 Make sure the perf stubs have "coq" in their name
  lib/dune
  perf/dune
  perf/perf.c
Labels: kind: infrastructure

#18203 Ltac2: add primitive APIs for projections
  plugins/ltac2/tac2core.ml
  user-contrib/Ltac2/Ind.v
  user-contrib/Ltac2/Proj.v
Labels: kind: enhancement

#18102 Add setoid_rewrite to Ltac2
  doc/changelog/06-Ltac2-language/18102-ltac2-setoid-rewrite.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  plugins/ltac2/tac2qexpr.mli
  plugins/ltac2/tac2quote.ml
  plugins/ltac2/tac2quote.mli
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ltac2/tac2tactics.mli
  plugins/ltac2/tac2types.mli
  test-suite/ltac2/std_tactics.v
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
Labels: kind: feature

#18225 Abstract away the type of tokens in number notations.
  interp/notation.ml
Labels: kind: cleanup

#18247 Fix the perf library loaded for debug printer.
  dev/db
Labels: kind: infrastructure

#18171 Fix FFi usage in coq_interp.c
  kernel/byterun/coq_interp.c
Labels: kind: fix

#18230 Fixes #18223: nested entry coercions possibly printed in the wrong order depending on the order in which coercions were declared
  doc/changelog/03-notations/18230-master+fixes18223-wrong-coercion-order-on-right.rst
  interp/notation.ml
  test-suite/output/bug_18223.out
  test-suite/output/bug_18223.v
Labels: kind: fix, part: notations, part: custom

#18220 Moving binder_tactic at a lower level to prevent needing the parsing recovery mode
  doc/sphinx/proof-engine/ltac.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_ltac.mlg
  plugins/ltac/pptactic.ml
Labels: kind: enhancement, part: parser

#18228 Micromega: avoid generating duplicate pivots in fourier_small
  plugins/micromega/certificate.ml
  test-suite/bugs/bug_17960.v
Labels: kind: fix

#18243 Followup of #17993, fixes #18239: anomaly on triggering conditions for simpl on encapsulated mutual fixpoints
  doc/changelog/04-tactics/18243-master+fix18239-followup-17993-simpl-triggering-condition.rst
  pretyping/tacred.ml
  test-suite/success/simpl.v
Labels: kind: fix, part: reduction strategies

#17576 Let with Qed: produce really-Qed side definition
  dev/ci/user-overlays/17576-SkySkimmer-let-abstract.sh
  doc/changelog/08-vernac-commands-and-options/17576-let-abstract.rst
  doc/sphinx/language/core/sections.rst
  test-suite/bugs/bug_17576_1.v
  vernac/comAssumption.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/vernacentries.ml
Labels: kind: enhancement

#18245 Catch NotConvertible from checking case parameters in typeops
  checker/checker.ml
  kernel/type_errors.ml
  kernel/type_errors.mli
  kernel/typeops.ml
  test-suite/bugs/bug_16954.v
  vernac/himsg.ml
Labels: kind: user messages

#18234 Correctly print internal exns (StuckGoal etc) in typeclasses debug
  tactics/class_tactics.ml
Labels: kind: user messages

#18258 Detect linux better for the perf library.
  perf/dune
Labels: kind: fix, kind: infrastructure

#18226 Fix DOWNLOAD_ONLY usage in quickchick_test script
  dev/ci/ci-quickchick_test.sh
Labels: kind: infrastructure

#18235 Dead code elimination in Micromega
  plugins/micromega/zify.ml
Labels: kind: cleanup

#18250 Remove Names API deprecated in Coq 8.13.
  kernel/names.ml
  kernel/names.mli
Labels: kind: cleanup

#18263 test-suite/complexity/constructor: -native-compiler no
  test-suite/complexity/constructor.v
Labels: kind: infrastructure

#18207 Revert "Stop catching anomalies from conversion"
  pretyping/pretype_errors.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  test-suite/bugs/bug_17910.v
  test-suite/bugs/bug_18126.v
  test-suite/bugs/bug_18206.v
Labels: kind: fix

#18265 TimeFileMaker: use accurate sum in sum_times
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-real.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/001-correct-diff-sorting-order/time-of-build-both-user.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/002-single-file-sorting/time-of-build-pretty-real.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/002-single-file-sorting/time-of-build-pretty-user.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/time-of-build-pretty.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/004-per-file-fuzz/foo-real.v.timing.diff.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/004-per-file-fuzz/foo-user.v.timing.diff.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-real.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user-absolute.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user-auto.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user-diff.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/005-correct-diff-sorting-order-mem/time-of-build-both-user.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/006-zero-before/time-of-build-both.log.expected
  test-suite/coq-makefile/timing/precomputed-time-tests/007-no-output-sync/time-of-build.log.expected
  tools/TimeFileMaker.py
Labels: kind: infrastructure

#17704 Ltac1 and Ltac2: don't normalize evars for open_constr:()
  doc/changelog/04-tactics/17704-open-constr-no-expand.rst
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2core.ml
Labels: kind: performance

#17136 [gramlib] Move syntax errors to Grammar.
  dev/ci/user-overlays/17136-ppedrot-stream_error_to_gramlib.sh
  gramlib/grammar.ml
  gramlib/grammar.mli
  gramlib/stream.ml
  gramlib/stream.mli
  interp/constrexpr_ops.ml
  interp/constrintern.ml
  parsing/cLexer.ml
  vernac/comInductive.ml
  vernac/himsg.ml
  vernac/record.ml
Labels: kind: cleanup

#18246 Stop computing kername hashes lazily.
  checker/values.ml
  kernel/names.ml
Labels: kind: cleanup

#18268 Remove deprecated API from Inductiveops.
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
Labels: kind: cleanup

#18240 Static invariants on the environment module from Micromega.
  plugins/micromega/certificate.ml
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
Labels: kind: cleanup

#12096 Add cardinal_Add_In to FMapFacts
  doc/changelog/11-standard-library/12096-FMapFacts_cardinal_3.rst
  theories/FSets/FMapFacts.v
Labels: kind: feature, part: standard library

#18288 Fix doc: import category "notations" does not include abbreviations
  doc/sphinx/language/core/modules.rst
Labels: kind: fix, kind: documentation

#18272 Add comment about PeanoNat.div_mod_eq unused hypothesis + slight cleanup
  theories/Arith/PeanoNat.v
Labels: kind: documentation

#18289 Doc: don't hide unsafe declarations of inductives
  doc/sphinx/language/core/inductive.rst
Labels: kind: documentation

#17832 Reformulating the grammar of rewstrategy with GRAMMAR EXTEND
  dev/ci/user-overlays/17832-herbelin-master+rewstrategy-explicit-assoc.sh
  doc/changelog/04-tactics/17832-master+rewstrategy-explicit-assoc.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_rewrite.mlg
  tactics/rewrite.ml
  test-suite/output/rewrite_strat.out
  test-suite/output/rewrite_strat.v
Labels: kind: fix, part: rewriting tactics

#18278 Small cleanups around the ssr implementation of applyn
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
Labels: kind: cleanup

#18286 Revert "bench with sort poly overlays" (should have been removed before merge)
  dev/bench/bench.sh
Labels: kind: internal

#18255 Scheme Equality: ensure universe polymorphism constraints of statements are collected
  test-suite/success/SchemeEquality.v
  vernac/auto_ind_decl.ml
Labels: kind: fix, part: universes, part: scheme

#18276 Do not use the legacy pattern_of_constr for variables from typed patterns
  plugins/ltac/tacinterp.ml
Labels: kind: cleanup

#18279 Simplifying the internals of the "hnf" tactic
  dev/ci/user-overlays/18279-ppedrot-tacred-factor-red-product.sh
  plugins/ltac/coretactics.mlg
  plugins/ltac/g_tactic.mlg
  plugins/ltac/tacintern.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ssr/ssrcommon.ml
  pretyping/tacred.ml
  pretyping/tacred.mli
  tactics/genredexpr.mli
  tactics/induction.ml
  tactics/ppred.ml
  tactics/redexpr.ml
  tactics/redops.ml
  tactics/rewrite.ml
  tactics/tactics.ml
Labels: kind: cleanup

#18296 doc_grammar: stricter regex for insertprodn
  doc/tools/docgram/doc_grammar.ml
Labels: kind: documentation, kind: infrastructure

#18189 Change Menhir branch target in ci-basic_overlay.sh
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-menhir.sh
Labels: kind: infrastructure

#18262 Restore tailrecness of CList.filter
  clib/cList.ml
Labels: kind: performance

#18267 [CI] Use a lighter target in fiat-crypto-ocaml
  dev/ci/ci-fiat_crypto_ocaml.sh
Labels: kind: infrastructure, part: CI

#18287 [build] [opam] Pass -p correctly to `make dunestrap` so we don't rebuild things in coq-core
  Makefile
  coq-stdlib.opam
  coq-stdlib.opam.template
Labels: kind: fix, part: build

#18294 Introduce a dedicated type for evar kinds in raw / glob terms
  dev/ci/user-overlays/18294-ppedrot-glob-evar-kinds.sh
  engine/evar_kinds.ml
  engine/evar_kinds.mli
  interp/constrexpr.mli
  interp/constrexpr_ops.ml
  interp/constrextern.ml
  interp/constrintern.ml
  interp/notation.ml
  interp/notation_ops.ml
  interp/notation_term.mli
  parsing/g_constr.mlg
  plugins/cc/cctac.ml
  plugins/funind/glob_termops.ml
  plugins/ltac/comRewrite.ml
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_tactic.mlg
  plugins/ltac2/g_ltac2.mlg
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrview.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/cases.ml
  pretyping/detyping.ml
  pretyping/glob_ops.ml
  pretyping/glob_ops.mli
  pretyping/glob_term.mli
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  printing/ppconstr.ml
  tactics/hipattern.ml
  vernac/classes.ml
  vernac/comDefinition.ml
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
Labels: kind: cleanup

#18280 Move relevance outside of case_info
  checker/values.ml
  dev/ci/user-overlays/18280-SkySkimmer-ci-relevance.sh
  dev/top_printers.ml
  engine/eConstr.ml
  engine/eConstr.mli
  engine/termops.ml
  engine/univSubst.ml
  kernel/cClosure.ml
  kernel/constr.ml
  kernel/constr.mli
  kernel/conversion.ml
  kernel/genlambda.ml
  kernel/inductive.ml
  kernel/inductive.mli
  kernel/inferCumulativity.ml
  kernel/mod_subst.ml
  kernel/relevanceops.ml
  kernel/typeops.ml
  kernel/typeops.mli
  kernel/vars.ml
  plugins/extraction/extraction.ml
  plugins/firstorder/unify.ml
  plugins/funind/recdef.ml
  plugins/ltac2/tac2core.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/cases.ml
  pretyping/cbv.ml
  pretyping/constr_matching.ml
  pretyping/detyping.ml
  pretyping/evarconv.ml
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/nativenorm.ml
  pretyping/patternops.ml
  pretyping/pretype_errors.mli
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/retyping.ml
  pretyping/typing.ml
  pretyping/unification.ml
  pretyping/vnorm.ml
  proofs/clenv.ml
  tactics/autorewrite.ml
  tactics/cbn.ml
  tactics/eqschemes.ml
  tactics/equality.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  user-contrib/Ltac2/Constr.v
  vernac/assumptions.ml
  vernac/auto_ind_decl.ml
  vernac/himsg.ml
  vernac/record.ml
Labels: kind: cleanup

#18284 Correctly run tests with opam + use in bench
  .gitlab-ci.yml
  coq.opam
  coq.opam.template
  dev/bench/bench.sh
  dune
  test-suite/Makefile
  test-suite/complexity/pattern.v
  test-suite/complexity/pretyping.v
  test-suite/dune
  test-suite/misc/deps-order-distinct-root.sh
  test-suite/misc/deps-order-from.sh
  test-suite/misc/deps-order-subdir1-file.sh
  test-suite/misc/deps-order-subdir2-file.sh
  test-suite/misc/deps-order-subdir3-file.sh
  test-suite/misc/deps-order.sh
  test-suite/misc/deps-utf8.sh
  test-suite/misc/external-deps.sh
  test-suite/report.sh
Labels: kind: fix, kind: infrastructure, part: build, part: bench

#18237 update-compat --release for 8.19
  doc/stdlib/index-list.html.template
  sysinit/coqargs.ml
  test-suite/success/CompatOldOldFlag.v
  test-suite/tools/update-compat/run.sh
  theories/Compat/Coq816.v
Labels: kind: infrastructure

#18028 Add coq-neural-net-interp-computed to bench
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#18315 Fix check that fixpoints on SProp inductives produce SProp values
  kernel/inductive.ml
  test-suite/bugs/bug_18314.v
Labels: kind: fix

#18313 Fix relevance handling in Tactics.mutual_fix
  tactics/tactics.ml
  test-suite/bugs/bug_18308.v
Labels: kind: fix, part: SProp

#18311 Ltac2: add ikfprintf API to do conditional printing
  doc/changelog/06-Ltac2-language/18311-ltac2-ikfprintf.rst
  plugins/ltac2/tac2core.ml
  test-suite/ltac2/printf.v
  user-contrib/Ltac2/Message.v
Labels: kind: enhancement, part: ltac2

#17667 Support quotations (genargs) in patterns
  dev/ci/user-overlays/17667-SkySkimmer-pattern-quotations.sh
  doc/changelog/06-Ltac2-language/17667-pattern-quotations.rst
  doc/sphinx/proof-engine/ltac2.rst
  interp/constrextern.ml
  interp/constrextern.mli
  interp/constrintern.ml
  interp/constrintern.mli
  interp/genintern.ml
  interp/genintern.mli
  interp/notation_ops.ml
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacsubst.ml
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2quote.mli
  plugins/ssr/ssrparser.mlg
  plugins/ssrmatching/ssrmatching.ml
  pretyping/constr_matching.ml
  pretyping/detyping.ml
  pretyping/detyping.mli
  pretyping/genarg.ml
  pretyping/genarg.mli
  pretyping/gensubst.ml
  pretyping/gensubst.mli
  pretyping/pattern.mli
  pretyping/patternops.ml
  pretyping/patternops.mli
  printing/printer.mli
  tactics/autorewrite.ml
  tactics/btermdn.ml
  tactics/hints.ml
  test-suite/bugs/bug_11641.v
Labels: kind: feature, part: ltac2

#18273 Ltac2: support "head" reduction flag
  doc/changelog/06-Ltac2-language/18273-ltac2-head-red.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2qexpr.mli
  plugins/ltac2/tac2quote.ml
  plugins/ltac2/tac2stdlib.ml
  test-suite/output/reduction.out
  test-suite/output/reduction.v
  user-contrib/Ltac2/RedFlags.v
  user-contrib/Ltac2/Std.v
Labels: kind: enhancement, part: ltac2

#17933 Add more tests for `nia`
  test-suite/success/Nia.v
Labels: kind: cleanup, kind: infrastructure, part: micromega, part: test-suite

#18323 Fix the wrong type declaration of [Ltac2.String.app].
  user-contrib/Ltac2/String.v
Labels: kind: fix

#18324 gitignore *.real in test-suite/misc
  test-suite/misc/.gitignore
Labels: kind: infrastructure

#18241 Simplify the encoding of the recursive disjunctive-conjunctive structure of (co)inductive types in rtree.ml by taking nodes of arrays of arrays
  checker/values.ml
  dev/base_include
  dev/top_printers.ml
  dev/top_printers.mli
  kernel/declareops.ml
  kernel/declareops.mli
  lib/rtree.ml
  lib/rtree.mli
Labels: kind: cleanup

#18197 Ltac2: make argument order of fold combinators same as OCaml
  doc/changelog/06-Ltac2-language/18197-ltac2-fold-order.rst
  test-suite/ltac2/array_lib.v
  test-suite/ltac2/map.v
  user-contrib/Ltac2/Array.v
  user-contrib/Ltac2/List.v
Labels: kind: cleanup, part: ltac2

#18303 Remove dead API from Micromega.
  plugins/micromega/mutils.ml
  plugins/micromega/mutils.mli
  plugins/micromega/polynomial.ml
  plugins/micromega/polynomial.mli
  plugins/micromega/simplex.ml
  plugins/micromega/simplex.mli
  plugins/micromega/vect.ml
  plugins/micromega/vect.mli
Labels: kind: cleanup

#18312 Turn Impargs.implicit_status into a record.
  dev/ci/user-overlays/18312-ppedrot-detuplify-impargs.sh
  interp/constrintern.ml
  interp/impargs.ml
  interp/impargs.mli
  vernac/comProgramFixpoint.ml
  vernac/prettyp.ml
Labels: kind: cleanup

#18305 Faster implementation of hint databases
  tactics/hints.ml
  test-suite/bugs/bug_18305.v
Labels: kind: performance

#18191 HMap: avoid hashing when map is empty, use Int.Map combinators more
  clib/hMap.ml
  clib/int.ml
Labels: kind: cleanup, kind: performance

#18285 Unit test for CList.filter
  test-suite/unit-tests/clib/clist.ml
Labels: kind: infrastructure

#18260 Cache set of undefined impossible case evars in evar_flags
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  pretyping/evarconv.ml
  pretyping/pretyping.ml
  test-suite/bugs/bug_18260_1.v
Labels: kind: performance

#18328 explain how to fix Perennial
  dev/ci/ci-basic-overlay.sh
Labels: kind: documentation, part: CI

#18157 Ltac2: use preterm in exact / eexact
  doc/changelog/06-Ltac2-language/18157-ltac2-exact-preterm.rst
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  test-suite/bugs/bug_12827.v
  test-suite/bugs/bug_17233.v
  test-suite/output/PrintGenarg.out
  test-suite/output/bug_17594.out
  user-contrib/Ltac2/Constr.v
  user-contrib/Ltac2/Notations.v
Labels: kind: enhancement, part: ltac2

#17856 Notation wish #17845: add support for notations with recursive binders involving "let" and "match"
  doc/changelog/03-notations/17856-master+more-general-form-binders-recursive-notation.rst
  interp/constrintern.ml
  interp/notation_ops.ml
  pretyping/glob_ops.ml
  pretyping/glob_ops.mli
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
Labels: part: notations, kind: enhancement

#18329 Fix mistake about iris in ci-basic-overlays
  dev/ci/ci-basic-overlay.sh
Labels: kind: documentation, part: CI

#18297 Port deprecated code related to library references in ssr.
  plugins/ssr/ssrequality.ml
Labels: kind: cleanup

#17339 Fix use of dot notation for non-primitive projections in functors for OCaml extraction
  plugins/extraction/extraction.ml
  test-suite/output/extraction_projection.out
Labels: kind: fix, part: extraction

#18333 CI: delete .git of downloaded projects to reduce artifact size
  dev/ci/ci-common.sh
Labels: kind: infrastructure

#18322 Split the ci-elpi_hb makefile in two.
  Makefile.ci
  dev/ci/ci-elpi.sh
  dev/ci/ci-hb.sh
Labels: kind: infrastructure

#18190 Support for weak cbv
  dev/ci/user-overlays/18190-herbelin-master+weak-cbv.sh
  doc/changelog/04-tactics/17503-redexpr.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/tools/docgram/orderedGrammar
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  pretyping/cbv.ml
  pretyping/cbv.mli
  pretyping/tacred.ml
  pretyping/tacred.mli
  proofs/tacmach.ml
  proofs/tacmach.mli
  tactics/eqdecide.ml
  tactics/redexpr.ml
  test-suite/output/reduction.out
  test-suite/output/reduction.v
Labels: kind: enhancement, part: reduction strategies

#18310 Fix check that sections are not opened when starting a module
  library/lib.ml
  test-suite/bugs/bug_18307.v
  vernac/synterp.ml
Labels: kind: fix

#18271 Remove codeowners entry for test-suite/complexity
  .github/CODEOWNERS
Labels: kind: infrastructure

#18344 [CI] Temporary fix for coqword
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure, part: CI

#17797 Move the documentation of Pwd and Cd to the extraction chapter.
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#18340 Fix const_relevance and default qvar handler with sort polymorphism
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  engine/evd.ml
  engine/evd.mli
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/constant_typing.ml
  kernel/constr.ml
  kernel/constr.mli
  kernel/conversion.ml
  kernel/conversion.mli
  kernel/genlambda.ml
  kernel/genlambda.mli
  kernel/mod_typing.ml
  kernel/nativecode.ml
  kernel/nativeconv.mli
  kernel/subtyping.ml
  kernel/typeops.ml
  kernel/typeops.mli
  kernel/uVars.ml
  kernel/uVars.mli
  kernel/vconv.ml
  kernel/vconv.mli
  kernel/vmbytegen.ml
  pretyping/evarconv.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  test-suite/success/sort_poly.v
Labels: kind: fix

#18193 Support for associating a comment or a warning to a library file
  checker/values.ml
  doc/changelog/08-vernac-commands-and-options/18193-master+docstring.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/using/libraries/writing.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  library/global.ml
  library/global.mli
  library/lib.ml
  library/lib.mli
  library/library_info.ml
  library/library_info.mli
  test-suite/output/library_attributes.out
  test-suite/output/library_attributes.v
  test-suite/output/library_attributes_require.out
  test-suite/output/library_attributes_require.v
  test-suite/prerequisite/library_attributes.v
  vernac/declaremods.ml
  vernac/declaremods.mli
  vernac/g_vernac.mlg
  vernac/library.ml
  vernac/ppvernac.ml
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.mli
Labels: kind: feature, kind: user messages

#18321 [CI] List points of contact in ci-basic-overlay.sh
  dev/ci/README-users.md
  dev/ci/ci-basic-overlay.sh
Labels: kind: documentation, kind: infrastructure

#18347 Remove old overlay files
  dev/ci/user-overlays/14928-herbelin-tmp-scope-delimiter.sh
  dev/ci/user-overlays/16890-SkySkimmer-deprecate-definitions.sh
  dev/ci/user-overlays/17115-herbelin-master+unify-CPatNotation-CNotation-partial-fix17094.sh
  dev/ci/user-overlays/17117-master+fix-printing-custom-no-level.sh
  dev/ci/user-overlays/17136-ppedrot-stream_error_to_gramlib.sh
  dev/ci/user-overlays/17359-SkySkimmer-tac2-preterm-antiquot.sh
  dev/ci/user-overlays/17453-SkySkimmer-reduction.sh
  dev/ci/user-overlays/17460-SkySkimmer-no-object-pr.sh
  dev/ci/user-overlays/17466-SkySkimmer-typing-relevance.sh
  dev/ci/user-overlays/17475-SkySkimmer-ltac2-defineval.sh
  dev/ci/user-overlays/17503-SkySkimmer-redexpr.sh
  dev/ci/user-overlays/17505-SkySkimmer-alg-on-right.sh
  dev/ci/user-overlays/17533-SkySkimmer-tac2plugin.sh
  dev/ci/user-overlays/17575-SkySkimmer-ltac2in1.sh
  dev/ci/user-overlays/17576-SkySkimmer-let-abstract.sh
  dev/ci/user-overlays/17585-SkySkimmer-warn-api.sh
  dev/ci/user-overlays/17605-SkySkimmer-summary-local.sh
  dev/ci/user-overlays/17616-SkySkimmer-elpi-backtrack.sh
  dev/ci/user-overlays/17633-SkySkimmer-app-head.sh
  dev/ci/user-overlays/17662-SkySkimmer-fix-async-qvar-union.sh
  dev/ci/user-overlays/17664-SkySkimmer-depr-versions.sh
  dev/ci/user-overlays/17667-SkySkimmer-pattern-quotations.sh
  dev/ci/user-overlays/17696-SkySkimmer-tac2compile-plugin.sh
  dev/ci/user-overlays/17699-SkySkimmer-badtype2.sh
  dev/ci/user-overlays/17716-proux01-deprecate_nonuniform.sh
  dev/ci/user-overlays/17719-ppedrot-vm-evar-global.sh
  dev/ci/user-overlays/17754-proux01-locality_subinstance_def_classes.sh
  dev/ci/user-overlays/17768-ppedrot-split-generalize-tactics.sh
  dev/ci/user-overlays/17795-SkySkimmer-comind-level-compute.sh
  dev/ci/user-overlays/17818-SkySkimmer-vernactypes.sh
  dev/ci/user-overlays/17823-herbelin-record-notation.sh
  dev/ci/user-overlays/17824-ppedrot-split-tactics-induction.sh
  dev/ci/user-overlays/17827-herbelin-master+collecting-ntn-vars-binding-in-ntn-var.sh
  dev/ci/user-overlays/17832-herbelin-master+rewstrategy-explicit-assoc.sh
  dev/ci/user-overlays/17836-SkySkimmer-sort-poly.sh
  dev/ci/user-overlays/17875-herbelin-printer-support-for-entries-arbitrary-level-on-right.sh
  dev/ci/user-overlays/17928-SkySkimmer-search-restr.sh
  dev/ci/user-overlays/17937-JasonGross-zify-no-dep-specialize.sh
  dev/ci/user-overlays/17955-ppedrot-hint-cut-static-globref.sh
  dev/ci/user-overlays/17964-SkySkimmer-replace-assum.sh
  dev/ci/user-overlays/17987-herbelin-master+fix17963-search-anomaly-with-evars.sh
  dev/ci/user-overlays/18007-herbelin-master+extra-checks-valid-declared-hyps.sh
  dev/ci/user-overlays/18014-herbelin-binder-constr.sh
  dev/ci/user-overlays/18023-rlepigre-brcleanup-cclosure.sh
  dev/ci/user-overlays/18039-proux01-vst.sh
  dev/ci/user-overlays/18082-SkySkimmer-tac2pure.sh
  dev/ci/user-overlays/18124-LasseBlaauwbroek-remove-complete.sh
  dev/ci/user-overlays/18139-SkySkimmer-ltac2printers.sh
  dev/ci/user-overlays/18174-SkySkimmer-clenv-unify-cv-pb.sh
  dev/ci/user-overlays/18187-SkySkimmer-redbehaviour-pred.sh
  dev/ci/user-overlays/18190-herbelin-master+weak-cbv.sh
  dev/ci/user-overlays/18279-ppedrot-tacred-factor-red-product.sh
  dev/ci/user-overlays/18280-SkySkimmer-ci-relevance.sh
  dev/ci/user-overlays/18294-ppedrot-glob-evar-kinds.sh
  dev/ci/user-overlays/18312-ppedrot-detuplify-impargs.sh
Labels: kind: cleanup

#17899 Add a file to spot-check the specs of primitive floats
  test-suite/primitive/float/add.v
  test-suite/primitive/float/classify.v
  test-suite/primitive/float/compare.v
  test-suite/primitive/float/div.v
  test-suite/primitive/float/double_rounding.v
  test-suite/primitive/float/frexp.v
  test-suite/primitive/float/gen_compare.sh
  test-suite/primitive/float/ldexp.v
  test-suite/primitive/float/mul.v
  test-suite/primitive/float/next_up_down.v
  test-suite/primitive/float/normfr_mantissa.v
  test-suite/primitive/float/spec_conv.v
  test-suite/primitive/float/specs.v
  test-suite/primitive/float/sqrt.v
  test-suite/primitive/float/sub.v
  test-suite/primitive/float/valid_binary_conv.v
Labels: kind: infrastructure, part: test-suite, part: primitive types

#18253 Remove useless poly argument in add_coercion and cie.
  dev/ci/user-overlays/18253-herbelin-master+useless-poly-flag-coercion.sh
  test-suite/bugs/HoTT_coq_014.v
  vernac/comAssumption.ml
  vernac/comAssumption.mli
  vernac/comCoercion.ml
  vernac/comCoercion.mli
  vernac/comInductive.ml
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: cleanup
