Repository rocq-prover/rocq, pull requests merged in 2023-06, with the labels that each got.

#17117 Clarifying the logic of levels in custom and constr entry rules (reopening of #13025)
  dev/ci/user-overlays/17117-master+fix-printing-custom-no-level.sh
  dev/doc/changes.md
  doc/changelog/03-notations/17117-master+fix-printing-custom-no-level.rst
  interp/constrexpr.mli
  interp/constrexpr_ops.ml
  interp/constrextern.ml
  interp/notation.ml
  interp/notation.mli
  interp/notation_ops.ml
  interp/notation_ops.mli
  interp/notation_term.mli
  interp/notationextern.ml
  interp/notationextern.mli
  parsing/extend.ml
  parsing/extend.mli
  parsing/notation_gram.mli
  parsing/notgram_ops.ml
  parsing/notgram_ops.mli
  printing/ppextend.ml
  printing/ppextend.mli
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  test-suite/output/PrintingParentheses.out
  test-suite/output/PrintingParentheses.v
  vernac/egramcoq.ml
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/prettyp.ml
Labels: kind: fix, kind: cleanup, part: notations, part: printer

#17666 Simplify the Mod_typing API
  kernel/mod_typing.ml
  kernel/mod_typing.mli
  plugins/extraction/extract_env.ml
  vernac/declaremods.ml
Labels: kind: cleanup

#17662 Fix sort quality variables with async workers
  dev/ci/user-overlays/17662-SkySkimmer-fix-async-qvar-union.sh
  dev/top_printers.ml
  engine/uState.ml
  engine/univGen.ml
  kernel/sorts.ml
  kernel/sorts.mli
  kernel/univ.ml
  kernel/univ.mli
  kernel/vmvalues.ml
  test-suite/bugs/bug_17661.v
Labels: kind: fix

#17575 ltac2val:() quotation in ltac1 to return Ltac1.t values
  dev/ci/user-overlays/17575-SkySkimmer-ltac2in1.sh
  doc/changelog/06-Ltac2-language/17575-ltac2in1.rst
  doc/sphinx/proof-engine/ltac2.rst
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2intern.ml
  test-suite/ltac2/ltac2in1.v
Labels: kind: enhancement

#17672 Fix propagate_loads in end_module
  kernel/safe_typing.ml
Labels: kind: fix

#17615 Check declared section variables of axioms in the kernel
  dev/base_include
  kernel/constant_typing.ml
  kernel/constant_typing.mli
  kernel/entries.mli
  kernel/safe_typing.ml
  vernac/declare.ml
Labels: kind: fix, kind: cleanup, part: kernel

#17649 Ltac1: Simplify error message for not fully applied tactic
  plugins/ltac/tacinterp.ml
  test-suite/output/ltac_missing_args.out
Labels: kind: user messages

#17670 injection: do not force Eqdep_dec to be required when equality scheme exists
  doc/changelog/04-tactics/17670-inject-eqdep.rst
  tactics/equality.ml
Labels: kind: fix

#17665 Remove bugged test of leaking evars in class_tactics
  tactics/class_tactics.ml
  test-suite/bugs/bug_5243.v
Labels: kind: fix

#17650 Preserve location of errors with async proofs on
  stm/stm.ml
Labels: kind: fix, kind: user messages, part: STM

#17467 Validate Proof command: runs typing.ml on the current proof
  doc/changelog/08-vernac-commands-and-options/17467-validate-proof.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  test-suite/success/ValidateProof.v
  vernac/g_proofs.mlg
  vernac/ppvernac.ml
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.mli
Labels: kind: enhancement

#17677 Add test for #6464
  test-suite/bugs/bug_6464.v
Labels: kind: internal

#17681 Slightly safer API for segment marshalling.
  checker/check.ml
  lib/objFile.ml
  lib/objFile.mli
  topbin/coqnative_bin.ml
  vernac/library.ml
Labels: kind: cleanup

#17675 Add flake.nix
  flake.lock
  flake.nix
Labels: kind: infrastructure, platform: Nix

#17616 Provide API for elpi-style import time vernac extends
  coqpp/coqpp_ast.mli
  coqpp/coqpp_main.ml
  coqpp/coqpp_parse.mly
  dev/ci/user-overlays/17616-SkySkimmer-elpi-backtrack.sh
  dev/top_printers.ml
  parsing/g_constr.mlg
  parsing/g_prim.mlg
  sysinit/coqinit.ml
  test-suite/misc/quotation_token/src/quotation.mlg
  toplevel/g_toplevel.mlg
  vernac/g_proofs.mlg
  vernac/g_vernac.mlg
  vernac/vernacextend.ml
  vernac/vernacextend.mli
Labels: kind: enhancement, kind: internal

#17605 Fix inverted logic in `Summary.ref ~local:true`
  dev/ci/user-overlays/17605-SkySkimmer-summary-local.sh
  interp/notation.ml
  interp/notationextern.ml
  library/goptions.ml
  library/lib.ml
  library/summary.ml
  library/summary.mli
  parsing/pcoq.ml
  parsing/pcoq.mli
  plugins/funind/indfun_common.ml
  stm/partac.ml
  stm/stm.ml
  vernac/declaremods.ml
  vernac/mltop.ml
  vernac/opaques.ml
  vernac/opaques.mli
  vernac/synterp.ml
  vernac/vernacinterp.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: redesign, kind: fix

#17690 Fix filtering of time-file option in async spawning
  stm/asyncTaskQueue.ml
Labels: kind: fix

#17645 Fix is_alias_of_already_visible_name with univ instance
  interp/abbreviation.ml
  test-suite/bugs/bug_17644.v
Labels: kind: fix

#17671 Improve error reporting from solve_constraints at end of command
  proofs/proof.ml
  proofs/refine.ml
Labels: kind: user messages

#17574 Keep anticipate synterp objects even for sealed modules
  test-suite/coqchk/bug_17570.v
  vernac/declaremods.ml
Labels: kind: fix

#17651 Fix freshness of generated module names when printing functors
  test-suite/bugs/bug_8222.v
  vernac/printmod.ml
Labels: kind: fix, kind: user messages

#17678 Add back VsCoq in CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-vscoq.sh
  dev/ci/docker/bionic_coq/Dockerfile
Labels: kind: infrastructure

#17359 Ltac2 preterm antiquotation `$preterm:x`
  dev/ci/user-overlays/17359-SkySkimmer-tac2-preterm-antiquot.sh
  doc/changelog/06-Ltac2-language/17359-tac2-preterm-antiquot.rst
  doc/sphinx/proof-engine/ltac2.rst
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2intern.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  test-suite/ltac2/preterm_antiquot.v
  test-suite/output-coqtop/ltac2_var_quot.out
  test-suite/output-coqtop/ltac2_var_quot.v
Labels: kind: enhancement

#17628 Fix stage of generic_notation_printing_rules
  lib/flags.mli
  printing/ppextend.ml
  test-suite/output/bug_17627.out
  test-suite/output/bug_17627.v
Labels: kind: fix

#17696 Expose APIs to make it possible to compile Ltac2 as a separate plugin
  dev/ci/user-overlays/17696-SkySkimmer-tac2compile-plugin.sh
  plugins/ltac2/tac2dyn.ml
  plugins/ltac2/tac2dyn.mli
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2intern.mli
  plugins/ltac2/tac2interp.ml
  plugins/ltac2/tac2interp.mli
  topbin/coqtop_byte_bin.ml
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: internal, part: ltac2

#17270 [coqdep] give relative paths to META and .cmxs files.
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/fl.ml
  tools/coqdep/lib/fl.mli
Labels: kind: fix, part: build, part: coqdep

#17669 Deprecate tactic "revert dependent" (alias of "generalize dependent")
  doc/changelog/04-tactics/17669-inject-eqdep.rst
  doc/sphinx/proof-engine/tactics.rst
  theories/Init/Tactics.v
Labels: kind: cleanup

#17707 Fix output test of #17627
  test-suite/output/bug_17627.out
Labels: kind: fix

#17691 Btauto: always print a counterexample
  plugins/btauto/refl_btauto.ml
  test-suite/output/btauto_counterexample.out
  test-suite/output/btauto_counterexample.v
Labels: kind: user messages

#17709 Add comment on Mltop.load_module
  vernac/mltop.mli
Labels: kind: documentation, part: native compiler, kind: internal, part: ocaml, part: toplevel

#17723 Arith: fix doc typos
  theories/NArith/Nnat.v
  theories/ZArith/Znat.v
Labels: kind: documentation, part: standard library

#17689 CI: add ITree
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-itree.sh
Labels: kind: infrastructure

#17699 Improve can'tapplybadtype error messages
  dev/ci/user-overlays/17699-SkySkimmer-badtype2.sh
  kernel/type_errors.ml
  kernel/type_errors.mli
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  pretyping/typing.ml
  test-suite/output/CantApplyBadType.out
  test-suite/output/CantApplyBadType.v
  test-suite/output/Errors.out
  test-suite/output/bug_13266.out
  vernac/himsg.ml
Labels: kind: user messages

#17714 Stop returning Sorts.family from Inductiveops.get_arity
  pretyping/cases.ml
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/pretyping.ml
  proofs/clenv.ml
  tactics/inv.ml
Labels: kind: cleanup

#17712 Remove "check-owners" scripts
  CONTRIBUTING.md
  dev/tools/check-owners-pr.sh
  dev/tools/check-owners.sh
Labels: kind: cleanup

#17743 [stm] fix regression introduced in de2d782
  stm/stm.ml
Labels: kind: fix, kind: performance, part: STM

#17734 add deprecation warnings for Int31
  doc/changelog/11-standard-library/17734-warn-Int31.rst
  test-suite/output/Int31NumberSyntax.v
  theories/Numbers/Cyclic/Int31/Cyclic31.v
  theories/Numbers/Cyclic/Int31/Int31.v
  theories/Numbers/Cyclic/Int31/Ring31.v
Labels: kind: cleanup, part: standard library

#17730 Ltac2: expose Tac2core.throw
  plugins/ltac2/tac2core.mli
Labels: kind: internal

#17695 create_overlays: skip non github repos instead of generating garbage
  dev/tools/create_overlays.sh
Labels: kind: infrastructure

#17740 Add gitignore for tc_declaration_observer test
  test-suite/misc/tc_declaration_observer/.gitignore
Labels: kind: infrastructure

#17736 Coqide filter_coq_args: use -q
  ide/coqide/coq.ml
Labels: kind: fix, part: CoqIDE

#17746 Adapt examples in deprecation warning attribute documentation.
  doc/sphinx/using/libraries/writing.rst
Labels: kind: documentation

#17751 Extending the Code of Conduct for forums
  CODE_OF_CONDUCT.md
Labels: kind: documentation, kind: meta

#17706 [build] Avoid conflict between library and module name in case-insensitive FS
  stm/dune
  tools/coqworkmgr/dune
Labels: kind: fix, part: build

#17718 Stop implicitly adding template inductive types to Keep Equality table.
  doc/changelog/08-vernac-commands-and-options/17718-no-template-keep-inj-equality.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  test-suite/bugs/bug_3125.v
  vernac/declareInd.ml
Labels: kind: cleanup

#17725 Improved adding of Ltac2 backtraces for externals
  plugins/ltac2/tac2bt.ml
  plugins/ltac2/tac2bt.mli
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
Labels: kind: user messages

#17755 Fix documentation of add_top.
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: fix, kind: documentation

#17748 Avoid generating empty letin in ltac in notation
  plugins/ltac/tacintern.ml
  test-suite/output/bug_17708.out
  test-suite/output/bug_17708.v
Labels: kind: fix

#17684 [release] drop 8.15 from compat
  doc/stdlib/index-list.html.template
  sysinit/coqargs.ml
  test-suite/success/CompatOldOldFlag.v
  test-suite/tools/update-compat/run.sh
  theories/Compat/Coq815.v
Labels: kind: infrastructure, kind: compatibility

#17756 Fix debug install printers after coqworkmgrapi name change
  dev/core_dune.dbg
  dev/db
Labels: kind: fix, part: build, kind: internal

#17750 (8.17) Fix "tip not cached" anomaly when there are open proofs at file end
  ide/coqide/idetop.ml
  stm/stm.ml
  stm/stm.mli
  test-suite/output/bug_16335.out
  test-suite/output/bug_16335.v
  toplevel/ccompile.ml
Labels: kind: fix

#17738 Stop considering Warnings experimental and add more cross-links.
  doc/sphinx/appendix/indexes/index.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  lib/cWarnings.ml
Labels: kind: documentation

#17728 Catch univ inconsistency in Abstract.interpretable_as_section_decl
  tactics/abstract.ml
  test-suite/bugs/bug_17727.v
Labels: kind: fix, part: universes

#17587 Fix insertion of default timeout
  vernac/synterp.ml
Labels: kind: fix

#17739 univ.ml: Add assertion that all univs in the ucontext instance are globals
  kernel/univ.ml
  kernel/univ.mli
Labels: kind: internal

#17762 Changelog for 8.17.1.
  doc/changelog/13-misc/17324-master+fix14843-extraction-collision-record-field.rst
  doc/changelog/13-misc/17495-byextendmsg.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#17763 UnivSubst.level_subst_of: assert that we are never called on an algebraic
  engine/univSubst.ml
  engine/univSubst.mli
Labels: kind: internal

#17715 Improve printing of goptions tables
  library/goptions.ml
Labels: kind: user messages

#17758 Turn "overwriting previous delimiting key" and "hiding binding of key" messages into warnings
  interp/notation.ml
  test-suite/output/FloatNumberSyntax.out
  test-suite/output/Int63NumberSyntax.out
  test-suite/output/Sint63NumberSyntax.out
  theories/ssr/ssrbool.v
Labels: kind: user messages

#17385 Fix documentation after change of default locality in #16258.
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
Labels: kind: documentation, priority: blocker

#17382 [xml protocol] [coqide] Alternative PR fixing some loc problems in master.
  dev/doc/changes.md
  dev/doc/xml-protocol.md
  doc/changelog/10-coqide/17382-xmlprotocol_fulllocs.rst
  ide/coqide/coqOps.ml
  ide/coqide/idetop.ml
  ide/coqide/protocol/serialize.ml
  ide/coqide/protocol/xmlprotocol.ml
  test-suite/interactive/tooltips.v
Labels: kind: fix, part: CoqIDE, kind: enhancement, priority: blocker, part: xml protocol

#17394 [vernac] Remove LoadPath edition vernacular commands
  dev/doc/xml-protocol.md
  doc/changelog/08-vernac-commands-and-options/17394-remove_vernac_loadpath.rst
  doc/sphinx/changes.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  ide/coqide/coq_commands.ml
  test-suite/success/extra_dep.v
  test-suite/success/extra_dep2.v
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/synterp.ml
  vernac/vernac_classifier.ml
  vernac/vernacexpr.mli
Labels: kind: cleanup, part: build, part: vernac

#17757 Use named arguments for boolean arguments of intro_then_gen
  tactics/tactics.ml
Labels: kind: cleanup

#17765 Fix documentation after #17394 (removal of `Add LoadPath`).
  doc/changelog/08-vernac-commands-and-options/17394-remove_vernac_loadpath.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#17540 Add CMap.ExtS.symmetric_diff
  clib/cMap.ml
  clib/cMap.mli
  clib/hMap.ml
Labels: kind: internal

#17120 Backports to v8.17
  doc/changelog/13-misc/17324-master+fix14843-extraction-collision-record-field.rst
  doc/changelog/13-misc/17495-byextendmsg.rst
  doc/sphinx/changes.rst
Labels: needs: full CI

#17766 Bump version number to 8.17.1.
  tools/configure/configure.ml
Labels: kind: infrastructure

#17754 Accept locality attribute for "field" of definitional typeclasses
  dev/ci/user-overlays/17754-proux01-locality_subinstance_def_classes.sh
  doc/changelog/02-specification-language/17754-master.rst
  doc/sphinx/language/core/inductive.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/funind/glob_term_to_relation.ml
  test-suite/bugs/bug_17451.v
  test-suite/output/bug_16224.out
  vernac/comInductive.ml
  vernac/g_vernac.mlg
  vernac/g_vernac.mli
  vernac/ppvernac.ml
  vernac/record.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.mli
Labels: kind: fix, part: typeclasses, part: attributes

#17484 Improve printing of reverse coercions
  doc/changelog/03-notations/17484-rev_coerce.rst
  pretyping/coercion.ml
  test-suite/output/bug_16224.out
  test-suite/output/relaxed_ambiguous_paths.out
  test-suite/output/reverse_coercions.out
  test-suite/output/reverse_coercions.v
  theories/Init/Prelude.v
Labels: kind: enhancement, part: coercions

#17773 Update doc versions
  doc/sphinx/conf.py
Labels: kind: documentation, kind: infrastructure

#17776 Fix #17775: Ltac2 Notations introduce invalid identifiers.
  plugins/ltac2/tac2entries.ml
  test-suite/bugs/bug_17775.v
Labels: kind: fix

#17768 Move generalize-like tactics to their own module.
  dev/ci/user-overlays/17768-ppedrot-split-generalize-tactics.sh
  plugins/firstorder/instances.ml
  plugins/firstorder/rules.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/invfun.ml
  plugins/funind/recdef.ml
  plugins/ltac/coretactics.mlg
  plugins/ltac/extratactics.mlg
  plugins/ltac/internals.ml
  plugins/ltac/leminv.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/micromega/coq_micromega.ml
  plugins/nsatz/nsatz.ml
  plugins/ssr/ssrview.ml
  tactics/equality.ml
  tactics/generalize.ml
  tactics/generalize.mli
  tactics/inv.ml
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#17741 Fatal warnings for duplicate objects in Coq refman.
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation, kind: infrastructure

#17772 Bump Sphinx to 4.5.0
  .gitlab-ci.yml
  dev/ci/docker/bionic_coq/Dockerfile
  doc/README.md
  doc/changelog/12-infrastructure-and-dependencies/17772-bump-sphinx.rst
  doc/sphinx/conf.py
Labels: kind: documentation

#17697 coq_makefile: put file to install list in file instead of shell script
  doc/changelog/09-cli-tools/17697-filestoinstall.rst
  tools/CoqMakefile.in
Labels: kind: infrastructure, part: coq_makefile

#17791 add RM release item about propagating opam package changes
  dev/doc/release-process.md
Labels: kind: documentation, kind: meta

#17793 Markup EQ as code.
  doc/sphinx/language/extensions/canonical.rst
Labels: kind: documentation

#17747 Warn when trying to enable an unknown warning
  doc/changelog/08-vernac-commands-and-options/17747-warn-unknown-warn.rst
  lib/cWarnings.ml
  lib/cWarnings.mli
  plugins/funind/g_indfun.mlg
  sysinit/coqinit.ml
  test-suite/output/Function.out
  test-suite/output/Function.v
  test-suite/success/unknown_warning.v
  vernac/vernacentries.ml
  vernac/vernacinterp.ml
Labels: kind: user messages, kind: enhancement
