Repository rocq-prover/rocq, pull requests merged in 2023-05, with the labels that each got.

#17505 Turn "algebraic on the right" error into regular univ inconsistency
  dev/ci/user-overlays/17505-SkySkimmer-alg-on-right.sh
  engine/uState.ml
  kernel/uGraph.ml
  kernel/uGraph.mli
Labels: kind: user messages

#17552 tclFOCUSID: when used on a shelved goal, shelve all produced goals
  engine/proofview.ml
  test-suite/bugs/bug_16513.v
Labels: kind: fix, part: tactics

#17453 Kernel: split reduction.ml to have conversion-related functions in conversion.ml
  checker/mod_checking.ml
  dev/ci/user-overlays/17453-SkySkimmer-reduction.sh
  engine/eConstr.ml
  engine/evarutil.ml
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/termops.mli
  engine/uState.ml
  kernel/conversion.ml
  kernel/conversion.mli
  kernel/inferCumulativity.ml
  kernel/mod_typing.ml
  kernel/mod_typing.mli
  kernel/nativeconv.ml
  kernel/nativeconv.mli
  kernel/reduction.ml
  kernel/reduction.mli
  kernel/safe_typing.ml
  kernel/subtyping.ml
  kernel/subtyping.mli
  kernel/term_typing.ml
  kernel/typeops.ml
  kernel/vconv.ml
  kernel/vconv.mli
  plugins/ssrmatching/ssrmatching.ml
  pretyping/cases.ml
  pretyping/coercion.ml
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/retyping.ml
  pretyping/unification.ml
  printing/printer.ml
  proofs/clenv.ml
  tactics/autorewrite.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  vernac/comInductive.ml
Labels: kind: cleanup

#17548 Stop calling inductive indices "annotations" in the doc
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/variants.rst
  vernac/indschemes.ml
Labels: kind: cleanup, kind: documentation

#17530 Remove dubious code in push_xref
  library/nametab.ml
Labels: kind: cleanup

#17475 Ltac2: allow 0 argument externals
  dev/ci/user-overlays/17475-SkySkimmer-ltac2-defineval.sh
  doc/changelog/06-Ltac2-language/17475-ltac2-defineval.rst
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2interp.ml
  plugins/ltac2/tac2stdlib.ml
Labels: kind: enhancement, part: ltac2

#17515 A big update pass on the contributing guide.
  CONTRIBUTING.md
Labels: kind: documentation, kind: meta

#17541 Stop reducing case analyses when the head is a constructor in case_pf.
  doc/changelog/04-tactics/17541-case-pf-no-red-head.rst
  proofs/clenv.ml
  test-suite/bugs/bug_17541.v
Labels: kind: fix

#17545 Use meta_instance instead of an adhoc function in clenv_unique_resolver.
  proofs/clenv.ml
Labels: kind: cleanup

#17558 Tweak CList.firstn: return original list when fully used
  clib/cList.ml
Labels: kind: performance

#17550 Make detyping of projections parameter recovery more robust
  engine/evd.ml
  engine/evd.mli
  pretyping/retyping.ml
  test-suite/output/bug_16716.out
  test-suite/output/bug_16716.v
Labels: kind: fix

#17347 Ltac2: Add set and map APIs for ident string int constant inductive constructor
  clib/cMap.ml
  clib/cMap.mli
  clib/hMap.ml
  doc/changelog/06-Ltac2-language/17347-ltac2-map.rst
  doc/stdlib/index-list.html.template
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2core.mli
  test-suite/ltac2/map.v
  user-contrib/Ltac2/Constant.v
  user-contrib/Ltac2/FMap.v
  user-contrib/Ltac2/FSet.v
  user-contrib/Ltac2/Int.v
  user-contrib/Ltac2/Ltac2.v
  user-contrib/Ltac2/String.v
Labels: kind: feature, part: ltac2

#17559 Bench: generate html timing tables with links to the html files
  dev/bench/bench.sh
  dev/bench/render_line_results.ml
  dev/bench/render_results.ml
  dev/bench/table.ml
  dev/bench/table.mli
  dev/bench/timelog2html.ml
  test-suite/misc/bench-render/result.html
Labels: kind: infrastructure

#17422 More robust reinterpreting of ltac variables
  pretyping/globEnv.ml
  pretyping/retyping.ml
  pretyping/retyping.mli
Labels: kind: fix

#17532 [refman] Add link to the deprecation policy
  doc/sphinx/biblio.bib
  doc/sphinx/using/libraries/writing.rst
Labels: kind: documentation

#17588 More informative "expression does not evaluate to a tactic"
  plugins/ltac/tacinterp.ml
Labels: kind: user messages

#17542 Merge tests using misc/coqdoc-options
  test-suite/misc/17072.sh
  test-suite/misc/coqdoc-options.sh
  test-suite/misc/coqdoc-options/15933.html.out
Labels: kind: fix, kind: infrastructure

#17569 Ltac2: use ValExt for uint63 and float64
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2interp.ml
Labels: kind: cleanup

#16890 Handle deprecation attribute for definition-like constructions
  dev/ci/user-overlays/16890-SkySkimmer-deprecate-definitions.sh
  doc/changelog/08-vernac-commands-and-options/16890-deprecate-definitions.rst
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/using/libraries/writing.rst
  interp/abbreviation.ml
  interp/abbreviation.mli
  interp/constrintern.ml
  lib/deprecation.ml
  lib/deprecation.mli
  library/nametab.ml
  library/nametab.mli
  test-suite/output/deprecation_definition.out
  test-suite/output/deprecation_definition.v
  vernac/classes.ml
  vernac/classes.mli
  vernac/comAssumption.ml
  vernac/comAssumption.mli
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comProgramFixpoint.ml
  vernac/comProgramFixpoint.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/indschemes.ml
  vernac/indschemes.mli
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/vernacentries.ml
Labels: kind: user messages, kind: enhancement

#17599 Don't leave an open proof in implicit-arguments.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
Labels: kind: documentation

#17598 Doc: Remove duplicate `match_term_context` label in ltac2.rst
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation

#17578 Ltac2: improve "tactic definition must be a syntactical value" error
  plugins/ltac2/tac2entries.ml
Labels: kind: user messages

#17564 Slightly tweak the heuristic to pose dependent metas in case_pf.
  doc/changelog/04-tactics/17564-case-pf-pose-dependent-metas.rst
  engine/proofview.ml
  engine/proofview.mli
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/tactics.ml
  test-suite/bugs/bug_17487_2.v
Labels: kind: fix, kind: cleanup

#17595 [ci] quick fix for MC 2.0 release
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#17601 add deprecation warnings to Numbers.Cyclic.ZModulo.ZModulo
  theories/Numbers/Cyclic/ZModulo/ZModulo.v
Labels: kind: user messages, part: standard library

#17573 Add debug printer for dirpath maps
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
Labels: kind: infrastructure

#17607 Fix incorrect env variable in render_line_results
  dev/bench/render_line_results.ml
Labels: kind: fix, kind: infrastructure

#17551 Add a unique id to workers
  stm/asyncTaskQueue.ml
  test-suite/bugs/bug_16700.v
Labels: kind: fix, part: STM, part: universes

#17591 Do not let field_simplify mess with side conditions (fix #17584).
  doc/changelog/04-tactics/17591-field-simplify.rst
  test-suite/bugs/bug_17584.v
  theories/setoid_ring/Field_tac.v
Labels: kind: fix, part: ring/field

#17620 Fix "tip not cached" anomaly when there are open proofs at file end
  ide/coqide/idetop.ml
  stm/stm.ml
  stm/stm.mli
  test-suite/output/bug_16335.out
  test-suite/output/bug_16335.v
  toplevel/ccompile.ml
Labels: kind: fix

#17590 Fast path in the Tacticals.check_evars function.
  tactics/tacticals.ml
Labels: kind: performance

#17623 Expose `interp_search_request` in API
  vernac/comSearch.mli
Labels: kind: internal, part: search

#17612 Typeclass instance hints are added by cache_function not rebuild
  vernac/classes.ml
Labels: kind: cleanup

#17586 Reject Timeout 0, correctly handle when synterp takes longer than the timeout without getting a signal.
  test-suite/output/bug_17579.out
  test-suite/output/bug_17579.v
  vernac/synterp.ml
  vernac/synterp.mli
  vernac/vernacinterp.ml
Labels: kind: fix

#17597 Ltac2 multimatch: preserve backtracking error from last branch
  doc/changelog/06-Ltac2-language/17597-ltac2-multimatch-fail.rst
  test-suite/output/bug_17594.out
  test-suite/output/bug_17594.v
  user-contrib/Ltac2/Pattern.v
Labels: kind: fix

#17622 Fix calls to partial summary unfreeze
  library/global.ml
  library/lib.ml
  vernac/declaremods.ml
Labels: kind: internal

#17324 Fixing shadowing of record fields in extraction to OCaml
  doc/changelog/13-misc/17324-master+fix14843-extraction-collision-record-field.rst
  plugins/extraction/common.ml
  plugins/extraction/common.mli
  plugins/extraction/ocaml.ml
  plugins/extraction/table.ml
  plugins/extraction/table.mli
  plugins/micromega/micromega.ml
  test-suite/bugs/bug_14843.v
Labels: part: extraction, kind: bug

#17611 TC declaration observer API
  test-suite/misc/tc_declaration_observer.sh
  test-suite/misc/tc_declaration_observer/_CoqProject
  test-suite/misc/tc_declaration_observer/main.out.reference
  test-suite/misc/tc_declaration_observer/main.v
  test-suite/misc/tc_declaration_observer/observer.ml
  test-suite/misc/tc_declaration_observer/observer_plugin.mlpack
  vernac/classes.ml
  vernac/classes.mli
Labels: kind: feature

#17632 CI: produce time log even when failing
  dev/ci/ci-wrapper.sh
Labels: kind: enhancement, part: CI

#17544 Attribute #[clearbody] useful instead of Let ... Qed
  doc/changelog/08-vernac-commands-and-options/17544-clearbody-att.rst
  doc/sphinx/language/core/sections.rst
  test-suite/output/UnivBinders.out
  test-suite/output/UnivBinders.v
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comProgramFixpoint.ml
  vernac/comProgramFixpoint.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/vernacentries.ml
Labels: kind: redesign, kind: cleanup, kind: compatibility, part: sections, part: attributes, part: vernac, kind: design discussion, kind: usability

#17634 Add `assert is_interactive` in Stm.edit_at
  stm/stm.ml
Labels: part: STM, kind: internal

#17568 gen_rules improvements: remove -fake-source, allow cross dependencies between theories/ and Ltac2/
  stm/asyncTaskQueue.ml
  tools/dune_rule_gen/coq_rules.ml
  tools/dune_rule_gen/gen_rules.ml
  toplevel/ccompile.ml
  toplevel/coqcargs.ml
  toplevel/coqcargs.mli
Labels: kind: infrastructure, part: build

#17629 coqpp: do not print line annotation when loc is dummy
  coqpp/coqpp_ast.mli
  coqpp/coqpp_lex.mll
  coqpp/coqpp_main.ml
  coqpp/coqpp_parse.mly
Labels: kind: fix, kind: infrastructure, part: tools

#17466 typing.ml checks relevance annotations
  dev/ci/user-overlays/17466-SkySkimmer-typing-relevance.sh
  dev/top_printers.ml
  engine/eConstr.ml
  engine/evarutil.ml
  engine/uState.ml
  kernel/context.ml
  kernel/context.mli
  kernel/names.ml
  kernel/names.mli
  kernel/typeops.mli
  library/nametab.ml
  plugins/firstorder/instances.ml
  pretyping/coercion.ml
  pretyping/retyping.ml
  pretyping/retyping.mli
  pretyping/typing.ml
  test-suite/bugs/bug_17466_1.v
  test-suite/bugs/bug_17466_2.v
  test-suite/bugs/bug_17466_3.v
  test-suite/bugs/bug_17547.v
  test-suite/bugs/bug_17619.v
  vernac/comInductive.ml
  vernac/himsg.ml
Labels: kind: fix

#17636 Pass stdlib with default goal selector ! (except ssr)
  theories/Reals/RIneq.v
  theories/Reals/Rfunctions.v
  theories/Reals/Rlogic.v
Labels: kind: cleanup

#17640 Remove unused Univ.ContextSet.{of_instance,add_instance}
  kernel/univ.ml
  kernel/univ.mli
Labels: kind: cleanup, part: universes, kind: internal

#17642 Improve breaks in debug pprinting
  lib/cDebug.ml
  pretyping/unification.ml
Labels: kind: user messages

#17630 Check that the env is evar free before using the kernel in Check/Eval
  test-suite/bugs/bug_17298.v
  vernac/vernacentries.ml
Labels: kind: fix

#17639 Add equations to the explicit bench packages + Improve bench failure detection and reporting
  dev/bench/bench.sh
Labels: kind: infrastructure

#17656 Update equality.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation

#17633 Move Termops.decompose_app_vect to EConstr, rename decompose_app->decompose_app_list, decompose_app_vect->decompose_app
  dev/ci/user-overlays/17633-SkySkimmer-app-head.sh
  engine/eConstr.ml
  engine/eConstr.mli
  engine/termops.ml
  engine/termops.mli
  interp/implicit_quantifiers.ml
  kernel/constr.ml
  kernel/constr.mli
  kernel/genlambda.ml
  kernel/indtypes.ml
  kernel/inductive.ml
  kernel/typeops.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/indfun.ml
  plugins/funind/recdef.ml
  plugins/ring/ring.ml
  plugins/ssr/ssrcommon.ml
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/inductiveops.ml
  pretyping/nativenorm.ml
  pretyping/reductionops.ml
  pretyping/retyping.ml
  pretyping/structures.ml
  pretyping/tacred.ml
  pretyping/typeclasses.ml
  pretyping/unification.ml
  pretyping/vnorm.ml
  proofs/clenv.ml
  tactics/autorewrite.ml
  tactics/contradiction.ml
  tactics/elim.ml
  tactics/eqdecide.ml
  tactics/eqschemes.ml
  tactics/equality.ml
  tactics/hints.ml
  tactics/hipattern.ml
  tactics/inv.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  vernac/comHints.ml
Labels: kind: cleanup, kind: internal

#17652 Be lazier in kernel fixpoint checking.
  kernel/inductive.ml
Labels: kind: performance

#17653 Recompute hint patterns at runtime for (e)apply / immediate
  tactics/hints.ml
Labels: kind: cleanup, kind: performance

#17646 Deprecate List.Forall2_refl (it has a bad type)
  doc/changelog/11-standard-library/17646-forall2-refl.rst
  theories/Lists/List.v
Labels: kind: cleanup

#17654 Add a sorting command to votour
  checker/votour.ml
Labels: kind: infrastructure
