Repository rocq-prover/rocq, pull requests merged in 2023-03, with the labels that each got.

#17287 Don't rerun compcert's configure
  dev/ci/ci-compcert.sh
Labels: kind: infrastructure

#17276 Use list ref for end_library_hook
  plugins/ltac/profile_ltac.ml
  vernac/declaremods.ml
Labels: kind: cleanup

#17301 Supporting debugging in extraction plugin by default
  dev/dune-dbg.in
Labels: kind: infrastructure

#17310 UnivSubst: don't use Not_found for flow control
  dev/ci/user-overlays/17310-SkySkimmer-subst-opt-noexn.sh
  engine/uState.ml
  engine/univSubst.ml
  engine/univSubst.mli
Labels: kind: cleanup

#17285 When univ minim to set is off, don't get confused by Prop lbound
  doc/changelog/08-vernac-commands-and-options/17285-minimset-bound-prop.rst
  engine/univMinim.ml
  test-suite/bugs/bug_13927.v
  test-suite/bugs/bug_17285.v
Labels: kind: fix

#17280 Print qualification information for module signature mismatch errors
  kernel/modops.ml
  kernel/modops.mli
  kernel/subtyping.ml
  test-suite/output/ModuleSubtyping.out
  test-suite/output/ModuleSubtyping.v
  vernac/himsg.ml
Labels: kind: user messages

#17320 Remove extra dependency compat syntax
  doc/sphinx/proof-engine/vernacular-commands.rst
  test-suite/success/extra_dep.v
  vernac/vernacentries.ml
Labels: kind: cleanup

#17328 Rename test file closed/bug_13428.v -> bug_13428.v
  test-suite/bugs/bug_13428.v
Labels: kind: cleanup, part: CI

#17133 remove BVector from Program.Syntax
  test-suite/bugs/bug_14221.v
  test-suite/bugs/bug_16995_2.v
  test-suite/bugs/bug_2393.v
  test-suite/bugs/bug_5521.v
  test-suite/bugs/bug_8739.v
  test-suite/success/unification_delta.v
  theories/Program/Syntax.v
Labels: kind: cleanup

#17305 Fix universe constraint inference for module subtyping
  doc/changelog/02-specification-language/17305-fix-infer-univs.rst
  pretyping/reductionops.ml
  test-suite/bugs/bug_17303.v
  vernac/declaremods.ml
Labels: kind: fix

#17284 More direct glob dumping for reduction `unfold`
  plugins/ltac/tacintern.ml
  plugins/ltac/tacintern.mli
Labels: kind: user messages

#16798 Error on cast in pattern where the type binds a variable
  pretyping/patternops.ml
  test-suite/bugs/bug_16916_1.v
  test-suite/success/ltac.v
Labels: kind: fix

#17335 Ltac2: use backtrackable grammar extension for constr notations
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
Labels: kind: fix

#16935 Passing interning flag strict_check functionally
  dev/ci/user-overlays/16935-herbelin-master+functional-strict_check.sh
  interp/constrintern.ml
  interp/constrintern.mli
  interp/genintern.ml
  interp/genintern.mli
  plugins/ltac/g_obligations.mlg
  plugins/ltac/tacentries.ml
  plugins/ltac/tacintern.ml
  plugins/ltac/tacintern.mli
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2intern.ml
  plugins/ssr/ssrview.ml
  printing/ppconstr.ml
  tactics/autorewrite.ml
  test-suite/success/intros.v
  test-suite/success/ltac.v
  theories/micromega/ZifyComparison.v
  vernac/comHints.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, part: ltac, part: notations, part: ltac2

#17327 Understand proof irrelevance when checking for dependent elim
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  test-suite/bugs/bug_17326.v
  vernac/indschemes.ml
Labels: kind: fix

#17281 change Hint Extern btauto.Algebra.bool to #[export]
  doc/changelog/11-standard-library/17281-export-hint-extern-bool.rst
  theories/btauto/Algebra.v
Labels: kind: cleanup

#17213 Fix typo in 'move' tactic example
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#17307 Use refine instead of simple apply in absurd tactic.
  tactics/contradiction.ml
Labels: kind: cleanup

#17283 More careful handling of possibly universe polymorphic globrefs
  dev/ci/user-overlays/17283-SkySkimmer-unsafe-mono.sh
  engine/eConstr.ml
  engine/eConstr.mli
  engine/termops.ml
  engine/termops.mli
  interp/implicit_quantifiers.ml
  interp/notation.ml
  kernel/constr.ml
  kernel/constr.mli
  kernel/safe_typing.ml
  kernel/typeops.ml
  library/globnames.ml
  library/globnames.mli
  plugins/derive/derive.ml
  plugins/extraction/extraction.ml
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/indfun.ml
  plugins/funind/indfun_common.ml
  plugins/funind/invfun.ml
  plugins/funind/recdef.ml
  plugins/ltac/comRewrite.ml
  plugins/ring/ring.ml
  plugins/ssr/ssrequality.ml
  plugins/ssrmatching/ssrmatching.ml
  plugins/syntax/number.ml
  pretyping/cbv.ml
  pretyping/coercionops.ml
  pretyping/inductiveops.ml
  pretyping/reductionops.ml
  pretyping/structures.ml
  pretyping/typeclasses.ml
  pretyping/typeclasses.mli
  tactics/autorewrite.ml
  tactics/btermdn.ml
  tactics/class_tactics.ml
  tactics/equality.ml
  tactics/rewrite.ml
  test-suite/output/NumberNotationsUnivPoly.out
  test-suite/output/NumberNotationsUnivPoly.v
  vernac/declare.ml
  vernac/indschemes.ml
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#17358 Add Nicolas Tabareau to the enforcement team
  CODE_OF_CONDUCT.md
Labels: kind: internal

#17360 Clearer documentation of `coqdoc`'s `--lib-subtitles`
  doc/sphinx/using/tools/coqdoc.rst
Labels: kind: documentation

#17351 Minor pattern related cleanups
  interp/constrintern.ml
  interp/constrintern.mli
  pretyping/constr_matching.ml
  pretyping/patternops.ml
  pretyping/patternops.mli
  vernac/comSearch.ml
Labels: kind: cleanup

#17317 [boot] env initialization cleanup
  boot/env.ml
  sysinit/coqinit.ml
  test-suite/misc/coq_environment.sh
Labels: kind: cleanup

#17294 More robust eta expansion check in old unification
  pretyping/unification.ml
  test-suite/bugs/bug_17294_1.v
  test-suite/bugs/bug_17294_2.v
Labels: kind: fix

#17200 [backport] Fix backtracking over plugin vernac extensions
  coqpp/coqpp_main.ml
  doc/changelog/08-vernac-commands-and-options/17069-backtrack-vernacextend.rst
  gramlib/grammar.ml
  gramlib/plexing.ml
  gramlib/plexing.mli
  parsing/cLexer.ml
  parsing/cLexer.mli
  parsing/pcoq.ml
  plugins/ltac/extraargs.mlg
  plugins/ltac/g_ltac.mlg
  plugins/ltac/g_obligations.mlg
  plugins/ltac/g_tactic.mlg
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ltac2/tac2core.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrvernac.mlg
  plugins/ssrmatching/g_ssrmatching.mlg
  sysinit/coqinit.ml
  test-suite/bugs/bug_17069_1.v
  test-suite/bugs/bug_17069_2.v
  test-suite/coq-makefile/template/src/test.mlg
  test-suite/misc/non-marshalable-state/src/evil.mlg
  test-suite/misc/non-marshalable-state/src/good.mlg
  vernac/egramml.ml
  vernac/egramml.mli
  vernac/mltop.ml
  vernac/mltop.mli
  vernac/vernacextend.ml
  vernac/vernacextend.mli
Labels: kind: fix

#17082 [stdlib] add lemmas list_power_length, concat_length, flat_map_length
  doc/changelog/11-standard-library/17082-list_power_length.rst
  theories/Lists/List.v
Labels: kind: feature

#17357 Understand type-in-type when checking (ie not infer) constraints
  engine/uState.ml
  kernel/uGraph.ml
  test-suite/bugs/bug_17355.v
Labels: kind: fix

#17338 Add a test summarizing the current behavior of extraction wrt projections
  test-suite/output/extraction_projection.out
  test-suite/output/extraction_projection.v
Labels: part: extraction, kind: internal

#17311 Coqlib.lib_ref raises custom exception instead of UserError
  engine/eConstr.ml
  engine/eConstr.mli
  library/coqlib.ml
  library/coqlib.mli
  plugins/ssr/ssrequality.ml
  pretyping/evarconv.ml
  tactics/equality.ml
  tactics/hipattern.ml
  tactics/inv.ml
  tactics/tactics.ml
Labels: kind: cleanup

#17334 Produce correct error paths when compiling stdlib
  tools/dune_rule_gen/coq_rules.ml
  toplevel/ccompile.ml
  toplevel/coqcargs.ml
  toplevel/coqcargs.mli
  toplevel/vernac.ml
  toplevel/vernac.mli
Labels: kind: infrastructure, priority: high

#17378 Port timelog2html to ocaml
  dev/bench/bench.sh
  dev/bench/dune
  dev/bench/timelog2html
  dev/bench/timelog2html.ml
  dev/bench/timelog2html.mli
Labels: kind: infrastructure

#17350 [library] Make require more independent of the filesystem.
  vernac/library.ml
  vernac/library.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: internal, part: vernac

#17370 Haskell extraction: use block comments where line wrapping may occur
  plugins/extraction/haskell.ml
  test-suite/output/bug_17369.out
  test-suite/output/bug_17369.v
Labels: kind: fix

#17384 Fix Nix CI following the removal of nixorg/nix.
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#17308 Add test for #14475
  test-suite/misc/qed-time.sh
  test-suite/misc/qed-time/.gitignore
  test-suite/misc/qed-time/file.v
  test-suite/output-modulo-time/qed_time.out
  test-suite/output-modulo-time/qed_time.v
Labels: kind: infrastructure

#17352 Error on genargs in patterns instead of treating them as holes
  doc/changelog/04-tactics/17352-pattern-genarg.rst
  pretyping/patternops.ml
  test-suite/success/pattern_genarg.v
Labels: kind: user messages

#17277 Use record for RequireInjection
  dev/ci/user-overlays/17277-SkySkimmer-reqinj.sh
  sysinit/coqargs.ml
  sysinit/coqargs.mli
  sysinit/coqinit.ml
Labels: kind: internal

#17118 [coqdoc] support multiple defs on the same ident in HTML
  doc/changelog/09-cli-tools/17118-coqdoc-multiple-def.rst
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  test-suite/coqdoc/bug11353.html.out
  test-suite/coqdoc/links.html.out
  test-suite/coqdoc/multiple_links.html.out
  test-suite/coqdoc/multiple_links.tex.out
  test-suite/coqdoc/multiple_links.v
  test-suite/misc/15933.html.out
  tools/coqdoc/index.ml
  tools/coqdoc/index.mli
  tools/coqdoc/output.ml
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/declare.ml
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/indschemes.ml
  vernac/indschemes.mli
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
Labels: kind: feature

#17379 timelog2html: display line numbers on the right
  dev/bench/timelog2html.ml
Labels: kind: infrastructure

#17383 Improve output of [make help-install] target.
  Makefile
Labels: kind: documentation, part: installation

#17390 Doc: Clarify cursor position for setting debugger breakpoints
  doc/sphinx/practical-tools/coqide.rst
Labels: kind: documentation, part: ltac debugger

#17387 Remove some unused clib/option APIs
  clib/option.ml
  clib/option.mli
Labels: kind: cleanup

#16910 Remove the no-argument instantiate tactic.
  doc/changelog/04-tactics/16910-rm-instantiate.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/extratactics.mlg
Labels: kind: cleanup

#17322 Reimplement the specialize with tactic using evar clauses.
  doc/changelog/04-tactics/17322-specialize-evar-clause.rst
  tactics/eClause.mli
  tactics/tactics.ml
  test-suite/success/specialize.v
Labels: kind: cleanup

#17381 [8.17] Backport of [coqide] Revert behavior changes in offset location
  gramlib/grammar.ml
  gramlib/grammar.mli
  gramlib/plexing.ml
  gramlib/plexing.mli
  gramlib/stream.mli
  ide/coqide/coqOps.ml
  ide/coqide/idetop.ml
  ide/coqide/ideutils.mli
  parsing/cLexer.ml
Labels: kind: fix, part: IDE

#8905 Fix #5351: Intuition does not work with universe polymorphism.
  doc/changelog/04-tactics/8905-fix-5351.rst
  plugins/ltac/tauto.ml
  test-suite/bugs/bug_4721.v
  test-suite/bugs/bug_5351.v
  theories/Init/Tauto.v
Labels: kind: fix

#17396 Remove now unused exception constructors in Logic.
  proofs/logic.ml
  proofs/logic.mli
  vernac/himsg.ml
Labels: kind: cleanup

#17397 Use a set instead of a list in pattern internalization.
  interp/constrintern.mli
  plugins/ltac/tacintern.ml
  pretyping/patternops.ml
  pretyping/patternops.mli
  pretyping/typeclasses.ml
  pretyping/typeclasses.mli
  vernac/comHints.ml
Labels: kind: cleanup

#17409 [refman] mention Coq-Elpi
  doc/sphinx/proofs/creating-tactics/index.rst
Labels: kind: documentation

#17412 Stop promoting unreleased.rst.
  .gitignore
  doc/dune
Labels: kind: cleanup, kind: infrastructure, part: build

#17410 Changelog for 8.17.0.
  doc/changelog/01-kernel/17116-master+fix17073-guard-checking-inaccessible-branch.rst
  doc/changelog/02-specification-language/17138-master+partial-fix17137-coercions-on-constructors-in-singleton-types.rst
  doc/changelog/02-specification-language/17174-master+fix17173-protect-partially-defined-implicit-arguments-list.rst
  doc/changelog/08-vernac-commands-and-options/17069-backtrack-vernacextend.rst
  doc/changelog/08-vernac-commands-and-options/17113-master+fix17110-travel_aux-anomaly.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#17400 Minor cleanup around System.time
  lib/system.ml
  plugins/funind/glob_term_to_relation.ml
Labels: kind: cleanup

#17343 Improve fatal locality warning message.
  tactics/autorewrite.ml
  tactics/hints.ml
Labels: kind: user messages, needs: full CI

#17304 [`setoid_rewrite`] rewrite hypotheses without evar instance shenanigans
  dev/ci/user-overlays/17304-LasseBlaauwbroek-17295-attempt-two.sh
  doc/changelog/04-tactics/17304-fix-17295-attempt-two.rst
  tactics/rewrite.ml
  test-suite/bugs/bug_17295.v
Labels: kind: fix

#16960 Remove Unification.unsafe_occur_meta_or_existential
  dev/ci/user-overlays/16960-SkySkimmer-rm-unsafe-occur-metaevar.sh
  doc/changelog/04-tactics/16960-rm-unsafe-occur-metaevar.rst
  pretyping/unification.ml
  test-suite/bugs/bug_16960.v
Labels: kind: cleanup

#16992 Add volatile casts and use them to print case univ and parameter data
  dev/ci/user-overlays/16992-SkySkimmer-volatile-cast.sh
  doc/changelog/02-specification-language/16992-volatile-cast.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/language/extensions/match.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  interp/constrexpr.ml
  interp/constrexpr_ops.ml
  interp/constrexpr_ops.mli
  interp/notation_ops.ml
  interp/notation_term.ml
  parsing/g_constr.mlg
  plugins/funind/glob_term_to_relation.ml
  plugins/ltac/g_ltac.mlg
  plugins/ltac2/g_ltac2.mlg
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssrmatching/ssrmatching.ml
  plugins/syntax/number.ml
  plugins/syntax/string_notation.ml
  pretyping/detyping.ml
  pretyping/glob_ops.ml
  pretyping/glob_term.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  printing/ppconstr.ml
  printing/proof_diffs.ml
  test-suite/output/PrintGrammar.out
  test-suite/output/PrintGrammarConstr.out
  test-suite/output/PrintMatch.out
  test-suite/output/PrintMatch.v
  vernac/comDefinition.ml
  vernac/g_proofs.mlg
  vernac/g_vernac.mlg
Labels: kind: user messages

#17416 Move missing changelog entry into 8.17.0 release notes.
  doc/changelog/09-cli-tools/17090-fix-coqdoc-g-omissions.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#17214 Remove use of "tacv" in Ltac doc
  doc/sphinx/proof-engine/ltac.rst
Labels: kind: documentation

#17398 Filter fake-source when spawning process in asynctaskqueue
  stm/asyncTaskQueue.ml
Labels: kind: internal

#17231 Eliminate last "nitpicky" exceptions
  doc/sphinx/conf.py
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation

#17230 Have doc_grammar generate error messages for edits that generate duplicate productions
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#17274 More uniform behaviour and implementation for Check and Eval
  dev/ci/user-overlays/17274-SkySkimmer-check-eval.sh
  doc/changelog/08-vernac-commands-and-options/17274-check-eval.rst
  test-suite/output/Notations5.out
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: user messages

#17401 Restore the FullHint.pattern function.
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: internal

#17427 Use a simpler definition of xorb.
  doc/changelog/11-standard-library/17427-xorb.rst
  theories/Init/Datatypes.v
  theories/NArith/BinNat.v
  theories/btauto/Algebra.v
  theories/btauto/Reflect.v
Labels: part: standard library, kind: enhancement

#17426 Make sure to use fresh intro names in Lqa and Lra (fix #17423).
  test-suite/bugs/bug_17423.v
  theories/micromega/Lqa.v
  theories/micromega/Lra.v
Labels: kind: fix, part: micromega

#17402 Inline and simplify the call to elim_type in Eqdecide
  tactics/eqdecide.ml
Labels: kind: cleanup

#17408 Static invariants enforced around the induction / destruct tactics
  tactics/tactics.ml
  test-suite/bugs/bug_17408.v
Labels: kind: cleanup

#17389 Clean Elim internals
  tactics/elim.ml
Labels: kind: cleanup

#17424 Vars.find_vars: use CList.assoc_f instead of local reimplementation
  kernel/vars.ml
Labels: kind: cleanup

#17429 Correct typo in changes for #11429
  doc/sphinx/changes.rst
Labels: kind: documentation

#17407 Add coq-tactician to CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-tactician.sh
Labels: kind: infrastructure

#17411 Fix timelog2html line count bug
  dev/bench/dune
  dev/bench/timelog2html.ml
  doc/changelog/09-cli-tools/17411-timelog.rst
  doc/sphinx/practical-tools/utilities.rst
  test-suite/misc/bench-render.sh
  test-suite/misc/bench-render/.gitignore
  test-suite/misc/bench-render/foo.v
  test-suite/misc/bench-render/foo.v.time1
  test-suite/misc/bench-render/foo.v.time2
  test-suite/misc/bench-render/foo.v.time3
  test-suite/misc/bench-render/foo.v.time4
  test-suite/misc/bench-render/result.html
  test-suite/misc/bench-render/stderr1v3
  test-suite/misc/bench-render/stderr1v4
Labels: kind: fix, kind: cleanup

#17430 Add -time-file to output the time data to a file
  boot/usage.ml
  doc/changelog/08-vernac-commands-and-options/17430-timef.rst
  doc/changelog/09-cli-tools/17430-timef.rst
  sysinit/coqargs.ml
  sysinit/coqargs.mli
  tools/CoqMakefile.in
  toplevel/ccompile.ml
  toplevel/coqtop.ml
  toplevel/vernac.ml
  toplevel/vernac.mli
Labels: kind: infrastructure, kind: enhancement, part: toplevel

#17441 Temporarily remove VsCoq from CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-vscoq.sh
Labels: kind: infrastructure

#17435 Fix #16390: destruct tactic misbehaves with let-bindings.
  proofs/clenv.ml
  tactics/tactics.ml
  test-suite/bugs/bug_16390.v
Labels: kind: fix

#17444 Bench: use --no-print-directory
  dev/bench/bench.sh
Labels: kind: infrastructure

#17425 Vars.substituend: cache lifts, not just closedness
  kernel/vars.ml
Labels: kind: performance

#17447 Clean the internals of the Indrec modules
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
Labels: kind: cleanup, kind: performance

#17246 Tagged runner system
  .gitlab-ci.yml
  dev/ci/gitlab-modes/normal-mode.yml
  dev/ci/gitlab-modes/protected-mode.yml
  dev/ci/gitlab-modes/tagged-runners.yml
  dev/ci/gitlab-modes/untagged-runners.yml
Labels: kind: infrastructure, part: CI

#17433 Allow coq-core and coqide-server to be compiled in bytecode-only mode
  ide/coqide/dune
  topbin/dune
Labels: kind: fix, kind: infrastructure, part: build
