Repository rocq-prover/rocq, pull requests merged in 2024-12, with the labels that each got.

#19868 Ltac2: added Constr.Unsafe.map_with_binders function
  user-contrib/Ltac2/Constr.v
Labels: kind: enhancement

#19693 Fix unicode classification of non-spacing marks.
  clib/unicode.ml
  doc/changelog/03-notations/19693-fix-19512.rst
Labels: kind: fix, part: parser

#19854 Small cleanup around coqdep find_dependencies
  tools/coqdep/lib/common.ml
Labels: kind: cleanup

#19812 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: kind: documentation, kind: meta

#19888 [ci] use elpi 2.0.4
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
Labels: kind: infrastructure

#19840 Delay import of notation sets in Notationextern.
  interp/notationextern.ml
Labels: kind: performance

#19892 SSR: Fix ustate when calling abs_cterm
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrequality.ml
Labels: kind: fix, part: ssreflect

#19889 Fix incorrect path normalization in coqdep on `//..`
  tools/coqdep/lib/file_util.ml
Labels: kind: fix

#19820 Remove "stdlib2" from CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-stdlib2.sh
Labels: kind: infrastructure

#19897 Windows CI use `ci` pick
  dev/ci/platform/coq-pf-03-build.bat
Labels: kind: fix, kind: infrastructure

#19878 Document Hint Variables/Constants Opaque/Transparent : rewrite
  doc/sphinx/addendum/generalized-rewriting.rst
Labels: kind: documentation, part: rewriting tactics

#19907 Fix opam --with-test
  dune
Labels: kind: fix, kind: infrastructure

#19886 Include digests of Declare ML Module dependencies in .vo
  vernac/mltop.ml
Labels: kind: fix, part: build

#19870 split preprocess_inductive_decl between defclass/record/inductive
  vernac/vernacentries.ml
Labels: kind: cleanup

#19833 rm problematic variables under beta redexes for evar instantiation
  doc/changelog/02-specification-language/19833-evd-inst-beta.rst
  pretyping/evarsolve.ml
  test-suite/bugs/bug_19833.v
Labels: kind: enhancement, part: elaboration, part: unification

#19909 Fix macos again
  .github/workflows/ci-macos.yml
Labels: kind: infrastructure

#19903 ci-stdlib don't use --release
  dev/ci/ci-stdlib.sh
Labels: kind: infrastructure

#19904 Fix bench with and without split stdlib
  dev/bench/bench.sh
Labels: kind: infrastructure

#19912 CI: also build coq-stdlib in pkg:opam job
  .gitlab-ci.yml
Labels: kind: infrastructure

#19917 Fix grammar in error message of rewrite tactic
  tactics/rewrite.ml
Labels: kind: user messages

#19911 Fix Vector warning link
  stdlib/theories/Bool/Bvector.v
  stdlib/theories/Vectors/Fin.v
  stdlib/theories/Vectors/Vector.v
  stdlib/theories/Vectors/VectorDef.v
  stdlib/theories/Vectors/VectorEq.v
  stdlib/theories/Vectors/VectorSpec.v
Labels: kind: documentation

#19921 Include stdlib in CI artifacts
  .gitlab-ci.yml
Labels: kind: infrastructure

#19923 Fix CODEOWNERS after stdlib split.
  .github/CODEOWNERS
Labels: kind: meta

#19899 [build] Fix wrong use of %{project_root}/_build in config files
  dev/shim/dune
  dune
  tools/coqdep/lib/dune
  tools/dune_rule_gen/coq_rules.ml
Labels: kind: fix, part: build

#19872 Disable and remove `Automatic Proposition Inductives`
  dev/ci/user-overlays/19872-SkySkimmer-depr-auto-prop-lowering.sh
  doc/changelog/08-vernac-commands-and-options/19872-depr-auto-prop-lowering.rst
  doc/sphinx/changes.rst
  doc/sphinx/language/core/inductive.rst
  plugins/funind/glob_term_to_relation.ml
  test-suite/bugs/bug_19872.v
  test-suite/success/AutoPropLowering.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#19929 Fix paths in shims
  dev/shim/dune
Labels: kind: fix

#19934 Doc: rename `coqtop::` -> `rocqtop::`, `coqdoc::` -> `rocqdoc::`
  doc/sphinx/README.rst
  doc/sphinx/README.template.rst
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/sphinx/addendum/implicit-coercions.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/miscellaneous-extensions.rst
  doc/sphinx/addendum/program.rst
  doc/sphinx/addendum/rewrite-rules.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/addendum/sprop.rst
  doc/sphinx/addendum/type-classes.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/changes.rst
  doc/sphinx/language/cic.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/coinductive.rst
  doc/sphinx/language/core/conversion.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/language/core/primitive.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/core/sections.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/language/extensions/arguments-command.rst
  doc/sphinx/language/extensions/canonical.rst
  doc/sphinx/language/extensions/evars.rst
  doc/sphinx/language/extensions/implicit-arguments.rst
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/practical-tools/coqide.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/automatic-tactics/logic.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/sphinx/using/libraries/funind.rst
  doc/sphinx/using/libraries/writing.rst
  doc/tools/coqrst/coqdomain.py
  stdlib/doc/sphinx/README.template.rst
  stdlib/doc/sphinx/language/coq-library.rst
  stdlib/doc/tools/coqrst/coqdomain.py
Labels: kind: documentation

#19935 Bypass warning override when possible
  vernac/declare.ml
Labels: kind: performance

#19926 Cleanup artifacts before upload
  .gitlab-ci.yml
  dev/tools/cleanup-artifacts.sh
  dev/tools/list-potential-artifacts.sh
Labels: kind: infrastructure

#19940 Update dev/ci/README-users.md after #19926
  dev/ci/README-users.md
Labels: kind: documentation

#19936 CI: add job printing stats about the current pipeline
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
  dev/tools/pipeline-stats.py
Labels: kind: infrastructure

#19942 CI: perennial depends on stdlib+flambda not stdlib
  .gitlab-ci.yml
Labels: kind: infrastructure

#19913 Universe constraint sources are `Escape`
  test-suite/output/PrintUnivsSubgraph.out
  test-suite/output/PrintUnivsSubgraph.v
  vernac/declareUniv.ml
  vernac/vernacentries.ml
Labels: kind: user messages, kind: enhancement

#19853 Perform whd in a separate function in Conversion.eqappr.
  kernel/conversion.ml
Labels: kind: cleanup

#19919 Remove generated dune files on "make clean"
  Makefile
Labels: kind: infrastructure

#19945 Fix coqdep ignoring commands with attributes
  test-suite/coq-makefile/coqdep-attribute/_CoqProject
  test-suite/coq-makefile/coqdep-attribute/a.v
  test-suite/coq-makefile/coqdep-attribute/b.v
  test-suite/coq-makefile/coqdep-attribute/run.sh
  tools/coqdep/lib/lexer.mll
Labels: kind: fix

#19947 Link wiki page about ocamldebug in build-system.md
  dev/doc/build-system.dune.md
Labels: kind: documentation

#19946 Remove warning "overwriting-delimiting-key"
  interp/notation.ml
  stdlib/test-suite/micromega/bug_14054.v
  stdlib/test-suite/output/Sint63NumberSyntax.out
  test-suite/output/DelimitScope.out
  test-suite/output/DelimitScope.v
  test-suite/output/FloatNumberSyntax.out
  test-suite/output/Int63NumberSyntax.out
  theories/ssr/ssrbool.v
Labels: kind: user messages

#19960 Remove unused argument of Retyping make_param_univs
  pretyping/retyping.ml
Labels: kind: cleanup

#19959 Fix dune-dbg (coqdep.bc doesn't exist anymore)
  dev/dune
  dev/dune-dbg.in
Labels: kind: fix, kind: infrastructure

#19944 CI: disable bin_annot (for smaller artifacts)
  .gitlab-ci.yml
  dev/ci/dune-workspace.ci
Labels: kind: infrastructure

#19808 Create HintDb does not erase pre-existing hint db
  doc/changelog/08-vernac-commands-and-options/19808-create-hintdb.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  tactics/hints.ml
  test-suite/success/Hints.v
Labels: kind: fix

#19939 Stdlib: warnings are fatal in dev profile
  stdlib/theories/dune
Labels: kind: infrastructure

#19943 GADT-based representation of module / module types.
  checker/mod_checking.ml
  checker/values.ml
  dev/ci/user-overlays/19943-ppedrot-module-expr-type-gadt.sh
  kernel/declarations.mli
  kernel/declareops.ml
  kernel/declareops.mli
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/modops.mli
  kernel/safe_typing.ml
  kernel/subtyping.ml
  plugins/extraction/extract_env.ml
  vernac/assumptions.ml
  vernac/declaremods.ml
  vernac/printmod.ml
Labels: kind: cleanup

#19938 coq_makefile produce timing info for coqdep
  test-suite/coq-makefile/timing-per-file/after/time-of-build-after.log.desired
  test-suite/coq-makefile/timing-per-file/after/time-of-build-before.log.desired
  test-suite/coq-makefile/timing-per-file/run.sh
  tools/CoqMakefile.in
Labels: kind: infrastructure

#19931 Stop relying on CClosure internals in ring protected reduction.
  kernel/cClosure.ml
  kernel/cClosure.mli
  plugins/ring/ring.ml
Labels: kind: cleanup

#19966 More useful usage message for `rocq`
  topbin/rocq.ml
Labels: kind: documentation, kind: user messages

#19952 stdlib use custom wrapper to avoid depending on coq-core
  .gitlab-ci.yml
  dev/ci/ci-stdlib.sh
  stdlib/.gitignore
  stdlib/coq-stdlib.opam
  stdlib/coq-stdlib.opam.template
  stdlib/dev/with-rocq-wrap.sh
  stdlib/dune-project
Labels: kind: infrastructure

#19967 Don't duplicate timing table for ci-stdlib_test
  dev/ci/ci-wrapper.sh
Labels: kind: infrastructure

#19957 Put back the doc section about `rocq workmgr`
  doc/sphinx/addendum/parallel-proof-processing.rst
Labels: kind: documentation

#19949 EqDec instance for option
  doc/changelog/11-standard-library/19949-option-eqdec.rst
  stdlib/test-suite/success/EquivDec.v
  stdlib/theories/Classes/EquivDec.v
Labels: part: standard library, kind: enhancement
