Repository rocq-prover/rocq, pull requests merged in 2024-08, with the labels that each got.

#19432 [CI] Unpin Jasmin
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/user-overlays/19432-proux01-unpin-jasmin.sh
Labels: kind: cleanup, part: CI

#19434 test suite don't run coqchk with -silent
  test-suite/Makefile
Labels: kind: infrastructure

#19435 Printing Match All Subterms support in debugger
  pretyping/detyping.ml
Labels: kind: user messages

#19443 [CI] Mark jasmin as allow_failure
  .gitlab-ci.yml
Labels: kind: infrastructure

#19423 hconstr don't use push_unknown_rel for matches
  kernel/hConstr.ml
Labels: kind: performance

#19447 bench.sh: Do not attempt to double unlimited stack limit
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#19430 coqchk support -d
  checker/checker.ml
Labels: kind: enhancement

#19438 Local bench download opam after user interaction (asking for commits)
  dev/bench/bench.sh
Labels: kind: infrastructure

#19456 Fix values.ml VM relocations after primitive strings
  checker/values.ml
  test-suite/bugs/bug_19455.v
Labels: kind: fix, part: VM

#19388 Printing tweaks: use format "compacting box" instead of hovbox + tweak `fun =>` break hint
  dev/ci/user-overlays/19388-SkySkimmer-open-box.sh
  lib/pp.ml
  lib/pp.mli
  plugins/micromega/micromega.ml
  printing/ppconstr.ml
  test-suite/output/CantApplyBadType.out
  test-suite/output/Cases.out
  test-suite/output/Notations3.out
  test-suite/output/NumberNotations.out
  test-suite/output/PrintingParentheses.out
  test-suite/output/Record.out
  test-suite/output/ltac2_check_globalize.out
  test-suite/output/ltac2_notations_eval_in.out
  test-suite/output/ltac2_typed_notations.out
  test-suite/output/reduction.out
  test-suite/output/unsat_constraints.out
Labels: kind: user messages

#19436 Always honor `Strict Resolution` (Fixes #15432)
  doc/changelog/04-tactics/19436-janno-strict-resolution.rst
  tactics/class_tactics.ml
  test-suite/bugs/bug_15432.v
Labels: kind: fix

#19433 Hconstr tweak debug and profile printing
  kernel/hConstr.ml
  kernel/hConstr.mli
  kernel/typeops.ml
Labels: kind: internal

#19417 CoqIDE: Improve preferences dialog
  doc/changelog/10-coqide/19417-coqide-preferences.rst
  doc/sphinx/_static/coqide-preferences-editor.png
  doc/sphinx/_static/coqide-preferences-shortcuts.png
  doc/sphinx/_static/coqide-queries.png
  doc/sphinx/_static/coqide.png
  doc/sphinx/practical-tools/coqide.rst
  ide/coqide/configwin.ml
  ide/coqide/configwin.mli
  ide/coqide/configwin_ihm.ml
  ide/coqide/configwin_ihm.mli
  ide/coqide/configwin_messages.ml
  ide/coqide/configwin_messages.mli
  ide/coqide/configwin_types.mli
  ide/coqide/coq_style.xml
  ide/coqide/coqide.ml
  ide/coqide/dune
  ide/coqide/fileOps.ml
  ide/coqide/preferences.ml
  ide/coqide/preferences.mli
  ide/coqide/preferences_ui.ml
  ide/coqide/preferences_ui.mli
  ide/coqide/tags.ml
  ide/coqide/ui_dialogs.ml
  ide/coqide/ui_dialogs.mli
Labels: part: CoqIDE, kind: usability

#19323 add table of locality attributes in refman
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/language/core/modules.rst
  doc/sphinx/language/core/sections.rst
  doc/sphinx/language/extensions/canonical.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/success/locality_attributes_modules.v
  test-suite/success/locality_attributes_modules_ltac2.v
  test-suite/success/locality_attributes_sections.v
  test-suite/success/locality_attributes_sections_in_modules.v
  test-suite/success/locality_attributes_sections_ltac2.v
Labels: kind: documentation

#19463 [CI] Revert "Mark jasmin as allow_failure"
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#19409 Bench: don't print CPU cycles in table
  dev/bench/bench.sh
  dev/bench/render_results.ml
Labels: kind: infrastructure

#19429 coqchk understand sharing when validating
  checker/validate.ml
Labels: kind: performance

#19092 Better integration of Derive in declare.ml + fix of #18951
  doc/changelog/02-specification-language/19092-master+fix18951-anomaly-derive-admitted.rst
  plugins/derive/derive.ml
  plugins/derive/derive.mli
  plugins/derive/g_derive.mlg
  test-suite/bugs/bug_19234.v
  test-suite/success/Derive.v
  vernac/declare.ml
  vernac/declare.mli
  vernac/vernacentries.ml
  vernac/vernacentries.mli
Labels: kind: fix, kind: cleanup, kind: enhancement, part: derive

#19474 Tweak formatting of "Print HintDb" output
  tactics/hints.ml
  test-suite/output/HintLocality.out
Labels: kind: usability
