Repository rocq-prover/rocq, pull requests merged in 2024-01, with the labels that each got.

#18336 Split the Micromega library in two components.
  dev/ci/user-overlays/18336-SkySkimmer-micromega-split-library.sh
  lib/core_plugins_findlib_compat.ml
  plugins/micromega/dune
  plugins/micromega/micromega_core_plugin.mllib
  test-suite/micromega/witness_tactics.v
  theories/micromega/Lia.v
  theories/micromega/Lqa.v
  theories/micromega/Lra.v
  theories/micromega/Psatz.v
  tools/dune_rule_gen/coq_rules.ml
Labels: kind: cleanup

#18460 Fix broken url
  engine/logic_monad.ml
Labels: kind: internal

#18461 translation of dev/doc/style.txt in md
  dev/doc/style.md
  dev/doc/style.txt
Labels: kind: documentation

#18418 release process: add note about adding a stable source archive
  dev/doc/release-process.md
Labels: kind: documentation, kind: internal

#18465 Fix type of Ltac2's Std.fix_ and Std.cofix_
  user-contrib/Ltac2/Std.v
Labels: kind: fix

#18396 Internal cleanup: factorization of the code of interp_context_evars and interp_named_context_evars + ability to share types
  interp/constrintern.ml
  interp/constrintern.mli
Labels: kind: cleanup, part: elaboration

#18094 rewrite strategies: expose fixpoint operator (take 2)
  dev/ci/user-overlays/18094-JasonGross-stratfix.sh
  doc/changelog/05-Ltac-language/18094-stratfix.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_rewrite.mlg
  plugins/ltac/g_rewrite.mli
  plugins/ltac/pptactic.mli
  plugins/ltac/tacexpr.ml
  plugins/ltac/tacexpr.mli
  plugins/ltac/tacintern.ml
  plugins/ltac/tacintern.mli
  plugins/ltac/tacinterp.ml
  plugins/ltac/tacinterp.mli
  plugins/ltac/tacsubst.ml
  plugins/ltac/tacsubst.mli
  tactics/redexpr.mli
  tactics/rewrite.ml
  tactics/rewrite.mli
  test-suite/bugs/bug_18463.v
  test-suite/output/rewrite_strat.out
  test-suite/output/rewrite_strat.v
  test-suite/success/rewrite_strat.v
Labels: part: ltac, kind: enhancement, part: ltac2

#18466 Compatibility of #18338 with MacOS: BSD style needs a specific call to "script"
  dev/ci/ci-wrapper.sh
Labels: kind: infrastructure, kind: enhancement, part: CI

#18431 coqdoc: update refman and stdlib URLs
  tools/configure/configure.ml
Labels: kind: usability

#18395 In "intro y" on a goal statement which is an existential variable, use the name "y" in the context of all resulting goals
  doc/changelog/04-tactics/18395-master+use-intro-name-in-evar-context-when-goal-is-evar.rst
  pretyping/evardefine.ml
  pretyping/evardefine.mli
  tactics/tactics.ml
  test-suite/success/intros.v
Labels: part: tactics, kind: enhancement, part: existential variables

#18229 The kernel does not care about whether a subtype of an inductive type is nested or not
  checker/checkInductive.ml
  checker/values.ml
  dev/ci/user-overlays/18229-herbelin-master+guard-merging-rec-nested.sh
  kernel/declarations.mli
  kernel/declareops.ml
  kernel/indtypes.ml
  kernel/inductive.ml
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  tactics/elimschemes.ml
  tactics/tacticals.ml
  test-suite/success/NestedInd.v
  vernac/auto_ind_decl.ml
Labels: kind: cleanup, part: kernel, part: inductives

#18214 [zify] use the current injection to guide the transformation.
  plugins/micromega/zify.ml
  plugins/micromega/zify.mli
  test-suite/bugs/bug_17983.v
Labels: kind: fix, part: micromega

#18447 Fixes #18342: try to insert an entry coercion when a notation in a custom entry has arguments
  doc/changelog/03-notations/18447-master+fix18342-insert-entry-coercion-applied-custom-notation.rst
  interp/constrextern.ml
  interp/notation.ml
  interp/notation.mli
  test-suite/output/bug_18342.out
  test-suite/output/bug_18342.v
Labels: kind: fix, part: notations, kind: enhancement, part: custom

#18429 gitignore *.install
  .gitignore
Labels: kind: infrastructure

#18469 Delay the lookup of csdp until the tool is actually needed.
  plugins/micromega/coq_micromega.ml
Labels: kind: performance, part: micromega

#18442 Fixes #15020: printing implicit arguments in the presence of notations
  doc/changelog/08-vernac-commands-and-options/18442-master+fixes15020-print-about-fully-see-through-notations.rst
  interp/constrextern.ml
  test-suite/output/Arguments.out
  test-suite/output/Search.out
  test-suite/output/bug_15020.out
  test-suite/output/bug_15020.v
  test-suite/output/bug_3810.out
Labels: kind: fix, part: printer, part: implicit arguments

#18448 Fixes #18434: arguments of --external in coqdoc were inadvertently swapped
  doc/changelog/09-cli-tools/18448-master+fix18434-coqdoc-external-regression.rst
  tools/coqdoc/cmdArgs.ml
Labels: kind: fix, part: coqdoc

#18444 Documenting and reorganizing prettyp.ml; showing implicit arguments also in the main type shown by "Print"
  doc/changelog/08-vernac-commands-and-options/18444-master+cleaning-print-about.rst
  test-suite/output/Arguments_renaming.out
  test-suite/output/Implicit.out
  test-suite/output/PatternsInBinders.out
  test-suite/output/PrintMatch.out
  test-suite/output/PrintModule.out
  test-suite/output/UnivBinders.out
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/printmod.ml
  vernac/vernacentries.ml
Labels: kind: enhancement, part: printer, part: implicit arguments

#18472 Add debug printer for goal_with_state
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
Labels: kind: internal

#18477 small typo in modules doc
  doc/sphinx/language/core/modules.rst
Labels: kind: documentation

#18445 More robust treatment of maximal implicit arguments in notations
  dev/ci/user-overlays/18445-herbelin-master+more-robust-notations-with-max-impargs.sh
  doc/changelog/03-notations/18445-master+more-robust-notations-with-max-impargs.rst
  interp/constrextern.ml
  interp/constrintern.ml
  interp/impargs.ml
  test-suite/success/Notations.v
  test-suite/success/implicit.v
Labels: kind: fix, kind: enhancement, part: printer, part: implicit arguments

#18435 Reduce docker size
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
  dev/ci/docker/old_ubuntu_lts/Dockerfile
Labels: kind: infrastructure, kind: enhancement, part: CI

#18487 Add documentation in NZAxioms
  theories/Numbers/NatInt/NZAxioms.v
Labels: kind: documentation, part: standard library

#18411 Ltac2: support let rec and pure projections as syntactic values
  doc/changelog/06-Ltac2-language/18411-ltac2-more-values.rst
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2interp.ml
Labels: kind: enhancement

#18492 Fix caching in Tacred.reference_eval and cache univ poly
  pretyping/tacred.ml
  test-suite/bugs/bug_18490.v
Labels: kind: fix, kind: performance

#18443 Granting wish #18097: Print and About see through abbreviations playing the role of aliases
  dev/ci/user-overlays/18443-herbelin-master+wish18097-print-about-see-through-aliases.sh
  interp/notation.ml
  interp/notation.mli
  test-suite/output/PrintInfos.out
  test-suite/output/bug_12777.out
  test-suite/output/wish_18097.out
  test-suite/output/wish_18097.v
  vernac/prettyp.ml
  vernac/prettyp.mli
Labels: kind: user messages, part: printer

#18494 Fix gzipping profile files with coq_makefile combined glob/vo rule
  tools/CoqMakefile.in
Labels: kind: fix, part: build

#18486 Update CI branch for coqtail (master -> main)
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#18496 [v8.17] Backport PR #17638: Guard many unguarded `try..with` expressions
  parsing/cLexer.ml
  parsing/pcoq.ml
  plugins/funind/indfun_common.ml
  plugins/ltac2/tac2core.ml
  plugins/micromega/persistent_cache.ml
  plugins/ssr/ssrbwd.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrvernac.mlg
  plugins/ssrmatching/ssrmatching.ml
  pretyping/detyping.ml
  pretyping/evarconv.ml
  printing/proof_diffs.ml
  proofs/proof_bullet.ml
  stm/stm.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  tools/coqworkmgr/coqworkmgrApi.ml
  vernac/assumptions.ml
  vernac/egramcoq.ml
  vernac/vernacentries.ml
Labels: kind: fix

#18471 Support explicit package versions in bench
  dev/bench/bench.sh
  dev/bench/wrapper.sh
Labels: kind: infrastructure

#18500 Deprecate Nat and Int implementations in Numbers
  doc/stdlib/hidden-files
  doc/stdlib/index-list.html.template
  theories/Numbers/Integer/Binary/ZBinary.v
  theories/Numbers/Integer/NatPairs/ZNatPairs.v
  theories/Numbers/Natural/Binary/NBinary.v
Labels: kind: cleanup, part: standard library

#18498 doc NZBase, NZadd, NZOrder
  theories/Numbers/NatInt/NZAdd.v
  theories/Numbers/NatInt/NZBase.v
  theories/Numbers/NatInt/NZOrder.v
Labels: kind: documentation, part: standard library

#18478 document Print Namespace
  doc/sphinx/language/core/modules.rst
Labels: kind: documentation, part: modules

#18473 Release summary for 8.19
  .mailmap
  doc/sphinx/changes.rst
Labels: kind: documentation

#18513 SsrIdents: use declare_bool_option_and_ref
  plugins/ssr/ssrparser.mlg
Labels: kind: fix, part: ssreflect, part: vernac

#18511 Forbid opening a functor with `Import`
  test-suite/bugs/bug_18504.v
  vernac/declaremods.ml
Labels: kind: fix

#18483 NewProfile: don't include full trace for unification and conversion
  lib/newProfile.ml
Labels: kind: infrastructure

#18514 [nit] Use standard `Summary.ref` for regular Summary reference
  interp/notationextern.ml
Labels: kind: cleanup, part: vernac

#17808 [build] [doc] Fix coq-doc package
  doc/changelog/12-infrastructure-and-dependencies/17808-coq-doc-pkg.rst
  doc/dune
  doc/stdlib/dune
  dune-project
Labels: kind: documentation, part: build

#18501 Document AddOrder Mul and MulOrder in NatInt
  doc/changelog/11-standard-library/18501-more_NatInt_doc.rst
  doc/stdlib/hidden-files
  doc/stdlib/index-list.html.template
  theories/Numbers/Integer/Abstract/ZBase.v
  theories/Numbers/NatInt/NZAddOrder.v
  theories/Numbers/NatInt/NZMul.v
  theories/Numbers/NatInt/NZMulOrder.v
  theories/Numbers/NatInt/NZProperties.v
  theories/Numbers/Natural/Abstract/NBase.v
Labels: kind: cleanup, kind: documentation, part: standard library

#18517 Add changelog entry for #18500
  doc/changelog/11-standard-library/18500-deprecations_in_Numbers.rst
Labels: kind: documentation, part: standard library

#18507 Module subtyping: primitive fields cannot be implemented
  dev/doc/critical-bugs
  doc/changelog/01-kernel/18507-fix-subtype-prim.rst
  kernel/subtyping.ml
  test-suite/bugs/bug_18503.v
Labels: kind: fix, part: kernel

#18519 Fix computation of possible evar projections.
  pretyping/evarconv.ml
Labels: kind: cleanup

#18530 Integrate last changelogs for 8.19
  doc/changelog/01-kernel/18507-fix-subtype-prim.rst
  doc/changelog/09-cli-tools/18448-master+fix18434-coqdoc-external-regression.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#18508 Bench: use 4.14.1 by default
  dev/bench/bench.sh
Labels: kind: infrastructure

#18542 Remove dune file in test-suite/unit-tests/parsing
  test-suite/unit-tests/parsing/dune
Labels: kind: infrastructure

#18543 Fixed documentation XML Add call
  dev/doc/xml-protocol.md
Labels: kind: documentation

#18479 Linter: print errors in red
  dev/lint-commits.sh
  dev/tools/check-cachekey.sh
  dev/tools/check-eof-newline.sh
  dev/tools/check-overlays.sh
Labels: kind: infrastructure

#18539 Deprecate NZDomain
  doc/changelog/11-standard-library/18539-deprecate_NZDomain.rst
  doc/stdlib/hidden-files
  doc/stdlib/index-list.html.template
  theories/Numbers/NatInt/NZAxioms.v
  theories/Numbers/NatInt/NZDomain.v
Labels: kind: cleanup, part: standard library

#18544 Deprecate ZDivEucl and Zeuclid
  doc/changelog/11-standard-library/18544-deprecate_Zeuclid.rst
  doc/stdlib/hidden-files
  doc/stdlib/index-list.html.template
  theories/Numbers/Integer/Abstract/ZDivEucl.v
  theories/ZArith/Zeuclid.v
Labels: kind: cleanup, part: standard library

#18476 CI: Support overriding colors even when CI is set
  dev/ci/ci-wrapper.sh
Labels: kind: infrastructure, part: CI

#18552 [CI] Fix after move of Analysis to MC2
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#18538 Deprecate Arith/Bool_nat
  doc/changelog/11-standard-library/18538-deprecate_Bool_nat.rst
  doc/stdlib/hidden-files
  doc/stdlib/index-list.html.template
  theories/Arith/Bool_nat.v
Labels: kind: cleanup, part: standard library

#18561 Tac2ffi.repr: remove unused field "r_id"
  plugins/ltac2/tac2ffi.ml
Labels: kind: cleanup

#18574 check-cachekey: don't use `function`
  dev/tools/check-cachekey.sh
Labels: kind: fix, kind: infrastructure

#18481 Avoid extra univ constraint in array literal elaboration
  pretyping/pretyping.ml
  test-suite/bugs/bug_18480.v
Labels: kind: fix

#18529 Remove Dyn.anonymous
  clib/dyn.ml
  clib/dyn.mli
  clib/exninfo.ml
  clib/exninfo.mli
  clib/store.ml
  clib/store.mli
  dev/ci/user-overlays/18529-SkySkimmer-dyn-no-anon.sh
  lib/loc.ml
  lib/stateid.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac/tactic_debug.ml
  plugins/ltac2/tac2bt.ml
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2intern.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrcommon.mli
  plugins/ssr/ssripats.ml
  plugins/ssr/ssrview.ml
  proofs/proof.ml
  proofs/proof.mli
  proofs/proof_bullet.ml
  stm/partac.ml
  tactics/hints.ml
  vernac/egramcoq.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#18551 Ltac2.Ltac1: add to/of_preterm
  doc/changelog/06-Ltac2-language/18551-ltac2-ltac1-uconstr.rst
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2print.ml
  plugins/ltac2_ltac1/tac2core_ltac1.ml
  user-contrib/Ltac2/Ltac1.v
Labels: kind: feature, part: ltac2

#18557 Remove non-run broken test
  test-suite/ltac2/stuff/ltac2.v
Labels: kind: internal

#18527 [coqdoc] Fix #18516 (handling of Context)
  doc/changelog/09-cli-tools/18527-hack_18516.rst
  interp/dumpglob.mli
  test-suite/coqdoc/Context.html.out
  test-suite/coqdoc/Context.tex.out
  test-suite/coqdoc/Context.v
  vernac/comAssumption.ml
Labels: kind: fix, part: coqdoc

#18421 Vernactypes: combine In and Out infos and abstract use of state info
  vernac/vernacentries.ml
  vernac/vernacinterp.ml
  vernac/vernactypes.ml
  vernac/vernactypes.mli
Labels: kind: cleanup, part: vernac

#18564 rename push lemmas for `List.length` to match convention
  doc/changelog/11-standard-library/18564-rename-push-length.rst
  theories/FSets/FMapFacts.v
  theories/FSets/FMapPositive.v
  theories/FSets/FSetProperties.v
  theories/Lists/List.v
  theories/Logic/FinFun.v
  theories/MSets/MSetProperties.v
  theories/MSets/MSetRBT.v
  theories/Numbers/DecimalFacts.v
  theories/Numbers/HexadecimalFacts.v
  theories/Reals/RList.v
  theories/Reals/RiemannInt_SF.v
  theories/Sorting/PermutEq.v
  theories/Sorting/PermutSetoid.v
  theories/Sorting/Permutation.v
Labels: kind: cleanup, part: standard library

#18541 small doc improvements around open_constr
  doc/sphinx/user-extensions/syntax-extensions.rst
  user-contrib/Ltac2/Ltac1.v
Labels: kind: documentation

#18370 Ltac2: Take some small APIs from rewriter (fst/snd)
  doc/changelog/06-Ltac2-language/18370-ltac2-apis.rst
  test-suite/output/ltac2_printabout.out
  user-contrib/Ltac2/Init.v
Labels: kind: feature

#18547 Remove outdated item in release process
  dev/doc/release-process.md
Labels: kind: documentation

#18595 fix typo in changelog
  doc/sphinx/changes.rst
Labels: kind: documentation
