Repository rocq-prover/rocq, pull requests merged in 2024-05, with the labels that each got.

#18766 Ltac2 #[abstract] attribute for types
  doc/changelog/06-Ltac2-language/18766-ltac2-abstract-type.rst
  doc/sphinx/proof-engine/ltac2.rst
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  plugins/ltac2/tac2print.ml
  test-suite/output/ltac2_abstract.out
  test-suite/output/ltac2_abstract.v
Labels: kind: feature, part: ltac2

#18717 CoqIDE: Improve menu items and accelerators
  doc/changelog/10-coqide/18717-coqide.rst
  doc/sphinx/practical-tools/coqide.rst
  ide/coqide/coq.ml
  ide/coqide/coqide.ml
  ide/coqide/coqide_main.ml
  ide/coqide/coqide_ui.ml
  ide/coqide/preferences.ml
  ide/coqide/preferences.mli
  ide/coqide/wg_Debugger.ml
  ide/coqide/wg_Debugger.mli
  ide/coqide/wg_MessageView.ml
  ide/coqide/wg_MessageView.mli
  ide/coqide/wg_ProofView.ml
  ide/coqide/wg_ProofView.mli
  ide/coqide/wg_RoutedMessageViews.ml
  ide/coqide/wg_RoutedMessageViews.mli
  ide/coqide/wg_ScriptView.ml
  ide/coqide/wg_ScriptView.mli
Labels: part: CoqIDE, kind: usability

#18906 [lib] Try to handle critical exceptions from memprof.
  clib/exninfo.mli
  coq-core.opam
  doc/changelog/12-infrastructure-and-dependencies/18906-fix_memprof_noncritical.rst
  dune-project
  lib/cErrors.ml
  lib/cErrors.mli
  lib/dune
  lib/interrupted.memprof.ml
  lib/interrupted.mli
  lib/interrupted.std.ml
Labels: kind: enhancement, part: build, kind: internal, part: ocaml

#18909 Slightly tweak the interpretation of using clause for eauto tactics.
  doc/changelog/04-tactics/18909-hint-using-strict-globref.rst
  tactics/hints.ml
  test-suite/bugs/bug_4354.v
  test-suite/bugs/bug_4450.v
  test-suite/bugs/bug_5501.v
  theories/Sorting/PermutSetoid.v
Labels: kind: cleanup

#18944 Improve incomplete proof errors
  doc/changelog/04-tactics/18944-prepare-proof-given-up.rst
  proofs/proof.ml
  proofs/proof.mli
  test-suite/bugs/bug_18942.v
  vernac/declare.ml
Labels: kind: fix, kind: user messages

#18955 Bench: use a normal package for the test suite
  dev/bench/bench.sh
  tools/CoqMakefile.in
Labels: kind: infrastructure

#18907 Extraction: print the name of the axiom in [failwith "axiom to be realized"]
  plugins/extraction/extraction.ml
  plugins/extraction/haskell.ml
  plugins/extraction/json.ml
  plugins/extraction/miniml.ml
  plugins/extraction/miniml.mli
  plugins/extraction/mlutil.ml
  plugins/extraction/modutil.ml
  plugins/extraction/ocaml.ml
  plugins/extraction/scheme.ml
  test-suite/output/Extraction_ffi.out
  test-suite/output/Extraction_ffi.v
Labels: part: extraction, kind: enhancement

#18993 Update "custom toplevel" documentation
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation, kind: infrastructure, part: build, part: toplevel

#18995 load_printer memprof_limits.cma in dev/db
  dev/db
Labels: kind: infrastructure, part: build, kind: internal

#18992 Remove useless code in coqtop_bin
  topbin/coqtop_bin.ml
Labels: kind: cleanup, part: ocaml, part: toplevel

#18991 Fix dependent evars line with defined evars
  printing/printer.ml
  test-suite/output-coqtop/DependentEvars3.out
  test-suite/output-coqtop/DependentEvars3.v
Labels: kind: fix

#18997 More informative printing of "params should be the same" error for inductives
  test-suite/output/Inductive.out
  test-suite/output/Inductive.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
Labels: kind: user messages

#18945 Fix abstract vs given up goals for 8.19
  doc/sphinx/changes.rst
  proofs/proof.ml
  proofs/proof.mli
  test-suite/bugs/bug_18942.v
  vernac/declare.ml
Labels: kind: fix

#18866 Fix RR hnf idempotency
  pretyping/tacred.ml
  test-suite/bugs/bug_18854.v
Labels: kind: fix, part: rewrite rules

#18940 Ltac2 auto-like tactics now take references in the using clause.
  doc/changelog/06-Ltac2-language/18940-ltac2-auto-ref-using.rst
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ltac2/tac2tactics.mli
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
Labels: kind: cleanup

#18988 Ltac2: Expose message boxing primitives
  doc/changelog/06-Ltac2-language/18988-ltac2-message-box.rst
  plugins/ltac2/tac2core.ml
  user-contrib/Ltac2/Message.v
Labels: kind: feature

#17986 Extrude uniform parameters of inner fixpoints in guard condition check (grant #16040)
  clib/cList.ml
  clib/cList.mli
  doc/changelog/01-kernel/17986-master+fix16040-guard-extrude-fix-parameter.rst
  interp/constrextern.ml
  interp/constrintern.ml
  interp/impargs.ml
  kernel/inductive.ml
  test-suite/success/Fixpoint.v
  vernac/comSearch.ml
Labels: kind: enhancement, part: inductives

#18809 Fix `Strategy`/`with_strategy`: set projection opacity.
  tactics/tactics.ml
  test-suite/bugs/bug_18809.v
  test-suite/success/primitive_strategy.v
  vernac/vernacentries.ml
Labels: kind: fix

#18785 Restore ability to make primitive projections hint opaque.
  doc/changelog/08-vernac-commands-and-options/18785-janno-fix-dnet-proj.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  printing/printer.ml
  printing/printer.mli
  tactics/btermdn.ml
  tactics/hints.ml
  tactics/hints.mli
  tactics/redexpr.ml
  test-suite/output/HintLocality.out
  test-suite/success/primitive_tc.v
  vernac/comHints.ml
  vernac/g_proofs.mlg
  vernac/ppvernac.ml
Labels: kind: fix

#18718 Store VM relocations that do not need substitution on disk.
  checker/values.ml
  kernel/vmemitcodes.ml
Labels: kind: performance, part: VM

#18994 [dune] [nit] Remove unneeded dependency on findlib.dynload
  dev/doc/build-system.dune.md
  topbin/dune
Labels: part: build, kind: internal, part: toplevel

#18890 [declare] Consolidate `Proof Using` handling.
  dev/ci/user-overlays/18890-ejgallego-no_using_cinfo.sh
  test-suite/success/definition_using.v
  test-suite/success/proof_using.v
  vernac/comDefinition.ml
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/vernacentries.ml
Labels: kind: fix, kind: cleanup, part: vernac

#19005 Cleanup coq_makefile doc about using -j
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#19010 improve Strings/Byte performance
  theories/Strings/Byte.v
Labels: kind: performance, part: standard library

#18979 Enter `Hint Extern` patterns syntactically into the Bnet
  tactics/btermdn.ml
  tactics/btermdn.mli
  tactics/hints.ml
Labels: kind: redesign

#18628 More bitwise in Numbers.Natural.Abstract
  doc/changelog/11-standard-library/18628-more_bitwise_in_Natural.rst
  test-suite/success/strong_and_binary_induction.v
  theories/Arith/PeanoNat.v
  theories/NArith/BinNat.v
  theories/Numbers/NatInt/NZParity.v
  theories/Numbers/Natural/Abstract/NBits.v
  theories/Numbers/Natural/Abstract/NMulOrder.v
  theories/Numbers/Natural/Abstract/NOrder.v
  theories/Numbers/Natural/Abstract/NPow.v
  theories/Numbers/Natural/Abstract/NSub.v
Labels: part: standard library, kind: enhancement

#19009 Ltac2: runtime representation of univ instance is the raw instance
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
Labels: kind: cleanup

#18996 Remove the tag branch information from case_info.
  checker/values.ml
  dev/ci/user-overlays/18996-ppedrot-case-info-rm-tags.sh
  kernel/constr.ml
  kernel/constr.mli
  plugins/extraction/extraction.ml
  pretyping/detyping.ml
  pretyping/inductiveops.ml
Labels: kind: cleanup

#19006 Deprecate non-reference hints in using clauses of auto-like tactics.
  doc/changelog/04-tactics/19006-hint-using-deprecate-constr.rst
  tactics/hints.ml
  test-suite/bugs/bug_4450.v
  test-suite/success/auto.v
  theories/Logic/ChoiceFacts.v
  theories/Sorting/PermutSetoid.v
  theories/Structures/OrdersTac.v
Labels: kind: cleanup

#19018 Bench: print size diff in vosize.log
  dev/bench/bench.sh
Labels: kind: infrastructure

#18998 [declare] Call interp_proof_using only once per mutual block.
  vernac/declare.ml
Labels: kind: cleanup, kind: enhancement

#19016 Automatically register induction schemes from Scheme
  doc/changelog/08-vernac-commands-and-options/19016-scheme-auto-register.rst
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  test-suite/bugs/bug_3132.v
  vernac/indschemes.ml
Labels: kind: fix

#19022 univminim: always use lbound:Set when adding univs to ugraph
  engine/univMinim.ml
Labels: kind: cleanup

#19025 additions/corrections about scopes in the refman
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation, part: notations

#19020 Compatibility of new fast "make report" with MacOS X
  test-suite/Makefile
  test-suite/report.sh
Labels: kind: infrastructure

#19019 Add convenience API Sorts.make taking quality and universe
  engine/uState.ml
  kernel/sorts.ml
  kernel/sorts.mli
Labels: kind: internal

#18941 autobuild .merlin files in CI scripts for some plugins
  dev/ci/ci-equations.sh
  dev/ci/ci-lean_importer.sh
  dev/ci/ci-mtac2.sh
  dev/ci/ci-relation_algebra.sh
  dev/ci/ci-smtcoq.sh
  dev/ci/ci-unicoq.sh
Labels: kind: infrastructure

#19028 Remove the Evd.sig datatype.
  engine/evd.ml
  engine/evd.mli
Labels: kind: cleanup

#19015 Factor the lambda compilation passes of VM and native
  kernel/genlambda.ml
  kernel/genlambda.mli
  kernel/nativelambda.ml
  kernel/vmbytegen.ml
  kernel/vmlambda.ml
  kernel/vmlambda.mli
Labels: kind: cleanup

#18743 Making `Theorem with` more flexible + code cleanup
  dev/ci/user-overlays/18743-herbelin-master+more-flexible-theorem-with.sh
  doc/changelog/02-specification-language/18743-master+more-flexible-theorem-with.rst
  engine/eConstr.mli
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  tactics/tactics.ml
  test-suite/success/Fixpoint.v
  vernac/comFixpoint.ml
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/recLemmas.ml
  vernac/recLemmas.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: enhancement, part: vernac, part: inductives

#18983 Add Fixpoint and CoFixpoint in Search logical_kind
  doc/changelog/08-vernac-commands-and-options/18983-SearchFixpoint.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  test-suite/output/SearchFixpoint.out
  test-suite/output/SearchFixpoint.v
  vernac/g_vernac.mlg
Labels: kind: feature, part: search

#19021 Faster composed module substitution of terms.
  checker/check.ml
  kernel/mod_subst.ml
  kernel/mod_subst.mli
  vernac/library.ml
Labels: kind: performance

#18981 Support syntax `Type@{q | _}`
  dev/ci/user-overlays/18981-SkySkimmer-sort-expr-anon-univ.sh
  doc/sphinx/language/core/sorts.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  interp/constrexpr.mli
  interp/constrexpr_ops.ml
  interp/constrexpr_ops.mli
  interp/constrextern.ml
  interp/constrintern.ml
  interp/notation.ml
  interp/notation_ops.ml
  parsing/g_constr.mlg
  plugins/funind/glob_term_to_relation.ml
  plugins/ssr/ssrcommon.ml
  pretyping/detyping.ml
  pretyping/glob_ops.ml
  pretyping/glob_ops.mli
  pretyping/glob_term.mli
  pretyping/pretyping.ml
  printing/ppconstr.ml
  test-suite/bugs/bug_18978.v
  test-suite/misc/quotation_token/src/quotation.mlg
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: enhancement, part: universes, part: parser, part: sort polymorphism

#18641 Ltac2: warn on unused variables
  clib/cString.ml
  clib/cString.mli
  doc/changelog/06-Ltac2-language/18641-ltac2-warn-unused.rst
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2typing_env.ml
  plugins/ltac2/tac2typing_env.mli
  test-suite/output/PrintGenarg.out
  test-suite/output/PrintGenarg.v
  test-suite/output/bug_18138.v
  test-suite/output/ltac2_unused_var.out
  test-suite/output/ltac2_unused_var.v
  user-contrib/Ltac2/Array.v
  user-contrib/Ltac2/List.v
  user-contrib/Ltac2/Notations.v
Labels: kind: enhancement, part: ltac2

#18714 Ltac2 `assert` scope: intern and typecheck types as types
  interp/notation.ml
  interp/notation.mli
  plugins/ltac2/tac2quote.ml
  test-suite/ltac2/std_tactics.v
  user-contrib/Ltac2/Constr.v
Labels: kind: fix, part: ltac2

#18956 Do not rely on floating universes in the upper layers
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  interp/constrintern.ml
  interp/constrintern.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/indTyping.ml
  library/global.ml
  library/global.mli
  plugins/funind/glob_termops.ml
  plugins/ltac/g_auto.mlg
  plugins/ltac/internals.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ring/ring.ml
  plugins/ssr/ssrcommon.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  tactics/evar_tactics.ml
  tactics/induction.ml
  tactics/tactics.ml
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: cleanup

#18915 Fixes #11766 and #11988: restrict universes in obligations
  doc/changelog/02-specification-language/18915-master+fixes11902-restrict-univ-obligations.rst
  test-suite/bugs/bug_11766.v
  vernac/declare.ml
Labels: kind: fix, part: program

#19036 Fix coqdoc handling of empty logical path
  tools/coqdoc/cmdArgs.ml
Labels: kind: fix, part: coqdoc

#19026 [8.20] Update compat infrastructure prior to branching
  doc/stdlib/index-list.html.template
  sysinit/coqargs.ml
  test-suite/success/CompatOldOldFlag.v
  test-suite/tools/update-compat/run.sh
  theories/Compat/Coq817.v
Labels: kind: cleanup

#19042 Fix handling of sort poly squash in typing.ml
  pretyping/cases.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/typing.ml
  test-suite/bugs/bug_19039.v
Labels: kind: fix

#19045 Small code factorization of qvar generation in pretyping
  pretyping/pretyping.ml
Labels: kind: cleanup

#19044 Print qvar names in Show Universes / ocamldebug ustate printer
  engine/uState.ml
Labels: kind: user messages

#19046 Fix debug printing of Lambda projections.
  kernel/genlambda.ml
Labels: kind: internal

#19014 Track unused constant arguments in Genlambda and erase them.
  checker/values.ml
  kernel/genlambda.ml
  kernel/genlambda.mli
  kernel/nativecode.ml
  kernel/safe_typing.ml
  kernel/vmbytegen.ml
  kernel/vmbytegen.mli
  kernel/vmemitcodes.ml
  kernel/vmemitcodes.mli
  kernel/vmsymtable.ml
Labels: kind: performance, part: VM, part: native compiler

#19017 Fix incorrect handling of Elimination and Case schemes
  doc/changelog/08-vernac-commands-and-options/19017-scheme-norec.rst
  test-suite/bugs/bug_10816.v
  vernac/indschemes.ml
  vernac/indschemes.mli
Labels: kind: fix

#19064 Force empty case nodes from irrelevant to relevant sorts to be CaseInvert
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/conversion.ml
  kernel/typeops.ml
  test-suite/bugs/bug_19041.v
Labels: kind: fix, part: kernel

#19063 Add tests for bug #4160.
  test-suite/bugs/bug_4160_1.v
  test-suite/bugs/bug_4160_2.v
Labels: kind: internal

#19071 Slight comment update after empty matches got CaseInvert
  kernel/constr.mli
  kernel/typeops.mli
Labels: kind: internal

#19060 Allow a direction specifier in replace with.
  doc/changelog/04-tactics/19060-replace-with-diropt.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/extratactics.mlg
  plugins/ltac/internals.ml
  plugins/ltac/internals.mli
  tactics/equality.ml
  tactics/equality.mli
  test-suite/bugs/bug_13480.v
Labels: kind: fix, kind: enhancement

#19058 Fix the man pages' formatting.
  man/coq-tex.1
  man/coq_makefile.1
  man/coqc.1
  man/coqchk.1
  man/coqdep.1
  man/coqdoc.1
  man/coqide.1
  man/coqnative.1
  man/coqtop.1
  man/coqtop.byte.1
  man/coqwc.1
Labels: kind: documentation

#18820 APIs for elpi stuff
  engine/evd.ml
  engine/evd.mli
  pretyping/structures.ml
  pretyping/structures.mli
Labels: kind: internal

#19002 Phrasing and formatting of the unsatisfiable constraints error message
  engine/termops.ml
  test-suite/output/ClassMissingInstance.out
  test-suite/output/bug_13942.out
  vernac/himsg.ml
Labels: kind: user messages, part: typeclasses, kind: enhancement

#19067 coqpp: use location annotations for attributes
  coqpp/coqpp_ast.mli
  coqpp/coqpp_main.ml
  coqpp/coqpp_parse.mly
Labels: kind: internal

#18449 ssr/have: use opaque constants
  dev/ci/ci-basic-overlay.sh
  plugins/ssr/ssrfwd.ml
  test-suite/output/section_have.out
  theories/ssr/ssreflect.v
Labels: kind: fix, part: ssreflect

#19051 Fix wrapping of guard error with evar map in cofix guard checking
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  test-suite/output/bug_19047.out
  test-suite/output/bug_19047.v
Labels: kind: fix

#19069 Switch default locality for TC transparency to Export + followup cleanup
  doc/changelog/08-vernac-commands-and-options/19069-hint-locality.rst
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_auto.mlg
  plugins/ltac/g_class.mlg
  tactics/autorewrite.ml
  tactics/autorewrite.mli
  tactics/hints.ml
  tactics/hints.mli
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/classes.ml
  vernac/classes.mli
  vernac/vernacentries.ml
Labels: kind: deprecation

#18727 Ltac2: don't use delayed_of_tactic for apply terms
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2tactics.ml
  tactics/tacticals.ml
  tactics/tacticals.mli
  tactics/tactics.ml
  tactics/tactics.mli
  test-suite/ltac2/std_tactics.v
Labels: kind: cleanup, part: ltac2

#19076 Avoid using async proofs cache in output tests
  test-suite/Makefile
  test-suite/output/Arguments_renaming.v
  test-suite/output/Search.out
  test-suite/output/Search.v
  test-suite/output/Search_2.out
  test-suite/output/Search_2.v
  test-suite/output/Search_3.out
  test-suite/output/Search_3.v
  test-suite/output/Search_bug17963.out
  test-suite/output/Search_bug17963.v
  test-suite/output/auto.v
  test-suite/output/library_attributes_require_transitive.out
  test-suite/output/library_attributes_require_transitive.v
  test-suite/output/library_attributes_require_transitive_2.out
  test-suite/output/library_attributes_require_transitive_2.v
  test-suite/output/simpl.v
  test-suite/output/subst.v
  test-suite/output/unification.v
Labels: kind: cleanup

#18964 Add a PUSHENVACCMANY opcode.
  kernel/byterun/coq_interp.c
  kernel/genOpcodeFiles.ml
  kernel/vmemitcodes.ml
Labels: kind: performance, part: VM

#19065 Tweak a weird syntax in CClosure.
  kernel/cClosure.ml
Labels: kind: cleanup

#19050 Code factorization around Evarutil.finalize and prepare_obligations
  vernac/comDefinition.ml
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/retrieveObl.ml
  vernac/retrieveObl.mli
Labels: kind: cleanup, part: universes

#19027 Remove the cutrewrite tactic.
  doc/changelog/04-tactics/19027-rm-cutrewrite.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/extratactics.mlg
  plugins/ltac/internals.ml
  tactics/equality.ml
  tactics/equality.mli
Labels: kind: cleanup

#19085 Canonically renaming List.safe_index into List.index_opt
  clib/cList.ml
  clib/cList.mli
  proofs/proof.ml
Labels: kind: cleanup

#19088 Fixes #19082: regression with primitive projections with defined fields
  doc/changelog/02-specification-language/19088-master+fix19082-branch-length-mismatch.rst
  pretyping/inductiveops.ml
  test-suite/bugs/bug_19082.v
Labels: kind: fix, part: primitive records

#19080 include_constructor_argument don't ignore sort quality when not univ poly
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
Labels: kind: fix

#19089 Fixes #18914: check for overlap between notations was too confidently assuming being in the same entry
  doc/changelog/03-notations/18089-master+fix18914-too-restrictive-notation-overlap-check.rst
  interp/constrextern.ml
  test-suite/output/bug_18914.out
  test-suite/output/bug_18914.v
Labels: kind: fix, part: notations

#19086 A few complex guard condition tests found in CI
  test-suite/success/Fixpoint.v
  test-suite/success/fix.v
Labels: kind: infrastructure, part: test-suite, part: fixpoints

#19083 Various typos, as well as parentheses and spacing enhancement
  kernel/inductive.ml
  kernel/mod_typing.ml
  lib/system.mli
  plugins/funind/recdef.ml
  pretyping/reductionops.mli
  vernac/declare.mli
Labels: kind: cleanup

#19097 Avoid async proofs messing up test output/auto
  test-suite/output/auto.v
Labels: kind: internal

#19034 More efficient compilation of PArray blobs in the VM.
  kernel/vmbytegen.ml
  kernel/vmlambda.ml
  kernel/vmlambda.mli
  kernel/vmvalues.ml
  kernel/vmvalues.mli
Labels: kind: performance, part: VM

#19096 Fix stage of ltac2 notation interp map (Tac2env.ltac_notations)
  plugins/ltac2/tac2env.ml
Labels: kind: fix, part: ltac2

#19093 Fix file extensions in CODEOWNERS.
  .github/CODEOWNERS
Labels: kind: fix, kind: meta

#19052 coq_interp: squelch a incompatible-pointer warning
  kernel/byterun/coq_interp.c
Labels: kind: cleanup, part: VM

#18588 [notation] Add warning for closed notations not at level 0
  doc/changelog/03-notations/18588-closed_notation_level0.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/output/Notations3.out
  theories/Init/Notations.v
  theories/Logic/Hurkens.v
  theories/ssr/ssreflect.v
  theories/ssr/ssrfun.v
  vernac/metasyntax.ml
Labels: kind: user messages, part: notations

#19094 Simplify declaremods internals
  vernac/declaremods.ml
Labels: kind: cleanup

#19078 Add module types USetS UMapS for unordered maps
  clib/cMap.ml
  clib/cMap.mli
  clib/cSig.mli
  clib/hMap.ml
  clib/hMap.mli
  dev/ci/user-overlays/19078-SkySkimmer-csig-umap.sh
  kernel/names.mli
  kernel/univ.mli
  lib/acyclicGraph.ml
  lib/acyclicGraph.mli
  library/globnames.mli
  library/goptions.ml
  library/goptions.mli
  plugins/extraction/table.mli
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2core.mli
Labels: kind: cleanup

#18959 Compress the compiled bytecode.
  kernel/byterun/coq_fix_code.c
  kernel/byterun/coq_interp.c
  kernel/vmemitcodes.ml
Labels: kind: performance, part: VM

#18989 Warn when automatically lowering an inductive declared with `: Type` to Prop
  dev/ci/user-overlays/18989-SkySkimmer-warn-auto-lower.sh
  doc/changelog/06-Ltac2-language/18989-warn-auto-lower.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/language/extensions/canonical.rst
  plugins/funind/glob_term_to_relation.ml
  test-suite/bugs/HoTT_coq_054.v
  test-suite/bugs/bug_4116.v
  test-suite/bugs/bug_5501.v
  test-suite/output/ArgumentsScope.v
  test-suite/output/bug_13266.v
  test-suite/output/inference.v
  test-suite/success/AutoPropLowering.v
  test-suite/success/DependentPropositionEliminators.v
  theories/micromega/OrderedRing.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/declareInd.ml
  vernac/record.ml
Labels: kind: enhancement, part: inductives

#19098 Use a structured type for Unification internal state.
  pretyping/unification.ml
  pretyping/unification.mli
Labels: kind: cleanup

#19081 Use stages in gitlab-ci.yml
  .gitlab-ci.yml
  dev/bench/gitlab-bench.yml
  dev/ci/README-users.md
Labels: kind: infrastructure

#18602 Update of the doc of simpl and cbn, especially wrt "simpl never".
  doc/sphinx/language/extensions/arguments-command.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation, part: reduction strategies

#19121 Move section about ltac1 defects to ltac.rst instead of ltac2.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proofs/creating-tactics/index.rst
Labels: kind: documentation, part: ltac, part: ltac2

#19049 [notations] Warn about incompatible prefixes
  doc/changelog/03-notations/19049-warn_notation_incompatible_prefix.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  parsing/notgram_ops.ml
  parsing/notgram_ops.mli
  test-suite/output/BinaryPrintingNotations.v
  test-suite/output/Notations.out
  test-suite/output/Notations3.out
  test-suite/output/allBytes.out
  test-suite/output/allBytes.v
  test-suite/output/lexical_convention_in_doc.out
  test-suite/output/lexical_convention_in_doc.v
  test-suite/output/notation_prefix_incompatible_level.out
  test-suite/output/notation_prefix_incompatible_level.v
  theories/Program/Utils.v
  theories/Relations/Operators_Properties.v
  theories/ssr/ssreflect.v
  vernac/metasyntax.ml
Labels: kind: user messages, part: notations
