Repository rocq-prover/rocq, pull requests merged in 2024-07, with the labels that each got.

#19293 Codeowners: add flake.lock -> nix maintainers
  .github/CODEOWNERS
Labels: kind: meta

#19258 Merge the execution paths for struct and measure/wf in Program Fixpoint
  interp/constrintern.ml
  interp/constrintern.mli
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/comProgramFixpoint.ml
  vernac/comProgramFixpoint.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, part: program, part: fixpoints

#19090 Add support for Admitted on multiple statements
  vernac/declare.ml
Labels: kind: cleanup, part: gallina

#19160 Avoid retypechecking repeated subterms in typeops
  kernel/constant_typing.ml
  kernel/constant_typing.mli
  kernel/constr.ml
  kernel/constr.mli
  kernel/declareops.ml
  kernel/declareops.mli
  kernel/hConstr.ml
  kernel/hConstr.mli
  kernel/mod_typing.ml
  kernel/safe_typing.ml
  kernel/typeops.ml
  kernel/typeops.mli
  test-suite/bugs/bug_19160_1.v
Labels: kind: performance, part: kernel, kind: enhancement

#19166 CoqIDE: Make tabs reorderable and fix preference on tabs position
  doc/changelog/10-coqide/19166-coqide.rst
  ide/coqide/configwin_ihm.ml
  ide/coqide/coqide.ml
  ide/coqide/wg_Notebook.ml
  ide/coqide/wg_Notebook.mli
Labels: part: CoqIDE, kind: enhancement

#19305 Algorithmically faster computation of argument scopes.
  interp/notation.ml
  test-suite/bugs/bug_19304.v
Labels: kind: fix

#18591 Refolding "simpl never" constants hiding fixpoints in position of argument of a destructor in tactic "simpl"
  dev/ci/user-overlays/18591-herbelin-master+simpl-refold-in-destructor-arg-position.sh
  doc/changelog/04-tactics/18591-master+simpl-refold-in-destructor-arg-position.rst
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/tacred.ml
  test-suite/success/simpl.v
Labels: kind: fix, part: tactics, part: reduction strategies

#19259 Merge the code paths for "CoFixpoint"/"Fixpoint" and "Theorem with"
  plugins/funind/gen_principle.ml
  test-suite/success/proof_using.v
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/recLemmas.ml
  vernac/recLemmas.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, part: fixpoints, part: cofixpoints, part: gallina

#19240 Slightly improve -profile output
  lib/newProfile.ml
Labels: kind: infrastructure

#19272 [CoqIDE] Display warnings in their own tab.
  ide/coqide/coqOps.ml
  ide/coqide/coqOps.mli
  ide/coqide/coqide.ml
  ide/coqide/session.ml
  ide/coqide/session.mli
Labels: kind: fix

#19317 Factorize Case cases in subst_univs_level_constr (trivial cleanup)
  kernel/vars.ml
Labels: kind: cleanup

#19316 Add hint of how to enable native compile in config/dune
  config/dune
Labels: kind: internal

#19291 Avoid calling global_vars_set in constant_typing when not in section
  kernel/constant_typing.ml
Labels: kind: performance

#19321 Mini comments about Declare.shrink
  vernac/declare.ml
Labels: kind: cleanup, kind: internal

#19319 Change rewrite rules arrow to =>
  doc/sphinx/addendum/rewrite-rules.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  test-suite/bugs/bug_18801.v
  test-suite/bugs/bug_18803.v
  test-suite/bugs/bug_18804.v
  test-suite/bugs/bug_18854.v
  test-suite/success/rewrule.v
  test-suite/success/rewrule_quality_match.v
  vernac/g_vernac.mlg
Labels: kind: fix, part: rewrite rules

#19268 [ci] update elpi branch
  .gitlab-ci.yml
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-elpi.sh
  dev/ci/ci-elpi_test.sh
  dev/ci/docker/edge_ubuntu/Dockerfile
Labels: kind: infrastructure, part: CI

#19313 Split a few easy plugins in a Ltac1-free core and a Ltac1 syntax plugin
  dev/ci/user-overlays/19313-ppedrot-ltac1-split-some-plugins.sh
  lib/core_plugins_findlib_compat.ml
  plugins/cc/cc_core_plugin.mllib
  plugins/cc/dune
  plugins/firstorder/dune
  plugins/firstorder/firstorder_core_plugin.mllib
  plugins/firstorder/g_ground.mlg
  plugins/firstorder/ground.ml
  plugins/nsatz/dune
  plugins/nsatz/nsatz_core_plugin.mllib
  theories/Init/Prelude.v
  theories/nsatz/NsatzTactic.v
  tools/dune_rule_gen/coq_rules.ml
Labels: kind: cleanup

#19260 Move code for interactive definitions close to the one for non interactive definitions
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, part: gallina

#19312 Inline calls to Functional Scheme in FMapAVL.
  theories/FSets/FMapAVL.v
  theories/FSets/FMapFullAVL.v
Labels: kind: cleanup, part: funind

#19311 Kernel: report all undeclared universes not just one
  checker/checker.ml
  dev/ci/user-overlays/19311-SkySkimmer-all-undeclared-univs.sh
  engine/uState.ml
  kernel/type_errors.ml
  kernel/type_errors.mli
  kernel/typeops.ml
  kernel/uGraph.ml
  kernel/uGraph.mli
  lib/acyclicGraph.ml
  lib/acyclicGraph.mli
  vernac/comRewriteRule.ml
  vernac/himsg.ml
Labels: kind: user messages

#19334 Fix documentation of overlays after change of coq-elpi branch.
  dev/ci/user-overlays/README.md
Labels: kind: documentation

#19328 Fix double substitution of relevance annotations in cclosure
  kernel/cClosure.ml
  test-suite/bugs/bug_19325.v
Labels: kind: inconsistency

#19331 Remove unknown_ind hack from detyping
  pretyping/detyping.ml
Labels: kind: cleanup

#19338 Trivial cleanup in notations
  interp/constrextern.ml
  interp/notationextern.ml
  interp/notationextern.mli
Labels: kind: cleanup

#19315 Use irrelevance masks to ignore arguments in flex / flex conversions.
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/conversion.ml
  test-suite/bugs/bug_19066.v
Labels: kind: performance

#19300 Quickfix for deprecated
  dev/ci/user-overlays/19300-gares-quickfix-deprecated.sh
  doc/changelog/08-vernac-commands-and-options/19300-quickfix-deprecated.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/using/libraries/writing.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  interp/abbreviation.ml
  interp/abbreviation.mli
  lib/deprecation.ml
  lib/deprecation.mli
  lib/quickfix.ml
  lib/userWarn.ml
  lib/userWarn.mli
  library/libnames.ml
  library/libnames.mli
  library/library_info.ml
  library/nametab.ml
  library/nametab.mli
  test-suite/output/Qf_deprecated.out
  test-suite/output/Qf_deprecated.v
  test-suite/output/Qf_end.out
  test-suite/output/Qf_extraction.out
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/comAssumption.mli
  vernac/comDefinition.mli
  vernac/comFixpoint.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
  vernac/metasyntax.mli
  vernac/vernacentries.ml
Labels: kind: user messages

#19339 [CI] Remove library-undecidability
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-coq_library_undecidability.sh
Labels: kind: infrastructure

#19307 [gen_rules] option -dep to depend on other theories
  tools/dune_rule_gen/coq_rules.ml
  tools/dune_rule_gen/coq_rules.mli
  tools/dune_rule_gen/gen_rules.ml
Labels: kind: infrastructure, part: build

#19329 Unify qualities as needed when elaborating matches
  doc/changelog/02-specification-language/19329-cases-unif-qualities.rst
  pretyping/cases.ml
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/pretyping.ml
  pretyping/typing.ml
  pretyping/typing.mli
  test-suite/bugs/bug_19327.v
  test-suite/success/sort_poly.v
Labels: kind: fix

#19314 Fix exception catchalls
  boot/util.ml
  checker/check.ml
  checker/checker.ml
  clib/terminal.ml
  engine/termops.ml
  kernel/nativelib.ml
  lib/envars.ml
  lib/spawn.ml
  lib/system.ml
  plugins/ltac/tactic_debug.ml
  plugins/micromega/coq_micromega.ml
  plugins/micromega/mutils.ml
  plugins/ssr/ssrcommon.ml
  sysinit/coqinit.ml
  tools/configure/util.ml
  toplevel/common_compile.ml
  toplevel/coqtop.ml
  vernac/indschemes.ml
  vernac/topfmt.ml
Labels: kind: fix, kind: cleanup

#19032 added ltac2 bindings for congruence and simple congruence
  doc/changelog/06-Ltac2-language/19032-ltac2-congruence.rst
  plugins/cc/cctac.ml
  plugins/cc/cctac.mli
  plugins/cc/g_congruence.mlg
  plugins/ltac2/dune
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ltac2/tac2tactics.mli
  test-suite/ltac2/congruence.v
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
Labels: kind: enhancement, part: ltac2

#19340 Simplify memprof_coq.std.ml
  clib/memprof_coq.mli
  clib/memprof_coq.std.ml
Labels: kind: cleanup, kind: internal, part: ocaml

#19345 Add coq-metacoq-common and metacoq-utils to explicit benched packages
  dev/bench/bench.sh
Labels: kind: infrastructure

#19364 Improve "more than one file to compile" error
  toplevel/coqcargs.ml
Labels: kind: user messages

#19352 Cleanup libobjects `rebuild_function`s
  interp/notation.ml
  pretyping/arguments_renaming.ml
  pretyping/coercion.ml
  pretyping/coercionops.ml
  pretyping/coercionops.mli
  pretyping/retyping.ml
  pretyping/retyping.mli
  vernac/classes.ml
  vernac/comCoercion.ml
Labels: kind: cleanup

#19354 Libobject.declare_object_full treats object name like declare_object
  library/libobject.ml
  library/libobject.mli
Labels: kind: cleanup

#19349 Ltac2 cleanup evaluation of globals
  plugins/ltac2/tac2interp.ml
Labels: kind: cleanup, part: ltac2

#19365 [CI] Fix elpi job following https://github.com/LPCIC/coq-elpi/pull/661
  dev/ci/ci-elpi.sh
Labels: kind: infrastructure

#19346 Automatic Proposition Inductives handled more functionally
  dev/ci/user-overlays/19346-SkySkimmer-func-auto-prop-lower.sh
  plugins/funind/glob_term_to_relation.ml
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
  vernac/vernacentries.mli
Labels: kind: cleanup

#19353 Libobject generalize API between discharge and rebuild functions
  library/libobject.ml
  library/libobject.mli
Labels: kind: internal

#19341 Allow eliminating sort poly inductive instantiated to Type at sort poly types
  kernel/inductive.ml
  pretyping/inductiveops.ml
  test-suite/output/sort_poly_elim_error.out
  test-suite/output/sort_poly_elim_error.v
  test-suite/success/sort_poly.v
Labels: kind: feature

#19351 Update comment in libobject.mli + tiny cleanup in declaremods
  library/libobject.mli
  vernac/declaremods.ml
Labels: kind: cleanup

#19216 Adding a modifier "clear simpl" to Arguments to reset "simpl" behavior to its default
  dev/ci/user-overlays/19216-herbelin-clear-simpl.sh
  doc/changelog/08-vernac-commands-and-options/19216-master+clear-simpl.rst
  doc/sphinx/language/extensions/arguments-command.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  test-suite/success/simpl_tuning.v
  vernac/comArguments.ml
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/prettyp.ml
  vernac/vernacexpr.mli
Labels: kind: enhancement, part: reduction strategies

#19371 Remove the last use of FunInd from FMapFullAVL.
  theories/FSets/FMapFullAVL.v
Labels: kind: cleanup

#17560 Add `reg` theorems for `nat` on multiplication
  doc/changelog/11-standard-library/17560-nat_mul_reg.rst
  theories/Numbers/NatInt/NZMulOrder.v
  theories/ZArith/BinInt.v
Labels: part: standard library, kind: enhancement

#19373 Speedup proof of nzhead_revapp in DecimalFacts and HexadecimalFacts
  theories/Numbers/DecimalFacts.v
  theories/Numbers/HexadecimalFacts.v
Labels: kind: performance, part: standard library

#19380 Clarify --index flag in coqdoc.rst
  doc/sphinx/using/tools/coqdoc.rst
Labels: kind: documentation, part: coqdoc

#19375 Minor CI cleanup / fixes around elpi
  Makefile.ci
  dev/ci/ci-elpi_test.sh
Labels: kind: infrastructure

#19369 Fix Inductive.instantiate_context not substituting universes in relevances
  kernel/environ.ml
Labels: kind: fix

#19336 API for fast demote
  dev/ci/user-overlays/19336-gares-demote-demote.sh
  engine/uState.ml
  engine/uState.mli
  engine/univFlex.ml
  engine/univFlex.mli
  vernac/declare.ml
  vernac/declare.mli
Labels: kind: performance, kind: internal

#19361 Fix discharge of Export in section
  dev/ci/user-overlays/19361-SkySkimmer-discharge-export.sh
  doc/changelog/08-vernac-commands-and-options/19361-discharge-export.rst
  doc/sphinx/language/core/modules.rst
  library/lib.ml
  library/lib.mli
  library/libobject.ml
  library/libobject.mli
  test-suite/bugs/bug_19360.v
  vernac/declaremods.ml
  vernac/declaremods.mli
  vernac/synterp.ml
  vernac/vernacentries.ml
Labels: kind: fix, part: modules, part: sections

#19377 Don't ignore unification error in pattern matching compilation
  pretyping/cases.ml
  test-suite/bugs/bug_9756.v
Labels: kind: fix

#19362 API for libobjects with locality + use it to support localities for some commands
  dev/ci/user-overlays/19362-SkySkimmer-obj-with-locality.sh
  doc/changelog/08-vernac-commands-and-options/19362-obj-with-locality.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  library/coqlib.ml
  library/coqlib.mli
  library/libobject.ml
  library/libobject.mli
  library/locality.ml
  library/locality.mli
  plugins/micromega/g_zify.mlg
  plugins/micromega/zify.ml
  plugins/micromega/zify.mli
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  tactics/autorewrite.ml
  tactics/declareScheme.ml
  tactics/declareScheme.mli
  tactics/hints.ml
  tactics/hints.mli
  tactics/ind_tables.ml
  test-suite/success/RegisterScheme.v
  test-suite/success/RewriteRegisteredElim.v
  vernac/attributes.ml
  vernac/attributes.mli
  vernac/declare.ml
  vernac/indschemes.ml
  vernac/vernacentries.ml
Labels: kind: enhancement, kind: internal

#19385 UState don't expose initial_graph
  engine/uState.ml
  engine/uState.mli
Labels: kind: cleanup

#19386 Remove useless UFAIL API in Firstorder.
  plugins/firstorder/unify.ml
  plugins/firstorder/unify.mli
Labels: kind: cleanup

#19376 Add test for #10259
  test-suite/bugs/bug_10259.v
Labels: kind: fix, part: typeclasses, part: test-suite

#19396 Tac2externals: wrap closures to make them pure
  plugins/ltac2/tac2externals.ml
  plugins/ltac2/tac2val.ml
  plugins/ltac2/tac2val.mli
Labels: kind: internal

#19392 Newprofile: profile vm_compile component
  kernel/vmbytegen.ml
Labels: kind: infrastructure

#19372 improve done
  doc/changelog/07-ssreflect/19372-changelog-ssr.rst
  theories/ssr/ssreflect.v
Labels: kind: performance

#19382 [ssr] Remove no longer used not_locked_false_eq_true
  doc/changelog/07-ssreflect/19382-ssr_rm_not_locked_false_eq_true.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  theories/ssr/ssreflect.v
Labels: kind: cleanup, part: ssreflect

#19383 STM classifier: Guarded and Validate Proof are queries not proof steps
  doc/changelog/08-vernac-commands-and-options/19383-classify-guard.rst
  vernac/vernac_classifier.ml
Labels: kind: fix, part: STM

#19091 Use multiple statements to implement interactive fixpoints
  test-suite/output/Fixpoint.out
  test-suite/output/Fixpoint.v
  vernac/comFixpoint.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/himsg.ml
  vernac/himsg.mli
  vernac/vernacentries.ml
Labels: kind: cleanup, part: fixpoints, part: cofixpoints

#19399 done with simple refine
  doc/changelog/07-ssreflect/19399-done_with_simple_refine.rst
  theories/ssr/ssreflect.v
Labels: kind: performance, part: ssreflect

#19405 Fix VM implementation of addmuldiv for large shifts (fix #19402).
  dev/doc/critical-bugs.md
  kernel/byterun/coq_uint63_native.h
  test-suite/primitive/uint63/addmuldiv.v
Labels: kind: fix, part: VM, kind: inconsistency, part: primitive types

#19395 Deprecate resolve_one_typeclass hook between pretyping and class_tactics
  plugins/micromega/coq_micromega.ml
  pretyping/typeclasses.ml
  pretyping/typeclasses.mli
  tactics/class_tactics.ml
  tactics/class_tactics.mli
  tactics/rewrite.ml
Labels: kind: cleanup

#19401 Annotate ocaml deprecations with the coq versions where they were deprecated
  engine/eConstr.mli
  engine/proofview.mli
  engine/termops.mli
  engine/uState.mli
  engine/univSubst.mli
  interp/dumpglob.mli
  interp/stdarg.mli
  kernel/constr.mli
  kernel/context.mli
  kernel/names.mli
  kernel/term.ml
  kernel/term.mli
  kernel/univ.mli
  lib/cErrors.mli
  lib/cWarnings.mli
  lib/util.mli
  library/coqlib.mli
  parsing/pcoq.mli
  plugins/ltac/tacarg.mli
  pretyping/patternops.mli
  pretyping/reductionops.mli
  tactics/hints.mli
  tactics/tacticals.mli
  tactics/tactics.mli
  vernac/library.mli
  vernac/vernacstate.mli
Labels: kind: internal

#19413 Fix destruct eqn with univ poly equality
  tactics/induction.ml
  test-suite/bugs/bug_19411.v
Labels: kind: fix, part: tactics, part: universes

#19266 Fix About info about squashing
  test-suite/output/Inductive.out
  vernac/prettyp.ml
Labels: kind: fix, kind: user messages

#19379 Add debug printer for ppcmds to print as a format call
  dev/top_printers.ml
  dev/top_printers.mli
  lib/pp.ml
  lib/pp.mli
Labels: kind: internal

#19406 Avoid allocating a new term when already whnf in Reductionops.red_of_state_red
  pretyping/reductionops.ml
Labels: kind: performance

#19384 Cleanup UState universe demoting APIs
  dev/ci/user-overlays/19384-SkySkimmer-more-demote.sh
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  engine/univFlex.ml
  pretyping/pretyping.ml
Labels: kind: cleanup

#19398 Rename Evd.evar_universe_context -> ustate
  dev/ml_toplevel/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  engine/evarutil.ml
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/termops.mli
  engine/uState.ml
  engine/uState.mli
  interp/constrintern.mli
  plugins/funind/gen_principle.ml
  plugins/funind/recdef.ml
  plugins/ltac/leminv.ml
  plugins/ssr/ssrbwd.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssrfwd.ml
  plugins/ssrmatching/ssrmatching.ml
  plugins/ssrmatching/ssrmatching.mli
  pretyping/detyping.ml
  pretyping/inductiveops.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  stm/partac.ml
  tactics/elimschemes.ml
  tactics/eqschemes.ml
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  tactics/tactics.ml
  vernac/auto_ind_decl.ml
  vernac/classes.ml
  vernac/comFixpoint.ml
  vernac/comRewriteRule.ml
  vernac/declare.ml
  vernac/vernacentries.ml
Labels: kind: cleanup, kind: internal

#19400 Bench: system to override opam urls
  dev/bench/bench.sh
Labels: kind: infrastructure, kind: enhancement

#19390 Support localities for goptions tables Add/Remove
  dev/ci/user-overlays/19390-SkySkimmer-ref-table-locality.sh
  doc/changelog/08-vernac-commands-and-options/19390-ref-table-locality.rst
  doc/sphinx/language/core/basic.rst
  library/goptions.ml
  library/goptions.mli
  pretyping/coercionops.ml
  pretyping/detyping.ml
  pretyping/detyping.mli
  tactics/equality.ml
  tactics/equality.mli
  test-suite/output/PrintingCoercion.out
  test-suite/output/PrintingCoercion.v
  vernac/vernacentries.ml
  vernac/vernacoptions.ml
  vernac/vernacoptions.mli
Labels: kind: enhancement

#18580 Do not use "simpl never" and cie in "hnf"
  doc/changelog/04-tactics/18580-master+hnf-without-simpl-never.rst
  pretyping/tacred.ml
  test-suite/output/simpl.out
  test-suite/success/intros.v
Labels: kind: fix, part: tactics, part: reduction strategies

#19165 Update browser commands
  ide/coqide/FAQ
  ide/coqide/coqide.ml
  ide/coqide/dune
  ide/coqide/preferences.ml
  ide/coqide/preferences.mli
  tools/configure/configure.ml
Labels: kind: fix, part: CoqIDE

#19419 Faster coherence check when adding coercions.
  pretyping/coercionops.ml
Labels: kind: performance

#19420 Delay kind_to_constr computation in hconstr
  kernel/hConstr.ml
Labels: kind: performance

#19422 Add mathcomp-analysis to the bench.
  dev/bench/bench.sh
Labels: kind: infrastructure

#19427 Remove pointless open/close in coqchk
  checker/check.ml
Labels: kind: cleanup

#19415 Make the bench easier to run locally
  dev/bench/bench.sh
Labels: kind: infrastructure
