Repository rocq-prover/rocq, pull requests merged in 2024-02, with the labels that each got.

#18587 CI: use macos 12 instead of 11
  .github/workflows/ci-macos.yml
Labels: kind: infrastructure

#18606 Fix bug introduced in #18564 (deprecation of stdlib `map_length`)
  theories/Lists/List.v
Labels: kind: fix

#18612 Fix typo in ssreflect-proof-language.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation, part: ssreflect

#18616 Fixes #17897: lost of canonical name of auxiliary constants of mutual fix/cofix at refolding time in "cbn"
  doc/changelog/04-tactics/18616-master+fix17897-cbn-wrong-canonical-name-refolding.rst
  kernel/names.mli
  tactics/cbn.ml
  test-suite/bugs/bug_17897.v
Labels: kind: fix, part: tactics, part: reduction strategies

#18603 Termops.Internal env printing functions take an evar map
  dev/ci/user-overlays/18603-SkySkimmer-temrops-use-evd.sh
  engine/termops.ml
  engine/termops.mli
  plugins/ltac/tactic_debug.ml
  pretyping/evarconv.ml
  proofs/tacmach.ml
Labels: kind: fix

#18584 Nicer elimination error messages for sort poly inductives
  kernel/inductive.mli
  test-suite/output/bug_16219.out
  test-suite/output/sort_poly_elim_error.out
  test-suite/output/sort_poly_elim_error.v
  vernac/himsg.ml
  vernac/himsg.mli
  vernac/record.ml
Labels: kind: user messages

#18596 Fix universe abstraction for const_relevance of opaques
  doc/changelog/01-kernel/18596-abstract-opaque-relevance.rst
  kernel/constant_typing.ml
  test-suite/bugs/bug_18594.v
Labels: kind: fix

#18597 Make log for non-marshalable-state test easier to understand
  test-suite/misc/non-marshalable-state.sh
Labels: kind: infrastructure

#18583 Linter: print errors in red in CI
  dev/lint-commits.sh
  dev/lint-repository.sh
  dev/tools/check-cachekey.sh
  dev/tools/check-eof-newline.sh
  dev/tools/check-overlays.sh
Labels: kind: infrastructure

#18565 Add conf- dependencies for opam
  coq-core.opam
  coq.opam
  dune-project
Labels: kind: infrastructure, part: build

#18608 Have separate jobs for ext_lib, simple_io, itree_io
  .gitlab-ci.yml
Labels: kind: fix, kind: infrastructure

#18599 Stash the bytecode interpreter's internal structures when OCaml's runtime is processing a signal.
  kernel/byterun/coq_interp.c
Labels: kind: fix, part: VM, kind: kernel segfault/exploit

#18560 Ltac2: fix printing of constructor values with arguments
  plugins/ltac2/tac2print.ml
  test-suite/output/bug_16716.out
  test-suite/output/bug_17155.out
  test-suite/output/ltac2_bt.out
  test-suite/output/ltac2_notations_eval_in.out
  test-suite/output/ltac2_pr_ctor.out
  test-suite/output/ltac2_pr_ctor.v
Labels: kind: fix, part: ltac2

#18555 Faster computation of coprime systems in Micromega
  plugins/micromega/certificate.ml
Labels: kind: performance

#18632 chore: Update release-process.md about opam+docker steps
  dev/doc/release-process.md
Labels: kind: documentation, kind: infrastructure

#18537 Fix Search is:Scheme
  doc/changelog/08-vernac-commands-and-options/18537-fix-search-scheme.rst
  tactics/declareScheme.ml
  tactics/declareScheme.mli
  test-suite/output/SearchScheme.out
  test-suite/output/SearchScheme.v
  vernac/comSearch.ml
Labels: kind: fix

#18624 Ltac2: split value APIs from Tac2ffi to new Tac2val
  dev/ci/user-overlays/18624-SkySkimmer-split-tac2ffi.sh
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2core.mli
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2externals.ml
  plugins/ltac2/tac2externals.mli
  plugins/ltac2/tac2extffi.ml
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2interp.ml
  plugins/ltac2/tac2interp.mli
  plugins/ltac2/tac2print.ml
  plugins/ltac2/tac2print.mli
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2val.ml
  plugins/ltac2/tac2val.mli
  plugins/ltac2_ltac1/tac2core_ltac1.ml
  plugins/ltac2_ltac1/tac2stdlib_ltac1.ml
Labels: kind: cleanup

#18576 Using same refolding strategy for named cofixpoints in tactic "simpl" as is done for named fixpoints
  doc/changelog/04-tactics/18576-master+fix4056-refolding-simpl-cofix.rst
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/tacred.ml
  test-suite/success/simpl.v
Labels: part: tactics, kind: enhancement, part: reduction strategies

#18630 coqchk: check const_relevance
  checker/checker.ml
  checker/mod_checking.ml
  checker/mod_checking.mli
  dev/doc/critical-bugs.md
Labels: kind: fix, part: checker, kind: inconsistency

#18604 Add Ltac2.Control.unshelve0 and Ltac2.Notations.unshelve
  doc/changelog/06-Ltac2-language/18604-ltac2-unshelve.rst
  plugins/ltac2/tac2core.ml
  test-suite/success/unshelve.v
  user-contrib/Ltac2/Control.v
  user-contrib/Ltac2/Notations.v
Labels: kind: enhancement, part: ltac2

#18620 Fast name generation in evar naming algorithm
  engine/evarutil.ml
  engine/evd.ml
  engine/evd.mli
  engine/nameops.ml
  engine/nameops.mli
Labels: kind: performance

#18458 Make `Cumulativity Weak Constraints` work with `Set` (when minim to set active)
  doc/changelog/08-vernac-commands-and-options/18458-weak-constraints-set.rst
  engine/univMinim.ml
  test-suite/bugs/bug_18455.v
Labels: kind: fix

#18348 ci-wrapper: grep for errors at the end
  dev/ci/ci-wrapper.sh
Labels: kind: feature, kind: infrastructure, part: CI

#18586 Remove deprecation of Qed Let in doc after #17576
  doc/sphinx/language/core/sections.rst
Labels: kind: documentation

#18645 windows CI: Fix path after platform update
  dev/ci/platform/coq-pf-04-installer.bat
Labels: kind: fix, kind: infrastructure, platform: Windows

#18627 Deactivation of notations grants verbose mode
  test-suite/output/Notations5.out
  test-suite/output/activation.out
  test-suite/output/onlyprinting.out
  vernac/metasyntax.ml
Labels: kind: user messages, part: notations

#18633 Reduce use of canonical name data in upper layers
  interp/reserve.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/names.ml
  kernel/names.mli
  library/coqlib.ml
  plugins/btauto/refl_btauto.ml
  plugins/cc/ccalgo.ml
  plugins/cc/ccalgo.mli
  plugins/cc/cctac.ml
  plugins/firstorder/formula.ml
  plugins/firstorder/formula.mli
  plugins/firstorder/ground.ml
  plugins/firstorder/instances.ml
  plugins/firstorder/instances.mli
  plugins/firstorder/sequent.ml
  plugins/firstorder/sequent.mli
  plugins/ltac/internals.ml
  plugins/ring/ring.ml
  pretyping/evarconv.ml
  pretyping/indrec.ml
  pretyping/keys.ml
  pretyping/keys.mli
  pretyping/patternops.ml
  pretyping/patternops.mli
  pretyping/tacred.ml
  pretyping/unification.ml
  tactics/autorewrite.ml
  tactics/btermdn.ml
  tactics/cbn.ml
  tactics/tacticals.ml
  vernac/auto_ind_decl.ml
  vernac/comSearch.ml
  vernac/prettyp.ml
  vernac/recLemmas.ml
Labels: kind: cleanup

#18432 Ltac2 typed notations
  doc/changelog/06-Ltac2-language/18432-ltac2-typed-notation.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/stdlib/index-list.html.template
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2intern.mli
  plugins/ltac2/tac2print.ml
  plugins/ltac2/tac2quote.ml
  sysinit/coqargs.ml
  test-suite/output/ltac2_check_globalize.out
  test-suite/output/ltac2_check_globalize.v
  test-suite/output/ltac2_typed_notations.out
  test-suite/output/ltac2_typed_notations.v
  user-contrib/Ltac2/Compat/Coq818.v
  user-contrib/Ltac2/Compat/Coq819.v
Labels: kind: feature, part: ltac2

#18649 Ltac2: fix type of FMap.fold
  user-contrib/Ltac2/FMap.v
Labels: kind: fix, part: ltac2

#18653 Primitive int and float notations: use Register instead of hardcoded paths
  plugins/syntax/number.ml
  theories/Floats/PrimFloat.v
  theories/Numbers/Cyclic/Int63/PrimInt63.v
Labels: kind: cleanup, part: primitive types

#18601 Fix refolding of named mutual fix/cofix defined in a section for "cbn"
  doc/changelog/04-tactics/18601-master+fix17897-cbn-wrong-canonical-name-refolding.rst
  tactics/cbn.ml
  test-suite/success/cbn.v
Labels: kind: fix, part: tactics, part: reduction strategies

#18667 Remove notation-related API
  interp/notation.ml
  interp/notation.mli
  interp/notationextern.ml
  interp/notationextern.mli
Labels: kind: cleanup, part: notations

#18662 Fix #18657: "Include" objects were not always taken into account in Search
  doc/changelog/08-vernac-commands-and-options/18662-master+small-cleanup-declare_variable.rst
  test-suite/output/bug_18657.out
  test-suite/output/bug_18657.v
  vernac/declaremods.ml
Labels: kind: fix, part: modules, part: search

#18668 Deprecate NDefOps and NIso
  doc/changelog/11-standard-library/18500-deprecations_in_Numbers.rst
  doc/changelog/11-standard-library/18501-more_NatInt_doc.rst
  doc/changelog/11-standard-library/18538-deprecate_Bool_nat.rst
  doc/changelog/11-standard-library/18539-deprecate_NZDomain.rst
  doc/changelog/11-standard-library/18544-deprecate_Zeuclid.rst
  doc/changelog/11-standard-library/18564-rename-push-length.rst
  doc/changelog/11-standard-library/18668-depr_NDefOps_NIso.rst
  doc/stdlib/hidden-files
  doc/stdlib/index-list.html.template
  theories/Numbers/Natural/Abstract/NDefOps.v
  theories/Numbers/Natural/Abstract/NIso.v
Labels: kind: cleanup, part: standard library

#18675 Fix `unfold` tactic not unfolding compatibility constants.
  pretyping/tacred.ml
  test-suite/success/primitiveproj.v
Labels: kind: fix

#18236 Coercion hook for funclass and sortclass
  dev/ci/user-overlays/18236-Tragicus-coercion-hook.sh
  pretyping/coercion.ml
  pretyping/coercion.mli
Labels: kind: enhancement, part: coercions

#18681 Remove all uses of the functional induction tactic from the stdlib.
  theories/FSets/FMapAVL.v
  theories/FSets/FMapFullAVL.v
  theories/MSets/MSetAVL.v
Labels: kind: cleanup

#18686 Attempt to clarify the meaning of decidable in Coq
  theories/Logic/Decidable.v
Labels: kind: documentation, part: standard library

#18172 [stdlib] several NoDup lemmas
  doc/changelog/11-standard-library/18172-NoDup_lemmas.rst
  theories/Lists/List.v
Labels: kind: feature, part: standard library

#18661 Functionalize and clean up the Find_subterm implementation
  pretyping/find_subterm.ml
  pretyping/find_subterm.mli
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  pretyping/unification.ml
  vernac/himsg.ml
Labels: kind: cleanup

#18652 Reduce reliance on global enviromnents in Prettyp.
  dev/ci/user-overlays/18652-ppedrot-prettyp-explicit-env.sh
  plugins/ltac/tacentries.ml
  plugins/ltac2/tac2entries.ml
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#18639 Fast path for equality function used in the progress tactical.
  engine/proofview.ml
Labels: kind: performance

#18674 Inline projection reduction in knht.
  kernel/cClosure.ml
Labels: kind: cleanup

#18685 [ci] [docker] Bump edge Dune version
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
Labels: kind: infrastructure, kind: internal, part: CI

#18644 Properly generalize the type of symbols from Grammar.generalize_symbol.
  gramlib/grammar.ml
  gramlib/grammar.mli
Labels: kind: internal

#18665 Remove constant argument from the AbstractPattern constructor.
  pretyping/unification.ml
  pretyping/unification.mli
  tactics/induction.ml
  tactics/tactics.ml
Labels: kind: cleanup

#18664 Simplify the API around hint paths
  dev/ci/user-overlays/18664-ppedrot-cleanup-hint-path-derivate.sh
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  plugins/ltac/g_auto.mlg
  plugins/ltac/g_auto.mli
  tactics/class_tactics.ml
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#18640 Revert "Stop doing early universe minimization and nf_evar in abstract"
  doc/changelog/04-tactics/18640-fix-double-abstract.rst
  test-suite/bugs/bug_18636.v
  vernac/declare.ml
Labels: kind: fix, part: universes

#18691 Correctly pass coqchk path in dune wrapper.
  checker/dune
  dev/dune-dbg.in
Labels: kind: infrastructure

#18577 Fixes #7982: add support for reduction of primitive projection of cofixpoints in "simpl" reduction strategy
  doc/changelog/04-tactics/18577-master+fix7982-primproj-cofix-simpl.rst
  pretyping/tacred.ml
  test-suite/bugs/bug_7982.v
Labels: kind: fix, part: tactics, part: primitive records, part: reduction strategies, part: coinductives

#18663 Use Coqlib primitives to check for reference equality in extraction.
  library/coqlib.ml
  library/coqlib.mli
  plugins/extraction/common.ml
  plugins/extraction/common.mli
  plugins/extraction/haskell.ml
  plugins/extraction/ocaml.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  tactics/hipattern.ml
Labels: kind: cleanup

#18694 Use Loc.raise instead of raise in Require for missing libraries
  test-suite/output/bug_15097.out
  vernac/synterp.ml
Labels: kind: internal, part: vernac

#18559 Add Ltac2.Ltac1.tag_name (useful for debug and error messages)
  doc/changelog/06-Ltac2-language/18559-ltac2-ltac1-tag-name.rst
  plugins/ltac2_ltac1/tac2core_ltac1.ml
  user-contrib/Ltac2/Ltac1.v
Labels: kind: enhancement, part: ltac2

#18699 Add Ltac2.Ltac1.to/of_int
  plugins/ltac2_ltac1/tac2core_ltac1.ml
  test-suite/ltac2/ltac1_conversions.v
  user-contrib/Ltac2/Ltac1.v
Labels: kind: enhancement, part: ltac2

#17321 Fix #16288: wrongly self-referencing extraction of primitive projections in functors
  doc/changelog/13-misc/17321-master+fix16288-extraction-prim-field-functor.rst
  plugins/extraction/extraction.ml
  test-suite/bugs/bug_16288.v
  test-suite/output/extraction_projection.out
Labels: kind: fix, part: extraction

#18651 Fix doc about Extraction AutoInline
  doc/sphinx/addendum/extraction.rst
Labels: kind: documentation

#18523 CoqIDE: Improve find/replace UI (margins, icons)
  doc/changelog/10-coqide/18523-coqide.rst
  ide/coqide/wg_Find.ml
Labels: part: CoqIDE, kind: usability

#18524 CoqIDE: A few fixes in file management
  doc/changelog/10-coqide/18524-coqide.rst
  ide/coqide/coqide.ml
  ide/coqide/fileOps.ml
  ide/coqide/fileOps.mli
  ide/coqide/preferences.ml
  ide/coqide/preferences.mli
Labels: kind: fix, part: CoqIDE

#18720 typo in the doc of ssreflect rewrite multirule
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
Labels: kind: documentation

#18710 coqchk --help should exit with 0 not 1.
  checker/checker.ml
Labels: kind: fix

#18579 Documenting actual behavior of simpl, cbn, and hnf wrt primitive projections and "simpl never"
  test-suite/output/simpl.out
  test-suite/output/simpl.v
Labels: kind: documentation, part: tactics, part: test-suite, part: reduction strategies

#18695 Loc for magic version and number check
  lib/system.ml
  lib/system.mli
  vernac/library.ml
  vernac/library.mli
  vernac/synterp.ml
Labels: kind: internal, part: vernac

#18708 Very rough cleanup of the CClosure pattern implementation
  kernel/cClosure.ml
Labels: kind: cleanup

#18688 Use more tail-recursion in lia to avoid stack overflows.
  plugins/micromega/coq_micromega.ml
Labels: kind: fix

#18648 Add autosubst-ocaml to CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-autosubst_ocaml.sh
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#18696 Update changelog for 8.19.1
  doc/changelog/01-kernel/18596-abstract-opaque-relevance.rst
  doc/changelog/04-tactics/18640-fix-double-abstract.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#18723 Fix changelog category for #17321
  doc/changelog/14-misc/17321-master+fix16288-extraction-prim-field-functor.rst
Labels: kind: fix, kind: documentation

#18679 add Trakt to Coq's CI
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/ci-trakt.sh
Labels: kind: infrastructure

#18719 Reduce dependencies on ltac_plugin + stricter type for vernac_argument extend
  dev/ci/user-overlays/18719-SkySkimmer-less-ltac-plugin.sh
  plugins/derive/dune
  plugins/extraction/dune
  plugins/extraction/g_extraction.mlg
  plugins/extraction/g_extraction.mli
  plugins/funind/dune
  plugins/funind/g_indfun.mli
  plugins/funind/indfun.mli
  plugins/ltac/g_auto.mli
  plugins/ltac/g_ltac.mli
  plugins/ltac2/g_ltac2.mli
  plugins/ring/g_ring.mli
  plugins/syntax/g_number_string.mli
  pretyping/genarg.ml
  pretyping/genarg.mli
  vernac/vernacextend.mli
Labels: kind: cleanup, part: funind, part: extraction, part: ltac, part: ltac2, part: derive

#18716 Always set `Sys.catch_break true`, not just when interactive
  checker/checker.ml
  doc/changelog/09-cli-tools/18716-catch-break.rst
  sysinit/coqinit.ml
  toplevel/coqloop.ml
Labels: kind: internal, part: ocaml, part: toplevel

#18670 Make "Found no matching notation to enable or disable." a warning
  doc/sphinx/user-extensions/syntax-extensions.rst
  interp/notation.ml
  test-suite/output/activation.out
  test-suite/output/activation.v
Labels: kind: fix, part: notations

#18726 [CI] Exclude new ModelCategories from UniMath
  dev/ci/ci-unimath.sh
Labels: kind: infrastructure, part: CI

#18734 Changelog for #18670
  doc/sphinx/changes.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#18731 zify: saturate before translating division to equations
  theories/micromega/Zify.v
Labels: kind: enhancement, part: micromega
