Repository rocq-prover/rocq, pull requests merged in 2024-04, with the labels that each got.

#18299 New command Register Scheme
  doc/changelog/08-vernac-commands-and-options/18299-regscheme.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  tactics/declareScheme.ml
  tactics/declareScheme.mli
  tactics/elimschemes.ml
  tactics/elimschemes.mli
  tactics/eqschemes.ml
  tactics/equality.ml
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  tactics/rewrite.ml
  vernac/auto_ind_decl.ml
  vernac/declare.ml
  vernac/g_vernac.mlg
  vernac/indschemes.ml
  vernac/ppvernac.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.mli
Labels: kind: feature

#18713 Ltac2: importing a mutable definition does not undo its mutations
  doc/changelog/06-Ltac2-language/18713-ltac2-original-redef-no-import.rst
  doc/sphinx/proof-engine/ltac2.rst
  plugins/ltac2/tac2entries.ml
  test-suite/ltac2/rebind.v
Labels: kind: fix, part: ltac2

#18868 Move from deprecated find_reference to lib_ref in the plugin tutorial
  doc/plugin_tutorial/tuto3/src/construction_game.ml
  doc/plugin_tutorial/tuto3/theories/Data.v
Labels: kind: cleanup

#18873 Fixes #3889: anomaly instead of error when no more obligation of some name are pending
  test-suite/bugs/bug_3889.v
  vernac/declare.ml
Labels: kind: fix, kind: user messages, part: program

#18834 Use implicit status of further arguments in measure/wf-like Program Fixpoint
  doc/changelog/02-specification-language/18834-master+use-extra-impargs-program-fixpoint-wf.rst
  interp/constrintern.ml
  interp/constrintern.mli
  test-suite/success/ProgramWf.v
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
Labels: kind: fix, part: program, part: implicit arguments, part: fixpoints

#18886 Add a votour command to handle the current node as if it were a list.
  checker/votour.ml
Labels: kind: infrastructure

#18546 Move [Names.Evaluable] to pretyping + copy in the kernel.
  dev/ci/user-overlays/18546-rlepigre-brevaluable_refactoring.sh
  kernel/conv_oracle.ml
  kernel/conv_oracle.mli
  kernel/conversion.ml
  kernel/names.ml
  kernel/names.mli
  kernel/safe_typing.mli
  library/global.mli
  plugins/ltac/pptactic.mli
  pretyping/evaluable.ml
  pretyping/evaluable.mli
  pretyping/reductionops.ml
  pretyping/unification.ml
  tactics/genredexpr.mli
  tactics/redexpr.ml
  tactics/redexpr.mli
  tactics/tactics.ml
  vernac/prettyp.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#18883 Mark arrays, products, and plain constants, as potentially needing a delayed evaluation during native_compute (fix #18703).
  kernel/nativecode.ml
  kernel/nativecode.mli
Labels: kind: fix, part: native compiler

#18843 Fixes sigma out of scope in wf-measure-based Program Fixpoint's hook
  vernac/comProgramFixpoint.ml
Labels: kind: cleanup, part: program, part: fixpoints

#18885 More efficient implementation of UState.demote_global_univs.
  engine/uState.ml
Labels: kind: performance

#18836 [build] Fix dune pure build
  user-contrib/Ltac2/dune.disabled
Labels: part: build, kind: internal

#18800 Allow matching on quality instances
  checker/mod_checking.ml
  checker/values.ml
  kernel/cClosure.ml
  kernel/declarations.mli
  kernel/sorts.ml
  kernel/sorts.mli
  kernel/uVars.ml
  kernel/uVars.mli
  pretyping/cbv.ml
  pretyping/reductionops.ml
  tactics/cbn.ml
  test-suite/success/rewrule_quality_match.v
  vernac/comRewriteRule.ml
Labels: kind: enhancement

#18821 Create new record_comments flag and fix comment lexing
  lib/flags.ml
  lib/flags.mli
  lib/pp.ml
  parsing/cLexer.ml
  sysinit/coqargs.ml
  test-suite/misc/comment-lexing.sh
  test-suite/misc/comment-lexing/.gitignore
  test-suite/misc/comment-lexing/test.out
  test-suite/misc/comment-lexing/test.v
  test-suite/misc/comment-lexing/test.v.beautified
  toplevel/vernac.ml
  vernac/ppvernac.ml
Labels: kind: fix, kind: internal

#18864 Call guard checking with evar handlers in higher layers
  dev/ci/user-overlays/18864-SkySkimmer-check-guard-evars.sh
  engine/evd.mli
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/conversion.ml
  kernel/conversion.mli
  kernel/genlambda.ml
  kernel/genlambda.mli
  kernel/inductive.ml
  kernel/inductive.mli
  kernel/reduction.ml
  kernel/reduction.mli
  kernel/typeops.mli
  pretyping/inductiveops.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  pretyping/typing.ml
  test-suite/bugs/bug_18358.v
  test-suite/bugs/bug_18680.v
  test-suite/bugs/bug_18850.v
  vernac/comProgramFixpoint.ml
Labels: kind: fix

#18862 Regular error for unknown state in BackTo
  stm/stm.ml
  test-suite/output-coqtop/backto.out
  test-suite/output-coqtop/backto.v
Labels: kind: fix

#18887 Remove the deprecated clear modifier.
  doc/changelog/04-tactics/18887-rm-deprecated-clear-modifier.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  plugins/ltac/g_tactic.mlg
Labels: kind: cleanup

#18901 Use type Opaqueproof.opaque_proofterm where appropriate
  checker/mod_checking.ml
  checker/mod_checking.mli
  library/global.ml
  library/global.mli
Labels: kind: cleanup

#18897 Nicer break hints for "no subterm matching ..." error message
  vernac/himsg.ml
Labels: kind: user messages

#18902 Test suite print correct log file when coqchk fails
  test-suite/Makefile
Labels: kind: fix, part: test-suite, part: build

#18422 Push Library.indirect_accessor references up in the call stack
  coqpp/coqpp_main.ml
  dev/ci/user-overlays/18422-SkySkimmer-indirect.sh
  doc/plugin_tutorial/tuto1/src/g_tuto1.mlg
  doc/plugin_tutorial/tuto1/src/simple_print.ml
  doc/plugin_tutorial/tuto1/src/simple_print.mli
  library/global.ml
  plugins/extraction/extract_env.ml
  plugins/extraction/extract_env.mli
  plugins/extraction/extraction.ml
  plugins/extraction/extraction.mli
  plugins/extraction/g_extraction.mlg
  stm/stm.ml
  toplevel/coqc.ml
  vernac/assumptions.ml
  vernac/assumptions.mli
  vernac/library.mli
  vernac/prettyp.ml
  vernac/prettyp.mli
  vernac/vernacentries.ml
  vernac/vernacinterp.ml
  vernac/vernactypes.ml
  vernac/vernactypes.mli
Labels: kind: cleanup, part: extraction, kind: internal, part: vernac

#18905 Remove UVars.AInstance
  dev/include_printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  engine/eConstr.ml
  engine/eConstr.mli
  kernel/cClosure.ml
  kernel/sorts.ml
  kernel/sorts.mli
  kernel/uVars.ml
  kernel/uVars.mli
  kernel/vars.ml
  kernel/vars.mli
  pretyping/cbv.ml
  pretyping/reductionops.ml
  tactics/cbn.ml
  vernac/comRewriteRule.ml
Labels: kind: cleanup

#17209 Moving general-purpose rapply from Programs to Init
  doc/sphinx/proof-engine/tactics.rst
  theories/Init/Tactics.v
  theories/Program/Tactics.v
Labels: kind: cleanup, part: tactics

#18563 add 8 "push" lemmas for `nth_error`
  doc/changelog/11-standard-library/18563-more-nth_error.rst
  theories/Lists/List.v
Labels: part: standard library, kind: enhancement

#18922 Fix printing of out-of-scope rels in rel_context debugging printer
  interp/constrextern.ml
Labels: kind: infrastructure, part: printer

#18893 [lexer] Fix handling of stream current location in error case.
  lib/cErrors.ml
  lib/cErrors.mli
  parsing/cLexer.ml
  test-suite/unit-tests/parsing/lexer_recovery.ml
Labels: kind: fix, kind: bug, part: parser

#18837 [ssr] Backports from mathcomp following merge of https://github.com/math-comp/math-comp/pull/1193
  theories/ssr/ssrbool.v
Labels: part: ssreflect, kind: enhancement

#18921 Fixes #11030, #11586: pattern-matching bugs in program mode or when using the program-style return predicate
  dev/ci/user-overlays/18921-herbelin-master+fix11030-bugs-program-pattern-matching.sh
  doc/changelog/02-specification-language/18921-master+fix11030-bugs-program-pattern-matching.rst
  pretyping/cases.ml
  test-suite/bugs/bug_11030.v
Labels: kind: fix, part: program, part: pattern-matching compilation

#18930 Fix the link and picture for the CI from the README portal.
  README.md
Labels: kind: fix, kind: infrastructure

#18924 Make some VM allocations more robust
  kernel/byterun/coq_interp.c
Labels: part: VM, kind: bug

#18390 [ci] Test native Dune build
  .gitlab-ci.yml
  dune-project
Labels: kind: infrastructure, part: build, part: CI

#18876 Checking freshness of definition name at the time of initial declaration
  test-suite/output/UnivBinders.out
  test-suite/output/UnivBinders.v
  test-suite/success/freshness.v
  vernac/vernacentries.ml
Labels: kind: cleanup

#18894 Fix a broken hint declaration in a test from the test-suite.
  test-suite/success/bteauto.v
Labels: kind: fix, part: test-suite

#18899 Remove essentially unused wrappers from Auto
  plugins/firstorder/g_ground.mlg
  plugins/funind/recdef.ml
  plugins/ltac/g_auto.mlg
  plugins/ltac2/tac2tactics.ml
  plugins/ssr/ssrtacs.mlg
  tactics/auto.ml
  tactics/auto.mli
  tactics/eauto.ml
  tactics/eqdecide.ml
Labels: kind: cleanup

#18911 Do not expose API relying on kernel instance substitution in EConstr.
  dev/ci/user-overlays/18911-ppedrot-econstr-einstance-api.sh
  engine/eConstr.ml
  engine/eConstr.mli
  pretyping/evarconv.ml
  pretyping/structures.ml
Labels: kind: cleanup

#18925 Pass the number of binders crossed in Find_subterm matching function.
  pretyping/find_subterm.ml
  pretyping/find_subterm.mli
  pretyping/unification.ml
Labels: kind: performance

#18932 Fix einstance use in rewrite rules
  pretyping/reductionops.ml
  tactics/cbn.ml
Labels: kind: internal

#18888 Use gitlab.inria.fr shared runners for docker boot
  .gitlab-ci.yml
  dev/ci/gitlab-modes/tagged-runners.yml
  dev/ci/gitlab-modes/untagged-runners.yml
Labels: kind: infrastructure, kind: internal, part: CI

#18771 Improve handling of Drop
  .gitignore
  .gitlab-ci.yml
  Makefile
  config/coq_byte_config.mli
  config/dune
  dev/base_include
  dev/ci/user-overlays/18771-afdw-drop.sh
  dev/db
  dev/debugger_support.ml
  dev/debugger_support.mli
  dev/doc/build-system.dune.md
  dev/doc/debugging.md
  dev/dune
  dev/dune-dbg.in
  dev/inc_ltac_dune
  dev/include
  dev/include_printers
  dev/ml_toplevel/include
  dev/ml_toplevel/include_directories
  dev/ml_toplevel/include_printers
  dev/ml_toplevel/include_utilities
  dev/shim/dune
  dev/top_printers.ml
  dev/top_printers.mli
  dev/vm_printers.ml
  dev/vm_printers.mli
  doc/changelog/12-infrastructure-and-dependencies/18771-drop.rst
  doc/sphinx/practical-tools/coq-commands.rst
  engine/termops.ml
  lib/flags.ml
  lib/flags.mli
  man/coqtop.opt.1
  man/dune
  pretyping/detyping.ml
  printing/printer.ml
  test-suite/dune
  test-suite/misc/printers.sh
  tools/configure/configure.ml
  topbin/coqc_byte_bin.ml
  topbin/coqc_byte_bin.mli
  topbin/coqtop_byte_bin.ml
  topbin/dune
  toplevel/coqloop.ml
  toplevel/coqloop.mli
  toplevel/coqtop.ml
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: enhancement

#18935 Full EConstr-based API for Inductiveops.
  dev/ci/user-overlays/18935-ppedrot-econstr-inductiveops-api.sh
  engine/eConstr.ml
  engine/eConstr.mli
  plugins/extraction/extraction.ml
  plugins/firstorder/formula.ml
  plugins/funind/gen_principle.ml
  plugins/funind/glob_term_to_relation.ml
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  pretyping/cases.ml
  pretyping/coercionops.ml
  pretyping/combinators.ml
  pretyping/indrec.ml
  pretyping/indrec.mli
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/nativenorm.ml
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  pretyping/pretyping.ml
  pretyping/retyping.ml
  pretyping/typing.ml
  pretyping/typing.mli
  proofs/clenv.ml
  tactics/elimschemes.ml
  tactics/eqschemes.ml
  tactics/equality.ml
  tactics/inv.ml
  tactics/tactics.ml
  vernac/auto_ind_decl.ml
  vernac/indschemes.ml
  vernac/search.ml
Labels: kind: cleanup

#18926 Fixes coq-elpi#618: remove synterp code from add_instance_base
  vernac/classes.ml
Labels: kind: cleanup

#18934 Fast path in Unification.make_abstraction_core.
  pretyping/unification.ml
Labels: kind: performance

#18729 zify Nat.double and Nat.div2
  doc/changelog/04-tactics/18729-zify-nat-double-halve.rst
  test-suite/micromega/zify.v
  theories/Reals/Exp_prop.v
  theories/ZArith/Znat.v
  theories/micromega/ZifyInst.v
Labels: kind: enhancement, part: micromega

#18928 Indent body and type when printing local definitions over several lines
  printing/printer.ml
  test-suite/output/Cases.out
  test-suite/output/DebugRelevances.out
  test-suite/output/Naming.out
  test-suite/output/Notations.out
  test-suite/output/Notations4.out
  test-suite/output/PrintAssumptions.out
Labels: kind: enhancement, part: printer

#18918 Fixes #13979: share universe instance in measure-based Program Fixpoint auxiliary constant
  test-suite/bugs/bug_13979.v
  vernac/comProgramFixpoint.ml
Labels: kind: fix, part: program, part: universes, part: fixpoints

#18859 A few more list, context and term combinators
  clib/cList.ml
  clib/cList.mli
  engine/eConstr.mli
  engine/evarutil.ml
  engine/evd.ml
  engine/evd.mli
  engine/univSubst.ml
  engine/univSubst.mli
  kernel/context.ml
  kernel/context.mli
  kernel/term.ml
  kernel/term.mli
  vernac/comProgramFixpoint.ml
  vernac/declare.ml
  vernac/record.ml
Labels: kind: cleanup

#18874 Ignore universes of inlined side effects in build_by_tactic
  test-suite/bugs/bug_13271.v
  vernac/declare.ml
Labels: kind: fix, part: program, part: universes

#18867 Don't make Prop inductives template to control eliminator generation
  dev/ci/user-overlays/18867-SkySkimmer-non-prop-template.sh
  doc/changelog/08-vernac-commands-and-options/18867-non-prop-template.rst
  engine/eConstr.ml
  kernel/inductive.ml
  kernel/inductive.mli
  kernel/term.ml
  pretyping/indrec.ml
  pretyping/indrec.mli
  pretyping/inductiveops.ml
  tactics/eqschemes.ml
  test-suite/output/PrimitiveProjectionsAttribute_Records.out
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/indschemes.ml
  vernac/prettyp.ml
  vernac/record.ml
  vernac/record.mli
Labels: kind: cleanup, part: universes

#18949 Remove unsafe_typ argument of Declare.prepare_proof
  vernac/declare.ml
Labels: kind: cleanup

#18910 Set some basic rewriting primitives in Type opaque for TC search.
  doc/changelog/11-standard-library/18910-setoid-type-core-tc-opaque.rst
  test-suite/bugs/bug_7675_3.v
  theories/Classes/CRelationClasses.v
Labels: kind: fix, part: rewriting tactics

#18936 remove NArith.Ndigits, NArith.Ndist, and Strings.ByteVector
  doc/changelog/11-standard-library/18936-remove-ByteVector-Ndist-Ndigits.rst
  doc/stdlib/index-list.html.template
  test-suite/bugs/bug_17466_3.v
  theories/NArith/NArith.v
  theories/NArith/Ndec.v
  theories/NArith/Ndigits.v
  theories/NArith/Ndist.v
  theories/Strings/ByteVector.v
Labels: kind: cleanup, part: standard library

#18952 Cleanup some STM related APIs in declare.ml
  stm/stm.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/vernacinterp.ml
  vernac/vernacstate.ml
  vernac/vernacstate.mli
Labels: kind: cleanup

#18764 Add some Ltac2.Constr.Unsafe combinators
  doc/changelog/06-Ltac2-language/18764-ltac2-combinators.rst
  plugins/ltac2/tac2core.ml
  user-contrib/Ltac2/Constr.v
Labels: kind: feature, part: ltac2

#18957 Properly flush -time-file at exit
  toplevel/vernac.ml
Labels: kind: fix, part: build, part: vernac, part: ocaml, part: toplevel

#18987 Remove outdated FIXME comment
  vernac/comProgramFixpoint.ml
Labels: kind: cleanup

#18958 Fixes #18920: anomaly with evars turned into obligations in binders of Program Fixpoint measure/wf
  doc/changelog/02-specification-language/18958-master+fix18920-evars-leak-program-fixpoint.rst
  test-suite/bugs/bug_18920.v
  vernac/comProgramFixpoint.ml
Labels: kind: fix, part: program, part: fixpoints

#18975 Test suite: Speed up summary.log generation
  test-suite/Makefile
Labels: kind: infrastructure, part: test-suite

#18969 Revert "Add attribute [@@immediate64] to Uint63.t"
  kernel/uint63.mli
Labels: kind: fix

#18968 Use callback to substitute universe instances in VM
  checker/values.ml
  kernel/byterun/coq_interp.c
  kernel/genOpcodeFiles.ml
  kernel/vmbytecodes.ml
  kernel/vmbytecodes.mli
  kernel/vmbytegen.ml
  kernel/vmemitcodes.ml
  kernel/vmvalues.ml
  kernel/vmvalues.mli
Labels: kind: performance, part: VM, part: universes
