Repository rocq-prover/rocq, pull requests merged in 2024-11, with the labels that each got.

#19794 Reduce the dependency on metas in several parts of the code
  plugins/ltac/taccoerce.ml
  pretyping/tacred.ml
  pretyping/typing.ml
  pretyping/unification.ml
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/auto.ml
  tactics/cbn.ml
  tactics/equality.ml
  tactics/tactics.ml
  test-suite/bugs/bug_19794.v
Labels: kind: cleanup

#19768 Fixes #19767: anomaly when printing functor with Strategy/Transparent in module parameter
  doc/changelog/08-vernac-commands-and-options/19768-master+fixes19767-anomaly-print-functor-strategy.rst
  tactics/redexpr.ml
  test-suite/bugs/bug_19767.v
Labels: kind: fix, part: modules, part: printer, part: reduction strategies

#19716 Refine description of "About" and mention transparency.
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  vernac/prettyp.ml
Labels: kind: documentation

#19804 8.20 backports
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: needs: full CI

#19809 Reduce most artifacts expire_in to 1 week
  .gitlab-ci.yml
Labels: kind: infrastructure

#19817 Remove `dfs eauto`, deprecated in 8.16
  doc/changelog/04-tactics/19817-remove_dfs_eauto.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_auto.mlg
Labels: kind: cleanup

#19784 Keep cache of (constant / inductive) -> needed section variables in environ
  kernel/environ.ml
  kernel/environ.mli
Labels: kind: performance

#19815 coqdep and dune_rule_gen fixes before removal of legacy loading
  tools/coqdep/lib/fl.ml
  tools/dune_rule_gen/coq_rules.ml
  tools/dune_rule_gen/path.ml
Labels: kind: fix

#19807 Apparently missing “if” in plugins/extraction/scheme.ml
  plugins/extraction/scheme.ml
  test-suite/output/bug_19806.out
  test-suite/output/bug_19806.v
Labels: kind: fix

#19802 Doc: Add an explicit example where let x := u in v is well-typed while (fun x => v) u is not
  doc/sphinx/language/cic.rst
Labels: kind: documentation

#19825 8.20 backports
  .github/workflows/ci-windows.yml
Labels: needs: full CI

#19803 Remove the meta state from evarmaps
  dev/ci/user-overlays/19803-ppedrot-split-meta-state.sh
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/termops.mli
  plugins/cc/cctac.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/evarconv.ml
  pretyping/evarconv.mli
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  pretyping/reductionops.ml
  pretyping/reductionops.mli
  pretyping/retyping.ml
  pretyping/retyping.mli
  pretyping/structures.ml
  pretyping/structures.mli
  pretyping/typing.ml
  pretyping/typing.mli
  pretyping/unification.ml
  pretyping/unification.mli
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/equality.ml
  tactics/induction.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  test-suite/bugs/bug_19803.v
Labels: kind: cleanup

#19830 CI: add elpi as dependency for CoRN
  .gitlab-ci.yml
  Makefile.ci
Labels: kind: infrastructure, part: CI

#19827 Declare ML Module allow plugin names not containing `.`
  doc/sphinx/proof-engine/vernacular-commands.rst
  vernac/mltop.ml
  vernac/synterp.ml
Labels: kind: fix, part: build, part: coqdep

#19836 MacOS CI: install pkgconf instead of pkg-config
  .github/workflows/ci-macos.yml
Labels: kind: infrastructure

#19834 Stop implicitly adding the current directory to ML paths
  dev/ci/user-overlays/19834-SkySkimmer-no-ml-cwd.sh
  doc/changelog/14-misc/19834-no-ml-cwd.rst
  sysinit/coqinit.ml
  sysinit/coqloadpath.ml
  vernac/loadpath.ml
  vernac/loadpath.mli
Labels: kind: cleanup, part: build, part: vernac

#19832 Reduce the exposed attack surface of meta states
  dev/top_printers.ml
  dev/top_printers.mli
  engine/evd.ml
  engine/evd.mli
  engine/termops.ml
  engine/termops.mli
  plugins/ssrmatching/ssrmatching.ml
  pretyping/evarconv.ml
  pretyping/evarconv.mli
  pretyping/unification.ml
  pretyping/unification.mli
  proofs/clenv.ml
  proofs/clenv.mli
  tactics/equality.ml
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup

#19837 CClosure.to_constr does not take a univ instance
  kernel/cClosure.ml
Labels: kind: cleanup

#19826 Coqinit split init_runtime to better support having multiple docs
  dev/ci/user-overlays/19826-SkySkimmer-vscoq-multiple-coqproject.sh
  sysinit/coqinit.ml
  sysinit/coqinit.mli
  toplevel/coqtop.ml
Labels: kind: internal

#19845 Fix binder factorization when implicit status differ
  interp/constrextern.ml
  test-suite/output/bug_19702.out
  test-suite/output/bug_19702.v
Labels: kind: fix, kind: user messages

#19848 Add test for template poly extracted from mtac2
  test-suite/bugs/bug_19299.v
Labels: kind: internal

#19847 Remove the unused PATTERNIDENT token.
  coqpp/coqpp_main.ml
  parsing/tok.ml
  parsing/tok.mli
Labels: kind: cleanup

#19831 When a record cannot be declared with primitive projections, explain why
  checker/checkInductive.ml
  kernel/indTyping.ml
  kernel/indTyping.mli
  kernel/indtypes.ml
  kernel/indtypes.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  library/global.mli
  test-suite/output/Record.out
  test-suite/output/Record.v
  vernac/declareInd.ml
  vernac/record.ml
Labels: kind: user messages

#19852 Fix stdlib proofs to work with strict focusing
  theories/Classes/CMorphisms.v
  theories/FSets/FMapFacts.v
  theories/ZArith/Zdiv_facts.v
Labels: kind: cleanup, part: standard library

#19841 coq_makefile stop installing cmxs files in legacy location
  doc/changelog/09-cli-tools/19841-coq-makefile-no-double-install-cmxs.rst
  test-suite/coq-makefile/coqdoc1/run.sh
  test-suite/coq-makefile/coqdoc2/run.sh
  test-suite/coq-makefile/mlpack1/run.sh
  test-suite/coq-makefile/mlpack2/run.sh
  test-suite/coq-makefile/multiroot/run.sh
  test-suite/coq-makefile/native1/run.sh
  test-suite/coq-makefile/native2/run.sh
  test-suite/coq-makefile/native3/run.sh
  test-suite/coq-makefile/native4/run.sh
  test-suite/coq-makefile/plugin1/run.sh
  test-suite/coq-makefile/plugin2/run.sh
  test-suite/coq-makefile/plugin3/run.sh
  tools/CoqMakefile.in
Labels: kind: cleanup, part: tools

#19856 Update ci-macos.yml
  .github/workflows/ci-macos.yml
Labels: kind: infrastructure

#19860 Reverse bad change to exception in Ltac debugger in #19314
  plugins/ltac/tactic_debug.ml
Labels: kind: regression, part: ltac debugger

#19846 Use `reference` nonterminal to parse references in terms
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  parsing/g_constr.mlg
  test-suite/output/PrintGrammar.out
  test-suite/output/PrintGrammarConstr.out
  test-suite/output/Qf_stdlib.out
  test-suite/output/Qf_stdlib.v
Labels: kind: cleanup

#19771 Fix scheme dependency duplicate definitions
  tactics/ind_tables.ml
  vernac/auto_ind_decl.ml
Labels: kind: fix, part: scheme

#19584 Provide source location for declared objects
  dev/ci/user-overlays/19584-SkySkimmer-jump-to-def.sh
  interp/abbreviation.ml
  lib/loc.ml
  lib/loc.mli
  library/nametab.ml
  library/nametab.mli
  test-suite/output/Arguments.out
  test-suite/output/ArgumentsScope.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/Inductive.out
  test-suite/output/PrimitiveProjectionsAttribute.out
  test-suite/output/PrimitiveProjectionsAttribute_Records.out
  test-suite/output/PrintInfos.out
  test-suite/output/PrintSecDeps.out
  test-suite/output/Qf_stdlib.out
  test-suite/output/SchemeNames.out
  test-suite/output/UnivBinders.out
  test-suite/output/Utf8Impargs.out
  test-suite/output/bug_15020.out
  test-suite/output/bug_19702.out
  test-suite/output/wish_18097.out
  vernac/classes.ml
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/prettyp.ml
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
  vernac/vernacinterp.ml
Labels: kind: feature

#19880 Remove outdated comment in conversion.ml
  kernel/conversion.ml
Labels: kind: cleanup

#19881 Delete remaining .mllib files in plugins/
  plugins/cc/cc_core_plugin.mllib
  plugins/firstorder/firstorder_core_plugin.mllib
  plugins/ltac2_ltac1/ltac2_ltac1_plugin.mllib
  plugins/micromega/micromega_core_plugin.mllib
  plugins/nsatz/nsatz_core_plugin.mllib
Labels: kind: cleanup

#19876 Add test and critical bug entry for #19861
  dev/doc/critical-bugs.md
  test-suite/output/bug_19861.out
  test-suite/output/bug_19861.v
Labels: kind: fix

#19882 Remove add_known_module in cctac.ml
  plugins/cc/cctac.ml
  plugins/cc/dune
Labels: kind: cleanup

#19863 coqdep: add `-I` from `-f _CoqProject` to findlib search path, remove `-m`
  doc/changelog/09-cli-tools/19863-coqdep-nom.rst
  test-suite/misc/non-marshalable-state.sh
  test-suite/misc/non-marshalable-state/_CoqProject
  test-suite/misc/non-marshalable-state/src/META.coq-test-suite
  test-suite/misc/quotation_token.sh
  test-suite/misc/quotation_token/.gitignore
  test-suite/misc/quotation_token/META.coq-test-suite
  test-suite/misc/quotation_token/_CoqProject
  tools/CoqMakefile.in
  tools/coqdep/lib/args.ml
  tools/coqdep/lib/args.mli
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/fl.ml
  tools/coqdep/lib/fl.mli
Labels: kind: cleanup, part: build, part: coqdep

#19877 (8.20) Fix inconsistency #19861
  kernel/constant_typing.ml
  test-suite/output/bug_19861.out
  test-suite/output/bug_19861.v
Labels: kind: fix

#19874 [ci] bump elpi to 2.0.x
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
  dev/ci/user-overlays/19874-gares-elpi-2.0.sh
Labels: kind: infrastructure

#19883 'Ltac2 Notation string := ...' is not abbreviation.
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation
