Repository rocq-prover/rocq, pull requests merged in 2025-01, with the labels that each got.

#19982 Missing spaces in documentation of rocq doc.
  doc/sphinx/using/tools/coqdoc.rst
Labels: kind: fix, kind: documentation

#19980 Rename coq-native -> rocq-native
  .gitlab-ci.yml
  coq.opam
  coq.opam.template
  dev/bench/bench.sh
  dev/ci/docker/edge_ubuntu/Dockerfile
  dune-project
  rocq-core.opam
  rocq-runtime.opam
  rocq-runtime.opam.template
  stdlib/coq-stdlib.opam
  stdlib/dune-project
Labels: kind: infrastructure

#19958 CI: validate jobs also check stdlib
  .gitlab-ci.yml
Labels: kind: infrastructure

#19964 pretype template poly as though sort poly restricted to above_prop
  pretyping/pretyping.ml
  pretyping/retyping.ml
  test-suite/success/Template.v
Labels: kind: redesign, kind: enhancement

#19954 check all keys
  pretyping/evarconv.ml
  test-suite/success/CanonicalStructure.v
Labels: kind: fix

#19769 Fixes #17314: Tactic unification may leave unbound de Bruijn indices when unifying holes under a "fun"
  doc/changelog/04-tactics/19769-master+fix17314-wrong-env-unif-meta-under-lambda.rst
  pretyping/unification.ml
  test-suite/bugs/bug_17314.v
Labels: kind: fix, part: tactics, part: unification

#19914 stdlib: add generated `All.v` requiring everything in stdlib
  doc/changelog/11-standard-library/19914-stdlib-all.rst
  stdlib/theories/dune
  stdlib/tools/dune
  stdlib/tools/gen_all.ml
Labels: part: standard library, kind: enhancement

#19970 retype template poly as though sort poly restricted to above_prop
  kernel/inductive.ml
  kernel/inductive.mli
  plugins/extraction/extraction.ml
  plugins/extraction/table.ml
  plugins/extraction/table.mli
  pretyping/evarsolve.ml
  pretyping/evarsolve.mli
  pretyping/pretyping.ml
  pretyping/retyping.ml
  pretyping/retyping.mli
  pretyping/templateArity.ml
  pretyping/templateArity.mli
  test-suite/success/Template.v
  test-suite/success/extraction_polyprop.v
Labels: kind: redesign, kind: enhancement, part: universes, part: inductives

#19973 Rename coq-stdlib -> rocq-stdlib
  .gitlab-ci.yml
  Makefile
  coq.opam
  dev/ci/ci-stdlib.sh
  dev/ci/platform/coq-pf-03-build.bat
  dev/doc/release-process.md
  dune-project
  rocq.opam
  stdlib/INSTALL.md
  stdlib/Makefile
  stdlib/coq-stdlib.opam
  stdlib/doc/dune
  stdlib/doc/stdlib/dune
  stdlib/dune-project
  stdlib/rocq-stdlib.opam
  stdlib/rocq-stdlib.opam.template
  stdlib/theories/dune
Labels: kind: infrastructure

#19775 Fixes #12417: check that the argument of "wf" in funind is a well-typed relation
  doc/changelog/02-specification-language/19775-master+fix12417-check-typing-wf-relation.rst
  plugins/funind/recdef.ml
  test-suite/bugs/bug_12417.v
Labels: kind: fix, part: functional scheme

#19988 More informative print for inductive missing constraints error
  checker/coqchk_main.ml
  kernel/indTyping.ml
  kernel/indtypes.ml
  kernel/type_errors.ml
  kernel/type_errors.mli
  vernac/comInductive.ml
  vernac/himsg.ml
Labels: kind: user messages

#19955 Env vars: try reading ROCQFOO before COQFOO, ROCQRUNTIMELIB before COQCORELIB
  INSTALL.md
  Makefile
  boot/env.ml
  boot/env.mli
  boot/util.ml
  boot/util.mli
  checker/coqchk_main.ml
  default.nix
  dev/ci/ci-common.sh
  dev/ci/nix/unicoq/default.nix
  doc/plugin_tutorial/dune
  doc/sphinx/changes.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  lib/envars.ml
  lib/envars.mli
  lib/newProfile.ml
  printing/proof_diffs.ml
  sysinit/coqinit.mli
  sysinit/coqloadpath.ml
  sysinit/coqloadpath.mli
  test-suite/Makefile
  test-suite/misc/coq_environment.sh
  test-suite/output-coqtop/ListTags.out
  tools/coqworkmgr/coqworkmgrApi.ml
  tools/coqworkmgr/rocqworkmgr.ml
  tools/update-require
  topbin/rocqnative.ml
  topbin/rocqshim.ml
  toplevel/colors.ml
Labels: kind: redesign

#19996 Fixing stdlib opam files
  dune-project
  rocq-core.opam
  stdlib/coq-stdlib.opam
  stdlib/dune-project
  stdlib/rocq-stdlib.opam
Labels: kind: infrastructure

#19993 Print file total time in timelog2html
  dev/bench/htmloutput.ml
  test-suite/misc/bench-render/result.html
Labels: kind: enhancement

#19981 "Warnings" and "Debug" options are synterp not interp
  dev/ci/user-overlays/19981-SkySkimmer-classify-warn.sh
  doc/changelog/08-vernac-commands-and-options/19981-classify-warn.rst
  vernac/vernacentries.ml
Labels: kind: user messages

#19956 Basic manpage for rocq
  man/dune
  man/rocq.1
  man/rocqchk.1
Labels: kind: documentation

#19997 remove compat Requires of Ztac
  stdlib/theories/Reals/R_Ifp.v
  stdlib/theories/Reals/Rfunctions.v
  stdlib/theories/micromega/ZMicromega.v
Labels: kind: cleanup, part: standard library

#20001 Fix #20000: Uncaught exception Modops.ModuleTypingError.
  test-suite/bugs/bug_20000.v
  test-suite/output/ErrorModuleWith.out
  vernac/himsg.ml
Labels: kind: fix

#20006 Use custom helper instead of md5sum in with-rocq-wrap
  stdlib/dev/tools/dune
  stdlib/dev/tools/hash.ml
  stdlib/dev/tools/hash.mli
  stdlib/dev/with-rocq-wrap.sh
Labels: kind: infrastructure

#20002 Bench: only show packages which took at least 1s in render_results table
  dev/bench/bench.sh
  dev/bench/render_results.ml
Labels: kind: infrastructure

#20010 Fix with-rocq-wrap when called from unexpected directory
  stdlib/dev/with-rocq-wrap.sh
Labels: kind: infrastructure

#20015 test suite printers test ignore welcome message
  test-suite/misc/printers.sh
Labels: kind: fix

#19961 ltac2-numgoals-ret-0 fix ltac2 eval before Qed
  doc/changelog/06-Ltac2-language/19961-eval-with-zero-goals.rst
  plugins/ltac2/tac2entries.ml
  test-suite/ltac2/numgoals.v
Labels: kind: usability

#19842 Stop adding user-contrib, xgd dirs and COQPATH to ml loadpath
  doc/changelog/14-misc/19842-no-ml-misc-dirs.rst
  sysinit/coqloadpath.ml
Labels: kind: cleanup, part: build, part: toplevel

#18762 Strictly unique classes can be resolved independently.
  doc/changelog/02-specification-language/18762-janno-strictly-unique.rst
  tactics/class_tactics.ml
  test-suite/success/eauto.v
Labels: kind: enhancement

#20007 build:base:dev artifact expire after 1 day instead of 1 week
  .gitlab-ci.yml
Labels: kind: infrastructure

#20017 Missing space in warning message
  lib/envars.ml
Labels: kind: user messages

#20004 Make cbn consider primitive values "constructors"
  doc/changelog/04-tactics/20004-janno-cbn-prim-constructor.rst
  tactics/cbn.ml
  test-suite/bugs/bug_20003.v
  test-suite/bugs/bug_20008.v
Labels: kind: fix

#20019 [release notes] Remove left-overs forgotten in https://github.com/coq/coq/pull/19370
  dev/doc/release-process.md
Labels: kind: documentation

#20021 Fix missing match cases for prim strings in notation.ml
  interp/notation.ml
  test-suite/output/bug_20020.out
  test-suite/output/bug_20020.v
Labels: kind: fix, part: primitive types

#20022 Remove Detyping.Now from constrextern (mistakenly committed)
  interp/constrextern.ml
Labels: kind: fix, kind: user messages

#20029 Fix with-rocq-wrap on cygwin
  stdlib/dev/tools/hash.ml
  stdlib/dev/with-rocq-wrap.sh
Labels: kind: infrastructure

#20023 Rename Coq -> Rocq in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind: documentation

#20025 Rename Coq -> Rocq in README.md
  README.md
Labels: kind: documentation

#20028 Renaming prompt
  dev/ci/user-overlays/20028-proux01-renamiing-prompt.sh
  stdlib/test-suite/Makefile
  stdlib/test-suite/README.md
  test-suite/Makefile
  test-suite/misc/printers.sh
  test-suite/output-coqtop/BracketLoc.out
  test-suite/output-coqtop/DependentEvars.out
  test-suite/output-coqtop/DependentEvars2.out
  test-suite/output-coqtop/DependentEvars3.out
  test-suite/output-coqtop/LookaheadErrors.out
  test-suite/output-coqtop/ShowGoal.out
  test-suite/output-coqtop/ShowProofDiffs.out
  test-suite/output-coqtop/attributes.out
  test-suite/output-coqtop/backto.out
  test-suite/output-coqtop/bug_12138.out
  test-suite/output-coqtop/bug_16462.out
  test-suite/output-coqtop/bug_16745.out
  test-suite/output-coqtop/ltac2_var_quot.out
  tools/rocqtex.ml
  toplevel/coqloop.ml
  toplevel/coqtop.ml
Labels: kind: user messages

#20024 Rename Coq -> Rocq in INSTALL.md
  INSTALL.md
Labels: kind: documentation

#20039 Fix doc:refman:deploy
  .gitlab-ci.yml
Labels: kind: infrastructure

#20041 reindent ppconstr
  printing/ppconstr.ml
Labels: kind: cleanup

#20040 Clean up leftovers in CODEOWNERS after stdlib split.
  .github/CODEOWNERS
Labels: kind: cleanup, kind: meta

#20027 Renaming Coq -> Rocq in user messages
  boot/env.ml
  boot/usage.ml
  lib/cErrors.ml
  lib/system.ml
  library/summary.ml
  stm/stm.ml
  tools/CoqMakefile.in
  tools/configure/cmdArgs.ml
  tools/configure/configure.ml
  tools/coqdep/lib/args.ml
  tools/coqdoc/cmdArgs.ml
  tools/coqworkmgr/rocqworkmgr.ml
  tools/rocqmakefile.ml
  tools/rocqtex.ml
  topbin/rocqnative.ml
  vernac/future.ml
  vernac/loadpath.ml
  vernac/mltop.ml
Labels: kind: user messages

#20050 Remove leftover dev tool from before the Platform.
  dev/tools/notify-upstream-pins.sh
Labels: kind: cleanup

#20049 Many small renaming fixes, use the Rocq Prover fullname more often.
  CONTRIBUTING.md
  README.md
  coq-doc.opam
  coqide-server.opam
  default.nix
  dev/ci/README.md
  dune-project
  man/rocqide.1
  rocq-core.opam
  rocq-runtime.opam
  rocq.opam
  rocqide.opam
Labels: kind: fix

#20046 Pin CI developments for the 9.0 branch.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#20053 Add `rocq --print-version` (same as `coqc --print-version`)
  topbin/rocq.ml
Labels: kind: user messages

#20043 CI: bump elpi to 2.0.7
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
Labels: kind: infrastructure

#19995 Abstract away the representation of module-related types
  checker/mod_checking.ml
  checker/mod_checking.mli
  checker/safe_checking.ml
  dev/ci/user-overlays/19995-ppedrot-module-abstract-type.sh
  interp/modintern.ml
  kernel/declarations.mli
  kernel/declareops.ml
  kernel/declareops.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/mod_declarations.ml
  kernel/mod_declarations.mli
  kernel/mod_typing.ml
  kernel/mod_typing.mli
  kernel/modops.ml
  kernel/modops.mli
  kernel/nativelibrary.ml
  kernel/nativelibrary.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  kernel/subtyping.ml
  kernel/subtyping.mli
  library/global.mli
  library/rocqlib.ml
  plugins/extraction/extract_env.ml
  topbin/rocqnative.ml
  vernac/assumptions.ml
  vernac/declaremods.ml
  vernac/himsg.ml
  vernac/printmod.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#20047 Add the 9.0 refman link.
  doc/sphinx/conf.py
Labels: kind: infrastructure

#20012 More informative error from universe instance length mismatch
  dev/ci/user-overlays/20012-SkySkimmer-instance-length-mismatch-error.sh
  engine/univGen.ml
  engine/univGen.mli
  pretyping/pretyping.ml
  printing/printer.ml
  printing/printer.mli
  test-suite/output/UnivBinders.out
  vernac/prettyp.ml
  vernac/printmod.ml
Labels: kind: user messages

#20058 Ensure at runtime that the modpath is synced with module bodies and types
  checker/mod_checking.ml
  kernel/mod_declarations.ml
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/nativelibrary.ml
  kernel/subtyping.ml
  plugins/extraction/extract_env.ml
  vernac/assumptions.ml
Labels: kind: cleanup

#20062 Changelog for 8 20 1
  doc/changelog/01-kernel/19671-master+fix19661-guard-with-uniform-parameters.rst
  doc/changelog/03-notations/19653-fix-19541.rst
  doc/changelog/03-notations/19673-fix_19658.rst
  doc/changelog/04-tactics/19675-janno-fix-19668.rst
  doc/sphinx/changes.rst
Labels: needs: full CI

#20060 Stop storing the module path in modules.
  checker/mod_checking.ml
  checker/safe_checking.ml
  checker/values.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/mod_declarations.ml
  kernel/mod_declarations.mli
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/modops.mli
  kernel/nativelibrary.ml
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  kernel/subtyping.ml
  kernel/subtyping.mli
  plugins/extraction/extract_env.ml
  vernac/assumptions.ml
  vernac/declaremods.ml
Labels: kind: cleanup

#20063 Bump the fiat-parsers and compcert pins for #20052.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#20065 Changelog for 8.20.1
  doc/changelog/01-kernel/19671-master+fix19661-guard-with-uniform-parameters.rst
  doc/changelog/03-notations/19653-fix-19541.rst
  doc/changelog/03-notations/19673-fix_19658.rst
  doc/changelog/04-tactics/19675-janno-fix-19668.rst
  doc/sphinx/changes.rst
Labels: kind: documentation

#20013 Cleanup configure directory handling / -prefix
  config/dune
  test-suite/Makefile
  tools/configure/cmdArgs.ml
  tools/configure/cmdArgs.mli
  tools/configure/configure.ml
Labels: kind: infrastructure

#20066 Remove XXX comment in tacentries
  plugins/ltac/tacentries.ml
Labels: kind: cleanup

#20070 basic-overlay stdlib repo is stdlib not stdlib-test
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#19805 Use the release Dune profile when running `configure` during opam package installation
  configure
  coq.opam
  coq.opam.template
  rocq-runtime.opam
  rocq-runtime.opam.template
Labels: kind: fix, part: build

#20071 Backport from opam repo
  coq-core.opam
  dune-project
  rocq-runtime.opam
Labels: kind: infrastructure

#20075 Do not use the delta_resolver type for safe environment paramresolver.
  kernel/mod_subst.ml
  kernel/names.ml
  kernel/names.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  vernac/declaremods.ml
Labels: kind: cleanup

#20077 Changing the RocqIDE icon to the Rocq logo.
  ide/rocqide/MacOS/coqide.icns
  ide/rocqide/coq.ico
  ide/rocqide/coq.png
Labels: kind: fix, priority: blocker

#20076 chore: Update CODEOWNERS to address #19962
  .github/CODEOWNERS
Labels: kind: meta

#20074 Simplify Universe.sup by inlining Expr.super
  kernel/univ.ml
Labels: kind: cleanup

#20084 Bump refman link for 8.20 to latest tag.
  doc/sphinx/conf.py
Labels: kind: documentation

#20091 Clarify when links for previous refman versions should be switched from branch to tag.
  dev/doc/release-process.md
Labels: kind: meta

#20083 Additions for integration in the new website (should be backwards compatible)
  doc/sphinx/_static/coqdoc.css
Labels: kind: infrastructure

#20080 Fix composition of module substitution.
  kernel/mod_subst.ml
Labels: kind: fix

#20079 Fix domain substitution of delta-resolvers.
  kernel/mod_subst.ml
  test-suite/bugs/bug_20079.v
Labels: kind: fix

#19969 Fix debug printer on binder with evars
  engine/namegen.ml
Labels: kind: internal

#20095 Refactor record.ml
  dev/ci/user-overlays/20095-SkySkimmer-record-share-ind.sh
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/record.ml
  vernac/record.mli
Labels: kind: redesign, kind: cleanup

#20108 Remove outdated TODO.
  dev/ci/ci-basic-overlay.sh
Labels: kind: cleanup

#20105 [v9.0] Bump stdlib commit after version switcher update.
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#20069 Remove "env" argument of Evd.set_(l)eq_sort
  dev/ci/user-overlays/20069-SkySkimmer-set-leq-noenv.sh
  engine/evd.ml
  engine/evd.mli
  pretyping/cases.ml
  pretyping/evarconv.ml
  pretyping/evardefine.ml
  pretyping/evarsolve.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  pretyping/typing.ml
  pretyping/unification.ml
  tactics/elimschemes.ml
  vernac/comInductive.ml
  vernac/record.ml
Labels: kind: cleanup

#20104 More informative error for not allowed dependent elimination
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  vernac/himsg.ml
Labels: kind: user messages

#20103 CI: there are no artifacts in stdlib/_build
  .gitlab-ci.yml
  dev/tools/cleanup-artifacts.sh
  dev/tools/list-potential-artifacts.sh
Labels: kind: infrastructure

#20102 Typecheck pseudo sort poly inductives in kernel using above prop qvar
  checker/checkInductive.ml
  checker/values.ml
  dev/ci/user-overlays/20102-SkySkimmer-kernel-template-qvar.sh
  kernel/declarations.mli
  kernel/declareops.ml
  kernel/discharge.ml
  kernel/entries.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/indTyping.ml
  kernel/inductive.ml
  kernel/inductive.mli
  kernel/typeops.ml
  kernel/uGraph.ml
  kernel/uGraph.mli
  test-suite/output/Inductive.out
  test-suite/output/UnivBinders.out
  vernac/comInductive.ml
  vernac/prettyp.ml
  vernac/record.ml
Labels: kind: redesign, part: universes, part: inductives

#20093 Add missing newlines in changelog titles
  doc/changelog/05-Ltac-language/00000-title.rst
  doc/changelog/06-Ltac2-language/00000-title.rst
  doc/changelog/10-rocqide/00000-title.rst
Labels: kind: documentation

#20115 Fix composition of delta resolvers in "with Module".
  kernel/mod_subst.ml
  kernel/mod_subst.mli
  kernel/mod_typing.ml
  test-suite/bugs/bug_20115.v
Labels: kind: cleanup

#20116 Strenghthen signatures from left to right.
  kernel/modops.ml
Labels: kind: cleanup

#20097 Fix some calls to Mod_subst.add_delta_resolver.
  kernel/modops.ml
Labels: kind: fix

#20123 Bump version to 9.0+rc1.
  tools/configure/configure.ml
Labels: kind: infrastructure

#20106 Case elaboration treat private inductives like abstract types
  pretyping/cases.ml
  test-suite/bugs/bug_19983.v
Labels: kind: fix

#20127 Rename PDF refman, and other occurrences of Coq RefMan.
  doc/LICENSE
  doc/common/styles/html/simple/styles.hva
  doc/dune
  doc/sphinx/conf.py
  man/coq_makefile.1
  man/coqc.1
  man/coqchk.1
  man/coqdoc.1
  man/coqnative.1
  man/coqtop.1
  man/coqtop.byte.1
Labels: kind: fix, kind: documentation

#20130 Update header and footer, fix name in simple/header.html as well
  doc/common/styles/html/coqremote/footer.html
  doc/common/styles/html/coqremote/header.html
  doc/common/styles/html/simple/header.html
Labels: kind: documentation

#20137 [CI] Fix mathcomp CI script
  dev/ci/ci-mathcomp.sh
  dev/ci/ci-mathcomp_test.sh
Labels: kind: infrastructure

#20124 Stronger invariants in delta resolvers.
  checker/mod_checking.ml
  checker/values.ml
  kernel/mod_declarations.ml
  kernel/mod_subst.ml
  kernel/mod_subst.mli
  kernel/mod_typing.ml
  kernel/modops.ml
  kernel/nativelibrary.ml
  kernel/safe_typing.ml
  plugins/extraction/extract_env.ml
  test-suite/bugs/bug_20124_1.v
  test-suite/bugs/bug_20124_2.v
  vernac/assumptions.ml
  vernac/declaremods.ml
  vernac/printmod.ml
Labels: kind: cleanup

#20126 Fix opam package name.
  coq.opam
  dune-project
  rocq-prover.opam
Labels: kind: fix, kind: infrastructure

#20088 Add Ltac2.Constr.{is_string,is_sort}
  doc/changelog/06-Ltac2-language/20088-ltac2-is-sort.rst
  user-contrib/Ltac2/Constr.v
Labels: kind: enhancement, part: ltac2

#19985 Stop using lbound:Prop
  dev/ci/user-overlays/19985-SkySkimmer-cominductive-lbound.sh
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  engine/univMinim.ml
  engine/univMinim.mli
  kernel/declareops.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/uGraph.ml
  kernel/uGraph.mli
  pretyping/templateArity.ml
  test-suite/success/Template.v
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/vernacentries.ml
Labels: kind: redesign, kind: enhancement, part: universes, part: inductives

#20146 Fix library index prefix for corelib/index.html generation
  doc/corelib/make-library-index
Labels: kind: documentation

#20143 More precise computation of delta-resolvers in with Module.
  kernel/mod_typing.ml
Labels: kind: cleanup

#20149 Fix windows CI overriding rocq-prover
  dev/ci/platform/coq-pf-03-build.bat
Labels: kind: infrastructure

#20151 Fix corelib doc deployment
  .gitlab-ci.yml
Labels: kind: documentation, kind: infrastructure

#20141 Faster computation of primitive arguments in CClosure.
  kernel/cClosure.ml
Labels: kind: performance

#20089 Add Ltac2.Constr.decompose_app{,_list}
  doc/changelog/06-Ltac2-language/20089-ltac2-decompose-app.rst
  user-contrib/Ltac2/Constr.v
Labels: kind: enhancement, part: ltac2

#20156 coq_makefile: Ensure `STDTIME` works when `TIMED` is empty
  tools/CoqMakefile.in
Labels: kind: enhancement, part: coq_makefile

#20094 Use Register instead of typeclass cl_projs to get "proper_prf"
  plugins/ltac/comRewrite.ml
  plugins/ring/ring.ml
  tactics/rewrite.ml
  tactics/rewrite.mli
  theories/Classes/CMorphisms.v
  theories/Classes/Morphisms.v
Labels: kind: cleanup

#20164 Bench explicit package is rocq-equations not coq-equations
  dev/bench/bench.sh
Labels: kind: infrastructure

#20166 [ci] Equations: use dune commands directly
  dev/ci/ci-equations.sh
  dev/ci/ci-equations_test.sh
Labels: kind: infrastructure

#20159 Introduce a notion of change function in the tactic API.
  plugins/ltac/internals.ml
  plugins/ltac/tacinterp.ml
  plugins/ltac2/tac2tactics.ml
  pretyping/tacred.ml
  pretyping/tacred.mli
  tactics/redexpr.ml
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: performance

#20152 Small cleanups around inductive_arity
  dev/ci/user-overlays/20152-SkySkimmer-simplify-arity.sh
  kernel/declarations.mli
  kernel/declareops.ml
  kernel/declareops.mli
Labels: kind: cleanup

#20054 Ltac redefinition support standard localities (default SuperGlobal + Export)
  dev/ci/user-overlays/20054-SkySkimmer-tac-redef-locality.sh
  doc/changelog/05-Ltac-language/20054-tac-redef-locality.rst
  doc/sphinx/proof-engine/ltac.rst
  plugins/ltac/g_ltac.mlg
  plugins/ltac/tacentries.ml
  plugins/ltac/tacentries.mli
  plugins/ltac/tacenv.ml
  plugins/ltac/tacenv.mli
Labels: kind: cleanup, kind: enhancement

#20172 Fix whitespace in rocq usage command
  topbin/rocq.ml
Labels: kind: fix, kind: user messages

#20173 Fix equations install
  dev/ci/ci-equations.sh
Labels: kind: infrastructure

#20174 Fix ci-equations_tests CI script.
  dev/ci/ci-equations_test.sh
Labels: kind: infrastructure

#20170 Additional cleanups around the module implementation
  checker/mod_checking.ml
  kernel/mod_declarations.ml
  kernel/mod_declarations.mli
  kernel/modops.ml
  kernel/safe_typing.ml
  kernel/subtyping.ml
  vernac/declaremods.ml
Labels: kind: cleanup

#20162 Faster functor application.
  kernel/mod_typing.ml
Labels: kind: performance

#20171 Do not add functor delta-resolvers when strengthening.
  kernel/modops.ml
Labels: kind: fix
