Repository rocq-prover/rocq, pull requests merged in 2025-09, with the labels that each got.

#20975 Better risk an anomaly than a missing warning (gramlib recovery mode)
  gramlib/grammar.ml
Labels: kind: cleanup

#20989 Do not overwrite modules when extracting abstract subcomponents.
  plugins/extraction/extract_env.ml
  test-suite/bugs/bug_20989.v
Labels: kind: cleanup

#21031 Slightly better compilation of functional cases in the VM / native.
  kernel/genlambda.ml
Labels: kind: cleanup

#21013 refactor tactic errors
  plugins/cc/cctac.ml
  tactics/tacticErrors.ml
  tactics/tacticErrors.mli
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: cleanup, part: tactics

#21020 Add an API for canonicalizing maps in Environ.
  dev/ci/user-overlays/21020-ppedrot-qmap-api.sh
  interp/constrextern.ml
  interp/constrintern.ml
  interp/dumpglob.ml
  interp/impargs.ml
  interp/implicit_quantifiers.ml
  interp/notation.ml
  interp/notation.mli
  kernel/environ.ml
  kernel/environ.mli
  plugins/ltac/comRewrite.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssr/ssrelim.ml
  plugins/ssr/ssrequality.ml
  plugins/ssr/ssripats.ml
  pretyping/arguments_renaming.ml
  pretyping/arguments_renaming.mli
  pretyping/cases.ml
  pretyping/coercion.ml
  pretyping/combinators.ml
  pretyping/evarconv.ml
  pretyping/evardefine.ml
  pretyping/evarsolve.ml
  pretyping/globEnv.ml
  pretyping/inductiveops.ml
  pretyping/pretyping.ml
  pretyping/pretyping.mli
  pretyping/retyping.ml
  pretyping/structures.ml
  pretyping/structures.mli
  pretyping/typeclasses.ml
  pretyping/typeclasses.mli
  pretyping/typing.ml
  pretyping/unification.ml
  proofs/clenv.ml
  tactics/class_tactics.ml
  tactics/evar_tactics.ml
  tactics/rewrite.ml
  tactics/tactics.ml
  vernac/classes.ml
  vernac/comArguments.ml
  vernac/comFixpoint.ml
  vernac/comInductive.ml
  vernac/prettyp.ml
  vernac/printmod.ml
  vernac/record.ml
Labels: kind: cleanup

#20226 Warning when generating a constraint involving a template universe
  engine/uState.ml
  engine/uState.mli
  vernac/declareInd.ml
Labels: kind: user messages

#21042 Fix ci-dpdgraph
  dev/ci/scripts/ci-coq_dpdgraph.sh
Labels: kind: infrastructure

#20885 Assert that modules are not redeclared in Environ API.
  kernel/environ.ml
Labels: kind: cleanup

#20931 Delete redundant Environ.push_qualities
  checker/safe_checking.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  library/global.ml
  library/global.mli
  vernac/declareUniv.ml
Labels: kind: cleanup

#21055 Ltac2 improve "patterns do not bind the same variables" message
  plugins/ltac2/tac2intern.ml
Labels: kind: user messages

#21057 Fix substitution of functor delta-resolvers when performing strengthening
  dev/doc/critical-bugs.md
  doc/changelog/01-kernel/21057-fix-module-strengthening-subst-Fixed.rst
  kernel/modops.ml
  test-suite/bugs/bug_21051.v
Labels: kind: fix, kind: inconsistency

#21040 Provide canonical map APIs in Environ.QConstant etc
  interp/impargs.ml
  interp/notation.ml
  kernel/environ.ml
  kernel/environ.mli
  pretyping/arguments_renaming.ml
  pretyping/pretyping.ml
  pretyping/structures.ml
  pretyping/typeclasses.ml
Labels: kind: cleanup

#21065 Add a test for #17726.
  test-suite/bugs/bug_17726.v
Labels: kind: infrastructure

#21059 Call the checker on the test for #2923.
  test-suite/bugs/bug_2923.v
Labels: kind: infrastructure

#21058 Add tests for the module system extracted from #21002.
  test-suite/bugs/bug_21002_1.v
  test-suite/bugs/bug_21002_2.v
Labels: kind: infrastructure

#21060 Stop relying on CanOrd in Ssrmatching.
  plugins/ssrmatching/ssrmatching.ml
Labels: kind: cleanup

#21049 Check correctness of canonical constant and inductive names when typing.
  checker/coqchk_main.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/modops.ml
  kernel/nativecode.ml
  kernel/type_errors.ml
  kernel/type_errors.mli
  kernel/typeops.ml
  kernel/vmsymtable.ml
  vernac/himsg.ml
Labels: kind: fix

#21071 doc_grammar SELF on the left means current level not NEXT
  doc/sphinx/language/core/assumptions.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/core/variants.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/doc_grammar.ml
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation, kind: infrastructure

#21066 Use user name for comparison in kernel side-effects.
  kernel/safe_typing.ml
Labels: kind: cleanup

#21061 Change univalence to propext in guard condition issue
  dev/doc/critical-bugs.md
  doc/changelog/01-kernel/21050-fix-match-as-subterm-Fixed.rst
  test-suite/bugs/bug_21053.v
Labels: kind: enhancement

#20957 Match-printing
  dev/ci/user-overlays/20957-Yann-Leray-match-printing.sh
  interp/constrextern.ml
  kernel/context.ml
  kernel/context.mli
  pretyping/inductiveops.mli
  printing/ppconstr.ml
  test-suite/output/Cases.out
  test-suite/output/Notations.out
  test-suite/output/PatternsInBinders.out
  test-suite/output/PrintMatch.out
  test-suite/output/PrintingParentheses.out
  test-suite/output/bug_19227.out
  test-suite/output/bug_19227.v
  test-suite/output/bug_20968.out
  test-suite/output/bug_20968.v
Labels: kind: user messages

#21086 Update history.rst
  doc/sphinx/history.rst
Labels: kind: fix, kind: documentation

#20614 Find schemes through registration in induction
  dev/ci/user-overlays/20614-SkySkimmer-induction-schemes.sh
  doc/changelog/04-tactics/20614-induction-schemes-Changed.rst
  doc/changelog/04-tactics/20614-induction-schemes-Deprecated.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  tactics/elimschemes.ml
  test-suite/success/Scheme.v
  vernac/indschemes.ml
  vernac/indschemes.mli
  vernac/vernacentries.ml
Labels: kind: enhancement

#21089 ci-metarocq build template plugin first
  dev/ci/scripts/ci-metarocq.sh
Labels: kind: infrastructure

#20794 Add equal for reference in Ltac2
  doc/changelog/06-Ltac2-language/20794-ltac2-equal-for-ref.rst
  doc/corelib/index-list.html.template
  theories/Ltac2/Reference.v
Labels: kind: enhancement

#21096 Ltac2: add Message.of_lconstr
  doc/changelog/06-Ltac2-language/21096-ltac2-message-lconstr-Added.rst
  plugins/ltac2/tac2core.ml
  test-suite/ltac2/example1.v
  theories/Ltac2/Message.v
Labels: kind: enhancement, part: ltac2

#21100 Further clean up of the constr matching algorithm
  pretyping/constr_matching.ml
Labels: kind: cleanup

#21063 Fix Tactics.descend_in_conjunctions on inductives with letins in constructors
  dev/ci/user-overlays/21063-SkySkimmer-fix-apply-nreal.sh
  tactics/tactics.ml
  test-suite/bugs/bug_21036.v
Labels: kind: fix

#21124 Helper scripts to update and reset local CI repositories
  Makefile.ci
  dev/ci/ci-reset.sh
  dev/ci/ci-update.sh
  dev/ci/scripts/ci-common.sh
Labels: kind: infrastructure

#21125 Remove noisy ls in ci-common
  dev/ci/scripts/ci-common.sh
Labels: kind: infrastructure

#21128 Minor enhancement to the ci-reset script.
  dev/ci/ci-reset.sh
Labels: kind: infrastructure

#21130 Use user name equality in checker rtree test.
  checker/checkInductive.ml
Labels: kind: cleanup

#21115 Purer scheme creation
  engine/evd.ml
  engine/evd.mli
  library/global.ml
  library/global.mli
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  vernac/declare.ml
Labels: kind: cleanup

#21114 Deprecate adding a hint to an undeclared hint database.
  doc/changelog/08-vernac-commands-and-options/21114-hintdb-strict-check-Deprecated.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  tactics/class_tactics.ml
  tactics/class_tactics.mli
  tactics/hints.ml
  test-suite/bugs/HoTT_coq_107.v
  test-suite/bugs/bug_21114.v
  test-suite/bugs/bug_3881.v
  test-suite/bugs/bug_4121.v
  test-suite/bugs/bug_4533.v
  test-suite/bugs/bug_4544.v
  test-suite/bugs/bug_5198.v
  test-suite/output/ArgumentsScope.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/Inductive.out
  test-suite/output/PrintInfos.out
  test-suite/output/TypeclassDebug.out
  test-suite/output/TypeclassDebug.v
  test-suite/output/auto_order.out
  test-suite/output/auto_order.v
  test-suite/output/bug_15020.out
  test-suite/output/bug_20754.out
  theories/Corelib/Classes/CRelationClasses.v
  theories/Corelib/Classes/RelationClasses.v
  theories/Corelib/Init/Datatypes.v
  theories/Corelib/Init/Logic.v
  theories/Corelib/Relations/Relation_Definitions.v
  vernac/classes.ml
  vernac/vernacentries.ml
Labels: kind: fix, kind: cleanup

#21132 Rely on user ordering for assumption sets and maps.
  printing/printer.ml
Labels: kind: cleanup

#20914 Parse 0 as Set and 1 as Set+1 in universe annotations
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/language/core/sorts.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  parsing/g_constr.mlg
  test-suite/success/polymorphism.v
Labels: kind: enhancement

#21142 Documentation fix
  doc/sphinx/proof-engine/vernacular-commands.rst
Labels: kind: documentation

#21144 CI don't print error summary for coq_tools
  dev/ci/ci-wrapper.sh
Labels: kind: infrastructure
