Repository rocq-prover/rocq, pull requests merged in 2025-05, with the labels that each got.

#20511 Extend goal selection to allow multiple named goals
  dev/ci/user-overlays/20511-dhalilov-multiple-named-goals.sh
  doc/changelog/05-Ltac-language/20511-multiple-named-goals-changed.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  engine/proofview.ml
  engine/proofview.mli
  plugins/ltac/g_ltac.mlg
  proofs/goal_select.ml
  proofs/goal_select.mli
  proofs/proof.mli
  test-suite/success/goal_selector.v
  vernac/declare.ml
  vernac/g_vernac.mlg
  vernac/vernacentries.ml
Labels: kind: enhancement

#20586 Remove the rocq-doc opam package
  doc/corelib/dune
  doc/dune
  dune-project
  rocq-doc.opam
Labels: kind: infrastructure

#20542 Don't use grammar rule deletion to implement unfreeze
  dev/ci/user-overlays/20542-SkySkimmer-clean-reinit.sh
  gramlib/grammar.ml
  gramlib/grammar.mli
  parsing/procq.ml
  parsing/procq.mli
  plugins/derive/g_derive.mlg
  plugins/ltac2/tac2entries.ml
  plugins/ssr/ssrparser.mlg
  plugins/ssr/ssrtacs.mlg
  plugins/ssr/ssrvernac.mlg
  plugins/ssrmatching/g_ssrmatching.mlg
  test-suite/bugs/bug_20537.v
  test-suite/output/Notations4.out
  vernac/egramrocq.ml
Labels: kind: redesign, kind: fix

#20589 [CI] Disactivate jasmin until it get fixed
  .gitlab-ci.yml
Labels: kind: infrastructure

#20566 Simplify encoding of Ltac2 rec
  plugins/ltac2/tac2entries.ml
  test-suite/bugs/bug_20564.v
Labels: kind: fix, part: ltac2

#20556 ci-waterproof don't use dune build -p
  dev/ci/scripts/ci-waterproof.sh
Labels: kind: infrastructure

#20573 document tactics/auto.mli
  tactics/auto.ml
  tactics/auto.mli
Labels: kind: internal

#20591 Use gender-neutral language in `CoqMakefile`
  tools/CoqMakefile.in
Labels: kind: internal

#20581 Revert using strip_update_shift_absorb_app for primitive types
  kernel/cClosure.ml
  test-suite/bugs/bug_20580.v
Labels: kind: fix

#18615 Declare global sort variables
  checker/values.ml
  dev/ci/user-overlays/18615-SkySkimmer-decl-sort.sh
  dev/top_printers.ml
  doc/changelog/08-vernac-commands-and-options/18615-decl-sort.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  engine/univGen.ml
  engine/univGen.mli
  engine/univNames.ml
  engine/univNames.mli
  interp/constrextern.ml
  interp/constrintern.ml
  interp/notation.ml
  kernel/cooking.ml
  kernel/cooking.mli
  kernel/discharge.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  kernel/section.ml
  kernel/section.mli
  kernel/sorts.ml
  kernel/sorts.mli
  library/global.ml
  library/global.mli
  library/nametab.ml
  library/nametab.mli
  plugins/funind/gen_principle.ml
  plugins/ltac/leminv.ml
  plugins/syntax/number_string.ml
  pretyping/glob_ops.ml
  pretyping/glob_ops.mli
  pretyping/typing.ml
  tactics/elimschemes.ml
  tactics/eqschemes.ml
  tactics/inv.ml
  test-suite/output/DeclareSort.out
  test-suite/output/DeclareSort.v
  vernac/declareUniv.ml
  vernac/declareUniv.mli
  vernac/g_vernac.mlg
  vernac/himsg.ml
  vernac/indschemes.ml
  vernac/ppvernac.ml
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
  vernac/vernacexpr.mli
Labels: kind: feature, part: universes, part: vernac

#20597 Add an option to set the bound on the message view.
  doc/changelog/10-rocqide/20597-rocqide-buffer-length-option-Fixed.rst
  ide/rocqide/preferences.ml
  ide/rocqide/preferences.mli
  ide/rocqide/preferences_ui.ml
  ide/rocqide/wg_MessageView.ml
Labels: kind: enhancement

#20598 Disable windows CI while it's broken
  .github/workflows/ci-windows.yml.disabled
Labels: kind: infrastructure

#20609 Move print_parentheses ref to constrextern
  interp/constrextern.ml
  interp/notation_ops.ml
  interp/notation_ops.mli
  interp/reserve.ml
Labels: kind: cleanup

#20610 [RocqIDE] Correctly switch focus in the search & replace widget.
  ide/rocqide/wg_Find.ml
Labels: kind: fix

#20612 Fix broken FAQ link in the README
  README.md
Labels: kind: documentation

#20607 Use CDebug for Dump Bytecode and Dump Lambda
  kernel/vmbytegen.ml
  kernel/vmbytegen.mli
  kernel/vmlambda.ml
  kernel/vmlambda.mli
  vernac/vernacentries.ml
Labels: kind: cleanup

#20584 Use APIs new since ocaml 4.09
  clib/cList.ml
  clib/cList.mli
  clib/cMap.ml
  clib/cMap.mli
  clib/cSig.mli
  clib/hMap.ml
  dev/bench/sourcehandler.ml
  kernel/vmemitcodes.ml
  lib/pp.ml
  tools/dune_rule_gen/coq_rules.ml
  tools/dune_rule_gen/util.ml
  tools/dune_rule_gen/util.mli
Labels: kind: cleanup

#20600 Fix missing implicit name from notation ToPostHole
  dev/ci/user-overlays/20600-SkySkimmer-fix-toposthole.sh
  engine/evar_kinds.ml
  engine/evar_kinds.mli
  engine/proofview.ml
  engine/termops.ml
  interp/constrintern.ml
  interp/notation.ml
  interp/notation.mli
  plugins/syntax/number_string.ml
  pretyping/glob_term.mli
  test-suite/bugs/bug_20599.v
  vernac/himsg.ml
Labels: kind: fix

#20498 Ltac2 add `%A` and `%m` format specifiers taking unthunked printer and message respectively
  doc/changelog/06-Ltac2-language/20498-ltac2-format-alpha.rst
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2extffi.ml
  plugins/ltac2/tac2extffi.mli
  plugins/ltac2/tac2print.ml
  plugins/ltac2/tac2print.mli
  plugins/ltac2/tac2quote.ml
  plugins/ltac2/tac2types.mli
  test-suite/output/ltac2_printf.out
  test-suite/output/ltac2_printf.v
  user-contrib/Ltac2/Message.v
  user-contrib/Ltac2/Printf.v
Labels: kind: enhancement

#20617 Ensure that Proofview.focus_context returns undefined evars
  engine/proofview.ml
  engine/proofview.mli
  ide/rocqide/idetop.ml
  proofs/proof.ml
  proofs/proof.mli
Labels: kind: cleanup

#20107 Allow error messages from number/string notation parsers
  doc/changelog/08-vernac-commands-and-options/20107-number-nota.rst
  doc/changelog/11-standard-library/20107-number-nota.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  interp/notation.ml
  interp/notation.mli
  plugins/syntax/number_string.ml
  test-suite/output/PrintInfos.out
  test-suite/output/StringNotationErrors.out
  test-suite/output/StringNotationErrors.v
  theories/Init/Datatypes.v
Labels: kind: user messages, kind: enhancement

#20619 `decompose` uses non dependent pattern matching for records
  tactics/elim.ml
Labels: kind: enhancement

#20608 Use :flag: for mention of Printing Matching in doc
  doc/sphinx/language/extensions/match.rst
Labels: kind: documentation

#20543 Ltac2: Add `Std.Red` module for conversions and centralize reduction tactics around it
  doc/changelog/06-Ltac2-language/20543-radrow-gh-20482-reductions-Added.rst
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ltac2/tac2tactics.mli
  plugins/ltac2/tac2types.mli
  test-suite/output/ltac2_anomaly_backtrace.out
  user-contrib/Ltac2/Std.v
Labels: kind: enhancement, part: ltac2

#20636 ci-algebra_tactics: disable native compute
  dev/ci/scripts/ci-algebra_tactics.sh
  dev/ci/scripts/ci-relation_algebra.sh
Labels: kind: infrastructure

#20605 Cleanup handling of projection flags
  dev/ci/user-overlays/20605-SkySkimmer-simpl-proj-flags.sh
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
  vernac/vernacexpr.mli
Labels: kind: cleanup, kind: internal

#20630 Further simplify mangling of Ltac2 rec, allowing type ascription
  plugins/ltac2/tac2entries.ml
  test-suite/ltac2/typing.v
Labels: kind: enhancement

#20623 Centralize the global state of extraction
  plugins/extraction/common.ml
  plugins/extraction/common.mli
  plugins/extraction/extract_env.ml
  plugins/extraction/extract_env.mli
  plugins/extraction/extraction.ml
  plugins/extraction/extraction.mli
  plugins/extraction/haskell.ml
  plugins/extraction/haskell.mli
  plugins/extraction/json.ml
  plugins/extraction/json.mli
  plugins/extraction/mlutil.ml
  plugins/extraction/mlutil.mli
  plugins/extraction/modutil.ml
  plugins/extraction/modutil.mli
  plugins/extraction/ocaml.ml
  plugins/extraction/ocaml.mli
  plugins/extraction/scheme.ml
  plugins/extraction/scheme.mli
  plugins/extraction/table.ml
  plugins/extraction/table.mli
Labels: kind: cleanup

#20643 Use EConstr.isRefX instead of copying it in constr_matching
  pretyping/constr_matching.ml
Labels: kind: cleanup

#20378 Fixed plugin_tutorial in rocq
  doc/plugin_tutorial/tuto0/Makefile
  doc/plugin_tutorial/tuto0/_CoqProject
  doc/plugin_tutorial/tuto0/src/META.rocq-plugin-tutorial
  doc/plugin_tutorial/tuto0/src/g_tuto0.mlg
  doc/plugin_tutorial/tuto0/theories/Loader.v
  doc/plugin_tutorial/tuto1/Makefile
  doc/plugin_tutorial/tuto1/_CoqProject
  doc/plugin_tutorial/tuto1/src/META.rocq-plugin-tutorial
  doc/plugin_tutorial/tuto1/src/g_tuto1.mlg
  doc/plugin_tutorial/tuto1/theories/Loader.v
  doc/plugin_tutorial/tuto2/Makefile
  doc/plugin_tutorial/tuto2/_CoqProject
  doc/plugin_tutorial/tuto2/src/META.rocq-plugin-tutorial
  doc/plugin_tutorial/tuto2/src/g_tuto2.mlg
  doc/plugin_tutorial/tuto2/theories/Loader.v
  doc/plugin_tutorial/tuto3/Makefile
  doc/plugin_tutorial/tuto3/_CoqProject
  doc/plugin_tutorial/tuto3/src/META.rocq-plugin-tutorial
  doc/plugin_tutorial/tuto3/src/g_tuto3.mlg
  doc/plugin_tutorial/tuto3/theories/Loader.v
Labels: kind: internal

#20651 Use a uniform representation for inductive nodes in extraction.
  plugins/extraction/extract_env.ml
  plugins/extraction/extraction.ml
  plugins/extraction/haskell.ml
  plugins/extraction/json.ml
  plugins/extraction/miniml.ml
  plugins/extraction/miniml.mli
  plugins/extraction/modutil.ml
  plugins/extraction/ocaml.ml
Labels: kind: cleanup

#20648 Fix guard checker inconsistency
  dev/doc/critical-bugs.md
  doc/changelog/01-kernel/20648-fix-guard-checker-Fixed.rst
  kernel/inductive.ml
  test-suite/bugs/bug_20555.v
Labels: kind: fix

#20502 Unify nametab APIs using functors
  engine/univNames.ml
  interp/constrintern.ml
  lib/deprecation.ml
  lib/deprecation.mli
  lib/userWarn.ml
  lib/userWarn.mli
  library/libnames.ml
  library/libnames.mli
  library/nametab.ml
  library/nametab.mli
  plugins/ltac/tacentries.ml
  plugins/ltac/tacenv.ml
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2intern.ml
  vernac/declareUniv.ml
Labels: kind: cleanup

#19700 Added a new projection generation for congruence
  doc/changelog/04-tactics/19700-dependent-projectability-congruence-Changed.rst
  plugins/cc/ccprojectability.ml
  plugins/cc/ccprojectability.mli
  plugins/cc/cctac.ml
  test-suite/failure/congruence.v
  test-suite/success/congruence.v
Labels: kind: enhancement, part: congruence

#20356 [refman] Improve Corelib documentation
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/core/primitive.rst
Labels: kind: documentation

#20613 Doc: add note about Printing Parentheses not adding parens to applications
  doc/sphinx/user-extensions/syntax-extensions.rst
Labels: kind: documentation

#20370 new example for bidirectionality hints in refman #12102
  doc/sphinx/language/extensions/arguments-command.rst
Labels: kind: documentation

#20658 remove some remaining uses of coq
  INSTALL.md
Labels: kind: documentation

#20640 Remove unused Lia Enum flag
  doc/changelog/08-vernac-commands-and-options/20640-lia-noenum-Removed.rst
  plugins/micromega/coq_micromega.ml
Labels: kind: cleanup

#20659 Clean up Ccprojectability implementation
  plugins/cc/ccprojectability.ml
Labels: kind: cleanup

#20664 Bench use metarocq instead of metacoq
  dev/bench/bench.sh
Labels: kind: infrastructure

#20625 ltac2: register names for terms and type definitions in VtSideff
  plugins/ltac2/g_ltac2.mlg
Labels: part: STM, kind: internal

#20655 Monomorphize sort polymorphic code in extraction.
  plugins/extraction/common.ml
  plugins/extraction/common.mli
  plugins/extraction/extract_env.ml
  plugins/extraction/extract_env.mli
  plugins/extraction/extraction.ml
  plugins/extraction/extraction.mli
  plugins/extraction/haskell.ml
  plugins/extraction/miniml.ml
  plugins/extraction/miniml.mli
  plugins/extraction/mlutil.ml
  plugins/extraction/mlutil.mli
  plugins/extraction/modutil.ml
  plugins/extraction/modutil.mli
  plugins/extraction/ocaml.ml
  plugins/extraction/table.ml
  plugins/extraction/table.mli
  test-suite/success/sort_poly_extraction.v
Labels: part: extraction, kind: enhancement

#20666 Fix typo in comment in Ltac2.List
  user-contrib/Ltac2/List.v
Labels: kind: documentation

#20676 Small typo in ltac2.rst
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation

#20677 Other typos in ltac2.rst
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation

#20675 Remove remnants of global mutable state in extraction
  plugins/extraction/extract_env.ml
  plugins/extraction/modutil.ml
Labels: kind: cleanup

#20637 ci-hott run make install (for the minimizer)
  dev/ci/scripts/ci-hott.sh
Labels: kind: infrastructure

#20569 Add a module Ltac1CompatibilityNotations for Ltac1 notations like transitivity
  doc/changelog/06-Ltac2-language/20549-ltac2-add-Ltac1CompatNotations.md
  doc/corelib/index-list.html.template
  user-contrib/Ltac2/Ltac1CompatNotations.v
Labels: kind: enhancement, part: ltac2
