Repository rocq-prover/rocq, pull requests merged in 2025-07, with the labels that each got.

#20826 Fix dependencies of the refman-html and refman-pdf targets.
  doc/dune
Labels: kind: fix, kind: infrastructure, part: build

#20842 Remove redundant add in changelog.
  doc/sphinx/changes.rst
Labels: kind: fix, kind: documentation

#20843 Avoid Stdlib.compare in notation.ml
  interp/constrexpr.mli
  interp/notation.ml
  interp/notationextern.ml
  interp/notationextern.mli
Labels: kind: cleanup

#20839 [classifier] visibility on attributes
  coqpp/coqpp_main.ml
  dev/ci/user-overlays/20839-gares-vernac-class-atts.sh
  dev/top_printers.ml
  vernac/vernac_classifier.ml
  vernac/vernacextend.ml
  vernac/vernacextend.mli
Labels: kind: internal

#20833 Fix inverted mod/modtype dumpglob in modintern
  interp/modintern.ml
Labels: kind: fix

#20831 Update mailmap
  .mailmap
  dev/tools/list-contributors.sh
Labels: kind: meta

#20836 Names: move set/map modules `KNset` -> `KerName.Set` etc
  dev/ci/user-overlays/20836-SkySkimmer-knset.sh
  dev/top_printers.ml
  dev/top_printers.mli
  interp/abbreviation.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/mod_declarations.ml
  kernel/mod_declarations.mli
  kernel/mod_subst.ml
  kernel/modops.ml
  kernel/names.ml
  kernel/names.mli
  kernel/safe_typing.ml
  kernel/vmlibrary.ml
  library/nametab.ml
  plugins/extraction/common.ml
  plugins/extraction/extract_env.ml
  plugins/extraction/modutil.ml
  plugins/extraction/table.ml
  plugins/extraction/table.mli
  plugins/ltac/pptactic.ml
  plugins/ltac/tacentries.ml
  plugins/ltac/tacenv.ml
  plugins/ltac/tacenv.mli
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2interp.ml
  plugins/ltac2/tac2print.ml
  tactics/autorewrite.ml
  tactics/hints.ml
  topbin/rocqnative.ml
  vernac/assumptions.ml
  vernac/declaremods.ml
  vernac/library.ml
Labels: kind: cleanup

#20844 Rocqify issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/SUPPORT.md
Labels: kind: meta

#20854 Fix test suite after parallel merge of #20813 and #20824
  test-suite/output/Cases.out
  test-suite/output/PrintMatch.out
Labels: kind: fix

#20799 Slightly simplify ltac2 goal_match_list grammar declaration
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
Labels: kind: cleanup

#20858 Correctly declare functor bodies in subtyping checks.
  kernel/subtyping.ml
Labels: kind: cleanup

#20819 Add modules shallowly in kernel module finalizer.
  kernel/mod_typing.ml
Labels: kind: cleanup

#20864 Add more stable anchor names for sections.
  doc/sphinx/language/core/conversion.rst
Labels: kind: documentation

#20642 Remove KerPair.SyntacticOrd
  dev/ci/user-overlays/20642-SkySkimmer-rm-synord.sh
  kernel/cooking.ml
  kernel/hConstr.ml
  kernel/names.ml
  kernel/names.mli
Labels: kind: cleanup

#20865 Do not pass the "core" database twice in hint tactics.
  tactics/hints.ml
Labels: kind: fix

#20820 Set firstorder solver explicitly to auto with core in prelude
  theories/Corelib/Init/Prelude.v
Labels: kind: cleanup

#20883 Add redirections for "coq-fooindex" refman pages to "rocq-fooindex"
  doc/sphinx/coq-attrindex.rst
  doc/sphinx/coq-cmdindex.rst
  doc/sphinx/coq-exnindex.rst
  doc/sphinx/coq-optindex.rst
  doc/sphinx/coq-tacindex.rst
Labels: kind: documentation

#20881 Remove dev/shim
  Makefile
  dev/doc/README.md
  dev/doc/build-system.dune.md
  dev/doc/debugging.md
  dev/doc/profiling.md
  dev/shim/dune
Labels: kind: infrastructure

#20853 Remove Mltop.module_is_known, now fully handled by Findlib
  coqpp/coqpp_main.ml
  dev/ci/user-overlays/20853-SkySkimmer-module-is-known.sh
  plugins/ltac/tauto.ml
  vernac/mltop.ml
  vernac/mltop.mli
Labels: kind: cleanup

#20882 Support local and export localities for Ltac2 Set
  doc/changelog/06-Ltac2-language/20882-ltac2-set-local-Added.rst
  plugins/ltac2/tac2entries.ml
  test-suite/ltac2/rebind.v
Labels: kind: enhancement

#20801 ci-cross-crypto keep build_ci for the minimizer
  .gitlab-ci.yml
Labels: kind: infrastructure

#20887 [ci] elpi 3.0
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
  dev/ci/user-overlays/20887-gares-elpi-3.0.sh
Labels: kind: infrastructure

#20891 Fix incorrect use of non-evar-aware `interp_casted_constr` in `exact_proof`
  interp/constrintern.ml
  interp/constrintern.mli
  tactics/tactics.ml
  test-suite/bugs/bug_20890.v
Labels: kind: fix

#20590 Export some APIs useful for ltac2 extensions
  plugins/ltac2/tac2core.mli
Labels: kind: internal

#20903 Ignore module redeclaration in Print Module commands.
  test-suite/bugs/bug_20903.v
  vernac/printmod.ml
Labels: kind: cleanup

#20912 Fix github CI badges in README
  README.md
Labels: kind: documentation

#20911 Make type Notation.prim_token_uid private
  dev/ci/user-overlays/20911-SkySkimmer-notation-uid.sh
  interp/notation.ml
  interp/notation.mli
Labels: kind: internal

#20913 coqpp fix NUMBER "x" handling
  coqpp/coqpp_main.ml
Labels: kind: fix, part: tools

#20907 rocq doc replace @@TITLE@@ in header with page title, use in corelib
  doc/changelog/09-cli-tools/20907-corelib-header-Added.rst
  doc/common/styles/html/coqremote/header.html
  doc/corelib/dune
  doc/sphinx/using/tools/coqdoc.rst
  tools/coqdoc/output.ml
Labels: kind: enhancement, part: coqdoc

#20698 Remove bugged Loose Hint Behavior and fix incorrect Import optim
  dev/ci/user-overlays/20698-SkySkimmer-rm-loose-hint.sh
  doc/changelog/04-tactics/20698-master-Fixed.rst
  doc/changelog/08-vernac-commands-and-options/20698-rm-loose-hint-Removed.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  tactics/auto.ml
  tactics/class_tactics.ml
  tactics/eauto.ml
  tactics/hints.ml
  tactics/hints.mli
  test-suite/bugs/bug_20695.v
Labels: kind: fix

#20921 Fix coqchk on files containing global sorts
  checker/safe_checking.ml
  checker/values.ml
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  test-suite/bugs/bug_20914.v
  vernac/vernacentries.ml
Labels: kind: fix

#20928 Use record instead of tuple for hint info in class_tactics
  tactics/class_tactics.ml
Labels: kind: cleanup

#20925 CI doc:refman:deploy shallow clone the doc repo
  .gitlab-ci.yml
Labels: kind: infrastructure

#20934 Remove trakt from CI
  .gitlab-ci.yml
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#20935 Stop changing build flags in elpi_test
  dev/ci/scripts/ci-elpi_test.sh
Labels: kind: infrastructure

#20951 gramlib remove unused "OPT_SEP" support on LIST0 SEP / LIST1 SEP
  coqpp/coqpp_main.ml
  gramlib/grammar.ml
  gramlib/grammar.mli
  plugins/ltac/tacentries.ml
  plugins/ltac2/tac2extravals.ml
  vernac/egramrocq.ml
  vernac/vernacextend.ml
Labels: kind: cleanup

#20959 Revert "[CI] Temporarily disactivate kami"
  .gitlab-ci.yml
Labels: kind: infrastructure, part: CI

#20954 Slightly nicer boxing in coqpp output
  coqpp/coqpp_main.ml
Labels: kind: cleanup

#20967 Fix some issues in refman
  doc/sphinx/proof-engine/tactics.rst
Labels: kind: documentation

#20952 Less <unknown> levels in warn-tolerance
  gramlib/grammar.ml
Labels: kind: fix, kind: user messages

#20977 Fix some issues in refman
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation

#20978 Reword a bit the documentation about library installation (fix #20963).
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: fix, kind: documentation

#20981 Use :n: for exclamation and question mark in refman equality
  doc/sphinx/proofs/writing-proofs/equality.rst
Labels: kind: documentation

#20838 Ubuntu 20.04 is EOL (move base to 22.04)
  .gitlab-ci.yml
  dev/ci/docker/old_ubuntu_lts/Dockerfile
  doc/README.md
  doc/sphinx/conf.py
Labels: kind: infrastructure, part: CI

#20946 Fixes #15815: Anomaly List.chop with extra projection parameters in a notation.
  doc/changelog/02-specification-language/20946-master+fix15815-anomaly-projection-notation-too-many-parameters-Fixed.rst
  interp/constrintern.ml
  test-suite/bugs/bug_15815.v
Labels: kind: fix, part: elaboration, part: records

#20945 Fixes #20940: anomaly List.chop in the presence of projections with not enough argument scopes
  doc/changelog/02-specification-language/20945-master+fix-arguments-too-little-scopes-proj-Fixed.rst
  interp/constrintern.ml
  test-suite/bugs/bug_20940.v
Labels: kind: fix, part: elaboration, part: records

#20926 Split some primitive notation code from notation.ml
  dev/ci/user-overlays/20926-SkySkimmer-split-nota.sh
  interp/notation.ml
  interp/notation.mli
  interp/primNotations.ml
  interp/primNotations.mli
  plugins/syntax/g_number_string.mlg
  plugins/syntax/number_string.ml
  plugins/syntax/number_string.mli
  vernac/himsg.ml
Labels: kind: internal
