Repository rocq-prover/rocq, pull requests merged in 2025-04, with the labels that each got.

#20415 Guard checker: don't forget to check non-structural arguments of fix
  dev/doc/critical-bugs.md
  doc/changelog/01-kernel/20415-fix-fix-incon.rst
  kernel/inductive.ml
  test-suite/bugs/bug_17091.v
  test-suite/bugs/bug_20413.v
Labels: kind: fix, kind: inconsistency

#20426 Fix comment in Ltac1.v to avoid coqdoc mangling it
  user-contrib/Ltac2/Ltac1.v
Labels: kind: documentation, part: ltac2

#20425 Coercionops remove useless whd betaiota after hnf_constr0
  pretyping/coercionops.ml
Labels: kind: cleanup, part: coercions

#20423 Explicitly pass the safe env to Namegen.next_global_ident_away.
  dev/ci/user-overlays/20423-ppedrot-namegen-no-global.sh
  engine/namegen.ml
  engine/namegen.mli
  plugins/funind/recdef.ml
  plugins/ring/ring.ml
  tactics/abstract.ml
  tactics/eqschemes.ml
  vernac/classes.ml
  vernac/declare.ml
  vernac/vernacentries.ml
Labels: kind: cleanup

#20419 Update various URLs after the renaming
  CONTRIBUTING.md
  INSTALL.md
  README.md
  coq-core.opam
  coq-doc.opam
  coq.opam
  coqide-server.opam
  default.nix
  dev/ci/README-developers.md
  dev/ci/README-users.md
  dev/tools/generate-release-changelog.sh
  dev/tools/make-changelog.sh
  doc/README.md
  doc/plugin_tutorial/README.md
  doc/sphinx/introduction.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/practical-tools/utilities.rst
  doc/sphinx/using/libraries/index.rst
  doc/sphinx/using/tools/coqdoc.rst
  doc/sphinx/using/tools/index.rst
  dune-project
  ide/rocqide/FAQ
  interp/notation.ml
  rocq-core.opam
  rocq-devtools.opam
  rocq-prover.opam
  rocq-runtime.opam
  rocqide.opam
  tactics/tactics.ml
  test-suite/coqdoc/Context.html.out
  test-suite/coqdoc/Record.html.out
  test-suite/coqdoc/binder.html.out
  test-suite/coqdoc/bug11194.html.out
  test-suite/coqdoc/bug11353.html.out
  test-suite/coqdoc/bug12742.html.out
  test-suite/coqdoc/bug5648.html.out
  test-suite/coqdoc/bug5700.html.out
  test-suite/coqdoc/details.html.out
  test-suite/coqdoc/links.html.out
  test-suite/coqdoc/multiple_links.html.out
  test-suite/coqdoc/typeclasses.html.out
  test-suite/coqdoc/verbatim.html.out
  test-suite/misc/coqdoc-options/15933.html.out
  test-suite/misc/coqdoc-options/_CoqProject
  test-suite/output/ltac2_anomaly_backtrace.out
  tools/configure/cmdArgs.ml
Labels: kind: documentation

#20391 Ltac1: importing a definition does not undo its mutations
  dev/ci/user-overlays/20391-SkySkimmer-ltac1-no-unredef.sh
  doc/changelog/05-Ltac-language/20391-ltac1-no-unredef.rst
  plugins/ltac/tacenv.ml
Labels: kind: fix, part: ltac

#20376 Improve Boot.Env API and callers
  boot/env.ml
  boot/env.mli
  checker/coqchk_main.ml
  doc/sphinx/practical-tools/coq-commands.rst
  kernel/nativelib.ml
  kernel/nativelib.mli
  plugins/micromega/coq_micromega.ml
  sysinit/coqinit.ml
  tools/coqdep/lib/args.ml
  tools/coqdep/lib/args.mli
  tools/coqdep/lib/common.ml
  tools/coqdep/lib/common.mli
  tools/coqdep/lib/rocqdep_main.ml
  tools/coqdoc/cmdArgs.ml
  tools/coqdoc/common.ml
  tools/coqdoc/common.mli
  tools/coqdoc/rocqdoc_main.ml
  tools/dune_rule_gen/dep_info.ml
  tools/rocqmakefile.ml
  topbin/rocqnative.ml
  topbin/rocqshim.ml
  toplevel/coqloop.ml
  toplevel/coqtop.ml
Labels: kind: cleanup, kind: enhancement, part: build, kind: internal

#14937 Do not register abstracted subproofs in the nametab
  doc/changelog/04-tactics/14937-abstract-no-nametab.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  interp/constrextern.ml
  interp/dumpglob.ml
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  proofs/proof.ml
  tactics/abstract.ml
  test-suite/output-coqtop/bug_16462.out
  test-suite/output-coqtop/bug_16745.out
  vernac/declare.ml
Labels: kind: cleanup

#20355 Add #[refine] attribute for Definition
  dev/ci/user-overlays/20355-Yann-Leray-refine-definition.sh
  doc/changelog/08-vernac-commands-and-options/20355-refine-definition.rst
  doc/sphinx/language/core/definitions.rst
  plugins/funind/gen_principle.ml
  test-suite/success/refine_definition.v
  vernac/comDefinition.ml
  vernac/comDefinition.mli
  vernac/comFixpoint.ml
  vernac/comFixpoint.mli
  vernac/declare.ml
  vernac/declare.mli
  vernac/vernac_classifier.ml
  vernac/vernacentries.ml
Labels: kind: enhancement

#20424 create_overlays: set git commit template message
  dev/tools/create_overlays.sh
Labels: kind: infrastructure

#20443 Fix dev/db
  dev/db
Labels: kind: infrastructure

#20430 Enable use of (open_)lconstr from Ltac2.
  doc/changelog/06-Ltac2-language/20430-lconstr_in_ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  plugins/ltac2/tac2core.ml
  test-suite/ltac2/lconstr.v
Labels: kind: enhancement

#20414 Nametabs always use full_path for "user_name"
  library/nametab.ml
  library/nametab.mli
  plugins/ltac/tacenv.ml
  plugins/ltac2/tac2env.ml
Labels: kind: cleanup

#20454 Fix missed ltac_expr -> generic_tactic in doc of Proof with
  doc/sphinx/proofs/automatic-tactics/auto.rst
Labels: kind: documentation

#20439 ci-quickchick don't use dune build -p
  dev/ci/scripts/ci-quickchick.sh
  dev/ci/scripts/ci-quickchick_test.sh
Labels: kind: infrastructure

#20447 Fix over-eager renaming in rocq makefile doc
  doc/sphinx/practical-tools/utilities.rst
Labels: kind: documentation

#20437 Fix bad interaction between dune and local opam directory switches.
  doc/changelog/12-infrastructure-and-dependencies/20437-fix_20422.rst
  tools/coqdep/lib/fl.ml
Labels: kind: fix

#20431 Ltac1 also print redefinition info when redefined in current module
  library/nametab.ml
  library/nametab.mli
  plugins/ltac/tacentries.ml
Labels: kind: user messages, part: ltac

#20434 Additional explanations on backtracking in Ltac2
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation

#20387 Compile Ltac2 with -noinit
  doc/changelog/06-Ltac2-language/20387-ltac2-noinit.rst
  dune
  plugins/ltac2/tac2stdlib.ml
  test-suite/ltac2/noinit.v
  theories/Init/Ltac.v
  theories/Init/Tactics.v
  tools/dune_rule_gen/coq_rules.ml
  tools/dune_rule_gen/coq_rules.mli
  tools/dune_rule_gen/gen_rules.ml
  user-contrib/Ltac2/Init.v
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
  user-contrib/Ltac2/dune.disabled
Labels: kind: enhancement, part: ltac2

#20466 Update DOI to point to new Zenodo record for the Rocq Prover.
  README.md
Labels: kind: documentation

#20461 Ltac2 Array.make_matrix use make instead of constant init
  user-contrib/Ltac2/Array.v
Labels: kind: cleanup

#20462 Ltac2 List.enumerate implementation use mapi instead of combine seq
  user-contrib/Ltac2/List.v
Labels: kind: cleanup

#20449 Minor cleanups and fixes around deprecation and user warnings
  interp/notation.ml
  lib/deprecation.ml
  lib/deprecation.mli
  lib/userWarn.ml
  test-suite/output/Deprecation.out
  test-suite/output/Deprecation.v
  vernac/attributes.ml
  vernac/metasyntax.ml
Labels: kind: cleanup

#20471 Bench: mathcomp package are renamed
  dev/bench/bench.sh
Labels: kind: infrastructure

#20472 Clean some bits of code related to side-effects
  dev/ci/user-overlays/20472-ppedrot-abstract-clean-seff.sh
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  plugins/ltac2/tac2tactics.ml
  plugins/ring/ring.ml
  plugins/ssr/ssrcommon.ml
  proofs/proof.ml
  proofs/proof.mli
  proofs/refine.ml
  tactics/class_tactics.ml
  tactics/ind_tables.ml
  tactics/ind_tables.mli
  vernac/declare.ml
Labels: kind: cleanup

#20442 Bump version of Sphinx in edge CI image
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
Labels: kind: infrastructure

#20463 Ltac2 List.(inclusive_)range reuse seq instead of doing custom recursion
  user-contrib/Ltac2/List.v
Labels: kind: cleanup

#20451 Fix code for calling csdpcert
  plugins/micromega/coq_micromega.ml
Labels: kind: fix

#20433 Rename dune package "coq-doc" -> "rocq-doc"
  doc/README.md
  doc/corelib/dune
  doc/dune
  doc/index.mld
  dune-project
  rocq-doc.opam
Labels: kind: infrastructure

#20478 backport ssrfun.v before release of MathComp 2.4.0
  dev/ci/user-overlays/20478-affeldt-aist-mathcomp-backport.sh
  doc/changelog/07-ssreflect/20478-mathcomp_backport_20250407_added.rst
  doc/changelog/07-ssreflect/20478-mathcomp_backport_20250407_changed.rst
  doc/changelog/07-ssreflect/20478-mathcomp_backport_20250407_deprecated.rst
  doc/changelog/07-ssreflect/20478-mathcomp_backport_20250407_removed.rst
  theories/ssr/ssrbool.v
  theories/ssr/ssrfun.v
Labels: part: ssreflect, kind: enhancement

#20484 Enable/Disable Notation only take effect in shallow import
  doc/changelog/03-notations/20484-enable-disable-nota-fix-locality.rst
  test-suite/output/Notations5.out
  test-suite/output/Notations5.v
  vernac/metasyntax.ml
Labels: kind: fix, part: modules, part: notations

#20485 Improve coqdoc help message
  tools/coqdoc/cmdArgs.ml
Labels: kind: user messages, part: coqdoc

#20483 Libobject.simple_open only open when depth = 1
  dev/ci/user-overlays/20483-SkySkimmer-simple-open-filtered-open.sh
  interp/abbreviation.ml
  interp/notation.ml
  library/goptions.ml
  library/libobject.ml
  library/libobject.mli
  plugins/ltac/tacentries.ml
  plugins/ltac/tacenv.ml
  plugins/ltac2/tac2entries.ml
  tactics/hints.ml
  vernac/canonical.ml
  vernac/classes.ml
  vernac/comCoercion.ml
  vernac/declare.ml
  vernac/declareInd.ml
  vernac/declareUniv.ml
  vernac/metasyntax.ml
  vernac/tactic_option.ml
Labels: kind: cleanup, kind: internal

#20465 test suite makefile: remove unused TEST_SUITE_CONFIG_PATH, reorder code
  test-suite/Makefile
Labels: kind: cleanup, kind: infrastructure

#20481 [changelog] Rename 11-standard-library -> 11-corelib
  doc/changelog/11-corelib/00000-title.rst
  doc/changelog/11-standard-library/00000-title.rst
Labels: kind: documentation

#20497 Add test for exfalso on sort polymorphic goal
  test-suite/bugs/bug_20177_1.v
Labels: kind: infrastructure

#20407 Rename ci-metacoq -> ci-metarocq
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/scripts/ci-metarocq.sh
Labels: kind: infrastructure

#20507 Change outdated comment in kernel/vars.ml
  kernel/vars.ml
Labels: kind: internal

#20458 Ltac2 improve letin printing
  plugins/ltac2/tac2print.ml
  test-suite/output/PrintGenarg.out
  test-suite/output/ltac2_check_globalize.out
  test-suite/output/ltac2_typed_notations.out
Labels: kind: user messages, part: ltac2

#20504 Stop saying "scope" when talking about ltac2 syntactic classes
  doc/changelog/06-Ltac2-language/20504-ltac2-scope-entry-Changed.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/using/libraries/writing.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  plugins/ltac2/tac2qexpr.mli
Labels: kind: documentation, kind: user messages

#20505 doc_grammar report error location for "can't find in edit"
  coqpp/coqpp_parse.mly
  doc/tools/docgram/doc_grammar.ml
Labels: kind: infrastructure

#20486 Classes.open_instance does nothing when superglobal
  doc/changelog/04-tactics/20486-tc-locality.rst
  test-suite/output/global_inst.out
  test-suite/output/global_inst.v
  test-suite/success/global_inst.v
  vernac/classes.ml
Labels: kind: cleanup

#20459 Add documentation comments to user-contrib/Ltac2/List.v
  user-contrib/Ltac2/List.v
Labels: kind: documentation, part: ltac2

#20522 Combining -boot and -coqlib is a warning, not an error.
  boot/env.ml
  boot/env.mli
  checker/coqchk_main.ml
  lib/cWarnings.ml
  lib/cWarnings.mli
  sysinit/coqinit.ml
  tools/coqdep/lib/common.ml
  topbin/rocqnative.ml
  topbin/rocqshim.ml
Labels: kind: usability

#20468 Ltac2, documentation for Constr.Unsafe and Control
  user-contrib/Ltac2/Constr.v
  user-contrib/Ltac2/Control.v
Labels: kind: documentation, part: ltac2

#20516 Ltac2 Set: only take effect in shallow imports
  dev/ci/user-overlays/20516-SkySkimmer-ltac2-set-export.sh
  doc/changelog/06-Ltac2-language/20516-ltac2-set-export-Changed.rst
  plugins/ltac2/tac2entries.ml
  test-suite/ltac2/rebind.v
Labels: kind: enhancement, part: ltac2

#20520 Slightly improve Print Grammar vernac
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  vernac/g_vernac.mlg
  vernac/metasyntax.ml
Labels: kind: cleanup, part: parser

#20524 Ignore COQPATH if it is equal to ROCQPATH
  lib/envars.ml
Labels: kind: user messages

#20531 Update style guide
  dev/doc/style.md
Labels: kind: documentation

#20530 update style guide link
  CONTRIBUTING.md
Labels: kind: documentation

#20527 Doc: add rules for inductive universes
  doc/sphinx/language/core/inductive.rst
Labels: kind: documentation

#20521 Improve README for overlays
  dev/ci/user-overlays/README.md
Labels: kind: meta

#20496 Use record instead of tuple for UVars.bound_names
  dev/ci/user-overlays/20496-LeoAlexElouan-clarify-bound-names.sh
  dev/top_printers.ml
  engine/uState.ml
  kernel/cPrimitives.ml
  kernel/indTyping.ml
  kernel/inferCumulativity.ml
  kernel/uVars.ml
  kernel/uVars.mli
  printing/printer.ml
  test-suite/misc/poly-capture-global-univs/src/evilImpl.ml
  vernac/declare.ml
  vernac/declareUniv.ml
Labels: kind: internal

#19811 Fix primitive projection handling for `setoid_rewrite`
  doc/changelog/04-tactics/19811-fix-setoid-proj-Changed.rst
  tactics/rewrite.ml
  test-suite/success/setoid_rewrite_proj.v
Labels: kind: enhancement

#20535 [RocqIDE] Guard a potentially unbounded loop in tooltip printing.
  ide/rocqide/rocqOps.ml
Labels: kind: fix, part: RocqIDE

#20540 Print Grammar Full also prints unreachable entries
  clib/polyMap.ml
  clib/polyMap.mli
  doc/sphinx/user-extensions/syntax-extensions.rst
  gramlib/grammar.ml
  gramlib/grammar.mli
  parsing/procq.ml
  vernac/metasyntax.ml
Labels: kind: user messages, part: parser

#20545 Use hypinfo record systematically in Rewrite.
  tactics/rewrite.ml
Labels: kind: cleanup

#20427 Add format combinator Pp.fmt
  dev/ci/user-overlays/20427-SkySkimmer-pp-strf.sh
  ide/rocqide/ideutils.ml
  ide/rocqide/protocol/xmlprotocol.ml
  lib/pp.ml
  lib/pp.mli
  vernac/himsg.ml
Labels: kind: internal

#20510 Simplify low level custom entry system
  parsing/procq.ml
  parsing/procq.mli
  vernac/egramrocq.ml
Labels: kind: cleanup, part: parser

#20476 Set Rewrite Output Constraints flag
  doc/changelog/04-tactics/20476-generalized-rewrite-debug-opt.rst
  doc/sphinx/addendum/generalized-rewriting.rst
  tactics/rewrite.ml
Labels: kind: feature

#20547 Ltac2 : Add empty message
  doc/changelog/06-Ltac2-language/20547-ltac2-message-empty.rst
  plugins/ltac2/tac2core.ml
  test-suite/ltac2/printf.v
  user-contrib/Ltac2/Message.v
Labels: kind: enhancement, part: ltac2

#20553 Tweak the output of the test-suite logs.
  test-suite/Makefile
  test-suite/README.md
  test-suite/unit-tests/src/utest.ml
Labels: kind: infrastructure

#20551 Remove the notation for "only" in Ltac2.
  doc/changelog/04-tactics/20197-ltac2-rename.rst
  test-suite/ltac2/std_tactics.v
  user-contrib/Ltac2/Notations.v
Labels: kind: cleanup

#20558 Add missing proof delimiters in Ltac2 tests.
  test-suite/ltac2/std_tactics.v
Labels: kind: cleanup

#20557 Fix test suite non-quiet mode
  test-suite/Makefile
Labels: kind: infrastructure

#20563 CI: fix jasmin (now depends on itree)
  .gitlab-ci.yml
  Makefile.ci
Labels: kind: infrastructure

#20499 Delete coq, rocq-prover packages, add rocq-test-suite package
  .gitlab-ci.yml
  coq.opam
  coq.opam.template
  dev/ci/platform/coq-pf-03-build.bat
  dune
  dune-project
  kernel/dune
  rocq-test-suite.opam
  rocq-test-suite.opam.template
  test-suite/coq-makefile/coqdep-attribute/run.sh
  test-suite/coq-makefile/coqdoc1/run.sh
  test-suite/coq-makefile/coqdoc2/run.sh
  test-suite/coq-makefile/findlib-local/run.sh
  test-suite/coq-makefile/mlpack1/run.sh
  test-suite/coq-makefile/mlpack2/run.sh
  test-suite/coq-makefile/multiroot/run.sh
  test-suite/coq-makefile/plugin1/run.sh
  test-suite/coq-makefile/plugin2/run.sh
  test-suite/coq-makefile/plugin3/run.sh
  test-suite/coq-makefile/uninstall1/run.sh
  test-suite/coq-makefile/uninstall2/run.sh
  test-suite/misc/changelog.sh
  test-suite/misc/comment-lexing.sh
  test-suite/misc/coq_environment.sh
  test-suite/tools/coq_config_to_make.ml
Labels: kind: infrastructure

#20517 Ltac2 print explanation when rejecting a definition due to value restriction
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2intern.ml
  plugins/ltac2/tac2intern.mli
Labels: kind: user messages

#20559 Add raw printers for Ltac2 commands
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  plugins/ltac2/tac2print.ml
  plugins/ltac2/tac2print.mli
  test-suite/output/ltac2_check_globalize.out
  test-suite/output/ltac2_typed_notations.out
  vernac/ppvernac.mli
Labels: kind: user messages

#20565 lib.ml reduce dependence on Global
  interp/impargs.ml
  interp/notation.ml
  library/global.ml
  library/global.mli
  library/lib.ml
  library/lib.mli
  pretyping/arguments_renaming.ml
  pretyping/coercionops.ml
  pretyping/keys.ml
  pretyping/reductionops.ml
  tactics/hints.ml
  tactics/redexpr.ml
  vernac/canonical.ml
  vernac/classes.ml
  vernac/comArguments.ml
  vernac/comCoercion.ml
  vernac/declareInd.ml
Labels: kind: cleanup

#20548 test suite merge `distclean` target (rm .aux) into `clean`
  test-suite/Makefile
Labels: kind: cleanup

#20571 Test suite include a version of uip_loop not relying on Prop
  test-suite/failure/uip_loop.v
Labels: kind: internal

#20572 Prevent an exponential behaviour in lambda-erasure in extraction.
  plugins/extraction/mlutil.ml
  test-suite/complexity/bug_17448.v
Labels: kind: fix, kind: performance, part: extraction

#20562 Less global state in extraction
  plugins/extraction/common.ml
  plugins/extraction/common.mli
  plugins/extraction/extract_env.ml
  plugins/extraction/extract_env.mli
  plugins/extraction/extraction.ml
  plugins/extraction/extraction.mli
  plugins/extraction/haskell.ml
  plugins/extraction/haskell.mli
  plugins/extraction/json.ml
  plugins/extraction/json.mli
  plugins/extraction/miniml.ml
  plugins/extraction/miniml.mli
  plugins/extraction/mlutil.ml
  plugins/extraction/mlutil.mli
  plugins/extraction/modutil.ml
  plugins/extraction/modutil.mli
  plugins/extraction/ocaml.ml
  plugins/extraction/ocaml.mli
  plugins/extraction/scheme.ml
  plugins/extraction/scheme.mli
  plugins/extraction/table.ml
  plugins/extraction/table.mli
Labels: kind: cleanup

#20552 Improve Tac2ffi.fun1 combinator and reduce direct `closure` use when declaring externals
  dev/ci/user-overlays/20552-SkySkimmer-tac2fun1.sh
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ltac2_ltac1/tac2stdlib_ltac1.ml
Labels: kind: cleanup, part: ltac2

#20475 Exposes functionality for inductive types in Ltac2
  doc/changelog/06-Ltac2-language/20475-ltac2_expose_inductive.rst
  plugins/ltac2/tac2core.ml
  test-suite/ltac2/ind.v
  user-contrib/Ltac2/Constr.v
  user-contrib/Ltac2/Ind.v
Labels: kind: feature
