Repository rocq-prover/rocq, pull requests merged in 2025-02, with the labels that each got.

#20180 Issue template: suggest mentioning which interface gets the bug
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: kind: infrastructure

#19851 CClosure: absorb arguments in FConstruct
  kernel/cClosure.ml
  kernel/cClosure.mli
  kernel/conversion.ml
  kernel/inferCumulativity.ml
Labels: kind: performance

#20132 Evd.new_pure_evar relevance argument is required instead of guessing Relevant
  dev/ci/user-overlays/20132-SkySkimmer-evar-relevance.sh
  engine/evarutil.mli
  engine/evd.ml
  engine/evd.mli
  engine/proofview.ml
  engine/proofview.mli
  kernel/cClosure.ml
  plugins/ltac2/tac2core.ml
  plugins/ssr/ssrcommon.ml
  plugins/ssrmatching/ssrmatching.ml
  pretyping/evarconv.ml
  pretyping/evarsolve.ml
  pretyping/globEnv.ml
  pretyping/globEnv.mli
  proofs/clenv.ml
  tactics/eClause.ml
  tactics/tactics.ml
  test-suite/bugs/bug_20131.v
Labels: kind: fix

#20160 Fix `Instance := {}` on class declared with Existing Class + preliminary cleanups
  engine/eConstr.ml
  engine/eConstr.mli
  pretyping/typeclasses.ml
  pretyping/typeclasses.mli
  test-suite/bugs/bug_20092.v
  vernac/classes.ml
  vernac/classes.mli
  vernac/record.ml
Labels: kind: fix

#20165 Export a view type over Environ.env for Serlib and abstract env away.
  checker/coqchk_main.ml
  dev/ci/user-overlays/20165-ppedrot-environ-view-serlib.sh
  kernel/cClosure.ml
  kernel/conversion.ml
  kernel/environ.ml
  kernel/environ.mli
  kernel/inductive.ml
  kernel/primred.ml
  kernel/safe_typing.ml
  kernel/typeops.ml
  pretyping/evarconv.ml
  pretyping/evardefine.ml
  pretyping/pretyping.ml
  pretyping/reductionops.ml
Labels: kind: cleanup

#20176 Stop relying on a global visit state in extraction.
  plugins/extraction/extract_env.ml
Labels: kind: cleanup

#20169 Move timelog2html implementation to rocq-devtools package
  .github/workflows/ci-macos.yml
  .gitlab-ci.yml
  Makefile
  dev/bench/bench.sh
  dev/bench/dune
  dev/bench/rocqtimelog2html.ml
  dev/bench/rocqtimelog2html.mli
  dev/bench/timelog2html.ml
  dev/bench/timelog2html.mli
  doc/changelog/09-cli-tools/20169-devtools.rst
  doc/sphinx/practical-tools/utilities.rst
  dune-project
  rocq-devtools.opam
  test-suite/dune
  topbin/dune
  topbin/rocq.ml
  topbin/rocqshim.ml
Labels: kind: infrastructure

#20184 Add Ltac2.Option.{is_some,is_none,compare,join,iter}
  doc/changelog/06-Ltac2-language/20184-ltac2-option-is-some-none.rst
  user-contrib/Ltac2/Option.v
Labels: kind: enhancement, part: ltac2

#20189 [CI] Fix stdlib-doc
  .gitlab-ci.yml
  dev/ci/docker/old_ubuntu_lts/Dockerfile
Labels: kind: infrastructure

#20167 Remove dead API in Tok.
  parsing/tok.ml
  parsing/tok.mli
  printing/proof_diffs.ml
Labels: kind: cleanup

#20192 Reduce the reliance on CanOrd in upper layers
  interp/notation.ml
  plugins/firstorder/formula.ml
  pretyping/cbv.ml
  pretyping/evaluable.ml
  pretyping/evaluable.mli
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/reductionops.ml
  tactics/cbn.ml
  tactics/class_tactics.ml
  tactics/elimschemes.ml
  tactics/hints.ml
  tactics/hints.mli
  tactics/hipattern.ml
  vernac/comRewriteRule.ml
Labels: kind: cleanup

#20194 [9.0] [CI] Fix stdlib-doc
  .gitlab-ci.yml
  dev/ci/docker/old_ubuntu_lts/Dockerfile
Labels: kind: infrastructure

#20198 fix bench (coq-bignums -> rocq-bignums)
  dev/bench/bench.sh
Labels: kind: infrastructure

#20196 Collapse environment fields and remove dead API.
  kernel/environ.ml
  kernel/environ.mli
Labels: kind: cleanup

#20178 Keep qvar in template poly entry and declarations
  checker/checkInductive.ml
  checker/values.ml
  dev/ci/user-overlays/20178-SkySkimmer-template-entry-qvar.sh
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  engine/univSubst.ml
  engine/univSubst.mli
  kernel/declarations.mli
  kernel/declareops.ml
  kernel/discharge.ml
  kernel/entries.mli
  kernel/environ.ml
  kernel/environ.mli
  kernel/indTyping.ml
  kernel/indTyping.mli
  kernel/indtypes.ml
  kernel/inductive.ml
  kernel/inductive.mli
  kernel/safe_typing.ml
  kernel/typeops.ml
  kernel/uGraph.ml
  kernel/uGraph.mli
  kernel/uVars.ml
  kernel/uVars.mli
  kernel/univ.ml
  kernel/univ.mli
  pretyping/evarsolve.ml
  pretyping/indrec.ml
  pretyping/inductiveops.ml
  pretyping/inductiveops.mli
  pretyping/pretyping.ml
  pretyping/retyping.ml
  pretyping/retyping.mli
  pretyping/templateArity.ml
  pretyping/templateArity.mli
  pretyping/typing.ml
  proofs/clenv.ml
  test-suite/success/Template.v
  vernac/auto_ind_decl.ml
  vernac/comInductive.ml
  vernac/comInductive.mli
  vernac/declareInd.ml
  vernac/declareInd.mli
  vernac/prettyp.ml
  vernac/record.ml
  vernac/record.mli
Labels: kind: redesign

#20202 Add changelog for #19160
  doc/sphinx/changes.rst
Labels: kind: documentation

#20190 Handle queries in rocqshim when possible
  boot/env.ml
  boot/env.mli
  boot/usage.ml
  boot/usage.mli
  boot/util.ml
  boot/util.mli
  dev/ci/user-overlays/20190-SkySkimmer-rocq-queries.sh
  kernel/nativelib.ml
  lib/envars.ml
  lib/envars.mli
  plugins/extraction/extract_env.ml
  sysinit/coqargs.ml
  sysinit/coqargs.mli
  sysinit/coqinit.ml
  sysinit/dune
  tools/rocqmakefile.ml
  topbin/rocq.ml
  topbin/rocqshim.ml
  topbin/rocqshim.mli
Labels: kind: fix, kind: cleanup, part: build

#20072 [zify] Protect clear_body with a try
  plugins/micromega/zify.ml
Labels: kind: fix, part: micromega

#20183 Use sets instead of ordered lists in hint stored data.
  tactics/hints.ml
Labels: kind: performance

#20213 Fix rocq dep issue with empty string arguments
  test-suite/coq-makefile/coqdep-attribute/b.v
  tools/coqdep/lib/lexer.mll
Labels: kind: fix, part: coqdep

#20208 coqrst: replace `extra` by `extra-foo` telling what it depends on
  dev/ci/ci-refman.sh
  doc/sphinx/README.rst
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/ring.rst
  doc/sphinx/language/core/basic.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  doc/sphinx/using/libraries/funind.rst
  doc/tools/coqrst/coqdomain.py
Labels: kind: documentation

#20207 Ltac2 external check that the name is not already used
  plugins/ltac2/tac2entries.ml
  user-contrib/Ltac2/Std.v
Labels: kind: fix, part: ltac2

#20201 Abstract the datatype of maps of hint modes.
  dev/ci/user-overlays/20201-ppedrot-hint-opaque-modes.sh
  tactics/class_tactics.ml
  tactics/class_tactics.mli
  tactics/hints.ml
  tactics/hints.mli
Labels: kind: cleanup

#20214 bench export ROCQ_PROFILE_COMPONENTS instead of COQ_...
  dev/bench/bench.sh
Labels: kind: cleanup

#20218 Let binder (x:T|P) not depend on the implicit status of sig.
  doc/sphinx/language/core/assumptions.rst
  parsing/g_constr.mlg
Labels: kind: enhancement

#18816 rocq timelog2html: handle json profile files
  .github/workflows/ci-macos.yml
  .gitlab-ci.yml
  default.nix
  dev/bench/bench.sh
  dev/bench/dune
  dev/bench/profparser.ml
  dev/bench/profparser.mli
  dev/bench/timelog2html.ml
  dev/ci/docker/old_ubuntu_lts/Dockerfile
  dune-project
  rocq-devtools.opam
Labels: kind: infrastructure, kind: enhancement

#20227 Evd.is_maybe_typeclass_hook uses econstr
  engine/evd.mli
  pretyping/typeclasses.ml
Labels: kind: cleanup

#20233 Stop using deprecated typing.io in python code
  doc/tools/coqrst/notations/TacticNotationsLexer.py
  doc/tools/coqrst/notations/TacticNotationsParser.py
Labels: kind: documentation

#20219 Add Evd.set_eq_qualities and set_above_prop
  engine/evd.ml
  engine/evd.mli
  pretyping/pretyping.ml
  vernac/comInductive.ml
Labels: kind: cleanup

#20221 Fix falsely general type variables in Ltac2.List
  user-contrib/Ltac2/List.v
Labels: kind: fix

#20237 ci: bump sel to 0.6.0
  .gitlab-ci.yml
  dev/ci/docker/edge_ubuntu/Dockerfile
Labels: kind: infrastructure

#20238 Update command in ssreflect.SsrSyntax
  theories/ssr/ssreflect.v
Labels: kind: cleanup, part: ssreflect

#20235 Print/About print arguments with DelimOnlyTmpScope
  dev/ci/user-overlays/20235-SkySkimmer-print-args-delim-tmp.sh
  test-suite/output/Arguments.out
  test-suite/output/ArgumentsScope.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/Cases.out
  test-suite/output/DebugRelevances.out
  test-suite/output/Implicit.out
  test-suite/output/Inductive.out
  test-suite/output/InductiveMainName.out
  test-suite/output/InitSyntax.out
  test-suite/output/Notations3.out
  test-suite/output/PatternsInBinders.out
  test-suite/output/PrintInfos.out
  test-suite/output/PrintMatch.out
  test-suite/output/PrintSecDeps.out
  test-suite/output/PrintingParentheses.out
  test-suite/output/Projections.out
  test-suite/output/Qf_stdlib.out
  test-suite/output/RecordProjParameter.out
  test-suite/output/SchemeNames.out
  test-suite/output/UnivBinders.out
  test-suite/output/Utf8Impargs.out
  test-suite/output/bug_14815.out
  test-suite/output/bug_15020.out
  test-suite/output/bug_15221.out
  test-suite/output/bug_3810.out
  test-suite/output/wish_18097.out
  vernac/prettyp.ml
Labels: kind: fix, kind: user messages

#20230 Delay getenv calls
  checker/coqchk_main.ml
  dev/ci/user-overlays/20230-SkySkimmer-delay-coq-env.sh
  lib/envars.ml
  lib/envars.mli
  lib/newProfile.ml
  sysinit/coqloadpath.ml
  tools/coqdep/lib/rocqdep_main.ml
  topbin/rocqnative.ml
Labels: kind: fix

#20250 CI: Fix elpi
  dev/ci/ci-elpi.sh
Labels: kind: infrastructure

#20239 ssrmatching cleanups
  plugins/ssrmatching/ssrmatching.ml
Labels: kind: cleanup

#20255 Fix bench false positive detection of failed dependency
  dev/bench/bench.sh
Labels: kind: infrastructure

#20259 CI: Lean importer repo moved to coq community
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure, part: CI

#20236 ROCQ_PROFILE_COMPONENTS handle negated list
  doc/sphinx/practical-tools/coq-commands.rst
  lib/newProfile.ml
Labels: kind: internal

#20234 Print/About print binding instances in binder style
  printing/printer.ml
  printing/printer.mli
  test-suite/output/DebugRelevances.out
  test-suite/output/Inductive.out
  vernac/himsg.ml
  vernac/prettyp.ml
  vernac/printmod.ml
Labels: kind: user messages

#20262 Add local qualities to env when Check calls kernel typechecking
  kernel/environ.ml
  kernel/environ.mli
  test-suite/bugs/bug_20261.v
  vernac/vernacentries.ml
Labels: kind: fix

#20225 recheck_against don't generate spurious template constraints
  pretyping/typing.ml
  test-suite/bugs/bug_20224.v
  test-suite/output/bug_13266.out
Labels: kind: fix

#20260 Print rigid qualities in sorts even if print universes is off
  engine/evd.ml
  engine/evd.mli
  engine/uState.ml
  engine/uState.mli
  interp/constrextern.ml
  pretyping/detyping.ml
  printing/ppconstr.ml
  test-suite/output/SortQuality.out
  test-suite/output/SortQuality.v
Labels: kind: user messages

#20248 check_evar_instance produce nicer error when retyping fails
  pretyping/evarsolve.ml
  pretyping/evarsolve.mli
  pretyping/pretype_errors.ml
  pretyping/pretype_errors.mli
  test-suite/output/IllTypedInstance.out
  test-suite/output/IllTypedInstance.v
  vernac/himsg.ml
Labels: kind: user messages

#20223 Cases do not generate spurious template constraints in `in ...`
  pretyping/cases.ml
  test-suite/bugs/bug_20222.v
Labels: kind: fix

#20265 CI: lean importer depends on stdlib
  .gitlab-ci.yml
  Makefile.ci
Labels: kind: infrastructure

#20258 Bench add invariant for rocq-runtime
  dev/bench/bench.sh
Labels: kind: infrastructure

#20263 Fix retyping with missing meta handler while printing
  pretyping/retyping.ml
  test-suite/bugs/bug_20251.v
Labels: kind: fix

#20267 bench: use rocq-elpi
  dev/bench/bench.sh
Labels: kind: infrastructure

#20244 Rely on explicit printing of pairs of terms in some module errors
  printing/printer.ml
  printing/printer.mli
  test-suite/output/bug_20242.out
  test-suite/output/bug_20242.v
  vernac/himsg.ml
Labels: kind: fix

#20256 Rocqide try to fix incorrect character conversions
  doc/changelog/10-rocqide/20256-ide-charset.rst
  ide/rocqide/ideutils.ml
  ide/rocqide/preferences.ml
Labels: kind: fix, part: CoqIDE

#20273 USe diff -u in doc_gram_verify
  doc/tools/docgram/doc_grammar.ml
Labels: kind: infrastructure

#20274 Constrintern: make var_internalization_data a record type
  interp/constrintern.ml
Labels: kind: cleanup

#20243 Ltac2.Constr.in_context don't drop goal state
  plugins/ltac2/tac2core.ml
Labels: kind: fix, part: ltac2

#20204 Do not rely on name canonization in CS cache.
  pretyping/evarconv.ml
Labels: kind: cleanup

#20266 timelog2html handle gzip compressed profile files
  .github/workflows/ci-macos.yml
  .gitlab-ci.yml
  default.nix
  dev/bench/bench.sh
  dev/bench/dune
  dev/bench/profparser.ml
  dev/bench/timelog2html.ml
  dev/ci/docker/edge_ubuntu/Dockerfile
  dev/ci/docker/old_ubuntu_lts/Dockerfile
  dune-project
  rocq-devtools.opam
Labels: kind: infrastructure, kind: enhancement

#20277 Doc: change Print Universes Subgraph example to avoid coqrst bug
  doc/sphinx/addendum/universe-polymorphism.rst
Labels: kind: documentation

#20276 timelog2html add option to produce machine readable data for render_line_results
  dev/bench/bench.sh
  dev/bench/htmloutput.ml
  dev/bench/htmloutput.mli
  dev/bench/render_line_results.ml
  dev/bench/timelog2html.ml
Labels: kind: infrastructure

#20282 [CI] Fix jasmin
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/ci-basic-overlay.sh
  dev/ci/scripts/ci-algebra_tactics.sh
Labels: kind: infrastructure

#20285 tac2core expose basic fset/fmap functions
  plugins/ltac2/tac2core.mli
Labels: kind: internal

#20291 [CI] Remove Stdlib dep from mathcomp
  .gitlab-ci.yml
  Makefile.ci
  dev/ci/scripts/ci-analysis.sh
  dev/ci/scripts/ci-analysis_stdlib.sh
  dev/ci/scripts/ci-elpi_test.sh
Labels: kind: infrastructure

#20281 Cache the set of metas appearing in firstorder atoms
  plugins/firstorder/formula.ml
  plugins/firstorder/formula.mli
  plugins/firstorder/instances.ml
  plugins/firstorder/unify.ml
  plugins/firstorder/unify.mli
  test-suite/bugs/bug_20281.v
Labels: kind: performance

#20232 refman-pdf deeper table of contents
  doc/sphinx/conf.py
Labels: kind: documentation

#20294 Specif notations use %_type for the second component
  doc/changelog/03-notations/20294-specif-type.rst
  theories/Init/Specif.v
Labels: kind: enhancement

#20292 Fix MSDOS line endings in output test
  test-suite/output/auto_order.out
Labels: kind: cleanup

#20272 Add more precise source locations for many objects and use fallback when needed
  dev/ci/user-overlays/20272-SkySkimmer-def-loc.sh
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  interp/constrintern.ml
  interp/constrintern.mli
  lib/cWarnings.ml
  lib/cWarnings.mli
  plugins/derive/derive.ml
  plugins/derive/derive.mli
  plugins/derive/g_derive.mlg
  plugins/funind/g_indfun.mlg
  plugins/funind/g_indfun.mli
  plugins/funind/gen_principle.ml
  plugins/funind/gen_principle.mli
  plugins/ltac/comRewrite.ml
  plugins/ltac/comRewrite.mli
  plugins/ltac/extratactics.mlg
  plugins/ltac/g_rewrite.mlg
  plugins/ltac/leminv.ml
  plugins/ltac/leminv.mli
  test-suite/output/Arguments.out
  test-suite/output/ArgumentsScope.out
  test-suite/output/Arguments_renaming.out
  test-suite/output/InductiveMainName.out
  test-suite/output/PrintInfos.out
  test-suite/output/Qf_stdlib.out
  test-suite/output/Record.out
  test-suite/output/RecordProjParameter.out
  test-suite/output/SchemeNames.out
  test-suite/output/UnivBinders.out
  test-suite/output/bug_3810.out
  test-suite/output/wish_18097.out
  vernac/classes.ml
  vernac/classes.mli
  vernac/comAssumption.ml
  vernac/comAssumption.mli
  vernac/comCoercion.ml
  vernac/comCoercion.mli
  vernac/comDefinition.ml
  vernac/comFixpoint.ml
  vernac/comInductive.ml
  vernac/comPrimitive.ml
  vernac/comRewriteRule.ml
  vernac/declare.ml
  vernac/declare.mli
  vernac/indschemes.ml
  vernac/record.ml
  vernac/record.mli
  vernac/vernacentries.ml
Labels: kind: fix, kind: user messages, kind: enhancement

#20284 Debug "unification" add "Starting"/"Leaving" messages
  pretyping/evarconv.ml
Labels: kind: user messages

#20300 [CI] Update point of contact for paramcoq
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#20283 timelog2html include memory info
  dev/bench/benchUtil.ml
  dev/bench/benchUtil.mli
  dev/bench/htmloutput.ml
  dev/bench/htmloutput.mli
  dev/bench/profparser.ml
  dev/bench/profparser.mli
  dev/bench/timelog2html.ml
Labels: kind: infrastructure, kind: enhancement

#20220 Ltac2 Fresh.Free using Nameops.Fresh, add convenience APIs
  doc/changelog/06-Ltac2-language/20220-better-fresh.rst
  engine/namegen.mli
  engine/nameops.ml
  engine/nameops.mli
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  user-contrib/Ltac2/Fresh.v
Labels: kind: enhancement, part: ltac2

#20307 Add some debug printers
  dev/top_printers.dbg
  dev/top_printers.ml
  dev/top_printers.mli
  kernel/safe_typing.ml
  kernel/safe_typing.mli
  proofs/proof.ml
Labels: kind: internal

#20311 Ltac2 expose f_equal directly instead of through ltac1
  plugins/ltac2/tac2stdlib.ml
  plugins/ltac2/tac2tactics.ml
  plugins/ltac2/tac2tactics.mli
  user-contrib/Ltac2/Notations.v
  user-contrib/Ltac2/Std.v
Labels: kind: cleanup

#20306 (v9.0) Use fallback location source more
  test-suite/output/ArgumentsScope.out
  test-suite/output/InductiveMainName.out
  test-suite/output/PrintInfos.out
  test-suite/output/RecordProjParameter.out
  test-suite/output/SchemeNames.out
  test-suite/output/UnivBinders.out
  test-suite/output/bug_3810.out
  vernac/declare.ml
Labels: kind: fix, kind: user messages

#20298 Locate on notation print additional info
  interp/notation.ml
  interp/notation.mli
  interp/notation_ops.ml
  test-suite/output/Notations3.out
  test-suite/output/bug_9180.out
  test-suite/output/locate.out
  test-suite/output/wish_17316.out
Labels: kind: user messages
