Repository rocq-prover/rocq, pull requests merged in 2025-08, with the labels that each got.

#20986 Fix some issues in refman
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
Labels: kind: documentation

#20990 Move Proof Mode and SSR chapter one level up.
  doc/sphinx/index.html.rst
  doc/sphinx/index.latex.rst
  doc/sphinx/introduction.rst
  doc/sphinx/language/core/definitions.rst
  doc/sphinx/language/core/index.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proofs/writing-proofs/index.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/using/libraries/index.rst
Labels: kind: documentation

#20943 Document tactics.mli
  engine/proofview.mli
  engine/termops.ml
  engine/termops.mli
  lib/cAst.ml
  lib/cAst.mli
  lib/loc.ml
  lib/loc.mli
  pretyping/locus.mli
  pretyping/tacred.ml
  proofs/logic.ml
  proofs/logic.mli
  proofs/tactypes.mli
  tactics/tactics.ml
  tactics/tactics.mli
Labels: kind: internal

#21006 doc: five typos fixed in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind: fix, kind: meta

#21007 Fix some issues in refman
  doc/sphinx/addendum/nsatz.rst
  doc/sphinx/proofs/automatic-tactics/auto.rst
  doc/sphinx/proofs/automatic-tactics/logic.rst
Labels: kind: documentation

#21011 Repair refman detecting errors
  doc/sphinx/addendum/rewrite-rules.rst
  doc/sphinx/practical-tools/coq-commands.rst
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
  toplevel/coqloop.ml
Labels: kind: fix, kind: documentation, kind: infrastructure

#21012 Fix some issues in refman
  doc/sphinx/addendum/generalized-rewriting.rst
Labels: kind: documentation

#21014 Handle focusing braces in rocqtop ReST directive
  doc/tools/rocqrst/rocqdomain.py
Labels: kind: infrastructure

#21023 Ltac2: add Option.filter
  doc/changelog/06-Ltac2-language/21023-ltac2-option-filter-Added.rst
  theories/Ltac2/Option.v
Labels: kind: feature

#20561 Ltac2 custom entries
  doc/changelog/06-Ltac2-language/20561-ltac2-custom-entry-Added.rst
  doc/sphinx/proof-engine/ltac2.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/g_ltac2.mli
  plugins/ltac2/tac2entries.ml
  plugins/ltac2/tac2entries.mli
  plugins/ltac2/tac2expr.mli
  plugins/ltac2/tac2extravals.ml
  plugins/ltac2/tac2print.ml
  test-suite/ltac2/custom_entry.v
Labels: kind: feature, part: ltac2

#21032 Fix stale CI job after organization renaming.
  .github/workflows/stale.yml
Labels: kind: fix, kind: infrastructure

#20045 Fix CMorphisms partial_application_tactic to correctly leverage Params instances
  doc/changelog/04-tactics/20045-cmorphisms-params-Fixed.rst
  test-suite/bugs/bug_20044.v
  theories/Corelib/Classes/CMorphisms.v
Labels: kind: fix, part: core library

#21025 Fix some issues in refman
  doc/sphinx/proof-engine/ltac.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation
