Repository rocq-prover/rocq, pull requests merged in 2025-06, with the labels that each got.

#20690 Wrap Lambda nodes in a dummy indirection.
  kernel/genlambda.ml
  kernel/genlambda.mli
  kernel/nativecode.ml
  kernel/nativelambda.ml
  kernel/vmbytegen.ml
  kernel/vmlambda.ml
Labels: kind: cleanup

#20703 Nativecode factorize restarting envs
  kernel/nativecode.ml
Labels: kind: cleanup

#20432 Backport opam file changes from opam repo
  coq-core.opam
  coq-core.opam.template
Labels: kind: infrastructure

#20708 Add check for cofix reduction bug
  test-suite/bugs/bug_20699.v
Labels: kind: infrastructure

#20611 Document undocumented options
  doc/sphinx/addendum/extraction.rst
  doc/sphinx/addendum/micromega.rst
  doc/sphinx/addendum/universe-polymorphism.rst
  doc/sphinx/changes.rst
  doc/sphinx/language/core/primitive.rst
  doc/sphinx/language/extensions/match.rst
  doc/sphinx/proof-engine/ltac.rst
  doc/sphinx/proof-engine/tactics.rst
  doc/sphinx/proofs/automatic-tactics/logic.rst
  doc/sphinx/proofs/writing-proofs/equality.rst
  doc/sphinx/proofs/writing-proofs/proof-mode.rst
  doc/sphinx/using/libraries/funind.rst
  plugins/funind/functional_principles_proofs.ml
  plugins/funind/gen_principle.ml
  plugins/funind/indfun_common.ml
  plugins/funind/indfun_common.mli
Labels: kind: documentation

#20681 Change introduction to Ltac2 refman page
  doc/sphinx/proof-engine/ltac2.rst
Labels: kind: documentation

#20724 Remove mailing list announcements from release process
  dev/doc/release-process.md
Labels: kind: infrastructure

#20715 Cleanup now that we require OCaml >= 4.14.0
  sysinit/coqinit.ml
Labels: kind: cleanup

#20735 Update parallel-proof-processing.rst
  doc/sphinx/addendum/parallel-proof-processing.rst
Labels: kind: documentation

#20732 Fix minor issues in refman
  doc/sphinx/language/core/conversion.rst
  doc/sphinx/language/core/inductive.rst
  doc/sphinx/language/core/records.rst
  doc/sphinx/language/core/variants.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation

#20737 Update extraction.rst
  doc/sphinx/addendum/extraction.rst
Labels: kind: documentation

#20733 Search is possible in open interactive modules
  doc/changelog/08-vernac-commands-and-options/20733-search-in-open-module.rst
  doc/sphinx/proof-engine/vernacular-commands.rst
  library/lib.ml
  library/nametab.ml
  library/nametab.mli
  test-suite/TestSearchOpenMod.out
  test-suite/TestSearchOpenMod.v
  vernac/comSearch.ml
Labels: kind: enhancement, part: vernac, part: search

#20745 Update hidden files
  doc/corelib/hidden-files
  doc/corelib/make-library-index
Labels: kind: cleanup

#20746 Pin CI for 9.1
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure

#20751 Update merge-pr script
  dev/tools/merge-pr.sh
Labels: kind: infrastructure

#20738 Improve "cannot define a fixpoint" error message (with elim constraints)
  dev/ci/user-overlays/20738-SkySkimmer-improve-fixpoint-no-elim.sh
  test-suite/output/FixpointNoElim.out
  test-suite/output/FixpointNoElim.v
  vernac/himsg.ml
Labels: kind: user messages

#20656 Ltac2 add $hyp:id quotation for dynamic hypotheses (where &id is static)
  doc/changelog/06-Ltac2-language/20656-ltac2-hyp-var-Added.rst
  doc/sphinx/proof-engine/ltac2.rst
  engine/evarutil.ml
  engine/evarutil.mli
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2env.ml
  plugins/ltac2/tac2env.mli
  plugins/ltac2/tac2intern.ml
  pretyping/globEnv.ml
  pretyping/globEnv.mli
  test-suite/output/ltac2_hyp_var.out
  test-suite/output/ltac2_hyp_var.v
Labels: kind: enhancement, part: ltac2

#20764 Update CACHEKEY for 9.1
  .gitlab-ci.yml
Labels: kind: infrastructure

#20755 Update rewrite-rules.rst with new sortPoly syntax
  doc/sphinx/addendum/rewrite-rules.rst
Labels: kind: fix, kind: documentation, part: rewrite rules

#20765 Opam files stop pointing at coqdev
  coq-core.opam
  coqide-server.opam
  rocq-core.opam
  rocq-devtools.opam
  rocq-runtime.opam
  rocq-test-suite.opam
  rocqide.opam
Labels: kind: infrastructure

#20768 Update coqdev email in dune-project
  coq-core.opam
  coqide-server.opam
  dune-project
  rocq-core.opam
  rocq-devtools.opam
  rocq-runtime.opam
  rocq-test-suite.opam
  rocqide.opam
Labels: kind: internal

#20753 Document where clauses in record fields
  doc/sphinx/language/core/records.rst
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/orderedGrammar
Labels: kind: documentation, part: records

#20739 UState.QState detect global sorts as rigid
  engine/uState.ml
  test-suite/output/DebugRelevances.out
  test-suite/output/DeclareSort.out
Labels: kind: user messages

#20583 Avoid generating bad template constraints in ssr saturate
  plugins/ssr/ssrcommon.ml
  pretyping/typing.ml
  pretyping/typing.mli
  test-suite/bugs/bug_20582.v
Labels: kind: fix, part: universes

#19759 [refman] Describe the successive compilation steps.
  doc/sphinx/language/extensions/compil-steps.rst
  doc/sphinx/language/extensions/index.rst
Labels: kind: documentation, kind: enhancement

#20769 Fix changelog
  doc/changelog/11-corelib/20107-number-nota.rst
Labels: kind: infrastructure

#20710 Fix #20679: avoid spurious newline in rocqdoc blocks.
  doc/sphinx/_static/notations.css
Labels: kind: documentation, kind: infrastructure

#20687 Update opam version used in bench (2.1.3 -> 2.3.0) + cleanup script parts about job count
  dev/bench/bench.sh
Labels: kind: infrastructure

#20136 Clarify release notes
  dev/doc/release-process.md
Labels: kind: documentation

#20773 Fix broken links in refman
  doc/sphinx/language/core/sections.rst
Labels: kind: documentation

#20761 Fast filter for subterm checking.
  pretyping/unification.ml
Labels: kind: cleanup, kind: performance

#20719 Tweak the native compilation scheme of cofixpoints.
  kernel/nativecode.ml
  kernel/nativeconv.ml
  kernel/nativevalues.ml
  kernel/nativevalues.mli
  pretyping/nativenorm.ml
  test-suite/bugs/bug_20719.v
Labels: kind: cleanup, kind: performance

#20776 Update release documentation after renaming and document how to create views.
  dev/doc/release-process.md
Labels: kind: meta

#20790 variants.rst: correct #20723 with "recursive type"
  doc/sphinx/language/core/variants.rst
Labels: kind: documentation

#20525 Move non-external values out of tac2core.ml
  plugins/ltac2/g_ltac2.mlg
  plugins/ltac2/tac2core.ml
  plugins/ltac2/tac2core.mli
  plugins/ltac2/tac2extravals.ml
  plugins/ltac2/tac2extravals.mli
  plugins/ltac2/tac2ffi.ml
  plugins/ltac2/tac2ffi.mli
  plugins/ltac2/tac2quote.ml
  plugins/ltac2/tac2quote.mli
  plugins/ltac2_ltac1/tac2core_ltac1.ml
Labels: kind: cleanup, part: ltac2

#20774 Fix returning delimiter instead of scope name for About in specific scope
  interp/notation.ml
  test-suite/output/bug_20754.out
  test-suite/output/bug_20754.v
Labels: kind: fix, kind: user messages

#20791 Small code simplification in Hints.add_one.
  tactics/hints.ml
Labels: kind: cleanup

#20669 Update parsing md & mention it in plugin tuto mlg files
  coqpp/coqpp_main.ml
  dev/doc/parsing.md
  doc/plugin_tutorial/tuto0/src/g_tuto0.mlg
  doc/plugin_tutorial/tuto1/src/g_tuto1.mlg
  doc/plugin_tutorial/tuto2/src/g_tuto2.mlg
  doc/plugin_tutorial/tuto3/src/g_tuto3.mlg
Labels: kind: documentation

#20744 coqrst is now rocqrst
  dev/ci/scripts/ci-refman.sh
  doc/dune
  doc/sphinx/README.rst
  doc/sphinx/_static/RocqNotations.ttf
  doc/sphinx/_static/rocqnotations.sty
  doc/sphinx/conf.py
  doc/tools/rocqrst/__init__.py
  doc/tools/rocqrst/checkdeps.py
  doc/tools/rocqrst/notations/Makefile
  doc/tools/rocqrst/notations/RocqNotations.ttf
  doc/tools/rocqrst/notations/TacticNotations.g
  doc/tools/rocqrst/notations/TacticNotations.tokens
  doc/tools/rocqrst/notations/TacticNotationsLexer.py
  doc/tools/rocqrst/notations/TacticNotationsLexer.tokens
  doc/tools/rocqrst/notations/TacticNotationsParser.py
  doc/tools/rocqrst/notations/TacticNotationsVisitor.py
  doc/tools/rocqrst/notations/UbuntuMono-B.ttf
  doc/tools/rocqrst/notations/__init__.py
  doc/tools/rocqrst/notations/fontsupport.py
  doc/tools/rocqrst/notations/html.py
  doc/tools/rocqrst/notations/parsing.py
  doc/tools/rocqrst/notations/plain.py
  doc/tools/rocqrst/notations/regexp.py
  doc/tools/rocqrst/notations/sphinx.py
  doc/tools/rocqrst/repl/__init__.py
  doc/tools/rocqrst/repl/ansicolors.py
  doc/tools/rocqrst/repl/rocqtop.py
  doc/tools/rocqrst/rocqdoc/__init__.py
  doc/tools/rocqrst/rocqdoc/main.py
  doc/tools/rocqrst/rocqdomain.py
Labels: kind: cleanup, kind: infrastructure

#20787 Simplify some uses of pr_global_env
  interp/notation.ml
  plugins/funind/indfun_common.ml
  plugins/ltac/pptactic.ml
  plugins/syntax/number_string.ml
  printing/printer.ml
Labels: kind: cleanup

#20770 Add grammar entry for control flags instead of inlined list parsing
  dev/ci/user-overlays/20770-SkySkimmer-control-flags.sh
  doc/tools/docgram/common.edit_mlg
  doc/tools/docgram/fullGrammar
  test-suite/output/bug_17579.out
  vernac/g_vernac.mlg
  vernac/ppvernac.ml
  vernac/vernacControl.ml
  vernac/vernacexpr.mli
  vernac/vernacprop.ml
Labels: kind: cleanup

#20759 Ltac2 autodetect notation levels + manual fixes
  doc/changelog/06-Ltac2-language/20759-ltac2-nota-levels-Changed.rst
  doc/sphinx/proof-engine/ltac2.rst
  plugins/ltac2/tac2entries.ml
  theories/Ltac2/Notations.v
Labels: kind: fix, part: ltac2

#20803 grammar.ml inline skip_if_empty
  gramlib/grammar.ml
Labels: kind: cleanup, part: parser

#20805 Refman: improve example for `induction in`
  doc/sphinx/proofs/writing-proofs/reasoning-inductives.rst
Labels: kind: documentation

#20806 Refman: Fix CSS classes after #20744
  doc/sphinx/_static/notations.css
Labels: kind: fix, kind: documentation

#20782 Native compute reduce mutability of accus
  kernel/nativevalues.ml
Labels: kind: cleanup, part: native compiler

#20797 Require that a module is already declared before checking subtyping.
  checker/mod_checking.ml
  kernel/mod_typing.ml
  kernel/safe_typing.ml
  kernel/subtyping.ml
  kernel/subtyping.mli
  vernac/declaremods.ml
Labels: kind: cleanup

#20822 [CI] Remove Ralf Jung from perennial contacts
  dev/ci/ci-basic-overlay.sh
Labels: kind: infrastructure, part: CI
