Repository rocq-prover/rocq, pull requests merged in 2025-10, with the labels that each got.

#21148 slightly improve boxing in TC debug output
  tactics/class_tactics.ml
Labels: kind: user messages

#21140 Use user equality in comparison of native values.
  kernel/nativecode.ml
  kernel/nativevalues.ml
  kernel/nativevalues.mli
Labels: kind: cleanup

#21143 Bubble up the imperative registering of constants in proof APIs
  proofs/proof.ml
  stm/stm.ml
  vernac/comTactic.ml
  vernac/declare.ml
  vernac/declare.mli
Labels: kind: cleanup

#21147 Enforcing more invariants in Ind_tables.Locmap module.
  tactics/ind_tables.ml
Labels: kind: cleanup

#21152 Move Optimize Proof and Optimize Heap out of ltac plugin
  doc/tools/docgram/fullGrammar
  plugins/ltac/extratactics.mlg
  vernac/g_proofs.mlg
Labels: kind: enhancement

#21097 Have Evd use einstance everywhere
  dev/ci/user-overlays/21097-Yann-Leray-einstance.sh
  engine/eConstr.mli
  engine/evarutil.ml
  engine/evd.ml
  engine/evd.mli
  interp/primNotations.ml
  plugins/funind/gen_principle.ml
  plugins/ssr/ssrfwd.ml
  pretyping/cases.ml
  pretyping/pretyping.ml
  pretyping/reductionops.ml
  tactics/elimschemes.ml
  tactics/eqschemes.ml
  tactics/tactics.ml
  vernac/indschemes.ml
Labels: kind: cleanup

#21155 Avoid declaring a parsing rule for head_of_constr
  doc/sphinx/addendum/generalized-rewriting.rst
  doc/tools/docgram/fullGrammar
  doc/tools/docgram/orderedGrammar
  plugins/ltac/g_class.mlg
  theories/Corelib/Classes/CMorphisms.v
  theories/Corelib/Classes/Morphisms.v
  theories/Corelib/Init/Ltac.v
Labels: kind: cleanup

#21107 Add warning for non closed level 0 notations
  dev/ci/user-overlays/21107-proux01-test-strict-right-assoc.sh
  doc/changelog/03-notations/21107-test-strict-right-assoc-Added.rst
  doc/changelog/07-ssreflect/21107-test-strict-right-assoc-Changed.rst
  doc/sphinx/language/extensions/arguments-command.rst
  doc/sphinx/proof-engine/ssreflect-proof-language.rst
  doc/sphinx/user-extensions/syntax-extensions.rst
  test-suite/output-coqtop/LookaheadErrors.out
  test-suite/output-coqtop/LookaheadErrors.v
  test-suite/output/Notations.out
  test-suite/output/Notations.v
  test-suite/output/Notations2.v
  test-suite/output/Notations3.v
  test-suite/output/Notations4.out
  test-suite/output/Notations4.v
  test-suite/output/Notations5.v
  test-suite/output/activation.v
  test-suite/output/bug_10824.v
  test-suite/output/bug_13018.v
  test-suite/output/bug_6764.v
  test-suite/output/bug_9180.v
  test-suite/output/bug_9682.v
  test-suite/output/lexical_convention_in_doc.out
  test-suite/output/lexical_convention_in_doc.v
  test-suite/output/locate.v
  theories/Corelib/Array/PrimArray.v
  theories/Corelib/ssr/ssrunder.v
  vernac/metasyntax.ml
Labels: kind: user messages, part: notations

#21169 [bench] Adapt to https://github.com/math-comp/math-comp/pull/1415
  dev/bench/bench.sh
Labels: kind: infrastructure, part: bench

#21154 Label some arguments of induction_gen
  tactics/induction.ml
Labels: kind: internal
